### ISSUE TITLE
pm2 monit crashes when using pm2 reload all

### ISSUE THREAD

**Issue by thomaschaaf** [Unitech/PM2#1002]
When I call "pm2 reload all" and have "pm2 monit" running in another window I get the following error:

```
/usr/local/lib/node_modules/pm2/lib/Monit.js:231
    this.bars[proc.pm_id].cpu.percent(0, proc.pm2_env.status.red);
                         ^
TypeError: Cannot read property 'cpu' of undefined
    at Object.Monit.updateBars (/usr/local/lib/node_modules/pm2/lib/Monit.js:231:26)
    at Object.Monit.refresh (/usr/local/lib/node_modules/pm2/lib/Monit.js:118:12)
    at /usr/local/lib/node_modules/pm2/lib/CLI.js:1231:13
    at /usr/local/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (events.js:107:17)
    at Parser._write (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Parser.Writable.write (_stream_writable.js:217:11)
```

System info
```
# node -v
v0.12.0
# pm2 -v
0.12.5
# uname -a
Linux komola-moonracer 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2+deb7u1 x86_64 GNU/Linux
```

**Comment by bwin** [comment]
This should be fixed in master.
