### ISSUE TITLE
Automatically all services shutdowned running in pm2

### ISSUE THREAD

**Issue by arun4san** [Unitech/PM2#1011]
Hi,
i have running around 15 services in aws using pm2. but yesterday automatically all services shutdowned in production server. i don't know what went wrong . please any one faced this issues.

Thanks,
Arun S

**Comment by fernandoneto** [comment]
can you give more informations (logs, etc) ?

**Comment by soyuka** [comment]
https://github.com/Unitech/PM2/blob/master/CONTRIBUTING.md

Everything we need is in there @arun4san please add more informations.

**Comment by arun4san** [comment]
I have add the log please give me one day time.I will share the log also..

**Comment by arun4san** [comment]
Hi ,

please check below the error log of pm2 ,


2015-02-12 08:19:30: App name:solarpulse_sunny_adapter id:11 online
2015-02-12 08:19:43: SyntaxError: Unexpected number
    at Object.parse (native)
    at Object.module.exports.serialize
(/usr/local/lib/node_modules/pm2/lib/Utility.js:23:17)
    at EventEmitter.interactionBroadcast
(/usr/local/lib/node_modules/pm2/lib/Satan.js:279:34)
    at EventEmitter.emit
(/usr/local/lib/node_modules/pm2/node_modules/eventemitter2/lib/eventemitter2.js:278:22)
    at Socket.forkOutData
(/usr/local/lib/node_modules/pm2/lib/God/ForkMode.js:126:17)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
2015-02-12 10:49:57: [PM2][WORKER] Started with refreshing interval: 30000
2015-02-12 10:49:57: [[[[ PM2/God daemon launched ]]]]
2015-02-12 10:49:57: BUS system [READY] on port /home/ubuntu/.pm2/pub.sock
2015-02-12 10:49:57: RPC interface [READY] on port
/home/ubuntu/.pm2/rpc.sock



On Tue, Feb 17, 2015 at 10:47 PM, Joni Shkurti <notifications@github.com>
wrote:

> Reopened #1011 <https://github.com/Unitech/PM2/issues/1011>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unitech/PM2/issues/1011#event-237081277>.
>



-- 
Thanks & Regards,
Arun Kumar S

**Comment by jshkurti** [comment]
It's fixed. Thanks for the feedback :)
