### ISSUE TITLE
TypeError when describing a process

### ISSUE THREAD

**Issue by catchdave** [Unitech/PM2#1013]
Similar error, but different line as https://github.com/Unitech/pm2/issues/423 and https://github.com/Unitech/PM2/issues/685

Using latest pm2 (v0.12.5).

When describing a process, a type error occurs.
e.g. `pm2 show 24`

```
Describing process with pid 24 - name BLAH
┌───────────────────┬────────────────────────────────────────────────┐
│ status            │ online                                         │
│ name              │ BLAH                           │
│ id                │ 24                                             │
│ path              │BLAH               │
│ args              │                                                │
│ exec cwd          │ BLAH                        │
│ error log path    │ BLAH               │
│ out log path      │ BLAH                 │
│ pid path          │ BLAH │
│ mode              │ cluster_mode                                   │
│ node v8 arguments │                                                │
│ watch & reload    │ ✘                                              │
│ interpreter       │ node                                           │
│ restarts          │ 0                                              │
│ unstable restarts │ 0                                              │
│ uptime            │ 28s                                            │
│ created at        │ 2015-02-14T00:50:50.109Z                       │
└───────────────────┴────────────────────────────────────────────────┘
Revision control metadata

/usr/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:182
      var contents = item.toString().split("\n").reduce(function (memo, l) {
                          ^
TypeError: Cannot call method 'toString' of undefined
    at /usr/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:182:27
    at Array.forEach (native)
    at generateRow (/usr/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:181:11)
    at /usr/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:275:16
    at Table.forEach (native)
    at Table.toString (/usr/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:258:10)
    at Object.UX.describeTable (/usr/lib/node_modules/pm2/lib/CliUx.js:96:24)
    at /usr/lib/node_modules/pm2/lib/CLI.js:1146:12
    at Array.forEach (native)
    at /usr/lib/node_modules/pm2/lib/CLI.js:1145:18
```

**Comment by MeisterRoerich** [comment]
I got the same error

**Comment by soyuka** [comment]
We're on it, this will be fixed soon ;).
Le sam. 14 févr. 2015 à 11:38, MeisterRoerich <notifications@github.com> a
écrit :

**Comment by Vijay-Bhaskar** [comment]
is the above error fixed?

**Comment by soyuka** [comment]
Is it closed ?

**Comment by jshkurti** [comment]
Fixed, thanks for the feedback :)
https://github.com/Unitech/PM2/commit/1627209ce511ce64b0c313dbadc620d8aed171da
