### ISSUE TITLE
pm2 describe gives Cannot call method 'toString' of undefined

### ISSUE THREAD

**Issue by joula** [Unitech/PM2#1028]
Here are the details:

/usr/local/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:182
      var contents = item.toString().split("\n").reduce(function (memo, l) {
                          ^
TypeError: Cannot call method 'toString' of undefined
    at /usr/local/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:182:27
    at Array.forEach (native)
    at generateRow (/usr/local/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:181:11)
    at /usr/local/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:275:16
    at Table.forEach (native)
    at Table.toString (/usr/local/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:258:10)
    at Object.UX.describeTable (/usr/local/lib/node_modules/pm2/lib/CliUx.js:96:24)
    at /usr/local/lib/node_modules/pm2/lib/CLI.js:1146:12
    at Array.forEach (native)
    at /usr/local/lib/node_modules/pm2/lib/CLI.js:1145:18

I installed PM2 with:

npm install git://github.com/Unitech/pm2#master -g

**Comment by joula** [comment]
Sorry, false alarm. When I executed "pm2 updatePM2" the above error disappeared.
