### ISSUE TITLE
Invalid protocol: git+http:

### ISSUE THREAD

**Issue by binarykitchen** [Unitech/PM2#1050]
When I install with `npmd` I get this error:

```
$ npmd install
GET https://registry.npmjs.org/express
GET https://registry.npmjs.org/nodemailer
GET https://registry.npmjs.org/chai
GET https://registry.npmjs.org/gulp-spawn-mocha

/opt/node-0.10.36/lib/node_modules/npmd/index.js:95
    if(err) throw err
                  ^
Error: package: pm2@0.12.6 could not resolve ikt@git+http://ikt.pm2.io/ikt.git#master
Invalid protocol: git+http:
    at Request.init (/opt/node-0.10.36/lib/node_modules/npmd/node_modules/npmd-cache/node_modules/request/request.js:591:31)
    at new Request (/opt/node-0.10.36/lib/node_modules/npmd/node_modules/npmd-cache/node_modules/request/request.js:264:8)
    at request (/opt/node-0.10.36/lib/node_modules/npmd/node_modules/npmd-cache/node_modules/request/index.js:50:10)
    at cache.getter (/opt/node-0.10.36/lib/node_modules/npmd/node_modules/npmd-cache/index.js:73:9)
    at fetch (/opt/node-0.10.36/lib/node_modules/npmd/node_modules/npmd-cache/node_modules/level-content-cache/index.js:108:7)
    at /opt/node-0.10.36/lib/node_modules/npmd/node_modules/npmd-cache/node_modules/level-content-cache/index.js:79:9
    at dispatchError (/opt/node-0.10.36/lib/node_modules/npmd/node_modules/levelup/lib/util.js:131:7)
    at /opt/node-0.10.36/lib/node_modules/npmd/node_modules/levelup/lib/levelup.js:197:14
    at /opt/node-0.10.36/lib/node_modules/npmd/node_modules/medeadown/medeadown.js:125:5
    at Medea.get (/opt/node-0.10.36/lib/node_modules/npmd/node_modules/medeadown/node_modules/medea/medea.js:472:13)

```

Any clues?

**Comment by fed135** [comment]
Install fails with npm as well.

pm2.io seems to be down at the moment.

Anyone on this ?

**Comment by binarykitchen** [comment]
Can you please fix this asap - it's affecting my sites, they are down :(

**Comment by Unitech** [comment]
Looks ok now, are you still affected by this?
This module is set as an [optional dependency](https://github.com/Unitech/PM2/blob/master/package.json#L181), it should not prevent pm2 to be installed

**Comment by binarykitchen** [comment]
By the way, I found out that I only see the above error when installing with the cool https://github.com/dominictarr/npmd tool. But when I do simply a `npm install` then it works.

**Comment by Unitech** [comment]
Everything need enhancements with time :)
