### ISSUE TITLE
Second gracefulReload in cluster mode doesn't working.

### ISSUE THREAD

**Issue by dharmesh-patel** [Unitech/PM2#1066]
I'm clearly doing something wrong: I'm using Ubuntu 12.04, NodeJS 0.12.0 and PM2 0.12.7 In cluster mode.

but the same thing happens with other version I tried (NodeJS 0.12.0 and PM2 0.12.4)

I follow these steps. I start pm2 like this

pm2 start app.js --name app --watch max_memory_restart 300M -i 0

it's working fine.

Now I gracefulReload my instance :

pm2 gracefulReload app

I am getting shudown message in nodejs everytime.

process.on('message', function(msg) {
    if (msg == 'shutdown') {
        console.log('Closing all connections...');
        gracefulShutdown('pm2 shutdown');
        console.log('skipped');
        setTimeout(function() {
            console.log('Finished closing connections');
            process.exit(0);
        }, 15000);
    }
});
and
[PM2] Reloading process by name app
[PM2] Process app succesfully reloaded
[PM2] Process app succesfully reloaded
[PM2] All processes reloaded

pm2.log

2015-03-03 17:13:02: Starting execution sequence in -cluster mode- for app name:app id:0
2015-03-03 17:13:03: App name:app id:0 online
2015-03-03 17:13:04: -reload- New worker listening
2015-03-03 17:13:04: -reload- Old worker disconnected
2015-03-03 17:13:04: Process with pid 11312 killed
2015-03-03 17:13:04: Starting execution sequence in -cluster mode- for app name:app id:1
2015-03-03 17:13:04: App name:app id:1 online
2015-03-03 17:13:06: -reload- New worker listening
2015-03-03 17:13:06: -reload- Old worker disconnected
2015-03-03 17:13:06: Process with pid 11323 killed

From second gracefulReload something happening wrong.

just getting
Closing all connections...

even not getting 
skipped

and start new process.

Let me know if there's any way to solved this issue.

**Comment by jshkurti** [comment]
I'm working on it :)

**Comment by jshkurti** [comment]
Are these your logs for the first or second gracefulReload ?
It looks like everything worked fine on these logs so I'm assuming it is the first gracefulReload (the one working).
Can you show us the logs for the second gracefulReload (the one not working proprerly) ?

**Comment by jshkurti** [comment]
I tried to reproduce the bug on my machine with this code but no luck, everything worked even after 3-4 gracefulReloads.
```
process.on('message', function(msg) {
  if (msg === 'shutdown') {
    console.log('Closing all connections...');
//    gracefulShutdown('pm2 shutdown');                                                                                                      
    console.log('skipped');
    setTimeout(function() {
      console.log('Finished closing connections');
      process.exit(0);
    }, 15000);
  }
});
```

**Comment by dharmesh-patel** [comment]
Hi jshkurti,

Thanks for your prompt reply.

After generate some logs I have found some errors.

when pm2 gracefulReload on timeout (default).

pm2 start app.js --name app --watch app.js max_memory_restart 300M -i 0

  process.on( 'message', function(msg)  {

        if (msg == 'shutdown') {
               console.log('Closing all connections...');
                var killtimer = setTimeout( function() {
                    console.log('FOREFULLY SHUTDOWN  %s', msg);
                    process.exit(1);
                }, 10 * 1000);

                killtimer.unref();

                redisClient.unref();

                ntMySQL.gracefullEnd(function(){
                    console.log('GRACEFUL MYSQL');
                });

                server.close(function(){
                    process.exit(1);
                });
            console.log('skipped');
        }
    });

Here Forcefully shutdown process in 10 secs.

Now,
pm2 gracefulReload app

[PM2] Reloading process by name app
[PM2] Process app succesfully reloaded
[PM2] Process app succesfully reloaded
[PM2] All processes reloaded

app-out-0.log 
-----------------

Closing all connections...
skipped
Got SIGTERM.  Press Control-D to exit.

app-error-0.log
---------------------

Error: channel closed
    at process.target.send (child_process.js:414:26)
    at SyncWriteStream.write (/usr/lib/node_modules/pm2/lib/ProcessContainer.js:140:17)
    at Console.log (console.js:55:16)
    at process.<anonymous> (/home/dharmesh/workspace/numbertank/app.js:1332:17)
    at process.emit (events.js:104:17)
    at Signal.wrap.onsignal (node.js:655:46)


at process.<anonymous> (/home/dharmesh/workspace/numbertank/app.js:1332:17)
uncaughtException on my nodejs appp


pm2.log
-------------------------

2015-03-04 12:11:02: Starting execution sequence in -cluster mode- for app name:app id:0
2015-03-04 12:11:02: App name:app id:0 online
2015-03-04 12:11:04: -reload- New worker listening
2015-03-04 12:11:12: -reload- Old worker disconnected
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: channel closed
    at process.target.send (child_process.js:414:26)
    at SyncWriteStream.write (/usr/lib/node_modules/pm2/lib/ProcessContainer.js:140:17)
    at Console.log (console.js:55:16)
    at process.<anonymous> (/home/dharmesh/workspace/numbertank/app.js:1384:17)
    at process.emit (events.js:129:20)
    at process._fatalException (node.js:236:26)
    at process.emit (events.js:107:17)
    at process.target.send (child_process.js:414:12)
    at SyncWriteStream.write (/usr/lib/node_modules/pm2/lib/ProcessContainer.js:140:17)
    at Console.log (console.js:55:16)
2015-03-04 12:11:12: Process with pid 5605 killed
2015-03-04 12:11:12: Starting execution sequence in -cluster mode- for app name:app id:1
2015-03-04 12:11:12: App name:app id:1 online
2015-03-04 12:11:13: -reload- New worker listening
2015-03-04 12:11:21: -reload- Old worker disconnected
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: channel closed
    at process.target.send (child_process.js:414:26)
    at SyncWriteStream.write (/usr/lib/node_modules/pm2/lib/ProcessContainer.js:140:17)
    at Console.log (console.js:55:16)
    at process.<anonymous> (/home/dharmesh/workspace/numbertank/app.js:1384:17)
    at process.emit (events.js:129:20)
    at process._fatalException (node.js:236:26)
    at process.emit (events.js:107:17)
    at process.target.send (child_process.js:414:12)
    at SyncWriteStream.write (/usr/lib/node_modules/pm2/lib/ProcessContainer.js:140:17)
    at Console.log (console.js:55:16)
2015-03-04 12:11:21: Process with pid 5616 killed


-------------------------------------------------------------------------------
If i decrease my FOREFULLY SHUTDOWN time to 1 sec,
-------------------------------------------------------------------------------

There is no error and working as expected.

app-out-0.log
------------------------

Server listening at port 3000
Closing all connections...
skipped
FOREFULLY SHUTDOWN shutdown

pm2.log
--------------------------

2015-03-04 12:22:49: Starting execution sequence in -cluster mode- for app name:app id:0
2015-03-04 12:22:49: App name:app id:0 online
2015-03-04 12:22:50: -reload- New worker listening
2015-03-04 12:22:51: -reload- Old worker disconnected
2015-03-04 12:22:51: Process with pid 5818 killed
2015-03-04 12:22:51: Starting execution sequence in -cluster mode- for app name:app id:1
2015-03-04 12:22:51: App name:app id:1 online
2015-03-04 12:22:53: -reload- New worker listening
2015-03-04 12:22:54: -reload- Old worker disconnected
2015-03-04 12:22:54: Process with pid 5829 killed

**Comment by jshkurti** [comment]
This should work by now (PM2 v0.12.13)
