### ISSUE TITLE
Long run process throw error on low memory

### ISSUE THREAD

**Issue by zhubofei** [Unitech/PM2#1105]
I got this error and the pm2 broke without restart

2015-03-18 15:55:24: ERROR CAUGHT BY DOMAIN:
Error: spawn ENOMEM
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1155:11)
    at exports.spawn (child_process.js:988:9)
    at Object.exports.execFile (child_process.js:682:15)
    at exports.exec (child_process.js:642:18)
    at getUrl (/usr/lib/node_modules/pm2/node_modules/vizion/lib/git.js:15:5)
    at fn (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:641:34)
    at Immediate._onImmediate (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
child_process.js:1155
    throw errnoException(err, 'spawn');
          ^
Error: spawn ENOMEM
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1155:11)
    at exports.spawn (child_process.js:988:9)
    at Object.exports.execFile (child_process.js:682:15)
    at exports.exec (child_process.js:642:18)
    at getUrl (/usr/lib/node_modules/pm2/node_modules/vizion/lib/git.js:15:5)
    at fn (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:641:34)
    at Immediate._onImmediate (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by jshkurti** [comment]
Hey, we can't do much about memory allocation errors but pm2 should have restarted.
Are you using PM2 v0.12.8 ?

**Comment by zhubofei** [comment]
Yes, I am using 0.12.8. PM2 didn't restart the app.

**Comment by zhubofei** [comment]
And Keymetrics showed the server was offline

**Comment by tUrG0n** [comment]
got the same error and pm2 behavior; it just won't restart. Any idea @jshkurti  ? :)
@zhubofei  did u manage to solve it?

**Comment by jshkurti** [comment]
Is your system out of memory ?

**Comment by tUrG0n** [comment]
oh my, yes!
![screen shot 2015-03-20 at 4 24 39 pm](https://cloud.githubusercontent.com/assets/753950/6754560/a713ab30-cf1d-11e4-98de-69cbaff8aecb.png)
Any idea why this is going on and how to prevent it? :)

**Comment by jshkurti** [comment]
Nothing anormal on your screenshot, the 902M is actually the virtual memory. It is not using that much.
But yeah 6.6% is quite high. Still not alarming yet.
Do you have other processes running on your machine susceptible to use a lot of memory ?

**Comment by tUrG0n** [comment]
i was worried abwt the 6.6% no the 902M

There was docker running and i fixed it. But i'm wondering why are the PM2 Daemon / Keymetrics consuming that much! Any idea?

**Comment by jshkurti** [comment]
I don't know actually.
On one of Keymetrics servers which is handling ~350 tcp requests/sec and a lot of apps and metricsdata and socket.io realtime stuff :
![km-memory](https://cloud.githubusercontent.com/assets/7647602/6755307/774e261e-cf22-11e4-87a0-2764dce7c3d1.png)

**Comment by tUrG0n** [comment]
My app is coffesscript based. Might that be the issue?

Also, my machine has 1G of ram. How much does the one in your example?

**Comment by zhubofei** [comment]
![screen shot 2015-03-20 at 12 00 16 pm](https://cloud.githubusercontent.com/assets/770482/6755365/f70eb546-cef8-11e4-9662-77e5709bf800.png)

**Comment by jshkurti** [comment]
```How much does the one in your example?```

120GB RAM and 16 cpus ^^

**Comment by tUrG0n** [comment]
well.. that's not fair now is as a comparison? :P
So yeah i guess it was the machine was getting out of memory caused by docker. I'll look into that. Thx guys :)

**Comment by jshkurti** [comment]
PM2 v0.12.16 is released. This bug shouldn't happen anymore. At least it won't crash PM2 if ENOMEM occurs.

https://github.com/Unitech/PM2/releases/tag/0.12.16
