### ISSUE TITLE
Starting with manifest only works after 3 tries

### ISSUE THREAD

**Issue by joshperry** [Unitech/pm2#1107]
![](https://www.dropbox.com/s/ugtvq721avki6ot/Screenshot%202015-03-18%2015.15.55.png?raw=1)

``` json
{
  "apps" : [
    {
      "name": "saidp",
      "script": "server/app.js",
      "cwd": "/opt/pdk/production/saidp/current",
      "run_as_user": "app",
      "exec_mode": "fork_mode",
      "env": {
        "NODE_ENV": "production",
        "PORT": "11234"
      }
    }
  ]
}
```

**Comment by jshkurti** [comment]
Hi Josh,
Can you please show us what happens in ```~/.pm2/pm2.log``` when this bug occurs ?
Thanks.

**Comment by joshperry** [comment]
Finally got some info on this issue. It looks like this problem is caused by log files with perms set incorrectly. I believe this happened when pm2 attempted to start the processes as root (not sure how that happened yet). PM2 start fails without an error when attempting to start the service, until it gets up to a process ID number for a log file that either doesn't exist, or has writable permissions.

At least bubbling this EACCESS error up to the user would be nice.

Here's pm2.log showing EACCESS errors:
```
2015-07-07 23:30:17: Starting execution sequence in -fork mode- for app name:saidp id:3
2015-07-07 23:30:17: Trace: { [Error: EACCES, open '/home/app/.pm2/logs/saidp-out-3.log']
  errno: 3,
  code: 'EACCES',
  path: '/home/app/.pm2/logs/saidp-out-3.log' }
    at Object.God.logAndGenerateError (/usr/lib64/node_modules/pm2/lib/God/Methods.js:30:15)
    at /usr/lib64/node_modules/pm2/lib/God/ForkMode.js:86:13
    at /usr/lib64/node_modules/pm2/node_modules/async/lib/async.js:49:16
    at /usr/lib64/node_modules/pm2/node_modules/async/lib/async.js:650:30
    at /usr/lib64/node_modules/pm2/node_modules/async/lib/async.js:1165:30
    at WriteStream.<anonymous> (/usr/lib64/node_modules/pm2/lib/Utility.js:107:13)
    at WriteStream.emit (events.js:95:17)
    at WriteStream.<anonymous> (fs.js:1669:12)
    at OpenReq.Req.done (/usr/lib64/node_modules/pm2/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (/usr/lib64/node_modules/pm2/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:63:22)
2015-07-07 23:30:29: Starting execution sequence in -fork mode- for app name:saidp id:4
2015-07-07 23:30:29: Trace: { [Error: EACCES, open '/home/app/.pm2/logs/saidp-out-4.log']
  errno: 3,
  code: 'EACCES',
  path: '/home/app/.pm2/logs/saidp-out-4.log' }
    at Object.God.logAndGenerateError (/usr/lib64/node_modules/pm2/lib/God/Methods.js:30:15)
    at /usr/lib64/node_modules/pm2/lib/God/ForkMode.js:86:13
    at /usr/lib64/node_modules/pm2/node_modules/async/lib/async.js:49:16
    at /usr/lib64/node_modules/pm2/node_modules/async/lib/async.js:650:30
    at /usr/lib64/node_modules/pm2/node_modules/async/lib/async.js:1165:30
    at WriteStream.<anonymous> (/usr/lib64/node_modules/pm2/lib/Utility.js:107:13)
    at WriteStream.emit (events.js:95:17)
    at WriteStream.<anonymous> (fs.js:1669:12)
    at OpenReq.Req.done (/usr/lib64/node_modules/pm2/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (/usr/lib64/node_modules/pm2/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:63:22)
2015-07-07 23:30:34: Starting execution sequence in -fork mode- for app name:saidp id:5
2015-07-07 23:30:34: App name:saidp id:5 online
```

Here are the perms on the log files:
```
-rw-r--r-- 1 app  app     59971 Jan 15 19:05 saidp-err-0.log
-rw-r--r-- 1 root root      449 Oct  2  2014 saidp-err-2.log
-rw-r--r-- 1 root root        0 Jul 30  2014 saidp-err-3.log
-rw-r--r-- 1 root root     3235 Sep  8  2014 saidp-err-4.log
-rw-r--r-- 1 app  app   2251074 Jun 25 00:48 saidp-error-5.log
-rw-r--r-- 1 app  app     49787 Jan 15 19:05 saidp-out-0.log
-rw-r--r-- 1 root root      577 Oct 14  2014 saidp-out-2.log
-rw-r--r-- 1 root root      417 Jul 30  2014 saidp-out-3.log
-rw-r--r-- 1 root root     9884 Sep 22  2014 saidp-out-4.log
-rw-r--r-- 1 app  app    202331 Jul  7 23:30 saidp-out-5.log
```
