### ISSUE TITLE
git config npm warning: Command failed: git config --get remote.origin.url

### ISSUE THREAD

**Issue by michaelBenin** [Unitech/PM2#1115]
Does PM2 need to have access to a git config to run correctly? 

````
npm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url
````

````
ubuntu@ip-xxx-xxx-xxx:~$ npm i pm2 -g
npm ERR! git config --get remote.origin.url
npm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:744:12)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:110:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:1008:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:1176:11)
npm WARN addRemoteGit     at Socket.emit (events.js:107:17)
npm WARN addRemoteGit     at Pipe.close (net.js:476:12)
npm WARN addRemoteGit  resetting remote /home/ubuntu/.npm/_git-remotes/http-ikt-pm2-io-ikt-git-58fd7291 because of error: { [Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }
npm WARN optional dep failed, continuing fsevents@0.3.5
/home/ubuntu/.nvm/versions/node/v0.12.0/bin/pm2 -> /home/ubuntu/.nvm/versions/node/v0.12.0/lib/node_modules/pm2/bin/pm2
pm2@0.12.8 /home/ubuntu/.nvm/versions/node/v0.12.0/lib/node_modules/pm2
├── ikt@0.0.0
├── json-stringify-safe@5.0.0
├── cli-table@0.3.1
├── eventemitter2@0.4.14
├── commander@2.6.0
├── pidusage@0.1.1
├── cron@1.0.5
├── async@0.9.0
├── debug@2.1.0 (ms@0.6.2)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── isbinaryfile@2.0.3
├── vizion@0.2.3
├── pm2-multimeter@0.1.2 (charm@0.1.2)
├── colors@1.0.3
├── pm2-deploy@0.1.2 (tv4@1.0.18)
├── semver@4.3.1
├── pm2-axon-rpc@0.3.6 (commander@1.0.5)
├── shelljs@0.3.0
├── pmx@0.3.5
├── nssocket@0.5.3 (lazy@1.0.11)
├── pm2-axon@2.0.8 (amp-message@0.1.2, escape-regexp@0.0.1, amp@0.3.1, configurable@0.0.1, debug@2.0.0)
├── chokidar@0.12.6 (async-each@0.1.6, readdirp@1.3.0)
├── coffee-script@1.8.0 (mkdirp@0.3.5)
├── pm2-logs@0.1.1 (chalk@0.4.0, pm2-interface@1.1.0, blessed@0.0.36)
└── moment@2.9.0
````

**Comment by jshkurti** [comment]
PM2 no. npm yes.
npm sometimes needs to fetch some modules via git :)

**Comment by michaelBenin** [comment]
Ah, thanks for the clarity.
