### ISSUE TITLE
Apps disappear from pm list but are still running.

### ISSUE THREAD

**Issue by albertjan** [Unitech/PM2#1150]
Start command:
```sh
root@test:~/api/jobs# pm2 start package.json
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
[PM2] Process launched
[PM2] Process launched
[PM2] Process launched
[PM2] Process launched
[PM2] Process launched
┌────────────────────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name                   │ id │ mode │ pid   │ status │ restart │ uptime │ memory      │ watching │
├────────────────────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ vragenlijstemail-generator │ 0  │ fork │ 15667 │ online │ 0       │ 1s     │ 25.098 MB   │  enabled │
│ antwoordlijst-generator    │ 1  │ fork │ 15668 │ online │ 0       │ 1s     │ 23.914 MB   │  enabled │
│ brieftekst-generator       │ 2  │ fork │ 15669 │ online │ 0       │ 1s     │ 20.926 MB   │  enabled │
│ hoofdstuk-generator        │ 3  │ fork │ 15670 │ online │ 0       │ 1s     │ 21.590 MB   │  enabled │
│ score-generator            │ 4  │ fork │ 15671 │ online │ 0       │ 1s     │ 20.816 MB   │  enabled │
└────────────────────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

After a while (list):

```sh
root@test:~/api/jobs# pm2 list
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬────────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ memory │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

But the nodes still run:

```sh
root@test:~/api/jobs# ps aux | grep node
root     12676  1.1  6.8 605444 34216 pts/2    S+   09:10   0:30 node /usr/local/bin/pm2 monit
root     15667  0.1 12.1 923936 61204 ?        Ssl  09:35   0:01 node /root/api/jobs/dist/continuous/vragenlijstemail-generator/run.js
root     15668  0.1 15.3 933044 77008 ?        Ssl  09:35   0:01 node /root/api/jobs/dist/continuous/antwoordlijst-generator/run.js
root     15669  0.1 13.7 926488 69060 ?        Ssl  09:35   0:02 node /root/api/jobs/dist/continuous/brieftekst-generator/run.js
root     15670  0.1 12.9 923992 64960 ?        Ssl  09:35   0:01 node /root/api/jobs/dist/continuous/hoofdstuk-generator/run.js
root     15671  0.1 13.9 926408 69832 ?        Ssl  09:35   0:02 node /root/api/jobs/dist/continuous/score-generator/run.js
root     17906  0.0  0.1  11740   936 pts/0    S+   09:54   0:00 grep --color=auto node
root@test:~/api/jobs#
```
Versions:

```sh
root@test:~/api/jobs# pm2 --version
0.12.9
root@test:~/api/jobs# node --version
v0.12.1
root@test:~/api/jobs# uname -a
Linux test 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jshkurti** [comment]
Hi,
Can you show us some ```~/.pm2/pm2.log``` please ?

**Comment by albertjan** [comment]
yes offcourse :smile:

```
2015-04-07 09:09:54: [PM2][WORKER] Started with refreshing interval: 30000
2015-04-07 09:09:54: [[[[ PM2/God daemon launched ]]]]
2015-04-07 09:09:54: BUS system [READY] on port /root/.pm2/pub.sock
2015-04-07 09:09:54: RPC interface [READY] on port /root/.pm2/rpc.sock
2015-04-07 09:10:03: Starting execution sequence in -fork mode- for app name:vragenlijstemail-generator id:0
2015-04-07 09:10:03: App name:vragenlijstemail-generator id:0 online
2015-04-07 09:10:04: Starting execution sequence in -fork mode- for app name:antwoordlijst-generator id:1
2015-04-07 09:10:04: App name:antwoordlijst-generator id:1 online
2015-04-07 09:10:04: Starting execution sequence in -fork mode- for app name:brieftekst-generator id:2
2015-04-07 09:10:04: App name:brieftekst-generator id:2 online
2015-04-07 09:10:04: Starting execution sequence in -fork mode- for app name:hoofdstuk-generator id:3
2015-04-07 09:10:04: App name:hoofdstuk-generator id:3 online
2015-04-07 09:10:04: Starting execution sequence in -fork mode- for app name:score-generator id:4
2015-04-07 09:10:04: App name:score-generator id:4 online
2015-04-07 09:34:51: [Watch] Stop watching 0
2015-04-07 09:34:51: Stopping app:vragenlijstemail-generator id:0
2015-04-07 09:34:51: App name:vragenlijstemail-generator id:0 exited with code SIGTERM
2015-04-07 09:34:51: [HandleExit] PM2 is being killed, stopping restart procedure...
2015-04-07 09:34:51: Process with pid 12591 killed
2015-04-07 09:34:51: [Watch] Stop watching 1
2015-04-07 09:34:51: Stopping app:antwoordlijst-generator id:1
2015-04-07 09:34:51: App name:antwoordlijst-generator id:1 exited with code SIGTERM
2015-04-07 09:34:51: [HandleExit] PM2 is being killed, stopping restart procedure...
2015-04-07 09:34:51: Process with pid 12592 killed
2015-04-07 09:34:51: [Watch] Stop watching 2
2015-04-07 09:34:51: Stopping app:brieftekst-generator id:2
2015-04-07 09:34:51: App name:brieftekst-generator id:2 exited with code SIGTERM
2015-04-07 09:34:51: [HandleExit] PM2 is being killed, stopping restart procedure...
2015-04-07 09:34:51: Process with pid 12593 killed
2015-04-07 09:34:51: [Watch] Stop watching 3
2015-04-07 09:34:51: Stopping app:hoofdstuk-generator id:3
2015-04-07 09:34:51: App name:hoofdstuk-generator id:3 exited with code SIGTERM
2015-04-07 09:34:51: [HandleExit] PM2 is being killed, stopping restart procedure...
2015-04-07 09:34:51: Process with pid 12596 killed
2015-04-07 09:34:51: [Watch] Stop watching 4
2015-04-07 09:34:51: Stopping app:score-generator id:4
2015-04-07 09:34:51: App name:score-generator id:4 exited with code SIGTERM
2015-04-07 09:34:51: [HandleExit] PM2 is being killed, stopping restart procedure...
2015-04-07 09:34:51: Process with pid 12599 killed
2015-04-07 09:34:52: PM2 is being killed via kill method
2015-04-07 09:34:52: RPC socket closed
2015-04-07 09:34:52: PUB socket closed
2015-04-07 09:35:58: [PM2][WORKER] Started with refreshing interval: 30000
2015-04-07 09:35:58: [[[[ PM2/God daemon launched ]]]]
2015-04-07 09:35:58: BUS system [READY] on port /root/.pm2/pub.sock
2015-04-07 09:35:58: RPC interface [READY] on port /root/.pm2/rpc.sock
2015-04-07 09:35:58: Starting execution sequence in -fork mode- for app name:vragenlijstemail-generator id:0
2015-04-07 09:35:58: App name:vragenlijstemail-generator id:0 online
2015-04-07 09:35:58: Starting execution sequence in -fork mode- for app name:antwoordlijst-generator id:1
2015-04-07 09:35:58: App name:antwoordlijst-generator id:1 online
2015-04-07 09:35:58: Starting execution sequence in -fork mode- for app name:brieftekst-generator id:2
2015-04-07 09:35:58: App name:brieftekst-generator id:2 online
2015-04-07 09:35:58: Starting execution sequence in -fork mode- for app name:hoofdstuk-generator id:3
2015-04-07 09:35:58: App name:hoofdstuk-generator id:3 online
2015-04-07 09:35:58: Starting execution sequence in -fork mode- for app name:score-generator id:4
2015-04-07 09:35:58: App name:score-generator id:4 online
2015-04-07 09:53:58: ERROR CAUGHT BY DOMAIN:
Error: spawn ENOMEM
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1155:11)
    at exports.spawn (child_process.js:988:9)
    at Object.exports.execFile (child_process.js:682:15)
    at exports.exec (child_process.js:642:18)
    at getUrl (/usr/local/lib/node_modules/pm2/node_modules/vizion/lib/git.js:15:5)
    at fn (/usr/local/lib/node_modules/pm2/node_modules/async/lib/async.js:641:34)
    at Immediate._onImmediate (/usr/local/lib/node_modules/pm2/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
child_process.js:1155
    throw errnoException(err, 'spawn');
          ^
Error: spawn ENOMEM
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1155:11)
    at exports.spawn (child_process.js:988:9)
    at Object.exports.execFile (child_process.js:682:15)
    at exports.exec (child_process.js:642:18)
    at getUrl (/usr/local/lib/node_modules/pm2/node_modules/vizion/lib/git.js:15:5)
    at fn (/usr/local/lib/node_modules/pm2/node_modules/async/lib/async.js:641:34)
    at Immediate._onImmediate (/usr/local/lib/node_modules/pm2/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
2015-04-07 09:54:54: [PM2][WORKER] Started with refreshing interval: 30000
2015-04-07 09:54:54: [[[[ PM2/God daemon launched ]]]]
2015-04-07 09:54:54: BUS system [READY] on port /root/.pm2/pub.sock
2015-04-07 09:54:54: RPC interface [READY] on port /root/.pm2/rpc.sock
```

**Comment by jshkurti** [comment]
Looks like PM2 ran out of memory :/

**Comment by albertjan** [comment]
I was afraid of something like that when I saw the `ENOMEM`. But it does restart how come pm2 doesn't pick them up again? It still has their pids right?

**Comment by albertjan** [comment]
it is running on fumes a bit:

```
             total       used       free     shared    buffers     cached
Mem:           490        432         57          0          6         35
-/+ buffers/cache:        391         98
Swap:            0          0          0
Total:         490        432         57
```

**Comment by karan** [comment]
Same thing happens to me. It seems like my app uses ~100MB of mem, but almost all of the rest is used by Ubuntu for caching. My understanding is that the cached mem is available for applications whenever. There should never be any instance when pm2 runs out of memory.

**Comment by icaliman** [comment]
This happens to me too. `~/.pm2/pm2.log` show same errors as for albertjan.

There are some updates on this?

**Comment by jshkurti** [comment]
@karan ```There should never be any instance when pm2 runs out of memory.```
We could close all apps when pm2 runs out of memory but isn't it better if your server keeps running even when PM2 dies ?

**Comment by jshkurti** [comment]
You can use ```pm2 install pm2-probe``` to monitor PM2's memory and cpu footprint.
On one of our biggest servers with Keymetrics back-end running on it, PM2 uses only 86MB and it stays still no matter how much load the server is having.

**Comment by onlyforart** [comment]
re >  isn't it better if your server keeps running even when PM2 dies

I would prefer to treat the loss of the management app (eg PM2) as a serious/fatal condition and would take that server out of fleet while the problem is investigated. Unmanaged apps are not to be relied on - they could crash later on and not be restarted and no-one would be any wiser. Turning a partial failure into a long drawn out unmonitored death. Far better to kill the whole thing, fix, and recover (having failed over to other servers in the interim).

Of course if they all start failing, that's a disaster of different proportions - but I am of the school of thought that says that the management app (eg PM2) cannot *ever* be allowed to fail (or if it does, it needs to be brought straight back up).

If the cause of the failures here is the process logging/monitoring functionality for Keymetrics, then in my opinion that should be carved out into it's own app that is run under the control of PM2 but that can be allowed to die without affecting uptime.

My model here is user-space tools like supervisord, which never fall over - and in my opinion the core PM2 daemon needs to be basically as reliable as a piece of the OS.

The slight unpredictability of node-forever is one of the main reasons we're moving away from using it. And node-forever does not fall over very often.

**Comment by jshkurti** [comment]
The PM2 crash mechanism has been enhanced a bit.
Now if PM2 runs out of memory it will dump the process list and kill all processes before exiting peacefully.
https://github.com/Unitech/PM2/blob/development/lib/Satan.js#L635-L655

Feel free to give it a try  : `npm i -g git://github.com/Unitech/PM2#development` :)

**Comment by albertjan** [comment]
@jshkurti thanks! :+1: 

might also be a good idea to mention adding swap to your machine.

**Comment by klinquist** [comment]
FYI I use the following Ansible script to add swap to my Amazon EC2 Ubuntu 14.04 Instances, this might help others too :)

- name: Create 1 gig swap file
  command: fallocate -l 1G /swapfile
  sudo: true
- name: Setting file permissions
  file: path=/swapfile mode=0600
  sudo: true
- name: Setup swap file
  command: mkswap /swapfile
  sudo: true
- name: Turn swap file on
  command: swapon /swapfile
  sudo: true
- name: Mounting in fstab
  lineinfile: dest=/etc/fstab  line="/swapfile   none    swap    sw    0   0"
  sudo: true

**Comment by jshkurti** [comment]
PM2 v0.12.16 is released. This bug shouldn't happen anymore. At least it won't crash PM2 if ENOMEM occurs.

https://github.com/Unitech/PM2/releases/tag/0.12.16

**Comment by Benew** [comment]
I got kinda the same problem but not related to memory: 
```
2015-12-21 06:25:26: Process with pid 2732 still not killed, retrying...
2015-12-21 06:25:26: Process with pid 2732 still not killed, retrying...
2015-12-21 06:25:26: Process with pid 2732 still not killed, retrying...
2015-12-21 06:25:26: Process with pid 2732 still not killed, retrying...
2015-12-21 06:25:26: Process with pid 2732 still alive after 1600ms, sending it SIGKILL now...
node.js:627
        throw errnoException(err, 'kill');
              ^
Error: kill ESRCH
    at exports._errnoException (util.js:746:11)
    at process.kill (node.js:627:15)
    at null._onTimeout (/usr/local/lib/node_modules/pm2/lib/God/Methods.js:216:17)
    at Timer.listOnTimeout (timers.js:110:15)
```

**Comment by Benew** [comment]
rel #1756 ?

**Comment by AayushSameerShah** [comment]
Okay, services are running, I can't see them... but now how to stop them? I want to restart all of them, but I can't because I can't stop them. I don't have their ids...
