### ISSUE TITLE
reload and gracefulReload kill processes too quickly (not 0s downtime)

### ISSUE THREAD

**Issue by pepkin88** [Unitech/pm2#1166]
I have a process initialized with this comand:

``` bash
NODE_ENV=production pm2 start app.js -i 1 --name "PituMenu" --node-args="--harmony" --log-date-format "\\[90\\m\\[YYYY-MM-DD HH:mm:ss.SSSZ\\]\\[39\\m"
```

Node version is: `v0.12.0`
PM2 version is: `0.12.10`

I'm gracefully reloading my process with these commands:

``` bash
export PM2_GRACEFUL_TIMEOUT=60000
export PM2_KILL_TIMEOUT=60000
pm2 gracefulReload "PituMenu"
```

`pm2 logs` prints this:

```
PM2: 2015-04-13 14:48:12: Starting execution sequence in -cluster mode- for app name:PituMenu id:0
PM2: 2015-04-13 14:48:12: App name:PituMenu id:0 online
PituMenu-0 (out): [2015-04-13 14:48:12.808+02:00]: 13 Apr 14:48:12 - Nodetime: Compilation or installation of native extention failed and precompiled package was not available or had no matching version. Please try the latest version of "nodetime". Alternatively, you can continue using Nodetime without the native extention, but will be missing several core features.
PituMenu-0 (out): [2015-04-13 14:48:16.507+02:00]: closing...
PM2: 2015-04-13 14:48:24: Stopping app:PituMenu id:_old_0
PituMenu-0 (err): [2015-04-13 14:48:24.597+02:00]: Process disconnected from parent !
PituMenu-0 (out): [2015-04-13 14:48:24.608+02:00]: closed
PM2: events.js:85
PM2:       throw er; // Unhandled 'error' event
PM2:             ^
PM2: Error: channel closed
PM2:   at process.target.send (child_process.js:414:26)
PM2:   at SyncWriteStream.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:144:17)
PM2:   at SyncWriteStream.obj.(anonymous function) [as write] (/srv/node_modules/nodetime/lib/core/proxy.js:45:19)
PM2:   at Console.log (console.js:55:16)
PM2:   at process.<anonymous> (/srv/pitumenu_prod/app.js:48:10)
PM2:   at process.emit (events.js:107:17)
PM2:   at process.exit (node.js:600:17)
PM2:   at process.uncaughtListener (/usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:174:17)
PM2:   at process.emit (events.js:107:17)
PM2:   at process._fatalException (node.js:236:26)
PM2:   at process.emit (events.js:107:17)
PM2:   at process.target.send (child_process.js:414:12)
PM2:   at SyncWriteStream.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:129:17)
PM2:   at SyncWriteStream.obj.(anonymous function) [as write] (/srv/node_modules/nodetime/lib/core/proxy.js:45:19)
PM2:   at Console.warn (console.js:63:16)
PM2:   at ipcSend (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/utils/transport.js:23:13)
PM2:   at Object.Transport.send (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/utils/transport.js:32:3)
PM2:   at [object Object].<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/Probe.js:59:17)
PM2:   at [object Object].wrapper [as _onTimeout] (timers.js:265:14)
PM2:   at Timer.listOnTimeout (timers.js:110:15)
PM2: 2015-04-13 14:48:24: Process with pid 26960 still not killed, retrying...
PM2: 2015-04-13 14:48:24: Process with pid 26960 still not killed, retrying...
PM2: 2015-04-13 14:48:24: Process with pid 26960 killed
PituMenu-0 (out): [2015-04-13 14:48:27.366+02:00]: Server started: 14659ms
```

Which means:
- 14:48:12.707 - new process is spawned (NodeTime warning is printed ~100ms after starting the app)
- 14:48:16.507 - old process gets the message 'shutdown' (prints 'closing...' and does nothing more)
- 14:48:24.597 - old process gets disconnected and killed by PM2 (PM2_GRACEFUL_TIMEOUT variable is disregarded)
- 14:48:27.366 - only now new process starts to listen on a TCP port

It is possible, that I messed something up with configuration. But if this is not the case, these are my conclusions:
- PM2 doesn't seem to be waiting for the 'listen' event
- PM2 waits only 4 seconds before it sends the 'shutdown' message to the old process
- PM2 waits only 8 seconds from sending the 'shutdown' message before it kills the old process
- PM2 doesn't seem to take into account the PM2_GRACEFUL_TIMEOUT nor PM2_KILL_TIMEOUT environment variables

**Comment by Unitech** [comment]
Issue fixed long time ago, 

New Graceful Stop system: http://pm2.keymetrics.io/docs/usage/signals-clean-restart/

```
$ npm install pm2@next -g
$ pm2 update
```
