### ISSUE TITLE
max-memory-restart problem

### ISSUE THREAD

**Issue by alsotang** [Unitech/PM2#1188]
when I use `max-memory-restart` option, and the app exceed the limitation.

pm2 would throw this error

```bash
cnode-0 (err): AssertionError: null == true
cnode-0 (err):   at process.target._send (child_process.js:402:5)
cnode-0 (err):   at process.<anonymous> (child_process.js:378:12)
cnode-0 (err):   at emitTwo (events.js:92:20)
cnode-0 (err):   at process.emit (events.js:169:7)
cnode-0 (err):   at handleMessage (child_process.js:306:10)
cnode-0 (err):   at Pipe.channel.onread (child_process.js:332:11)
```

**Comment by jshkurti** [comment]
Which versions of pm2 and node have you been using ? :)

**Comment by alsotang** [comment]
pm2 0.12.10 and iojs 1.5.0

**Comment by jshkurti** [comment]
Can you show some more logs please ? Let's say ```-n 150```

**Comment by alsotang** [comment]
Above logs is only meaningful log...others is some app error info..

2015-04-18 0:45 GMT+08:00 Joni Shkurti <notifications@github.com>:

**Comment by jshkurti** [comment]
I need to see what ```~/.pm2/pm2.log``` shows at the time when the bug happens.

**Comment by alsotang** [comment]
all related logs from `~/.pm2/pm2.log`

```
2015-04-17 14:55:09: [PM2][WORKER] Process 0 restarted because it exceeds --max-memory-restart value
2015-04-17 14:55:09: Stopping app:cnode id:0
2015-04-17 14:55:10: App name:cnode id:0 disconnected
2015-04-17 14:55:10: App name:cnode id:0 exited with code 100
2015-04-17 14:55:10: Process with pid 20089 killed
2015-04-17 15:03:16: [PM2][WORKER] Started with refreshing interval: 30000
2015-04-17 15:03:16: [[[[ PM2/God daemon launched ]]]]
2015-04-17 15:03:16: BUS system [READY] on port /home/safeuser/.pm2/pub.sock
2015-04-17 15:03:16: RPC interface [READY] on port /home/safeuser/.pm2/rpc.sock
2015-04-17 15:03:23: PM2 is being killed via kill method
2015-04-17 15:03:23: RPC socket closed
2015-04-17 15:03:23: PUB socket closed
2015-04-17 15:03:45: [PM2][WORKER] Started with refreshing interval: 30000
2015-04-17 15:03:45: [[[[ PM2/God daemon launched ]]]]
2015-04-17 15:03:45: BUS system [READY] on port /home/safeuser/.pm2/pub.sock
2015-04-17 15:03:45: RPC interface [READY] on port /home/safeuser/.pm2/rpc.sock
2015-04-17 15:03:45: Starting execution sequence in -cluster mode- for app name:cnode id:0
2015-04-17 15:03:45: App name:cnode id:0 online
2015-04-17 15:07:00: Stopping app:cnode id:0
2015-04-17 15:07:00: App name:cnode id:0 disconnected
2015-04-17 15:07:00: App name:cnode id:0 exited with code SIGTERM
2015-04-17 15:07:00: [HandleExit] PM2 is being killed, stopping restart procedure...
2015-04-17 15:07:00: Process with pid 570 killed
2015-04-17 15:07:00: PM2 is being killed via kill method
2015-04-17 15:07:00: RPC socket closed
2015-04-17 15:07:00: PUB socket closed
2015-04-17 15:07:20: [PM2][WORKER] Started with refreshing interval: 30000
2015-04-17 15:07:20: [[[[ PM2/God daemon launched ]]]]
2015-04-17 15:07:20: BUS system [READY] on port /home/safeuser/.pm2/pub.sock
2015-04-17 15:07:20: RPC interface [READY] on port /home/safeuser/.pm2/rpc.sock
2015-04-17 15:07:20: Starting execution sequence in -cluster mode- for app name:cnode id:0
2015-04-17 15:07:20: App name:cnode id:0 online
2015-04-17 15:09:43: Starting execution sequence in -cluster mode- for app name:cnode id:0
2015-04-17 15:09:44: App name:cnode id:0 online
2015-04-17 15:09:48: -reload- New worker listening
2015-04-17 15:09:48: Stopping app:cnode id:_old_0
2015-04-17 15:09:48: Process with pid 859 killed
2015-04-17 15:09:57: Stopping app:cnode id:0
2015-04-17 15:09:57: App name:cnode id:0 disconnected
2015-04-17 15:09:57: App name:cnode id:0 exited with code 100
2015-04-17 15:09:57: Process with pid 1085 killed
2015-04-17 15:10:14: [PM2][WORKER] Started with refreshing interval: 30000
2015-04-17 15:10:14: [[[[ PM2/God daemon launched ]]]]
2015-04-17 15:10:15: BUS system [READY] on port /home/safeuser/.pm2/pub.sock
2015-04-17 15:10:15: RPC interface [READY] on port /home/safeuser/.pm2/rpc.sock
2015-04-17 15:10:21: PM2 is being killed via kill method
2015-04-17 15:10:21: RPC socket closed
2015-04-17 15:10:21: PUB socket closed
2015-04-17 15:10:41: [PM2][WORKER] Started with refreshing interval: 30000
2015-04-17 15:10:41: [[[[ PM2/God daemon launched ]]]]
2015-04-17 15:10:41: BUS system [READY] on port /home/safeuser/.pm2/pub.sock
2015-04-17 15:10:41: RPC interface [READY] on port /home/safeuser/.pm2/rpc.sock
2015-04-17 15:10:42: Starting execution sequence in -cluster mode- for app name:cnode id:0
2015-04-17 15:10:42: App name:cnode id:0 online
```

**Comment by alsotang** [comment]
at that time, I remember some scene this bug happen

1. `pm2 reload appname`
2. when the app exceed memory limitation, and pm2 want to restart(or reload?) it

**Comment by gunish** [comment]
+1

**Comment by th507** [comment]
Same problem here.
PM2 hangs for 2 hours without properly resurrect its apps. (PM2 itself is running through.)

```
2015-04-30 06:42:27: Process with pid 2932 still not killed, retrying...
2015-04-30 06:42:27: Process with pid 2932 still not killed, retrying...
2015-04-30 06:42:27: Process with pid 2932 still not killed, retrying...
2015-04-30 06:42:27: Process with pid 2932 still not killed, retrying...
2015-04-30 06:42:27: App name:*** id:0 exited
2015-04-30 06:42:27: Process with pid 2932 killed
2015-04-30 09:03:06: [PM2][WORKER] Started with refreshing interval: 30000
2015-04-30 09:03:06: [[[[ PM2/God daemon launched ]]]]
```

**Comment by XadillaX** [comment]
```
2015-06-16 11:13:06: Starting execution sequence in -cluster mode- for app name:notification-dev id:1
2015-06-16 11:13:06: App name:notification-dev id:1 online
2015-06-16 11:13:07: -softReload- New worker listening
2015-06-16 11:13:07: Stopping app:notification-dev id:_old_1
2015-06-16 11:13:07: Process with pid 21558 still not killed, retrying...
2015-06-16 11:13:07: [PM2] Error caught by domain:
TypeError: Cannot read property 'apply' of undefined
    at ChildProcess.<anonymous> (cluster.js:692:7)
    at ChildProcess.emit (events.js:129:20)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)
2015-06-16 11:13:07: [PM2] Automatic `pm2 update` failed. Killing PM2 daemon and its processes...
2015-06-16 11:13:07: pm2 has been killed by signal, dumping process list before exit...
2015-06-16 11:13:07: Stopping app:notification-dev id:0
2015-06-16 11:13:07: Process with pid 21558 killed

assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: false == true
    at ChildProcess.<anonymous> (child_process.js:375:7)
    at ChildProcess.emit (events.js:129:20)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: channel closed
    at process.target.send (child_process.js:414:26)
    at SyncWriteStream.write (/opt/nvm/versions/node/v0.12.2/lib/node_modules/pm2/lib/ProcessContainer.js:157:17)
    at Console.log (console.js:55:16)
    at Logger.<anonymous> (/disk/ssd1/yupoo/app/her/notification/dev/node_modules/log4js/lib/appenders/console.js:8:5)
    at Logger.emit (events.js:129:20)
    at Logger.log (/disk/ssd1/yupoo/app/her/notification/dev/node_modules/log4js/lib/logger.js:58:10)
    at Logger.(anonymous function) [as error] (/disk/ssd1/yupoo/app/her/notification/dev/node_modules/log4js/lib/logger.js:77:30)
    at process.<anonymous> (/disk/ssd1/yupoo/app/her/notification/dev/bin/her-notification:5:13)
    at process.emit (events.js:129:20)
    at process._fatalException (node.js:236:26)
    at process.emit (events.js:107:17)
    at process.target.send (child_process.js:414:12)
    at sendHelper (cluster.js:676:8)
    at send (cluster.js:663:5)
    at Object.close (cluster.js:609:7)
    at Server.close (net.js:1374:18)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: channel closed
    at process.target.send (child_process.js:414:26)
    at SyncWriteStream.write (/opt/nvm/versions/node/v0.12.2/lib/node_modules/pm2/lib/ProcessContainer.js:157:17)
    at Console.log (console.js:55:16)
    at Logger.<anonymous> (/disk/ssd1/yupoo/app/her/notification/dev/node_modules/log4js/lib/appenders/console.js:8:5)
    at Logger.emit (events.js:129:20)
    at Logger.log (/disk/ssd1/yupoo/app/her/notification/dev/node_modules/log4js/lib/logger.js:58:10)
    at Logger.(anonymous function) [as error] (/disk/ssd1/yupoo/app/her/notification/dev/node_modules/log4js/lib/logger.js:77:30)
    at process.<anonymous> (/disk/ssd1/yupoo/app/her/notification/dev/bin/her-notification:5:13)
    at process.emit (events.js:129:20)
    at process._fatalException (node.js:236:26)
    at process.emit (events.js:107:17)
    at process.target.send (child_process.js:414:12)
    at sendHelper (cluster.js:676:8)
    at send (cluster.js:663:5)
    at Object.close (cluster.js:609:7)
    at Server.close (net.js:1374:18)
```

Same error. The PM2 daemon crashed.

**Comment by Unitech** [comment]
@jshkurti has fixed this with latest pm2 version

**Comment by XadillaX** [comment]
@Unitech can you show me which commit or commits? I wanna know the cause.

**Comment by Unitech** [comment]
@jshkurti

**Comment by alsotang** [comment]
great! https://cnodejs.org/ is already used the lastest pm2 version 0.14.3

2015-07-22 20:24 GMT+08:00 Alexandre Strzelewicz <notifications@github.com>:

**Comment by Unitech** [comment]
Awesome! :sake:

**Comment by sakshi-devotess** [comment]
**Title:** PM2 restarting Node.js workers due to high memory usage – need help identifying memory leak / root cause

Hi everyone,

I’m facing an issue where my Node.js application managed by PM2 keeps restarting workers due to exceeding the memory limit.

### 🔍 Problem

PM2 logs show frequent restarts like this:

```
[PM2][WORKER] Process X restarted because it exceeds --max-memory-restart value
(current_memory=2.7GB+ max_memory_limit=~2.3GB)
```

In some cases, memory usage goes up to **3.5GB+** before restart.
script: 'dist/main.js',
instances: 1,
max_memory_restart: '2200M',
exec_mode: 'cluster',
---

### ⚙️ Environment

* Node.js:
* PM2
* OS: Linux (64-bit)
* PM2 mode: Cluster (multiple workers) - 6 instance

---

### 🧠 Observations

* Multiple workers (2–6) are affected
* Memory usage keeps increasing over time
* Restart happens when memory crosses ~2.3GB (`--max-memory-restart`)
* Default Node heap (~2GB) seems exceeded in total RSS, so likely external/buffer memory is also involved

---

### ❓ What I need help with

1. How can I **identify the exact source of memory growth**?
2. Best way to analyze whether this is:

   * a memory leak (heap)
   * buffer/native memory issue
   * or heavy requests causing spikes
3. Recommended tools/workflow to debug in production (heap snapshots, profiling, etc.)

---

### 🧪 What I’ve tried

* Monitoring with `pm2 monit`
* Checking logs with `pm2 logs`
* Planning to use heap snapshots and `process.memoryUsage()`

---

### 🙏 Looking for guidance

If anyone has faced similar issues or can suggest a **step-by-step approach to pinpoint the leak/root cause**, that would be really helpful.

Thanks in advance!
