### ISSUE TITLE
pm2 start catch error and can't start successfull

### ISSUE THREAD

**Issue by jerrywu55** [Unitech/PM2#1198]
```
bbs.xxx.com-4 (out): Log file "/root/.pm2/logs/bbs.xxx.com-out-4.log" does not exist.
bbs.xxx.com-4 (err): Log file "/root/.pm2/logs/bbs.xxx.com-error-4.log" does not exist.
PM2:                       ^
PM2: Error: ENOENT, no such file or directory
PM2:     at Error (native)
PM2:     at Function.startup.resolveArgv0 (node.js:720:23)
PM2:     at startup (node.js:63:13)
PM2:     at node.js:814:3
PM2: 2015-04-20 17:41:35: App name:bbs.aiaiu.com id:4 disconnected
PM2: 2015-04-20 17:41:35: App name:bbs.aiaiu.com id:4 exited with code 1
PM2: 2015-04-20 17:41:35: Starting execution sequence in -cluster mode- for app name:bbs.xxx.com id:4
PM2: node.js:720
PM2:     var cwd = process.cwd();
PM2:                       ^
PM2: Error: ENOENT, no such file or directory
PM2:     at Error (native)
PM2:     at Function.startup.resolveArgv0 (node.js:720:23)
PM2:     at startup (node.js:63:13)
PM2:     at node.js:814:3
PM2: 2015-04-20 17:41:35: App name:bbs.xxx.com id:4 disconnected
PM2: 2015-04-20 17:41:35: App name:bbs.xxx.com id:4 exited with code 1
PM2: 2015-04-20 17:41:35: Script /data/www/bbs/xxx/index.js had too many unstable restarts (15). Stopped. "errored"
```

**Comment by jerrywu55** [comment]
pm2 -v 
0.12.11

**Comment by jerrywu55** [comment]
I use the nvm to install and manage nodejs

**Comment by jshkurti** [comment]
Is this bug recurrent ?

**Comment by jshkurti** [comment]
This happens sometimes when your node.js binary isn't called ```node``` but since you're using nvm I don't see any reason why it wouldn't

**Comment by Unitech** [comment]
This
```
PM2:     var cwd = process.cwd();
```
Means that something has been deleted, this is a edge case caused by bad usage, tell us if you get one more time this error under a conventional usage
