### ISSUE TITLE
pm2 v0.12.12 throwing error upon executing `pm2 logs`

### ISSUE THREAD

**Issue by shamasis** [Unitech/PM2#1206]
Downgrading to `0.12.11` fixes the same. This is happening inside a docker container, hence nothing has changed in the system.

Trace:
```
/usr/local/lib/node_modules/pm2/lib/CLI.js:1489
    var app_name = (proc.pm2_env.name || p.basename(proc.pm2_env.pm_exec_path)
                        ^
TypeError: Cannot read property 'pm2_env' of undefined
    at printLogs (/usr/local/lib/node_modules/pm2/lib/CLI.js:1489:25)
    at /usr/local/lib/node_modules/pm2/lib/CLI.js:1470:9
    at /usr/local/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (events.js:107:17)
    at Parser._write (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Parser.Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (_stream_readable.js:540:20)
```

**Comment by jshkurti** [comment]
Yes we know, it is fixed on 0.12.13. Coming soon :)
Thanks

**Comment by jshkurti** [comment]
I'm closing this for now. I'll let you know when the release is published ;)

**Comment by shamasis** [comment]
:+1: thanks.
