### ISSUE TITLE
Running pm2 logs gives error

### ISSUE THREAD

**Issue by michaelBenin** [Unitech/PM2#1207]
pm2 logs with v0.12.12 node version v0.12.0 

My start script:

````
{
  "apps": [
    {
      "name": "generic8888",
      "cwd": ".",
      "script": "app.js",
      "ignoreWatch": [
        "logs",
        "test",
        "static",
        "browser",
        "node_modules"
      ],
      "watch": [
        "app.js",
        "app",
        "config",
        "lib"
      ],
      "max_memory_restart" : "450M",
      "merge_logs": true,
      "log_file"   : "logs/pm2_child.log",
      "error_file" : "logs/pm2_error.log",
      "out_file"   : "logs/pm2_child_out.log",
      "exec_interpreter": "node",
      "env": {
        "NODE_ENV": "development"
      },
      "env_development": {
        "NODE_ENV": "development"
      }
    }
  ]
}
````

My start command:

    pm2 startOrRestart pm2/pm2_development.json

View logs command: 

    pm2 logs

Error output:

````
NYNYMBENINOXM:generic-node michael.benin$ pm2 logs
########### Starting streaming logs for [all] process
/Users/michael.benin/.nvm/versions/node/v0.12.0/lib/node_modules/pm2/lib/CLI.js:1489
    var app_name = (proc.pm2_env.name || p.basename(proc.pm2_env.pm_exec_path)
                        ^
TypeError: Cannot read property 'pm2_env' of undefined
    at printLogs (/Users/michael.benin/.nvm/versions/node/v0.12.0/lib/node_modules/pm2/lib/CLI.js:1489:25)
    at /Users/michael.benin/.nvm/versions/node/v0.12.0/lib/node_modules/pm2/lib/CLI.js:1470:9
    at /Users/michael.benin/.nvm/versions/node/v0.12.0/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/Users/michael.benin/.nvm/versions/node/v0.12.0/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (events.js:107:17)
    at Parser._write (/Users/michael.benin/.nvm/versions/node/v0.12.0/lib/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Parser.Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (_stream_readable.js:540:20)
````

**Comment by jshkurti** [comment]
https://github.com/Unitech/PM2/issues/1206

In the meantime you can go back to 0.12.11 `npm i -g pm2@0.12.11` or get the latest development version `npm i -g git://github.com/Unitech/PM2#development`.
Sorry for the inconvenience again.

**Comment by michaelBenin** [comment]
Hey no problem!

I go it working by running the log command before starting the process. 

I'll revert down to 0.12.11.

Thank you.

**Comment by michaelBenin** [comment]
Closing for #1206
