### ISSUE TITLE
Error: channel closed

### ISSUE THREAD

**Issue by rabbitfufu** [Unitech/PM2#1215]
Using PM2 in cluster mode in production on Node 0.12.1.

The application runs fine, however I am seeing the following error periodically in the logs:

```
Error: channel closed
    at process.target.send (child_process.js:414:26)
    at SyncWriteStream.write (/home/project/.nvm/versions/node/v0.12.1/lib/node_modules/pm2/lib/ProcessContainer.js:144:17)
    at Array.logRequest (/home/project/node_modules/express/node_modules/connect/node_modules/morgan/index.js:126:14)
    at listener (/home/project/node_modules/express/node_modules/connect/node_modules/morgan/node_modules/on-finished/index.js:164:15)
    at onFinish (/home/project/node_modules/express/node_modules/connect/node_modules/morgan/node_modules/on-finished/index.js:95:5)
    at callback (/home/project/node_modules/express/node_modules/connect/node_modules/morgan/node_modules/on-finished/node_modules/ee-first/index.js:33:10)
    at ServerResponse.onevent (/home/project/node_modules/express/node_modules/connect/node_modules/morgan/node_modules/on-finished/node_modules/ee-first/index.js:66:5)
    at ServerResponse.emit (events.js:129:20)
    at finish (_http_outgoing.js:521:10)
    at process._tickCallback (node.js:355:11)
```

Any suggestions as to what might be happening / how I can fix this?

**Comment by jshkurti** [comment]
Are you using an old version of PM2 ?

**Comment by rabbitfufu** [comment]
0.12.9

**Comment by jshkurti** [comment]
This was fixed on recent versions.
I suggest you to `npm i -g pm2@latest` ;)

**Comment by rabbitfufu** [comment]
Thanks!
