### ISSUE TITLE
Weird Error

### ISSUE THREAD

**Issue by tUrG0n** [Unitech/PM2#1266]
Hey guys,

I'm getting this error:
```
PM2: Error: spawn ENOMEM
PM2:     at exports._errnoException (util.js:746:11)
PM2:     at ChildProcess.spawn (child_process.js:1155:11)
PM2:     at exports.spawn (child_process.js:988:9)
PM2:     at Object.exports.execFile (child_process.js:682:15)
PM2:     at exports.exec (child_process.js:642:18)
PM2:     at getUrl (/usr/local/lib/node_modules/pm2/node_modules/vizion/lib/git.js:15:5)
PM2:     at fn (/usr/local/lib/node_modules/pm2/node_modules/async/lib/async.js:641:34)
PM2:     at Immediate._onImmediate (/usr/local/lib/node_modules/pm2/node_modules/async/lib/async.js:557:34)
PM2:     at processImmediate [as _immediateCallback] (timers.js:358:17)
PM2: 2015-05-13 07:22:18: [PM2][WORKER] Started with refreshing interval: 30000
PM2: 2015-05-13 07:22:18: [[[[ PM2/God daemon launched ]]]]
PM2: 2015-05-13 07:22:18: BUS system [READY] on port /root/.pm2/pub.sock
PM2: 2015-05-13 07:22:18: RPC interface [READY] on port /root/.pm2/rpc.sock
PM2: 2015-05-13 07:22:49: Starting execution sequence in -fork mode- for app name:watson id:0
PM2: 2015-05-13 07:22:49: App name:watson id:0 online
PM2: 2015-05-13 07:22:49: Starting execution sequence in -fork mode- for app name:twitter id:1
PM2: 2015-05-13 07:22:49: App name:twitter id:1 online
```

Does that mean that my machine was running out of memory?

**Comment by jshkurti** [comment]
Yep, it does.
Or at least PM2 daemon was refused memory allocation when it tried to use the child_process.spawn() method.
If this becomes really a problem you can start your app with `--no-vizion` flag.

**Comment by tUrG0n** [comment]
what does the `--no-vizion` flag do?

**Comment by jorge-d** [comment]
It disables [Vizion](https://github.com/keymetrics/vizion) from pm2 :)

**Comment by tUrG0n** [comment]
ok thanks guys :)  @jorge-d  @jshkurti  <3

**Comment by jshkurti** [comment]
PM2 v0.12.16 is released. This bug shouldn't happen anymore. At least it won't crash PM2 if ENOMEM occurs.

https://github.com/Unitech/PM2/releases/tag/0.12.16
