### ISSUE TITLE
pm2 suddenly kill my process

### ISSUE THREAD

**Issue by roysG** [Unitech/PM2#1302]
Please assist me,
 if you need some addition info, let me know.

OS : ubuntu 64 bit

**Comment by jshkurti** [comment]
Yes please show me some `~/.pm2/pm2.log` lines at around the time your process is suddenly killed.

**Comment by roysG** [comment]
2015-05-19 04:06:17: App name:prto id:0 exited with code 143
2015-05-19 04:06:17: Process with pid 7892 killed
2015-05-19 04:07:13: [Watch] Stop watching 0
2015-05-19 04:08:09: Starting execution sequence in -fork mode- for app name:pro id:1
2015-05-19 04:08:10: App name:pro id:1 online
2015-05-20 15:04:43: Starting execution sequence in -fork mode- for app name:app id:2
2015-05-20 15:04:43: App name:app id:2 online
2015-05-21 06:58:31: App name:app id:2 exited with code SIGKILL
2015-05-21 06:58:31: Starting execution sequence in -fork mode- for app name:app id:2
2015-05-21 06:58:31: App name:app id:2 online
2015-05-21 10:25:41: Stopping app:pro id:1
2015-05-21 10:25:41: App name:pro id:1 exited with code 143
2015-05-21 10:25:41: Process with pid 8008 killed
2015-05-21 10:25:52: Starting execution sequence in -fork mode- for app name:pro id:1
2015-05-21 10:25:52: App name:pro id:1 online
2015-05-21 10:25:59: Stopping app:app id:2
2015-05-21 10:25:59: App name:app id:2 exited with code 143
2015-05-21 10:25:59: Process with pid 11986 killed
2015-05-21 10:29:25: Starting execution sequence in -fork mode- for app name:app id:2
2015-05-21 10:29:25: App name:app id:2 online
2015-05-21 10:29:34: Stopping app:app id:2
2015-05-21 10:29:34: App name:app id:2 exited with code 143
2015-05-21 10:29:34: Process with pid 1715 killed
2015-05-21 10:29:34: Starting execution sequence in -fork mode- for app name:app id:2
2015-05-21 10:29:34: App name:app id:2 online
2015-05-21 14:05:37: Stopping app:app id:2
2015-05-21 14:05:37: App name:app id:2 exited with code 143
2015-05-21 14:05:37: Process with pid 1745 killed
2015-05-21 14:05:37: Starting execution sequence in -fork mode- for app name:app id:2
2015-05-21 14:05:37: App name:app id:2 online
2015-05-21 14:07:40: Stopping app:app id:2
2015-05-21 14:07:41: App name:app id:2 exited with code 143
2015-05-21 14:07:41: Process with pid 21025 killed
2015-05-22 16:52:29: Starting execution sequence in -fork mode- for app name:app id:2
2015-05-22 16:52:29: App name:app id:2 online
2015-05-23 00:53:43: Stopping app:app id:2
2015-05-23 00:53:43: App name:app id:2 exited with code 143
2015-05-23 00:53:43: Process with pid 14793 killed
2015-05-23 00:53:43: Starting execution sequence in -fork mode- for app name:app id:2
2015-05-23 00:53:43: App name:app id:2 online
2015-05-23 01:40:34: Stopping app:app id:2
2015-05-23 01:40:34: App name:app id:2 exited with code 143
2015-05-23 01:40:34: Process with pid 6141 killed
2015-05-23 06:45:39: Starting execution sequence in -fork mode- for app name:app id:2
2015-05-23 06:45:39: App name:app id:2 online

child_process.js:958
    throw errnoException(process._errno, 'spawn');
          ^
Error: spawn ENOMEM
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at exports.spawn (child_process.js:746:9)
    at Object.exports.execFile (child_process.js:628:15)
    at exports.exec (child_process.js:591:18)
    at getUrl (/usr/lib/node_modules/pm2/node_modules/vizion/lib/git.js:17:5)
    at fn (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
2015-05-23 07:41:17: [PM2][WORKER] Started with refreshing interval: 30000
2015-05-23 07:41:17: [[[[ PM2/God daemon launched ]]]]
2015-05-23 07:41:17: BUS system [READY] on port /root/.pm2/pub.sock
2015-05-23 07:41:17: RPC interface [READY] on port /root/.pm2/rpc.sock
2015-05-24 05:12:22: Starting execution sequence in -fork mode- for app name:app id:0
2015-05-24 05:12:22: App name:app id:0 online



Let me know if you need more info.

**Comment by roysG** [comment]
this is happend again !
A few minutes ago

  at Object.exports.execFile (child_process.js:628:15)
    at exports.exec (child_process.js:591:18)
    at getUrl (/usr/lib/node_modules/pm2/node_modules/vizion/lib/git.js:17:5)
    at fn (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
2015-05-27 11:08:37: [PM2][WORKER] Started with refreshing interval: 30000
2015-05-27 11:08:37: [[[[ PM2/God daemon launched ]]]]
2015-05-27 11:08:37: BUS system [READY] on port /root/.pm2/pub.sock
2015-05-27 11:08:37: RPC interface [READY] on port /root/.pm2/rpc.sock

**Comment by jshkurti** [comment]
Well it just mean your machine is running out of memory (ENOMEM).
How much RAM do you got ?

For now, a solution would be to start your apps with `--no-vizion` flag (`vizion: false` in JSON declaration).
We're are going to do something about it soon.

**Comment by roysG** [comment]
i reinstall pm2 and check if maybe this will fix the problem, cause i ran for long time this process and everything was ok, in the previous version.

i update you.

and about the --nu-vizion, what does it do exactly ?

**Comment by jshkurti** [comment]
`vizion` is the module used to get metadata about your versioning (git/svn/mercurial).
When you start a process, PM2 will execute a vizion.parse() of your app folder to grab some metadatas about the repository (if there is one). You can see those metadatas with `pm2 desc <id>`.
Then, every 30seconds a worker will be executed which refreshes these metadatas.
vizion.parse() uses child_process.spawn() at some point to execute some git commands and the ENOMEN error happens here.

**Comment by gdraganic** [comment]
Encountered the same problem on pm2@0.12.14. It's very frustrating so I'm thinking to downgrade, but what is the last version that does not have this issue?

**Comment by roysG** [comment]
yee i am also frustrating, i think i move to forever

**Comment by jshkurti** [comment]
The real issue is your server running out of memory.
PM2 memory footprint is ridiculously small. PM2 v0.12.16 (which is going to be published today) will take about 20MB when empty and around 40MB with a lot of applications running.

@roysG because it's `--no-vizion` instead of `--nu-vizion`.

If you launch all your apps with `--no-vizion` flag (`vizion : false` in json declaration) this error won't happen again.

**Comment by jshkurti** [comment]
Nevertheless I'm going to reduce even more the memory footprint of spawn() which seems to trigger the error here and think about a workaround so PM2 would never crash even when there is no more memory avaible.

**Comment by jshkurti** [comment]
Here we go. PM2 v0.12.16 is released. This bug shouldn't happen anymore. At least it won't crash PM2 if ENOMEM occurs.

https://github.com/Unitech/PM2/releases/tag/0.12.16
