### ISSUE TITLE
PM2 clustered mode laod balancing issue

### ISSUE THREAD

**Issue by dhirendragupta** [Unitech/pm2#1311]
I have Node-v0.12.04 and pm2-v0.12.15

I am running the pm2 in cluster mode with 4 clusters 
sudo pm2 start app.js --name myapp -i max

Now I am running a jmeter script which has 100 threads and 1 sec ramp up time forever. 
Before reload everything works fine. When I ran
sudo pm2 reload myapp

Around 100 of request gets failed. I think loadbalancer is not able to balance the request which are coming on the clustered process which is reloading. I am getting errors "server is not able to respond" and there are around 100 request failed error while reload. Please help me as soon as possible.

Error which one I am getting in the response is:
org.apache.http.NoHttpResponseException: The target server failed to respond
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:95)
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:61)
    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:254)
    at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:289)
    at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:252)
    at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:191)
    at org.apache.jmeter.protocol.http.sampler.MeasuringConnectionManager$MeasuredConnection.receiveResponseHeader(MeasuringConnectionManager.java:201)
    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:300)
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:127)
    at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:715)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:520)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
    at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.executeRequest(HTTPHC4Impl.java:517)
    at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:331)
    at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:74)
    at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1146)
    at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1135)
    at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:434)
    at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:261)
    at java.lang.Thread.run(Thread.java:745)

Sampler Result::

Thread Name: Thread Group 1-41
Sample Start: 2015-05-27 19:50:17 IST
Load time: 1112
Connect Time: 0
Latency: 0
Size in bytes: 2068
Headers size in bytes: 0
Body size in bytes: 2068
Sample Count: 1
Error Count: 1
Response code: Non HTTP response code: org.apache.http.NoHttpResponseException
Response message: Non HTTP response message: The target server failed to respond

Response headers:

HTTPSampleResult fields:
ContentType: 
DataEncoding: null

**Comment by dhirendragupta** [comment]
I have Node-v0.12.04 and pm2-v0.12.15

**Comment by jshkurti** [comment]
That's pretty normal. `reload` will kill the instance immediately and thus the requests being handled by that instance will fail.
Try `pm2 gracefulReload` instead.
`gracefulReload` will send a 'shutdown' signal to the process and give it 8 seconds (by default, but you can change that by setting PM2_GRACEFUL_TIMEOUT (in milliseconds) env variable when you launch the app) to gracefully exit.

You can catch the signal this way :
```javascript
process.on('message', function(message) {
  if (message === 'shutdown') {
    server.close();
    wait_for_all_requests_to_finish();
    process.exit(0);
  }
});
```

**Comment by dhirendragupta** [comment]
With pm2 gracefulReload I am getting error as following: 

org.apache.http.NoHttpResponseException: localhost:5000 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:197)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:284)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:62)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1075)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1064)
	at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:426)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:255)
	at java.lang.Thread.run(Thread.java:745)

**Comment by dhirendragupta** [comment]
One more thing I read about pm2 is it has cluster load balancing feature. If one of the worker of the cluster is reloading then why not pm2 is transferring request to other available worker. Is there any functionality in pm2 by which the request to the reloading worker gets transferred to another available or running worker?

**Comment by dhirendragupta** [comment]
I have also tried PM2_GRACEFUL_TIMEOUT=30000 before running pm2 gracefulReload myApp. Even after this I am getting same error as mentioned above.

**Comment by jshkurti** [comment]
But, did you put the piece of code that I gave you above in your own code ?
`gracefulReload` is pointless if you don't.

Try it this way :
```javascript

process.on('message', function(message) {
  if (message === 'shutdown') {
    server.close(); // when server is your http/tcp server handle
    setTimeout(function() {
      process.exit(0);
    }, 6000);
  }
});
```

**Comment by jshkurti** [comment]
Oh, no need to say, launch your process with several instances : `pm2 start app.js -i 8` for example

**Comment by dhirendragupta** [comment]
Yes I did add above code at the end of the app.js which I use to run.

**Comment by dhirendragupta** [comment]
Also tried it adding that code here
.
.
.
/**
 * Ignore self-signed certificates with RESTLER.
 * @type {string}
 */
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

//new code
process.on('message', function(message) {
  if (message === 'shutdown') {
    server.close(); // stop accepting new requests from this point
    wait_for_all_requests_to_finish();
    process.exit(0);
  }
});
//new code ends

var cluster = require('cluster');
var os = require('os');

if ( options.localCluster ) {
    console.log("Starting a local cluster...");
    if (cluster.isMaster) {
        for (var i = 0, n = os.cpus().length ; i < n; i += 1 ) {
            cluster.fork();
        }
    } else {
        appStart();
    }
} else {
    console.log("Starting a single instance...");
    appStart();
}

function appStart() {
    app.use(compress);

//    console.log(fs.readFileSync('/Users/rusne001/.ssh/testkey.pem').toString());

    var httpsOptions = {
//        pfx: fs.readFileSync('server.pfx'),
//        key: fs.readFileSync('keys/key.pem'),
/*
        key: fs.readFileSync('/Users/rusne001/.ssh/server-key.rsa'),
        cert: fs.readFileSync('/Users/rusne001/.ssh/server-cert.pem')
*/

    };

    app.listen(9000);
    console.log('Application started and listening on port 9000');    
}

And getting errors as follows:

org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:95)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:61)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:254)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:289)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:252)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:191)
	at org.apache.jmeter.protocol.http.sampler.MeasuringConnectionManager$MeasuredConnection.receiveResponseHeader(MeasuringConnectionManager.java:201)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:300)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:127)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:715)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:520)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.executeRequest(HTTPHC4Impl.java:517)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:331)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:74)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1146)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1135)
	at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:434)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:261)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Unitech** [comment]
Issue fixed long time ago,

New Graceful Stop system: http://pm2.keymetrics.io/docs/usage/signals-clean-restart/

```
$ npm install pm2@next -g
$ pm2 update
```
