### ISSUE TITLE
Can't run `pm2-dev` with `next-gen-js`

### ISSUE THREAD

**Issue by xpepermint** [Unitech/PM2#1315]
I was excited when I saw `--next-gen-js` flag in the docs but running 
```
$ pm2-dev run test/index.js --next-gen-js
```
gives me this
```
Error: To run next generation Javascript you need to run PM2 with io.js
    at resolvePaths (/Users/me/.nvm/versions/v0.12.2/lib/node_modules/pm2/lib/CLI.js:1955:11)
    at /Users/me/.nvm/versions/v0.12.2/lib/node_modules/pm2/lib/CLI.js:161:28
    at /Users/me/.nvm/versions/v0.12.2/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/Users/me/.nvm/versions/v0.12.2/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (events.js:107:17)
    at Parser._write (/Users/me/.nvm/versions/v0.12.2/lib/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Parser.Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (_stream_readable.js:540:20)
```

Using `pm2 0.12.15`, `node 0.12.2`.

**Comment by jshkurti** [comment]
`Error: To run next generation Javascript you need to run PM2 with io.js`

**Comment by xpepermint** [comment]
Yeah... I saw that but I `--interpreter` option doesn't work for me :(.

**Comment by xpepermint** [comment]
Ow... `npm install pm2 -g` wasn't enough I had to install it like `npm install pm2@latest -g`.

**Comment by vbalas6** [comment]
[PM2][ERROR] script not found : /var/lib/jenkins/jobs/pulse-api/io.js
