### ISSUE TITLE
error starting pm2 in cluster mode in windows

### ISSUE THREAD

**Issue by prashantbaid** [Unitech/pm2#1368]
I am getting an error while starting pm2 in cluster mode.
I ran this command - `pm2 start <filename> -i 4`
Only one instance gets created. 
I am using Windows 7, Node 0.12.0 and pm2 0.14.0

This is my error log

2015-06-18 10:10:54: [PM2][WORKER] Started with refreshing interval: 30000
2015-06-18 10:10:54: [[[[ PM2/God daemon launched ]]]]
2015-06-18 10:10:54: BUS system [READY] on port \\.\pipe\pub.sock
2015-06-18 10:10:54: RPC interface [READY] on port \\.\pipe\rpc.sock
2015-06-18 10:10:54: Starting execution sequence in -cluster mode- for app name:server id:0
2015-06-18 10:10:54: App name:server id:0 online
2015-06-18 10:10:54: Starting execution sequence in -cluster mode- for app name:server id:1
2015-06-18 10:10:54: Trace: { [Error: spawn EBADF] code: 'EBADF', errno: 'EBADF', syscall: 'spawn' }
    at Object.God.logAndGenerateError (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God\Methods.js:30:15)
    at Object.nodeApp (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God\ClusterMode.js:52:11)
    at Object.executeApp (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God.js:145:9)
    at ex (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God.js:361:18)
    at C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God.js:365:16
    at Worker.cluOnline (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God.js:188:17)
    at Worker.g (events.js:199:16)
    at Worker.emit (events.js:104:17)
    at online (cluster.js:449:12)
    at Worker.onmessage (cluster.js:436:7)
2015-06-18 10:10:54: Starting execution sequence in -cluster mode- for app name:server id:2
2015-06-18 10:10:54: Trace: { [Error: spawn EBADF] code: 'EBADF', errno: 'EBADF', syscall: 'spawn' }
    at Object.God.logAndGenerateError (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God\Methods.js:30:15)
    at Object.nodeApp (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God\ClusterMode.js:52:11)
    at Object.executeApp (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God.js:145:9)
    at ex (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God.js:361:18)
    at C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God.js:362:25
    at nodeApp (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God.js:146:29)
    at Object.nodeApp (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God\ClusterMode.js:53:14)
    at Object.executeApp (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God.js:145:9)
    at ex (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God.js:361:18)
    at C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God.js:365:16
2015-06-18 10:10:54: Starting execution sequence in -cluster mode- for app name:server id:3
2015-06-18 10:10:54: Trace: { [Error: spawn EBADF] code: 'EBADF', errno: 'EBADF', syscall: 'spawn' }
    at Object.God.logAndGenerateError (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God\Methods.js:30:15)
    at Object.nodeApp (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God\ClusterMode.js:52:11)
    at Object.executeApp (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God.js:145:9)
    at ex (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God.js:361:18)
    at C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God.js:362:25
    at nodeApp (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God.js:146:29)
    at Object.nodeApp (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God\ClusterMode.js:53:14)
    at Object.executeApp (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God.js:145:9)
    at ex (C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God.js:361:18)
    at C:\Users\pbaid\AppData\Roaming\npm\node_modules\pm2\lib\God.js:362:25

**Comment by Tjatse** [comment]
joyent/node#3779

**Comment by keeganmccallum** [comment]
+1

**Comment by matthieu-vincke** [comment]
Same problem Windows 7, Node v0.12.6 (64 bits) and pm2 0.14.3 (works fine with option --no-daemon as mentioned in the previous post)

2015-07-13 07:52:35: Starting execution sequence in -cluster mode- for app name:app id:1
2015-07-13 07:52:35: Trace: { [Error: spawn EBADF] code: 'EBADF', errno: 'EBADF', syscall: 'spawn' }
    at Object.God.logAndGenerateError (....\node_modules\pm2\lib\God\Methods.js:30:15)
    at Object.nodeApp (....\node_modules\pm2\lib\God\ClusterMode.js:52:11)
    at Object.executeApp (....\node_modules\pm2\lib\God.js:145:9)
    at ex (....\node_modules\pm2\lib\God.js:361:18)
    at ....\node_modules\pm2\lib\God.js:365:16
    at Worker.cluOnline (....\node_modules\pm2\lib\God.js:188:17)
    at Worker.g (events.js:199:16)
    at Worker.emit (events.js:104:17)
    at online (cluster.js:449:12)
    at Worker.onmessage (cluster.js:436:7)

**Comment by crkepler** [comment]
+1
Same error on Node 0.12.0
pm2 0.14.6
Windows 7 64 bits

<precode>
2015-08-08 03:16:00: [PM2][WORKER] Started with refreshing interval: 30000
2015-08-08 03:16:00: [[[[ PM2/God daemon launched ]]]]
2015-08-08 03:16:00: BUS system [READY] on port \\.\pipe\pub.sock
2015-08-08 03:16:00: RPC interface [READY] on port \\.\pipe\rpc.sock
2015-08-08 03:16:05: Starting execution sequence in -cluster mode- for app name:api-test-server id:0
2015-08-08 03:16:05: App name:api-test-server id:0 online
2015-08-08 03:16:05: Starting execution sequence in -cluster mode- for app name:api-test-server id:1
2015-08-08 03:16:05: <strong>Trace: { [Error: spawn EBADF] code: 'EBADF', errno: 'EBADF', syscall: 'spawn' }
    at Object.God.logAndGenerateError (C:\Users\rk\AppData\Roaming\npm\node_modules\pm2\lib\God\Methods.js:30:15)</strong>
    at Object.nodeApp (C:\Users\rk\AppData\Roaming\npm\node_modules\pm2\lib\God\ClusterMode.js:52:11)
    at Object.executeApp (C:\Users\rk\AppData\Roaming\npm\node_modules\pm2\lib\God.js:145:9)
    at ex (C:\Users\rk\AppData\Roaming\npm\node_modules\pm2\lib\God.js:367:18)
    at C:\Users\rk\AppData\Roaming\npm\node_modules\pm2\lib\God.js:371:16
    at Worker.cluOnline (C:\Users\rk\AppData\Roaming\npm\node_modules\pm2\lib\God.js:188:17)
    at Worker.g (events.js:199:16)
    at Worker.emit (events.js:104:17)
    at online (cluster.js:449:12)
    at Worker.onmessage (cluster.js:436:7)
</precode>

**Comment by Tjatse** [comment]
It seems `cluster.fork()` failed. If this happens any time, try to make sure it's a bug of `node.js` on a specific Windows Ver. by running:
```js
var cluster = require('cluster');
var numCPUs = require('os').cpus().length;

if (cluster.isMaster) {
  for (var i = 0; i < numCPUs; i++) {
    cluster.fork();
  }

  cluster.on('exit', function(worker, code, signal) {
    console.log('worker ' + worker.process.pid + ' died');
  });
} else {
  console.log('worker ' + process.pid + ' is online...');
}
```

**Comment by crkepler** [comment]
+1
Same error on Node 0.12.0
pm2 0.14.6
Windows 7 64 bits

<precode>
2015-08-08 03:16:00: [PM2][WORKER] Started with refreshing interval: 30000
2015-08-08 03:16:00: [[[[ PM2/God daemon launched ]]]]
2015-08-08 03:16:00: BUS system [READY] on port \\.\pipe\pub.sock
2015-08-08 03:16:00: RPC interface [READY] on port \\.\pipe\rpc.sock
2015-08-08 03:16:05: Starting execution sequence in -cluster mode- for app name:api-test-server id:0
2015-08-08 03:16:05: App name:api-test-server id:0 online
2015-08-08 03:16:05: Starting execution sequence in -cluster mode- for app name:api-test-server id:1
2015-08-08 03:16:05: <strong>Trace: { [Error: spawn EBADF] code: 'EBADF', errno: 'EBADF', syscall: 'spawn' }
    at Object.God.logAndGenerateError (C:\Users\rk\AppData\Roaming\npm\node_modules\pm2\lib\God\Methods.js:30:15)</strong>
    at Object.nodeApp (C:\Users\rk\AppData\Roaming\npm\node_modules\pm2\lib\God\ClusterMode.js:52:11)
    at Object.executeApp (C:\Users\rk\AppData\Roaming\npm\node_modules\pm2\lib\God.js:145:9)
    at ex (C:\Users\rk\AppData\Roaming\npm\node_modules\pm2\lib\God.js:367:18)
    at C:\Users\rk\AppData\Roaming\npm\node_modules\pm2\lib\God.js:371:16
    at Worker.cluOnline (C:\Users\rk\AppData\Roaming\npm\node_modules\pm2\lib\God.js:188:17)
    at Worker.g (events.js:199:16)
    at Worker.emit (events.js:104:17)
    at online (cluster.js:449:12)
    at Worker.onmessage (cluster.js:436:7)
</precode>

**Comment by Vega-ne** [comment]
+1
Same error on
`Node v0.12.7`
`pm2 v0.14.6`
`Windows 7 64-bit`

Works fine when running with --no-daemon. Also running an app with cluster works fine as well (not using pm2).

```
2015-08-10 16:55:51: Starting execution sequence in -cluster mode- for app name:main id:3
2015-08-10 16:55:51: Trace: { [Error: spawn EBADF] code: 'EBADF', errno: 'EBADF', syscall: 'spawn' }
    at Object.God.logAndGenerateError (C:\Users\foobar\AppData\Roaming\npm\node_modules\pm2\lib\God\Methods.js:30:15)
    at Object.nodeApp (C:\Users\foobar\AppData\Roaming\npm\node_modules\pm2\lib\God\ClusterMode.js:52:11)
    at Object.executeApp (C:\Users\foobar\AppData\Roaming\npm\node_modules\pm2\lib\God.js:145:9)
    at ex (C:\Users\foobar\AppData\Roaming\npm\node_modules\pm2\lib\God.js:367:18)
    at C:\Users\foobar\AppData\Roaming\npm\node_modules\pm2\lib\God.js:368:25
    at nodeApp (C:\Users\foobar\AppData\Roaming\npm\node_modules\pm2\lib\God.js:146:29)
    at Object.nodeApp (C:\Users\foobar\AppData\Roaming\npm\node_modules\pm2\lib\God\ClusterMode.js:53:14)
    at Object.executeApp (C:\Users\foobar\AppData\Roaming\npm\node_modules\pm2\lib\God.js:145:9)
    at ex (C:\Users\foobar\AppData\Roaming\npm\node_modules\pm2\lib\God.js:367:18)
    at C:\Users\foobar\AppData\Roaming\npm\node_modules\pm2\lib\God.js:368:25
```

**Comment by djordjelacmanovic** [comment]
+1
Same error on :
pm2 v0.14.7, node v0.12.6, Windows 8.1 64bit

exactly the same logs as with @Vega-ne 's

**Comment by McFarts** [comment]
Same here issue, any fix?

**Comment by Alex-Werner** [comment]
Same issue here. 
Win 10 64 bits

**Comment by lopesc** [comment]
+1.  Windows 7 Enterprise 64bit.  Node v0.12.5.  I have an app running in cluster mode and have deployed new production code.  On reload, this happens:

```
C:\Users\lopesc\MyApp> pm2 reload myapp
[PM2] Reloading process by name myapp
Error: spawn EBADF
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at exports.spawn (child_process.js:995:9)
    at exports.fork (child_process.js:581:10)
    at createWorkerProcess (cluster.js:320:12)
    at EventEmitter.cluster.fork (cluster.js:334:25)
    at Object.nodeApp (C:\Users\lopesc\AppData\Roaming\npm\node_modules\pm2\lib
\God\ClusterMode.js:50:21)
    at Object.executeApp (C:\Users\lopesc\AppData\Roaming\npm\node_modules\pm2\
lib\God.js:145:9)
    at hardReload (C:\Users\lopesc\AppData\Roaming\npm\node_modules\pm2\lib\God
\Reload.js:125:7)
    at God.reloadProcessId (C:\Users\lopesc\AppData\Roaming\npm\node_modules\pm
2\lib\God\Reload.js:194:14)
C:\Users\lopesc\MyApp>
```

Code isn't picked up either.

**Comment by Unitech** [comment]
Could someone try the PM2 development version, there are some Windows fixes

```
$ npm install Unitech/pm2#development -g
$ pm2 update
```

**Comment by dwelle** [comment]
@Unitech no dice, problems persists after installing the dev (at least for me).

**Comment by DavidBenko** [comment]
+1 same issue on 2008 RC2

**Comment by puncha** [comment]
This is definitely an issue of nodejs 0.12.x. Could you notice this in the README.md or somewhere else to avoid more people wasting time on this issue?

**Comment by vmarchaud** [comment]
Work great with latest version of pm2 : `pm2@next` !
