### ISSUE TITLE
child_process.execSync() in cluster mode crashes pm2 logs

### ISSUE THREAD

**Issue by xiaody** [Unitech/PM2#1391]
I'm on OSX 10.10.3 and using io.js v2.3.1 and pm2@0.14.2

Reproduce:
`pm2 --no-daemon start test.json`

The config file `test.json`:
```json
{
  "apps" : [{
    "name"               : "test",
    "script"             : "tmp/test.js",
    "exec_interpreter"   : "node",
    "exec_mode"          : "cluster_mode",
    "instances"          : 1
  }]
}
```

The app `tmp/test.js`:
```js
'use strict'
setInterval(function () {
    console.log('run `echo`')
    require('child_process').execSync('echo')
}, 200)
```

The output:
```
➜  paidui git:(master) ✗ pm2 --no-daemon start test.json
pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
2015-06-26 11:42:07: [PM2][WORKER] Started with refreshing interval: 30000
2015-06-26 11:42:07: [[[[ PM2/God daemon launched ]]]]
2015-06-26 11:42:07: BUS system [READY] on port /Users/xiaody/.pm2/pub.sock
2015-06-26 11:42:07: RPC interface [READY] on port /Users/xiaody/.pm2/rpc.sock
2015-06-26 11:42:07: Starting execution sequence in -cluster mode- for app name:test id:0
2015-06-26 11:42:07: App name:test id:0 online
2015-06-26 11:42:07: [PM2] Process launched
2015-06-26 11:42:07: ┌──────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name │ id │ mode    │ pid   │ status │ restart │ uptime │ memory      │ watching │
├──────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ test     │ 0  │ cluster │ 70723 │ online │ 0       │ 0s     │ 20.816 MB   │ disabled │
└──────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────────────┴──────────┘
2015-06-26 11:42:07:  Use `pm2 show <id|name>` to get more details about an app
2015-06-26 11:42:07: --no-daemon option enabled = do not exit pm2 CLI
2015-06-26 11:42:07: PM2 daemon PID = 70710
2015-06-26 11:42:07: [PM2] Tailing last 1 lines for [all] processes

PM2: 2015-06-26 11:42:07: 2015-06-26 11:41:54: PUB socket closed

test-0 (err): 2015-06-26 11:42:07: IPC channel with master closed

test-0 (out): 2015-06-26 11:42:07: run `echo`

2015-06-26 11:42:07: [PM2] Streaming realtime logs for [all] processes

test-0 run `echo`
test-0 net.js:614
    throw new TypeError('invalid data');
          ^
TypeError: invalid data
    at WriteStream.Socket.write (net.js:614:11)
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Log.js:96:22)
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/sub-emitter.js:52:19)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser._write (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:291:12)
    at writeOrBuffer (_stream_writable.js:277:5)
    at Parser.Writable.write (_stream_writable.js:206:11)
    at Socket.ondata (_stream_readable.js:521:20)
➜  paidui git:(master) ✗
```

**Comment by Tjatse** [comment]
The `process.stdout.write` in `io.js` only accept `String` argument.
Currently it's an object like `{type: 'Buffer', data: []}`. @jshkurti

**Comment by xiaody** [comment]
See https://github.com/nodejs/io.js/blob/master/lib/child_process.js#L471
execSync() write some `Buffer` data but after being passed between processes, the data is no longer a Buffer (`Buffer.isBuffer() --> false`) (see also https://github.com/joyent/node/issues/5727)
And finally the io.js socket refuse to write it https://github.com/nodejs/io.js/blob/master/lib/net.js#L613

**Comment by jshkurti** [comment]
`npm i -g Unitech/PM2#development` does this fix it ? :)

**Comment by jshkurti** [comment]
It does actually, I just tested.
Thanks for reporting this :)
