### ISSUE TITLE
can't start webservice with pm2

### ISSUE THREAD

**Issue by linayanse** [Unitech/pm2#1405]
i'm using nunjucks rendering templates.
Error: template not found: error.html
   at null.<anonymous> (F:\workspace\p33_wzksywx\Web\node_modules\nunjucks\src\environment.js:151:31)
   at next (F:\workspace\p33_wzksywx\Web\node_modules\nunjucks\src\lib.js:201:13)
   at handle (F:\workspace\p33_wzksywx\Web\node_modules\nunjucks\src\environment.js:136:25)
   at F:\workspace\p33_wzksywx\Web\node_modules\nunjucks\src\environment.js:147:21
   at next (F:\workspace\p33_wzksywx\Web\node_modules\nunjucks\src\lib.js:198:13)
   at Object.exports.asyncIter (F:\workspace\p33_wzksywx\Web\node_modules\nunjucks\src\lib.js:205:5)
   at Obj.extend.getTemplate (F:\workspace\p33_wzksywx\Web\node_modules\nunjucks\src\environment.js:130:17)
   at Obj.extend.render (F:\workspace\p33_wzksywx\Web\node_modules\nunjucks\src\environment.js:211:14)
   at NunjucksView.render (F:\workspace\p33_wzksywx\Web\node_modules\nunjucks\src\environment.js:193:15)
   at Function.app.render (F:\workspace\p33_wzksywx\Web\node_modules\express\lib\application.js:527:10)

**Comment by vmarchaud** [comment]
This error doesnt have any link with pm2 as you can read in the trace.
