### ISSUE TITLE
npm install pm2@latest -g  install errors (appears to be related to git repos)

### ISSUE THREAD

**Issue by MikeCaspar** [Unitech/PM2#1430]
current pm2 version : 0.14.3
node : 0.12.6 (have also tried 0.12.7)
ubuntu 14.04 (64 bit)  3.13.0-52-generic

```
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/home/deploy/.nvm/versions/node/v0.12.6/lib/node_modules/npm/node_modules/which/which.js:72:28)
npm WARN addRemoteGit     at E (/home/deploy/.nvm/versions/node/v0.12.6/lib/node_modules/npm/node_modules/which/which.js:75:29)
npm WARN addRemoteGit     at /home/deploy/.nvm/versions/node/v0.12.6/lib/node_modules/npm/node_modules/which/which.js:83:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:95:15)
npm WARN addRemoteGit  git+http://ikt.pm2.io/ikt.git#master resetting remote /home/deploy/.npm/_git-remotes/http-ikt-pm2-io-ikt-git-4d23bf0d because of error: { [Error: not found: git] code: 'ENOGIT' }
npm ERR! git clone --template=/home/deploy/.npm/_git-remotes/_templates --mirror http://ikt.pm2.io/ikt.git /home/deploy/.npm/_git-remotes/http-ikt-pm2-io-ikt-git-4d23bf0d: undefined
npm ERR! git clone --template=/home/deploy/.npm/_git-remotes/_templates --mirror http://ikt.pm2.io/ikt.git /home/deploy/.npm/_git-remotes/http-ikt-pm2-io-ikt-git-4d23bf0d: undefined
npm WARN optional dep failed, continuing ikt@git+http://ikt.pm2.io/ikt.git#master
npm WARN optional dep failed, continuing fsevents@0.3.6
/home/deploy/.nvm/versions/node/v0.12.6/bin/pm2 -> /home/deploy/.nvm/versions/node/v0.12.6/lib/node_modules/pm2/bin/pm2
/home/deploy/.nvm/versions/node/v0.12.6/bin/pm2-dev -> /home/deploy/.nvm/versions/node/v0.12.6/lib/node_modules/pm2/bin/pm2-dev
pm2@0.14.3 /home/deploy/.nvm/versions/node/v0.12.6/lib/node_modules/pm2
├── is-iojs@1.1.0
├── isbinaryfile@2.0.4
├── eventemitter2@0.4.14
├── pidusage@0.1.1
├── safe-clone-deep@1.0.5
├── colors@1.1.0
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── debug@2.2.0 (ms@0.7.1)
├── pm2-multimeter@0.1.2 (charm@0.1.2)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── semver@4.3.6
├── shelljs@0.5.1
├── pm2-deploy@0.1.2 (tv4@1.0.18, async@0.9.2)
├── pm2-axon-rpc@0.3.6 (json-stringify-safe@5.0.1, commander@1.0.5)
├── cli-table@0.3.1 (colors@1.0.3)
├── vizion@0.2.11 (async@0.9.0)
├── pm2-axon@2.0.8 (amp-message@0.1.2, escape-regexp@0.0.1, amp@0.3.1, configurable@0.0.1, debug@2.0.0)
├── nssocket@0.5.3 (lazy@1.0.11)
├── coffee-script@1.9.3
├── async@1.2.1
├── pm2-logs@0.1.1 (json-stringify-safe@5.0.1, chalk@0.4.0, blessed@0.0.36, pm2-interface@1.1.0)
├── pmx@0.3.20 (json-stringify-safe@5.0.1)
├── chokidar@1.0.3 (arrify@1.0.0, path-is-absolute@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, is-binary-path@1.0.1, readdirp@1.3.0, anymatch@1.3.0)
├── cron@1.0.9 (moment-timezone@0.3.1)
├── moment@2.10.3
└── babel@5.6.14 (slash@1.0.0, path-is-absolute@1.0.0, path-exists@1.0.0, fs-readdir-recursive@0.1.2, convert-source-map@1.1.1, output-file-sync@1.1.1, source-map@0.4.3, glob@5.0.13, lodash@3.10.0, babel-core@5.6.17)
deploy@mona:~$

**Comment by Unitech** [comment]
It has been installed, the optionnal module (requiring) just failed but does not impact the installation of pm2
