### ISSUE TITLE
Ugly error on invalid JSON syntax

### ISSUE THREAD

**Issue by dandv** [Unitech/PM2#1440]
If I forgot a comma in ecosystem.json, pm2 will die with this horrible error:

```sh
$ pm2 start /home/dandv/idr/ecosystem.json5

/usr/lib/node_modules/pm2/lib/CLI.js:2300
    return vm.runInNewContext(code, sandbox, filename);
              ^
SyntaxError: Unexpected identifier
    at parseConfig (/usr/lib/node_modules/pm2/lib/CLI.js:2300:15)
    at Object.CLI._startJson (/usr/lib/node_modules/pm2/lib/CLI.js:283:15)
    at Object.CLI.start (/usr/lib/node_modules/pm2/lib/CLI.js:91:9)
    at Command.commander.command.option.option.option.option.option.description.action.line (/usr/lib/node_modules/pm2/bin/pm2:205:11)
    at Command.listener (/usr/lib/node_modules/pm2/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:98:17)
    at Command.parseArgs (/usr/lib/node_modules/pm2/node_modules/commander/index.js:610:12)
    at Command.parse (/usr/lib/node_modules/pm2/node_modules/commander/index.js:458:21)
    at beginCommandProcessing (/usr/lib/node_modules/pm2/bin/pm2:116:13)
    at commander.command.option.option.option.option.option.description.action.line (/usr/lib/node_modules/pm2/bin/pm2:169:7)
```

**Comment by kodamirmo** [comment]
+1

**Comment by dandv** [comment]
This is better now. The error message is "[PM2][ERROR] File ecosystem.config.js malformated".

Still, that should be "malformed" :)
