### ISSUE TITLE
pm2 startup throws an error on windows platform

### ISSUE THREAD

**Issue by adasq** [Unitech/PM2#1441]
As described at https://nodejs.org/api/process.html#process_process_getuid,
process.getuid method does not exsists on windows platform. That's why using pm2's startup feature throws an error.

`
C:\Users\Alucard\AppData\Roaming\npm\node_modules\pm2\lib\CLI.js:559
  if (process.getuid() != 0) {
              ^
TypeError: Object #<process> has no method 'getuid'
    at Object.CLI.startup (C:\Users\Alucard\AppData\Roaming\npm\node_modules\pm2\lib\CLI.js:559:15)
    at Command.commander.command.option.option.option.option.option.description.action.line (C:\Users\Alucard\AppData\Roaming\npm\node_modules\pm2\bin\pm2:476:9)
    at Command.listener (C:\Users\Alucard\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:301:8)
    at Command.EventEmitter.emit (events.js:98:17)
    at Command.parseArgs (C:\Users\Alucard\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:610:12)
    at Command.parse (C:\Users\Alucard\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:458:21)
    at beginCommandProcessing (C:\Users\Alucard\AppData\Roaming\npm\node_modules\pm2\bin\pm2:116:13)
    at commander.command.option.option.option.option.option.description.action.line (C:\Users\Alucard\AppData\Roaming\npm\node_modules\pm2\bin\pm2:169:7)
    at null._onTimeout (C:\Users\Alucard\AppData\Roaming\npm\node_modules\pm2\lib\Satan.js:454:19)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
`

pm2 v.0.14.3
node v.0.10.26
windows v.8.1

**Comment by soyuka** [comment]
#1079
