### ISSUE TITLE
PM2 crashes under load

### ISSUE THREAD

**Issue by artursudnik** [Unitech/pm2#1458]
Hi,

Everytime I perform load test, pm2 crashes and application list (pm2 list) is empty after that.

excerpt from logs:

`2015-07-23 11:39:54: [PM2][WORKER] Error caught by domain:
TypeError: Cannot read property 'addListener' of undefined
    at Object.exports.execFile (child_process.js:788:15)
    at exports.exec (child_process.js:649:18)
    at getMeta (/usr/lib/node_modules/pm2/node_modules/vizion/lib/git.js:30:5)
    at fn (/usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:641:34)
    at Immediate._onImmediate (/usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn /bin/sh EMFILE
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at Immediate._tickDomainCallback [as _onImmediate] (node.js:381:11)
    at processImmediate [as _immediateCallback] (timers.js:367:17)`

**Comment by soyuka** [comment]
Temporary fix: `pm2 start --no-vizion` to disable it.

@jshkurti any ideas on this?

**Comment by artursudnik** [comment]
Seems it helped. What this option is?

**Comment by soyuka** [comment]
To disable vizion.

**Comment by jshkurti** [comment]
http://blog.izs.me/post/56827866110/wtf-is-emfile-and-why-does-it-happen-to-me

**Comment by parisholley** [comment]
ditto, my ulimit is already at 64000, bumping up, but this shouldn't crash all the workers, disabled with CLI for now.

**Comment by kanongil** [comment]
I found an `EMFILE` issue that I reported in #1501 that might be related to this.
