### ISSUE TITLE
startup command suggestion is misleading and may cause problems later

### ISSUE THREAD

**Issue by bragma** [Unitech/PM2#1460]
Hi,
suppose that, after installing pm2, I run "pm2 startup systemd". This suggests me to execute a command:

```
#pm2 startup systemd
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
[PM2] You have to run this command as root. Execute the following command:
      sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u user
```

Now, the suggested command works correctly only because I already ran pm2 and this created a .pm2 folder owned by user "user". But if the folder does not exist (because I deleted it, because I execute the command on another machine or after install I execute the command directly) this gets me into trouble because it will create a ".pm2" folder owned by root in the home of "user".

As an example:

```
# rm -rf .pm2
```

This will remove my .pm2 if it is present. Now, to the problem:

```
# sudo env PATH=$PATH:/usr/bin pm2 startup ubuntu -u user
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
[PM2] Generating system init script in /etc/init.d/pm2-init.sh
[PM2] Making script booting at startup...
[PM2] -ubuntu- Using the command:
      su -c "chmod +x /etc/init.d/pm2-init.sh && update-rc.d pm2-init.sh defaults"

[PM2] Done.
```

This seems to have worked correctly, but:

```
# ls -la | grep .pm2
drwxr-xr-x   4 root  root   4096 Jul 24 14:08 .pm2
```

The folder is owned by root. Now, if I use pm2 it will fail since it can't write in .pm2 folder, ex:

```
# pm2 dump

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect EACCES
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
```

This leads me to another question: why is pm2 starting the daemon when it is not required?
Ex:

```
# pm2 unexistingcommand
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
[PM2]
Command not found

  Usage: pm2 [cmd] app
...
```

Or even just for getting the help:

```
# pm2 -h
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized

  Usage: pm2 [cmd] app
```

Thanks.

**Comment by bragma** [comment]
As an addenda, my suggestion is to change the suggested command to:

sudo su -c 'env PATH=$PATH:/usr/bin pm2 startup ubuntu -u user'

This will correctly create a ".pm2" folder in the root's home.
Let me know if you'd like a PR for this.

**Comment by bragma** [comment]
Added a PR, enjoy!
