### ISSUE TITLE
Using wrong drive for PID files on Windows 

### ISSUE THREAD

**Issue by fkollmann** [Unitech/PM2#1513]
Hi, 

when working with multiple drives, the PID is being created in the wrong folder:

1. Checkout project on non-system drive, e.g. D:
2. Run "pm2 start ..."

The log file will show the following error:

```
2015-08-10 17:39:33: Error: ENOENT, no such file or directory 'D:\Users\mail_000\.pm2\pm2.pid'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at Object.Satan.processStateHandler (C:\Users\mail_000\AppData\Roaming\npm\node_modules\pm2\lib\Satan.js:98:8)
    at Object.Satan.remoteWrapper (C:\Users\mail_000\AppData\Roaming\npm\node_modules\pm2\lib\Satan.js:130:9)
    at Domain.<anonymous> (C:\Users\mail_000\AppData\Roaming\npm\node_modules\pm2\lib\Satan.js:651:13)
    at Domain.run (domain.js:197:16)
    at Object.<anonymous> (C:\Users\mail_000\AppData\Roaming\npm\node_modules\pm2\lib\Satan.js:650:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

# Workaround 1

Create junction point on the other drive by running the following command in an elevated cmd shell:

```
mklink /j d:\Users c:\Users
```

# Workaround 2

Have your PM2 run in a specific home directory by adding this to your batch file:

```
set PM2_HOME=%~dp0\.pm2
```

**Comment by cleytonb** [comment]
I'm having the same problem here.

Just setted the PM2_HOME variable to the right path in my dev machine and everything is ok, but it just a workaround, not how things should run.

**Comment by jshkurti** [comment]
Thanks @cleytonb !
