### ISSUE TITLE
undefined symbol: node_module_register

### ISSUE THREAD

**Issue by niftylettuce** [Unitech/pm2#1518]
I'm not sure how this relates to PM2, but if I run my app without it, it works fine.  Otherwise I get this error:

```
Error: /opt/myproject/node_modules/qr-js/node_modules/canvas/build/Release/canvas.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Function.cls_wrapMethod [as _load] (/opt/myproject/node_modules/newrelic/lib/shimmer.js:230:38)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/myproject/node_modules/qr-js/node_modules/canvas/lib/bindings.js:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Function.cls_wrapMethod [as _load] (/opt/myproject/node_modules/newrelic/lib/shimmer.js:230:38)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    ...
```

Node `v0.12.7` and NPM `2.11.3`

Possibly related to `qr-js` project via https://github.com/neocotic/qr.js/issues/36.

**Comment by niftylettuce** [comment]
Duplicate of https://github.com/Unitech/PM2/issues/1477 it appears

**Comment by jshkurti** [comment]
Install the latest pm2 and launch your app with `--no-pmx` flag (`"pmx" : "false"` in JSON declaration).
It should fix the issue for now while we investigate the bug.

**Comment by jshkurti** [comment]
Did the solution in #1477 help btw ?

**Comment by niftylettuce** [comment]
The solution for #1477 didn't help, but we're trying `--no-pmx` now, /cc @freekrai

**Comment by niftylettuce** [comment]
@jshkurti `--no-pmx` did not work, any other suggestions for how to fix?

**Comment by jshkurti** [comment]
My bad, I thought it had been published but it is not.
It will be on v0.14.7 which is going to be published in a few hours.

**Comment by niftylettuce** [comment]
It looks like `v0.14.7` was released, @freekrai please test?

**Comment by niftylettuce** [comment]
@jshkurti This did not fix the issue /cc @freekrai

**Comment by Unitech** [comment]
guess it's fixed!
