### ISSUE TITLE
pm2 does not show error if permission denied to log file

### ISSUE THREAD

**Issue by Jokero** [Unitech/PM2#1524]
OS - Ubuntu 14.04.1 LTS
Node.js - 0.12.2
pm2 - 0.14.6

app.js:
```javascript
var http = require('http');
http.createServer(function (req, res) {
  res.end('Hello World');
}).listen(9999);

console.log('Server running at http://127.0.0.1:9999/');
```

apps.json:
```javascript
{
  "apps" : [{
    "name":       "pm2",
    "script":     "app.js",
    "exec_mode":  "cluster",
    "instances":  0,
    "out_file":   "output.log",
    "error_file": "error.log",
    "merge_logs": true
  }]
}
```
Log files exist and, for example, owner of `output.log` is root (not simple user).

Run app:
```
pm2 start apps.json
```
Status is online but in fact app does not work:
```
┌──────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name │ id │ mode    │ pid   │ status │ restart │ uptime │ memory      │ watching │
├──────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ pm2      │ 0  │ cluster │ 9983  │ online │ 0       │ 0s     │ 20.320 MB   │ disabled │
│ pm2      │ 1  │ cluster │ 9988  │ online │ 0       │ 0s     │ 20.254 MB   │ disabled │
│ pm2      │ 2  │ cluster │ 9997  │ online │ 0       │ 0s     │ 20.133 MB   │ disabled │
│ pm2      │ 3  │ cluster │ 10006 │ online │ 0       │ 0s     │ 14.980 MB   │ disabled │
└──────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────────────┴──────────┘
```
And `pm2 flush` output:
```
[PM2] Flushing /home/dmitry/.pm2/pm2.log
[PM2] Flushing
[PM2] /home/dmitry/dev/pm2/output.log
[PM2] /home/dmitry/dev/pm2/error.log
fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES, permission denied '/home/dmitry/dev/pm2/output.log'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at /home/dmitry/.nvm/versions/node/v0.12.2/lib/node_modules/pm2/lib/CLI.js:1503:23
    at Array.forEach (native)
    at /home/dmitry/.nvm/versions/node/v0.12.2/lib/node_modules/pm2/lib/CLI.js:1493:10
    at /home/dmitry/.nvm/versions/node/v0.12.2/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/home/dmitry/.nvm/versions/node/v0.12.2/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (events.js:107:17)
    at Parser._write (/home/dmitry/.nvm/versions/node/v0.12.2/lib/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:301:12)

```

Run app in fork mode:
```
[PM2][WARN] You are starting 1 processes in fork_mode without load balancing. To enable it remove -x option.
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬────────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ memory │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴────────┴──────────┘
```
No running apps but there is message `You are starting 1 processes`

**Comment by alokraj68** [comment]
No comments for this issue?
