### ISSUE TITLE
Log.js:98 - tail.disconnect(); TypeError: Object #<ChildProcess> has no method 'disconnect'

### ISSUE THREAD

**Issue by atomantic** [Unitech/PM2#1526]
I'm running a pm2 app in a docker container with watch. When I save a file, it dies with this error:
```
web_1       | /usr/lib/node_modules/pm2/lib/Log.js:98
web_1       |     tail.disconnect();
web_1       |          ^
web_1       | TypeError: Object #<ChildProcess> has no method 'disconnect'
web_1       |     at Socket.<anonymous> (/usr/lib/node_modules/pm2/lib/Log.js:98:10)
web_1       |     at Socket.emit (events.js:95:17)
web_1       |     at Socket.<anonymous> (_stream_readable.js:764:14)
web_1       |     at Socket.emit (events.js:92:17)
web_1       |     at emitReadable_ (_stream_readable.js:426:10)
web_1       |     at emitReadable (_stream_readable.js:422:5)
web_1       |     at readableAddChunk (_stream_readable.js:165:9)
web_1       |     at Socket.Readable.push (_stream_readable.js:127:10)
web_1       |     at Pipe.onread (net.js:528:21)
dockerized_web_1 exited with code 8
```

**Comment by atomantic** [comment]
hmm... suddenly I can't repro this...

**Comment by jshkurti** [comment]
It looks like you're using an old version of PM2 :)

**Comment by atomantic** [comment]
Thanks. yeah, I fixed it by adding 
```
RUN npm install -g pm2@latest
```
to my Dockerfile :)
