### ISSUE TITLE
PM2 restart loop - possible to show what caused "change" to trigger?

### ISSUE THREAD

**Issue by jimlei** [Unitech/PM2#1547]
Trying to start a new sailsjs app on a newly installed (vagrant) ubuntu 14.04 box but it gets stuck in an infinite "change detected - reloading" loop. It's quite frustrating to not know what triggered it. Hope there is some attribute somewhere to show a more verbose log of what's going on.

node v0.12.7
npm 2.11.3
pm2 0.14.7

```sh
pm2 start processes.json --watch
```

```json
{
    "apps":
    [
        {
            "name"        : "api",
            "script"      : "app.js",
            "args"        : [],
            "node_args"   : "--harmony",
            "instances"   : 0,
            "max_memory_restart": "300M",
            "exec_mode"   : "cluster",
            "autorestart" : true,
            "merge_logs"  : true,
            "watch_options": {
                "followSymlinks": false,
                "usePolling": true,
                "interval": 400
            },
            "ignoreWatch" : ["[\\/\\\\]\\./", "logs", "node_modules", ".tmp", ".idea", ".vagrant"],
            "error_file"  : "./logs/error.log",
            "out_file"    : "./logs/out.log",
            "pid_file"    : "./logs/app.pid"
        }
    ]
}
```

```sh
PM2 Change detected for app name: api - restarting
PM2 Stopping app:api id:0
PM2 App name:api id:0 disconnected
PM2 App name:api id:0 exited with code SIGTERM
PM2 Process with pid 3209 killed
PM2 Starting execution sequence in -cluster mode- for app name:api id:0
PM2 App name:api id:0 online
PM2 Change detected for app name: api - restarting
PM2 Stopping app:api id:0
PM2 App name:api id:0 disconnected
PM2 App name:api id:0 exited with code SIGTERM
PM2 Process with pid 3214 killed
PM2 Starting execution sequence in -cluster mode- for app name:api id:0
PM2 App name:api id:0 online
PM2 Change detected for app name: api - restarting
PM2 Stopping app:api id:0
PM2 App name:api id:0 disconnected
PM2 App name:api id:0 exited with code SIGTERM
PM2 Process with pid 3219 killed
PM2 Starting execution sequence in -cluster mode- for app name:api id:0
PM2 App name:api id:0 online
PM2 Change detected for app name: api - restarting
PM2 Stopping app:api id:0
PM2 App name:api id:0 disconnected
PM2 App name:api id:0 exited with code SIGTERM
PM2 Process with pid 3224 killed
PM2 Starting execution sequence in -cluster mode- for app name:api id:0
PM2 App name:api id:0 online
```

**Comment by cazgp** [comment]
I'm getting exactly the same errors, and it's cluster mode specific. `pm2 logs`:

```
M2: 2015-08-23 02:04:55: Starting execution sequence in -cluster mode- for app name:load-balancer id:0
PM2: node.js:720
PM2:     var cwd = process.cwd();
PM2:                       ^
PM2: Error: ENOENT, no such file or directory
PM2:     at Error (native)
PM2:     at Function.startup.resolveArgv0 (node.js:720:23)
PM2:     at startup (node.js:63:13)
PM2:     at node.js:814:3
PM2: 2015-08-23 02:04:55: App name:load-balancer id:0 disconnected
PM2: 2015-08-23 02:04:55: App name:load-balancer id:0 exited with code 1
```

**Comment by cazgp** [comment]
Reinstalling pm2 by downgrading to 0.14.6, then running `pm2 updatePM2` has fixed it.

**Comment by jimlei** [comment]
It's not cluster specific and reinstalling / downgrading+upgrading pm2 didn't help for me :(

PM2 works perfectly if I turn off the watch, so I'm not sure what's wrong. I've tried destroying the VM and reinstalling it (a few times) but still stuck :\

**Comment by jimlei** [comment]
My bad.. typo in "ignoreWatch", should be "ignore_watch"
