### ISSUE TITLE
Process with pid already exists.

### ISSUE THREAD

**Issue by sabrehagen** [Unitech/PM2#1555]
Hi,

I received this issue today when restarting my server. Just alerting you to it. PM2 version 0.14.7 on Ubuntu 14.04.
```
[PM2] Process server succesfully reloaded
[PM2] Process server succesfully reloaded
[PM2] Process server succesfully reloaded
Error: Process with pid 10377 already exists
    at Object.God.logAndGenerateError (/usr/local/lib/iojs-v2.3.3-linux-x64/lib/node_modules/pm2/lib/God/Methods.js:35:12)
    at Object.God.startProcessId (/usr/local/lib/iojs-v2.3.3-linux-x64/lib/node_modules/pm2/lib/God/ActionMethods.js:218:21)
    at Object.God.restartProcessId (/usr/local/lib/iojs-v2.3.3-linux-x64/lib/node_modules/pm2/lib/God/ActionMethods.js:421:18)
    at God.reloadProcessId (/usr/local/lib/iojs-v2.3.3-linux-x64/lib/node_modules/pm2/lib/God/Reload.js:198:18)
    at Server.onmessage (/usr/local/lib/iojs-v2.3.3-linux-x64/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:105:6)
    at emitTwo (events.js:87:13)
    at RepSocket.emit (events.js:172:7)
    at Parser.<anonymous> (/usr/local/lib/iojs-v2.3.3-linux-x64/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/rep.js:51:15)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
```

**Comment by ClementParis016** [comment]
I'm encountering the same problem. Did you managed to solve it @sabrehagen?

Ubuntu 14.04.3
pm2 v0.14.5

```log
[PM2] Reloading process
[PM2] Process succesfully reloaded
Error: Process with pid 15357 already exists
    at Object.God.logAndGenerateError (/home/srv/.nvm/versions/v0.12.4/lib/node_modules/pm2/lib/God/Methods.js:35:12)
    at Object.God.startProcessId (/home/srv/.nvm/versions/v0.12.4/lib/node_modules/pm2/lib/God/ActionMethods.js:218:21)
    at Object.God.restartProcessId (/home/srv/.nvm/versions/v0.12.4/lib/node_modules/pm2/lib/God/ActionMethods.js:419:18)
    at God.reloadProcessId (/home/srv/.nvm/versions/v0.12.4/lib/node_modules/pm2/lib/God/Reload.js:198:18)
    at Server.onmessage (/home/srv/.nvm/versions/v0.12.4/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:105:6)
    at RepSocket.emit (events.js:110:17)
    at Parser.<anonymous> (/home/srv/.nvm/versions/v0.12.4/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/rep.js:51:15)
    at Parser.emit (events.js:107:17)
    at Parser._write (/home/srv/.nvm/versions/v0.12.4/lib/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:301:12)
```

**Comment by acarstoiu** [comment]
A full restart (including _God_) solves it. This problem shows up with pm2 _1.0.0_ as well, but I cannot give a replication recipe (it a series of start/reload operations that triggered it).

The problem is that a process is both state `errored`but at the same time `God.clusters_db[id].process.pid` is set. Looks very much like a **bug**!

**Comment by acarstoiu** [comment]
**For PM2 developers:**
By any chance, is it that PM2 running in _cluster_ mode places an instance in state **_errored_** when it fails to reply to a request, i.e. a timeout occurs before receiving an answer?

**Comment by venkatesh-tr** [comment]
I can see one of the process getting SIGINT when this happened! Is it something to do with the fact that that process which got SIGINT is not closed down in time?
