### ISSUE TITLE
How to view process truly logs?

### ISSUE THREAD

**Issue by Gaubee** [Unitech/pm2#1557]
[progress](https://www.npmjs.com/package/progress) module no work.

``` is
process.stderr.isTTY //false
process.stderr.clearLine // undefined
```

pm2 rewrite process.stdout/stderr .

**Comment by derit** [comment]
same issue
```javascript
0|app  | 2019-10-01 17:17 +07:00: TypeError: process.stdout.clearLine is not a function
0|app  | 2019-10-01 17:17 +07:00:     at Pumpify._ (/home/dr/test/dist/index.js:1:1751)
0|app  | 2019-10-01 17:17 +07:00:     at Pumpify.emit (events.js:198:13)
0|app  | 2019-10-01 17:17 +07:00:     at addChunk (/home/dr/test/node_modules/pumpify/node_modules/readable-stream/lib/_stream_readable.js:297:12)
0|app  | 2019-10-01 17:17 +07:00:     at readableAddChunk (/home/dr/test/node_modules/pumpify/node_modules/readable-stream/lib/_stream_readable.js:279:11)
0|app  | 2019-10-01 17:17 +07:00:     at Pumpify.Readable.push (/home/dr/test/node_modules/pumpify/node_modules/readable-stream/lib/_stream_readable.js:240:10)
0|app  | 2019-10-01 17:17 +07:00:     at Pumpify.Duplexify._forward (/home/dr/test/node_modules/pumpify/node_modules/duplexify/index.js:172:26)
0|app  | 2019-10-01 17:17 +07:00:     at PassThrough.onreadable (/home/dr/test/node_modules/pumpify/node_modules/duplexify/index.js:136:10)
0|app  | 2019-10-01 17:17 +07:00:     at PassThrough.emit (events.js:198:13)
0|app  | 2019-10-01 17:17 +07:00:     at emitReadable_ (_stream_readable.js:554:12)
0|app  | 2019-10-01 17:17 +07:00:     at process._tickCallback (internal/process/next_tick.js:63:19)
0|app  | 2019-10-01 17:17 +07:00: TypeError: process.stdout.clearLine is not a function
0|app  | 2019-10-01 17:17 +07:00:     at Pumpify._ (/home/dr/test/dist/index.js:1:1751)
0|app  | 2019-10-01 17:17 +07:00:     at Pumpify.emit (events.js:198:13)
0|app  | 2019-10-01 17:17 +07:00:     at addChunk (/home/dr/test/node_modules/pumpify/node_modules/readable-stream/lib/_stream_readable.js:297:12)
0|app  | 2019-10-01 17:17 +07:00:     at readableAddChunk (/home/dr/test/node_modules/pumpify/node_modules/readable-stream/lib/_stream_readable.js:279:11)
0|app  | 2019-10-01 17:17 +07:00:     at Pumpify.Readable.push (/home/dr/test/node_modules/pumpify/node_modules/readable-stream/lib/_stream_readable.js:240:10)
0|app  | 2019-10-01 17:17 +07:00:     at Pumpify.Duplexify._forward (/home/dr/test/node_modules/pumpify/node_modules/duplexify/index.js:172:26)
0|app  | 2019-10-01 17:17 +07:00:     at PassThrough.onreadable (/home/dr/test/node_modules/pumpify/node_modules/duplexify/index.js:136:10)
0|app  | 2019-10-01 17:17 +07:00:     at PassThrough.emit (events.js:198:13)
0|app  | 2019-10-01 17:17 +07:00:     at emitReadable_ (_stream_readable.js:554:12)
0|app  | 2019-10-01 17:17 +07:00:     at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by fullflash** [comment]
this is important issue. everything works as expected when running with $ node test.js but when running with pm2 not.
looks like this packages is abandoned.
