### ISSUE TITLE
 --ignore-watch="*.log" has crashed pm2 

### ISSUE THREAD

**Issue by soichih** [Unitech/PM2#1577]
I just observed that pm2 server crashed and killed all of my node apps simply by trying to start another application by doing following.
```
pm2 start progress.js --watch --ignore-watch="error.log"
```

I see following in the pm2 logs

```
2015-09-02 16:27:32: Process with pid 13717 killed
2015-09-02 16:27:36: [PM2] Error caught by domain:
SyntaxError: Invalid regular expression: /*.log/: Nothing to repeat
    at new RegExp (<anonymous>)
    at Object.ClusterMode.God.watch.enable (/usr/lib/node_modules/pm2/lib/Watcher.js:33:17)
    at Object.executeApp (/usr/lib/node_modules/pm2/lib/God.js:111:17)
    at ex (/usr/lib/node_modules/pm2/lib/God.js:367:18)
    at prepare (/usr/lib/node_modules/pm2/lib/God.js:373:7)
    at Server.onmessage (/usr/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:105:6)
    at RepSocket.emit (events.js:98:17)
    at Parser.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/rep.js:51:15)
    at Parser.emit (events.js:95:17)
    at Parser._write (/usr/lib/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
2015-09-02 16:27:36: [PM2] Trying to update PM2...

module.js:340
    throw err;
          ^
Error: Cannot find module '/undefined'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

events.js:72
        throw er; // Unhandled 'error' event
              ^
```

2 requests...

1) Make pm2 not crash if it received any uncaught exceptions.
2) Make --ignore-watch to accept wild cards (like *.log)
(I just realized I could do --ignore-watch="\.log$".. however)

Thank you!

**Comment by Unitech** [comment]
This has been fixed in PM2 #dev so:

```
$ npm install Unitech/PM2#development -g
$ pm2 update
```
