### ISSUE TITLE
It seems that Node.js processes which are started by PM2 are different than others, e.g. /proc/$pid/cmdline is truncated at 59 characters.

### ISSUE THREAD

**Issue by imaxwel** [Unitech/pm2#1609]
# ps -ef |grep node

root     21016  3289  0 11:16 pts/4    00:00:00 grep --color=auto node
root     29840 29839  0 05:30 ?        00:00:00 node ./../erizoJS/erizoJS.js 4295a387-8ea8-6b45-7a64-59348c137429 222.174.255.190 222.174.255.190
root     41845 41823  0  9月11 ?      00:01:19 node /usr/vish/licode/extras/Nmeeting/Nmeeting.js
root     41867 41823  0  9月11 ?      00:05:55 node /root/.pm2/node_modules/pm2-server-monit/app.js
root     45107 41823  0  9月11 ?      00:01:30 node /usr/vish_new/licode/nuve/nuveAPI/nuve.js
root     45169 41823  0  9月11 ?      00:02:05 node /usr/vish_new/licode/erizo_controller/erizoControll
root     45198 41823  0  9月11 ?      00:00:36 node /usr/vish_new/licode/erizo_controller/erizoAgent/er

---

the process whose pid is 29840 is started by normal node.js shell command, while pid of 41845 41867 45107 45169 45198 are started by pm2.
# 

root@gzze:/usr/vish_new/licode/scripts# pm2 --version
1.0.0-beta.1
root@gzze:/usr/vish_new/licode/scripts# node --version
v0.10.37
root@gzze:/usr/vish_new/licode/scripts# uname -a
Linux gzze 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@gzze:/usr/vish_new/licode/scripts# head -n 50 ~/.pm2/pm2.log output
==> /root/.pm2/pm2.log <==
2015-09-11 16:35:23: [PM2][WORKER] Started with refreshing interval: 30000
2015-09-11 16:35:23: [[[[ PM2/God daemon launched ]]]]
2015-09-11 16:35:23: BUS system [READY] on port /root/.pm2/pub.sock
2015-09-11 16:35:23: RPC interface [READY] on port /root/.pm2/rpc.sock
2015-09-11 16:35:23: PM2 is being killed via kill method
2015-09-11 16:35:23: RPC socket closed
2015-09-11 16:35:23: PUB socket closed
2015-09-11 16:35:23: [PM2][WORKER] Started with refreshing interval: 30000
2015-09-11 16:35:23: [[[[ PM2/God daemon launched ]]]]
2015-09-11 16:35:23: BUS system [READY] on port /root/.pm2/pub.sock
2015-09-11 16:35:23: RPC interface [READY] on port /root/.pm2/rpc.sock
2015-09-11 17:18:01: Starting execution sequence in -fork mode- for app name:pm2-server-monit id:0
2015-09-11 17:18:01: App name:pm2-server-monit id:0 online
2015-09-11 17:26:02: Starting execution sequence in -fork mode- for app name:Nmeetingjs id:1
2015-09-11 17:26:02: App name:Nmeetingjs id:1 online
2015-09-11 17:26:10: Error: watch ENOSPC
    at errnoException (fs.js:1031:11)
    at FSWatcher.start (fs.js:1063:11)
    at Object.fs.watch (fs.js:1088:11)
    at createFsWatchInstance (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at EventEmitter.NodeFsHandler._handleFile (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:468:21)
    at Object.oncomplete (fs.js:108:15)
2015-09-11 17:26:10: Error: watch ENOSPC
    at errnoException (fs.js:1031:11)
    at FSWatcher.start (fs.js:1063:11)
    at Object.fs.watch (fs.js:1088:11)
    at createFsWatchInstance (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at EventEmitter.NodeFsHandler._handleFile (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:468:21)
    at Object.oncomplete (fs.js:108:15)
2015-09-11 17:26:10: Error: watch ENOSPC
    at errnoException (fs.js:1031:11)
    at FSWatcher.start (fs.js:1063:11)
    at Object.fs.watch (fs.js:1088:11)
    at createFsWatchInstance (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at EventEmitter.NodeFsHandler._handleFile (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:468:21)
    at Object.oncomplete (fs.js:108:15)
2015-09-11 17:26:10: Error: watch ENOSPC
    at errnoException (fs.js:1031:11)
    at FSWatcher.start (fs.js:1063:11)
    at Object.fs.watch (fs.js:1088:11)
    at createFsWatchInstance (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:37:15)
head: cannot open ‘output’ for reading: No such file or directory
root@gzze:/usr/vish_new/licode/scripts# date
2015年 09月 12日 星期六 11:50:05 CST
root@gzze:/usr/vish_new/licode/scripts#

**Comment by mojojoseph** [comment]
Confirmed here as well, and this is preventing monit scripts from working properly (monit monitors processes as well and uses the 'matching' keyword to watch the process output).  

```
nobody      3642 33.0  8.8  83288 45008 ?        Ssl  13:14   0:09 node /usr/lib/node_modules/m2m-supervisor/bin/m2m-supervis
```

I would have expected the additional characters 'or.js' on the output above.

pm2 version is 0.15.6.

**Comment by artem-karpenko** [comment]
We've stumbled upon this issue too and discovered that adding `node_args` property fixes this.

**Comment by Unitech** [comment]
Error: watch ENOSPC
