### ISSUE TITLE
`pm2 updatePM2` hangs indefinitely

### ISSUE THREAD

**Issue by mzgol** [Unitech/PM2#1638]
Latest pm2 can't finish the `updatePM2` command for me:
```
$ node --version
v4.1.1
$ npm -g ls --depth 0
/usr/lib
├── npm@3.3.4
└── pm2@0.15.5

$ sudo pm2 updatePM2
Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.
[PM2] Stopping PM2...
[PM2][WARN] No process found
[PM2] All processes have been stopped and deleted
[PM2] PM2 stopped
```
and it just stays there until I kill the process via Ctrl+C.

Fortunately the process *is* spawned (although I believe the first time I did that it didn't, that's why in the above run it says "No process found") so I'm not blocked by that but it's weird the update process never finishes.

**Comment by Unitech** [comment]
What was the previous PM2 version installed?

Can you tail /root/.pm2/pm2.log and copy it here

**Comment by mzgol** [comment]
I've upgraded at the same time:

1. Node 4.0.0 -> 4.1.1
2. npm 2.14.sth -> 3.3.4
3. pm2 0.14.7 (I think) -> 0.15.5

To reduce any possible compatibility problems with switching npm versions (npm@3 dedupes deps by default so the directory structure is different) I removed pm2 via `npm -g uninstall pm2` and installed it again after the npm upgrade.

I'm not running the process as root so the log is under /home/wiekxix/.pm2/pm2.log. Now I'm afraid that running `pm2 updatePM2` via `sudo` might cause all these problems... I had some files under /home/wiekxix/.pm2/ owned by `root`, I've not chowned the whole directory back to my user.

If that's the case it would still be good to have a message about the permission problem instead of hanging indefinitely.

```
$ tail -100 .pm2/pm2.log
[Keymetrics.io] [Agent updated] Agent ACTIVE - Web Access: https://app.keymetrics.io/
>>>>>>>>>> PM2 updated
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬────────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ memory │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
2015-09-23 14:36:35: PM2 is being killed via kill method
2015-09-23 14:36:35: RPC socket closed
2015-09-23 14:36:35: PUB socket closed
2015-09-23 14:36:35: [PM2] Error caught by domain:
Error: kill EPERM
    at exports._errnoException (util.js:837:11)
    at process.kill (node.js:764:15)
    at /usr/lib/node_modules/pm2/lib/God/ActionMethods.js:512:17
    at PubSocket.Socket.closeServer (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/sock.js:136:9)
    at PubSocket.Socket.close (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/sock.js:122:25)
    at /usr/lib/node_modules/pm2/lib/God/ActionMethods.js:505:24
    at RepSocket.Socket.closeServer (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/sock.js:136:9)
    at RepSocket.Socket.close (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/sock.js:122:25)
    at God.killMe (/usr/lib/node_modules/pm2/lib/God/ActionMethods.js:503:22)
    at Server.onmessage (/usr/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:105:6)
2015-09-23 14:36:35: [PM2] Trying to update PM2...
[PM2] Spawning PM2 daemon
2015-09-23 14:36:36: [PM2][WORKER] Started with refreshing interval: 30000
2015-09-23 14:36:36: [[[[ PM2/God daemon launched ]]]]
2015-09-23 14:36:36: BUS system [READY] on port /home/wiekxix/.pm2/pub.sock
2015-09-23 14:36:36: RPC interface [READY] on port /home/wiekxix/.pm2/rpc.sock
[Keymetrics.io] Using (Public key: iq8a5n8sagm3lte) (Private key: 8g5qvc3kdhqbxqn)
[Keymetrics.io] [Agent updated] Agent ACTIVE - Web Access: https://app.keymetrics.io/
[PM2] PM2 Successfully daemonized
Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.
[PM2] Stopping PM2...
[PM2][WARN] No process found
[PM2] All processes have been stopped and deleted
2015-09-23 14:36:37: PM2 is being killed via kill method
2015-09-23 14:36:37: RPC socket closed
2015-09-23 14:36:37: PUB socket closed
[PM2] PM2 stopped
2015-09-23 14:36:38: [PM2][WORKER] Started with refreshing interval: 30000
2015-09-23 14:36:38: [[[[ PM2/God daemon launched ]]]]
2015-09-23 14:36:38: BUS system [READY] on port /home/wiekxix/.pm2/pub.sock
2015-09-23 14:36:38: RPC interface [READY] on port /home/wiekxix/.pm2/rpc.sock
[Keymetrics.io] Using (Public key: iq8a5n8sagm3lte) (Private key: 8g5qvc3kdhqbxqn)
2015-09-23 14:36:39: [PM2][WORKER] Started with refreshing interval: 30000
2015-09-23 14:36:39: [[[[ PM2/God daemon launched ]]]]
2015-09-23 14:36:39: Process is already listening on socket /home/wiekxix/.pm2/pub.sock
[Keymetrics.io] [Agent updated] Agent ACTIVE - Web Access: https://app.keymetrics.io/
>>>>>>>>>> PM2 updated
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬────────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ memory │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
2015-09-23 14:41:35: PM2 is being killed via kill method
2015-09-23 14:41:35: RPC socket closed
2015-09-23 14:41:35: PUB socket closed
2015-09-23 14:41:35: [PM2] Error caught by domain:
Error: kill EPERM
    at exports._errnoException (util.js:837:11)
    at process.kill (node.js:764:15)
    at /usr/lib/node_modules/pm2/lib/God/ActionMethods.js:512:17
    at PubSocket.Socket.closeServer (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/sock.js:136:9)
    at PubSocket.Socket.close (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/sock.js:122:25)
    at /usr/lib/node_modules/pm2/lib/God/ActionMethods.js:505:24
    at RepSocket.Socket.closeServer (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/sock.js:136:9)
    at RepSocket.Socket.close (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/sock.js:122:25)
    at God.killMe (/usr/lib/node_modules/pm2/lib/God/ActionMethods.js:503:22)
    at Server.onmessage (/usr/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:105:6)
2015-09-23 14:41:35: [PM2] Trying to update PM2...
[PM2] Spawning PM2 daemon
2015-09-23 14:41:37: [PM2][WORKER] Started with refreshing interval: 30000
2015-09-23 14:41:37: [[[[ PM2/God daemon launched ]]]]
2015-09-23 14:41:37: BUS system [READY] on port /home/wiekxix/.pm2/pub.sock
2015-09-23 14:41:37: RPC interface [READY] on port /home/wiekxix/.pm2/rpc.sock
[Keymetrics.io] Using (Public key: iq8a5n8sagm3lte) (Private key: 8g5qvc3kdhqbxqn)
2015-09-23 14:41:40: [PM2][WORKER] Started with refreshing interval: 30000
[Keymetrics.io] [Agent updated] Agent ACTIVE - Web Access: https://app.keymetrics.io/
[PM2] PM2 Successfully daemonized
2015-09-23 14:41:40: [[[[ PM2/God daemon launched ]]]]
Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.
[PM2] Stopping PM2...
[PM2][WARN] No process found
[PM2] All processes have been stopped and deleted
2015-09-23 14:41:40: Process is already listening on socket /home/wiekxix/.pm2/pub.sock
2015-09-23 14:41:40: PM2 is being killed via kill method
2015-09-23 14:41:40: RPC socket closed
2015-09-23 14:41:40: PUB socket closed
[PM2] PM2 stopped
2015-09-23 14:41:41: [PM2][WORKER] Started with refreshing interval: 30000
2015-09-23 14:41:41: [[[[ PM2/God daemon launched ]]]]
2015-09-23 14:41:41: BUS system [READY] on port /home/wiekxix/.pm2/pub.sock
2015-09-23 14:41:41: RPC interface [READY] on port /home/wiekxix/.pm2/rpc.sock
[Keymetrics.io] Using (Public key: iq8a5n8sagm3lte) (Private key: 8g5qvc3kdhqbxqn)
[Keymetrics.io] [Agent updated] Agent ACTIVE - Web Access: https://app.keymetrics.io/
>>>>>>>>>> PM2 updated
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬────────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ memory │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
2015-09-23 14:51:22: Starting execution sequence in -fork mode- for app name:wiekxix id:0
2015-09-23 14:51:22: App name:wiekxix id:0 online
```

**Comment by Unitech** [comment]
Thanks for these infos, is there something weird in the pm2.log?

**Comment by mzgol** [comment]
I'm looking into it. I posted the log before for a moment before realizing it has the private key in plain text inside... :/ How do I reset it? Does the log contain any other info I shouldn't share?

**Comment by Unitech** [comment]
I would like just to know if there is a stacktrace about a kind of exception

For the log, just remove the private key and it should be good

**Comment by mzgol** [comment]
@Unitech The full log from today: https://gist.github.com/mzgol/30ac4e83c25b35a7a38b

Is there any way to reset the keys used for Keymetrics? Since I posted the log with them inside here for a moment I'd like to reset them ASAP, all 399 people watching this repo will get them in the mail.

**Comment by Unitech** [comment]
Looks like there are permission problems and the lib parse-glob from chokidar has not been well installed. Does it work now?

Concerning the keys, you have to delete your current bucket and create a new one, there is no way to reset private keys and tell to your PM2 to relink with the new key automatically

**Comment by mzgol** [comment]
Yeah, it works fine now. I wonder what might have happened that broke the installation. :/ I guess in that case there's not much you can do, right?

**Comment by Unitech** [comment]
I just upgraded 18 servers with the new PM2 and I haven't got this problem, I'm looking to remove some deps for the next release

Thanks for reporting!
