### ISSUE TITLE
pm2 delete <json> throws exception if watch property is set to true

### ISSUE THREAD

**Issue by manuelbieh** [Unitech/pm2#1668]
Using pm2 0.15.7. 
I have the following app.json (complete file):

```
{
  "apps" : [{
    "name"        : "Amakuria-Service--DEV",
    "script"      : "index.js",
    "watch"       : "true",
    "merge_logs"  : true,
    "ignore_watch": ["[\\/\\\\]\\./", "node_modules", "cache/*"],
    "cwd"         : "./",
    "env": {
        "NODE_ENV": "dev"
    }
  }]
}
```

`pm2 start|stop|reload app.json` all work fine. If I try `pm2 delete app.json` I get the following error:

```
util.js:744
    origin[keys[i]] = add[keys[i]];
                    ^

TypeError: Cannot assign to read only property 'watch' of 5
    at Object.exports._extend (util.js:744:21)
    at async.eachLimit.next1.success (/usr/lib/node_modules/pm2/lib/CLI.js:560:23)
    at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:187:20
    at replenish (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:322:21)
    at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:333:15
    at Object.async.forEachLimit.async.eachLimit (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:226:35)
    at /usr/lib/node_modules/pm2/lib/CLI.js:550:13
    at /usr/lib/node_modules/pm2/lib/Common.js:308:12
    at /usr/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
```

(5 is the id of my process)

`Cannot assign to read only property 'watch' of 5` - what does that mean and why can I not use it in my app.json declaration? If I remove the `watch` property - everything works fine and the process is deleted properly.

**Comment by Unitech** [comment]
bug confirmed

**Comment by Unitech** [comment]
fixed in dev, thanks for reporting

**Comment by michahell** [comment]
Confirmed, getting this too. Might this be related to why the watch parameter in my application.json is not being picked up at all, even when using ```bash pm2 stop <id>``` and then using ```bash pm2 start app.json``` ?
