### ISSUE TITLE
How to use the --interpreter option

### ISSUE THREAD

**Issue by JosephDuffy** [Unitech/pm2#1697]
I'm trying to start an instance of my project using iojs 1.2 as [pointed out in another issue](https://github.com/Unitech/PM2/issues/1034#issuecomment-75638119). I have tried the following command to start it:

```
pm2 start /home/josephduffy/www/app.js --name personal-blog --interpreter=~/.nvm/versions/io.js/v1.2.0/bin/node
```

However, I get the warning

```
[PM2][WARN] We've notice that you are running the node script, but currently using a ~/.nvm/versions/io.js/v1.2.0/bin/node interpreter, may be you need inspect the --interpreter option.
```

and the app is in a constant "errored" status with no logs.

I am using iojs v3.3.1 and pm2 v0.15.7 on Ubuntu 14.04.2. The only [other thing I can find about this is about using it in cluster mode](https://github.com/Unitech/PM2/issues/1224#issuecomment-99931316), which I am not (I am using fork mode).

Any help much appreciated!

**Comment by Unitech** [comment]
Please give an absolute path to the `--interpreter` option (it does not resolve the `~`)

**Comment by btleffler** [comment]
Sorry to resurrect a closed issue, but I'm having trouble using the interpreter option with pm2 0.15.10.

```
$ pm2 describe 0
Describing process with id 0 - name test
┌───────────────────┬───────────────────────────────────────────────────────────────────────┐
│ status            │ errored                                                               │
│ name              │ test                                                                  │
│ id                │ 0                                                                     │
│ path              │ /home/ben/Projects/node-services/deploy_server/services/test/index.js │
│ args              │                                                                       │
│ exec cwd          │ /home/ben/Projects/node-services/deploy_server/services/test          │
│ error log path    │ /home/ben/.pm2/logs/test-error-0.log                                  │
│ out log path      │ /home/ben/.pm2/logs/test-out-0.log                                    │
│ pid path          │ /home/ben/.pm2/pids/test-0.pid                                        │
│ mode              │ fork_mode                                                             │
│ node v8 arguments │                                                                       │
│ watch & reload    │ ✘                                                                     │
│ interpreter       │ /opt/nvm/v0.10.41/bin/node                                            │
│                   │                                                                       │
│ restarts          │ 0                                                                     │
│ unstable restarts │ 0                                                                     │
│ uptime            │ 0                                                                     │
│ created at        │ 2015-12-14T19:11:53.630Z                                              │
└───────────────────┴───────────────────────────────────────────────────────────────────────┘

```

```
$ /opt/nvm/v0.10.41/bin/node --version
v0.10.41
```

The intended interpreter definitely exists, and an absolute path is passed as the interpreter option. For some reason when I try to start the process, it immediately goes to the "errored" status, and this is the only output I can find.

```
PM2: 2015-12-14 14:09:12: Error: spawn /opt/nvm/v0.10.41/bin/node
PM2:  ENOENT
PM2:     at exports._errnoException (util.js:856:11)
PM2:     at Process.ChildProcess._handle.onexit (internal/child_process.js:179:32)
PM2:     at onErrorNT (internal/child_process.js:345:16)
PM2:     at nextTickCallbackWith2Args (node.js:455:9)
PM2:     at process._tickDomainCallback (node.js:410:17)
PM2: 2015-12-14 14:11:53: Starting execution sequence in -fork mode- for app name:test id:0
PM2: 2015-12-14 14:11:53: App name:test id:0 online
PM2: 2015-12-14 14:11:53: Error: spawn /opt/nvm/v0.10.41/bin/node
PM2:  ENOENT
PM2:     at exports._errnoException (util.js:856:11)
PM2:     at Process.ChildProcess._handle.onexit (internal/child_process.js:179:32)
PM2:     at onErrorNT (internal/child_process.js:345:16)
PM2:     at nextTickCallbackWith2Args (node.js:455:9)
PM2:     at process._tickDomainCallback (node.js:410:17)
```

If I run the process manually using that interpreter, it seems to work correctly.

```
$ /opt/nvm/v0.10.41/bin/node /home/ben/Projects/node-services/deploy_server/services/test/index.js 
2015-12-14T14:36:33-05:00
2015-12-14T14:36:36-05:00
2015-12-14T14:36:39-05:00
2015-12-14T14:36:42-05:00
<this is the intended output>
```

If it's more helpful, I can start a new issue.
