### ISSUE TITLE
Error on gracefulReload when app handling long requests?

### ISSUE THREAD

**Issue by mattcasey** [Unitech/pm2#1702]
We have the same process deployed on two separate machines, node v0.12.7 and pm2 0.14.7 on a 4-core machine in AWS.

We've recently started using 'startOrGracefulReload' to restart these apps, they are both serving as an internal api. The 1st one eventually restarts in under 2 minutes but it is used for fast queries in production. The 2nd one handles much longer queries, however, such that it really can't be graceful. When pm2 hits this limit everything seems to go to hell, and it tries to update itself (?!). When I first discovered the process was down, I noticed that my processes were all gone and each replaced with a 'pm2 update' command.

In the following example, you can see the logs where i initially started the process, but then it was triggered to restart and couldn't:
```
internal_api-0 2015-10-19T20:33:54.884Z - info: Express server listening on port 3002 in production mode
internal_api-0 info: Mongoose connection open
internal_api-1 2015-10-19T20:33:54.994Z - info: Express server listening on port 3002 in production mode
internal_api-1 info: Mongoose connection open
internal_api-2 2015-10-19T20:33:55.069Z - info: Express server listening on port 3002 in production mode
internal_api-2 info: Mongoose connection open
internal_api-3 2015-10-19T20:33:55.155Z - info: Express server listening on port 3002 in production mode
internal_api-3 info: Mongoose connection open
internal_api-0 Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
internal_api-2 Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
PM2 Starting execution sequence in -cluster mode- for app name:internal_api id:0
PM2 App name:internal_api id:0 online
internal_api-0 info: Overriding Mongo uri: mongodb://ip-10-0-0-162.ec2.internal:27017
internal_api-0 info: Overriding Mongo options: slaveOk=true, readPreference=secondary, w=0
internal_api-0 2015-10-19T20:52:58.489Z - info: Express server listening on port 3002 in production mode
internal_api-0 info: Mongoose connection open
PM2 Stopping app:internal_api id:_old_0
PM2 Process with pid 6761 still not killed, retrying...
PM2 Process with pid 6761 still not killed, retrying...
PM2 Process with pid 6761 still not killed, retrying...
PM2 Process with pid 6761 still not killed, retrying...
PM2 Process with pid 6761 still not killed, retrying...
PM2 Process with pid 6761 still not killed, retrying...
PM2 Process with pid 6761 still not killed, retrying...
PM2 Process with pid 6761 still not killed, retrying...
PM2 Process with pid 6761 still not killed, retrying...
PM2 Process with pid 6761 still not killed, retrying...
PM2 Process with pid 6761 still not killed, retrying...
PM2 Process with pid 6761 still not killed, retrying...
PM2 Process with pid 6761 still not killed, retrying...
PM2 Process with pid 6761 still not killed, retrying...
PM2 Process with pid 6761 still not killed, retrying...
PM2 Process with pid 6761 still alive after 1600ms, sending it SIGKILL now...
PM2 [PM2] Error caught by domain:
Error: kill ESRCH
    at exports._errnoException (util.js:746:11)
    at process.kill (node.js:627:15)
    at null._onTimeout (/home/ubuntu/npm/lib/node_modules/pm2/lib/God/Methods.js:216:17)
    at Timer.listOnTimeout (timers.js:119:15)
PM2 [PM2] Trying to update PM2...
PM2 Stopping app:internal_api id:0
PM2 App name:internal_api id:0 disconnected
PM2 App name:internal_api id:0 exited with code 7
PM2 [HandleExit] PM2 is being killed, stopping restart procedure...
PM2 Process with pid 7078 killed
PM2 Stopping app:internal_api id:1
PM2 App name:internal_api id:1 disconnected
PM2 App name:internal_api id:1 exited with code 7
PM2 [HandleExit] PM2 is being killed, stopping restart procedure...
PM2 Process with pid 6770 killed
PM2 Stopping app:internal_api id:2
PM2 App name:internal_api id:2 disconnected
PM2 App name:internal_api id:2 exited with code 7
PM2 [HandleExit] PM2 is being killed, stopping restart procedure...
PM2 Process with pid 6779 killed
PM2 Stopping app:internal_api id:3
PM2 Process with pid 6788 still not killed, retrying...
PM2 Process with pid 6788 still not killed, retrying...
PM2 Process with pid 6788 still not killed, retrying...
PM2 Process with pid 6788 still not killed, retrying...
PM2 Process with pid 6788 still not killed, retrying...
PM2 Process with pid 6788 still not killed, retrying...
PM2 Process with pid 6788 still not killed, retrying...
PM2 Process with pid 6788 still not killed, retrying...
PM2 Process with pid 6788 still not killed, retrying...
PM2 Process with pid 6788 still not killed, retrying...
PM2 Process with pid 6788 still not killed, retrying...
PM2 Process with pid 6788 still not killed, retrying...
PM2 Process with pid 6788 still not killed, retrying...
PM2 Process with pid 6788 still not killed, retrying...
PM2 Process with pid 6788 still not killed, retrying...
```

**Comment by Benew** [comment]
+1

**Comment by hankchiutw** [comment]
Seems related to #1974

**Comment by Unitech** [comment]
closing in favor of #2061
