### ISSUE TITLE
pm2 cluster can't bind to port 80 but fork does

### ISSUE THREAD

**Issue by grassick** [Unitech/pm2#1707]
After running
``` sudo setcap 'cap_net_bind_service=+ep' `which node` ```

to allow binding to port 80, 443, pm2 works perfectly in fork mode.

But in cluster mode, it gives `Error: bind EACCES null:80`
I'm using nvm v4.2.1

See the error below:

```
  pm2:satan Calling daemon method pm2:getMonitorData +1ms
  pm2:satan God notified +3ms
  pm2:satan God notified +0ms
┌──────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name │ id │ mode    │ pid   │ status │ restart │ uptime │ memory      │ watching │
├──────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ server   │ 0  │ cluster │ 21529 │ online │ 2       │ 0s     │ 29.070 MB   │ disabled │
│ server   │ 1  │ cluster │ 21554 │ online │ 2       │ 0s     │ 14.875 MB   │ disabled │
└──────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
--no-daemon option enabled = do not exit pm2 CLI
PM2 daemon PID = 15141
  pm2:satan Calling daemon method pm2:getMonitorData +69ms
[PM2] Streaming realtime logs for [all] processes 

02:18:28 server-0 
Error: bind EACCES null:80
  at Object.exports._errnoException (util.js:874:11)
  at exports._exceptionWithHostPort (util.js:897:20)
  at cb (net.js:1299:16)
  at rr (cluster.js:588:14)
  at Worker.<anonymous> (cluster.js:558:9)
  at process.<anonymous> (cluster.js:710:8)
  at emitTwo (events.js:92:20)
  at process.emit (events.js:172:7)
  at handleMessage (internal/child_process.js:686:10)
  at Pipe.channel.onread (internal/child_process.js:440:11)

02:18:28 server-1 
Error: bind EACCES null:80
  at Object.exports._errnoException (util.js:874:11)
  at exports._exceptionWithHostPort (util.js:897:20)
```

pm2 --version
0.15.7

node --version
v4.2.1

uname -a
Linux ip-172-30-0-127 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Unitech** [comment]
Do a pm2 update once you did the command ```sudo setcap 'cap_net_bind_service=+ep' which node ```

else use [authbind](http://pm2.keymetrics.io/docs/usage/specifics/#allow-pm2-to-bind-applications-on-ports-80-443-without-root)
