### ISSUE TITLE
error with pm2 pull command

### ISSUE THREAD

**Issue by targos** [Unitech/pm2#1708]
We always have this error when there are new commits:
```
pm2 % pm2 pull grm
[PM2] Updating repository for process name grm
[PM2] Process successfully updated grm
[PM2] Current commit d6a0f72fca818992e3052f8a18948294bf4fd56d
[PM2] restartProcessId process id 14
/usr/lib/node_modules/pm2/lib/tools/VersionManagement.js:64
                return cb(null, {
                       ^

TypeError: cb is not a function
    at /usr/lib/node_modules/pm2/lib/tools/VersionManagement.js:64:24
    at /usr/lib/node_modules/pm2/lib/CLI.js:984:19
    at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:203:33
    at /usr/lib/node_modules/pm2/lib/CLI.js:980:16
    at /usr/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser._write (/usr/lib/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:292:12)

```

**Comment by Unitech** [comment]
Please upgrade PM2 (https://github.com/Unitech/pm2/blob/master/lib/tools/VersionManagement.js#L62)
