### ISSUE TITLE
Error pm2_env is undefined when using grunt concurrent

### ISSUE THREAD

**Issue by wassimsalib** [Unitech/pm2#1714]
When I run my ecosystem.js file I get this error in the logs:

```
Running "concurrent:dist" (concurrent) task
    Warning: undefined:1
    undefined
    ^
    SyntaxError: Unexpected token u
        at Object.parse (native)
        at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:11:20)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3 Use --force to continue.

        Aborted due to warnings.

```

it looks like pm2_env is undefined in this line https://github.com/Unitech/pm2/blob/master/lib/ProcessContainer.js#L11

This issue started to happen when using grunt concurrent with these 2 tasks 'imagemin' & 'svgmin'

**Comment by Unitech** [comment]
Could I get a sample of Gruntfile + node app to reproduce this bug,

Thank you
