### ISSUE TITLE
Wrong location during pm2 dump on 'startup systemd -u USER'

### ISSUE THREAD

**Issue by pszypowicz** [Unitech/pm2#1720]
pm2 version: 0.15.7
node version: 4.2.1
npm version: 2.14.7
system centos 7 x86_64

While using 
```bash
pm2 startup systemd -u node
```
i receive information: 

```
$ pm2 startup systemd -u node
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
[PM2] Generating system init script in /etc/systemd/system/pm2.service
[PM2] Making script booting at startup...
[PM2] -systemd- Using the command:
      su node -c "pm2 dump && pm2 kill" && su root -c "systemctl daemon-reload && systemctl enable pm2 && systemctl start pm2"
Command failed: /bin/sh -c su node -c "pm2 dump && pm2 kill" && su root -c "systemctl daemon-reload && systemctl enable pm2 && systemctl start pm2"
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:874:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:339:9)
    at Object.launchDaemon (/usr/lib/node_modules/pm2/lib/Satan.js:351:40)
    at /usr/lib/node_modules/pm2/lib/Satan.js:53:20
    at /usr/lib/node_modules/pm2/lib/Satan.js:399:14
    at doNTCallback0 (node.js:417:9)
    at process._tickDomainCallback (node.js:387:13)

----- Are you sure you use the right platform command line option ? centos / redhat, amazon, ubuntu, gentoo, systemd or darwin?
```

I see issue it this line: 
```
/bin/sh -c su node -c "pm2 dump && pm2 kill" 
```
which leaves HOME for commands execution same as root. Effectively he is trying to write to root HOME and surprised it cannot :) I will follow with pull request that basically will use **su -l** for those first command. As I observed, once .pm2 folder is created in user home dir, its using this, not causing EACCES errors.

**Comment by soyuka** [comment]
https://github.com/Unitech/pm2/issues/1654#issuecomment-153181749 `--hp home/path` should fix your issue. @Unitech thoughts?

**Comment by Unitech** [comment]
The -l option can fix this issue, but with the new `--hp home/path` option (shown when using pm2 startup) should fix this issue, please upgrade your PM2
