### ISSUE TITLE
Changing from version 0.15.7 to 0.15.8 gives me always an Error: watch ENOSPC

### ISSUE THREAD

**Issue by darkxeno** [Unitech/pm2#1728]
I made a rollback to 0.15.7 to avoid receiving the following error on start up:
```
16:59:00 PM2 Error: watch ENOSPC
16:59:00 PM2     at exports._errnoException (util.js:746:11)
16:59:00 PM2     at FSWatcher.start (fs.js:1172:11)
16:59:00 PM2     at Object.fs.watch (fs.js:1198:11)
16:59:00 PM2     at createFsWatchInstance (/usr/local/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:37:15)
16:59:00 PM2     at setFsWatchListener (/usr/local/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:80:15)
16:59:00 PM2     at EventEmitter.NodeFsHandler._watchWithNodeFs (/usr/local/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:228:14)
16:59:00 PM2     at EventEmitter.NodeFsHandler._handleFile (/usr/local/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:255:21)
16:59:00 PM2     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:468:21)
16:59:00 PM2     at FSReqWrap.oncomplete (fs.js:95:15)
```
If you need more info please ask.

**Comment by soyuka** [comment]
#1729
