### ISSUE TITLE
Error introduced from 0.15.8 to 0.15.9

### ISSUE THREAD

**Issue by LarsBuur** [Unitech/pm2#1746]
Just updated to 0.15.9 and got this error 

```
/usr/local/bin/xxx-worker/.npm-packages/lib/node_modules/pm2/lib/CLI.js:2305
    if(util.isObject(app.env[key])) {
            ^
TypeError: Object #<Object> has no method 'isObject'
    at mergeEnvironmentVariables (/usr/local/bin/xxx-worker/.npm-packages/lib/node_modules/pm2/lib/CLI.js:2305:13)
    at /usr/local/bin/xxx-worker/.npm-packages/lib/node_modules/pm2/lib/CLI.js:337:7
    at /usr/local/bin/xxx-worker/.npm-packages/lib/node_modules/pm2/node_modules/async/lib/async.js:181:20
    at replenish (/usr/local/bin/xxx-worker/.npm-packages/lib/node_modules/pm2/node_modules/async/lib/async.js:319:21)
    at /usr/local/bin/xxx-worker/.npm-packages/lib/node_modules/pm2/node_modules/async/lib/async.js:330:15
    at Object.async.forEachLimit.async.eachLimit (/usr/local/bin/xxx-worker/.npm-packages/lib/node_modules/pm2/node_modules/async/lib/async.js:220:35)
    at startApps (/usr/local/bin/xxx-worker/.npm-packages/lib/node_modules/pm2/lib/CLI.js:323:11)
    at /usr/local/bin/xxx-worker/.npm-packages/lib/node_modules/pm2/lib/CLI.js:423:14
    at /usr/local/bin/xxx-worker/.npm-packages/lib/node_modules/pm2/node_modules/async/lib/async.js:52:16
    at replenish (/usr/local/bin/xxx-worker/.npm-packages/lib/node_modules/pm2/node_modules/async/lib/async.js:314:29)
```

running 

```
./.npm-packages/bin/pm2 start process.json
```

contents of process.json:
```
{
  "name": "xxx-worker",
  "script": "/usr/local/bin/xxx-worker/runner.js",
  "log_date_format": "YYYY-MM-DD HH:mm Z",
  "watch": false,
  "env": {
    "NODE_ENV": "production",
    "xxxx":"YYYYY..."
  }
}
```

after running 
```
npm install pm2@0.15.8 -g
```

pm2 is running again.

Node version: v0.10.40
OS: Debian GNU/Linux 7.9 (wheezy)

Additional info: 
```
2015-11-04 13:49:23: [PM2][WORKER] Started with refreshing interval: 30000
2015-11-04 13:49:23: [[[[ PM2/God daemon launched ]]]]
2015-11-04 13:49:23: BUS system [READY] on port /home/xxx/.pm2/pub.sock
2015-11-04 13:49:23: RPC interface [READY] on port /home/xxx/.pm2/rpc.sock
```

**Comment by soyuka** [comment]
Shit node it has been added in node 1.0.0, I'll polyfill it asap.

Thanks for the report.

**Comment by soyuka** [comment]
`npm install -g Unitech/pm2#development` to patch it ;)

**Comment by LarsBuur** [comment]
Great - that solved the problem.

**Comment by Unitech** [comment]
0.15.10 published
