### ISSUE TITLE
pm2 doesn't abort where native run does

### ISSUE THREAD

**Issue by BruceBGordon** [Unitech/pm2#1747]
My node app throws an exception if it is not configured properly. When I run it from the command line it does in fact exit. When run via pm2 (fork mode), it stays up with it's status reported via PM2 as "onine"

node v4.1.2
pm2 version 0.15.9

app is started via 
```pm2 start {...json file} ```

The .json file is:
```
{
  "apps" : [{
    // Master
    "name"        : "guerilla-master",
    "script"      : "server.js",
    "args"        : ["--master"],
    "watch"       : false,
    "node_args"   : "--harmony",
    "cwd"         : "/Users/bruceg/repos/bruceg-yahoo-guerilla",
    "env": {
        "NODE_ENV": "production",
        "GuerillaConfigFile": "$GuerillaHostName/hahah"
    }
  },{
    // Worker
    "name"        : "guerilla-worker",
    "script"      : "server.js",
    "args"        : ["--worker"],
    "watch"       : false,
    "node_args"   : "--harmony",
    "cwd"         : "/Users/bruceg/repos/bruceg-yahoo-guerilla",
    "env": {
        "NODE_ENV": "production",
        "GuerillaConfigFile": "$GuerillaHostName/hahah"
    }
  }]
}
```
Currently I am forcing an exception at startup to highlight the issue. 

guerilla-master-error-0.log

```
Error: forcing exception in getConfig
    at getConfig (/Users/bruceg/repos/bruceg-yahoo-guerilla/lib/config.js:37:11)
    at new Config (/Users/bruceg/repos/bruceg-yahoo-guerilla/lib/config.js:109:18)
    at Object.<anonymous> (/Users/bruceg/repos/bruceg-yahoo-guerilla/lib/config.js:146:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
/Users/bruceg/repos/bruceg-yahoo-guerilla/lib/config.js:37
    throw new Error("forcing exception in getConfig");
    ^

Error: forcing exception in getConfig
    at getConfig (/Users/bruceg/repos/bruceg-yahoo-guerilla/lib/config.js:37:11)
    at new Config (/Users/bruceg/repos/bruceg-yahoo-guerilla/lib/config.js:109:18)
    at Object.<anonymous> (/Users/bruceg/repos/bruceg-yahoo-guerilla/lib/config.js:146:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
 
```

running ```pm2 logs``` in another window while I startup the app yields:
```
PM2: 2015-11-04 11:51:36: [PM2][WORKER] Started with refreshing interval: 30000
PM2: 2015-11-04 11:51:36: [[[[ PM2/God daemon launched ]]]]
PM2: 2015-11-04 11:51:36: BUS system [READY] on port /Users/bruceg/.pm2/pub.sock
PM2: 2015-11-04 11:51:36: RPC interface [READY] on port /Users/bruceg/.pm2/rpc.sock

[PM2] Streaming realtime logs for [all] processes 

PM2 Starting execution sequence in -fork mode- for app name:guerilla-master id:0
PM2 App name:guerilla-master id:0 online
PM2 Starting execution sequence in -fork mode- for app name:guerilla-worker id:1
PM2 App name:guerilla-worker id:1 online
guerilla-master-0 Guerilla master is starting up...
guerilla-master-0 Validating config/master/config.json...
guerilla-master-0 forcing exception in getConfig
guerilla-worker-1 Guerilla worker is starting up...
guerilla-worker-1 Validating config/worker/config.json...
guerilla-worker-1 forcing exception in getConfig
```

**Comment by BruceBGordon** [comment]
My application was catching the exception. I changed it to let the exception bubble up and the application did change its status to "errored". In the non-pm2 case it did behave different by exiting the node.js server.
