### ISSUE TITLE
TypeError: (data.data || "").split is not a function

### ISSUE THREAD

**Issue by ndaidong** [Unitech/pm2#1752]
Hi guys, 

Sometime I got the following error while trying to view log with "pm2 logs". What does it relate to? And how to fix it?

```
/usr/local/lib/node_modules/pm2/lib/Log.js:97
      var lines = (data.data || '').split('\n');
                                    ^

TypeError: (data.data || "").split is not a function
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Log.js:97:37)
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/sub-emitter.js:52:19)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser._write (/usr/local/lib/node_modules/pm2/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Parser.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
```

My environment:
- Linux Mint, Ubuntu latest
- node.js v5.0.0, npm v3.3.11
- pm2 v0.15.8

Thank for your advice,
Regards

**Comment by Unitech** [comment]
Hello,

What are you printing on the stdout?

**Comment by ndaidong** [comment]
@Unitech I just use console.log and console.trace to see how the processes work. They basically print out plain text or object. I don't think the issue comes from my script because everything works as normal.

**Comment by tomasikp** [comment]
Just got the same thing when I updated to `0.15.8` from `0.12`

**Comment by deadratfink** [comment]
Looks like this related or even could have similar cause like in #1756 !? Pls check tat issue as well...

Regards Jens

**Comment by deadratfink** [comment]
Sorry, I meant #1765

**Comment by phatthana-t** [comment]
I got the same when throw error.

**Comment by mathewmeconry** [comment]
:+1:

**Comment by cschwerdt** [comment]
+1

**Comment by Unitech** [comment]
Are you using newrelic?

**Comment by ericsaboia** [comment]
same thing here.
I'm using newrelic and node 0.12.4

**Comment by jasonstaczek** [comment]
Also getting it here when I use "throw".
