### ISSUE TITLE
Error in Log.js when logging data.data

### ISSUE THREAD

**Issue by deadratfink** [Unitech/pm2#1766]
Hi,

we just updated from v0.14.7 to to v0.15.10 of PM2. We experienced an error in _Log.js_ line 97:

```javascript
 {"name":"bdu-node-rest-service-template(development)","hostname":"...","pid":3183,"level":30,"msg":"process.env.NEW_RELIC_HOME = ....","time":"2015-11-10T13:11:21.548Z","v":0}
DEBUUUUUUUUUG: {"at":1447161081557,"data":{"type":"Buffer","data":[123,34,118,34,58,48,44,34,108,101,118,101,108,34,58,50,48,44,34,110,97,109,101,34,58,34,110,101,119,114,101,108,105,99,34,44,34,104,111,115,116,110,97,109,101,34,58,34,72,66,86,56,51,48,51,50,54,54,55,34,44,34,112,105,100,34,58,51,49,56,51,44,34,116,105,109,101,34,58,34,50,48,49,53,45,49,49,45,49,48,84,49,51,58,49,49,58,50,49,46,53,53,54,90,34,44,34,109,115,103,34,58,34,76,111,97,100,105,110,103,32,97,103,101,110,116,32,102,114,111,109,32,47,85,115,101,114,115,47,106,101,110,115,46,107,114,101,102,101,108,100,116,47,68,101,118,101,108,111,112,109,101,110,116,47,83,111,117,114,99,101,115,47,110,111,100,101,106,115,47,98,100,117,45,110,111,100,101,45,114,101,115,116,45,115,101,114,118,105,99,101,45,116,101,109,112,108,97,116,101,47,110,111,100,101,95,109,111,100,117,108,101,115,47,98,100,117,45,110,111,100,101,45,110,101,119,114,101,108,105,99,47,110,111,100,101,95,109,111,100,117,108,101,115,47,110,101,119,114,101,108,105,99,34,125,10]},"process":{"pm_id":0,"name":"bdu-node-rest-service-template-1.1.0","rev":"392b26a76ca7fa186b2dc51674fab5884aae938c"}} data.data="[object Object]"
/Users/jens.krefeldt/Development/Sources/nodejs/bdu-node-rest-service-template/node_modules/bdu-node-pm2/node_modules/pm2/lib/Log.js:98
      var lines = (data.data || '').split('\n');
                                    ^

TypeError: (data.data || "").split is not a function
    at Parser.<anonymous> (/Users/jens.krefeldt/Development/Sources/nodejs/bdu-node-rest-service-template/node_modules/bdu-node-pm2/node_modules/pm2/lib/Log.js:98:37)
    at Parser.<anonymous> (/Users/jens.krefeldt/Development/Sources/nodejs/bdu-node-rest-service-template/node_modules/bdu-node-pm2/node_modules/pm2/node_modules/pm2-axon/lib/sockets/sub-emitter.js:52:19)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser._write (/Users/jens.krefeldt/Development/Sources/nodejs/bdu-node-rest-service-template/node_modules/bdu-node-pm2/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Parser.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
```

I inserted a `console.log` before line 97 (so it is shown as line 98 above, so don't be confused ;-):

```javascript
      //console.log('DEBUUUUUUUUUG: ' + JSON.stringify(data) + ' data.data=' + JSON.stringify(data.data.toString()));
      var lines = (data.data || '').split('\n');  
```

which shows me that the incoming `data.data` is set but is NOT a string but a an object which itself contains a `data.data`, so it's actually a `data.data.data`:

```
DEBUUUUUUUUUG: {"at":1447161081557,"data":{"type":"Buffer","data":[123,34,118,34,58,48,44,34,108,101,118,101,108,34,58,50,48,44,34,110,97,109,101,34,58,34,110,101,119,114,101,108,105,99,34,44,34,104,111,115,116,110,97,109,101,34,58,34,72,66,86,56,51,48,51,50,54,54,55,34,44,34,112,105,100,34,58,51,49,56,51,44,34,116,105,109,101,34,58,34,50,48,49,53,45,49,49,45,49,48,84,49,51,58,49,49,58,50,49,46,53,53,54,90,34,44,34,109,115,103,34,58,34,76,111,97,100,105,110,103,32,97,103,101,110,116,32,102,114,111,109,32,47,85,115,101,114,115,47,106,101,110,115,46,107,114,101,102,101,108,100,116,47,68,101,118,101,108,111,112,109,101,110,116,47,83,111,117,114,99,101,115,47,110,111,100,101,106,115,47,98,100,117,45,110,111,100,101,45,114,101,115,116,45,115,101,114,118,105,99,101,45,116,101,109,112,108,97,116,101,47,110,111,100,101,95,109,111,100,117,108,101,115,47,98,100,117,45,110,111,100,101,45,110,101,119,114,101,108,105,99,47,110,111,100,101,95,109,111,100,117,108,101,115,47,110,101,119,114,101,108,105,99,34,125,10]},"process":{"pm_id":0,"name":"bdu-node-rest-service-template-1.1.0","rev":"392b26a76ca7fa186b2dc51674fab5884aae938c"}} data.data="[object Object]"
```

Since we use _newrelic_ module it seems this strange object which I printed out is in the context of it because the error occurs right after the _newrelic_ plugin was added by `require('newrelic')` at the top of Node.js script _www_ which is loaded by PM2 programmatically (using a `pm2.start({...}, cb)` in the callback of `pm2.connect(cb)`, ...you know). 

Another hint for that is that when I place the `require('newrelic')` inside the the `cb` of `pm2.start({...}, cb)` the error disappear.

Anyway, I don't know why the latter happens, but we an issue here that some other code could provoke such objects comming to line 97 which are _not_ a string (which is assumed by this)!

I can assume that for performance reasons there is not a a `typeof` check, but for the sake of more robustness I would propose to do a check or use even use a JSON.stringify(data.data) to prevent such situations. Unfortunately, this issue  prevents us from using the newest version.

What do you think?

If you need more information pls let me know...

Thx, Jens

**Comment by soyuka** [comment]
Closing in favor of #1765
