### ISSUE TITLE
Errored start app in windows

### ISSUE THREAD

**Issue by men232** [Unitech/pm2#1768]
Hey guys, you have created a great project, THX.
I have error when trying start app in windows. So.. this error displayed when i used coffe interpreter.

Error: spawn coffee ENOENT
    at exports._errnoException (util.js:860:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:450:9)
    at process._tickDomainCallback (node.js:405:17)

Also have a problem with passing arguments to my application. All arguments after -- passing to pm2 environment.

**Comment by soyuka** [comment]
Can you provide the command or the `ecosystem.json` file?

**Comment by men232** [comment]
When trying generate ecosystem file:
```
C:\>pm2 ecosystem
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at Object.CLI.generateSample (C:\Users\VM_Win7\AppData\Roaming\npm\node_modules\pm2\lib\CLI.js:1385:27)
    at Command.<anonymous> (C:\Users\VM_Win7\AppData\Roaming\npm\node_modules\pm2\bin\pm2:528:9)
    at Command.listener (C:\Users\VM_Win7\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (C:\Users\VM_Win7\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:615:12)
    at Command.parse (C:\Users\VM_Win7\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:458:21)
    at beginCommandProcessing (C:\Users\VM_Win7\AppData\Roaming\npm\node_modules\pm2\bin\pm2:118:13)
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at Object.CLI.generateSample (C:\Users\VM_Win7\AppData\Roaming\npm\node_modules\pm2\lib\CLI.js:1389:38)
    at Command.<anonymous> (C:\Users\VM_Win7\AppData\Roaming\npm\node_modules\pm2\bin\pm2:528:9)
    at Command.listener (C:\Users\VM_Win7\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (C:\Users\VM_Win7\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:615:12)
    at Command.parse (C:\Users\VM_Win7\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:458:21)
    at beginCommandProcessing (C:\Users\VM_Win7\AppData\Roaming\npm\node_modules\pm2\bin\pm2:118:13)
```

**Comment by Unitech** [comment]
`process.env.PWD` does not exists under Windows? I cannot see what should not work on that line https://github.com/Unitech/pm2/blob/master/lib/CLI.js#L1385

**Comment by arieljannai** [comment]
@Unitech I just wanted to open an issue about that, and came across it.
In windows `process.cwd()` is working instead of `process.env.PWD` that returns `undefined`.
So using `process.env.PWD || process.cwd()` will work great!

**Comment by choxnox** [comment]
I can confirm this issue exists on my dev configuration running Windows 10.

**Comment by GauthamYerroju** [comment]
I also ran into the same error as @men232 on Windows.

**Comment by frankred** [comment]
Same with me => Windows7 
v1.1.2

**Comment by vmarchaud** [comment]
Work with `pm2@next`, as @arieljannai explained, process.cwd() works great.
