### ISSUE TITLE
App does not start with pm2 start command

### ISSUE THREAD

**Issue by giovanniroos** [Unitech/pm2#1780]
Hi,

system info:
o/s: windows 7
node version: 0.12.7
npm version: 3.4.1

I have successfully installed pm2 with npm and uses your bufallo app. 

![image](https://cloud.githubusercontent.com/assets/846781/11294980/6aec0206-8f70-11e5-9dca-f3c9bafd57eb.png)

But the bufallo app does not start with ps2 from the commandline:

![image](https://cloud.githubusercontent.com/assets/846781/11294918/f613d24c-8f6f-11e5-899c-b4e85dfb0bac.png)

If I use: node app.js then it starts up correctly and works correctly:

![image](https://cloud.githubusercontent.com/assets/846781/11294928/09502572-8f70-11e5-8c4a-534dc3d02c01.png)

Here is a screen cap from the keymetrics dashboard:

![image](https://cloud.githubusercontent.com/assets/846781/11294926/00efc4d2-8f70-11e5-8911-6faacd2d8441.png)

Which confims that there is no apps running.

What am I doing wrong?

Thank you

**Comment by Unitech** [comment]
Could you show me the pm2.logs (HOMEPATH/.pm2/pm2.log)

**Comment by giovanniroos** [comment]
Hi,

From the logs (shown below) the issue is this:

1) D:\users\giovanni1\pm2\logs    (actual in windows)
2) D:\Users\giovanni1\.pm2\logs   (trying to access but does not find)

It seems in windows the '.' infront of the folder cause the issue. The folder in win7 is marked as 'hidden' but does not have the '.' infront and therefore does not find it.

Any ideas how to quick fix this?

=======error from log file=====
2015-11-24 15:52:16: Trace: [Error: can not create directories (logs/pids):ENOENT, no such file or directory 'D:\Users\giovanni1\.pm2\logs']
    at Object.God.logAndGenerateError (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\pm2\lib\God\Methods.js:45:15)
    at C:\Users\giovanni1\AppData\Roaming\npm\node_modules\pm2\lib\God\ForkMode.js:86:13
    at Object.module.exports.startLogging (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\pm2\lib\Utility.js:93:14)
    at Object.forkMode (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\pm2\lib\God\ForkMode.js:84:13)
    at Object.executeApp (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\pm2\lib\God.js:197:9)
    at ex (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\pm2\lib\God.js:368:18)
    at prepare (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\pm2\lib\God.js:374:7)
    at Server.onmessage (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon-rpc\lib\server.js:105:6)
    at RepSocket.emit (events.js:110:17)
    at Parser.<anonymous> (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon\lib\sockets\rep.js:51:15)

**Comment by giovanniroos** [comment]
Hi
After closer inspection i found the following: 
Error from the logs:
Trace: [Error: can not create directories (logs/pids):ENOENT, no such file or directory 'D:\Users\giovanni1\.pm2\logs']

If the drive (D:\) above changes to C:\ it wourld work because the directory '.pm2' exists on that path:

![image](https://cloud.githubusercontent.com/assets/846781/11390369/26281584-9352-11e5-81cd-cdb16746a8cb.png)

However it tries to write to a directory on the D: drive:

![image](https://cloud.githubusercontent.com/assets/846781/11390409/86aecd26-9352-11e5-85a7-0dc38f7218f6.png)

**Comment by giovanniroos** [comment]
Hi

I got the issue fixed.

1) I added a '.pm2' folder with the CL to D:\users\giovanni1\.pm2
2) I added a 'logs' folder to C:\Users\giovanni1\.pm2

![image](https://cloud.githubusercontent.com/assets/846781/11390569/2118d7de-9354-11e5-9c82-ec166ef7b3c8.png)
