### ISSUE TITLE
pm2 breaking and deleting from pm2 list

### ISSUE THREAD

**Issue by robcalcroft** [Unitech/pm2#1814]
I create my servers and then leave them running on my server. The next day I've come back to it and pm2 is not running and has removed all of the servers :fearful:

**Comment by Unitech** [comment]
Could you copy paste ~/.pm2/pm2.log here thanks

**Comment by robcalcroft** [comment]
Apologies, i've looked in the log and it looks like the server ran out out memory and pm2 must've died:
```
2015-12-02 16:00:02: [PM2][WORKER] Error caught by domain:
Error: spawn ENOMEM
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at exports.spawn (child_process.js:746:9)
    at Object.exports.execFile (child_process.js:628:15)
    at exports.exec (child_process.js:591:18)
    at getUrl (/usr/lib/node_modules/pm2/node_modules/vizion/lib/git.js:18:5)    at fn (/usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:363:15)
2015-12-02 16:15:02: [PM2][WORKER] Error caught by domain:
Error: spawn ENOMEM
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at exports.spawn (child_process.js:746:9)
    at Object.exports.execFile (child_process.js:628:15)
    at exports.exec (child_process.js:591:18)
    at getUrl (/usr/lib/node_modules/pm2/node_modules/vizion/lib/git.js:18:5)
    at fn (/usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:363:15)
FATAL ERROR: Evacuation Allocation failed - process out of memory
2015-12-03 20:44:26: [PM2][WORKER] Started with refreshing interval: 30000
2015-12-03 20:44:26: [[[[ PM2/God daemon launched ]]]]
2015-12-03 20:44:26: BUS system [READY] on port /home/rob/.pm2/pub.sock
2015-12-03 20:44:26: RPC interface [READY] on port /home/rob/.pm2/rpc.sock
2015-12-03 20:53:01: PM2 is being killed via kill method
2015-12-03 20:53:01: RPC socket closed
2015-12-03 20:53:01: PUB socket closed
2015-12-03 20:53:14: [PM2][WORKER] Started with refreshing interval: 30000
2015-12-03 20:53:14: [[[[ PM2/God daemon launched ]]]]
2015-12-03 20:53:14: BUS system [READY] on port /home/rob/.pm2/pub.sock
2015-12-03 20:53:14: RPC interface [READY] on port /home/rob/.pm2/rpc.sock
2015-12-03 21:18:12: Starting execution sequence in -fork mode- for app name:me id:0
2015-12-03 21:18:12: App name:me id:0 online
2015-12-03 21:20:46: Starting execution sequence in -fork mode- for app name:me id:1
2015-12-03 21:20:46: App name:me id:1 online
2015-12-03 21:20:47: App name:me id:1 exited with code 255
2015-12-03 21:20:47: Starting execution sequence in -fork mode- for app name:me id:1
2015-12-03 21:20:47: App name:me id:1 online
2015-12-03 21:20:47: App name:me id:1 exited with code 255
2015-12-03 21:20:47: Starting execution sequence in -fork mode- for app name:me id:1
2015-12-03 21:20:47: App name:me id:1 online
2015-12-03 21:20:47: App name:me id:1 exited with code 255
```
The file is v long so not posting entire thing. The rest looks very similar to the above except for this:
```
2015-12-03 21:23:03: Trace: [Error: 2 : id unknown]
    at Object.God.logAndGenerateError (/usr/lib/node_modules/pm2/lib/God/Methods.js:45:15)
    at /usr/lib/node_modules/pm2/lib/God/ActionMethods.js:373:30
    at Object.God.stopProcessId (/usr/lib/node_modules/pm2/lib/God/ActionMethods.js:236:14)
    at God.deleteProcessId (/usr/lib/node_modules/pm2/lib/God/ActionMethods.js:372:9)
    at Server.onmessage (/usr/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:105:6)
    at RepSocket.emit (events.js:98:17)
    at Parser.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/rep.js:51:15)
    at Parser.emit (events.js:95:17)
    at Parser._write (/usr/lib/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:226:10)
```
One of my Node servers `me.js` has had issues of its own unrelated to this which may be reflected in some of these logs.

**Comment by robcalcroft** [comment]
It has been working fine ever since I reduced the amount of Node servers running

**Comment by Unitech** [comment]
Alright you are tight on memory, internally in PM2 it looks like it comes from the versioning data parsing.

You can add the option --no-vizion to avoid this memory overhead

**Comment by robcalcroft** [comment]
Cool thanks for your help! Would the `--no-vizion` need to be applied for each server when I run `pm2 start server.js`
