### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by sovattha** [Unitech/pm2#1831]
Hi,

I am running with the following environment:
pm2 version: 0.15.10
node version: 0.12.7
OS: WIndows 8.1

I wanted to start on my local machine the Node application [http-master](https://www.npmjs.com/package/http-master) through pm2, as I already did successfully on my Unix servers.

Here is my `http-master-local.json` file:

```
{
  "apps": [{
    "name": "http-master-local",
    "script": "http-master",
    "args": ["--config=http-master-local.conf"],
    "watch": false,
    "node_args": "",
    "merge_logs": true,
    "cwd": "C:/dev/http-master"
  }]
}
```

Then, when I execute: `pm2 start http-master-local.json`.
I get the following errors in the error log file:

```
C:\Users\sso\AppData\Roaming\npm\http-master:2
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.<anonymous> (C:\Users\sso.IEMNET\AppData\Roaming\npm\node_modules\pm2\node_modules\pmx\lib\transaction.js:62:21)
    at Object.<anonymous> (C:\Users\sso.IEMNET\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:28:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
``` 

In `pm2.log`, I can read:
```
2015-12-11 09:57:48: Starting execution sequence in -fork mode- for app name:http-master-local id:1
2015-12-11 09:57:48: App name:http-master-local id:1 online
2015-12-11 09:57:49: App name:http-master-local id:1 exited with code 255
2015-12-11 09:57:49: Script C:\Users\sso\AppData\Roaming\npm\http-master had too many unstable restarts (15). Stopped. "errored"
2015-12-11 09:58:24: Stopping app:http-master-local id:1
```

Do you have any idea how I could get this work?

Thank you,
Sovattha

**Comment by soyuka** [comment]
Templates needs `--harmony` on node < 4. Or use node 4.x+

**Comment by sovattha** [comment]
Thank you.

I tried to add the argument `--harmony` either from the command line:
```
pm2 start pp-http-master-local.json --node-args="--harmony"
```

or in the JSON file:

```
{
  "apps": [{
    "name": "http-master-local",
    "script": "http-master",
    "args": ["--config=http-master-local.conf"],
    "watch": false,
    "node_args": "--harmony",
    "merge_logs": true,
    "cwd": "C:/dev/http-master"
  }]
}
```

but the problem is still the same (SyntaxError: Unexpected token ILLEGAL).

Shall I mention again that with my Unix server, pm2 with http-master works properly, and I am also using Node 0.12.7 there?

I might consider upgrading to Node 4+ if you think this can help.

**Comment by soyuka** [comment]
Actually I'm not sure that node `0.12.7` supports templates with or without harmony. Json and cli usage is correct.

Not related to pm2, closing.

**Comment by sovattha** [comment]
I am sorry, but the problem is not solved yet.
I have upgraded Node to version 4.2.3 and the problem is now different. I create another issue.
