### ISSUE TITLE
SyntaxError: Unexpected token case on Windows 8.1

### ISSUE THREAD

**Issue by sovattha** [Unitech/pm2#1833]
Hi,

this issue is consecutive to [this one](https://github.com/Unitech/pm2/issues/1831) which was solved by upgrading node from 0.12.7 to 4.2.3. 

I am using Windows 8.1 and I know pm2 is still in beta version for Windows.

Here is my environment:
pm2 version: 0.15.10
node version: 4.2.3
OS: WIndows 8.1

I want to start on my local machine the Node application [http-master](https://www.npmjs.com/package/http-master) through pm2, as I already did successfully on my Unix servers.

Here is my http-master-local.json file:

```
{
  "apps": [{
    "name": "http-master-local",
    "script": "http-master",
    "args": ["--config=http-master-local.conf"],
    "watch": false,
    "node_args": "--harmony",
    "merge_logs": true,
    "cwd": "C:/dev/http-master"
  }]
}
```

Then, when I execute: pm2 start http-master-local.json.
I get the following errors in the error log file:

```
SyntaxError: Unexpected token case
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function._load (C:\Users\sso\AppData\Roaming\npm\node_modules\pm2\node_modules\pmx\lib\transaction.js:62:21)
    at Object.<anonymous> (C:\Users\sso\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:28:21)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

Would you have any advice on how to solve this issue?

**Comment by soyuka** [comment]
```
SyntaxError: Unexpected token case
```

You've written a bad `switch` IMO.

**Comment by sovattha** [comment]
Any update so far?

@soyuka I did not write any code. Just trying to run pm2 with http-master.

**Comment by sovattha** [comment]
Ok 7 months later, I guess it is better I do not rely on pm2 to run http-master.
I moved to Apache as a proxy...

**Comment by vmarchaud** [comment]
duplicate #2037 currently investing for a fix.
