### ISSUE TITLE
pm2 doesn't start cluster if it's not on the first running after pm2 kill

### ISSUE THREAD

**Issue by arieljannai** [Unitech/pm2#1863]
I have some weird issues - pm2 doesn't start cluster if it's not on the first running after `pm2 kill`.

When I'm trying to start a cluster (with `ecosystem.json` or `-i num`) it partially works and only if it's immediately after pm2 starts. didn't have any issues with `fork` mode.
I've tried adding the debugging flags as suggested in [CONTRIBUTING.md](https://github.com/Unitech/pm2/blob/master/CONTRIBUTING.md), and I've noticed some things:
- If running with --no-daemon all works
- If not:
  - First run - only one instance of the cluster is up
  - Later - none of them. it just doesn't do anything.

log for `pm2 kill` and then `pm2 start ecosystem.json`

```
2015-12-28 11:46:34: PM2 is being killed via kill method
2015-12-28 11:46:34: RPC socket closed
2015-12-28 11:46:34: PUB socket closed
2015-12-28 11:46:42: [PM2][WORKER] Started with refreshing interval: 30000
2015-12-28 11:46:42: [[[[ PM2/God daemon launched ]]]]
2015-12-28 11:46:42: BUS system [READY] on port \\.\pipe\pub.sock
2015-12-28 11:46:42: RPC interface [READY] on port \\.\pipe\rpc.sock
2015-12-28 11:46:42: Starting execution sequence in -cluster mode- for app name:test-server id:0
2015-12-28 11:46:42: App name:test-server id:0 online
2015-12-28 11:46:42: Starting execution sequence in -cluster mode- for app name:test-server id:1
2015-12-28 11:46:42: Trace: { [Error: spawn EBADF] code: 'EBADF', errno: 'EBADF', syscall: 'spawn' }
    at Object.God.logAndGenerateError (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God\Methods.js:45:15)
    at Object.nodeApp (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God\ClusterMode.js:52:11)
    at Object.executeApp (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God.js:145:9)
    at ex (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God.js:368:18)
    at C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God.js:372:16
    at Worker.cluOnline (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God.js:188:17)
    at Worker.g (events.js:199:16)
    at Worker.emit (events.js:104:17)
    at online (cluster.js:449:12)
    at Worker.onmessage (cluster.js:436:7)
2015-12-28 11:46:42: Starting execution sequence in -cluster mode- for app name:test-server id:2
2015-12-28 11:46:42: Trace: { [Error: spawn EBADF] code: 'EBADF', errno: 'EBADF', syscall: 'spawn' }
    at Object.God.logAndGenerateError (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God\Methods.js:45:15)
    at Object.nodeApp (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God\ClusterMode.js:52:11)
    at Object.executeApp (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God.js:145:9)
    at ex (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God.js:368:18)
    at C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God.js:369:25
    at nodeApp (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God.js:146:29)
    at Object.nodeApp (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God\ClusterMode.js:53:14)
    at Object.executeApp (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God.js:145:9)
    at ex (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God.js:368:18)
    at C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God.js:372:16
2015-12-28 11:46:42: Starting execution sequence in -cluster mode- for app name:test-server id:3
2015-12-28 11:46:42: Trace: { [Error: spawn EBADF] code: 'EBADF', errno: 'EBADF', syscall: 'spawn' }
    at Object.God.logAndGenerateError (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God\Methods.js:45:15)
    at Object.nodeApp (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God\ClusterMode.js:52:11)
    at Object.executeApp (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God.js:145:9)
    at ex (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God.js:368:18)
    at C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God.js:369:25
    at nodeApp (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God.js:146:29)
    at Object.nodeApp (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God\ClusterMode.js:53:14)
    at Object.executeApp (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God.js:145:9)
    at ex (C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God.js:368:18)
    at C:\Users\ariel.j\AppData\Roaming\npm\node_modules\pm2\lib\God.js:369:25
```

_`OS: Windows 7 x64`_
_`Node version: v0.12.4`_
_`PM2 version: 0.15.10`_

Any more information that I can supply that will be helpful?

**Comment by arieljannai** [comment]
My `server.js`:
Using random port to start at, so I can easily start a cluster with no port conflicts
```javascript
var express = require('express');
var app = express();

function randomIntInc (low, high) {
    return Math.floor(Math.random() * (high - low + 1) + low);
}

app.get('/', function(req, res) {
	res.send("hey you");
	console.log("i said hey to someone");
});

var server = app.listen(randomIntInc(3100, 3199), function() {
	var host = server.address().address;
	var port = server.address().port;
	console.log("testing! listening at http://%s:%s", host, port);
});
```

The `ecosystem.json`:

```javascript
{
  apps : [

    // First application
    {
      name      : "test-server",
      script    : "server.js",
      instances : 0,
      exec_mode : "cluster",
      cwd       : "c:\\dev\\file-utils-test",
    }
  ]
}
```

**Comment by arieljannai** [comment]
_Example:
Fork works great, and cluster doe's nothing._
![1](https://cloud.githubusercontent.com/assets/3811594/12018505/5f48f98a-ad6c-11e5-893b-e140c8a1020d.PNG)

**Comment by poyannabati** [comment]
Maybe an associated issue?

If after kill I run 
`pm2 start main.js -i 0`
`pm2 stop all`
`pm2 start main.js -i 3`

Then pm2 starts MAX processes again.

**Comment by arieljannai** [comment]
@poyannabati Unfortunately I receive the same result :pensive:

**Comment by arieljannai** [comment]
@Unitech Please tell me if you want me to check something that might help
