### ISSUE TITLE
Error When "pm2 pull app"

### ISSUE THREAD

**Issue by bangbang93** [Unitech/pm2#1867]
```bash
[cofactories@10-10-101-5 cofactories]$ pm2 pull cofactories
[PM2] Updating repository for process name cofactories
[PM2] Process successfully updated cofactories
[PM2] Current commit edbc6727398ffa40fd78a7c6e47df1e3879fcc75
[PM2] Reloading process by name cofactories
Error: Process with pid 31078 already exists
    at Object.God.logAndGenerateError (/home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/lib/God/Methods.js:50:12)
    at Object.God.startProcessId (/home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/lib/God/ActionMethods.js:218:21)
    at Object.God.restartProcessId (/home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/lib/God/ActionMethods.js:424:18)
    at God.reloadProcessId (/home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/lib/God/Reload.js:198:18)
    at Server.onmessage (/home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:105:6)
    at emitTwo (events.js:87:13)
    at RepSocket.emit (events.js:172:7)
    at Parser.<anonymous> (/home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/rep.js:51:15)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
/home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/lib/tools/VersionManagement.js:61
                if (err) return cb(err);
                                ^

TypeError: cb is not a function
    at /home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/lib/tools/VersionManagement.js:61:33
    at /home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/lib/CLI.js:1034:21
    at /home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/node_modules/async/lib/async.js:52:16
    at /home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/node_modules/async/lib/async.js:322:29
    at /home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/node_modules/async/lib/async.js:44:16
    at /home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/lib/CLI.js:1024:18
    at /home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:42:7
    at Parser.<anonymous> (/home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)

```

and here is pm2.log
```
2015-12-31 14:28:22: Change detected on path modules/market.js for app cofactories - restarting
2015-12-31 14:28:22: Stopping app:cofactories id:16
2015-12-31 14:28:22: App name:cofactories id:16 disconnected
2015-12-31 14:28:22: Process in a stopped status, starting it
2015-12-31 14:28:22: Process with pid 31078 already exists
2015-12-31 14:28:22: App name:cofactories id:16 exited with code SIGTERM
2015-12-31 14:28:22: Process with pid 31078 killed
2015-12-31 14:28:22: Starting execution sequence in -cluster mode- for app name:cofactories id:16
2015-12-31 14:28:22: App name:cofactories id:16 online

```

**Comment by Unitech** [comment]
thanks for reporting! fixed
