### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by dszymczuk** [Unitech/pm2#1871]
TypeError: Cannot read property 'replace' of undefined
    at /root/.pm2/node_modules/pm2-server-monit/lib/drive.js:22:35
    at ChildProcess.exithandler (child_process.js:194:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

**Comment by Unitech** [comment]
Could you please report the issue here, thanks: https://github.com/pm2-hive/pm2-server-monit
