### ISSUE TITLE
Unable to install PM2 using the zip or NPM

### ISSUE THREAD

**Issue by spawnrider** [Unitech/pm2#1906]
When I try to install to install PM2 from a local folder (downloaded from Github) or using NPM, I am facing this issue : 
```
λ npm install -g C:\Users\YC2D8A8N\Téléchargement\pm2-master
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:818:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:469:12)
npm WARN addRemoteGit  git+http://ikt.pm2.io/ikt.git#master resetting remote C:\Users\YC2D8A8N\AppData\Roaming\npm-cache\_git-remotes\git-http-ikt-pm2-io-ikt-git-master-d352a2a2 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! registry error parsing json
npm ERR! git clone --template=C:\Users\YC2D8A8N\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror http://ikt.pm2.io/ikt.git C:\Users\YC2D8A8N\AppData\Roaming\npm-cache\_git-remotes\git-http-ikt-pm2-io-ikt-git-master-d352a2a2: Cloning into bare repository 'C:\Users\YC2D8A8N\AppData\Roaming\npm-cache\_git-remotes\git-http-ikt-pm2-io-ikt-git-master-d352a2a2'...
npm ERR! git clone --template=C:\Users\YC2D8A8N\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror http://ikt.pm2.io/ikt.git C:\Users\YC2D8A8N\AppData\Roaming\npm-cache\_git-remotes\git-http-ikt-pm2-io-ikt-git-master-d352a2a2: fatal: unable to access 'http://ikt.pm2.io/ikt.git/': Received HTTP code 403 from proxy after CONNECT
npm WARN optional Skipping failed optional dependency /pm2/ikt:
npm WARN Command failed: git -c core.longpaths=true clone --template=C:\Users\YC2D8A8N\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror http://ikt.pm2.io/ikt.git C:\Users\YC2D8A8N\AppData\Roaming\npm-cache\_git-remotes\git-http-ikt-pm2-io-ikt-git-master-d352a2a2
npm WARN Cloning into bare repository 'C:\Users\YC2D8A8N\AppData\Roaming\npm-cache\_git-remotes\git-http-ikt-pm2-io-ikt-git-master-d352a2a2'...
npm WARN fatal: unable to access 'http://ikt.pm2.io/ikt.git/': Received HTTP code 403 from proxy after CONNECT
npm WARN
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\YC2D8A8N\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "C:\\Users\\YC2D8A8N\\Téléchargement\\pm2-master"
npm ERR! node v4.2.4
npm ERR! npm  v3.5.3
```
This is due to an 404 error on this repository : http://ikt.pm2.io/ikt.git/

How can I override this ?

**Comment by spawnrider** [comment]
Ok, I just found that this dependency is only used for statistic usage and is not mandatory for running PM2. 
BTW, You can install PM2 using : `npm install pm2 -g --no-optional`
