### ISSUE TITLE
cli command `pm2 logs` sometimes crashes with error

### ISSUE THREAD

**Issue by pleaseshutup** [Unitech/pm2#1964]
/usr/local/lib/node_modules/pm2/lib/Log.js:97
      var lines = (data.data || '').split('\n');
                                    ^

TypeError: (data.data || "").split is not a function
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Log.js:97:37)
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/sub-emitter.js:52:19)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser._write (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Parser.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (_stream_readable.js:525:20)
    at emitOne (events.js:77:13)

**Comment by peterchoo** [comment]
I'm also getting this error:

```
/usr/local/lib/node_modules/pm2/lib/Log.js:97
      var lines = (data.data || '').split('\n');
                                    ^
TypeError: undefined is not a function
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Log.js:97:37)
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/sub-emitter.js:52:19)
    at Parser.emit (events.js:107:17)
    at Parser._write (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Parser.Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
```

It would seem that `data.data` is not a string or falsey value.

**Comment by jasonstaczek** [comment]
Also getting the error here when I use "throw".

**Comment by vmarchaud** [comment]
what's your node/pm2 version @jasonstaczek ?

**Comment by vmarchaud** [comment]
duplicate #1752
