### ISSUE TITLE
Wrong behavior of watch option

### ISSUE THREAD

**Issue by zim32** [Unitech/pm2#1967]
PM2 is trying to watch all files from the CWD, not the application root folder.

cd /
pm2 start -n app -i 1 /home/user/www/app/index.js --watch

tail -f ~/.pm2/pm2.log

```
2016-02-24 10:06:57: Error: watch /usr/include/c++/4.9.2/valarray ENOSPC
    at exports._errnoException (util.js:870:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:82:15)
2016-02-24 10:06:57: Error: watch /usr/include/c++/4.9.2/vector ENOSPC
    at exports._errnoException (util.js:870:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/usr/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by soyuka** [comment]
It's intended, please use a value for your watch argument to specify a path.

**Comment by zim32** [comment]
You should fix your help doc. No parameters..

`--watch                              watch application folder for changes`

**Comment by Unitech** [comment]
Error: watch /usr/include/c++/4.9.2/valarray ENOSPC
