### ISSUE TITLE
pm2 startup error on Windows 10

### ISSUE THREAD

**Issue by roccomuso** [Unitech/pm2#1988]
I'm on Windows 10, the <code>pm2 startup</code> command fails with this error:

`C:\Users\Rocco\AppData\Roaming\npm\node_modules\pm2\lib\CLI.js:562
  if (process.getuid() != 0) {
              ^
TypeError: undefined is not a function
    at Object.CLI.startup (C:\Users\Rocco\AppData\Roaming\npm\node_modules\pm2\lib\CLI.js:562:15)
    at Command.<anonymous> (C:\Users\Rocco\AppData\Roaming\npm\node_modules\pm2\bin\pm2:560:9)
    at Command.listener (C:\Users\Rocco\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:301:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (C:\Users\Rocco\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:615:12)
    at Command.parse (C:\Users\Rocco\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:458:21)
    at beginCommandProcessing (C:\Users\Rocco\AppData\Roaming\npm\node_modules\pm2\bin\pm2:121:13)
    at C:\Users\Rocco\AppData\Roaming\npm\node_modules\pm2\bin\pm2:174:7
    at C:\Users\Rocco\AppData\Roaming\npm\node_modules\pm2\lib\Modularizer.js:268:17
    at C:\Users\Rocco\AppData\Roaming\npm\node_modules\pm2\node_modules\async\lib\async.js:52:16`

**Comment by Unitech** [comment]
Have you tried https://www.npmjs.com/package/pm2-windows-startup?

**Comment by roccomuso** [comment]
Nope, but why do I get that error?

**Comment by Unitech** [comment]
Maybe an old Node.js version, anyway PM2 builtin startup script generation does not support Windows, you have to refer to the two previous modules

**Comment by Unitech** [comment]
closed in favor of https://github.com/Unitech/pm2/issues/2559
