### ISSUE TITLE
PM2 1.0.2 seems have compatibility issue with babel-require

### ISSUE THREAD

**Issue by timnew** [Unitech/pm2#2005]
I'm using `PM2 1.0.2` on my production environment, but after deployment. The server yields error that seems `babel-require` hook doesn't work at all:

```
tickets-server-0 /home/suoper/node/tickets/source/apps/startApp.js:18
tickets-server-0   const port = parseInt(val, 10);
tickets-server-0
tickets-server-0
tickets-server-0 ^
tickets-server-0 ^
tickets-server-0 ^
tickets-server-0 ^
tickets-server-0 ^
tickets-server-0 SyntaxError: Use of const in strict mode.
tickets-server-0     at Module._compile (module.js:439:25)
tickets-server-0     at loader (/home/suoper/node/tickets/source/node_modules/babel-register/lib/node.js:126:5)
tickets-server-0     at Object.require.extensions.(anonymous function) [as .js] (/home/suoper/node/tickets/source/node_modules/babel-register/lib/node.js:136:7)
tickets-server-0     at Module.load (module.js:356:32)
tickets-server-0     at Function.Module._load (module.js:312:12)
tickets-server-0     at Function._load (/usr/local/node-v5.7.1-linux-x64/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
tickets-server-0     at Module.require (module.js:364:17)
tickets-server-0     at require (module.js:380:17)
tickets-server-0     at Object.<anonymous> (/home/suoper/node/tickets/source/bin/server:5:1)
tickets-server-0     at Module._compile (module.js:456:26)
tickets-server-0     at Object.Module._extensions..js (module.js:474:10)
tickets-server-0     at Module.load (module.js:356:32)
tickets-server-0     at Function.Module._load (module.js:312:12)
tickets-server-0     at Function._load (/usr/local/node-v5.7.1-linux-x64/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
tickets-server-0     at Object.<anonymous> (/usr/local/node-v5.7.1-linux-x64/lib/node_modules/pm2/lib/ProcessContainerFork.js:41:21)
tickets-server-0     at Module._compile (module.js:456:26)
tickets-server-0     at Object.Module._extensions..js (module.js:474:10)
tickets-server-0     at Module.load (module.js:356:32)
tickets-server-0     at Function.Module._load (module.js:312:12)
tickets-server-0     at Function.Module.runMain (module.js:497:10)
tickets-server-0     at startup (node.js:119:16)
tickets-server-0     at node.js:935:3
```

Then I tried to add `DEBUG=*` to pm2 `env`, to display Babel debugging info while the app starts, and I did observe the compiling info displayed.

So the reason must be `require-hook` doesn't work as expected due to some reason.

Then I downgrade `PM2` to `0.15.10`, and the server starts fine.

So I suspect that `PM2 1.0.2` have compatibility issue with `babel-require`

**Comment by timnew** [comment]
Tried several approach to start process, found this issue only occurs while start process via `pm2 start ecosystem.json`

What I see is that babel require hook doesn't work

```
tickets-www-0 /home/suoper/node/tickets/source/apps/startApp.js:38
tickets-www-0   server.on('error', error => {
tickets-www-0                             ^
tickets-www-0 SyntaxError: Unexpected token >
tickets-www-0     at Module._compile (module.js:439:25)
tickets-www-0     at loader (/home/suoper/node/tickets/source/node_modules/babel-register/lib/node.js:126:5)
tickets-www-0     at Object.require.extensions.(anonymous function) [as .js] (/home/suoper/node/tickets/source/node_modules/babel-register/lib/node.js:136:7)
tickets-www-0     at Module.load (module.js:356:32)
tickets-www-0     at Function.Module._load (module.js:312:12)
tickets-www-0     at Function._load (/usr/local/node-v5.7.1-linux-x64/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
tickets-www-0     at Module.require (module.js:364:17)
tickets-www-0     at require (module.js:380:17)
tickets-www-0     at Object.<anonymous> (/home/suoper/node/tickets/source/bin/www:5:1)
tickets-www-0     at Module._compile (module.js:456:26)
tickets-www-0     at Object.Module._extensions..js (module.js:474:10)
tickets-www-0     at Module.load (module.js:356:32)
tickets-www-0     at Function.Module._load (module.js:312:12)
tickets-www-0     at Function._load (/usr/local/node-v5.7.1-linux-x64/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
tickets-www-0     at Object.<anonymous> (/usr/local/node-v5.7.1-linux-x64/lib/node_modules/pm2/lib/ProcessContainerFork.js:28:21)
tickets-www-0     at Module._compile (module.js:456:26)
tickets-www-0     at Object.Module._extensions..js (module.js:474:10)
tickets-www-0     at Module.load (module.js:356:32)
tickets-www-0     at Function.Module._load (module.js:312:12)
tickets-www-0     at Function.Module.runMain (module.js:497:10)
tickets-www-0     at startup (node.js:119:16)
tickets-www-0     at node.js:935:3
tickets-www-0 /home/suoper/node/tickets/source/apps/startApp.js:38
tickets-www-0   server.on('error', error => {
tickets-www-0                             ^
tickets-www-0 SyntaxError: Unexpected token >
tickets-www-0     at Module._compile (module.js:439:25)
tickets-www-0     at loader (/home/suoper/node/tickets/source/node_modules/babel-register/lib/node.js:126:5)
tickets-www-0     at Object.require.extensions.(anonymous function) [as .js] (/home/suoper/node/tickets/source/node_modules/babel-register/lib/node.js:136:7)
tickets-www-0     at Module.load (module.js:356:32)
tickets-www-0     at Function.Module._load (module.js:312:12)
tickets-www-0     at Function._load (/usr/local/node-v5.7.1-linux-x64/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
tickets-www-0     at Module.require (module.js:364:17)
tickets-www-0     at require (module.js:380:17)
tickets-www-0     at Object.<anonymous> (/home/suoper/node/tickets/source/bin/www:5:1)
tickets-www-0     at Module._compile (module.js:456:26)
tickets-www-0     at Object.Module._extensions..js (module.js:474:10)
tickets-www-0     at Module.load (module.js:356:32)
tickets-www-0     at Function.Module._load (module.js:312:12)
tickets-www-0     at Function._load (/usr/local/node-v5.7.1-linux-x64/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
tickets-www-0     at Object.<anonymous> (/usr/local/node-v5.7.1-linux-x64/lib/node_modules/pm2/lib/ProcessContainerFork.js:28:21)
tickets-www-0     at Module._compile (module.js:456:26)
tickets-www-0     at Object.Module._extensions..js (module.js:474:10)
tickets-www-0     at Module.load (module.js:356:32)
tickets-www-0     at Function.Module._load (module.js:312:12)
tickets-www-0     at Function.Module.runMain (module.js:497:10)
tickets-www-0     at startup (node.js:119:16)
tickets-www-0     at node.js:935:3
```

To fix the issue, just `pm2 restart`

**Comment by Unitech** [comment]
Thanks for reporting,

Have you tried with PM2 1.0.1?
Do you have a startApp.js.map in the same folder?

**Comment by timnew** [comment]
I tried `1.0.2` and `0.15.10`, both have similar issues.
`startApp.js` is written in ES6 + Stage-0 features, which should be loaded via `babel-require`. 
I don't have any `source map` file since the file haven't been compiled yet.

**Comment by Unitech** [comment]
Ok I see so this is not linked with the recent source-map file support,
Could you please show me a part of your `ecosystem.json` file and the beginning of your `startApp.js` file? I will try to reproduce locally

**Comment by timnew** [comment]
Sure, here is the app part
```
{
"apps": [{
    "name": "tickets-www",
    "script": "/home/suoper/node/tickets/current/bin/www",
    "cwd": "/home/suoper/node/tickets/current",
    "env": {
      "API_SERVER": "http://192.168.105.2:3001",
      "API_PORT": 3001,
      "WWW_SERVER": "http://192.168.105.2:3000",
      "WWW_PORT": 3000
    }
  }, {
    "name": "tickets-api",
    "script": "/home/suoper/node/tickets/current/bin/api",
    "cwd": "/home/suoper/node/tickets/current",
    "env": {
      "API_SERVER": "http://192.168.105.2:3001",
      "API_PORT": 3001,
      "WWW_SERVER": "http://192.168.105.2:3000",
      "WWW_PORT": 3000
    },
    "qa_env": {
      "USER_PROFILE_SERVICE": "http://192.168.100.60:8080/"
    }
  }]
 ...
}
```

**Comment by timnew** [comment]
I found the app broken after use `pm2 deploy`, not matter how I config the post-deployment script. I tried `startOrRestart` and `restart all`.

And I found the app also broken if I restart the app via `pm2 start ecosystem.json`

But the issues can be fixed if I do `pm2 restart all` or `pm2 restart 0`

**Comment by Unitech** [comment]
Just tried with babel-register with PM2 1.0.2 & Node.js 4.3.0, everythin works as expected

https://github.com/Unitech/pm2-tests

Please if you see any issue tell me

**Comment by timnew** [comment]
Is that possibly caused because that I used some `stage-0` feature?

**Comment by soyuka** [comment]
yes

**Comment by Unitech** [comment]
Is that issue fixed? If it need documentation we could add a Transpiler tutorial page on PM2 documentation

**Comment by soyuka** [comment]
https://github.com/pm2-hive/pm2-hive.github.io/pull/19
