### ISSUE TITLE
Error: IPC channel is already disconnected

### ISSUE THREAD

**Issue by TOP-Chao** [Unitech/pm2#2043]
exec_mode : cluster_mode

**Comment by soyuka** [comment]
Please give more informations and/or read https://github.com/Unitech/pm2/blob/master/CONTRIBUTING.md

**Comment by TOP-Chao** [comment]
pm2: 1.0.2
node: 5.6.0
```
{
    "apps": [{
        "name": "heikuai",
        "script": "app.js",
        "watch": false,
        "env": {
            "NODE_ENV": "development"
        },
        "instances": "max",
        "exec_mode": "cluster_mode",
        "node_args": ["--harmony", "--nouse-idle-notification", "--max-old-space-size=3072"],
        "error_file": "logs/err.log"
    }]
}
```
```
Error: IPC channel is already disconnected
    at process.target.disconnect (internal/child_process.js:637:26)
    at Server.checkWaitingCount (cluster.js:696:19)
    at Server.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at Server.emit (events.js:179:7)
    at emitCloseNT (net.js:1514:8)
    at nextTickCallbackWith1Arg (node.js:464:9)
    at process._tickDomainCallback (node.js:427:17)
```
pm2.log
```
2016-03-25 14:12:44: Error: Process with pid 2228 already exists
    at Object.God.logAndGenerateError (/usr/local/lib/node_modules/pm2/lib/God/Methods.js:50:12)
    at Object.God.startProcessId (/usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:218:21)
    at /usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:418:20
    at /usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:283:18
    at null._onTimeout (/usr/local/lib/node_modules/pm2/lib/God/Methods.js:228:16)
    at Timer.listOnTimeout (timers.js:92:15)
2016-03-25 14:12:44: [PM2][WORKER] Process 2 restarted because it uses 0 memory and has ONLINE status
2016-03-25 14:12:44: Stopping app:heikuai id:2
2016-03-25 14:12:45: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:45: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:45: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:45: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:45: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:46: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:46: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:46: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:46: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:46: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:46: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:46: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:46: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:46: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:47: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:47: Process with pid 2233 still alive after 1600ms, sending it SIGKILL now...
2016-03-25 14:12:47: Process cannot be killed kill ESRCH
2016-03-25 14:12:47: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:47: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:47: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:47: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:47: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:47: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:47: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:47: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:48: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:48: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:48: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:48: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:48: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:48: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:48: Process with pid 2233 still not killed, retrying...
2016-03-25 14:12:48: Process with pid 2233 could not be killed
2016-03-25 14:12:48: Process with pid 2233 already exists
2016-03-25 14:12:48: Error: Process with pid 2233 already exists
    at Object.God.logAndGenerateError (/usr/local/lib/node_modules/pm2/lib/God/Methods.js:50:12)
    at Object.God.startProcessId (/usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:218:21)
    at /usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:418:20
    at /usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:283:18
    at null._onTimeout (/usr/local/lib/node_modules/pm2/lib/God/Methods.js:228:16)
    at Timer.listOnTimeout (timers.js:92:15)
2016-03-25 14:12:48: [PM2][WORKER] Process 3 restarted because it uses 0 memory and has ONLINE status
2016-03-25 14:12:48: Stopping app:heikuai id:3
2016-03-25 14:12:49: App name:heikuai id:3 disconnected
2016-03-25 14:12:49: App [heikuai] with id [3] and pid [2499], exited with code [0] via signal [SIGINT]
2016-03-25 14:12:49: Starting execution sequence in -cluster mode- for app name:heikuai id:3
2016-03-25 14:12:49: App name:heikuai id:3 online
2016-03-25 14:51:58: Process with pid 2219 already exists
```

**Comment by TOP-Chao** [comment]
I need your help.

**Comment by Unitech** [comment]
closing in favor of #2061
