### ISSUE TITLE
sendDataToProcessId not working

### ISSUE THREAD

**Issue by steebchen** [Unitech/pm2#2070]
When I execute the following code (almost the example code in [CONTRIBUTING.md](http://pm2.keymetrics.io/docs/usage/pm2-api/#send-message-to-process)) in `node`:

```
pm2.connect(function() {
  pm2.sendDataToProcessId({
    type : 'process:msg',
    data : {
      some : 'data',
      hello : true
    },
    id   : 0
  }, function(err, res) {
    console.log(err, res);
  });
});
```

I see the following error in the other process (with the id 0, I ran it with the debug flags):

```
01:32:58 PM2 [PM2] Error caught by domain:
01:32:58 PM2 TypeError: Cannot read property 'id' of null
01:32:58 PM2     at God.sendDataToProcessId (/usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:656:22)
01:32:58 PM2     at Server.onmessage (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:105:6)
01:32:58 PM2     at emitTwo (events.js:100:13)
01:32:58 PM2     at RepSocket.emit (events.js:185:7)
01:32:58 PM2     at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/rep.js:51:15)
01:32:58 PM2     at emitOne (events.js:90:13)
01:32:58 PM2     at Parser.emit (events.js:182:7)
01:32:58 PM2     at Parser._write (/usr/local/lib/node_modules/pm2/node_modules/amp/lib/stream.js:91:16)
01:32:58 PM2     at doWrite (_stream_writable.js:292:12)
01:32:58 PM2     at writeOrBuffer (_stream_writable.js:278:5)
01:32:58 PM2 [PM2] Trying to update PM2...
01:32:58 PM2 Stopping app:master id:0
01:32:58 PM2 App [master] with id [0] and pid [14889], exited with code [0] via signal [SIGINT]
01:32:58 PM2 [HandleExit] PM2 is being killed, stopping restart procedure...
01:32:58 PM2 PM2 is being killed via kill method
01:32:58 PM2 RPC socket closed
```

which has this code:

```
process.on('message', function(packet) {
    console.log(packet);
});
```

`pm2 --version` 1.1.1
`node --version` v5.5.0
`head -n 50 ~/.pm2/pm2.log` (there's really no useful information in this)
Linux Mint 17.2 Rafaela

**Comment by V1c70r** [comment]
I have the same error. But sendDataToProcessId works if I send in this way:

    pm2.sendDataToProcessId(
      proc[ 'pm2_env' ][ 'pm_id' ],
      {
        topic: PROCESS_EVENT,
        data: message
      }, 
      callback
    );

**Comment by Tyratox** [comment]
Any updates on this?

**Comment by h091237557** [comment]
I have same problem ~

**Comment by Unitech** [comment]
Fixed.

Changelog: [2.9.0 CHANGELOG](https://github.com/Unitech/pm2/blob/master/CHANGELOG.md#290)
Introduced in version: 2.9.0

Update procedure:

```bash
npm install pm2 -g
pm2 update
```
