### ISSUE TITLE
Error on start in ~/.pm2/agent.log

### ISSUE THREAD

**Issue by domarmstrong** [Unitech/pm2#2079]
Having issues viewing apps in keymetrics, could this be the cause?

Pm2 1.1
Ubuntu 14.04
Node 5.9.0
NPM 3.7.3

```
[Keymetrics.io] Launching agent
2016-04-08 17:30:17: Launching Interactor exposure
2016-04-08 17:30:18: [WATCHDOG] Launching
2016-04-08 17:30:18: [PUSH] Connecting epsilon.keymetrics.io:80
2016-04-08 17:30:18: [REV] Connecting to epsilon.keymetrics.io:43554
2016-04-08 17:30:18: [WATCHDOG] Connected to PM2
2016-04-08 17:30:18: [PUSH] PM2 interface ready, listening to PM2
2016-04-08 17:30:18: [REV] Connected to PM2
/home/dom/npm/lib/node_modules/pm2/lib/Interactor/PushInteractor.js:294
      self.socket.client.sendv2(str, function() {
                         ^

TypeError: self.socket.client.sendv2 is not a function
    at /home/dom/npm/lib/node_modules/pm2/lib/Interactor/PushInteractor.js:294:26
    at /home/dom/npm/lib/node_modules/pm2/lib/Interactor/PushInteractor.js:247:19
    at /home/dom/npm/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/home/dom/npm/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at emitOne (events.js:90:13)
    at Parser.emit (events.js:182:7)
    at Parser._write (/home/dom/npm/lib/node_modules/pm2/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at Parser.Writable.write (_stream_writable.js:215:11)

```

**Comment by domarmstrong** [comment]
stale
