### ISSUE TITLE
pm2 crash without any cli operation

### ISSUE THREAD

**Issue by bangbang93** [Unitech/pm2#2088]
```
2016-04-12 11:32:02: App name:cofactories-html5 id:29 online
2016-04-12 12:01:21: [PM2][WORKER] Error caught by domain:
TypeError: Cannot read property 'addListener' of undefined
    at Object.exports.execFile (child_process.js:240:15)
    at exports.exec (child_process.js:101:18)
    at getUrl (/home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/node_modules/vizion/lib/git.js:18:5)
    at fn (/home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:641:34)
    at Immediate._onImmediate (/home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /bin/sh EAGAIN
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at Immediate._tickDomainCallback [as _onImmediate] (node.js:396:17)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
2016-04-12 12:04:26: [PM2][WORKER] Started with refreshing interval: 30000
2016-04-12 12:04:26: [[[[ PM2/God daemon launched ]]]]
```

```
2016-04-12 16:27:29: App name:temp-contract id:12 online
2016-04-13 09:52:58: [PM2][WORKER] Error caught by domain:
TypeError: Cannot read property 'addListener' of undefined
    at Object.exports.execFile (child_process.js:240:15)
    at exports.exec (child_process.js:101:18)
    at getUrl (/home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/node_modules/vizion/lib/git.js:18:5)
    at fn (/home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:641:34)
    at Immediate._onImmediate (/home/cofactories/.nvm/versions/node/v4.2.2/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /bin/sh EAGAIN
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at Immediate._tickDomainCallback [as _onImmediate] (node.js:396:17)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
2016-04-13 10:03:16: [PM2][WORKER] Started with refreshing interval: 30000
2016-04-13 10:03:16: [[[[ PM2/God daemon launched ]]]]
```

I didn't do anything with pm2, but something happened:(

**Comment by bangbang93** [comment]
[cofactories@10-10-101-5 cofactories]$ pm2 -v
0.15.10

well……I will update and keep watching

**Comment by git-patrickliu** [comment]
I have just the same problem. My pm2 version is 0.12.16.

**Comment by vmarchaud** [comment]
Update pm2 version.
