### ISSUE TITLE
Cluster mode not working on Windows

### ISSUE THREAD

**Issue by oliversalzburg** [Unitech/pm2#2110]
When I try to start our application in cluster mode on Windows, the  processes will be marked as `errored` and no processes are running.

In the log files, I can see part of our application startup and then it just stops with no error message.

When I run our application directly with `node` or a single instance in fork mode in `pm2`, it will runs just fine.

```
$ node -v; pm2 -v
v4.4.3
1.1.3
```

**Comment by oliversalzburg** [comment]
I didn't realize that there is a *main* `pm2.log` as well. This showed the following error:
```
2016-04-26 19:42:45: App [web] with id [1] and pid [21248], exited with code [0] via signal [SIGTERM]
2016-04-26 19:42:46: Error: write ENOTSUP
    at exports._errnoException (util.js:870:11)
    at ChildProcess.target._send (internal/child_process.js:611:20)
    at ChildProcess.target.send (internal/child_process.js:507:12)
    at sendHelper (cluster.js:722:8)
    at send (cluster.js:517:5)
    at cluster.js:492:7
    at SharedHandle.options.process.on.process.on.SharedHandle.add (cluster.js:86:3)
    at queryServer (cluster.js:484:12)
    at Worker.onmessage (cluster.js:432:7)
    at ChildProcess.<anonymous> (cluster.js:736:8)
```

After searching a bit, I realized that this was caused by using a UDP socket.

**Comment by lzszone** [comment]
seems that i got same problem, do u have any idea about this?
