### ISSUE TITLE
pm2 cluster_mode doesn't work with node v6.0.0

### ISSUE THREAD

**Issue by iRalph** [Unitech/pm2#2113]
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
[PM2][WARN] Applications koatest not running, starting...

always showing 'starting...', unable to go further when using cluster_mode with node v6.0.0

**Comment by iRalph** [comment]
when running 'pm2 kill' with nodejs v6.0.0, I got an error:

> [PM2] Stopping PM2...
> path.js:7
>     throw new TypeError('Path must be a string. Received ' + inspect(path));
>     ^
> 
> TypeError: Path must be a string. Received undefined
>     at assertPath (path.js:7:11)
>     at Object.basename (path.js:1355:5)
>     at prepareAppName (/usr/local/lib/node_modules/pm2/lib/CLI.js:2372:19)
>     at verifyConfs (/usr/local/lib/node_modules/pm2/lib/CLI.js:2295:5)
>     at Object.CLI._handleAttributeUpdate (/usr/local/lib/node_modules/pm2/lib/CLI.js:1186:17)
>     at Object.CLI._operate (/usr/local/lib/node_modules/pm2/lib/CLI.js:1016:16)
>     at /usr/local/lib/node_modules/pm2/lib/CLI.js:1676:11
>     at /usr/local/lib/node_modules/pm2/lib/CLI.js:1748:19
>     at /usr/local/lib/node_modules/pm2/node_modules/async/lib/async.js:52:16
>     at replenish (/usr/local/lib/node_modules/pm2/node_modules/async/lib/async.js:314:29)
