### ISSUE TITLE
TypeError: obj.hasOwnProperty is not a function on start

### ISSUE THREAD

**Issue by pycbouh** [Unitech/pm2#2132]
I've just updated to node v6.0.0 and pm2 v1.1.3, and can no longer successfully start any application. I use JSON declarations to configure my apps. When I try to run `pm2 start startup.json`, I only get two lines
```
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
```
and then the process hangs. Sometimes an app actually launches in the background, but as soon as I interrupt the hanged process with Ctrl+C, the app stops as well. I was unable to determine, on what condition does it launch, but the process hangs regardless.

There are no errors, except for the pm2.log, which has the following:
```
2016-05-05 11:18:22: [PM2] Error caught by domain:
TypeError: obj.hasOwnProperty is not a function
    at safeDeepClone (/usr/local/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:49:13)
    at safeDeepClone (/usr/local/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:53:22)
    at safeDeepClone (/usr/local/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:53:22)
    at cloneWrap (/usr/local/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:65:10)
    at Object.module.exports.clone (/usr/local/lib/node_modules/pm2/lib/Utility.js:25:12)
    at Object.Common.deepCopy.Common.serialize.Common.clone (/usr/local/lib/node_modules/pm2/lib/Common.js:164:18)
    at /usr/local/lib/node_modules/pm2/lib/God.js:363:25
    at forkMode (/usr/local/lib/node_modules/pm2/lib/God.js:231:15)
    at /usr/local/lib/node_modules/pm2/lib/God/ForkMode.js:198:22
    at /usr/local/lib/node_modules/pm2/node_modules/async/lib/async.js:49:16
2016-05-05 11:18:22: [PM2] Trying to update PM2...
Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.
/usr/local/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:49
    if (obj.hasOwnProperty(attr)) {
            ^

TypeError: obj.hasOwnProperty is not a function
    at safeDeepClone (/usr/local/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:49:13)
    at safeDeepClone (/usr/local/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:53:22)
    at safeDeepClone (/usr/local/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:53:22)
    at cloneWrap (/usr/local/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:65:10)
    at Object.module.exports.clone (/usr/local/lib/node_modules/pm2/lib/Utility.js:25:12)
    at Object.Common.deepCopy.Common.serialize.Common.clone (/usr/local/lib/node_modules/pm2/lib/Common.js:164:18)
    at Object.getFormatedProcesses (/usr/local/lib/node_modules/pm2/lib/God/Methods.js:53:21)
    at getMonitorData (/usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:42:25)
    at Server.onmessage (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:105:6)
    at emitTwo (events.js:106:13)
```

Starting an app config-less does not help the situation. Only difference is an extra output line
```
[PM2] Starting app.js in fork_mode (1 instance)
```

If I can give you any other information, please tell me. So far, nothing seems to work at all.

**Comment by pycbouh** [comment]
Figured, that I didn't actually update pm2 properly under the running user. No problem with pm2, sorry.

**Comment by OrKoN** [comment]
Hey @pycbouh I have the same problem. I have updated pm2 but still have this problem. How did you solve it?

**Comment by pycbouh** [comment]
@OrKoN Either something changed on my server recently, or one of the new PM2 dependencies required write access to one of the folders it did not have before. User I was updating under the first time did not have such permissions. So it did not actually update. PM2 did update with sudo, but it installed in another directory, which slipped my attention. So, under the original user it was running the old version.

All in all, just a confusion on my part.
