### ISSUE TITLE
pm2 failed to start app while using readFileSync function

### ISSUE THREAD

**Issue by tinyxiao** [Unitech/pm2#2146]
I start a simple app.js using pm2, it failed and thrown errors as below:
Error: ENOENT: no such file or directory, open './1.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/home/jk/test/app.js:3:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:46:21)

The following is my app.js
var fs = require('fs');
var protobufStr = fs.readSyncFile('./1.txt');

But if I change fs.readSyncFile to async function: fs.readFile, it successed .
Could anyone explain exactly, thank you.

**Comment by maxidev** [comment]
+1 confirmed

**Comment by vmarchaud** [comment]
Because the cwd of the script isn't the same as the` 1.txt`, checkout process file [here](http://pm2.keymetrics.io/docs/usage/application-declaration/)
