### ISSUE TITLE
Elasticsearch Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by Nulsen** [Unitech/pm2#2160]
Hi, i'm getting the following error message when i'm trying to run `pm2 start ./bin/elasticsearch`.
Everything works properly when i run `./bin/elasticsearch`.
I'm able to start other applications, like my node-servers app.js and mongodb, but not elasticsearch.
```
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:46:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

**Comment by Unitech** [comment]
starting elasticsearch with PM2, that's... interesting :)

Maybe:

```
$ pm2 start ./bin/elasticsearch --interpreter="bash"
```

But that's out of scope, closing

**Comment by Nulsen** [comment]
Woah thanks man, that actually worked!
