### ISSUE TITLE
Problem with pmx module:Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by mihailstefanov** [Unitech/pm2#2213]
pm2 1.1.3
node v5.11.1
Fedora
TypeError: Cannot convert undefined or null to object
    at getOwnPropertyNames (native)
    at Function.assign (/home/mihail/blue-vending/node_modules/traceur/bin/traceur-runtime.js:163:19)
    at process.target.send (internal/child_process.js:518:22)
    at ipcSend (/usr/lib/node_modules/pm2/node_modules/pmx/lib/utils/transport.js:22:13)
    at Object.Transport.send (/usr/lib/node_modules/pm2/node_modules/pmx/lib/utils/transport.js:33:3)
    at Timeout._repeat (/usr/lib/node_modules/pm2/node_modules/pmx/lib/Probe.js:120:17)
    at Timeout.wrapper [as _onTimeout](timers.js:408:11)
    at Timer.unrefdHandle (timers.js:445:14)
Process disconnected from parent !

**Comment by Unitech** [comment]
Do you use custom metrics?

**Comment by mihailstefanov** [comment]
nope,
just updated to the latest version.

On Jun 14, 2016, at 2:22 PM, Alexandre Strzelewicz <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you use custom metrics?

**Comment by Uter1007** [comment]
have the same problem in one of our client projects when I am using node >= 6.0.0

**Comment by Uter1007** [comment]
just saw that I am running an old traceur package - will update it to verify the behaviour

**Comment by vmarchaud** [comment]
@Uter1007 The version `v6.4.0` is breaking a lot of things, we disabled our test suite with it for this reason, i recommend you to downgrade or wait for update.

**Comment by Uter1007** [comment]
hmm problem still occures with LTS Version, any update ?
