### ISSUE TITLE
pm2 start command hanging

### ISSUE THREAD

**Issue by TimCody** [Unitech/pm2#2221]
Hey guys,

I'm using node v 6.2.1 on an ubuntu 14.04 box.  With pm2 version 0.15.10

When I try to start a node process, I get the following errors in my pm2.log file.

TypeError: obj.hasOwnProperty is not a function
    at safeDeepClone (/usr/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:49:13)
    at safeDeepClone (/usr/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:53:22)
    at safeDeepClone (/usr/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:53:22)
    at cloneWrap (/usr/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:65:10)
    at Object.module.exports.clone (/usr/lib/node_modules/pm2/lib/Utility.js:39:12)
    at Object.Common.deepCopy.Common.serialize.Common.clone (/usr/lib/node_modules/pm2/lib/Common.js:151:18)
    at Object.getFormatedProcesses (/usr/lib/node_modules/pm2/lib/God/Methods.js:68:21)
    at getMonitorData (/usr/lib/node_modules/pm2/lib/God/ActionMethods.js:42:25)
    at Server.onmessage (/usr/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:105:6)
    at emitTwo (events.js:106:13)
Fri, 10 Jun 2016 14:33:24 GMT axon:sock remove socket 0
Fri, 10 Jun 2016 14:33:24 GMT axon:sock attempting reconnect
Fri, 10 Jun 2016 14:33:24 GMT axon:sock connect attempt null:/home/user_123/.pm2/rpc.sock
Fri, 10 Jun 2016 14:33:24 GMT axon:sock error ECONNREFUSED
Fri, 10 Jun 2016 14:33:24 GMT axon:sock ignored ECONNREFUSED
Fri, 10 Jun 2016 14:33:25 GMT axon:sock attempting reconnect
Fri, 10 Jun 2016 14:33:25 GMT axon:sock connect attempt null:/home/user_123/.pm2/rpc.sock
Fri, 10 Jun 2016 14:33:25 GMT axon:sock error ECONNREFUSED
Fri, 10 Jun 2016 14:33:25 GMT axon:sock ignored ECONNREFUSED
Fri, 10 Jun 2016 14:33:25 GMT axon:sock attempting reconnect
Fri, 10 Jun 2016 14:33:25 GMT axon:sock connect attempt null:/home/user_123/.pm2/rpc.sock
Fri, 10 Jun 2016 14:33:25 GMT axon:sock error ECONNREFUSED
Fri, 10 Jun 2016 14:33:25 GMT axon:sock ignored ECONNREFUSED
Fri, 10 Jun 2016 14:33:25 GMT axon:sock attempting reconnect
Fri, 10 Jun 2016 14:33:25 GMT axon:sock connect attempt null:/home/user_123/.pm2/rpc.sock
Fri, 10 Jun 2016 14:33:25 GMT axon:sock error ECONNREFUSED
Fri, 10 Jun 2016 14:33:25 GMT axon:sock ignored ECONNREFUSED
Fri, 10 Jun 2016 14:33:26 GMT axon:sock attempting reconnect
Fri, 10 Jun 2016 14:33:26 GMT axon:sock connect attempt null:/home/user_123/.pm2/rpc.sock
Fri, 10 Jun 2016 14:33:26 GMT axon:sock error ECONNREFUSED
Fri, 10 Jun 2016 14:33:26 GMT axon:sock ignored ECONNREFUSED
Fri, 10 Jun 2016 14:33:26 GMT axon:sock attempting reconnect
Fri, 10 Jun 2016 14:33:26 GMT axon:sock connect attempt null:/home/user_123/.pm2/rpc.sock
Fri, 10 Jun 2016 14:33:26 GMT axon:sock error ECONNREFUSED
Fri, 10 Jun 2016 14:33:26 GMT axon:sock ignored ECONNREFUSED
Fri, 10 Jun 2016 14:33:28 GMT axon:sock attempting reconnect
Fri, 10 Jun 2016 14:33:28 GMT axon:sock connect attempt null:/home/user_123/.pm2/rpc.sock
Fri, 10 Jun 2016 14:33:28 GMT axon:sock error ECONNREFUSED
Fri, 10 Jun 2016 14:33:28 GMT axon:sock ignored ECONNREFUSED
Fri, 10 Jun 2016 14:33:29 GMT axon:sock attempting reconnect
Fri, 10 Jun 2016 14:33:29 GMT axon:sock connect attempt null:/home/user_123/.pm2/rpc.sock
Fri, 10 Jun 2016 14:33:29 GMT axon:sock error ECONNREFUSED
Fri, 10 Jun 2016 14:33:29 GMT axon:sock ignored ECONNREFUSED
Fri, 10 Jun 2016 14:33:32 GMT axon:sock attempting reconnect
Fri, 10 Jun 2016 14:33:32 GMT axon:sock connect attempt null:/home/user_123/.pm2/rpc.sock
Fri, 10 Jun 2016 14:33:32 GMT axon:sock error ECONNREFUSED
Fri, 10 Jun 2016 14:33:32 GMT axon:sock ignored ECONNREFUSED
Fri, 10 Jun 2016 14:33:36 GMT axon:sock attempting reconnect
Fri, 10 Jun 2016 14:33:36 GMT axon:sock connect attempt null:/home/user_123/.pm2/rpc.sock
Fri, 10 Jun 2016 14:33:36 GMT axon:sock error ECONNREFUSED
Fri, 10 Jun 2016 14:33:36 GMT axon:sock ignored ECONNREFUSED

Any ideas what could be causing this?  Thanks.  Let me know if any additional information is needed on my end.  I installed node 6.2.1 using sudo npm n latest

**Comment by TimCody** [comment]
I was able to solve it by updating pm2 to the latest version (Had to run some apt-get update commands  before pm2 would give me the latest version).
