### ISSUE TITLE
pm2 restart app-name causing pm2 to restart the process that spawns pm2 restart request

### ISSUE THREAD

**Issue by ashishbajaj99** [Unitech/pm2#2228]
I am using pm2 for some continuous integration via webhooks from GitHub. So I have two processes being monitored by PM2:
1. git-hooks - this responds to push notification from github webhook to launch a shell script node-deploy.sh
2. cloud-production - this is my production app

Here is the shell script that is used by git-hooks to restart the cloud-production app, node-deploy.sh
```
#!/bin/bash
git checkout production
git pull
npm install
pm2 restart cloud-production  
```
Running the script directly from the shell works perfectly. An issue occurs when I am trying to execute the script from within the git-hooks process that is also being monitored by PM2. So here is what is happening when I receive a push notification:
1. git-hooks spawns the node-deploy.sh script
2. The first 3 steps of git checkout, git pull and npm install happen correctly
3. But when pm2 restart cloud-production happens, it first stops the cloud-production app, and then instead of restarting that app, tries to restart the git-hooks app. This obviously fails because the git-hooks app is already online and using the port 2900. I am not sure why it doesn't restart the app name "cloud-production" but acts upon itself instead.

See setup details here:
$ pm2 list
```
┌─────────────────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name                │ id │ mode │ pid   │ status │ restart │ uptime │ memory      │ watching │
├─────────────────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ cloud-production        │ 1  │ fork │ 28614 │ online │ 0       │ 4s     │ 54.516 MB   │ disabled │
│ git-hooks               │ 2  │ fork │ 28660 │ online │ 0       │ 0s     │ 13.141 MB   │ disabled │
└─────────────────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────────────┴──────────┘
 Module activated
┌───────────────┬─────────┬────────────┬────────┬─────────┬─────┬─────────────┐
│ Module        │ version │ target PID │ status │ restart │ cpu │ memory      │
├───────────────┼─────────┼────────────┼────────┼─────────┼─────┼─────────────┤
│ pm2-logrotate │ 1.3.1   │ 28608      │ online │ 0       │ 10% │ 31.113 MB   │
└───────────────┴─────────┴────────────┴────────┴─────────┴─────┴─────────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

$ pm2 logs
```
<snip>
git-hooks-2 (out): 2016-06-18 20:07 +05:30: Received a push on production, build started...
git-hooks-2 (out): 2016-06-18 20:07 +05:30: Your branch is up-to-date with 'origin/production'.
git-hooks-2 (out): 2016-06-18 20:07 +05:30: Already up-to-date.

[PM2] Streaming realtime logs for [all] processes 

git-hooks-2 npm
git-hooks-2  
git-hooks-2 WARN
git-hooks-2  
git-hooks-2 optional Skipping failed optional dependency /chokidar/fsevents:
git-hooks-2 npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
git-hooks-2 [PM2] Applying action restartProcessId on app [cloud-production](ids: 1)
PM2 [Watch] Start watching 1
PM2 Stopping app:cloud-production id:1
PM2 App [cloud-production] with id [1] and pid [28614], exited with code [0] via signal [SIGINT]
PM2 Starting execution sequence in -fork mode- for app name:git-hooks id:2
PM2 App name:git-hooks id:2 online
git-hooks-2 [PM2] [git-hooks](1) ✓
git-hooks-2 Error: listen EADDRINUSE :::2900
git-hooks-2     at Object.exports._errnoException (util.js:1007:11)
git-hooks-2     at exports._exceptionWithHostPort (util.js:1030:20)
git-hooks-2     at Server._listen2 (net.js:1253:14)
git-hooks-2     at listen (net.js:1289:10)
git-hooks-2     at Server.listen (net.js:1385:5)
git-hooks-2     at Object.<anonymous> (git-hooks.js:17:4)
git-hooks-2     at Module._compile (module.js:541:32)
git-hooks-2     at Object.Module._extensions..js (module.js:550:10)
git-hooks-2     at Module.load (module.js:458:32)
git-hooks-2     at tryModuleLoad (module.js:417:12)
<snip>
```

For bugs or installation issues, please provide the following information:

### Environment info
Operating System: ubuntu
Pm2 version: 1.1.3
Node version: 6.2.1
Shell: bash

**Comment by ashishbajaj99** [comment]
If PM2 process ID for git-hooks is smaller than cloud-production, I get a different error. 

See setup details here:
```
$ pm2 list
┌─────────────────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name                │ id │ mode │ pid   │ status │ restart │ uptime │ memory      │ watching │
├─────────────────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ git-hooks               │ 1  │ fork │ 23647 │ online │ 0       │ 76s    │ 21.098 MB   │ disabled │
│ cloud-production        │ 2  │ fork │ 23692 │ online │ 0       │ 67s    │ 41.359 MB   │ disabled │
└─────────────────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────────────┴──────────┘
 Module activated
┌───────────────┬─────────┬────────────┬────────┬─────────┬─────┬─────────────┐
│ Module        │ version │ target PID │ status │ restart │ cpu │ memory      │
├───────────────┼─────────┼────────────┼────────┼─────────┼─────┼─────────────┤
│ pm2-logrotate │ 1.3.1   │ 23641      │ online │ 0       │ 0%  │ 31.266 MB   │
└───────────────┴─────────┴────────────┴────────┴─────────┴─────┴─────────────┘
 Use `pm2 show <id|name>` to get more details about an app
```
$pm2 logs
```
git-hooks-1 Received a push on production, build started...
git-hooks-1 Already on 'production'
git-hooks-1 Your branch is up-to-date with 'origin/production'.
git-hooks-1 Already up-to-date.
git-hooks-1 npm
git-hooks-1  
git-hooks-1 WARN
git-hooks-1  
git-hooks-1 optional Skipping failed optional dependency /chokidar/fsevents:
git-hooks-1 npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
git-hooks-1 [PM2] Applying action restartProcessId on app [cloud-production](ids: 2)
git-hooks-1 /usr/lib/node_modules/pm2/node_modules/amp-message/index.js:126
git-hooks-1   return new Buffer('j:' + JSON.stringify(arg));
git-hooks-1                                 ^
git-hooks-1 TypeError: Converting circular structure to JSON
git-hooks-1     at Object.stringify (native)
git-hooks-1     at pack (/usr/lib/node_modules/pm2/node_modules/amp-message/index.js:126:33)
git-hooks-1     at encode (/usr/lib/node_modules/pm2/node_modules/amp-message/index.js:101:14)
git-hooks-1     at Message.toBuffer (/usr/lib/node_modules/pm2/node_modules/amp-message/index.js:68:10)
git-hooks-1     at ReqSocket.Socket.pack (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/sock.js:92:14)
git-hooks-1     at ReqSocket.send (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:96:21)
git-hooks-1     at Client.call (/usr/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:34:13)
git-hooks-1     at Object.executeRemote (/usr/lib/node_modules/pm2/lib/Satan.js:563:23)
git-hooks-1     at /usr/lib/node_modules/pm2/lib/CLI.js:1047:13
git-hooks-1     at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:181:20
```

Does this help identify what could be going wrong even in the first case where git-hooks PM2 process ID is larger than cloud-production? Ideally both should behave in the same manner...

Thanks,
-Ashish

**Comment by ashishbajaj99** [comment]
Okay, I dug around and found this other issue that my issue could be duplicate of?

https://github.com/Unitech/pm2/issues/2077

Is there a fix available on the development branch?

```
$ npm install Unitech/pm2#development -g
$ pm2 update
```

**Comment by ashishbajaj99** [comment]
Still getting the same error after update to latest development branch. Any idea when this will get fixed? :(

**Comment by ashishbajaj99** [comment]
A workaround that worked for me, thanks to @Tarrask https://github.com/Tarrask 

```
var env = _.clone(process.env);
delete env.name;
delete env.cwd;
delete env.pm_exec_path;
delete env.pm_cwd;
delete env.pm_out_log_path;
delete env.pm_err_log_path;
delete env.pm_pid_path;
delete env.PM2_JSON_PROCESSING;
delete env.PORT;
delete env.pm_id;
exec(`pm2 restart ${childName}`, {env}, (err, stdout, stderr) => { ... });
```
