### ISSUE TITLE
Problem passing node args when using coffee interpreter

### ISSUE THREAD

**Issue by foxx** [Unitech/pm2#2239]
I can't seem to make `pm2` pass any arguments directly to `nodejs` when using `coffee` interpreter.

I've tried all sorts of combinations;

```
pm2 start server.coffee --node-args="--nodejs -- --perf-basic-prof-only-functions"
pm2 start server.coffee --node-args="--perf-basic-prof-only-functions"
pm2 start --node-args="--perf-basic-prof-only-functions" server.coffee
```

This only results in errors such as;

```
Error: unrecognized option: --perf-basic-prof-only-functions
  at OptionParser.exports.OptionParser.OptionParser.parse (/root/.nvm/versions/node/v4.4.5/lib/node_modules/coffee-script/lib/coffee-script/optparse.js:51:19)
  at parseOptions (/root/.nvm/versions/node/v4.4.5/lib/node_modules/coffee-script/lib/coffee-script/command.js:550:29)
  at Object.exports.run (/root/.nvm/versions/node/v4.4.5/lib/node_modules/coffee-script/lib/coffee-script/command.js:54:5)
  at Object.<anonymous> (/root/.nvm/versions/node/v4.4.5/lib/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3
```

And..

```
SyntaxError: Unexpected token >
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
/opt/simwood/apiv4/services/http-server.coffee:1
(function (exports, require, module, __filename, __dirname) { global.my_require = (moduleName) -> require __dirname + '/../' + moduleName
```

#### Software versions used

```
OS         :    Ubuntu 14.04.3 LTS
node.js    :    v4.4.5
PM2        :    1.1.3
```

**Comment by vmarchaud** [comment]
PM2 v2 has better/simpler support for transpiler, example in the release post [here](https://keymetrics.io/2016/08/24/pm2-v2-released/).
Feel free to re-open if you have still problem with it.
