### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by sawangupta** [Unitech/pm2#2247]
#### Expected behaviour

No errors

#### Actual behaviour

/usr/share/pack/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:32
Parser.prototype.__proto__ = Stream.prototype;
                                   ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/usr/share/pack/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:32:36)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/share/pack/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/index.js:3:18)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)

#### Steps to reproduce

Trying to run the command:
pm2 startup linux -u some_user

#### Software versions used

```
OS         : debian 7
node.js    : 4.2.1
PM2        : 1.1.3
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

No pm2.log file created yet.

**Comment by sawangupta** [comment]
Never mind. It was a version issue on the target system. The system had node 0.8.26 on it.
