### ISSUE TITLE
pm2-server-monit TypeError.

### ISSUE THREAD

**Issue by roccomuso** [Unitech/pm2#2284]
This is part of the email reporting an error regarding pm2-server-monit agent.

Application: pm2-server-monit
Message:
TypeError: Cannot read property 'replace' of undefined
    at /root/.pm2/node_modules/pm2-server-monit/lib/drive.js:22:35
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket. (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

**Comment by soyuka** [comment]
Moved to correct repository.
