### ISSUE TITLE
pm2.reload not working in no-daemon mode

### ISSUE THREAD

**Issue by saponifi3d** [Unitech/pm2#2307]
#### Expected behaviour
```js
pm2.reload('all', function(err, procs) {
  // call this function after doing a reload of all children
});
```

#### Actual behaviour
Does nothing. Satan attemps to call the daemon method, `getMonitorData` but it never resolves.

#### Steps to reproduce
have a `master.js` file as follows:

```js
pm2.connect(true, function(err) {
  pm2.start({
    script: 'app.js'
  });
});

process.on('SIGHUP', function() {
  pm2.reload('all', function() {
    // works and calls this
    console.log('is never called');
  });
});
```

```js
// app.js
var app = require('express')();
app.use(function(req,res,next) {
  res.sendStatus(200);
});

app.listen(3000, function() {
  console.log('worker listening on port 3000');
});
```

`kill -HUP <pm2 process id>`

#### Software versions used

```
OS         : docker container
node.js    : 4.2.6
PM2        : 1.1.3
```

#### PM2 Log output

```
Wed, 27 Jul 2016 20:24:17 GMT pm2:satan Calling daemon method pm2:getMonitorData
Wed, 27 Jul 2016 20:24:40 GMT pm2:worker [PM2][WORKER] Processing proc id: 0
Wed, 27 Jul 2016 20:24:40 GMT pm2:worker [PM2][WORKER] Processing proc id: 1
Wed, 27 Jul 2016 20:24:40 GMT pm2:worker [PM2][WORKER] Processing proc id: 2
Wed, 27 Jul 2016 20:24:40 GMT pm2:worker [PM2][WORKER] Processing proc id: 3
Wed, 27 Jul 2016 20:24:40 GMT pm2:worker [PM2][WORKER] My job here is done, next job in 30 seconds
```

#### Limitations

Trying to get this to work in a production environment where we have runit / supervisor sending signals to clusters (these signals aren't just for node, and i don't have control over what signals are being used).  It seems like pm2 + runit are trying to do similar things, but i need the clustering / graceful reloading from pm2.

**Comment by saponifi3d** [comment]
### Additional Info
In the shell if I run `pm2 reload all` it works, so I tried executing that command on the signal, however i get this in the logs:

```
Wed, 27 Jul 2016 20:36:48 GMT pm2:constants PM2 folder (logs, pids, configuration): /root/.pm2
Wed, 27 Jul 2016 20:36:49 GMT pm2:interface:daemon Getting interaction info
Wed, 27 Jul 2016 20:36:49 GMT pm2:interface:daemon [PING INTERACTOR] Trying to connect to Interactor daemon
Wed, 27 Jul 2016 20:36:49 GMT pm2:satan [PING PM2] Trying to connect to server
Wed, 27 Jul 2016 20:36:49 GMT pm2:satan Daemon alive
Wed, 27 Jul 2016 20:36:49 GMT pm2:satan Launching RPC client on socket file /root/.pm2/rpc.sock
Wed, 27 Jul 2016 20:36:49 GMT pm2:satan Connected to Daemon
Wed, 27 Jul 2016 20:36:49 GMT pm2:cli Got message from Satan as successfully connected to PM2, now parsing arguments
Wed, 27 Jul 2016 20:36:49 GMT pm2:satan Calling daemon method pm2:getVersion
Wed, 27 Jul 2016 20:36:49 GMT pm2:satan Calling daemon method pm2:getMonitorData
Wed, 27 Jul 2016 20:36:49 GMT pm2:satan Calling daemon method pm2:reloadProcessId
/code/brochure/node_modules/amp-message/index.js:126
  return new Buffer('j:' + JSON.stringify(arg));
                                ^

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at pack (/code/brochure/node_modules/amp-message/index.js:126:33)
    at encode (/code/brochure/node_modules/amp-message/index.js:101:14)
    at Message.toBuffer (/code/brochure/node_modules/amp-message/index.js:68:10)
    at ReqSocket.Socket.pack (/code/brochure/node_modules/pm2-axon/lib/sockets/sock.js:92:14)
    at ReqSocket.send (/code/brochure/node_modules/pm2-axon/lib/sockets/req.js:96:21)
    at Client.call (/code/brochure/node_modules/pm2-axon-rpc/lib/client.js:34:13)
    at Object.executeRemote (/code/brochure/node_modules/pm2/lib/Satan.js:563:23)
    at /code/brochure/node_modules/pm2/lib/CLI.js:1047:13
```

**Comment by Unitech** [comment]
Could you try pm2 v2:

```
$ npm install pm2@next -g
```

**Comment by saponifi3d** [comment]
@Unitech `pm2.connect(noDaemonMode, errback)` doesn't work in pm2, how can i get it to run in `noDaemonMode`?

```
/MyApp/node_modules/pm2/lib/API.js:129
      return cb(err, meta);
             ^

TypeError: cb is not a function
    at /code/brochure/node_modules/pm2/lib/API.js:129:14
    at /code/brochure/node_modules/pm2/lib/Client.js:52:16
    at null._onTimeout (/code/brochure/node_modules/pm2/lib/Client.js:321:19)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by Unitech** [comment]
Can you try like that with pm2@next:

```javascript
var PM2 = require('pm2');

// Or instanciate a custom PM2 instance

var pm2 = new PM2.custom({
  daemon_mode : false
});

pm2.start('app.js');

process.on('SIGHUP', function() {
  pm2.reload('all', function() {
    console.log('is never called');
  });
});
```

Make sure there is no PM2 running,

I will look at making the previous API (~PM2 v1) backward compatible

**Comment by Unitech** [comment]
I've updated the documentation about pm2.disconnect :)
The thing is that the script will not exit by itself if you don't call that function

**Comment by saponifi3d** [comment]
@Unitech that worked great thanks!

One last question.... where does the pm2@2.x documentation live? is there any yet?

**Comment by Unitech** [comment]
Alright API backward compatibility implemented with test

The pm2@2.x API documentation is not publicly available yet, will let you know once it's available, cheers!
