### ISSUE TITLE
Pm2 Cpu Error

### ISSUE THREAD

**Issue by NotSoSuper** [Unitech/pm2#2312]
If reporting a bug, please use the following template.

#### Expected behaviour
pm2 status (or any other dynamic command)
*The Table with information and processes*
...

#### Actual behaviour
root@host:~/.pm2# pm2 status
/usr/lib/node_modules/pm2/lib/API/CliUx.js:227
        l.monit.cpu + '%',
               ^

TypeError: Cannot read property 'cpu' of undefined
    at /usr/lib/node_modules/pm2/lib/API/CliUx.js:227:16
    at Array.forEach (native)
    at Object.UX.dispAsTable (/usr/lib/node_modules/pm2/lib/API/CliUx.js:212:8)
    at /usr/lib/node_modules/pm2/lib/API.js:1364:10
    at /usr/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser._write (/usr/lib/node_modules/pm2/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:300:12)
root@host:~/.pm2# 
...

#### Steps to reproduce
pm2 status
OR
any pm2 command other than help and static ones
...

#### Software versions used

```
OS         : Ubuntu Server 14.04 LTS
node.js    : v4.4.7
PM2        : 2.0.2
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
2016-08-02 00:01:10: ===============================================================================
2016-08-02 00:01:10: --- New PM2 Daemon started ----------------------------------------------------
2016-08-02 00:01:10: Time                 : Tue Aug 02 2016 00:01:10 GMT-0400 (EDT)
2016-08-02 00:01:10: PM2 version          : 2.0.2
2016-08-02 00:01:10: Node.js version      : 4.4.7
2016-08-02 00:01:10: Current arch         : x64
2016-08-02 00:01:10: PM2 home             : /root/.pm2
2016-08-02 00:01:10: PM2 PID file         : /root/.pm2/pm2.pid
2016-08-02 00:01:10: RPC socket file      : /root/.pm2/rpc.sock
2016-08-02 00:01:10: BUS socket file      : /root/.pm2/pub.sock
2016-08-02 00:01:10: Application log path : /root/.pm2/logs
2016-08-02 00:01:10: Process dump file    : /root/.pm2/dump.pm2
2016-08-02 00:01:10: Concurrent actions   : 4
2016-08-02 00:01:10: SIGTERM timeout      : 1600
2016-08-02 00:01:10: ===============================================================================
2016-08-02 00:01:11: Starting execution sequence in -fork mode- for app name:pm2-webshell id:0
2016-08-02 00:01:11: App name:pm2-webshell id:0 online
2016-08-02 00:01:11: Starting execution sequence in -fork mode- for app name:pm2-server-monit id:1
2016-08-02 00:01:11: App name:pm2-server-monit id:1 online
2016-08-02 00:01:11: Starting execution sequence in -fork mode- for app name:pm2-mysql id:2
2016-08-02 00:01:11: App name:pm2-mysql id:2 online
2016-08-02 00:01:11: Starting execution sequence in -fork mode- for app name:bot0 id:3
2016-08-02 00:01:11: Starting execution sequence in -fork mode- for app name:bot1 id:4
2016-08-02 00:01:11: Starting execution sequence in -fork mode- for app name:bot2 id:5
2016-08-02 00:01:11: App name:bot0 id:3 online
2016-08-02 00:01:11: App name:bot1 id:4 online
2016-08-02 00:01:11: App name:bot2 id:5 online
2016-08-02 00:01:13: App [bot2] with id [5] and pid [2423], exited with code [1] via signal [SIGINT]
2016-08-02 00:01:13: Starting execution sequence in -fork mode- for app name:bot2 id:5
2016-08-02 00:01:13: App name:bot2 id:5 online
2016-08-02 00:01:13: App [bot1] with id [4] and pid [2422], exited with code [1] via signal [SIGINT]
2016-08-02 00:01:13: Starting execution sequence in -fork mode- for app name:bot1 id:4
2016-08-02 00:01:13: App name:bot1 id:4 online
2016-08-02 00:01:13: App [bot0] with id [3] and pid [2421], exited with code [1] via signal [SIGINT]
2016-08-02 00:01:13: Starting execution sequence in -fork mode- for app name:bot0 id:3
2016-08-02 00:01:13: App name:bot0 id:3 online
2016-08-02 00:04:10: Stopping app:pm2-server-monit id:1
2016-08-02 00:04:10: App [pm2-server-monit] with id [1] and pid [2411], exited with code [0] via signal [SIGINT]
2016-08-02 00:04:12: Starting execution sequence in -fork mode- for app name:pm2-server-monit id:6
2016-08-02 00:04:12: App name:pm2-server-monit id:6 online
2016-08-02 00:05:05: Starting execution sequence in -fork mode- for app name:pm2-monitor id:7
2016-08-02 00:05:05: App name:pm2-monitor id:7 online```

**Comment by Unitech** [comment]
thanks for reporting
