### ISSUE TITLE
Process with pid already exists

### ISSUE THREAD

**Issue by peze** [Unitech/pm2#2315]
i have this problem , please help me to solve it:

    2016-08-03 00:34:34: Process with pid 27388 still not killed, retrying...
    2016-08-03 00:34:34: Process with pid 27388 still not killed, retrying...
    2016-08-03 00:34:34: Process with pid 27388 still not killed, retrying...
    2016-08-03 00:34:34: Process with pid 27388 still not killed, retrying...
    2016-08-03 00:34:34: Process with pid 27388 still not killed, retrying...
    2016-08-03 00:34:34: Process with pid 27388 still alive after 1600ms, sending it SIGKILL now...
    2016-08-03 00:34:35: Process with pid 27388 still not killed, retrying...
    2016-08-03 00:34:35: Process with pid 27388 still not killed, retrying...
    2016-08-03 00:34:35: Process with pid 27388 still not killed, retrying...
    2016-08-03 00:34:35: Process with pid 27388 still not killed, retrying...
    2016-08-03 00:34:35: Process with pid 27388 still not killed, retrying...
    2016-08-03 00:34:35: Process with pid 27388 still not killed, retrying...
    2016-08-03 00:34:35: Process with pid 27388 still not killed, retrying...
    2016-08-03 00:34:35: Process with pid 27388 still not killed, retrying...
      n6-08-03 00:34:35: Process with pid 27388 still not killed, retrying...
    2016-08-03 00:34:35: Process with pid 27388 still not killed, retrying...
    2016-08-03 00:34:36: Process with pid 27388 still not killed, retrying...
    2016-08-03 00:34:36: Process with pid 27388 still not killed, retrying...
    2016-08-03 00:34:36: Process with pid 27388 still not killed, retrying...
    2016-08-03 00:34:36: Process with pid 27388 still not killed, retrying...
    2016-08-03 00:34:36: Process with pid 27388 still not killed, retrying...
    2016-08-03 00:34:36: Process with pid 27388 could not be killed
    2016-08-03 00:34:36: Process with pid 27388 already exists 
    2016-08-03 00:34:36: Error: Process with pid 27388 already exists
        at Object.God.logAndGenerateError (/usr/lib64/node_modules/pm2/lib/God/Methods.js:35:12)
        at Object.God.startProcessId (/usr/lib64/node_modules/pm2/lib/God/ActionMethods.js:218:21)
        at /usr/lib64/node_modules/pm2/lib/God/ActionMethods.js:414:20
        at /usr/lib64/node_modules/pm2/lib/God/ActionMethods.js:280:18
        at null._onTimeout (/usr/lib64/node_modules/pm2/lib/God/Methods.js:212:16)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
        
i think pm2 tried to restart the server,but it could not kill the process of this server. i don't know why the error is that Process with pid 27388 already exists and then the server was down....i feel very puzzle about it...

**Comment by Unitech** [comment]
PM2 version? Node.js version?
How did pm2 ended on that /usr/lib64/ folder?
Do you catch signals?

**Comment by Unitech** [comment]
Any news?
