### ISSUE TITLE
Starting node-red with PM2 on Windows: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by arakno76** [Unitech/pm2#2317]
#### Expected behaviour
node-red should start and be available
...

#### Actual behaviour
node-red starts but after few seconds the status changes to "errored"
...

#### Steps to reproduce
- Open Win CMD 
- type "pm2 start node-red"
...

#### Software versions used

```
OS  Windows 10   Pro   :
node.js    : v4.1.0
PM2        v1.1.3
node-red: v0.14.6
```

#### PM2 Log output

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function._load (C:\Users\Arakno\AppData\Roaming\npm\node_modules\pm2\node_modules\pmx\lib\transaction.js:62:21)
    at Object.<anonymous> (C:\Users\Arakno\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:46:21)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
Same as #2037 , we are currently searching for a solution, if you have any more information, dont hesitate to communicate it to the #2037 issue.
