### ISSUE TITLE
pm2.connect noDaemon/cb not acting correctly

### ISSUE THREAD

**Issue by colegrigsby** [Unitech/pm2#2324]
So I was testing with the newest pm2, and my pm2.connect call was giving me the following TypeError, I was calling it from a module with only a callback and no boolean, which should work. Just thought I would give you a heads up! 

#### Software versions used

```
PM2        : 2.0.4
```

#### PM2 module Log output

```
TypeError: cb is not a function
at /opt/auto-reload/node_modules/pm2/lib/API.js:136:14
at /opt/auto-reload/node_modules/pm2/lib/Client.js:52:16
at null._onTimeout (/opt/auto-reload/node_modules/pm2/lib/Client.js:321:19)
at Timer.listOnTimeout (timers.js:92:15)
```

Source Code for reference 
```
API.prototype.connect = function(noDaemon, cb) {
 var that = this;
 this.start_timer = new Date();

 if (typeof(cb) == 'undefined') {
   cb = noDaemon;
   noDaemon = false;
 } else if (noDaemon === true) {
   // Backward compatibility with PM2 1.x
   this.Client.daemon_mode = false;
   this.daemon_mode = false;
 }
```

**Comment by colegrigsby** [comment]
Just kidding, had a misplaced bracket / parenthesis! haha good work on the newest dev branch its working great!
