### ISSUE TITLE
weird bug when deleting a process programatically

### ISSUE THREAD

**Issue by HERRKIN** [Unitech/pm2#2328]
If reporting a bug, please use the following template.

#### Expected behaviour

I expect it to delete the process so I can start other or the same one after that. 

#### Actual behaviour
when I delete a process pm2 crashes the app and it wont say which call (or line ) in my app is causing the error.

#### Steps to reproduce
the first thing I do is to stop all the processes that have certain criteria. `pm2.stop()` later I delete a particular process which is already stopped. when I do so it deletes, it calls back but after that pm2 throws this error. 

```
            name         : proc.pm2_env.name,
                                       ^

TypeError: Cannot read property 'name' of undefined
    at /home/herrkin/dev/work/smsinterface/node_modules/pm2/lib/CLI.js:1073:40
    at Array.forEach (native)
    at /home/herrkin/dev/work/smsinterface/node_modules/pm2/lib/CLI.js:1069:13
    at /home/herrkin/dev/work/smsinterface/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/home/herrkin/dev/work/smsinterface/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at emitOne (events.js:90:13)
    at Parser.emit (events.js:182:7)
    at Parser._write (/home/herrkin/dev/work/smsinterface/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
```
#### Software versions used

```
OS         : ubuntu 16.04
node.js    : v5
PM2        :1.1.3
```
```
#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```2016-08-10 16:57:28: --- Stopping PM2 --------------------------------------------------------------
2016-08-10 16:57:28: Time                 : Wed Aug 10 2016 16:57:28 GMT-0400 (VET)
2016-08-10 16:57:28: ===============================================================================
2016-08-10 16:57:28: RPC closed
2016-08-10 16:57:28: PUB closed
2016-08-10 16:57:28: PM2 successfully stopped
2016-08-10 16:57:32: ===============================================================================
2016-08-10 16:57:32: --- New PM2 Daemon started ----------------------------------------------------
2016-08-10 16:57:32: Time                 : Wed Aug 10 2016 16:57:32 GMT-0400 (VET)
2016-08-10 16:57:32: PM2 version          : 2.0.4
2016-08-10 16:57:32: Node.js version      : 5.5.0
2016-08-10 16:57:32: Current arch         : x64
2016-08-10 16:57:32: PM2 home             : /home/herrkin/.pm2
2016-08-10 16:57:32: PM2 PID file         : /home/herrkin/.pm2/pm2.pid
2016-08-10 16:57:32: RPC socket file      : /home/herrkin/.pm2/rpc.sock
2016-08-10 16:57:32: BUS socket file      : /home/herrkin/.pm2/pub.sock
2016-08-10 16:57:32: Application log path : /home/herrkin/.pm2/logs
2016-08-10 16:57:32: Process dump file    : /home/herrkin/.pm2/dump.pm2
2016-08-10 16:57:32: Concurrent actions   : 4
2016-08-10 16:57:32: SIGTERM timeout      : 1600
2016-08-10 16:57:32: ===============================================================================
2016-08-10 17:03:54: ===============================================================================
2016-08-10 17:03:54: --- Stopping PM2 --------------------------------------------------------------
2016-08-10 17:03:55: Time                 : Wed Aug 10 2016 17:03:55 GMT-0400 (VET)
2016-08-10 17:03:55: ===============================================================================
2016-08-10 17:03:55: RPC closed
2016-08-10 17:03:55: PUB closed
2016-08-10 17:03:55: PM2 successfully stopped
2016-08-10 17:03:55: [PM2][WORKER] Started with refreshing interval: 30000
2016-08-10 17:04:01: Starting execution sequence in -fork mode- for app name:351753037327334 id:0
2016-08-10 17:04:01: App name:351753037327334 id:0 online
2016-08-10 17:04:05: App [351753037327334] with id [0] and pid [16572], exited with code [0] via signal [SIGINT]
2016-08-10 17:04:05: Starting execution sequence in -fork mode- for app name:351753037327334 id:0
2016-08-10 17:04:05: App name:351753037327334 id:0 online
2016-08-10 17:04:07: Stopping app:351753037327334 id:0
2016-08-10 17:04:07: App [351753037327334] with id [0] and pid [16601], exited with code [0] via signal [SIGINT]
2016-08-10 17:04:07: Stopping app:351753037327334 id:0
2016-08-10 17:04:39: Starting execution sequence in -fork mode- for app name:351753037327334 id:0
2016-08-10 17:04:39: App name:351753037327334 id:0 online
2016-08-10 17:04:42: App [351753037327334] with id [0] and pid [16647], exited with code [0] via signal [SIGINT]
2016-08-10 17:04:42: Starting execution sequence in -fork mode- for app name:351753037327334 id:0
2016-08-10 17:04:43: App name:351753037327334 id:0 online
2016-08-10 17:04:44: Stopping app:351753037327334 id:0
2016-08-10 17:04:44: App [351753037327334] with id [0] and pid [16672], exited with code [0] via signal [SIGINT]
2016-08-10 17:04:44: Stopping app:351753037327334 id:0
2016-08-10 17:04:47: Starting execution sequence in -fork mode- for app name:351753037327334 id:0
2016-08-10 17:04:47: App name:351753037327334 id:0 online
2016-08-10 17:04:50: Stopping app:351753037327334 id:0
2016-08-10 17:04:50: App [351753037327334] with id [0] and pid [16715], exited with code [0] via signal [SIGINT]
2016-08-10 17:04:50: Stopping app:351753037327334 id:0

...
```

cf CONTRIBUTING.md for more informations

**Comment by Unitech** [comment]
Would you have an example code to reproduce that issue?
Could you try with pm2@next?

**Comment by HERRKIN** [comment]
I realized that somehow the stop part was being executed later than the delete call, even I called it before. so I had to wait for all processes to stop before sending a delete call. 

I am having a similar problem, but I don't know how to explain it honestly. to make it short I am developing an app that should look query the processes in pm2, them  validate some parameters and delete certain apps, restart them or keep it stopped. the app seems to work fine except that those apps wich should remain stopped are lost when I call delete to a specific process. then if I try to put it back online, pm2 crashes, that is very weird.

**Comment by HERRKIN** [comment]
also I am having some problems when calling stop. I print the output like this 

```
pm2.stop(i.name,(e,p)=>{
console.log(`${p[0].name stopped}`)

})```

but sometimes without an explaination it says it cant print name of undefined.

**Comment by Unitech** [comment]
Ok I would like to fix this potential issue but I need some of your help,

Would you mind having a look at this [test file](https://github.com/Unitech/pm2/blob/development/test/programmatic/api.mocha.js), and add some PM2 commands that could end up to the same issue you have?

To launch this test:

```bash
$ git clone git@github.com:Unitech/pm2.git
$ git checkout development
$ cd pm2
$ npm install
$ mocha test/programmatic/api.mocha.js
```

**Comment by HERRKIN** [comment]
you can close this, I realized that somehow my delete was finished before my stop even though I did call it later. but I managed to do it sequentially. now I am having another weird but. but I am opening another issue for that.
