### ISSUE TITLE
pm2-dev not running on windows on 2.0.7

### ISSUE THREAD

**Issue by amelon** [Unitech/pm2#2365]
I'm trying to run following command

`pm2-dev start config/pm2/_development.json` 

#### Actual behaviour
I get following error

````
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:466:7)
    at Object.<anonymous> (C:\Users\...\AppData\Roaming\nvm\v6.5.0\node_modules\pm2\lib\DevCli.js:25:19)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
````

#### Steps to reproduce

If I change following lines

````
var pm2 = new PM2.custom({
  pm2_home : path.join(process.env.HOME, '.pm2-dev')
});
````

with 
````
var pm2 = new PM2.custom({
  pm2_home : path.join(process.env.HOMEPATH, '.pm2-dev')
});
````
it works.

it seems `process.env.HOME` is not known on win7.

You should probably try following line
`process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE`

or maybe the best one

`os.homedir()`

(https://nodejs.org/api/os.html#os_os_homedir)
(http://stackoverflow.com/questions/9080085/node-js-find-home-directory-in-platform-agnostic-way)

#### Software versions used

```
OS         : win7
node.js    : 6.5.0 (also tried 6.4.4)
PM2        : 2.0.7

#### PM2 Log output

no pm2 log available

**Comment by Unitech** [comment]
thanks for the suggestion, fix landed in development mode

```bash
$ npm install pm2#development -g
```
