### ISSUE TITLE
pm2 ecosystem not working

### ISSUE THREAD

**Issue by psabharwal3** [Unitech/pm2#2370]
If reporting a bug, please use the following template.

#### Expected behaviour
pm2 ecosystem should work
...

#### Actual behaviour
C:\Users\punee\Documents\hrms-app>pm2 ecosystem
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:466:7)
    at Object.CLI.generateSample (C:\Users\punee\AppData\Roaming\npm\node_modules\pm2\lib\CLI.js:1272:27)
    at Command.<anonymous> (C:\Users\punee\AppData\Roaming\npm\node_modules\pm2\bin\pm2:541:9)
    at Command.listener (C:\Users\punee\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (C:\Users\punee\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:615:12)
    at Command.parse (C:\Users\punee\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:458:21)
    at beginCommandProcessing (C:\Users\punee\AppData\Roaming\npm\node_modules\pm2\bin\pm2:121:13)
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:466:7)
    at Object.CLI.generateSample (C:\Users\punee\AppData\Roaming\npm\node_modules\pm2\lib\CLI.js:1276:45)
    at Command.<anonymous> (C:\Users\punee\AppData\Roaming\npm\node_modules\pm2\bin\pm2:541:9)
    at Command.listener (C:\Users\punee\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (C:\Users\punee\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:615:12)
    at Command.parse (C:\Users\punee\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:458:21)
    at beginCommandProcessing (C:\Users\punee\AppData\Roaming\npm\node_modules\pm2\bin\pm2:121:13)
...

#### Steps to reproduce
pm2 ecosystem (in command line)
...

#### Software versions used
1.1.3
```
OS         :  windows 10
node.js    : 6.2.0
PM2        :  1.1.3
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by Unitech** [comment]
Fixed in PM2 v2:

```
$ npm install pm2@next -g
```
