### ISSUE TITLE
Can not reload by using child_process.execFile("update.sh")

### ISSUE THREAD

**Issue by start940315** [Unitech/pm2#2371]
#### Expected behaviour

I tried to using webhook to auto reload my app. I create a  server to receive the webhook message. When I push my code to the remove repo, it should receive the event and pull code and execute "pm2 reload app". Then the main app should reload and running  the updated code.

My update.sh is like this:
```
#!/bin/bash
cd /my/app/path
git pull
pm2 reload app
```

#### Actual behaviour

`git pull` works fine and pulls the latest code but `pm2 reload app` create error.
The app is shutdown and logs repeats EDDRINUSE:8000
It seems that pm2 is restarting the app and the old is not shutdown.

#### Steps to reproduce

1. create an app to receive webhook event from git.
2. start main app with `pm2 start app.js -i max -- --prod`
3. start the webhook app
4. upon receiving the push event, exec the sh file I mentioned above.

#### Software versions used

```
OS         : ubuntu
node.js    : v4.5.0
PM2        :1.1.3
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
2016-09-07 11:52:20: Starting execution sequence in -fork mode- for app name:index id:1
2016-09-07 11:52:20: App name:index id:1 online
2016-09-07 11:52:21: App [index] with id [1] and pid [13426], exited with code [255] via signal [SIGINT]
2016-09-07 11:52:21: Starting execution sequence in -fork mode- for app name:index id:1
2016-09-07 11:52:21: App name:index id:1 online
2016-09-07 11:52:21: App [index] with id [1] and pid [13436], exited with code [255] via signal [SIGINT]
2016-09-07 11:52:21: Starting execution sequence in -fork mode- for app name:index id:1
2016-09-07 11:52:21: App name:index id:1 online
2016-09-07 11:52:21: App [index] with id [1] and pid [13446], exited with code [255] via signal [SIGINT]
2016-09-07 11:52:21: Starting execution sequence in -fork mode- for app name:index id:1
2016-09-07 11:52:21: App name:index id:1 online
2016-09-07 11:52:21: App [index] with id [1] and pid [13464], exited with code [255] via signal [SIGINT]
2016-09-07 11:52:21: Starting execution sequence in -fork mode- for app name:index id:1
2016-09-07 11:52:21: App name:index id:1 online
2016-09-07 11:52:22: App [index] with id [1] and pid [13474], exited with code [255] via signal [SIGINT]
2016-09-07 11:52:22: Starting execution sequence in -fork mode- for app name:index id:1
2016-09-07 11:52:22: App name:index id:1 online
2016-09-07 11:52:22: App [index] with id [1] and pid [13484], exited with code [255] via signal [SIGINT]
2016-09-07 11:52:22: Starting execution sequence in -fork mode- for app name:index id:1
2016-09-07 11:52:22: App name:index id:1 online
2016-09-07 11:52:22: App [index] with id [1] and pid [13494], exited with code [255] via signal [SIGINT]
2016-09-07 11:52:22: Starting execution sequence in -fork mode- for app name:index id:1
2016-09-07 11:52:22: App name:index id:1 online
2016-09-07 11:52:23: App [index] with id [1] and pid [13504], exited with code [255] via signal [SIGINT]
2016-09-07 11:52:23: Starting execution sequence in -fork mode- for app name:index id:1
2016-09-07 11:52:23: App name:index id:1 online
2016-09-07 11:52:23: App [index] with id [1] and pid [13514], exited with code [255] via signal [SIGINT]
2016-09-07 11:52:23: Starting execution sequence in -fork mode- for app name:index id:1
2016-09-07 11:52:23: App name:index id:1 online
2016-09-07 11:52:23: App [index] with id [1] and pid [13524], exited with code [255] via signal [SIGINT]
2016-09-07 11:52:23: Starting execution sequence in -fork mode- for app name:index id:1
2016-09-07 11:52:23: App name:index id:1 online
2016-09-07 11:52:23: App [index] with id [1] and pid [13534], exited with code [255] via signal [SIGINT]
2016-09-07 11:52:23: Starting execution sequence in -fork mode- for app name:index id:1
2016-09-07 11:52:23: App name:index id:1 online
2016-09-07 11:52:24: App [index] with id [1] and pid [13544], exited with code [255] via signal [SIGINT]
2016-09-07 11:52:24: Starting execution sequence in -fork mode- for app name:index id:1
2016-09-07 11:52:24: App name:index id:1 online
2016-09-07 11:52:24: App [index] with id [1] and pid [13554], exited with code [255] via signal [SIGINT]
2016-09-07 11:52:24: Starting execution sequence in -fork mode- for app name:index id:1
2016-09-07 11:52:24: App name:index id:1 online
2016-09-07 11:52:24: App [index] with id [1] and pid [13564], exited with code [255] via signal [SIGINT]
2016-09-07 11:52:24: Starting execution sequence in -fork mode- for app name:index id:1
2016-09-07 11:52:24: App name:index id:1 online
2016-09-07 11:52:25: Stopping app:index id:1
2016-09-07 11:52:25: App [index] with id [1] and pid [13580], exited with code [255] via signal [SIGINT]
2016-09-07 11:52:25: [HandleExit] PM2 is being killed, stopping restart procedure...
2016-09-07 11:52:25: PM2 is being killed via kill method
2016-09-07 11:52:25: RPC socket closed
2016-09-07 11:52:25: PUB socket closed
```

**Comment by start940315** [comment]
I use `pm2 logs` to display the outputs.
index-1 is the webhook app.
```
PM2 Starting execution sequence in -fork mode- for app name:index id:1
PM2 App name:index id:1 online
index-1 Error: listen EADDRINUSE :::8000
index-1     at Object.exports._errnoException (util.js:907:11)
index-1     at exports._exceptionWithHostPort (util.js:930:20)
index-1     at Server._listen2 (net.js:1250:14)
index-1     at listen (net.js:1286:10)
index-1     at Server.listen (net.js:1382:5)
index-1     at EventEmitter.listen (/home/ubuntu/test/node_modules/express/lib/application.js:617:24)
index-1     at Object.<anonymous> (/home/ubuntu/test/index.js:14:5)
index-1     at Module._compile (module.js:409:26)
index-1     at Object.Module._extensions..js (module.js:416:10)
index-1     at Module.load (module.js:343:32)
PM2 App [index] with id [1] and pid [14593], exited with code [255] via signal [SIGINT]
PM2 Starting execution sequence in -fork mode- for app name:index id:1
PM2 App name:index id:1 online
index-1 Error: listen EADDRINUSE :::8000
index-1     at Object.exports._errnoException (util.js:907:11)
index-1     at exports._exceptionWithHostPort (util.js:930:20)
index-1     at Server._listen2 (net.js:1250:14)
index-1     at listen (net.js:1286:10)
index-1     at Server.listen (net.js:1382:5)
index-1     at EventEmitter.listen (/home/ubuntu/test/node_modules/express/lib/application.js:617:24)
index-1     at Object.<anonymous> (/home/ubuntu/test/index.js:14:5)
index-1     at Module._compile (module.js:409:26)
index-1     at Object.Module._extensions..js (module.js:416:10)
index-1     at Module.load (module.js:343:32)
```

**Comment by vmarchaud** [comment]
You should look into the [`pm2.pullAndGracefulReload` ](https://github.com/Unitech/pm2/blob/master/lib/CLI.js#L2160 ) method, to do that properly.

**Comment by FoghostCn** [comment]
I have the same problem

**Comment by FoghostCn** [comment]
```
pm2 pull order
[PM2] Updating repository for process name order
[PM2] No versioning system found for process order
```

**Comment by Unitech** [comment]
Could you try with PM2 v2, inner PM2 management works now:

```bash
$ npm install pm2@next -g
```

**Comment by Unitech** [comment]
Please re-open if anyone has a related issue on pm2 v2
