### ISSUE TITLE
TypeError: Cannot read property 'INTERACTION_CONF' of undefined

### ISSUE THREAD

**Issue by gregegan** [Unitech/pm2#2383]
#### Software versions used

```
OS         : Heroku
node.js    : v6.2.2
PM2        : "pm2": "^2.0.12",
```

#### PM2 Log output

```
16-09-16T02:49:28.018182+00:00 heroku[web.1]: Starting process with command `node main.js`
2016-09-16T02:49:31.590366+00:00 heroku[web.1]: Process exited with status 1
2016-09-16T02:49:31.461893+00:00 app[web.1]: PM2 and application has been succesfully started
2016-09-16T02:49:31.468529+00:00 app[web.1]: /app/node_modules/pm2/lib/Interactor/InteractorDaemonizer.js:391
2016-09-16T02:49:31.468543+00:00 app[web.1]:     console.error('Error when writting configuration file %s', conf.INTERACTION_CONF);
2016-09-16T02:49:31.468553+00:00 app[web.1]:                                                                    ^
2016-09-16T02:49:31.468565+00:00 app[web.1]:
2016-09-16T02:49:31.468578+00:00 app[web.1]: TypeError: Cannot read property 'INTERACTION_CONF' of undefined
2016-09-16T02:49:31.468580+00:00 app[web.1]:     at Object.InteractorDaemonizer.getSetKeys (/app/node_modules/pm2/lib/Interactor/InteractorDaemonizer.js:391:68)
2016-09-16T02:49:31.468580+00:00 app[web.1]:     at Object.InteractorDaemonizer.launchAndInteract (/app/node_modules/pm2/lib/Interactor/InteractorDaemonizer.js:451:24)
2016-09-16T02:49:31.468581+00:00 app[web.1]:     at CLI.interact (/app/node_modules/pm2/lib/API/Interaction.js:22:14)
2016-09-16T02:49:31.468582+00:00 app[web.1]:     at /app/main.js:33:73
2016-09-16T02:49:31.468582+00:00 app[web.1]:     at /app/node_modules/pm2/lib/API.js:927:21
2016-09-16T02:49:31.468583+00:00 app[web.1]:     at /app/node_modules/pm2/lib/API.js:985:19
2016-09-16T02:49:31.468584+00:00 app[web.1]:     at /app/node_modules/pm2/node_modules/async/lib/async.js:52:16
2016-09-16T02:49:31.468584+00:00 app[web.1]:     at replenish (/app/node_modules/pm2/node_modules/async/lib/async.js:306:28)
2016-09-16T02:49:31.468585+00:00 app[web.1]:     at /app/node_modules/pm2/node_modules/async/lib/async.js:326:29
2016-09-16T02:49:31.468596+00:00 app[web.1]:     at /app/node_modules/pm2/node_modules/async/lib/async.js:44:16
2016-09-16T02:49:31.616613+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by inv8der** [comment]
This can be closed. We narrowed the issue down to a bug on our end. Thanks!
