### ISSUE TITLE
Undocumented breaking changes in 2.0+ API ?

### ISSUE THREAD

**Issue by Al10s** [Unitech/pm2#2398]
I am using the PM2 API to monitor my PM2 instances through HTTP requests.
It worked well for versions <= 1.1.3, but I now have an error thrown every time I try to request the API

It seems that "API.Client" is undefined when I try to do pm2.list()

Errors I was able to reproduce :
> TypeError: Cannot read property 'executeRemote' of undefined
>     at API.list (/home/al10s/Code/Tests/pm2-api-minimal/node_modules/pm2/lib/API.js:524:14)

> Error: SUB connection to PM2 is not launched
>     at /home/al10s/Code/Tests/pm2-api-minimal/node_modules/pm2/lib/Client.js:343:10
>     at nextTickCallbackWith0Args (node.js:420:9)
>     at process._tickDomainCallback (node.js:390:13)

#### Expected behaviour

As the API is said to be backward compatible, I expected the same behavior as before, which is an object containing the status of my PM2 instances

#### Actual behaviour

An error is thrown when I try to use the API

#### Steps to reproduce

```bash
git clone https://github.com/Al10s/pm2-api-minimal.git
cd pm2-api-minimal
export PM2_HOME="/tmp/pm2";
mkdir -p "$PM2_HOME/logs" "$PM2_HOME/pids";
npm install;
npm start;
```

```bash
curl localhost:9999/pm2/list
```

Editing package.json and setting the version of pm2 to 1.1.3 shows the previous behavior

#### Software versions used

```
OS         : Ubuntu 14.04 (Tested too in a docker "node:4.5.0", based on a debian 8 (jessie))
node.js    : 4.5.0
PM2        : 1.1.3 (OK) 2.0.0 (FAILS) 2.0.15 (FAILS)
```

#### PM2 Log output

```
2016-09-22 14:26:13: ===============================================================================
2016-09-22 14:26:13: --- New PM2 Daemon started ----------------------------------------------------
2016-09-22 14:26:13: Time                 : Thu Sep 22 2016 14:26:13 GMT+0200 (CEST)
2016-09-22 14:26:13: PM2 version          : 2.0.15
2016-09-22 14:26:13: Node.js version      : 4.5.0
2016-09-22 14:26:13: Current arch         : x64
2016-09-22 14:26:13: PM2 home             : /tmp/pm2
2016-09-22 14:26:13: PM2 PID file         : /tmp/pm2/pm2.pid
2016-09-22 14:26:13: RPC socket file      : /tmp/pm2/rpc.sock
2016-09-22 14:26:13: BUS socket file      : /tmp/pm2/pub.sock
2016-09-22 14:26:13: Application log path : /tmp/pm2/logs
2016-09-22 14:26:13: Process dump file    : /tmp/pm2/dump.pm2
2016-09-22 14:26:13: Concurrent actions   : 4
2016-09-22 14:26:13: SIGTERM timeout      : 1600
2016-09-22 14:26:13: ===============================================================================
2016-09-22 14:26:13: Starting execution sequence in -fork mode- for app name:server id:0
2016-09-22 14:26:13: App name:server id:0 online
2016-09-22 14:26:13: Starting execution sequence in -fork mode- for app name:scheduled-tasks id:1
2016-09-22 14:26:13: App name:scheduled-tasks id:1 online
2016-09-22 14:26:16: App [server] with id [0] and pid [6751], exited with code [1] via signal [SIGINT]
2016-09-22 14:26:16: Starting execution sequence in -fork mode- for app name:server id:0
2016-09-22 14:26:16: App name:server id:0 online
```

#### /tmp/pm2/logs/server-error-0.log output

```
Error: SUB connection to PM2 is not launched
    at /home/al10s/Code/Tests/pm2-api-minimal/node_modules/pm2/lib/Client.js:343:10
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
```

**Comment by Unitech** [comment]
Thanks for this sample.

[Here](https://github.com/Al10s/pm2-api-minimal/blob/master/server.js#L10), instead of `Q.nbind(pm2.connect)()` you may want to do `Q.nbind(pm2.connect, pm2)()`

[Here](https://github.com/Al10s/pm2-api-minimal/blob/master/main.js#L23) Do not call destroy and disconnect, but disconnect only

**Comment by Al10s** [comment]
I added the destroy to stop the PM2 daemon after my app is shut down.
Is there a better way to do so ?

Thanks for the fast reply and sorry for wasting your time with my dumb mistake, I will try to fix my sample in order to reproduce the bug I actually have. 
> TypeError: Cannot read property 'executeRemote' of undefined
>     at API.list (/var/www/node_modules/pm2/lib/API.js:524:14)
>     at /var/www/server.js:438:6
>     at /var/www/node_modules/pm2/lib/API.js:136:14
>     at /var/www/node_modules/pm2/lib/Client.js:52:16
>     at null._onTimeout (/var/www/node_modules/pm2/lib/Client.js:321:19)
>     at Timer.listOnTimeout (timers.js:92:15)

I'll update this thread as soon as I'm able to reproduce it, or I'll close it if I find the bug in my code

**Comment by Al10s** [comment]
Well I found the bug and fixed it. It has to do with binding the method to PM2 too.
Long story short, I had to replace 
```javascript
var cmd = pm2[command];
cmd(cb)
```
with
```javascript
var cmd = pm2[command];
cmd.bind(pm2)(cb)
```
I guess versions 2.0+ now require an explicit binding to pm2, that previous versions didn't.
I don't know if it should be considered as a breaking change, as I suppose it is already considered as the following feature
> PM2 isolation for multi PM2 instance management

But the problem I encountered might happen to others, so it could be worth highlighting it.

**Comment by Unitech** [comment]
The .destroy command allows to kill the PM2 Daemon + delete the configuration folder. The .destroy method cannot be called without triggering an error if you do not set a custom PM2_HOME env variable.

These binding issues might happen in this context because the main PM2 file is a class in the V2 (allowing multiple PM2 to run on the same host)  whereas it was a singleton in PM2 0.x & 1.x
