### ISSUE TITLE
Wrong coffeescript file location

### ISSUE THREAD

**Issue by brianmwadime** [Unitech/pm2#2423]
Pm2 is no longer running my app as before. Started getting issue after updating pm2 to the latest version.

Not sure what's changed.

```
$pm2 start index.coffee
```
Should start the app.

#### Actual behaviour

Starts the app in returns **status: errored**

#### Software versions used

```
OS         : ubuntu
node.js    : v6.5.0
PM2        : latest
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
2016-10-02 09:01:24: Stopping app:index id:0
2016-10-02 09:01:29: Starting execution sequence in -fork mode- for app name:index id:0
2016-10-02 09:01:29: App name:index id:0 online
2016-10-02 09:01:29: Error: spawn /usr/share/nginx/html/api/node_modules/pm2/node_modules/.bin/coffee ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2016-10-02 09:01:34: Stopping app:index id:0
2016-10-02 09:01:59: Starting execution sequence in -fork mode- for app name:index id:0
2016-10-02 09:01:59: App name:index id:0 online
2016-10-02 09:01:59: Error: spawn /usr/share/nginx/html/api/node_modules/pm2/node_modules/.bin/coffee ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
You didnt install the coffee interpreter : `pm2 install coffee` and you will be able to start your application.
