### ISSUE TITLE
PM2 save is not work after error a out of memory

### ISSUE THREAD

**Issue by extensionsapp** [Unitech/pm2#2424]
#### Expected behaviour

After error, start the application.
#### Actual behaviour

Not start.
#### Steps to reproduce

After an error occurs the application will not start after you restart the server (reboot). Apparently the PM2 save (file) disappeared.

I had to run the application again:
`cd /home/myapp && pm2 start process.json && pm2 save`

process.json

```
{
  "apps" : [{
    "name" : "myapp",
    "script" : "/home/myapp/app.js",
    "cwd" : "/home/myapp",
    "error_file" : "/home/myapp/log/err.log",
    "out_file" : "/home/myapp/log/out.log",
    "node_args" : "--max-old-space-size=768",
    "max_memory_restart" : "768M",
    "watch" : true,
    "ignore_watch" : [
      "config",
      "log",
      "node_modules",
      "themes/*/public",
      "themes/.*",
      ".*"
    ],
    "watch_options" : {
      "followSymlinks": false
    },
    "vizion" : false
  }]
}
```
#### Software versions used

```
OS         : Debian 8 (1Gb RAM, 1 core)
node.js    : 4.4.7
PM2        : 1.1.3
```
#### PM2 Log output

free -h
http://prnt.sc/cpch5j
htop
http://prnt.sc/cpchp5

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory

<--- Last few GCs --->

454122537 ms: Scavenge 15.7 (52.9) -> 14.7 (52.9) MB, 0.5 / 0 ms [allocation failure].
454133117 ms: Scavenge 15.7 (52.9) -> 14.7 (52.9) MB, 0.8 / 0 ms [allocation failure].
454143123 ms: Scavenge 15.7 (52.9) -> 14.8 (52.9) MB, 1.0 / 0 ms [allocation failure].
454156634 ms: Scavenge 15.7 (52.9) -> 14.7 (52.9) MB, 0.5 / 0 ms [allocation failure].
454167977 ms: Scavenge 15.7 (52.9) -> 14.7 (52.9) MB, 0.7 / 0 ms [allocation failure].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2d6ac59b4629 <JS Object>
    2: emit [events.js:~117] [pc=0x3910f8b0f410] (this=0x398f17d24549 <a Socket with map 0x3590f1693c01>,type=0x2d6ac59bd781 <String[4]: data>)
    3: arguments adaptor frame: 2->1
    4: readableAddChunk(aka readableAddChunk) [_stream_readable.js:~124] [pc=0x3910f8b7c107] (this=0x2d6ac59041b9 <undefined>,stream=0x398f17d24549 <a Socket with map 0x3590f1693c01>,state=0x398f17d24629 <a ReadableS...

2016-10-03 06:46:22: [PM2][WORKER] Started with refreshing interval: 30000
2016-10-03 06:46:22: [[[[ PM2/God daemon launched ]]]]
2016-10-03 06:46:22: BUS system [READY] on port /root/.pm2/pub.sock
2016-10-03 06:46:22: RPC interface [READY] on port /root/.pm2/rpc.sock
2016-10-03 06:46:24: [PM2][WORKER] Started with refreshing interval: 30000
2016-10-03 06:46:24: [[[[ PM2/God daemon launched ]]]]
2016-10-03 06:46:24: BUS system [READY] on port /root/.pm2/pub.sock
2016-10-03 06:46:24: RPC interface [READY] on port /root/.pm2/rpc.sock
2016-10-03 12:21:30: [PM2][WORKER] Started with refreshing interval: 30000
2016-10-03 12:21:30: [[[[ PM2/God daemon launched ]]]]
2016-10-03 12:21:30: BUS system [READY] on port /root/.pm2/pub.sock
2016-10-03 12:21:30: RPC interface [READY] on port /root/.pm2/rpc.sock
2016-10-03 12:27:41: pm2 has been killed by signal, dumping process list before exit...
2016-10-03 12:27:41: [PM2] Exited peacefully
2016-10-03 12:28:35: [PM2][WORKER] Started with refreshing interval: 30000
2016-10-03 12:28:35: [[[[ PM2/God daemon launched ]]]]
2016-10-03 12:28:35: BUS system [READY] on port /root/.pm2/pub.sock
2016-10-03 12:28:35: RPC interface [READY] on port /root/.pm2/rpc.sock
2016-10-03 12:30:18: pm2 has been killed by signal, dumping process list before exit...
2016-10-03 12:30:18: [PM2] Exited peacefully
2016-10-03 12:31:27: [PM2][WORKER] Started with refreshing interval: 30000
2016-10-03 12:31:27: [[[[ PM2/God daemon launched ]]]]
2016-10-03 12:31:27: BUS system [READY] on port /root/.pm2/pub.sock
2016-10-03 12:31:27: RPC interface [READY] on port /root/.pm2/rpc.sock
```

**Comment by vmarchaud** [comment]
Please update to latest pm2 version : `npm install -g pm2 && pm2 update` and tell me if its still happening.

**Comment by extensionsapp** [comment]
Hello. Again, not autostart.

```
2016-11-21 07:19:09: [PM2][WORKER] Error caught by domain:
Error: spawn ENOMEM
    at exports._errnoException (util.js:907:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at Object.exports.execFile (child_process.js:151:15)
    at exports.exec (child_process.js:111:18)
    at getUrl (/usr/lib/node_modules/pm2/node_modules/vizion/lib/git.js:18:5)
    at fn (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:746:34)
    at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:1213:16
    at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:166:37
    at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:706:43
FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory

<--- Last few GCs --->

1697863659 ms: Scavenge 12.0 (49.9) -> 11.1 (49.9) MB, 0.4 / 0 ms [allocation failure].
1697872752 ms: Scavenge 12.0 (49.9) -> 11.1 (49.9) MB, 0.7 / 0 ms [allocation failure].
1697889496 ms: Scavenge 12.0 (49.9) -> 11.1 (49.9) MB, 0.4 / 0 ms [allocation failure].
1697904328 ms: Scavenge 12.0 (49.9) -> 11.1 (49.9) MB, 8.7 / 0 ms [allocation failure].
1697920148 ms: Scavenge 12.1 (49.9) -> 11.1 (49.9) MB, 0.4 / 0 ms [allocation failure].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2780221b4629 <JS Object>
    2: write [fs.js:~616] [pc=0x2e289b8d8680] (this=0x1cc90666e199 <an Object with map 0x1a52a0b75859>,fd=12,buffer=0x33f77a0ffe89 <an Uint8Array with map 0
    3: _write [fs.js:~1847] [pc=0x2e2899e0fde5] (this=0x2dc34f404601 <a WriteStream with map 0x...

2016-11-21 12:33:22: ===============================================================================
2016-11-21 12:33:22: --- New PM2 Daemon started ----------------------------------------------------
2016-11-21 12:33:22: Time                 : Mon Nov 21 2016 12:33:22 GMT+0200 (EET)
2016-11-21 12:33:22: PM2 version          : 2.0.19
2016-11-21 12:33:22: Node.js version      : 4.6.1
2016-11-21 12:33:22: Current arch         : x64
2016-11-21 12:33:22: PM2 home             : /root/.pm2
2016-11-21 12:33:22: PM2 PID file         : /root/.pm2/pm2.pid
2016-11-21 12:33:22: RPC socket file      : /root/.pm2/rpc.sock
2016-11-21 12:33:22: BUS socket file      : /root/.pm2/pub.sock
2016-11-21 12:33:22: Application log path : /root/.pm2/logs
2016-11-21 12:33:22: Process dump file    : /root/.pm2/dump.pm2
2016-11-21 12:33:22: Concurrent actions   : 4
2016-11-21 12:33:22: SIGTERM timeout      : 1600
2016-11-21 12:33:22: ===============================================================================
2016-11-21 12:33:33: [Watch] Start watching 0
2016-11-21 12:33:33: Starting execution sequence in -fork mode- for app name:kinocom id:0
2016-11-21 12:33:33: App name:kinocom id:0 online
2016-11-21 12:34:07: pm2 has been killed by signal, dumping process list before exit...
2016-11-21 12:34:07: [PM2] Exited peacefully
2016-11-21 12:35:21: ===============================================================================
```

**Comment by extensionsapp** [comment]
Help properly configure this option.
```
"node_args" : "--max-old-space-size=768",
"max_memory_restart" : "768M",
```

What parameter must be greater?
```
"node_args" : "--max-old-space-size=750",
"max_memory_restart" : "768M",
```
or
```
"node_args" : "--max-old-space-size=768",
"max_memory_restart" : "750M",
```

And, this option
```
"error_file" : "/home/kinocom/log/err.log",
"out_file" : "/home/kinocom/log/out.log",
```
```
~# ls /home/kinocom/log/
err-0.log  err.log  out-0.log  out.log
```
Why are these files `err-0.log` `out-0.log`?

**Comment by vmarchaud** [comment]
It's the pm2 daemon that run out of memory, we can't handle this error internally, you need to use [pm2 startup](http://pm2.keymetrics.io/docs/usage/startup/) to respawn the process when it crash.
