### ISSUE TITLE
Support .js extension for ecosystem file

### ISSUE THREAD

**Issue by finom** [Unitech/pm2#2433]
#### Expected behaviour
Allow to use .js extension instead of .json.
...

#### Actual behaviour
It throws an error 
```sh
/usr/local/lib/node_modules/pm2/lib/CLI/Deploy.js:95

  if (!json_conf.deploy || !json_conf.deploy[env]) {
                ^

TypeError: Cannot read property 'deploy' of undefined
    at Object.DeployModule.deploy (/usr/local/lib/node_modules/pm2/lib/CLI/Deploy.js:95:17)
    at Command.<anonymous> (/usr/local/lib/node_modules/pm2/bin/pm2:253:9)
    at Command.listener (/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:458:21)
    at beginCommandProcessing (/usr/local/lib/node_modules/pm2/bin/pm2:121:13)
    at /usr/local/lib/node_modules/pm2/bin/pm2:174:7
    at Timeout._onTimeout (/usr/local/lib/node_modules/pm2/lib/Satan.js:443:19)
```

#### Steps to reproduce
Rename ecosystem.json to ecosystem.js and run 
```sh
pm2 deploy production ecosystem.js
```
...

#### Software versions used

```
OS         : Ubuntu
node.js    : 6.4.0
PM2        : 1.1.3
```

-----------------------------

PM2 supports custom JavaScript syntax at ecosystem files but it doesn't allow to use .js extension as it should be. I want at least the possibility to use .js extension but ideally I'd like to export configuration via ``module.exports``.

Problems I get because of this issue:
- I cannot lint ecosystem.json via JSONLint  because it is not JSON 
- I get problems linting ecosystem.json via ESLint because the file doesn't export config object (fixable disabling some rules).
- A syntax highligher at Atom editor (I guess at other editors too) gets crazy because it doesn't understand custom JavaScript syntax at .json files.

**Comment by igorushko** [comment]
https://github.com/Unitech/pm2/pull/2451

**Comment by Unitech** [comment]
merged into dev
