### ISSUE TITLE
pm2 dump doesn't fail when it shoud (EACCESS)

### ISSUE THREAD

**Issue by dmitry-mukhin** [Unitech/pm2#2464]
#### Expected behaviour

when I run pm2 dump, I expect it to fail if it doesn't have access to a dump file

#### Actual behaviour

pm2 dump prints an error to stdout but succeeds

#### Steps to reproduce

```bash
$ sudo chown root:root '/path/to/.pm2/dump.pm2'
$ pm2 dump
[PM2] Saving current process list...
Error: EACCES: permission denied, open '/path/to/.pm2/dump.pm2'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at fin (/usr/lib/node_modules/pm2/lib/API/Startup.js:225:14)
    at ex (/usr/lib/node_modules/pm2/lib/API/Startup.js:236:30)
    at ex (/usr/lib/node_modules/pm2/lib/API/Startup.js:242:16)
    at /usr/lib/node_modules/pm2/lib/API/Startup.js:243:9
    at /usr/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at emitOne (events.js:96:13)
[PM2] Successfully saved in /path/to/.pm2/dump.pm2
```

#### Software versions used

```
OS         : Ubuntu 14.04
node.js    : 6.8.1
PM2        : 2.0.18
```

**Comment by Unitech** [comment]
fixed

```
$ npm install Unitech/pm2#development -g
$ pm2 update
```

**Comment by dmitry-mukhin** [comment]
:+1:
