### ISSUE TITLE
Nodejs 7 ---harmony-async-await flag not working

### ISSUE THREAD

**Issue by anaibol** [Unitech/pm2#2479]
#### Actual behaviour
![selection_226](https://cloud.githubusercontent.com/assets/3210177/19813007/14383d68-9d38-11e6-9daa-0a529621d361.png)

#### Steps to reproduce
```json
{ "apps" : [{
    "name": "api",
    "script": "index.js",
    "exec_interpreter": "~/.nvm/versions/node/v7.0.0/bin/node",
    "node_args": [
      "--harmony-async-await"
    ],
    "env": {
      "NODE_ENV": "production"
    }
  }]
}

```
...

#### Software versions used

```
OS         : Linux
node.js    : 7.0.0
PM2        : 2.0.19
```

#### PM2 Log output
```
2016-10-28 17:55:24: Starting execution sequence in -fork mode- for app name:api id:0
2016-10-28 17:55:24: App name:api id:0 online
2016-10-28 17:55:24: Error: spawn ~/.nvm/versions/node/v7.0.0/bin/node ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by vmarchaud** [comment]
As you can see in the pm2 logs, pm2 spawn the executable you provided but the syscall return a `ENOENT`, that means that the path requested isn't found.
You must fix the path to call the good node executable, but the problem don't come from PM2 for sure.

**Comment by anaibol** [comment]
Ok @vmarchaud, you are right. Sorry and thanks!
