### ISSUE TITLE
PM2 processes crashes, pm2 deletes dump file

### ISSUE THREAD

**Issue by Alan01252** [Unitech/pm2#2485]
If reporting a bug, please use the following template.

#### Expected behaviour

- PM2 Crashes
- PM2 resurrect resurrects dump file
- All processes started

#### Actual behaviour

- PM2 Crashes
- PM2 Resurrect is called
- PM2 deletes all processes are dead
- All process are dead

#### Software versions used

```
OS         : ubuntu
node.js    : 6.2.0
PM2        : 2.0.15
```

#### PM2 Log output

```
2016-10-25 15:00:30: Starting execution sequence in -fork mode- for app name:myanimalcamifu id:0
2016-10-25 15:00:30: Starting execution sequence in -fork mode- for app name:agricamera-camera-proxy id:1
2016-10-25 15:00:30: App name:myanimalcamifu id:0 online
2016-10-25 15:00:30: App name:agricamera-camera-proxy id:1 online
2016-10-25 15:05:14: Stopping app:myanimalcamifu id:0
2016-10-25 15:05:14: Stopping app:agricamera-camera-proxy id:1
2016-10-25 15:05:14: App [myanimalcamifu] with id [0] and pid [830], exited with code [0] via signal [SIGINT]
2016-10-25 15:05:14: App [agricamera-camera-proxy] with id [1] and pid [836], exited with code [0] via signal [SIGINT]
2016-10-25 15:05:16: ===============================================================================
2016-10-25 15:05:19: --- Stopping PM2 --------------------------------------------------------------
2016-10-25 15:05:19: Time                 : Tue Oct 25 2016 15:05:19 GMT+0000 (UTC)
2016-10-25 15:05:19: ===============================================================================
2016-10-25 15:05:19: RPC closed
2016-10-25 15:05:19: PUB closed
2016-10-25 15:05:19: ===============================================================================
2016-10-25 15:05:19: --- PM2 global error caught ---------------------------------------------------
2016-10-25 15:05:19: Time                 : Tue Oct 25 2016 15:05:19 GMT+0000 (UTC)
2016-10-25 15:05:19: kill ESRCH
2016-10-25 15:05:19: Error: kill ESRCH
    at exports._errnoException (util.js:953:11)
    at process.kill (internal/process.js:173:13)
    at /usr/local/lib/node_modules/pm2/lib/Daemon.js:237:15
    at PubSocket.Socket.closeServer (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/sock.js:136:9)
    at PubSocket.Socket.close (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/sock.js:122:25)
    at /usr/local/lib/node_modules/pm2/lib/Daemon.js:229:21
    at RepSocket.Socket.closeServer (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/sock.js:136:9)
    at RepSocket.Socket.close (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/sock.js:122:25)
    at Daemon.close (/usr/local/lib/node_modules/pm2/lib/Daemon.js:227:19)
    at Server.onmessage (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:105:6)
2016-10-25 15:05:19: ===============================================================================
2016-10-25 15:05:19: [PM2][%s] Resurrecting PM2
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
2016-10-25 15:05:22: ===============================================================================
2016-10-25 15:05:22: --- New PM2 Daemon started ----------------------------------------------------
2016-10-25 15:05:22: Time                 : Tue Oct 25 2016 15:05:22 GMT+0000 (UTC)
2016-10-25 15:05:22: PM2 version          : 2.0.15
2016-10-25 15:05:22: Node.js version      : 6.2.0
2016-10-25 15:05:22: Current arch         : arm
2016-10-25 15:05:22: PM2 home             : /root/.pm2
2016-10-25 15:05:22: PM2 PID file         : /root/.pm2/pm2.pid
2016-10-25 15:05:22: RPC socket file      : /root/.pm2/rpc.sock
2016-10-25 15:05:22: BUS socket file      : /root/.pm2/pub.sock
2016-10-25 15:05:22: Application log path : /root/.pm2/logs
2016-10-25 15:05:22: Process dump file    : /root/.pm2/dump.pm2
2016-10-25 15:05:22: Concurrent actions   : 4
2016-10-25 15:05:22: SIGTERM timeout      : 1600
2016-10-25 15:05:22: ===============================================================================
[PM2] PM2 Successfully daemonized
Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.
[PM2] Saving current process list...
[PM2] Stopping PM2...
[PM2][WARN] No process found
[PM2] All processes have been stopped and deleted

```

I'll try and spend some time going through the code to get exact steps to reproduce later, but wanted to log this whilst I still had access to the logs.

**Comment by Unitech** [comment]
That's a strange behavior on ARM. Btw it's fixed:

```
$ npm install Unitech/pm2#development -g
$ pm2 update
```
