### ISSUE TITLE
TypeError: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by jcwik** [Unitech/PM2#249]
Cmd: "pm2 start server.js"

Platforms: Windows Server 2008, Windows 7

Stack Trace:
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:116:15)
    at Object.<anonymous> (C:\Users\jcwik\AppData\Roaming\npm\node_modules\pm2\constants.js:8:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\jcwik\AppData\Roaming\npm\node_modules\pm2\lib\Satan.js:22:14)
    at Module._compile (module.js:456:26)

**Comment by chrisweb** [comment]
@dareid is right, I had the same problem, when setting up instances on aws using the cloud init script, the home directory was not set (amazon linux instance)

If I connect via ssh to the server and execute pm2 manually its ok, but if I tell cloud init to switch to the user (I created in my cloud init script) to execute the "pm2 start server.js", then it fails because the home directory is undefined

I now set the home directory (in my cloud init script), the same way as I do for the environment and it works:

 - export NODE_ENV=production
 - export HOME=/home/www_user

**Comment by MonsJovis** [comment]
@dareid @chrisweb +1! I can confirm that it's working fine if you set the HOME environment var

**Comment by jackielihf** [comment]
@artakvg      

export HOME=/root
