### ISSUE TITLE
pm2 crashed and auto updated, all node process killed

### ISSUE THREAD

**Issue by sunfuze** [Unitech/pm2#2499]
System:
```
Linux chzh5 3.2.0-4-amd64 #1 SMP Debian 3.2.60-1+deb7u3 x86_64 GNU/Linux
```  
NODE:  
```
v4.3.1
```  
PM2:
```
1.1.3
```  
Actual behaviour:
```
2016-11-08 07:36:21: [PM2] Error caught by domain:
TypeError: Cannot read property 'apply' of undefined
    at ChildProcess.<anonymous> (cluster.js:731:7)
    at emitTwo (events.js:92:20)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:689:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
2016-11-08 07:36:21: [PM2] Trying to update PM2...
cluster.js:731
    fn.apply(worker, arguments);
      ^

TypeError: Cannot read property 'apply' of undefined
    at ChildProcess.<anonymous> (cluster.js:731:7)
    at emitTwo (events.js:92:20)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:689:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
[PM2] Spawning PM2 daemon
2016-11-08 07:36:22: [PM2][WORKER] Started with refreshing interval: 30000
2016-11-08 07:36:22: [[[[ PM2/God daemon launched ]]]]
2016-11-08 07:36:22: BUS system [READY] on port /home/dev/.pm2/pub.sock
2016-11-08 07:36:22: RPC interface [READY] on port /home/dev/.pm2/rpc.sock
[PM2] PM2 Successfully daemonized
[PM2][Module] Starting module pm2-logrotate
[PM2][WARN] Applications pm2-logrotate not running, starting...
2016-11-08 07:36:22: Starting execution sequence in -fork mode- for app name:pm2-logrotate id:0
2016-11-08 07:36:22: App name:pm2-logrotate id:0 online
[PM2] App [pm2-logrotate] launched (1 instances)
Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.
[PM2] Saving current process list...
[PM2] Stopping PM2...
[PM2] Applying action deleteProcessId on app [0](ids: 0)
2016-11-08 07:36:22: Stopping app:pm2-logrotate id:0
2016-11-08 07:36:22: App [pm2-logrotate] with id [0] and pid [22379], exited with code [0] via signal [SIGINT]
2016-11-08 07:36:22: [HandleExit] PM2 is being killed, stopping restart procedure...
[PM2] [pm2-logrotate](0) ✓
[PM2][WARN] No process found
[PM2] All processes have been stopped and deleted
2016-11-08 07:36:23: PM2 is being killed via kill method
2016-11-08 07:36:23: RPC socket closed
2016-11-08 07:36:23: PUB socket closed
[PM2] PM2 stopped
2016-11-08 07:36:23: [PM2][WORKER] Started with refreshing interval: 30000
[PM2] Restoring processes located in /home/dev/.pm2/dump.pm2
>>>>>>>>>> PM2 updated
[PM2][Module] Starting module pm2-logrotate
[PM2][WARN] Applications pm2-logrotate not running, starting...
2016-11-08 07:36:23: Starting execution sequence in -fork mode- for app name:pm2-logrotate id:0
2016-11-08 07:36:23: App name:pm2-logrotate id:0 online
[PM2] App [pm2-logrotate] launched (1 instances)
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬────────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ memory │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴────────┴──────────┘
 Module activated
┌───────────────┬─────────┬────────────┬────────┬─────────┬─────┬─────────────┐
│ Module        │ version │ target PID │ status │ restart │ cpu │ memory      │
├───────────────┼─────────┼────────────┼────────┼─────────┼─────┼─────────────┤
│ pm2-logrotate │ N/A     │ 22401      │ online │ 0       │ 8%  │ 13.184 MB   │
└───────────────┴─────────┴────────────┴────────┴─────────┴─────┴─────────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

**Comment by Unitech** [comment]
That comes from the Node.js cluster module:

```
TypeError: Cannot read property 'apply' of undefined
    at ChildProcess.<anonymous> (cluster.js:731:7)
    at emitTwo (events.js:92:20)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:689:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

**Comment by sunfuze** [comment]
@Unitech i didnt understang, all my process is running in fork mode

```
┌───────────┬────┬──────┬───────┬────────┬─────────┬────────┬──────────────┬──────────┐
│ App name  │ id │ mode │ pid   │ status │ restart │ uptime │ memory       │ watching │
├───────────┼────┼──────┼───────┼────────┼─────────┼────────┼──────────────┼──────────┤
│ tcp       │ 2  │ fork │ 23523 │ online │ 0       │ 2h     │ 194.867 MB   │ disabled │
│ data      │ 3  │ fork │ 23532 │ online │ 0       │ 2h     │ 76.859 MB    │ disabled │
│ motor-app │ 4  │ fork │ 23626 │ online │ 0       │ 2h     │ 87.922 MB    │ disabled │
│ admin     │ 6  │ fork │ 25059 │ online │ 0       │ 2h     │ 108.891 MB   │  enabled │
└───────────┴────┴──────┴───────┴────────┴─────────┴────────┴──────────────┴──────────┘

```

This is not pm2 problem?

**Comment by vmarchaud** [comment]
I advise you to update to latest pm2 version just in case : `npm install -g pm2 && pm2 update`
