### ISSUE TITLE
Stuck on delete(stop) list of process where filename map.js

### ISSUE THREAD

**Issue by tapin13** [Unitech/pm2#2518]
If reporting a bug, please use the following template.

#### Expected behaviour

Close all processes with "pm2 delete all"

#### Actual behaviour

Stop on closing process with filename map.js
Stuck.

#### Steps to reproduce

Create even empty file map.js
Run with pm2 start map.js
pm2 delete all

#### Software versions used

```
OS         : Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-44-generic x86_64)
node.js    : nodejs -v v0.10.25
PM2        : pm2 -v 2.1.4

```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`
```

PM2        | [Watch] Stop watching 1
PM2        | ===============================================================================
PM2        | --- PM2 global error caught ---------------------------------------------------
PM2        | Time                 : Sun Nov 13 2016 17:29:00 GMT+0200 (EET)
PM2        | Object function map() { [native code] } has no method 'close'
PM2        | TypeError: Object function map() { [native code] } has no method 'close'
PM2        |     at Object.ClusterMode.God.watch.disable (/usr/local/lib/node_modules/pm2/lib/Watcher.js:109:41)
PM2        |     at God.stopWatch (/usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:489:19)
PM2        |     at Server.onmessage (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:105:6)
PM2        |     at RepSocket.EventEmitter.emit (events.js:98:17)
PM2        |     at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/rep.js:51:15)
PM2        |     at Parser.EventEmitter.emit (events.js:95:17)
PM2        |     at Parser._write (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
PM2        |     at doWrite (_stream_writable.js:223:10)
PM2        |     at writeOrBuffer (_stream_writable.js:213:5)
PM2        |     at Parser.Writable.write (_stream_writable.js:180:11)
PM2        |     at write (_stream_readable.js:583:24)
PM2        |     at flow (_stream_readable.js:592:7)
PM2        | ===============================================================================
PM2        | [PM2][%s] Resurrecting PM2
PM2        | [Watch] Stop watching 1

...
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
We are aware of this issue, a edge case that is simply coming from the fact that the application name is the same as a native method, so when we make operation on it, we got an object that contains all process data, and we access it by using `processes[app_name]`, and you guessed it, it return the native method.
The simpler way we found is just to rename your application into another name, like map_app.js or something like that (you can change the name using `--name myname` CLI option)

**Comment by tapin13** [comment]
> rename your application into another name

exactly what I did.
