### ISSUE TITLE
 Error: channel closed on stop in cluster mode

### ISSUE THREAD

**Issue by avaranovich** [Unitech/pm2#253]
I have an express app, which handles shut down gracefully

``` ruby
cleanUp = ->
  logger.info "Clean up"
  client.quit() # client here is a redis client
  gracefulExit.gracefulExitHandler app, server

process.on "SIGTERM", ->
  logger.info "SIGTERM - Closing App"
  cleanUp()
```

gracefulExit is this module https://github.com/mathrawka/express-graceful-exit

The app is started like pm start server.coffee
when i do pm2 stop all

I get

```
info: SIGTERM - Closing App
Error: channel closed
at process.target.send (child_process.js:402:26)
at SyncWriteStream.write (/usr/lib/node_modules/pm2/lib/ProcessContainer.js:87:43)
at Console.log (/var/www/app/node_modules/winston/lib/winston/transports/console.js:80:20)
 at emit (/var/www/app/node_modules/winston/lib/winston/logger.js:174:17)
at /var/www/app/node_modules/winston/node_modules/async/lib/async.js:108:13
at Array.forEach (native)
at _each (/var/www/app/node_modules/winston/node_modules/async/lib/async.js:32:24)
 at Object.async.each (/var/www/app/node_modules/winston/node_modules/async/lib/async.js:107:9)
at Logger.log (/var/www/app/node_modules/winston/lib/winston/logger.js:202:9)
at target.(anonymous function) [as info] (/var/www/app/node_modules/winston/lib/winston/common.js:43:18)
at process.<anonymous> (/var/www/app/server.coffee:270:12)
at process.EventEmitter.emit (events.js:92:17)
at Signal.wrap.onsignal (node.js:757:46)
```

**Comment by ShiningRay** [comment]
+1

**Comment by jshkurti** [comment]
@ShiningRay version of PM2 and Node.js ?

**Comment by ShiningRay** [comment]
@jshkurti I'm using iojs 2.0.2 with PM2 0.12.15.
My script catches SIGTERM event and then do some clean work in the callback.
But I can only call `console.log` successfully once, and then 'Error: channel closed' will raise whenever `console.log` is called.
Later, I just disable logging after caught SIGTERM when `cluster.isMaster` returns true, then everything goes ok.
