### ISSUE TITLE
Error: spawn ENOMEM 

### ISSUE THREAD

**Issue by ktkaushik** [Unitech/pm2#2563]
The pm2 process is throwing Out of memory issue

#### Expected behaviour
It shouldn't throw this error
...

#### Actual behaviour
On my different application servers using pm2, i have been getting out of memory issues for the past couple of days. 
...

#### Steps to reproduce

...

#### Software versions used

```
OS           : Ubuntu 16.04
node.js    : v6.4.0
PM2        : 2.1.5
```

#### PM2 Log output

```
PM2        | Error: spawn ENOMEM
PM2        |     at exports._errnoException (util.js:1026:11)
PM2        |     at ChildProcess.spawn (internal/child_process.js:302:11)
PM2        |     at exports.spawn (child_process.js:380:9)
PM2        |     at Object.exports.execFile (child_process.js:143:15)
PM2        |     at exports.exec (child_process.js:103:18)
PM2        |     at getStaged (/home/deploy/.nvm/versions/node/v6.4.0/lib/node_modules/pm2/node_modules/vizion/lib/git.js:43:5)
PM2        |     at fn (/home/deploy/.nvm/versions/node/v6.4.0/lib/node_modules/pm2/node_modules/async/lib/async.js:746:34)
PM2        |     at /home/deploy/.nvm/versions/node/v6.4.0/lib/node_modules/pm2/node_modules/async/lib/async.js:1213:16
PM2        |     at /home/deploy/.nvm/versions/node/v6.4.0/lib/node_modules/pm2/node_modules/async/lib/async.js:166:37
PM2        |     at /home/deploy/.nvm/versions/node/v6.4.0/lib/node_modules/pm2/node_modules/async/lib/async.js:706:43
PM2        |
PM2        | <--- Last few GCs --->
PM2        |
PM2        | 1187538200 ms: Scavenge 12.0 (51.0) -> 11.3 (51.0) MB, 5.0 / 0 ms [allocation failure].
PM2        | 1187556641 ms: Scavenge 12.2 (51.0) -> 11.4 (51.0) MB, 5.3 / 0 ms [allocation failure].
PM2        | 1187581247 ms: Scavenge 12.3 (51.0) -> 11.5 (51.0) MB, 2.6 / 0 ms [allocation failure].
PM2        | 1187586770 ms: Scavenge 12.4 (51.0) -> 11.6 (51.0) MB, 6.0 / 0 ms [allocation failure].
PM2        | 1187619040 ms: Scavenge 12.5 (51.0) -> 11.7 (51.0) MB, 66.2 / 1 ms [allocation failure].
PM2        |
PM2        |
PM2        | <--- JS stacktrace --->
PM2        |
PM2        | ==== JS stack trace =========================================
PM2        |
PM2        | Security context: 0x3e8b8d4c9e31 <JS Object>
PM2        |     1: split [native string.js:~276] [pc=0x2a9a3fd1e44b] (this=0x978890ffba9 <String[323]\: D 27160 13755 13755 0 -1 4196352 23744986 5240 143171 23 205071 10939 37 4 20 0 10 0 114172921 1319346176 32101 18446744073709551615 4194304 29088912 140736195071440 140736195065304 16303808 0 0 4096 16898 0 0 0 17 0 0 0 3826 0 0 31186944 31283096 53866496 140736195072820 140736195072913 140736195072913 ...
PM2        |
PM2        | FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory
PM2        |  1: node::Abort() [PM2 v2.1.5: God Daemon (/home/deploy/.pm2)]
PM2        |  2: 0xfb7bfc [PM2 v2.1.5: God Daemon (/home/deploy/.pm2)]
PM2        |  3: v8::Utils::ReportApiFailure(char const*, char const*) [PM2 v2.1.5: God Daemon (/home/deploy/.pm2)]
PM2        |  4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [PM2 v2.1.5: God Daemon (/home/deploy/.pm2)]
PM2        |  5: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [PM2 v2.1.5: God Daemon (/home/deploy/.pm2)]
PM2        |  6: v8::internal::Heap::CollectGarbage(v8::internal::GarbageCollector, char const*, char const*, v8::GCCallbackFlags) [PM2 v2.1.5: God Daemon (/home/deploy/.pm2)]
PM2        |  7: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [PM2 v2.1.5: God Daemon (/home/deploy/.pm2)]
PM2        |  8: v8::internal::Factory::NewProperSubString(v8::internal::Handle<v8::internal::String>, int, int) [PM2 v2.1.5: God Daemon (/home/deploy/.pm2)]
PM2        |  9: v8::internal::Runtime_StringSplit(int, v8::internal::Object**, v8::internal::Isolate*) [PM2 v2.1.5: God Daemon (/home/deploy/.pm2)]
PM2        | 10: 0x2a9a3f40961b
```

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
 1: split [native string.js:~276] [pc=0x2a9a3fd1e44b] (this=0x978890ffba9 <String[323]\: D 27160 13755 13755 0 -1 4196352 23744986 5240 143171 23 205071 10939 37 4 20 0 10 0 114172921 1319346176 32101 18446744073709551615 4194304 29088912 140736195071440 140736195065304 16303808 0 0 4096 16898 0 0 0 17 0 0 0 3826 0 0 31186944 31283096 53866496 140736195072820 140736195072913 140736195072913 ...

FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory
 1: node::Abort() [PM2 v2.1.5: God Daemon (/home/deploy/.pm2)]
 2: 0xfb7bfc [PM2 v2.1.5: God Daemon (/home/deploy/.pm2)]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [PM2 v2.1.5: God Daemon (/home/deploy/.pm2)]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [PM2 v2.1.5: God Daemon (/home/deploy/.pm2)]
 5: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [PM2 v2.1.5: God Daemon (/home/deploy/.pm2)]
 6: v8::internal::Heap::CollectGarbage(v8::internal::GarbageCollector, char const*, char const*, v8::GCCallbackFlags) [PM2 v2.1.5: God Daemon (/home/deploy/.pm2)]
 7: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [PM2 v2.1.5: God Daemon (/home/deploy/.pm2)]
 8: v8::internal::Factory::NewProperSubString(v8::internal::Handle<v8::internal::String>, int, int) [PM2 v2.1.5: God Daemon (/home/deploy/.pm2)]
 9: v8::internal::Runtime_StringSplit(int, v8::internal::Object**, v8::internal::Isolate*) [PM2 v2.1.5: God Daemon (/home/deploy/.pm2)]
10: 0x2a9a3f40961b
2016-12-07 05:34:23: ===============================================================================
2016-12-07 05:34:23: --- New PM2 Daemon started ----------------------------------------------------
2016-12-07 05:34:23: Time                 : Wed Dec 07 2016 05:34:23 GMT+0000 (UTC)
2016-12-07 05:34:23: PM2 version          : 2.1.5
2016-12-07 05:34:23: Node.js version      : 6.4.0
2016-12-07 05:34:23: Current arch         : x64
2016-12-07 05:34:23: PM2 home             : /home/deploy/.pm2
2016-12-07 05:34:23: PM2 PID file         : /home/deploy/.pm2/pm2.pid
2016-12-07 05:34:23: RPC socket file      : /home/deploy/.pm2/rpc.sock
2016-12-07 05:34:23: BUS socket file      : /home/deploy/.pm2/pub.sock
2016-12-07 05:34:23: Application log path : /home/deploy/.pm2/logs
2016-12-07 05:34:23: Process dump file    : /home/deploy/.pm2/dump.pm2
2016-12-07 05:34:23: Concurrent actions   : 2
2016-12-07 05:34:23: SIGTERM timeout      : 1600
2016-12-07 05:34:23: ===============================================================================
2016-12-07 05:45:06: ===============================================================================
2016-12-07 05:45:06: --- Stopping PM2 --------------------------------------------------------------
2016-12-07 05:45:06: Time                 : Wed Dec 07 2016 05:45:06 GMT+0000 (UTC)
2016-12-07 05:45:06: ===============================================================================
2016-12-07 05:45:06: RPC closed
2016-12-07 05:45:06: PUB closed
2016-12-07 05:45:06: PM2 successfully stopped
2016-12-07 05:45:06: ===============================================================================
2016-12-07 05:45:06: --- New PM2 Daemon started ----------------------------------------------------
2016-12-07 05:45:06: Time                 : Wed Dec 07 2016 05:45:06 GMT+0000 (UTC)
2016-12-07 05:45:06: PM2 version          : 2.1.5
2016-12-07 05:45:06: Node.js version      : 6.4.0
2016-12-07 05:45:06: Current arch         : x64
2016-12-07 05:45:06: PM2 home             : /home/deploy/.pm2
2016-12-07 05:45:06: PM2 PID file         : /home/deploy/.pm2/pm2.pid
2016-12-07 05:45:06: RPC socket file      : /home/deploy/.pm2/rpc.sock
2016-12-07 05:45:06: BUS socket file      : /home/deploy/.pm2/pub.sock
2016-12-07 05:45:06: Application log path : /home/deploy/.pm2/logs
2016-12-07 05:45:06: Process dump file    : /home/deploy/.pm2/dump.pm2
2016-12-07 05:45:06: Concurrent actions   : 2
2016-12-07 05:45:06: SIGTERM timeout      : 1600
2016-12-07 05:45:06: ===============================================================================
```

More info on memory on my system `free -m`- 

```
              total        used        free      shared  buff/cache   available
Mem:            992         185         448           3         358         624
Swap:             0           0           0
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
We can't handle memory for you, if your applications take too much RAM, its normal that PM2 run out of memory.

**Comment by ktkaushik** [comment]
@vmarchaud it's weird that it never seemed to happen before.
