### ISSUE TITLE
Cannot read property 'apply' of undefined in the last version

### ISSUE THREAD

**Issue by fbonesso** [Unitech/pm2#2589]
#### Actual behaviour

Application randomly stopped.

#### Software versions used

```
OS         : Ubuntu 14
node.js    : 5.8.0
PM2        : 2.2.2
```

#### PM2 Log output

```
PM2        | ===============================================================================
PM2        | --- PM2 global error caught ---------------------------------------------------
PM2        | Time                 : Tue Dec 20 2016 12:51:20 GMT+0000 (UTC)
PM2        | Cannot read property 'apply' of undefined
PM2        | TypeError: Cannot read property 'apply' of undefined
PM2        |     at ChildProcess.<anonymous> (cluster.js:737:7)
PM2        |     at emitTwo (events.js:105:20)
PM2        |     at ChildProcess.emit (events.js:185:7)
PM2        |     at handleMessage (internal/child_process.js:718:10)
PM2        |     at Pipe.channel.onread (internal/child_process.js:444:11)
PM2        | ===============================================================================
PM2        | [PM2][%s] Resurrecting PM2
PM2        | ===============================================================================
PM2        | --- Stopping PM2 --------------------------------------------------------------
PM2        | Time                 : Tue Dec 20 2016 12:51:22 GMT+0000 (UTC)
PM2        | ===============================================================================
PM2        | RPC closed
```

**Comment by Unitech** [comment]
Node.js 5.x is an unstable version, this is not related to PM2
