### ISSUE TITLE
pm2 monit crashes with `RangeError: Invalid array length`

### ISSUE THREAD

**Issue by 2sui** [Unitech/pm2#2592]
The `pm2 monit` crashes on my system:

```
⌬ PM2 monitoring (To go further check out https://app.keymetrics.io) 

 ● matrixProducerServer                [/usr/local/lib/node_modules/pm2/node_modules/.0.1.2@pm2-multimeter/lib/bar.js:56
        .write(Array(bars + 1).join(this.solid.text))||               ] 84.520 MB  
               ^
 ● main                                [                              ] 0 %
RangeError: Invalid array length       [||||                          ] 22.977 MB  
    at Bar.draw (/usr/local/lib/node_modules/pm2/node_modules/.0.1.2@pm2-multimeter/lib/bar.js:56:16)
    at Bar.percent (/usr/local/lib/node_modules/pm2/node_modules/.0.1.2@pm2-multimeter/lib/bar.js:86:14)
    at Object.Monit.updateBars (/usr/local/lib/node_modules/pm2/lib/API/Monit.js:239:33)
    at Object.Monit.refresh (/usr/local/lib/node_modules/pm2/lib/API/Monit.js:124:12)
    at /usr/local/lib/node_modules/pm2/lib/API.js:1574:13
    at /usr/local/lib/node_modules/pm2/node_modules/.0.4.5@pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/.3.0.2@pm2-axon/lib/sockets/req.js:67:8)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._write (/usr/local/lib/node_modules/pm2/node_modules/.0.3.1@amp/lib/stream.js:91:16)

```

System info:
* OS: 
Darwin MacBook-Pro.local 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64
* Node version:
 v6.9.1
* pm2 version: 
2.2.2

**Comment by vmarchaud** [comment]
Merging with https://github.com/Unitech/pm2/issues/2631
