### ISSUE TITLE
Multiple Daemon processes running and no responsiveness

### ISSUE THREAD

**Issue by oiime** [Unitech/pm2#2607]
#### Expected behaviour

A single daemon running

#### Actual behaviour

Multiple daemons running, behavior starting at seemingly arbitrary times (usually after 1-3 days of running)

There are ~500 processes that seem to start at 1 minute intervals, the daemon is not responsive to commands (status etc). there are scripts there that delay exiting but I am not sure how that might relate. nothing in the logs for the period in which the daemons spawns

#### Software versions used

```
OS          : CentOS 7.2
node.js    : 6.9.2
PM2        : 2.2.2
```

#### Running processes before killing all daemons (cropped)
```
agent    16335  0.0  0.0 884272 25496 ?        Ssl  07:05   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16342  0.0  0.0 884276 25628 ?        Ssl  07:06   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16348  0.0  0.0 884280 25500 ?        Ssl  07:07   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16354  0.0  0.0 884280 25644 ?        Ssl  07:08   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16360  0.0  0.0 884272 25612 ?        Ssl  07:09   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16366  0.0  0.0 884268 25356 ?        Ssl  07:10   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16373  0.0  0.0 884272 25748 ?        Ssl  07:11   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16379  0.0  0.0 884272 25496 ?        Ssl  07:12   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16385  0.0  0.0 884280 25612 ?        Ssl  07:13   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16391  0.0  0.0 884276 25532 ?        Ssl  07:14   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16397  0.0  0.0 884272 25500 ?        Ssl  07:15   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16404  0.0  0.0 884276 25500 ?        Ssl  07:16   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16410  0.0  0.0 884276 25496 ?        Ssl  07:17   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16417  0.0  0.0 884320 25576 ?        Ssl  07:18   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16424  0.0  0.0 884280 25508 ?        Ssl  07:19   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16430  0.0  0.0 884280 25360 ?        Ssl  07:20   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16437  0.0  0.0 884320 25404 ?        Ssl  07:21   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16443  0.0  0.0 884276 25240 ?        Ssl  07:22   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16449  0.0  0.0 884272 25356 ?        Ssl  07:23   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16455  0.0  0.0 884276 25352 ?        Ssl  07:24   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16463  0.0  0.0 884272 25528 ?        Ssl  07:25   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16470  0.0  0.0 884296 25288 ?        Ssl  07:26   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16476  0.0  0.0 884272 25372 ?        Ssl  07:27   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16482  0.0  0.0 884276 25372 ?        Ssl  07:28   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16488  0.0  0.0 884272 25348 ?        Ssl  07:29   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16494  0.0  0.0 884272 25352 ?        Ssl  07:30   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16503  0.0  0.0 884276 25372 ?        Ssl  07:31   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16509  0.0  0.0 884276 25260 ?        Ssl  07:32   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16515  0.0  0.0 884276 25228 ?        Ssl  07:33   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16521  0.0  0.0 884280 25248 ?        Ssl  07:34   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16527  0.0  0.0 884272 25240 ?        Ssl  07:35   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16534  0.0  0.0 884296 25268 ?        Ssl  07:36   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16540  0.0  0.0 884276 25368 ?        Ssl  07:37   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16546  0.0  0.0 884272 25352 ?        Ssl  07:38   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16552  0.0  0.0 884272 25252 ?        Ssl  07:39   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16558  0.0  0.0 884280 25188 ?        Ssl  07:40   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16565  0.0  0.0 884272 25236 ?        Ssl  07:41   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16571  0.0  0.0 884276 25264 ?        Ssl  07:42   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16577  0.0  0.0 884272 25352 ?        Ssl  07:43   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16583  0.0  0.0 884280 27276 ?        Ssl  07:44   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16590  0.0  0.0 884276 25368 ?        Ssl  07:45   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16597  0.0  0.0 884272 25104 ?        Ssl  07:46   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16603  0.0  0.0 884288 25392 ?        Ssl  07:47   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16609  0.0  0.0 884276 25232 ?        Ssl  07:48   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16615  0.0  0.0 884256 25068 ?        Ssl  07:49   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16621  0.1  0.0 884272 25228 ?        Ssl  07:50   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16628  0.1  0.0 884268 25220 ?        Ssl  07:51   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16634  0.2  0.0 884280 25240 ?        Ssl  07:52   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16792  0.8  0.0 884260 25712 ?        Ssl  07:53   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
agent    16798  0.8  0.0 884276 25232 ?        Ssl  07:53   0:00 PM2 v2.2.2: God Daemon (/home/agent/.pm2)
```

#### PM2 Log output
```
2016-12-30 10:44:21: App name:ev id:32 disconnected
2016-12-30 10:44:21: App [ev] with id [32] and pid [23068], exited with code [99] via signal [SIGINT]
2016-12-30 10:44:21: Starting execution sequence in -cluster mode- for app name:ev id:32
2016-12-30 10:44:21: Error: spawn /home/agent/.nvm/versions/node/v6.9.2/bin/node EMFILE
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2016-12-30 10:44:21: App name:ev id:33 disconnected
2016-12-30 10:44:21: App [ev] with id [33] and pid [23123], exited with code [99] via signal [SIGINT]
2016-12-30 10:44:21: Starting execution sequence in -cluster mode- for app name:ev id:33
2016-12-30 10:44:21: Error: spawn /home/agent/.nvm/versions/node/v6.9.2/bin/node EMFILE
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2016-12-30 10:49:22: App name:ev id:34 disconnected
2016-12-30 10:49:22: App [ev] with id [34] and pid [23139], exited with code [99] via signal [SIGINT]
2016-12-30 10:49:22: Starting execution sequence in -cluster mode- for app name:ev id:34
2016-12-30 10:49:22: Error: spawn /home/agent/.nvm/versions/node/v6.9.2/bin/node EMFILE
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2016-12-30 10:49:24: App name:ev id:26 disconnected
2016-12-30 10:49:24: App [ev] with id [26] and pid [8504], exited with code [99] via signal [SIGINT]
2016-12-30 10:49:24: Starting execution sequence in -cluster mode- for app name:ev id:26
2016-12-30 10:49:24: Error: spawn /home/agent/.nvm/versions/node/v6.9.2/bin/node EMFILE
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2016-12-30 10:49:24: App name:ev id:24 disconnected
2016-12-30 10:49:24: App [ev] with id [24] and pid [8510], exited with code [99] via signal [SIGINT]
2016-12-30 10:49:24: Starting execution sequence in -cluster mode- for app name:ev id:24
2016-12-30 10:49:24: Error: spawn /home/agent/.nvm/versions/node/v6.9.2/bin/node EMFILE
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2016-12-30 10:49:24: App name:ev id:25 disconnected
2016-12-30 10:49:24: App [ev] with id [25] and pid [8520], exited with code [99] via signal [SIGINT]
2016-12-30 10:49:24: Starting execution sequence in -cluster mode- for app name:ev id:25
2016-12-30 10:49:24: Error: spawn /home/agent/.nvm/versions/node/v6.9.2/bin/node EMFILE
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2016-12-30 10:49:24: App name:ev id:27 disconnected
2016-12-30 10:49:24: App [ev] with id [27] and pid [8535], exited with code [99] via signal [SIGINT]
2016-12-30 10:49:24: Starting execution sequence in -cluster mode- for app name:ev id:27
2016-12-30 10:49:24: Error: spawn /home/agent/.nvm/versions/node/v6.9.2/bin/node EMFILE
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2016-12-30 10:49:24: App name:ev id:29 disconnected
2016-12-30 10:49:24: App [ev] with id [29] and pid [8562], exited with code [99] via signal [SIGINT]
2016-12-30 10:49:24: Starting execution sequence in -cluster mode- for app name:ev id:29
2016-12-30 10:49:24: Error: spawn /home/agent/.nvm/versions/node/v6.9.2/bin/node EMFILE
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2016-12-30 10:54:22: App [ev_vacuum] with id [35] and pid [8487], exited with code [99] via signal [SIGINT]
2016-12-30 10:54:22: Starting execution sequence in -fork mode- for app name:ev_vacuum id:35
2016-12-30 10:54:22: App name:ev_vacuum id:35 online
2016-12-30 10:54:22: App name:ev id:28 disconnected
2016-12-30 10:54:22: App [ev] with id [28] and pid [8498], exited with code [99] via signal [SIGINT]
2016-12-30 10:54:22: Starting execution sequence in -cluster mode- for app name:ev id:28
2016-12-30 10:54:23: App name:ev id:28 online
2016-12-30 19:19:24: App name:ev id:31 disconnected
2016-12-30 19:19:24: App [ev] with id [31] and pid [8555], exited with code [99] via signal [SIGINT]
2016-12-30 19:19:24: Starting execution sequence in -cluster mode- for app name:ev id:31
2016-12-30 19:19:24: Error: spawn /home/agent/.nvm/versions/node/v6.9.2/bin/node EMFILE
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2016-12-30 19:24:24: App [ev_vacuum] with id [35] and pid [28322], exited with code [99] via signal [SIGINT]
2016-12-30 19:24:24: Starting execution sequence in -fork mode- for app name:ev_vacuum id:35
2016-12-30 19:24:24: App name:ev_vacuum id:35 online
2016-12-31 07:54:09: ===============================================================================
2016-12-31 07:54:09: --- New PM2 Daemon started ----------------------------------------------------
2016-12-31 07:54:09: Time                 : Sat Dec 31 2016 07:54:09 GMT+0000 (UTC)
2016-12-31 07:54:09: PM2 version          : 2.2.2
2016-12-31 07:54:09: Node.js version      : 6.9.2
2016-12-31 07:54:09: Current arch         : x64
2016-12-31 07:54:09: PM2 home             : /home/agent/.pm2
2016-12-31 07:54:09: PM2 PID file         : /home/agent/.pm2/pm2.pid
2016-12-31 07:54:09: RPC socket file      : /home/agent/.pm2/rpc.sock
2016-12-31 07:54:09: BUS socket file      : /home/agent/.pm2/pub.sock
2016-12-31 07:54:09: Application log path : /home/agent/.pm2/logs
2016-12-31 07:54:09: Process dump file    : /home/agent/.pm2/dump.pm2
2016-12-31 07:54:09: Concurrent actions   : 2
2016-12-31 07:54:09: SIGTERM timeout      : 1600
2016-12-31 07:54:09: ===============================================================================
```

**Comment by vmarchaud** [comment]
There are two many daemon launched, kill them and it should work
PS : `EMFILE` = too many open files so you can't spawn any application.

**Comment by oiime** [comment]
Yeah, I am well aware that I can kill them, problem is the entire service hangs until that happens. I can make a cron job that looks for more than X instances of the daemon and then executes something like `for pid in $(ps -ef | grep "PM2" | awk '{print $2}'); do kill -9 $pid; done` but that seems like a hack an d would still involve downtime

What I'd like to know is _why_ this might happen and as far as I can deduce it is an issue with pm2 respawning itself for no apparent reason. 

I know what EMFILE means, I assume it's somehow triggered by the hundreds of deamons running

**Comment by vmarchaud** [comment]
That's totally not normal indeed, can you make a `DEBUG=* pm2 ls` and copy/paste me what it does ?

**Comment by oiime** [comment]
this is what i'm getting right now, however as i've already restarted the problem is not present. while the problem exists issuing commands to pm2 just hangs.

```
  pm2:paths pm2 home resolved to /home/agent/.pm2 /home/agent +0ms
  pm2:conf Using 2 parallelism (CONCURRENT_ACTIONS) +9ms
  pm2:client Using RPC file /home/agent/.pm2/rpc.sock +176ms
  pm2:client Using PUB file /home/agent/.pm2/pub.sock +0ms
  pm2:interface:daemon Getting interaction info +0ms
  pm2:interface:daemon [PING INTERACTOR] Trying to connect to Interactor daemon +1ms
  axon:sock connect attempt null:/home/agent/.pm2/interactor.sock +0ms
  pm2:client [PING PM2] Trying to connect to server +6ms
  axon:sock connect attempt null:/home/agent/.pm2/rpc.sock +4ms
  axon:sock error ENOENT +4ms
  axon:sock ignored ENOENT +0ms
  axon:sock connect +1ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +2ms
  axon:sock closing +0ms
  axon:sock closing 1 connections +0ms
  pm2:client Daemon alive +7ms
  axon:sock remove socket 0 +1ms
  pm2:client Launching RPC client on socket file /home/agent/.pm2/rpc.sock +2ms
  axon:sock connect attempt null:/home/agent/.pm2/rpc.sock +1ms
  axon:sock connect +1ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  pm2:client RPC Connected to Daemon +1ms
  pm2:cli Now connected to daemon +4ms
  pm2:client Calling daemon method pm2:getVersion on rpc socket:/home/agent/.pm2/rpc.sock +1ms
  pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/home/agent/.pm2/rpc.sock +3ms
  pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/home/agent/.pm2/rpc.sock +19ms
┌────────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────┬────────────┬──────────┐
│ App name   │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu │ mem        │ watching │
├────────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────┼────────────┼──────────┤
│ api        │ 18 │ cluster │ 17324 │ online │ 0       │ 3h     │ 0%  │ 88.2 MB    │ disabled │
│ api        │ 17 │ cluster │ 17303 │ online │ 0       │ 3h     │ 0%  │ 88.1 MB    │ disabled │
│ ev         │ 33 │ cluster │ 17722 │ online │ 0       │ 3h     │ 0%  │ 50.2 MB    │ disabled │
│ ev         │ 32 │ cluster │ 17683 │ online │ 0       │ 3h     │ 0%  │ 56.6 MB    │ disabled │
│ ev         │ 31 │ cluster │ 17658 │ online │ 0       │ 3h     │ 0%  │ 53.2 MB    │ disabled │
│ ev         │ 30 │ cluster │ 17628 │ online │ 0       │ 3h     │ 0%  │ 54.0 MB    │ disabled │
│ ev         │ 29 │ cluster │ 17614 │ online │ 0       │ 3h     │ 0%  │ 54.9 MB    │ disabled │
│ ev         │ 28 │ cluster │ 17569 │ online │ 0       │ 3h     │ 0%  │ 51.3 MB    │ disabled │
│ ev         │ 27 │ cluster │ 17544 │ online │ 0       │ 3h     │ 49% │ 69.6 MB    │ disabled │
│ ev         │ 34 │ cluster │ 17746 │ online │ 0       │ 3h     │ 0%  │ 59.1 MB    │ disabled │
│ ev         │ 25 │ cluster │ 17496 │ online │ 0       │ 3h     │ 0%  │ 54.3 MB    │ disabled │
│ ev         │ 24 │ cluster │ 17466 │ online │ 0       │ 3h     │ 0%  │ 57.5 MB    │ disabled │
│ ev         │ 23 │ cluster │ 17443 │ online │ 0       │ 3h     │ 0%  │ 58.6 MB    │ disabled │
│ ev         │ 22 │ cluster │ 17420 │ online │ 0       │ 3h     │ 0%  │ 60.3 MB    │ disabled │
│ ev         │ 21 │ cluster │ 17398 │ online │ 0       │ 3h     │ 0%  │ 53.8 MB    │ disabled │
│ ev         │ 20 │ cluster │ 17377 │ online │ 0       │ 3h     │ 0%  │ 53.9 MB    │ disabled │
│ ev         │ 19 │ cluster │ 17365 │ online │ 0       │ 3h     │ 0%  │ 61.5 MB    │ disabled │
│ ev         │ 26 │ cluster │ 17514 │ online │ 0       │ 3h     │ 0%  │ 61.3 MB    │ disabled │
│ ev_vacuum  │ 35 │ fork    │ 17803 │ online │ 0       │ 3h     │ 0%  │ 88.5 MB    │ disabled │
│ noc        │ 9  │ cluster │ 17072 │ online │ 0       │ 3h     │ 0%  │ 110.4 MB   │ disabled │
│ noc        │ 1  │ cluster │ 16861 │ online │ 0       │ 3h     │ 0%  │ 126.2 MB   │ disabled │
│ noc        │ 15 │ cluster │ 17234 │ online │ 0       │ 3h     │ 0%  │ 113.4 MB   │ disabled │
│ noc        │ 14 │ cluster │ 17207 │ online │ 0       │ 3h     │ 0%  │ 127.6 MB   │ disabled │
│ noc        │ 13 │ cluster │ 17181 │ online │ 0       │ 3h     │ 0%  │ 142.6 MB   │ disabled │
│ noc        │ 12 │ cluster │ 17154 │ online │ 0       │ 3h     │ 0%  │ 116.6 MB   │ disabled │
│ noc        │ 11 │ cluster │ 17131 │ online │ 0       │ 3h     │ 0%  │ 97.5 MB    │ disabled │
│ noc        │ 10 │ cluster │ 17099 │ online │ 0       │ 3h     │ 0%  │ 129.3 MB   │ disabled │
│ noc        │ 2  │ cluster │ 16887 │ online │ 0       │ 3h     │ 0%  │ 123.3 MB   │ disabled │
│ noc        │ 8  │ cluster │ 17045 │ online │ 0       │ 3h     │ 0%  │ 143.9 MB   │ disabled │
│ noc        │ 7  │ cluster │ 17018 │ online │ 0       │ 3h     │ 0%  │ 130.1 MB   │ disabled │
│ noc        │ 6  │ cluster │ 16991 │ online │ 0       │ 3h     │ 0%  │ 134.0 MB   │ disabled │
│ noc        │ 5  │ cluster │ 16964 │ online │ 0       │ 3h     │ 0%  │ 95.7 MB    │ disabled │
│ noc        │ 4  │ cluster │ 16937 │ online │ 0       │ 3h     │ 0%  │ 131.0 MB   │ disabled │
│ noc        │ 3  │ cluster │ 16910 │ online │ 0       │ 3h     │ 0%  │ 129.6 MB   │ disabled │
│ noc        │ 0  │ cluster │ 16851 │ online │ 0       │ 3h     │ 0%  │ 99.1 MB    │ disabled │
│ supervisor │ 16 │ fork    │ 17285 │ online │ 0       │ 3h     │ 0%  │ 135.6 MB   │ disabled │
└────────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────┴────────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
  axon:sock closing +64ms
  axon:sock closing 1 connections +0ms
  axon:sock remove socket 0 +0ms
  pm2:client PM2 RPC cleanly closed +38ms
  pm2:cli This command took 0.076s to execute +0ms
```

**Comment by vmarchaud** [comment]
Can you try to run with `DEBUG=*` the pm2 command that hangs ?

**Comment by oiime** [comment]
I can try doing that next time when the problem is present. looking at your code the only place I see that relates to 1min intervals is EXEC_TIMEOUT (which I assume is where the deamon is instructed to respawn). do you think postponing the exit via process.on('SIGINT') might somehow be related?

**Comment by oiime** [comment]
noticed today service is down again

```
[agent@s2 ~]$ DEBUG=* pm2 status
  pm2:paths pm2 home resolved to /home/agent/.pm2 /home/agent +0ms
  pm2:conf Using 2 parallelism (CONCURRENT_ACTIONS) +10ms
  pm2:client Using RPC file /home/agent/.pm2/rpc.sock +166ms
  pm2:client Using PUB file /home/agent/.pm2/pub.sock +0ms
  pm2:interface:daemon Getting interaction info +0ms
  pm2:interface:daemon [PING INTERACTOR] Trying to connect to Interactor daemon +1ms
  axon:sock connect attempt null:/home/agent/.pm2/interactor.sock +0ms
  pm2:client [PING PM2] Trying to connect to server +6ms
  axon:sock connect attempt null:/home/agent/.pm2/rpc.sock +4ms
  axon:sock error ENOENT +5ms
  axon:sock ignored ENOENT +0ms
  axon:sock error EAGAIN +0ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect EAGAIN /home/agent/.pm2/rpc.sock
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
```

Not sure it is the same error, there were no multiple daemons this time. From the look of it I _do_ have enough local ports to use but this might be an indication this one is not specifically a pm2 problem. so unless you got any insights I'd keep looking for external causes.

**Comment by vmarchaud** [comment]
Not on this one i'm afraid, i never saw this issue before but it seems to be an external problem. Which ressources have your server ?

**Comment by oiime** [comment]
```
free
              total        used        free      shared  buff/cache   available
Mem:       65694180    19869348    13902432     1458952    31922400    43821756
Swap:             0           0           0
```

```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
Stepping:              1
CPU MHz:               1937.414
BogoMIPS:              4200.03
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-15
```

**Comment by oiime** [comment]
do you use unix sockets to communicate with the daemon?

**Comment by vmarchaud** [comment]
Yeah we use the sockets created in `~/.pm2/*.sock`

**Comment by oiime** [comment]
ran with DEBUG=* now and got an endless stream of this (till i killed the daemon)
```
  axon:queue flush 0 messages +1ms
  axon:sock remove socket 0 +0ms
  axon:sock attempting reconnect +100ms
  axon:sock connect attempt null:/home/agent/.pm2/rpc.sock +0ms
  axon:sock connect +1ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  axon:sock remove socket 0 +1ms
  axon:sock attempting reconnect +101ms
  axon:sock connect attempt null:/home/agent/.pm2/rpc.sock +0ms
  axon:sock connect +0ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  axon:sock remove socket 0 +0ms
  axon:sock attempting reconnect +101ms
  axon:sock connect attempt null:/home/agent/.pm2/rpc.sock +0ms
  axon:sock connect +0ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  axon:sock remove socket 0 +0ms
  axon:sock attempting reconnect +101ms
  axon:sock connect attempt null:/home/agent/.pm2/rpc.sock +0ms
  axon:sock connect +0ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  axon:sock remove socket 0 +0ms
  axon:sock attempting reconnect +101ms
  axon:sock connect attempt null:/home/agent/.pm2/rpc.sock +0ms
  axon:sock connect +0ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  axon:sock remove socket 0 +0ms
  axon:sock attempting reconnect +100ms
  axon:sock connect attempt null:/home/agent/.pm2/rpc.sock +1ms
  axon:sock connect +0ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  axon:sock remove socket 0 +0ms
  axon:sock attempting reconnect +101ms
  axon:sock connect attempt null:/home/agent/.pm2/rpc.sock +0ms
  axon:sock connect +0ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  axon:sock remove socket 0 +0ms
  axon:sock attempting reconnect +101ms
  axon:sock connect attempt null:/home/agent/.pm2/rpc.sock +0ms
  axon:sock connect +0ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  axon:sock remove socket 0 +0ms
  axon:sock attempting reconnect +100ms
  axon:sock connect attempt null:/home/agent/.pm2/rpc.sock +1ms
  axon:sock connect +0ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  axon:sock remove socket 0 +0ms
  axon:sock attempting reconnect +100ms
  axon:sock connect attempt null:/home/agent/.pm2/rpc.sock +0ms
  axon:sock connect +1ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  axon:sock remove socket 0 +0ms
  axon:sock attempting reconnect +100ms
  axon:sock connect attempt null:/home/agent/.pm2/rpc.sock +0ms
  axon:sock connect +0ms
  axon:sock add socket 0 +1ms
  axon:queue flush 0 messages +0ms
  axon:sock remove socket 0 +0ms
```

**Comment by oiime** [comment]
Anyway, it seems the problem is only with PM2 itself as running without it works perfectly. I'd have to stop using this library as it's very unstable for me. better luck to anybody else that encounters this in the future.

**Comment by vmarchaud** [comment]
Closing so, if anyone has more information we'll be happy to try fix the problem.
