### ISSUE TITLE
Error: spawn ps EMFILE

### ISSUE THREAD

**Issue by Maxpain177** [Unitech/pm2#2610]
#### Actual behaviour

PM2 somtimes crashes and not restarts

#### Software versions used

```
OS: Ubuntu 14.04.5 LTS
node.js: v4.6.1
PM2: 2.1.0
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
2017-01-04 14:50:23: [PM2][WORKER] Process 0 restarted because it uses 0 memory and has ONLINE status
2017-01-04 14:50:24: Stopping app:easydrop id:0
2017-01-04 14:50:24: [PM2][WORKER] Error caught by domain:
TypeError: Cannot read property 'on' of undefined
    at buildProcessTree (/usr/local/lib/node_modules/pm2/lib/TreeKill.js:81:14)
    at module.exports (/usr/local/lib/node_modules/pm2/lib/TreeKill.js:32:9)
    at Object.God.killProcess (/usr/local/lib/node_modules/pm2/lib/God/Methods.js:223:7)
    at Object.God.stopProcessId (/usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:261:9)
    at Object.God.restartProcessId (/usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:358:11)
    at maxMemoryRestart (/usr/local/lib/node_modules/pm2/lib/Worker.js:51:11)
    at /usr/local/lib/node_modules/pm2/lib/Worker.js:130:11
    at /usr/local/lib/node_modules/pm2/lib/Worker.js:88:16
    at /usr/local/lib/node_modules/pm2/node_modules/vizion/lib/git.js:148:14
    at /usr/local/lib/node_modules/pm2/node_modules/async/lib/async.js:52:16
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn ps EMFILE
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
```

**Comment by vmarchaud** [comment]
Should be fixed in `PM2 v2.1.6`, see [this](https://github.com/Unitech/pm2/commit/5cbe4fd2369c68183c55b0b6780ef0f69fdff104).
