### ISSUE TITLE
Error install PM2

### ISSUE THREAD

**Issue by VovaZil** [Unitech/pm2#2627]
#### Expected behaviour

Install PM2

#### Actual behaviour

Error

#### Steps to reproduce

npm i pm2 -g

#### Software versions used

```
OS         : Debian 8 x64
node.js    : v6.9.4
PM2        : v3.10.10
```

#### PM2 Log output

```
# npm i pm2 -g
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules                                                                                /pm2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fseven                                                                                ts@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch"                                                                                :"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: expand-range@^1.8.1 (node_mod                                                                                ules/pm2/node_modules/braces/node_modules/expand-range):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Failed to parse json
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: No data, empty input at 1:1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ^
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: File: /root/.npm/expand-range                                                                                /1.8.2/package/package.json
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: repeat-element@^1.1.2 (node_m                                                                                odules/pm2/node_modules/braces/node_modules/repeat-element):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Failed to parse json
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: No data, empty input at 1:1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ^
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: File: /root/.npm/repeat-eleme                                                                                nt/1.1.2/package/package.json
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "pm2" "-g"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! file /root/.npm/preserve/0.2.0/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: /root/.npm/preserve/0.2.0/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```

**Comment by vmarchaud** [comment]
Clean your NPM cache : `rm -rf ~/.npm` and retry, definitly not a PM2 issue.

**Comment by VovaZil** [comment]
@vmarchaud 

What are these errors?

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/pm2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
~# pm2 list
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Object.Configuration.getAllSync (/usr/lib/node_modules/pm2/lib/Configuration.js:271:17)
    at Object.Configuration.getSync (/usr/lib/node_modules/pm2/lib/Configuration.js:242:30)
    at Modularizer.listModules (/usr/lib/node_modules/pm2/lib/API/Modules/Modularizer.js:230:30)
    at Object.Modularizer.launchAll (/usr/lib/node_modules/pm2/lib/API/Modules/Modularizer.js:265:17)
    at /usr/lib/node_modules/pm2/lib/API.js:141:17
    at /usr/lib/node_modules/pm2/lib/Client.js:108:16
    at Timeout._onTimeout (/usr/lib/node_modules/pm2/lib/Client.js:309:19)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

**Comment by vmarchaud** [comment]
Configuration file aren't correctly formatted, you can try to `pm2 kill && rm -rf ~/.pm2 && pm2 ls` and it shouldn't rethrow these errors

**Comment by VovaZil** [comment]
@vmarchaud Thank you.
