### ISSUE TITLE
CakePHP Shells & PM2: SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by Linnk** [Unitech/pm2#2635]
I have some daemons written in NodeJS, vanilla PHP and CakePHP (a framework for PHP). I can start the Node and vanilla PHP daemons using PM2, but the ones written in CakePHP shells can't.

As far as I'm concern, there is no difference in between the output from both kinds of daemons. I checked both outputs with a Hex editor looking for something, but I have found nothing.

#### Steps to reproduce (it takes 5 seconds)

1. Download a fresh CakePHP 2.9.4: https://github.com/cakephp/cakephp/releases/tag/2.9.4
2. Open terminal at the cake folder.
3. Run: `pm2 start app/Console/cake`

It should start the script and stop almost inmeadiatly, but looking at the pm2 log you can see it throws the following error: _SyntaxError: Unexpected token ILLEGAL._

I haven't found anything strange and as I said, I even look at the output with a Hex editor. I don't understand what is going on. Will keep researching, but if someone has a clue it will be wonderful.

#### Software versions used

```
OS:      macOS Sierra 10.12.2
node.js: v4.4.7
PM2:     2.2.3
```

#### PM2 Log output

Use the command: `cat ~/.pm2/logs/cake-error-0.log` and it shows 15x (because of the restarts) the following lines:

```
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function._load (/opt/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Object.<anonymous> (/opt/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:52:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

:(

**Comment by vmarchaud** [comment]
Because like this you ask PM2 to start an node application, you need to have `--interpreter php` and it should works.
