### ISSUE TITLE
Any command line pm2 command results in 

### ISSUE THREAD

**Issue by dragsssss** [Unitech/pm2#2642]
Hi,

I'm having issues running any pm2 commands from the command line, for some reason it keeps on crashing whenever I run a pm2 command but the application is still running ok.

#### Expected behaviour
When entering any command prompt command I expect that pm2 runs well and doesn't crash. For example pm2 list should display a table that shows monitored processes.

#### Actual behaviour
'pm2 list' or any other pm2 command results in an error.
'RangeError: Maximum call stack size exceeded'
![image](https://cloud.githubusercontent.com/assets/520458/22088573/25b44540-de39-11e6-93cc-7c4b7827b9e9.png)

#### Steps to reproduce
Open command prompt and type in 'pm2 list' or any other pm2 command.

#### Software versions used
OS         : Windows 2012 R2 64 bit
node.js    :  v6.9.4
PM2        : v2.2.3
```

#### PM2 Log output

I haven't been able to see anything in the pm2 log file but here it is:

2017-01-18 14:46:21: ===============================================================================
2017-01-18 14:46:21: --- Stopping PM2 --------------------------------------------------------------
2017-01-18 14:46:21: Time                 : Wed Jan 18 2017 14:46:21 GMT+1100 (AUS Eastern Daylight Time)
2017-01-18 14:46:21: ===============================================================================
2017-01-18 14:46:21: RPC closed
2017-01-18 14:46:21: PUB closed
2017-01-18 14:46:21: PM2 successfully stopped
2017-01-18 14:47:50: ===============================================================================
2017-01-18 14:47:50: --- New PM2 Daemon started ----------------------------------------------------
2017-01-18 14:47:50: Time                 : Wed Jan 18 2017 14:47:50 GMT+1100 (AUS Eastern Daylight Time)
2017-01-18 14:47:50: PM2 version          : 2.2.3
2017-01-18 14:47:50: Node.js version      : 6.9.4
2017-01-18 14:47:50: Current arch         : x64
2017-01-18 14:47:50: PM2 home             : C:\pm2\
2017-01-18 14:47:50: PM2 PID file         : C:\pm2\pm2.pid
2017-01-18 14:47:50: RPC socket file      : \\.\pipe\rpc.sock
2017-01-18 14:47:50: BUS socket file      : \\.\pipe\pub.sock
2017-01-18 14:47:50: Application log path : C:\pm2\logs
2017-01-18 14:47:50: Process dump file    : C:\pm2\dump.pm2
2017-01-18 14:47:50: Concurrent actions   : 2
2017-01-18 14:47:50: SIGTERM timeout      : 1600
2017-01-18 14:47:50: ===============================================================================
2017-01-18 14:47:50: ===============================================================================
2017-01-18 14:47:50: --- Stopping PM2 --------------------------------------------------------------
2017-01-18 14:47:50: Time                 : Wed Jan 18 2017 14:47:50 GMT+1100 (AUS Eastern Daylight Time)
2017-01-18 14:47:50: ===============================================================================
2017-01-18 14:47:50: RPC closed
2017-01-18 14:47:50: PUB closed
2017-01-18 14:47:50: PM2 successfully stopped
2017-01-18 14:50:43: ===============================================================================
2017-01-18 14:50:43: --- New PM2 Daemon started ----------------------------------------------------
2017-01-18 14:50:43: Time                 : Wed Jan 18 2017 14:50:43 GMT+1100 (AUS Eastern Daylight Time)
2017-01-18 14:50:43: PM2 version          : 2.2.3
2017-01-18 14:50:43: Node.js version      : 6.9.4
2017-01-18 14:50:43: Current arch         : x64
2017-01-18 14:50:43: PM2 home             : C:\pm2\
2017-01-18 14:50:43: PM2 PID file         : C:\pm2\pm2.pid
2017-01-18 14:50:43: RPC socket file      : \\.\pipe\rpc.sock
2017-01-18 14:50:43: BUS socket file      : \\.\pipe\pub.sock
2017-01-18 14:50:43: Application log path : C:\pm2\logs
2017-01-18 14:50:43: Process dump file    : C:\pm2\dump.pm2
2017-01-18 14:50:43: Concurrent actions   : 2
2017-01-18 14:50:43: SIGTERM timeout      : 1600
2017-01-18 14:50:43: ===============================================================================
2017-01-18 14:50:43: ===============================================================================
2017-01-18 14:50:43: --- Stopping PM2 --------------------------------------------------------------
2017-01-18 14:50:43: Time                 : Wed Jan 18 2017 14:50:43 GMT+1100 (AUS Eastern Daylight Time)
2017-01-18 14:50:43: ===============================================================================
2017-01-18 14:50:43: RPC closed
2017-01-18 14:50:43: PUB closed
2017-01-18 14:50:43: PM2 successfully stopped

**Comment by vmarchaud** [comment]
Can you retry with the patch : `npm install -g Unitech/pm2#development` ? Thanks

**Comment by dragsssss** [comment]
Great, thanks for that.

The error handling and extra logging has helped me figure out what went wrong. It was an issue with an incorrectly formatted pm2 directory in the environment variables. 

dules\mkdirp\index.js:78:17)
Error: ENOENT: no such file or directory, open 'c:\pm2" \m\module_conf.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Client.initFileStructure (C:\Users\Administrator\AppData\Roaming\npm\node
_modules\pm2\lib\Client.js:153:10)

**Comment by vmarchaud** [comment]
Could you try setting one of these [vars](https://github.com/Unitech/pm2/blob/3f5641a67d13b746b861dd2a491206df2eb50cca/paths.js#L14) ?

**Comment by dragsssss** [comment]
Yes, I've set the variable to the correct value. What happened was a node plugin ended up changing the environmental variable from c:\pm2 to c:\pm2" \m which produced the error above.

Changing the environmental variable back to c:\pm2 fixed the issue, the extra logging in the new patch ended up showing me what the problem is.

Thanks.
