### ISSUE TITLE
pm2 babel-node on cluster model

### ISSUE THREAD

**Issue by Maxim-Chugaev** [Unitech/pm2#2666]
```javascript
      {
        "name" : "my_app",
        "exec_interpreter": "babel-node",
        "script" : "./app.js",
        "instances" : "max",
        "exec_mode" : "cluster",
        "env": {
          "COMMON_VARIABLE":      "true"
       },
```
```javascript
/Users/maksim/Documents/rotator/app.js:1
6|rotator  | (function (exports, require, module, __filename, __dirname) { import express     from 'express';
6|rotator  |                                                               ^^^^^^
6|rotator  | SyntaxError: Unexpected token import
6|rotator  |     at Object.exports.runInThisContext (vm.js:78:16)
6|rotator  |     at Module._compile (module.js:543:28)
6|rotator  |     at Object.Module._extensions..js (module.js:580:10)
6|rotator  |     at Module.load (module.js:488:32)
6|rotator  |     at tryModuleLoad (module.js:447:12)
6|rotator  |     at Function.Module._load (module.js:439:3)
6|rotator  |     at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
6|rotator  |     at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:260:23
6|rotator  |     at /usr/local/lib/node_modules/pm2/node_modules/async/lib/async.js:52:16
6|rotator  |     at /usr/local/lib/node_modules/pm2/node_modules/async/lib/async.js:1209:30
```

**Comment by vmarchaud** [comment]
duplicate #2614
