### ISSUE TITLE
Error logs doesn't show in error log file and only shows in pm2 logs on cluster mode

### ISSUE THREAD

**Issue by sqy371** [Unitech/pm2#2696]
#### Behaviour

The code is
```javascript
console.error('test')
testFunc()                 // testFunc is undefined
```
There should be some logs like `ReferenceError: testFunc is not defined` in the error log file on cluster mode, but it only shows in pm2 logs.

#### Steps to reproduce

1. Build a simple node server
```javascript
var http = require('http');
var server = http.createServer(function(req, res ){
	console.error('test')
	testFunc()
	res.write('this is a simple node server')
	res.end()
})
server.listen(3001)
```

2. Use pm2 to start this server on cluster mode, specify out log file and error log file
```
pm2 start server.js -o tmp-o.log -e tmp-e.log -i max
```

3. Display error logs
```
pm2 logs --err
```

4. Tail error log file
```
tail -f tmp-e-*
```

5. visit pages `127.0.0.1:3001`

After the command `pm2 logs --err`:
```
3|server   | test
3|server   | ReferenceError: testFunc is not defined
3|server   |     at Server.<anonymous> (/Users/qiyaoshen/fe/output/server.js:5:2)
3|server   |     at emitTwo (events.js:87:13)
3|server   |     at Server.emit (events.js:172:7)
3|server   |     at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:528:12)
3|server   |     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
```

After the command `tail -f tmp-e-*`:
```
==> tmp-e-0.log <==
test

==> tmp-e-1.log <==
test

==> tmp-e-2.log <==
test

==> tmp-e-3.log <==
test
```

#### Software versions used

```
OS       : OS X El Capitan
node.js  : v4.4.4
PM2      : 2.3.0
```

#### PM2 Log output

Use the command: `tail -50 ~/.pm2/pm2.log`

```
2017-02-06 16:29:44: App name:server id:2 disconnected
2017-02-06 16:29:44: App [server] with id [2] and pid [49056], exited with code [0] via signal [SIGINT]
2017-02-06 16:29:44: App name:server id:1 disconnected
2017-02-06 16:29:44: App [server] with id [1] and pid [49062], exited with code [0] via signal [SIGINT]
2017-02-06 16:29:44: App name:server id:3 disconnected
2017-02-06 16:29:44: App [server] with id [3] and pid [49057], exited with code [0] via signal [SIGINT]
2017-02-06 16:29:44: pid=49061 msg=process killed
2017-02-06 16:29:44: pid=49056 msg=process killed
2017-02-06 16:29:44: pid=49062 msg=process killed
2017-02-06 16:29:44: pid=49057 msg=process killed
2017-02-06 16:30:10: Starting execution sequence in -cluster mode- for app name:server id:0
2017-02-06 16:30:10: App name:server id:0 online
2017-02-06 16:30:10: Starting execution sequence in -cluster mode- for app name:server id:1
2017-02-06 16:30:10: App name:server id:1 online
2017-02-06 16:30:10: Starting execution sequence in -cluster mode- for app name:server id:2
2017-02-06 16:30:10: App name:server id:2 online
2017-02-06 16:30:10: Starting execution sequence in -cluster mode- for app name:server id:3
2017-02-06 16:30:10: App name:server id:3 online
2017-02-06 16:30:34: App name:server id:0 disconnected
2017-02-06 16:30:34: App [server] with id [0] and pid [49326], exited with code [0] via signal [SIGINT]
2017-02-06 16:30:34: Starting execution sequence in -cluster mode- for app name:server id:0
2017-02-06 16:30:34: App name:server id:1 disconnected
2017-02-06 16:30:34: App [server] with id [1] and pid [49327], exited with code [0] via signal [SIGINT]
2017-02-06 16:30:34: Starting execution sequence in -cluster mode- for app name:server id:1
2017-02-06 16:30:34: App name:server id:2 disconnected
2017-02-06 16:30:34: App [server] with id [2] and pid [49328], exited with code [0] via signal [SIGINT]
2017-02-06 16:30:34: Starting execution sequence in -cluster mode- for app name:server id:2
2017-02-06 16:30:35: App name:server id:3 disconnected
2017-02-06 16:30:35: App [server] with id [3] and pid [49329], exited with code [0] via signal [SIGINT]
2017-02-06 16:30:35: Starting execution sequence in -cluster mode- for app name:server id:3
2017-02-06 16:30:35: App name:server id:1 online
2017-02-06 16:30:35: App name:server id:0 online
2017-02-06 16:30:35: App name:server id:2 online
2017-02-06 16:30:35: App name:server id:3 online
2017-02-06 16:30:44: Stopping app:server id:0
2017-02-06 16:30:44: Stopping app:server id:1
2017-02-06 16:30:44: App name:server id:0 disconnected
2017-02-06 16:30:44: App [server] with id [0] and pid [49348], exited with code [0] via signal [SIGINT]
2017-02-06 16:30:44: App name:server id:1 disconnected
2017-02-06 16:30:44: App [server] with id [1] and pid [49349], exited with code [0] via signal [SIGINT]
2017-02-06 16:30:44: pid=49348 msg=process killed
2017-02-06 16:30:44: pid=49349 msg=process killed
2017-02-06 16:30:44: Stopping app:server id:2
2017-02-06 16:30:44: Stopping app:server id:3
2017-02-06 16:30:44: App name:server id:2 disconnected
2017-02-06 16:30:44: App [server] with id [2] and pid [49350], exited with code [0] via signal [SIGINT]
2017-02-06 16:30:44: App name:server id:3 disconnected
2017-02-06 16:30:44: App [server] with id [3] and pid [49351], exited with code [0] via signal [SIGINT]
2017-02-06 16:30:44: pid=49350 msg=process killed
2017-02-06 16:30:44: pid=49351 msg=process killed
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
After investigating it seems that the file descriptor of the error logs isn't flushing the data to the file system, or maybe that the cluster mode close all file descriptors related to the worker, either way we can't really do much here
