### ISSUE TITLE
Node 7.7.2 MongoDB error

### ISSUE THREAD

**Issue by dnohr** [Unitech/pm2#2759]
I'm not sure if it's PM2 or a MongoDB driver bug. After upgrading to Node 7.7.2, my applications connected to MongoDB failed with following error. I have full connection from my server to the database.

**NODE**: 7.7.2
**PM2**: 2.4.2
**MongoDB**: 2.2.24

**Stack trace**:
TypeError: "listener" argument must be a function
at Socket.once (events.js:307:11)
at Socket.connect (net.js:943:10)
at Socket.connect (/usr/lib/node_modules/pm2/node_modules/async-listener/index.js:76:27)
at Object.exports.connect.exports.createConnection (net.js:76:35)
at Connection.connect (/var/nodes/site.com/node_modules/mongodb-core/lib/connection/connection.js:397:11)
at Pool.connect (/var/nodes/site.com/node_modules/mongodb-core/lib/connection/pool.js:638:16)
at Server.connect (/var/nodes/site.com/node_modules/mongodb-core/lib/topologies/server.js:383:17)
at Server.connect (/var/nodes/site.com/node_modules/mongodb/lib/server.js:361:17)
at open (/var/nodes/site.com/node_modules/mongodb/lib/db.js:226:19)
at Db.open (/var/nodes/site.com/node_modules/mongodb/lib/db.js:249:44)

**Solution**:
After downgrading to Node 7.7.1, my applications through PM2 was able to connect to the DB again.

Just a heads up before upgrading your environment to the latest node release.

Thanks.

**Comment by vmarchaud** [comment]
We will push an update today to avoid this with pm2, still opened an issue over the responsible module : https://github.com/othiym23/async-listener/issues/99
Thanks for reporting this !

**Comment by vhain** [comment]
@vmarchaud @dnohr actually, it's bug on Node 7.7.2 and will be fixed by https://github.com/nodejs/node/pull/11762

**Comment by dnohr** [comment]
@vhain Sounds good, thanks for the details.

**Comment by FullTS** [comment]
The same problem!

**Comment by vmarchaud** [comment]
We released pmx `1.0.4` that should fix this issue
