### ISSUE TITLE
Prevent PM2 from adding Logs

### ISSUE THREAD

**Issue by cnole** [Unitech/pm2#2771]
I have a node.js App with Banyun as Logger. All Logs will be transferred by Docker GELF format into ELK so that our PM can easily do some research. I found out that PM2 adds Logs during starting and shutting down the app and in a format which is not configurable, such as with log level '6' instead of using more readable text 'Warning'. Is it possible to turn out this Logging so that our Logs are a little bit clearer?

**Comment by vmarchaud** [comment]
Where does PM2 output the logs you talking about ?

**Comment by cnole** [comment]
When i start the app using pm2-docker, i can see the logs with `docker logs`, that is exact the logs our PM will see in ELK.

**Comment by cnole** [comment]
You can see it in following snippet, notice the difference between the first and second lines. The first line comes from pm2 and the second line comes from Banyun with much more informations:

```
$ docker logs 88dd92745ad97d35d2fb20a6e6c56a6b1968f67e72b648046ce705b00c27794e
{"timestamp":"Thu Mar 16 2017 16:32:31 GMT+0000","type":"process_event","status":"online","app_name":"rechnung"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"INFO\",\"time\":\"2017-03-16T16:32:32.872Z\",\"v\":0,\"message\":\"http server listening on 11001...\",\"loggerName\":\"index\"}","timestamp":"2017-03-16T16:32:32.874Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"ERROR\",\"time\":\"2017-03-16T16:32:32.912Z\",\"v\":0,\"message\":\"Problem making eureka request { Error: connect ECONNREFUSED 127.0.0.1:8761\\n    at Object.exports._errnoException (util.js:1022:11)\\n    at exports._exceptionWithHostPort (util.js:1045:20)\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)\\n  code: 'ECONNREFUSED',\\n  errno: 'ECONNREFUSED',\\n  syscall: 'connect',\\n  address: '127.0.0.1',\\n  port: 8761 }\",\"loggerName\":\"lib/eureka\"}","timestamp":"2017-03-16T16:32:32.915Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"WARN\",\"time\":\"2017-03-16T16:32:32.913Z\",\"v\":0,\"message\":\"Eureka request failed to endpoint http://localhost:8761/eureka/apps/, next server retry in 500ms\",\"loggerName\":\"lib/eureka\"}","timestamp":"2017-03-16T16:32:32.917Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"ERROR\",\"time\":\"2017-03-16T16:32:33.425Z\",\"v\":0,\"message\":\"Problem making eureka request { Error: connect ECONNREFUSED 127.0.0.1:8761\\n    at Object.exports._errnoException (util.js:1022:11)\\n    at exports._exceptionWithHostPort (util.js:1045:20)\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)\\n  code: 'ECONNREFUSED',\\n  errno: 'ECONNREFUSED',\\n  syscall: 'connect',\\n  address: '127.0.0.1',\\n  port: 8761 }\",\"loggerName\":\"lib/eureka\"}","timestamp":"2017-03-16T16:32:33.426Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"WARN\",\"time\":\"2017-03-16T16:32:33.426Z\",\"v\":0,\"message\":\"Eureka request failed to endpoint http://localhost:8761/eureka/apps/, next server retry in 1000ms\",\"loggerName\":\"lib/eureka\"}","timestamp":"2017-03-16T16:32:33.427Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"ERROR\",\"time\":\"2017-03-16T16:32:34.435Z\",\"v\":0,\"message\":\"Problem making eureka request { Error: connect ECONNREFUSED 127.0.0.1:8761\\n    at Object.exports._errnoException (util.js:1022:11)\\n    at exports._exceptionWithHostPort (util.js:1045:20)\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)\\n  code: 'ECONNREFUSED',\\n  errno: 'ECONNREFUSED',\\n  syscall: 'connect',\\n  address: '127.0.0.1',\\n  port: 8761 }\",\"loggerName\":\"lib/eureka\"}","timestamp":"2017-03-16T16:32:34.437Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"WARN\",\"time\":\"2017-03-16T16:32:34.438Z\",\"v\":0,\"message\":\"Eureka request failed to endpoint http://localhost:8761/eureka/apps/, next server retry in 1500ms\",\"loggerName\":\"lib/eureka\"}","timestamp":"2017-03-16T16:32:34.442Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"ERROR\",\"time\":\"2017-03-16T16:32:35.949Z\",\"v\":0,\"message\":\"Problem making eureka request { Error: connect ECONNREFUSED 127.0.0.1:8761\\n    at Object.exports._errnoException (util.js:1022:11)\\n    at exports._exceptionWithHostPort (util.js:1045:20)\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)\\n  code: 'ECONNREFUSED',\\n  errno: 'ECONNREFUSED',\\n  syscall: 'connect',\\n  address: '127.0.0.1',\\n  port: 8761 }\",\"loggerName\":\"lib/eureka\"}","timestamp":"2017-03-16T16:32:35.950Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"WARN\",\"time\":\"2017-03-16T16:32:35.951Z\",\"v\":0,\"message\":\"Error registering with eureka client. { Error: connect ECONNREFUSED 127.0.0.1:8761\\n    at Object.exports._errnoException (util.js:1022:11)\\n    at exports._exceptionWithHostPort (util.js:1045:20)\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)\\n  code: 'ECONNREFUSED',\\n  errno: 'ECONNREFUSED',\\n  syscall: 'connect',\\n  address: '127.0.0.1',\\n  port: 8761 }\",\"loggerName\":\"lib/eureka\"}","timestamp":"2017-03-16T16:32:35.952Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"WARN\",\"time\":\"2017-03-16T16:32:35.952Z\",\"v\":0,\"message\":\"Error starting the Eureka Client { Error: connect ECONNREFUSED 127.0.0.1:8761\\n    at Object.exports._errnoException (util.js:1022:11)\\n    at exports._exceptionWithHostPort (util.js:1045:20)\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)\\n  code: 'ECONNREFUSED',\\n  errno: 'ECONNREFUSED',\\n  syscall: 'connect',\\n  address: '127.0.0.1',\\n  port: 8761 }\",\"loggerName\":\"lib/eureka\"}","timestamp":"2017-03-16T16:32:35.953Z","type":"out","process_id":0,"app_name":"rechnung"}
Exiting PM2
{"message":"Stopping app:rechnung id:0","timestamp":"2017-03-16T16:33:24.523Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"INFO\",\"time\":\"2017-03-16T16:33:24.532Z\",\"v\":0,\"message\":\"shutting down server - deregistering from eureka...\",\"loggerName\":\"index\"}","timestamp":"2017-03-16T16:33:24.533Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"ERROR\",\"time\":\"2017-03-16T16:33:24.538Z\",\"v\":0,\"message\":\"Problem making eureka request { Error: connect ECONNREFUSED 127.0.0.1:8761\\n    at Object.exports._errnoException (util.js:1022:11)\\n    at exports._exceptionWithHostPort (util.js:1045:20)\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)\\n  code: 'ECONNREFUSED',\\n  errno: 'ECONNREFUSED',\\n  syscall: 'connect',\\n  address: '127.0.0.1',\\n  port: 8761 }\",\"loggerName\":\"lib/eureka\"}","timestamp":"2017-03-16T16:33:24.538Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"WARN\",\"time\":\"2017-03-16T16:33:24.538Z\",\"v\":0,\"message\":\"Eureka request failed to endpoint http://localhost:8761/eureka/apps/, next server retry in 500ms\",\"loggerName\":\"lib/eureka\"}","timestamp":"2017-03-16T16:33:24.539Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:24.636Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:24.740Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:24.845Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:24.947Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"ERROR\",\"time\":\"2017-03-16T16:33:25.042Z\",\"v\":0,\"message\":\"Problem making eureka request { Error: connect ECONNREFUSED 127.0.0.1:8761\\n    at Object.exports._errnoException (util.js:1022:11)\\n    at exports._exceptionWithHostPort (util.js:1045:20)\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)\\n  code: 'ECONNREFUSED',\\n  errno: 'ECONNREFUSED',\\n  syscall: 'connect',\\n  address: '127.0.0.1',\\n  port: 8761 }\",\"loggerName\":\"lib/eureka\"}","timestamp":"2017-03-16T16:33:25.043Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"WARN\",\"time\":\"2017-03-16T16:33:25.042Z\",\"v\":0,\"message\":\"Eureka request failed to endpoint http://localhost:8761/eureka/apps/, next server retry in 1000ms\",\"loggerName\":\"lib/eureka\"}","timestamp":"2017-03-16T16:33:25.043Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:25.048Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:25.153Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:25.256Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:25.358Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
0 application online, exiting
Exiting PM2
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:25.467Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"Stopping app:rechnung id:0","timestamp":"2017-03-16T16:33:25.473Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"INFO\",\"time\":\"2017-03-16T16:33:25.483Z\",\"v\":0,\"message\":\"shutting down server - deregistering from eureka...\",\"loggerName\":\"index\"}","timestamp":"2017-03-16T16:33:25.485Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"ERROR\",\"time\":\"2017-03-16T16:33:25.486Z\",\"v\":0,\"message\":\"Problem making eureka request { Error: connect ECONNREFUSED 127.0.0.1:8761\\n    at Object.exports._errnoException (util.js:1022:11)\\n    at exports._exceptionWithHostPort (util.js:1045:20)\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)\\n  code: 'ECONNREFUSED',\\n  errno: 'ECONNREFUSED',\\n  syscall: 'connect',\\n  address: '127.0.0.1',\\n  port: 8761 }\",\"loggerName\":\"lib/eureka\"}","timestamp":"2017-03-16T16:33:25.487Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"WARN\",\"time\":\"2017-03-16T16:33:25.487Z\",\"v\":0,\"message\":\"Eureka request failed to endpoint http://localhost:8761/eureka/apps/, next server retry in 500ms\",\"loggerName\":\"lib/eureka\"}","timestamp":"2017-03-16T16:33:25.488Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:25.567Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:25.586Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:25.669Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:25.695Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:25.776Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:25.799Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:25.886Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:25.903Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:25.990Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"ERROR\",\"time\":\"2017-03-16T16:33:25.992Z\",\"v\":0,\"message\":\"Problem making eureka request { Error: connect ECONNREFUSED 127.0.0.1:8761\\n    at Object.exports._errnoException (util.js:1022:11)\\n    at exports._exceptionWithHostPort (util.js:1045:20)\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)\\n  code: 'ECONNREFUSED',\\n  errno: 'ECONNREFUSED',\\n  syscall: 'connect',\\n  address: '127.0.0.1',\\n  port: 8761 }\",\"loggerName\":\"lib/eureka\"}","timestamp":"2017-03-16T16:33:25.993Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"WARN\",\"time\":\"2017-03-16T16:33:25.993Z\",\"v\":0,\"message\":\"Eureka request failed to endpoint http://localhost:8761/eureka/apps/, next server retry in 1000ms\",\"loggerName\":\"lib/eureka\"}","timestamp":"2017-03-16T16:33:25.995Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:26.014Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"ERROR\",\"time\":\"2017-03-16T16:33:26.046Z\",\"v\":0,\"message\":\"Problem making eureka request { Error: connect ECONNREFUSED 127.0.0.1:8761\\n    at Object.exports._errnoException (util.js:1022:11)\\n    at exports._exceptionWithHostPort (util.js:1045:20)\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)\\n  code: 'ECONNREFUSED',\\n  errno: 'ECONNREFUSED',\\n  syscall: 'connect',\\n  address: '127.0.0.1',\\n  port: 8761 }\",\"loggerName\":\"lib/eureka\"}","timestamp":"2017-03-16T16:33:26.046Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"{\"hostname\":\"88dd92745ad9\",\"pid\":16,\"level\":\"WARN\",\"time\":\"2017-03-16T16:33:26.046Z\",\"v\":0,\"message\":\"Eureka request failed to endpoint http://localhost:8761/eureka/apps/, next server retry in 1500ms\",\"loggerName\":\"lib/eureka\"}","timestamp":"2017-03-16T16:33:26.048Z","type":"out","process_id":0,"app_name":"rechnung"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:26.095Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"pid=16 msg=failed to kill - retrying in 100ms","timestamp":"2017-03-16T16:33:26.116Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"Process with pid 16 still alive after 1600ms, sending it SIGKILL now...","timestamp":"2017-03-16T16:33:26.133Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"App name:rechnung id:0 disconnected","timestamp":"2017-03-16T16:33:26.145Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"App [rechnung] with id [0] and pid [16], exited with code [0] via signal [SIGKILL]","timestamp":"2017-03-16T16:33:26.147Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"timestamp":"Thu Mar 16 2017 16:33:26 GMT+0000","type":"process_event","status":"exit","app_name":"rechnung"}
{"message":"[HandleExit] PM2 is being killed, stopping restart procedure...","timestamp":"2017-03-16T16:33:26.158Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"pid=16 msg=process killed","timestamp":"2017-03-16T16:33:26.219Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"timestamp":"Thu Mar 16 2017 16:33:26 GMT+0000","type":"process_event","status":"exit","app_name":"rechnung"}
{"message":"pid=16 msg=process killed","timestamp":"2017-03-16T16:33:26.244Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"timestamp":"Thu Mar 16 2017 16:33:26 GMT+0000","type":"process_event","status":"exit","app_name":"rechnung"}
{"message":"===============================================================================","timestamp":"2017-03-16T16:33:26.330Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"--- Stopping PM2 --------------------------------------------------------------","timestamp":"2017-03-16T16:33:26.330Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"Time                 : Thu Mar 16 2017 16:33:26 GMT+0000 (UTC)","timestamp":"2017-03-16T16:33:26.332Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"===============================================================================","timestamp":"2017-03-16T16:33:26.332Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
{"message":"RPC closed","timestamp":"2017-03-16T16:33:26.334Z","type":"PM2","process_id":"PM2","app_name":"PM2"}
```

**Comment by vmarchaud** [comment]
Currently it isn't possible since the pm2 daemon make direct call to `console.log`, this need a little work.

**Comment by cnole** [comment]
@vmarchaud Thank you for the info. I think it's OK to ask our PM to ignore those Logs for now :)
