### ISSUE TITLE
pm2 can't start apps

### ISSUE THREAD

**Issue by steevhise** [Unitech/pm2#2785]
If reporting a bug, please use the following template.

#### Expected behaviour
starting an app, such as with 
`pm2 start /usr/bin/sinopia --name 'npm'`
used to work fine. for over a year now....
...

#### Actual behaviour

...
I'm not sure what changed, but  now, it hangs without forking from terminal, with:

>  [PM2] Spawning PM2 daemon
> [PM2] PM2 Successfully daemonized
> [PM2] Starting /usr/bin/sinopia in fork_mode (1 instance)

This is for node apps that still work fine standalone running without pm2.

#### Steps to reproduce
for instance `pm2 start ./lib/server.js --name 'app'`  (after cd to app directory)
...

#### Software versions used

```
OS         : Debian Jessie
node.js    :  v6.10.0
PM2        :  0.14.7
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```

in pm2.log I see:

2017-03-21 21:21:57: RPC interface [READY] on port /root/.pm2/rpc.sock
2017-03-21 21:22:08: PM2 is being killed via kill method
2017-03-21 21:22:08: RPC socket closed
2017-03-21 21:22:08: PUB socket closed
2017-03-21 21:22:09: [PM2][WORKER] Started with refreshing interval: 30000
2017-03-21 21:22:09: [[[[ PM2/God daemon launched ]]]]
2017-03-21 21:22:09: BUS system [READY] on port /root/.pm2/pub.sock
2017-03-21 21:22:09: RPC interface [READY] on port /root/.pm2/rpc.sock
2017-03-21 21:30:42: PM2 is being killed via kill method
2017-03-21 21:30:42: RPC socket closed
2017-03-21 21:30:42: PUB socket closed
2017-03-21 21:34:42: [PM2][WORKER] Started with refreshing interval: 30000
2017-03-21 21:34:42: [[[[ PM2/God daemon launched ]]]]
2017-03-21 21:34:42: BUS system [READY] on port /root/.pm2/pub.sock
2017-03-21 21:34:42: RPC interface [READY] on port /root/.pm2/rpc.sock
2017-03-21 21:34:42: Starting execution sequence in -fork mode- for app name:npm id:0
2017-03-21 21:34:43: App name:npm id:0 online
2017-03-21 21:34:43: [PM2] Error caught by domain:
TypeError: obj.hasOwnProperty is not a function
    at safeDeepClone (/usr/local/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:49:13)
    at safeDeepClone (/usr/local/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:53:22)
    at safeDeepClone (/usr/local/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:53:22)
    at cloneWrap (/usr/local/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:65:10)
    at Object.clone (/usr/local/lib/node_modules/pm2/lib/Utility.js:39:12)
    at Object.Common.deepCopy.Common.serialize.Common.clone (/usr/local/lib/node_modules/pm2/lib/Common.js:165:18)
    at /usr/local/lib/node_modules/pm2/lib/God.js:369:25
    at forkMode (/usr/local/lib/node_modules/pm2/lib/God.js:231:15)
    at /usr/local/lib/node_modules/pm2/lib/God/ForkMode.js:203:22
    at /usr/local/lib/node_modules/pm2/node_modules/async/lib/async.js:52:16
2017-03-21 21:34:43: [PM2] Trying to update PM2...
Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.
/usr/local/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:49
    if (obj.hasOwnProperty(attr)) {
            ^

TypeError: obj.hasOwnProperty is not a function
    at safeDeepClone (/usr/local/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:49:13)
    at safeDeepClone (/usr/local/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:53:22)
    at safeDeepClone (/usr/local/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:53:22)
    at cloneWrap (/usr/local/lib/node_modules/pm2/node_modules/safe-clone-deep/src/index.js:65:10)
    at Object.clone (/usr/local/lib/node_modules/pm2/lib/Utility.js:39:12)
    at Object.Common.deepCopy.Common.serialize.Common.clone (/usr/local/lib/node_modules/pm2/lib/Common.js:165:18)
    at Object.getFormatedProcesses (/usr/local/lib/node_modules/pm2/lib/God/Methods.js:53:21)
    at getMonitorData (/usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:42:25)
    at Server.onmessage (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:105:6)
    at emitTwo (events.js:106:13)

...
```

cf CONTRIBUTING.md for more informations

**Comment by steevhise** [comment]
oops looks like i just fixed it myself.  my path was pointing to an old version of pm2.  when i realized v2.4.2 was in /usr/bin/  and 0.14.7 was in /usr/local/bin/, i realized what was wrong.
