### ISSUE TITLE
Pm2 using Docker and Elastic Beanstalk

### ISSUE THREAD

**Issue by ThiagoMiranda** [Unitech/pm2#2798]
I'm trying to upload a Docker Application on AWS ElasticBeanstalk but it's giving me some errors. Basically I have only a Dockerfile with the image node:6.10.1 and at the and I run a Pm2 instance ( I'm also installing fluentd on this process but I've hide the code to make it more clear since it isn't the problem ):

    FROM node:6.10.1

    RUN useradd --user-group --create-home --shell /bin/false app

    ENV HOME=/home/app

    COPY package.json npm-shrinkwrap.json $HOME/playerlogger/
    RUN chown -R app:app $HOME/*

    USER app
    WORKDIR $HOME/playerlogger

    RUN npm cache clean && npm install --progress=false

    COPY . $HOME/playerlogger
   
    EXPOSE 8081

    WORKDIR $HOME/playerlogger

    CMD ["npm", "run", "dist"]

My npm run dist makes something like this:
   

    ./node_modules/.bin/copyfiles ./server/config/config.json ./.dist && ./node_modules/.bin/babel . -d ./.dist --ignore=\"node_modules\

and then:

    ./node_modules/.bin/pm2 start --no-daemon pm2.json

My pm2.json:

    {
      "apps" : [{
        "name"        : "PlayerLogger",
        "script"      : "server/main.js",
        "args"        : ["--env=prod"],
        "merge_logs"  : true,
        "cwd"         : "./.dist/",
        "instances"   : 0,
        "exec_mode"   : "cluster"
      }]
    }

So when I make a docker build . locally it works perfectly. And also docker run image_name works great locally but when I try to upload my .zip file to Aws Elastic Beanstalk I get this error running pm2:

    17:52:24 0|PlayerLo | SyntaxError: Unexpected reserved word
    17:52:24 0|PlayerLo |     at exports.runInThisContext (vm.js:53:16)
    17:52:24 0|PlayerLo |     at Module._compile (module.js:373:25)
    17:52:24 0|PlayerLo |     at Object.Module._extensions..js (module.js:416:10)
    17:52:24 0|PlayerLo |     at Module.load (module.js:343:32)
    17:52:24 0|PlayerLo |     at Function.Module._load (module.js:300:12)
    17:52:24 0|PlayerLo |     at /home/app/playerlogger/node_modules/pm2/lib/ProcessContainer.js:301:23
    17:52:24 0|PlayerLo |     at /home/app/playerlogger/node_modules/async/lib/async.js:52:16
    17:52:24 0|PlayerLo |     at /home/app/playerlogger/node_modules/async/lib/async.js:1209:30
    17:52:24 0|PlayerLo |     at WriteStream.<anonymous> (/home/app/playerlogger/node_modules/pm2/lib/Utility.js:147:13)

Does anyone knows what could be happening? For me it doesn't make any sense since one of the main advantages of Docker should be the "equality" of the environment independently of the machine. I've tried changing the node image version ( 4.8 ) and tried to initialize pm2 in fork mode. But none of these worked.

I've also changed the `npm run dist` to use the pm2-docker:
`pm2-docker pm2.yml`

And a yml file:
```yml
apps:
  - script   : './.dist/server/main.js'
    name     : 'PlayerLogger'
    exec_mode: 'cluster'
    instances: 4
    cwd: "./.dist/"
    args: "--no-daemon --env=prod"
     
```

But the same behavior occurs: runs in my local machine but not on ElasticBeanstalk. Did anyone came across on this error?

Thanks

**Comment by ThiagoMiranda** [comment]
Sorry. It was a HUGE mistake of mine. I've forgot to zip ( using the Mac Finder ) the .* files including the .babelrc one ( that has the transpile directives ).
