### ISSUE TITLE
Install PM2 module from Github's non-master branch

### ISSUE THREAD

**Issue by ma-zal** [Unitech/pm2#2809]
**Installation of PM2 module from GitHub's non-master branch is failing.**

Problem is, that PM2 is expecting, that final NPM module directory will be `module#branchname`, but real is without `#branchname` of course. So the PM2 finally stores the wrong name to `module_conf.json` -> `module-db` object.

**Example:**
`pm2 install ma-zal/pm2-slack#own-customization`

```
[PM2][Module] Installing module ma-zal/pm2-slack#own-customization
[PM2][Module] Calling [NPM] to install ma-zal/pm2-slack#own-customization ...
--- skiping some lines here ---
/home/nodejs/.pm2
└─┬ pm2-slack@0.3.2  (git+https://github.com/ma-zal/pm2-slack.git#cee398d0ce8aeac02222a9686532331aff4bbd51)
--- skiping some lines here ---
[PM2][Module] Module downloaded
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/nodejs/.pm2/node_modules/pm2-slack#own-customization/package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at startModule (/usr/lib/node_modules/pm2/lib/API/Modules/Modularizer.js:33:22)
    at /usr/lib/node_modules/pm2/lib/API/Modules/Modularizer.js:158:9
    at /usr/lib/node_modules/pm2/lib/Configuration.js:64:14
    at FSReqWrap.oncomplete (fs.js:123:15)
```

```
pm2 --version
2.4.3
```

**Comment by vmarchaud** [comment]
We should add something [here](https://github.com/Unitech/pm2/blob/master/lib/API/Modules/Modularizer.js#L156) to trim the name

**Comment by Unitech** [comment]
@ma-zal looks like a quick fix, feel free to open a PR on this
Basically we just pass arguments to npm
