### ISSUE TITLE
Windows 10 and node 7.8.0 will not start pm2

### ISSUE THREAD

**Issue by ZergRushJoe** [Unitech/pm2#2819]
can't run pm2 on windows 10 with node 7.8.0. this is what shows up

## command run in cmd
`c:\Users\jkarp\Desktop\widgetManager>pm2 start ./bin/www'

## output
```
RangeError: Maximum call stack size exceeded
    at getPathFromURL (internal/url.js:1138:14)
    at Object.fs.mkdirSync (fs.js:893:23)
    at sync (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:71:13)
    at sync (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:77:24)
RangeError: Maximum call stack size exceeded
    at getPathFromURL (internal/url.js:1138:14)
    at Object.fs.mkdirSync (fs.js:893:23)
    at sync (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:71:13)
    at sync (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:77:24)
Error: ENOENT: no such file or directory, open 'U:\.pm2\module_conf.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1316:33)
    at module.exports.Client.initFileStructure (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\lib\Client.js:154:10)
    at new module.exports (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\lib\Client.js:38:8)
    at new module.exports (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\lib\API.js:99:17)
    at Object.<anonymous> (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\bin\pm2:19:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

                        -------------

                      PM2 process manager

__/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
 _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
  _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
   _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
    _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
     _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
      _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
       _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
        _\///______________\///______________\///__\///////////////__


                       Getting started

                        Documentation
                        http://pm2.io/

                      Start PM2 at boot
                        $ pm2 startup

                     Daemonize Application
                       $ pm2 start <app>

                     Monitoring/APM solution
                    https://app.keymetrics.io/

                        -------------

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'U:\.pm2\pm2.log'
    at Object.fs.openSync (fs.js:584:18)
    at module.exports.Client.launchDaemon (C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\lib\Client.js:209:14)
    at C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\lib\Client.js:102:10
    at C:\Users\jkarp\AppData\Roaming\npm\node_modules\pm2\lib\Client.js:291:14
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by vmarchaud** [comment]
Can you try with the Git shell (that use bash instead of the cmd.exe) ?
