### ISSUE TITLE
TypeError: pushInteractor.bufferData is not a function

### ISSUE THREAD

**Issue by jdbranham** [Unitech/pm2#2854]
**What's going wrong?**  
When I build PM2, 5 tests fail.

**How could we reproduce this issue?**
I am doing this for the current master - https://github.com/Unitech/pm2/commit/e18d976788255ff985d29c62c8614005e17c3103

npm install 
npm test

## Supporting information
Failed tests -
```
19 passing (64ms)
  5 failing

  1) Transactions Aggregator .aggregate should aggregate:
     TypeError: pushInteractor.bufferData is not a function
      at merge (/tools/jenkins/jobs/GitHub/jobs/pm2/workspace/lib/Interactor/TransactionAggregator.js:349:26)
      at mergeTrace (/tools/jenkins/jobs/GitHub/jobs/pm2/workspace/lib/Interactor/TransactionAggregator.js:368:16)
      at aggregate (/tools/jenkins/jobs/GitHub/jobs/pm2/workspace/lib/Interactor/TransactionAggregator.js:285:12)
      at Context.<anonymous> (aggregator.mocha.js:172:18)

  2) Transactions Aggregator .normalizeAggregation should get normalized aggregattion:
     TypeError: Cannot read property 'process' of undefined
      at Context.<anonymous> (aggregator.mocha.js:201:31)

  3) Transactions Aggregator .resetAggregation and .clearData should get transactions:

      AssertionError: expected 1 to equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.fail (/tools/jenkins/jobs/GitHub/jobs/pm2/workspace/node_modules/should/cjs/should.js:258:17)
      at Assertion.value (/tools/jenkins/jobs/GitHub/jobs/pm2/workspace/node_modules/should/cjs/should.js:335:19)
      at Context.<anonymous> (aggregator.mocha.js:209:40)

  4) Transactions Aggregator .resetAggregation and .clearData should .resetAggregation for "appname" app:

      AssertionError: expected 2 to equal 4
      + expected - actual

      -2
      +4
      
      at Assertion.fail (/tools/jenkins/jobs/GitHub/jobs/pm2/workspace/node_modules/should/cjs/should.js:258:17)
      at Assertion.value (/tools/jenkins/jobs/GitHub/jobs/pm2/workspace/node_modules/should/cjs/should.js:335:19)
      at Context.<anonymous> (aggregator.mocha.js:215:48)

  5) Transactions Aggregator .resetAggregation and .clearData should .clearData:
     TypeError: Cannot read property 'meta' of undefined
      at Context.<anonymous> (aggregator.mocha.js:228:20)

```

```
NPM version: `npm -v`
3.10.10

Node version: `node -v`
v6.10.0

OS:
Linux RHEL 7
```

**Comment by vmarchaud** [comment]
Can't reproduce under Ubuntu + node 6/7 and our CI isn't experiencing the issue, are you sure that it doesn't come from your environment ?

**Comment by vmarchaud** [comment]
Actually i hit it with our CI, inspected and found the problem, should be fixed with https://github.com/Unitech/pm2/commit/64b0793d191296d15b5e5bfc844fb7324943144d

**Comment by jdbranham** [comment]
Thanks @vmarchaud !
