### ISSUE TITLE
pm2 crashed and delete all processes

### ISSUE THREAD

**Issue by hungbya** [Unitech/pm2#2856]
I have a clean install Centos 7 server (includes only `myslq`, and `nodejs`). I also use this version (`2.4.5`) of `pm2` on another server but nothing goes wrong.

Here is the logs:

```
2017-04-26 19:00:07: --- PM2 global error caught ---------------------------------------------------
2017-04-26 19:00:07: Time                 : Wed Apr 26 2017 19:00:07 GMT+0000 (UTC)
2017-04-26 19:00:07: false == true
2017-04-26 19:00:07: AssertionError: false == true
    at RoundRobinHandle.add (cluster.js:139:3)
    at queryServer (cluster.js:501:12)
    at Worker.onmessage (cluster.js:450:7)
    at ChildProcess.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:753:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
2017-04-26 19:00:07: ===============================================================================
2017-04-26 19:00:07: [PM2] Resurrecting PM2

assert.js:81
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at RoundRobinHandle.add (cluster.js:139:3)
    at queryServer (cluster.js:501:12)
    at Worker.onmessage (cluster.js:450:7)
    at ChildProcess.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:753:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
2017-04-26 19:00:08: ===============================================================================
2017-04-26 19:00:08: --- New PM2 Daemon started ----------------------------------------------------
2017-04-26 19:00:08: Time                 : Wed Apr 26 2017 19:00:08 GMT+0000 (UTC)
2017-04-26 19:00:08: PM2 version          : 2.4.5
2017-04-26 19:00:08: Node.js version      : 6.10.1
2017-04-26 19:00:08: Current arch         : x64
2017-04-26 19:00:08: PM2 home             : /root/.pm2
2017-04-26 19:00:08: PM2 PID file         : /root/.pm2/pm2.pid
2017-04-26 19:00:08: RPC socket file      : /root/.pm2/rpc.sock
2017-04-26 19:00:08: BUS socket file      : /root/.pm2/pub.sock
2017-04-26 19:00:08: Application log path : /root/.pm2/logs
2017-04-26 19:00:08: Process dump file    : /root/.pm2/dump.pm2
2017-04-26 19:00:08: Concurrent actions   : 2
2017-04-26 19:00:08: SIGTERM timeout      : 1600
2017-04-26 19:00:08: ===============================================================================
[PM2] PM2 Successfully daemonized
Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.
[PM2] Saving current process list...
[PM2] Stopping PM2...
[PM2] All processes have been stopped and deleted
2017-04-26 19:00:08: ===============================================================================
2017-04-26 19:00:08: --- Stopping PM2 --------------------------------------------------------------
2017-04-26 19:00:08: Time                 : Wed Apr 26 2017 19:00:08 GMT+0000 (UTC)
2017-04-26 19:00:08: ===============================================================================
2017-04-26 19:00:08: RPC closed
2017-04-26 19:00:08: PUB closed
[PM2] PM2 stopped
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
2017-04-26 19:00:08: PM2 successfully stopped
2017-04-26 19:00:09: ===============================================================================
2017-04-26 19:00:09: --- New PM2 Daemon started ----------------------------------------------------
2017-04-26 19:00:09: Time                 : Wed Apr 26 2017 19:00:09 GMT+0000 (UTC)
2017-04-26 19:00:09: PM2 version          : 2.4.5
2017-04-26 19:00:09: Node.js version      : 6.10.1
2017-04-26 19:00:09: Current arch         : x64
2017-04-26 19:00:09: PM2 home             : /root/.pm2
2017-04-26 19:00:09: PM2 PID file         : /root/.pm2/pm2.pid
2017-04-26 19:00:09: RPC socket file      : /root/.pm2/rpc.sock
2017-04-26 19:00:09: BUS socket file      : /root/.pm2/pub.sock
2017-04-26 19:00:09: Application log path : /root/.pm2/logs
2017-04-26 19:00:09: Process dump file    : /root/.pm2/dump.pm2
2017-04-26 19:00:09: Concurrent actions   : 2
2017-04-26 19:00:09: SIGTERM timeout      : 1600
2017-04-26 19:00:09: ===============================================================================
[PM2] Restoring processes located in /root/.pm2/dump.pm2
>>>>>>>>>> PM2 updated
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

**Comment by vmarchaud** [comment]
The problem come from nodejs itself : 
```
AssertionError: false == true
    at RoundRobinHandle.add (cluster.js:139:3)
```
So you should upgrade your nodejs version to resolve this.

**Comment by hungbya** [comment]
I just updated both `nodejs` and `pm2`, and the same thing happened

```
2017-04-27 12:24:41: ===============================================================================
2017-04-27 12:24:41: --- PM2 global error caught ---------------------------------------------------
2017-04-27 12:24:41: Time                 : Thu Apr 27 2017 12:24:41 GMT+0000 (UTC)
2017-04-27 12:24:41: false == true
2017-04-27 12:24:41: AssertionError: false == true
    at RoundRobinHandle.add (internal/cluster/round_robin_handle.js:34:3)
    at queryServer (internal/cluster/master.js:304:10)
    at Worker.onmessage (internal/cluster/master.js:248:5)
    at ChildProcess.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:194:7)
    at process.nextTick (internal/child_process.js:766:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
2017-04-27 12:24:41: ===============================================================================
2017-04-27 12:24:41: [PM2] Resurrecting PM2

assert.js:81
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at RoundRobinHandle.add (internal/cluster/round_robin_handle.js:34:3)
    at queryServer (internal/cluster/master.js:304:10)
    at Worker.onmessage (internal/cluster/master.js:248:5)
    at ChildProcess.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:194:7)
    at process.nextTick (internal/child_process.js:766:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
2017-04-27 12:24:42: ===============================================================================
2017-04-27 12:24:42: --- New PM2 Daemon started ----------------------------------------------------
2017-04-27 12:24:42: Time                 : Thu Apr 27 2017 12:24:42 GMT+0000 (UTC)
2017-04-27 12:24:42: PM2 version          : 2.4.6
2017-04-27 12:24:42: Node.js version      : 7.9.0
2017-04-27 12:24:42: Current arch         : x64
2017-04-27 12:24:42: PM2 home             : /root/.pm2
2017-04-27 12:24:42: PM2 PID file         : /root/.pm2/pm2.pid
2017-04-27 12:24:42: RPC socket file      : /root/.pm2/rpc.sock
2017-04-27 12:24:42: BUS socket file      : /root/.pm2/pub.sock
2017-04-27 12:24:42: Application log path : /root/.pm2/logs
2017-04-27 12:24:42: Process dump file    : /root/.pm2/dump.pm2
2017-04-27 12:24:42: Concurrent actions   : 2
2017-04-27 12:24:42: SIGTERM timeout      : 1600
2017-04-27 12:24:42: ===============================================================================
[PM2] PM2 Successfully daemonized
Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.
[PM2] Saving current process list...
[PM2] Stopping PM2...
[PM2] All processes have been stopped and deleted
2017-04-27 12:24:42: ===============================================================================
2017-04-27 12:24:42: --- Stopping PM2 --------------------------------------------------------------
2017-04-27 12:24:42: Time                 : Thu Apr 27 2017 12:24:42 GMT+0000 (UTC)
2017-04-27 12:24:42: ===============================================================================
2017-04-27 12:24:42: RPC closed
2017-04-27 12:24:42: PUB closed
2017-04-27 12:24:42: PM2 successfully stopped
[PM2] PM2 stopped
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
2017-04-27 12:24:42: ===============================================================================
2017-04-27 12:24:42: --- New PM2 Daemon started ----------------------------------------------------
2017-04-27 12:24:42: Time                 : Thu Apr 27 2017 12:24:42 GMT+0000 (UTC)
2017-04-27 12:24:42: PM2 version          : 2.4.6
2017-04-27 12:24:42: Node.js version      : 7.9.0
2017-04-27 12:24:42: Current arch         : x64
2017-04-27 12:24:42: PM2 home             : /root/.pm2
2017-04-27 12:24:42: PM2 PID file         : /root/.pm2/pm2.pid
2017-04-27 12:24:42: RPC socket file      : /root/.pm2/rpc.sock
2017-04-27 12:24:42: BUS socket file      : /root/.pm2/pub.sock
2017-04-27 12:24:42: Application log path : /root/.pm2/logs
2017-04-27 12:24:42: Process dump file    : /root/.pm2/dump.pm2
2017-04-27 12:24:42: Concurrent actions   : 2
2017-04-27 12:24:42: SIGTERM timeout      : 1600
2017-04-27 12:24:42: ===============================================================================
[PM2] Restoring processes located in /root/.pm2/dump.pm2
>>>>>>>>>> PM2 updated
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

**Comment by vmarchaud** [comment]
You should open an issue on `nodejs/node`, i personally don't think its linked to PM2 since we just implement the cluster module.

**Comment by LucianoGanga** [comment]
@hungbya could you solve the problem? The same thing is happening to me :/

**Comment by hungbya** [comment]
@LucianoGanga Seems it happens only with cluster mode. Hence, I use fork mode instead of cluster mode.
