### ISSUE TITLE
PM2 get global exception when stop node process in cluster mode

### ISSUE THREAD

**Issue by macurial** [Unitech/pm2#2883]
## Supporting information

```
PM2 version: `v2.4.6`
Node version: `v6.10.3`
Windows
```
I start a cluster Mode ,and watch the `log:PM2` events, and when I stop one of the node process , it's just stopped in the Terminal and the events give me this below:
```
{ data: 'Stopping app:cloudfe-node-web id:0\n',
  at: 1494987284818,
  process: { rev: null, name: 'PM2', pm_id: 'PM2' } }
{ data: 'App name:cloudfe-node-web id:0 disconnected\n',
  at: 1494987284993,
  process: { rev: null, name: 'PM2', pm_id: 'PM2' } }
{ data: '===============================================================================\n',
  at: 1494987284994,
  process: { rev: null, name: 'PM2', pm_id: 'PM2' } }
{ data: '--- PM2 global error caught ---------------------------------------------------\n',
  at: 1494987284994,
  process: { rev: null, name: 'PM2', pm_id: 'PM2' } }
{ data: 'Time                 : Wed May 17 2017 10:14:44 GMT+0800 (中国标准时间)\n',
  at: 1494987284995,
  process: { rev: null, name: 'PM2', pm_id: 'PM2' } }
{ data: 'Cannot read property \'writable\' of undefined\n',
  at: 1494987284995,
  process: { rev: null, name: 'PM2', pm_id: 'PM2' } }
{ data: 'TypeError: Cannot read property \'writable\' of undefined\n    at PubSocket.send (E:\\modules\\pm2-agent\\node_modules\\pm2-axon\\lib\\sockets\\pub.js:47:13)\n    at EventEmitter.<anonymous> (E:\\modules\\pm2-agent\\node_modules\\pm2\\lib\\Daemon.js:388:14)\n    at EventEmitter.emit (E:\\modules\\pm2-agent\\node_modules\\eventemitter2\\lib\\eventemitter2.js:294:22)\n    at Console.console.(anonymous function) [as log] (E:\\modules\\pm2-agent\\node_modules\\pm2\\lib\\Utility.js:81:17)\n    at Worker.<anonymous> (E:\\modules\\pm2-agent\\node_modules\\pm2\\lib\\God.js:187:17)\n    at Worker.g (events.js:291:16)\n    at emitNone (events.js:86:13)\n    at Worker.emit (events.js:185:7)\n    at ChildProcess.<anonymous> (cluster.js:399:14)\n    at ChildProcess.g (events.js:291:16)\n',
  at: 1494987284996,
  process: { rev: null, name: 'PM2', pm_id: 'PM2' } }
```
 and this options does not happened always,it occurred sometimes

**Comment by vmarchaud** [comment]
Pretty sure its because the file descriptor used to communicate are closed before the process really end so it might happen, it isn't fatal so you can ignore it.
