### ISSUE TITLE
NodeJS 8.0.0 Support

### ISSUE THREAD

**Issue by slowdeath007** [Unitech/pm2#2922]
**What's going wrong?** Unable to install pm2 after updating nodeJS to 8.0.0 The following error is print:
```
2777 verbose stack TypeError: Cannot read property 'find' of undefined
2777 verbose stack     at opts.integrity.digests.find.hash (C:\Users\slowdeath007\AppData\Roaming\npm\node_modules\npm\node_modules\ssri\index.js:264:33)
2777 verbose stack     at Array.find (native)
2777 verbose stack     at Transform.on (C:\Users\slowdeath007\AppData\Roaming\npm\node_modules\npm\node_modules\ssri\index.js:263:15)
2777 verbose stack     at emitNone (events.js:110:20)
2777 verbose stack     at Transform.emit (events.js:207:7)
2777 verbose stack     at endReadableNT (_stream_readable.js:1045:12)
2777 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)
2777 verbose stack     at process._tickCallback (internal/process/next_tick.js:161:9)
```

**How could we reproduce this issue?** Use npm install pm2 -g while having nodeJS 8.0 installed

## Supporting information
```
PM2 version: unable to install
Node version: 8.0.0
NPM version : 5.0.1
Windows 10 Build 14393 
```

**Comment by vmarchaud** [comment]
This error isn't coming from PM2, just read the stack.
