### ISSUE TITLE
Different config watсh for development and production

### ISSUE THREAD

**Issue by cawa-93** [Unitech/pm2#2930]
I want to set up PM2 as follows:
For development env:
```js
watch: ['app', 'config', '.env'],
```
For production env
```js
watch: false
```
How to implement this approach?

**Comment by cawa-93** [comment]
I tried to create two separate files with different settings for the environment. But now I'm getting an error when trying to run
```
pm2 startOrRestart ./config/pm2-development.js --only madpost

[PM2] Spawning PM2 daemon with pm2_home=/home/alex/.pm2
[PM2] PM2 Successfully daemonized                                                                                                                                                       
/usr/lib/node_modules/pm2/lib/API.js:866                                                                                                                                                
  if (config.deploy)                                                                                                                                                                    
            ^                                                                                                                                                                           
                                                                                                                                                                                        
TypeError: Cannot read property 'deploy' of undefined                                                                                                                                   
    at module.exports.API._startJson (/usr/lib/node_modules/pm2/lib/API.js:866:13)                                                                                                      
    at Command.<anonymous> (/usr/lib/node_modules/pm2/bin/pm2:296:9)                                                                                                                    
    at Command.listener (/usr/lib/node_modules/pm2/node_modules/commander/index.js:301:8)                                                                                               
    at emitTwo (events.js:125:13)                                                                                                                                                       
    at Command.emit (events.js:213:7)                                                                                                                                                   
    at Command.parseArgs (/usr/lib/node_modules/pm2/node_modules/commander/index.js:615:12)                                                                                             
    at Command.parse (/usr/lib/node_modules/pm2/node_modules/commander/index.js:458:21)                                                                                                 
    at beginCommandProcessing (/usr/lib/node_modules/pm2/bin/pm2:120:13)                                                                                                                
    at /usr/lib/node_modules/pm2/bin/pm2:194:7                                                                                                                                          
    at /usr/lib/node_modules/pm2/lib/API.js:158:14                                                                                                                                      
npm ERR! code ELIFECYCLE                                                                                                                                                                
npm ERR! errno 1                                                                                                                                                                        
npm ERR! madpost@1.0.0 dev: `pm2 startOrRestart ./config/pm2-development.js --only madpost`                                                                                             
npm ERR! Exit status 1                                                                                                                                                                  
npm ERR!                                                                                                                                                                                
npm ERR! Failed at the madpost@1.0.0 dev script.                                                                                                                                        
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alex/.npm/_logs/2017-06-07T14_23_11_830Z-debug.log
```

**Comment by vmarchaud** [comment]
Could you share your configuration ?

**Comment by cawa-93** [comment]
./config/pm2.prod.js
```js
module.exports = {
	/**
	 * Application configuration section
	 * http://pm2.keymetrics.io/docs/usage/application-declaration/
	 */
	apps: [{
		name: 'madpost',
		script: 'server.js',
		exec_mode : "cluster",
		instances : 0,
		watch: false,
	},{
		name: 'madpost-cron',
		script: 'cron.js',
	}],
}
```
./config/pm2.dev.js
```js
module.exports = {
	/**
	 * Application configuration section
	 * http://pm2.keymetrics.io/docs/usage/application-declaration/
	 */
	apps: [{
		name: 'madpost',
		script: 'server.js',
		watch: ['app', 'bootstrap', 'config', '.env']
	},{
		name: 'madpost-cron',
		script: 'cron.js',
	}],
}
```
```bash
$ pm2 startOrRestart ./config/pm2.dev.js

/usr/lib/node_modules/pm2/lib/API.js:866
  if (config.deploy)
            ^

TypeError: Cannot read property 'deploy' of undefined
    at module.exports.API._startJson (/usr/lib/node_modules/pm2/lib/API.js:866:13)
    at Command.<anonymous> (/usr/lib/node_modules/pm2/bin/pm2:296:9)
    at Command.listener (/usr/lib/node_modules/pm2/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:125:13)
    at Command.emit (events.js:213:7)
    at Command.parseArgs (/usr/lib/node_modules/pm2/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/lib/node_modules/pm2/node_modules/commander/index.js:458:21)
    at beginCommandProcessing (/usr/lib/node_modules/pm2/bin/pm2:120:13)
    at /usr/lib/node_modules/pm2/bin/pm2:194:7
    at /usr/lib/node_modules/pm2/lib/API.js:153:14
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! madpost@1.0.0 dev: `pm2 startOrRestart ./config/pm2.dev.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the madpost@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alex/.npm/_logs/2017-06-12T16_47_50_858
```
/home/alex/.npm/_logs/2017-06-12T16_47_50_858
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@5.0.3
3 info using node@v8.1.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle madpost@1.0.0~predev: madpost@1.0.0
6 silly lifecycle madpost@1.0.0~predev: no script for predev, continuing
7 info lifecycle madpost@1.0.0~dev: madpost@1.0.0
8 verbose lifecycle madpost@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle madpost@1.0.0~dev: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/run/media/alex/LinWin/Develop/fb-scaner/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
10 verbose lifecycle madpost@1.0.0~dev: CWD: /run/media/alex/LinWin/Develop/fb-scaner
11 silly lifecycle madpost@1.0.0~dev: Args: [ '-c', 'pm2 startOrRestart ./config/pm2.dev.js' ]
12 silly lifecycle madpost@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle madpost@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: madpost@1.0.0 dev: `pm2 startOrRestart ./config/pm2.dev.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:887:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid madpost@1.0.0
16 verbose cwd /run/media/alex/LinWin/Develop/fb-scaner
17 verbose Linux 4.11.3-1-ARCH
18 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
19 verbose node v8.1.0
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error madpost@1.0.0 dev: `pm2 startOrRestart ./config/pm2.dev.js`
23 error Exit status 1
24 error Failed at the madpost@1.0.0 dev script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by alewaros** [comment]
I'd also like to know if this is a valid approach. Currently it doesn't work like that or I may have misconfigured something.

**Comment by nicotroia** [comment]
using `startOrRestart` command gives me that error as well. (`Cannot read property 'deploy' of undefined`). Using `start`/`restart` separately makes it work as normal

**Comment by gabriel-garcia** [comment]
I'm also having this issue. Is there any way to make `startOrRestart` work without having to resort to `start`/`restart` ?

**Comment by tim-field** [comment]
So config files must be end with `.config.js`  otherwise its not seen, event if you pass it as an argument :rage4:  

Wasted a lot of time until I noticed that
