### ISSUE TITLE
Pm2 after update to 2.5.0

### ISSUE THREAD

**Issue by jkelany** [Unitech/pm2#2939]
after update pm2 to 2.5.0

and run pm2 m command it give me this error

[root@server ~]# pm2 m
TypeError: Object has no method 'repeat'
at sprintf_format (/usr/lib/node_modules/pm2/node_modules/sprintf-js/src/sprintf.js:134:70)
at sprintf (/usr/lib/node_modules/pm2/node_modules/sprintf-js/src/sprintf.js:26:16)
at Object.Dashboard.refresh (/usr/lib/node_modules/pm2/lib/API/Dashboard.js:273:16)
at /usr/lib/node_modules/pm2/lib/API/Extra.js:405:19
at /usr/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
at Parser.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
at Parser.emit (events.js:95:17)
at Parser._write (/usr/lib/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
at doWrite (_stream_writable.js:226:10)
at writeOrBuffer (_stream_writable.js:216:5)

**Comment by vmarchaud** [comment]
Need NodeJS version + OS please

**Comment by jkelany** [comment]
Node.js v0.10.42
Centos 7

**Comment by vmarchaud** [comment]
Sorry but we don't maintain support for nodejs 0.10, it has been deprecated since 1 year already by the nodejs foundation.

**Comment by jkelany** [comment]
My Nodejs was 6.5 and i have two servers updated to 2.4.6 pm2 but the other don't update till i have changed the node to this version

**Comment by torloneg** [comment]
i'have the same problem with pm2 monit
PM2 2.5.0
node v8.1.3 (npm v5.0.3)

TypeError: Object   has no method 'repeat'
