### ISSUE TITLE
PM2 crashes when PM2 m used.

### ISSUE THREAD

**Issue by PsyTae** [Unitech/pm2#2943]
**What's going wrong?**

I have a process that needs to be monitored by PM2, occasionally the process gets above 1.76 GB of memory and the entire PM2 monitoring app crashes at that point.

I can run the process by itself with
node --max_old_space_size=4096 process.js

And it doesn't seem to crash on its own.

If I setup pm2 with that node argument
pm2 start process.js --watch --node-args="--max_old_space_size=4096"

pm2 crashes and shuts down all monitored processes if one of my monitored processes climbs above 1.76GB

## Supporting information

```
pm2 -v          2.4.6
node -v         v5.4.0
Windows
```

**Comment by vmarchaud** [comment]
Can you try with `--max-memory-restart 4G` ? ([docs](http://pm2.keymetrics.io/docs/usage/process-management/#max-memory-restart))
Or if PM2 crash, do you have any logs of it ?

**Comment by PsyTae** [comment]
PM@_HOME System Variable = c:\ProgramData\.pm2\

Directory of C:\Users\Administrator\AppData\Roaming\npm

05/31/2017  10:45 PM    <DIR>          .
05/31/2017  10:45 PM    <DIR>          ..
01/08/2016  03:19 PM    <DIR>          etc
05/31/2017  10:45 PM    <DIR>          node_modules
05/31/2017  10:45 PM               282 pm2
05/31/2017  10:45 PM               290 pm2-dev
05/31/2017  10:45 PM               198 pm2-dev.cmd
05/31/2017  10:45 PM               296 pm2-docker
05/31/2017  10:45 PM               204 pm2-docker.cmd
07/15/2016  07:19 PM               346 pm2-service-install
07/15/2016  07:19 PM               254 pm2-service-install.cmd
07/15/2016  07:19 PM               350 pm2-service-uninstall
07/15/2016  07:19 PM               258 pm2-service-uninstall.cmd
05/31/2017  10:45 PM               190 pm2.cmd
05/31/2017  10:45 PM               288 rundev
05/31/2017  10:45 PM               196 rundev.cmd
              12 File(s)          3,152 bytes
               4 Dir(s)  22,641,106,944 bytes free

C:\ProgramData\.pm2\pm2.log

Logs For around the crashes.

```
2017-06-09 23:03:07: Starting execution sequence in -fork mode- for app name:FleetFTPFolderWatcher id:2
2017-06-09 23:03:07: App name:FleetFTPFolderWatcher id:2 online
2017-06-10 06:18:23: App [FleetFTPFolderWatcher] with id [2] and pid [5676], exited with code [1] via signal [SIGINT]
2017-06-10 06:18:23: Starting execution sequence in -fork mode- for app name:FleetFTPFolderWatcher id:2
2017-06-10 06:18:24: App name:FleetFTPFolderWatcher id:2 online
2017-06-10 06:29:07: App [FleetFTPFolderWatcher] with id [2] and pid [7052], exited with code [1] via signal [SIGINT]
2017-06-10 06:29:07: Starting execution sequence in -fork mode- for app name:FleetFTPFolderWatcher id:2
2017-06-10 06:29:07: App name:FleetFTPFolderWatcher id:2 online
2017-06-10 06:39:35: App [FleetFTPFolderWatcher] with id [2] and pid [4484], exited with code [1] via signal [SIGINT]
2017-06-10 06:39:35: Starting execution sequence in -fork mode- for app name:FleetFTPFolderWatcher id:2
2017-06-10 06:39:35: App name:FleetFTPFolderWatcher id:2 online
2017-06-10 08:25:09: App [FleetFTPFolderWatcher] with id [2] and pid [11932], exited with code [1] via signal [SIGINT]
2017-06-10 08:25:09: Starting execution sequence in -fork mode- for app name:FleetFTPFolderWatcher id:2
2017-06-10 08:25:09: App name:FleetFTPFolderWatcher id:2 online
2017-06-10 08:41:37: ===============================================================================
2017-06-10 08:41:37: --- PM2 global error caught ---------------------------------------------------
2017-06-10 08:41:37: Time                 : Sat Jun 10 2017 08:41:37 GMT+0000 (Coordinated Universal Time)
2017-06-10 08:41:37: spawn ENOMEM
2017-06-10 08:41:37: Error: spawn ENOMEM
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at Object.stats.win (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\pidusage\lib\stats.js:128:16)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\pidusage\index.js:13:28)
    at Object.exports.stat (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\pidusage\index.js:37:20)
    at computeMonitor (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\lib\God\ActionMethods.js:59:18)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\async\lib\async.js:181:20
    at iterate (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\async\lib\async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\async\lib\async.js:281:9)
2017-06-10 08:41:37: ===============================================================================
2017-06-10 08:41:37: [PM2] Resurrecting PM2
module.js:328
    throw err;
    ^

Error: Cannot find module 'C:\Users\Administrator\bin\pm2'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:1003:3
2017-06-10 08:41:38: PM2 successfully forked
2017-06-12 14:27:44: ===============================================================================
2017-06-12 14:27:44: --- New PM2 Daemon started ----------------------------------------------------
2017-06-12 14:27:44: Time                 : Mon Jun 12 2017 14:27:44 GMT+0000 (Coordinated Universal Time)
2017-06-12 14:27:44: PM2 version          : 2.4.6
2017-06-12 14:27:44: Node.js version      : 5.4.0
2017-06-12 14:27:44: Current arch         : x64
2017-06-12 14:27:44: PM2 home             : C:\ProgramData\.pm2\
2017-06-12 14:27:44: PM2 PID file         : C:\ProgramData\.pm2\pm2.pid
2017-06-12 14:27:44: RPC socket file      : \\.\pipe\rpc.sock
2017-06-12 14:27:44: BUS socket file      : \\.\pipe\pub.sock
2017-06-12 14:27:44: Application log path : C:\ProgramData\.pm2\logs
2017-06-12 14:27:44: Process dump file    : C:\ProgramData\.pm2\dump.pm2
2017-06-12 14:27:44: Concurrent actions   : 2
2017-06-12 14:27:44: SIGTERM timeout      : 1600
2017-06-12 14:27:44: ===============================================================================
2017-06-12 14:27:44: Starting execution sequence in -fork mode- for app name:pm2-logrotate id:0
2017-06-12 14:27:44: App name:pm2-logrotate id:0 online
2017-06-12 14:33:06: [Watch] Start watching 1
2017-06-12 14:33:06: Starting execution sequence in -fork mode- for app name:ColdFusionMoninitor id:1
2017-06-12 14:33:06: [Watch] Start watching 2
2017-06-12 14:33:06: Starting execution sequence in -fork mode- for app name:FleetFTPFolderWatcher id:2
2017-06-12 14:33:06: App name:ColdFusionMoninitor id:1 online
2017-06-12 14:33:06: App name:FleetFTPFolderWatcher id:2 online
2017-06-12 14:33:06: [Watch] Start watching 3
2017-06-12 14:33:06: Starting execution sequence in -fork mode- for app name:FileZillaLogsTailWatcher id:3
2017-06-12 14:33:06: App name:FileZillaLogsTailWatcher id:3 online
2017-06-12 14:50:30: ===============================================================================
2017-06-12 14:50:30: --- PM2 global error caught ---------------------------------------------------
2017-06-12 14:50:30: Time                 : Mon Jun 12 2017 14:50:30 GMT+0000 (Coordinated Universal Time)
2017-06-12 14:50:30: This socket is closed.
2017-06-12 14:50:30: Error: This socket is closed.
    at Socket._writeGeneric (net.js:640:19)
    at Socket._write (net.js:694:8)
    at doWrite (_stream_writable.js:292:12)
    at clearBuffer (_stream_writable.js:396:7)
    at onwrite (_stream_writable.js:331:7)
    at Socket.WritableState.onwrite (_stream_writable.js:89:5)
    at WriteWrap.afterWrite (net.js:775:12)
2017-06-12 14:50:30: ===============================================================================
2017-06-12 14:50:30: [PM2] Resurrecting PM2
module.js:328
    throw err;
    ^

Error: Cannot find module 'C:\Users\Administrator\bin\pm2'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:1003:3
2017-06-12 14:50:30: PM2 successfully forked
2017-06-12 14:50:38: ===============================================================================
2017-06-12 14:50:38: --- New PM2 Daemon started ----------------------------------------------------
2017-06-12 14:50:38: Time                 : Mon Jun 12 2017 14:50:38 GMT+0000 (Coordinated Universal Time)
2017-06-12 14:50:38: PM2 version          : 2.4.6
2017-06-12 14:50:38: Node.js version      : 5.4.0
2017-06-12 14:50:38: Current arch         : x64
2017-06-12 14:50:38: PM2 home             : C:\ProgramData\.pm2\
2017-06-12 14:50:38: PM2 PID file         : C:\ProgramData\.pm2\pm2.pid
2017-06-12 14:50:38: RPC socket file      : \\.\pipe\rpc.sock
2017-06-12 14:50:38: BUS socket file      : \\.\pipe\pub.sock
2017-06-12 14:50:38: Application log path : C:\ProgramData\.pm2\logs
2017-06-12 14:50:38: Process dump file    : C:\ProgramData\.pm2\dump.pm2
2017-06-12 14:50:38: Concurrent actions   : 2
2017-06-12 14:50:38: SIGTERM timeout      : 1600
2017-06-12 14:50:38: ===============================================================================
2017-06-12 14:50:38: Starting execution sequence in -fork mode- for app name:pm2-logrotate id:0
2017-06-12 14:50:38: App name:pm2-logrotate id:0 online
2017-06-12 14:51:33: 2 : id unknown
2017-06-12 15:06:17: [Watch] Start watching 1
2017-06-12 15:06:17: Starting execution sequence in -fork mode- for app name:ColdFusionMoninitor id:1
2017-06-12 15:06:17: [Watch] Start watching 2
2017-06-12 15:06:17: Starting execution sequence in -fork mode- for app name:FleetFTPFolderWatcher id:2
2017-06-12 15:06:17: App name:ColdFusionMoninitor id:1 online
2017-06-12 15:06:17: App name:FleetFTPFolderWatcher id:2 online
2017-06-12 15:06:17: [Watch] Start watching 3
2017-06-12 15:06:17: Starting execution sequence in -fork mode- for app name:FileZillaLogsTailWatcher id:3
```

restarted my pm2 app with 
pm2 start FleetFTPFolderWatcher.js --watch --node-args="--max_old_space_size=4096" --max-memory-restart 4G to see if that remedies.

**Comment by PsyTae** [comment]
This has crashed a few time today after setting up the job with
pm2 start FleetFTPFolderWatcher.js --watch --node-args="--max_old_space_size=4096" --max-memory-restart 4G

**Comment by PsyTae** [comment]
I think this might be more towards writing logs or something, as I killed Everything and wiped out the logs folder and emptied pm2.log, and now my streaming logs no longer show up.   pm2 m the the global Logs section is empty.   and pm2 logs or pm2 logs 0 doesn't show anything.

I can navigate to my logs folder and the files are there and constantly getting updated.....

**Comment by vmarchaud** [comment]
Could you try with other nodejs version ? The version 5 isn't maintained since almost a year already

**Comment by PsyTae** [comment]
This Keeps Happeneing....
2017-06-12 23:12:18: ===============================================================================
2017-06-12 23:12:18: --- PM2 global error caught ---------------------------------------------------
2017-06-12 23:12:18: Time                 : Mon Jun 12 2017 23:12:18 GMT+0000 (Coordinated Universal Time)
2017-06-12 23:12:18: This socket is closed.
2017-06-12 23:12:18: Error: This socket is closed.
    at Socket._writeGeneric (net.js:640:19)
    at Socket._write (net.js:694:8)
    at doWrite (_stream_writable.js:292:12)
    at clearBuffer (_stream_writable.js:396:7)
    at onwrite (_stream_writable.js:331:7)
    at Socket.WritableState.onwrite (_stream_writable.js:89:5)
    at WriteWrap.afterWrite (net.js:775:12)
```
2017-06-12 23:12:18: ===============================================================================
2017-06-12 23:12:18: [PM2] Resurrecting PM2
module.js:328
    throw err;
    ^

Error: Cannot find module 'C:\Users\Administrator\bin\pm2'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:1003:3
2017-06-12 23:12:19: PM2 successfully forked
```

only C:\Users\Administrator\bin\pm2  should be pointing to either 
C:\Users\Administrator\AppData\Roaming\npm
or
C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\bin

This is installed Globally and I don't know why it can't find itself when it crashes.

**Comment by PsyTae** [comment]
update node version as requested
pm2 -v 2.5.0
node -v v6.11.0

**Comment by vmarchaud** [comment]
@PsyTae And its still happening ?

**Comment by PsyTae** [comment]
So far it has stayed up for 10 minutes without crashing after updating node versions.

I think it is crashing more often than not when I have either 'pm2 m' running in a command window, or pm2 logs # up in a command window.   Then the logs will stop scrolling.  and if I look at pm2 l (L) none of my processes are running, and I look in pm2.log and see "This socket is closed" global error.

Then it trying to resurrect and I get this error about bin/pm2 only it is missing some folders to where it should actually be going.
C:\Users\Administrator\bin\pm2  // where it is looking
C:\Users\Administrator\AppData\Roaming\npm\pm2  // should be looking here for the executable
C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\bin // or should be looking here for the executable

**Comment by vmarchaud** [comment]
do you use a windows service to restart pm2 when it crash maybe ?

**Comment by PsyTae** [comment]
"pm2 m" sees to be the culprit for socket is closed error.
I just got it again after no problems all day, and it was when I closed a cmd window that had pm2 m running in it.
As Soon as I closed the window my pm2 logs # window stopped streaming and When I tried a pm2 l it restarted the deamon with nothing running.
I had to use pm2 resurrect and it come up successfully using that.

```
2017-06-13 20:11:09: ===============================================================================
2017-06-13 20:11:09: --- PM2 global error caught ---------------------------------------------------
2017-06-13 20:11:09: Time                 : Tue Jun 13 2017 20:11:09 GMT+0000 (Coordinated Universal Time)
2017-06-13 20:11:09: This socket is closed
2017-06-13 20:11:09: Error: This socket is closed
    at Socket._writeGeneric (net.js:679:19)
    at Socket._write (net.js:730:8)
    at doWrite (_stream_writable.js:331:12)
    at clearBuffer (_stream_writable.js:438:7)
    at onwrite (_stream_writable.js:370:7)
    at Socket.WritableState.onwrite (_stream_writable.js:90:5)
    at WriteWrap.afterWrite (net.js:812:12)
2017-06-13 20:11:09: ===============================================================================
2017-06-13 20:11:09: [PM2] Resurrecting PM2
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\Administrator\bin\pm2'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
2017-06-13 20:11:09: PM2 successfully forked
2017-06-13 20:11:25: ===============================================================================
2017-06-13 20:11:25: --- New PM2 Daemon started ----------------------------------------------------
2017-06-13 20:11:25: Time                 : Tue Jun 13 2017 20:11:25 GMT+0000 (Coordinated Universal Time)
2017-06-13 20:11:25: PM2 version          : 2.5.0
2017-06-13 20:11:25: Node.js version      : 6.11.0
2017-06-13 20:11:25: Current arch         : x64
2017-06-13 20:11:25: PM2 home             : C:\Users\Administrator\.pm2
2017-06-13 20:11:25: PM2 PID file         : C:\Users\Administrator\.pm2\pm2.pid
2017-06-13 20:11:25: RPC socket file      : \\.\pipe\rpc.sock
2017-06-13 20:11:25: BUS socket file      : \\.\pipe\pub.sock
2017-06-13 20:11:25: Application log path : C:\Users\Administrator\.pm2\logs
2017-06-13 20:11:25: Process dump file    : C:\Users\Administrator\.pm2\dump.pm2
2017-06-13 20:11:25: Concurrent actions   : 2
2017-06-13 20:11:25: SIGTERM timeout      : 1600
2017-06-13 20:11:25: ===============================================================================
2017-06-13 20:11:25: Starting execution sequence in -fork mode- for app name:pm2-logrotate id:0
2017-06-13 20:11:25: App name:pm2-logrotate id:0 online
2017-06-13 20:11:49: [Watch] Start watching 1
2017-06-13 20:11:49: Starting execution sequence in -fork mode- for app name:ColdFusionMoninitor id:1
2017-06-13 20:11:49: [Watch] Start watching 2
2017-06-13 20:11:49: Starting execution sequence in -fork mode- for app name:diskspace id:2
2017-06-13 20:11:49: App name:ColdFusionMoninitor id:1 online
2017-06-13 20:11:49: App name:diskspace id:2 online
2017-06-13 20:11:49: [Watch] Start watching 3
2017-06-13 20:11:49: Starting execution sequence in -fork mode- for app name:FileZillaLogsTailWatcher id:3
2017-06-13 20:11:49: App name:FileZillaLogsTailWatcher id:3 online
2017-06-13 20:11:49: [Watch] Start watching 4
2017-06-13 20:11:49: Starting execution sequence in -fork mode- for app name:FleetFTPFolderWatcher id:4
2017-06-13 20:11:49: App name:FleetFTPFolderWatcher id:4 online
```

**Comment by PsyTae** [comment]
I could not get the windows service to really work with pm2.

I ended up creating a Windows scheduled task that triggered on startup to
Start a program | C:\Users\Administrator\AppData\Roaming\npm\pm2.cmd resurrect

**Comment by PsyTae** [comment]
How much more data, are you needing?
Nothing For 14 days.

This is not a max memory issue as thought when opened.  It is an issue when using PM2 monit or pm2 m.

PM2 crashes and will not restart correctly.

**Comment by eran10** [comment]
happen to us in pm2 2.6.1 -> from some reason pm2 crash, what can we do here guys ?

**Comment by Unitech** [comment]
fixed in recent versions
