### ISSUE TITLE
Process exit with Error: bind EADDRINUSE 0.0.0.0

### ISSUE THREAD

**Issue by zhujun24** [Unitech/pm2#2947]
Process exit with `Error: bind EADDRINUSE 0.0.0.0`, not `Error: bind EADDRINUSE`
Anyone has find this issue?
```
pm2 start index.js -i max
```
After start this process, it will exit and reload every 2-5 minutes
```
Error: bind EADDRINUSE 0.0.0.0
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at dgram.js:221:18
    at /qiguo/thor/thor/shared/node_modules/async-listener/glue.js:188:31
    at /qiguo/thor/thor/shared/node_modules/async-listener/glue.js:188:31
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)
```
```
PM2 version: 2.5.0
Node version: v6.2.2
OS: CentOS release 6.5 (Final)
```

**Comment by vmarchaud** [comment]
You must have others processes that try to bind the address, i would advise to checkout which process is binding the address (there is a stackoverflow post about this but can't remember the post exactly)
