### ISSUE TITLE
change the app path while the pm2 daemon is still running 

### ISSUE THREAD

**Issue by gejiawen** [Unitech/pm2#2959]
Hi, there

I have changed the app path while the pm2 daemon is running, then `pm2 reload`,  it says:

```
Error: ENOENT: no such file or directory, uv_cwd
PM2        |     at Error (native)
PM2        |     at Object.resolve (path.js:1142:25)
PM2        |     at Function.Module._resolveLookupPaths (module.js:390:17)
PM2        |     at Function.Module._resolveFilename (module.js:460:31)
PM2        |     at Function.Module._load (module.js:417:25)
PM2        |     at Module.require (module.js:497:17)
PM2        |     at require (internal/module.js:20:19)
PM2        |     at Object.<anonymous> (/node_modules/pm2/lib/ProcessContainer.js:12:15)
PM2        |     at Module._compile (module.js:570:32)
PM2        |     at Object.Module._extensions..js (module.js:579:10)
```

Why I have this error message?

PM2 version: 2.4.6
Node version: 6.10
Linux

**Comment by vmarchaud** [comment]
You can't change the app path with a `pm2 reload`, you need to delete the process and restart it.
