### ISSUE TITLE
pm2 syntax error with object spread operator?

### ISSUE THREAD

**Issue by damianobarbati** [Unitech/pm2#2966]
Node: v8.1.2 (obj spread operator supported)
PM2: 2.4.4

I have the following code:
```
const config = require('../package.json');
const keys = require('./keys.js');

let env = process.env.NODE_ENV;
if(!env)
    throw new Error('NODE_ENV is undefined');

let result = {
    ...{ name: config.name },
    ...{ browserslist: config.browserslist },
    ...config.config,
    ...config.config[env],
    ...keys
};
```
PM2 complaining:
```
PM2        | Starting execution sequence in -cluster mode- for app name:Quant01 id:0
PM2        | App name:Quant01 id:0 online
0|Quant01  | /Users/damz/Desktop/quant01/config/config.js:9
0|Quant01  |     ...{ name: config.name },
0|Quant01  |     ^^^
0|Quant01  | SyntaxError: Unexpected token ...
0|Quant01  |     at createScript (vm.js:74:10)
0|Quant01  |     at Object.runInThisContext (vm.js:116:10)
0|Quant01  |     at Module._compile (module.js:533:28)
0|Quant01  |     at Object.Module._extensions..js (module.js:580:10)
0|Quant01  |     at Module.load (module.js:503:32)
0|Quant01  |     at tryModuleLoad (module.js:466:12)
0|Quant01  |     at Function.Module._load (module.js:458:3)
0|Quant01  |     at Module.require (module.js:513:17)
0|Quant01  |     at require (internal/module.js:11:18)
0|Quant01  |     at Object.<anonymous> (/Users/damz/Desktop/quant01/index.js:3:16)
PM2        | App name:Quant01 id:0 disconnected
PM2        | App [Quant01] with id [0] and pid [3505], exited with code [0] via signal [SIGINT]
```

But everything is correct! 
Firing with `NODE_ENV=development node index.js` gives not problem at all!

What's going on?
Node 8.1.2 is the only version installed on the system (brew).

**Comment by damianobarbati** [comment]
Got it: in pm2.config.js add the following
`node_args: '--max_old_space_size=256 --harmony --trace-deprecation'`
