### ISSUE TITLE
Dump is purged on ENOSPC error

### ISSUE THREAD

**Issue by bisubus** [Unitech/pm2#2971]
**What's going wrong?**

After the server accidentally gets out of space error and tried to recover with `pm2 resurrect`, this results in empty dump.pm2 (`[]`), even though no `pm2 save` or `pm2 dump` were performed at that time.

Since PM2 writes dump.pm2 occasionally with WatchDog, it is expected that it should make a backup copy before updating it and probably revert to it.

Probably related to #2827 

**How could we reproduce this issue?**

## Supporting information

*pm2.log*
```
2017-06-27 03:15:57: App name:some-app id:1 online
2017-06-27 03:15:57: App [some-app] with id [1] and pid [56501], exited with code [1] via signal [SIGINT]
2017-06-27 03:15:57: Starting execution sequence in -fork mode- for app name:some-app id:1
2017-06-27 03:15:57: Error: ENOSPC: no space left on device, write
    at Error (native)
    at Object.fs.writeSync (fs.js:780:20)
    at Object.fs.writeFileSync (fs.js:1337:24)
    at /usr/lib/node_modules/pm2/lib/God/ForkMode.js:226:12
    at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:52:16
    at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:1209:30
    at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:147:13)
    at emitOne (events.js:96:13)
    at WriteStream.emit (events.js:188:7)
    at WriteStream.<anonymous> (fs.js:1884:10)
20172017-06-27 05:22:00: ===============================================================================
2017-06-27 05:22:00: --- New PM2 Daemon started ----------------------------------------------------
2017-06-27 05:22:00: Time                 : Tue Jun 27 2017 05:22:00 GMT+0300 (MSK)
2017-06-27 05:22:00: PM2 version          : 2.5.0
2017-06-27 05:22:00: Node.js version      : 6.2.2
2017-06-27 05:22:00: Current arch         : x64
2017-06-27 05:22:00: PM2 home             : /root/.pm2
2017-06-27 05:22:00: PM2 PID file         : /root/.pm2/pm2.pid
2017-06-27 05:22:00: RPC socket file      : /root/.pm2/rpc.sock
2017-06-27 05:22:00: BUS socket file      : /root/.pm2/pub.sock
2017-06-27 05:22:00: Application log path : /root/.pm2/logs
2017-06-27 05:22:00: Process dump file    : /root/.pm2/dump.pm2
2017-06-27 05:22:00: Concurrent actions   : 2
2017-06-27 05:22:00: SIGTERM timeout      : 1600
2017-06-27 05:22:00: ===============================================================================

```
```
PM2 version: 2.5.0
Node version: 6.2.2
Linux
```

**Comment by bisubus** [comment]
Interestingly, after the list of processes is recreated by hand, process stats (restart count) are not lost. I'm not sure where they originate from if they don't persist in dump.pm2. Could they be retrieved from Keymetrics?
