### ISSUE TITLE
pm2-monit(1) does not exist when running pm2 reload/show, etc

### ISSUE THREAD

**Issue by kaelzhang** [Unitech/pm2#3007]
**What's going wrong?**

Error message:

```sh
$ pm2 reload m

pm2-monit(1) does not exist, try --help

Use --update-env to update environment variables
internal/child_process.js:317
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:317:11)
    at exports.spawn (child_process.js:491:9)
    at Command.executeSubCommand (/installer/node/lib/node_modules/pm2/node_modules/commander/index.js:546:14)
    at Command.parse (/installer/node/lib/node_modules/pm2/node_modules/commander/index.js:475:17)
    at beginCommandProcessing (/installer/node/lib/node_modules/pm2/bin/pm2:120:13)
    at /installer/node/lib/node_modules/pm2/bin/pm2:194:7
    at /installer/node/lib/node_modules/pm2/lib/API.js:153:14
    at /installer/node/lib/node_modules/pm2/lib/Client.js:54:16
    at Timeout._onTimeout (/installer/node/lib/node_modules/pm2/lib/Client.js:325:19)
```

**How could we reproduce this issue?**

0. Start with a non-root user
1. install node to `/installer/node` (not confirm whether this is necessary to reproduce this issue)
2. adds `/installer/node/bin` to `PATH`
3. npm i -g pm2
4. start a server with `pm2 start ... --name='foo'`
5. then `pm2 show foo` and `pm2 reload foo` and many other commands will print the error message.

BTW, `pm2 restart foo` is ok. 

## Supporting information

```
PM2 version: `pm2 -v`  # 2.5.0
Node version: `node -v` # v8.1.3
Windows? Mac? Linux? # CentOS release 6.5 (Final)
```

**Comment by vmarchaud** [comment]
I believe you just don't have access to the pm2 dir, checkout the permission on the `~/.pm2` folder

**Comment by kaelzhang** [comment]
I have access to ~/.pm2 which I'm sure.

**Comment by vmarchaud** [comment]
Pretty sure it's a permission issue because `pm2 monit` is just a class that retrieve process data from the daemon (via the RPC server exposed on a socket so your problem might come from here).
Could you try to launch `DEBUG=* pm2 monit` ?

**Comment by kaelzhang** [comment]
Launch both `DEBUG=* pm2 monit` and `pm2 monit` are OK

```
pm2:paths pm2 home resolved to /home/scm/.pm2 /home/scm +0ms
  pm2:conf Using 2 parallelism (CONCURRENT_ACTIONS) +10ms
  pm2:client Using RPC file /home/scm/.pm2/rpc.sock +193ms
  pm2:client Using PUB file /home/scm/.pm2/pub.sock +1ms
  pm2:interface:daemon Getting interaction info +0ms
  pm2:interface:daemon [PING INTERACTOR] Trying to connect to Interactor daemon +1ms
  axon:sock connect attempt null:/home/scm/.pm2/interactor.sock +0ms
  pm2:client [PING PM2] Trying to connect to server +6ms
  axon:sock connect attempt null:/home/scm/.pm2/rpc.sock +4ms
  axon:sock error ENOENT +5ms
  axon:sock ignored ENOENT +0ms
  axon:sock connect +0ms
  axon:sock add socket 0 +1ms
  axon:queue flush 0 messages +1ms
  axon:sock closing +0ms
  axon:sock closing 1 connections +1ms
  pm2:client Daemon alive +8ms
  axon:sock remove socket 0 +1ms
  pm2:client Launching RPC client on socket file /home/scm/.pm2/rpc.sock +1ms
  axon:sock connect attempt null:/home/scm/.pm2/rpc.sock +0ms
  axon:sock connect +1ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  pm2:client RPC Connected to Daemon +2ms
  pm2:cli Now connected to daemon +4ms
  pm2:client Calling daemon method pm2:getVersion on rpc socket:/home/scm/.pm2/rpc.sock +1ms
  axon:sock connect attempt null:/home/scm/.pm2/pub.sock +272ms
  pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/home/scm/.pm2/rpc.sock +267ms
  axon:sock attempting reconnect +3ms
  axon:sock closing +0ms
  axon:sock closing 0 connections +0ms
  pm2:interface:daemon Interactor Daemon not launched +2ms
  axon:sock connect attempt null:/home/scm/.pm2/interactor.sock +0ms
  axon:sock error ENOENT +2ms
  axon:sock ignored ENOENT +0ms
  axon:sock connect +4ms
  axon:sock add socket 0 +0ms
  axon:sub subscribe to "log:*" +0ms
```

**Comment by kaelzhang** [comment]
My doubt is that `pm2 reload` should not attempt to launch `pm2-monit` rather than `pm2 monit`

**Comment by Unitech** [comment]
fixed, that's a weird bug from commander.js
