### ISSUE TITLE
Symlinks issues / logs directory, pm2 corrupts filesystem.

### ISSUE THREAD

**Issue by joshribakoff** [Unitech/pm2#3019]
```
PM2 version: `pm2 -v` 2.5.0
Node version: `node -v` 6.11.0
Windows? Mac? Linux? "Ubuntu 14.04.5 LTS"

Also I am running Ubuntu as a guest inside Vagrant Virtual Box provider w/ shared folders, on a Fedora host system.
```
I have a script at `foo/communicator/dist/index.js`. I create a symlink `ln -s foo sym`.

I then run `pm2 start sym/communicator/dist/index.js`:
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/repos$ pm2 start sym/services.dist.json 
[PM2][WARN] Applications API - Communicator not running, starting...
[PM2][WARN] Folder does not exists: /vagrant/repos/sym/logs
[PM2] Creating folder: /vagrant/repos/sym/logs
[PM2][WARN] Folder does not exists: /vagrant/repos/sym/logs
[PM2] Creating folder: /vagrant/repos/sym/logs
[PM2][WARN] Folder does not exists: /vagrant/repos/sym/logs
[PM2] Creating folder: /vagrant/repos/sym/logs
[PM2][ERROR] Could not create folder: ../logs
/home/vagrant/.nvm/versions/node/v6.11.0/lib/node_modules/pm2/lib/Common.js:206
          throw new Error('Could not create folder');
```
After pm2 fails, I list the directory `ls -lah sym/`:

```
d????????? ? ?       ?            ?            ? logs/
```

Now I can't use my system at all, pm2 apparently corrupted my filesystem....

```
$ sudo rm -fr logs
rm: cannot remove ‘logs’: Is a directory

mv logs deleteme
mv: cannot stat ‘logs’: No such file or directory

```

Here's my services.json:
```
{
  "apps": [
    {
      "name": "API - Communicator",
      "args": [],
      "script": "dist/index.js",
      "cwd": "/vagrant/repos/sym/communicator",
      "node_args": [
        "--harmony"
      ],
      "log_date_format": "YYYY-MM-DD HH:mm Z",
      "error_file": "../logs/communicator.stderr.log",
      "out_file": "../logs/communicator.stdout.log",
      "pid_file": "../logs/communicator.pid",
      "instances": 1,
      //or 0 => 'max'
      "min_uptime": "200s",
      // 200 seconds, defaults to 1000
      "max_restarts": 10000,
      // defaults to 15
      "max_memory_restart": "256M",
      "watch": false,
      "ignore_watch": [
        "[\\/\\\\]\\./",
        "node_modules",
        "src",
        "typings",
        "log",
        ".idea"
      ],
      "merge_logs": true,
      "exec_interpreter": "node",
      "exec_mode": "fork",
      "autorestart": true
    }
  ]
}

```

What I was hoping to accomplish was run the script from capistrano's `current` symlink, so if the symlink is updated to point at new code release  & pm2 sees the new code. When capistrano prunes old code folders off the disk, pm2 can no longer find the script (since its not using a symlink). When I try to do a basic test w/ symlinks, it corrupts my filesystem.

I then tried deleting the parent folder which contained the `logs` folder. I was able to delete, but now I can't re-create it, it says it already exists yet it does not:
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/repos$ mkdir -p foo/
mkdir: cannot create directory ‘foo/’: File exists
vagrant@vagrant-ubuntu-trusty-64:/vagrant/repos$ ls -la |grep foo
vagrant@vagrant-ubuntu-trusty-64:/vagrant/repos$ 

```

I repeated the test again in another folder & it worked perfectly first time. Not sure if a pm2 bug or a Vagrant issue, or a Linux thing? Either way I am concerned about the stability of this setup, to say the least. I've been using this setup without any such problems, using supervisord & symlinks without problems.

**Comment by joshribakoff** [comment]
And now another crash, after capistrano updates the symlink, pm2 status fails to run:
```
root@ubuntu:/var/www/html/app/current/# pm2 status
path.js:1142
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1142:25)
    at Function.Module._resolveLookupPaths (module.js:390:17)
    at Function.Module._resolveFilename (module.js:460:31)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/.nvm/versions/node/v6.11.1/lib/node_modules/pm2/bin/pm2:7:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by vmarchaud** [comment]
Try using absolute path with the logs directories ?

**Comment by joshribakoff** [comment]
I found this link http://pm2.keymetrics.io/docs/tutorials/capistrano-like-deployments

I will also try using absolute path for the log directory from now on, thanks.
