### ISSUE TITLE
Start Application with specific user won't work

### ISSUE THREAD

**Issue by Bizarrus** [Unitech/pm2#3055]
## What's going wrong?
I wan't to start an Node.js Application with an specific user:

> pm2 start main.js --user="globalpm2" --hp="/srv" --pid="Server.pid" --name="DEV" --node-args="--harmony" --merge-logs --log ./logs/main.log --output ./logs/output.log --error ./logs/error.log 

**Result:**
```
[PM2] Starting /srv/DEV/ChatServer/main.js in fork_mode (1 instance)
[PM2] Done.
┌──────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬──────────┬────────┬──────────┐
│ App name │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem      │ user   │ watching │
├──────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼──────────┼────────┼──────────┤
│ DEV      │ 0  │ fork │ 11407 │ online │ 0       │ 0s     │ 0%  │ 7.1 MB   │ salvos │ disabled │
└──────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴──────────┴────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

When i try to restart or stop the service with another user, pm2 can't find the process:
> [PM2][WARN] DEV doesn't exist

> pm2 restart --user="globalpm2" --hp="/srv" --pid="Server.pid" "DEV"

## Supporting information
```
$ pm2 report
```

```
===============================================================================
--- PM2 REPORT (Sat Jul 29 2017 12:05:58 GMT+0200 (CEST)) ---------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.6.1
node version         : 0.10.29
node path            : /usr/local/bin/pm2
argv                 : node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : undefined
user                 : root
uid                  : N/A
gid                  : N/A
uptime               : 2663min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.6.1
node version         : 0.10.29
node path            : /usr/local/bin/pm2
argv                 : node,/usr/local/bin/pm2,report
argv0                : undefined
user                 : root

/usr/local/lib/node_modules/pm2/lib/API/Extra.js:70
        fmt.field('uid', process.geteuid());
                                 ^
TypeError: Object #<process> has no method 'geteuid'
    at /usr/local/lib/node_modules/pm2/lib/API/Extra.js:70:34
    at /usr/local/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:4                                                                                        5:10
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon                                                                                        /lib/sockets/req.js:67:8)
    at Parser.emit (events.js:95:17)
    at Parser._write (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/node                                                                                        _modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Parser.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:585:24)
    at flow (_stream_readable.js:594:7)
You have new mail in /var/mail/root
```

Additional method with **--uuid** or **--gid** only works with root, but why?

**Comment by vmarchaud** [comment]
You need to have the right to use `setuid` so by default you need to be under `root`, see [this](https://stackoverflow.com/questions/13040644/setuid-equivalent-for-non-root-users)

**Comment by Unitech** [comment]
`node version         : 0.10.29`

Upgrade your node.js version, https://nodejs.org/api/process.html#process_process_geteuid, geteuid is available since node 2

**Comment by Bizarrus** [comment]
I don't know, why node-version `0.10.29` is set; I had installed the latest version.

But currently, i've tried to create a new infrastructure - I had installed one of my machines completely new and try it again.

Thanks for the tips. I will try it.

**Comment by intergleam** [comment]
same issue here, my node app creates a screen and this screen ends under root, not under user that I've specified

**Comment by intergleam** [comment]
had to do 
```
var userid = require('userid');
var userId = userid.uid("myuser");
exec(`screen -S sessionName -d -m bash -c "xxx"`, { uid: userId  })
```
