### ISSUE TITLE
pm2 crashes under DDoS

### ISSUE THREAD

**Issue by Maxpain177** [Unitech/pm2#3097]
## What's going wrong?
Pm2 crashes under DDoS (cluster mode).

## How could we reproduce this issue?

- Start app in cluster mode.
- Send many http requests

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
===============================================================================
--- PM2 REPORT (Thu Aug 17 2017 11:26:40 GMT+0300 (MSK)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.6.1
node version         : 4.8.4
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : undefined
user                 : maxpain
uid                  : 0
gid                  : 0
uptime               : 22min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.6.1
node version         : 4.8.4
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : undefined
user                 : maxpain
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
cpus nb              : 8
freemem              : 31085887488
totalmem             : 67584950272
home                 : /home/maxpain
===============================================================================
--- PM2 list -----------------------------------------------
┌────────────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────┬────────────┬─────────┬──────────┐
│ App name       │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu │ mem        │ user    │ watching │
├────────────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────┼────────────┼─────────┼──────────┤
│ dota2_easydrop │ 6  │ cluster │ 25884 │ online │ 0       │ 16m    │ 0%  │ 81.0 MB    │ maxpain │ disabled │
│ dota2_easydrop │ 11 │ cluster │ 26022 │ online │ 0       │ 16m    │ 0%  │ 81.9 MB    │ maxpain │ disabled │
│ dota2_easydrop │ 10 │ cluster │ 25993 │ online │ 0       │ 16m    │ 0%  │ 74.8 MB    │ maxpain │ disabled │
│ dota2_easydrop │ 9  │ cluster │ 25966 │ online │ 0       │ 16m    │ 0%  │ 76.3 MB    │ maxpain │ disabled │
│ dota2_easydrop │ 4  │ cluster │ 25852 │ online │ 0       │ 16m    │ 0%  │ 72.8 MB    │ maxpain │ disabled │
│ dota2_easydrop │ 5  │ cluster │ 25858 │ online │ 0       │ 16m    │ 0%  │ 77.3 MB    │ maxpain │ disabled │
│ dota2_easydrop │ 8  │ cluster │ 25939 │ online │ 0       │ 16m    │ 0%  │ 73.0 MB    │ maxpain │ disabled │
│ dota2_easydrop │ 7  │ cluster │ 25911 │ online │ 0       │ 16m    │ 0%  │ 74.9 MB    │ maxpain │ disabled │
│ easydrop       │ 1  │ cluster │ 25688 │ online │ 0       │ 16m    │ 20% │ 168.9 MB   │ maxpain │ disabled │
│ easydrop       │ 3  │ cluster │ 25747 │ online │ 0       │ 16m    │ 19% │ 160.4 MB   │ maxpain │ disabled │
│ easydrop       │ 2  │ cluster │ 25719 │ online │ 0       │ 16m    │ 10% │ 150.0 MB   │ maxpain │ disabled │
│ easydrop       │ 0  │ cluster │ 25677 │ online │ 0       │ 16m    │ 24% │ 172.5 MB   │ maxpain │ disabled │
└────────────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────┴────────────┴─────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
<--- Last few GCs --->

932253310 ms: Scavenge 1088.0 (1126.5) -> 1088.0 (1126.5) MB, 0.0 / 0 ms (+ 0.8 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
932253501 ms: Mark-sweep 1088.0 (1126.5) -> 656.7 (694.5) MB, 191.6 / 0 ms (+ 0.9 ms in 2 steps since start of marking, biggest step 0.8 ms) [last resort gc].
932253656 ms: Mark-sweep 656.7 (694.5) -> 656.7 (694.5) MB, 154.6 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x70ccdcd37399 <JS Object>
    2: onconnection [cluster.js:~119] [pc=0x70ccbbe08d1e] (this=0x70ccb8596821 <a TCP with map 0x70ccdcfb9fe1>,err=-24,handle=0x70ccdcd04131 <undefined>)

==== Details ================================================

[2]: onconnection [cluster.js:~119] [pc=0x70ccbbe08d1e] (this=0x70ccb8596821 <a TCP with map 0x70ccdcfb9fe1>,err=-24,handle=0x70ccdcd04131 <undefined>) {
// optimized frame
------...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
2017-08-17 11:03:41: ===============================================================================
2017-08-17 11:03:41: --- New PM2 Daemon started ----------------------------------------------------
2017-08-17 11:03:41: Time                 : Thu Aug 17 2017 11:03:41 GMT+0300 (MSK)
2017-08-17 11:03:41: PM2 version          : 2.6.1
2017-08-17 11:03:41: Node.js version      : 4.8.4
2017-08-17 11:03:41: Current arch         : x64
2017-08-17 11:03:41: PM2 home             : /home/maxpain/.pm2
2017-08-17 11:03:41: PM2 PID file         : /home/maxpain/.pm2/pm2.pid
2017-08-17 11:03:41: RPC socket file      : /home/maxpain/.pm2/rpc.sock
2017-08-17 11:03:41: BUS socket file      : /home/maxpain/.pm2/pub.sock
2017-08-17 11:03:41: Application log path : /home/maxpain/.pm2/logs
2017-08-17 11:03:41: Process dump file    : /home/maxpain/.pm2/dump.pm2
2017-08-17 11:03:41: Concurrent actions   : 2
2017-08-17 11:03:41: SIGTERM timeout      : 1600
2017-08-17 11:03:41: ===============================================================================
2017-08-17 11:03:58: Starting execution sequence in -cluster mode- for app name:easydrop id:0
2017-08-17 11:03:58: App name:easydrop id:0 online
2017-08-17 11:03:58: Starting execution sequence in -cluster mode- for app name:easydrop id:1
2017-08-17 11:03:58: App name:easydrop id:1 online
2017-08-17 11:03:58: Starting execution sequence in -cluster mode- for app name:easydrop id:2
2017-08-17 11:03:58: App name:easydrop id:2 online
2017-08-17 11:03:58: Starting execution sequence in -cluster mode- for app name:easydrop id:3
2017-08-17 11:03:58: App name:easydrop id:3 online
2017-08-17 11:03:59: App name:easydrop id:3 disconnected
2017-08-17 11:03:59: App [easydrop] with id [3] and pid [21002], exited with code [0] via signal [SIGINT]
2017-08-17 11:03:59: Starting execution sequence in -cluster mode- for app name:easydrop id:3
2017-08-17 11:03:59: App name:easydrop id:3 online
2017-08-17 11:04:00: App name:easydrop id:1 disconnected
2017-08-17 11:04:00: App [easydrop] with id [1] and pid [20948], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:00: Starting execution sequence in -cluster mode- for app name:easydrop id:1
2017-08-17 11:04:00: App name:easydrop id:1 online
2017-08-17 11:04:08: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:4
2017-08-17 11:04:08: App name:dota2_easydrop id:4 online
2017-08-17 11:04:08: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:5
2017-08-17 11:04:08: App name:dota2_easydrop id:5 online
2017-08-17 11:04:08: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:6
2017-08-17 11:04:08: App name:dota2_easydrop id:6 online
2017-08-17 11:04:08: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:7
2017-08-17 11:04:08: App name:dota2_easydrop id:7 online
2017-08-17 11:04:08: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:8
2017-08-17 11:04:08: App name:dota2_easydrop id:8 online
2017-08-17 11:04:08: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:9
2017-08-17 11:04:08: App name:dota2_easydrop id:9 online
2017-08-17 11:04:08: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:10
2017-08-17 11:04:09: App name:dota2_easydrop id:10 online
2017-08-17 11:04:09: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:11
2017-08-17 11:04:09: App name:dota2_easydrop id:11 online
2017-08-17 11:04:10: App name:dota2_easydrop id:4 disconnected
2017-08-17 11:04:10: App [dota2_easydrop] with id [4] and pid [21216], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:10: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:4
2017-08-17 11:04:10: App name:dota2_easydrop id:4 online
2017-08-17 11:04:11: App name:dota2_easydrop id:11 disconnected
2017-08-17 11:04:11: App [dota2_easydrop] with id [11] and pid [21374], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:11: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:11
2017-08-17 11:04:11: App name:dota2_easydrop id:11 online
2017-08-17 11:04:11: App name:dota2_easydrop id:7 disconnected
2017-08-17 11:04:11: App [dota2_easydrop] with id [7] and pid [21276], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:11: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:7
2017-08-17 11:04:11: App name:dota2_easydrop id:7 online
2017-08-17 11:04:12: App name:dota2_easydrop id:8 disconnected
2017-08-17 11:04:12: App [dota2_easydrop] with id [8] and pid [21303], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:12: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:8
2017-08-17 11:04:12: App name:dota2_easydrop id:10 disconnected
2017-08-17 11:04:12: App [dota2_easydrop] with id [10] and pid [21363], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:12: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:10
2017-08-17 11:04:12: App name:dota2_easydrop id:8 online
2017-08-17 11:04:12: App name:dota2_easydrop id:10 online
2017-08-17 11:04:13: App name:dota2_easydrop id:4 disconnected
2017-08-17 11:04:13: App [dota2_easydrop] with id [4] and pid [21444], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:13: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:4
2017-08-17 11:04:13: App name:dota2_easydrop id:6 disconnected
2017-08-17 11:04:13: App [dota2_easydrop] with id [6] and pid [21249], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:13: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:6
2017-08-17 11:04:13: App name:dota2_easydrop id:4 online
2017-08-17 11:04:13: App name:dota2_easydrop id:6 online
2017-08-17 11:04:13: App name:dota2_easydrop id:11 disconnected
2017-08-17 11:04:13: App [dota2_easydrop] with id [11] and pid [21478], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:13: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:11
2017-08-17 11:04:14: App name:dota2_easydrop id:11 online
2017-08-17 11:04:14: App name:dota2_easydrop id:7 disconnected
2017-08-17 11:04:14: App [dota2_easydrop] with id [7] and pid [21493], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:14: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:7
2017-08-17 11:04:14: App name:dota2_easydrop id:7 online
2017-08-17 11:04:15: App name:dota2_easydrop id:8 disconnected
2017-08-17 11:04:15: App [dota2_easydrop] with id [8] and pid [21584], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:15: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:8
2017-08-17 11:04:15: App name:dota2_easydrop id:8 online
2017-08-17 11:04:15: App name:dota2_easydrop id:10 disconnected
2017-08-17 11:04:15: App [dota2_easydrop] with id [10] and pid [21610], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:15: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:10
2017-08-17 11:04:15: App name:dota2_easydrop id:10 online
2017-08-17 11:04:15: App name:dota2_easydrop id:4 disconnected
2017-08-17 11:04:15: App [dota2_easydrop] with id [4] and pid [21706], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:15: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:4
2017-08-17 11:04:15: App name:dota2_easydrop id:4 online
2017-08-17 11:04:16: App name:dota2_easydrop id:6 disconnected
2017-08-17 11:04:16: App [dota2_easydrop] with id [6] and pid [21716], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:16: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:6
2017-08-17 11:04:16: App name:dota2_easydrop id:6 online
2017-08-17 11:04:16: App name:dota2_easydrop id:11 disconnected
2017-08-17 11:04:16: App [dota2_easydrop] with id [11] and pid [21806], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:16: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:11
2017-08-17 11:04:16: App name:dota2_easydrop id:11 online
2017-08-17 11:04:17: App name:dota2_easydrop id:8 disconnected
2017-08-17 11:04:17: App [dota2_easydrop] with id [8] and pid [21894], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:17: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:8
2017-08-17 11:04:17: App name:dota2_easydrop id:8 online
2017-08-17 11:04:17: App name:dota2_easydrop id:10 disconnected
2017-08-17 11:04:17: App [dota2_easydrop] with id [10] and pid [21909], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:17: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:10
2017-08-17 11:04:17: App name:dota2_easydrop id:10 online
2017-08-17 11:04:18: App name:dota2_easydrop id:4 disconnected
2017-08-17 11:04:18: App [dota2_easydrop] with id [4] and pid [21939], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:18: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:4
2017-08-17 11:04:18: App name:dota2_easydrop id:6 disconnected
2017-08-17 11:04:18: App [dota2_easydrop] with id [6] and pid [21979], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:18: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:6
2017-08-17 11:04:18: App name:dota2_easydrop id:4 online
2017-08-17 11:04:18: App name:dota2_easydrop id:6 online
2017-08-17 11:04:18: App name:dota2_easydrop id:11 disconnected
2017-08-17 11:04:18: App [dota2_easydrop] with id [11] and pid [22003], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:18: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:11
2017-08-17 11:04:18: App name:dota2_easydrop id:11 online
2017-08-17 11:04:19: App name:dota2_easydrop id:10 disconnected
2017-08-17 11:04:19: App [dota2_easydrop] with id [10] and pid [22050], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:19: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:10
2017-08-17 11:04:20: App name:dota2_easydrop id:10 online
2017-08-17 11:04:20: App name:dota2_easydrop id:4 disconnected
2017-08-17 11:04:20: App [dota2_easydrop] with id [4] and pid [22102], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:20: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:4
2017-08-17 11:04:20: App name:dota2_easydrop id:7 disconnected
2017-08-17 11:04:20: App [dota2_easydrop] with id [7] and pid [21859], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:20: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:7
2017-08-17 11:04:20: App name:dota2_easydrop id:4 online
2017-08-17 11:04:20: App name:dota2_easydrop id:11 disconnected
2017-08-17 11:04:20: App name:dota2_easydrop id:7 online
2017-08-17 11:04:20: App name:dota2_easydrop id:8 disconnected
2017-08-17 11:04:20: App [dota2_easydrop] with id [8] and pid [22042], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:20: App [dota2_easydrop] with id [11] and pid [22158], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:20: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:8
2017-08-17 11:04:20: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:11
2017-08-17 11:04:20: App name:dota2_easydrop id:8 online
2017-08-17 11:04:21: App name:dota2_easydrop id:11 online
2017-08-17 11:04:22: App name:dota2_easydrop id:10 disconnected
2017-08-17 11:04:22: App [dota2_easydrop] with id [10] and pid [22192], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:22: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:10
2017-08-17 11:04:22: App name:dota2_easydrop id:10 online
2017-08-17 11:04:22: App name:dota2_easydrop id:7 disconnected
2017-08-17 11:04:22: App [dota2_easydrop] with id [7] and pid [22231], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:22: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:7
2017-08-17 11:04:22: App name:dota2_easydrop id:7 online
2017-08-17 11:04:23: App name:dota2_easydrop id:8 disconnected
2017-08-17 11:04:23: App [dota2_easydrop] with id [8] and pid [22245], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:23: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:8
2017-08-17 11:04:23: App name:dota2_easydrop id:8 online
2017-08-17 11:04:23: App name:dota2_easydrop id:11 disconnected
2017-08-17 11:04:23: App [dota2_easydrop] with id [11] and pid [22246], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:23: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:11
2017-08-17 11:04:23: App name:dota2_easydrop id:4 disconnected
2017-08-17 11:04:23: App [dota2_easydrop] with id [4] and pid [22225], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:23: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:4
2017-08-17 11:04:23: App name:dota2_easydrop id:4 online
2017-08-17 11:04:23: App name:dota2_easydrop id:11 online
2017-08-17 11:04:24: Starting execution sequence in -fork mode- for app name:cdn id:12
2017-08-17 11:04:24: App name:cdn id:12 online
2017-08-17 11:04:24: App name:dota2_easydrop id:10 disconnected
2017-08-17 11:04:24: App [dota2_easydrop] with id [10] and pid [22339], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:24: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:10
2017-08-17 11:04:24: App name:dota2_easydrop id:10 online
2017-08-17 11:04:24: App [cdn] with id [12] and pid [22494], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:24: Starting execution sequence in -fork mode- for app name:cdn id:12
2017-08-17 11:04:24: App name:cdn id:12 online
2017-08-17 11:04:24: App name:dota2_easydrop id:8 disconnected
2017-08-17 11:04:24: App [dota2_easydrop] with id [8] and pid [22400], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:24: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:8
2017-08-17 11:04:25: App name:dota2_easydrop id:8 online
2017-08-17 11:04:25: App [cdn] with id [12] and pid [22531], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:25: Starting execution sequence in -fork mode- for app name:cdn id:12
2017-08-17 11:04:25: App name:cdn id:12 online
2017-08-17 11:04:25: App name:dota2_easydrop id:7 disconnected
2017-08-17 11:04:25: App [dota2_easydrop] with id [7] and pid [22366], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:25: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:7
2017-08-17 11:04:25: App name:dota2_easydrop id:11 disconnected
2017-08-17 11:04:25: App [dota2_easydrop] with id [11] and pid [22422], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:25: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:11
2017-08-17 11:04:25: App name:dota2_easydrop id:4 disconnected
2017-08-17 11:04:25: App [dota2_easydrop] with id [4] and pid [22430], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:25: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:4
2017-08-17 11:04:25: App name:dota2_easydrop id:7 online
2017-08-17 11:04:25: App name:dota2_easydrop id:11 online
2017-08-17 11:04:25: App [cdn] with id [12] and pid [22574], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:25: Starting execution sequence in -fork mode- for app name:cdn id:12
2017-08-17 11:04:25: App name:cdn id:12 online
2017-08-17 11:04:25: App name:dota2_easydrop id:4 online
2017-08-17 11:04:26: App [cdn] with id [12] and pid [22637], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:26: Starting execution sequence in -fork mode- for app name:cdn id:12
2017-08-17 11:04:26: App name:cdn id:12 online
2017-08-17 11:04:26: App name:dota2_easydrop id:10 disconnected
2017-08-17 11:04:26: App [dota2_easydrop] with id [10] and pid [22500], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:26: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:10
2017-08-17 11:04:26: App name:dota2_easydrop id:10 online
2017-08-17 11:04:26: App [cdn] with id [12] and pid [22681], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:26: Starting execution sequence in -fork mode- for app name:cdn id:12
2017-08-17 11:04:26: App name:cdn id:12 online
2017-08-17 11:04:27: App [cdn] with id [12] and pid [22714], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:27: Starting execution sequence in -fork mode- for app name:cdn id:12
2017-08-17 11:04:27: App name:cdn id:12 online
2017-08-17 11:04:27: App name:dota2_easydrop id:7 disconnected
2017-08-17 11:04:27: App [dota2_easydrop] with id [7] and pid [22580], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:27: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:7
2017-08-17 11:04:27: App name:dota2_easydrop id:8 disconnected
2017-08-17 11:04:27: App [dota2_easydrop] with id [8] and pid [22538], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:27: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:8
2017-08-17 11:04:27: App name:dota2_easydrop id:7 online
2017-08-17 11:04:27: App name:dota2_easydrop id:8 online
2017-08-17 11:04:28: App [cdn] with id [12] and pid [22734], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:28: Starting execution sequence in -fork mode- for app name:cdn id:12
2017-08-17 11:04:28: App name:cdn id:12 online
2017-08-17 11:04:28: App name:dota2_easydrop id:11 disconnected
2017-08-17 11:04:28: App [dota2_easydrop] with id [11] and pid [22586], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:28: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:11
2017-08-17 11:04:28: App name:dota2_easydrop id:11 online
2017-08-17 11:04:28: App [cdn] with id [12] and pid [22798], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:28: Starting execution sequence in -fork mode- for app name:cdn id:12
2017-08-17 11:04:28: App name:cdn id:12 online
2017-08-17 11:04:28: App name:dota2_easydrop id:10 disconnected
2017-08-17 11:04:28: App [dota2_easydrop] with id [10] and pid [22687], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:28: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:10
2017-08-17 11:04:28: App name:dota2_easydrop id:10 online
2017-08-17 11:04:29: App [cdn] with id [12] and pid [22837], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:29: Starting execution sequence in -fork mode- for app name:cdn id:12
2017-08-17 11:04:29: App name:cdn id:12 online
2017-08-17 11:04:29: App [cdn] with id [12] and pid [22878], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:29: Starting execution sequence in -fork mode- for app name:cdn id:12
2017-08-17 11:04:29: App name:cdn id:12 online
2017-08-17 11:04:29: App name:dota2_easydrop id:8 disconnected
2017-08-17 11:04:29: App [dota2_easydrop] with id [8] and pid [22746], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:29: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:8
2017-08-17 11:04:29: App name:dota2_easydrop id:7 disconnected
2017-08-17 11:04:29: App [dota2_easydrop] with id [7] and pid [22740], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:29: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:7
2017-08-17 11:04:30: App [cdn] with id [12] and pid [22894], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:30: Starting execution sequence in -fork mode- for app name:cdn id:12
2017-08-17 11:04:30: App name:cdn id:12 online
2017-08-17 11:04:30: App name:dota2_easydrop id:7 online
2017-08-17 11:04:30: App name:dota2_easydrop id:8 online
2017-08-17 11:04:30: App name:dota2_easydrop id:11 disconnected
2017-08-17 11:04:30: App [dota2_easydrop] with id [11] and pid [22804], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:30: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:11
2017-08-17 11:04:30: App [cdn] with id [12] and pid [22916], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:30: Starting execution sequence in -fork mode- for app name:cdn id:12
2017-08-17 11:04:30: App name:cdn id:12 online
2017-08-17 11:04:30: App name:dota2_easydrop id:11 online
2017-08-17 11:04:30: App name:dota2_easydrop id:10 disconnected
2017-08-17 11:04:30: App [dota2_easydrop] with id [10] and pid [22844], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:30: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:10
2017-08-17 11:04:30: App [cdn] with id [12] and pid [22977], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:30: Starting execution sequence in -fork mode- for app name:cdn id:12
2017-08-17 11:04:30: App name:cdn id:12 online
2017-08-17 11:04:31: App name:dota2_easydrop id:10 online
2017-08-17 11:04:31: App [cdn] with id [12] and pid [23022], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:31: Starting execution sequence in -fork mode- for app name:cdn id:12
2017-08-17 11:04:31: App name:cdn id:12 online
2017-08-17 11:04:31: App name:dota2_easydrop id:4 disconnected
2017-08-17 11:04:31: App [dota2_easydrop] with id [4] and pid [22592], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:31: Starting execution sequence in -cluster mode- for app name:dota2_easydrop id:4
2017-08-17 11:04:31: App [cdn] with id [12] and pid [23053], exited with code [0] via signal [SIGINT]
2017-08-17 11:04:31: Starting execution sequence in -fork mode- for app name:cdn id:12
2017-08-17 11:04:31: ===============================================================================
2017-08-17 11:04:31: --- PM2 global error caught ---------------------------------------------------
2017-08-17 11:04:31: Time                 : Thu Aug 17 2017 11:04:31 GMT+0300 (MSK)
2017-08-17 11:04:31: Cannot read property 'on' of undefined
2017-08-17 11:04:31: TypeError: Cannot read property 'on' of undefined
    at /usr/local/lib/node_modules/pm2/lib/God/ForkMode.js:109:18
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:421:16
    at next (/usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:5302:29)
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:906:16
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Utility.js:165:13)
    at emitOne (events.js:77:13)
    at WriteStream.emit (events.js:169:7)
    at WriteStream.<anonymous> (fs.js:1842:10)
    at FSReqWrap.oncomplete (fs.js:82:15)
2017-08-17 11:04:31: ===============================================================================
2017-08-17 11:04:31: [PM2] Resurrecting PM2
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn node EMFILE
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:32)
    at onErrorNT (internal/child_process.js:363:16)
    at nextTickCallbackWith2Args (node.js:511:9)
    at Immediate._tickDomainCallback [as _onImmediate] (node.js:466:17)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
[PM2] Spawning PM2 daemon with pm2_home=/home/maxpain/.pm2
2017-08-17 11:04:32: ===============================================================================
2017-08-17 11:04:32: --- New PM2 Daemon started ----------------------------------------------------
2017-08-17 11:04:32: Time                 : Thu Aug 17 2017 11:04:32 GMT+0300 (MSK)
2017-08-17 11:04:32: PM2 version          : 2.6.1
2017-08-17 11:04:32: Node.js version      : 4.8.4
2017-08-17 11:04:32: Current arch         : x64
2017-08-17 11:04:32: PM2 home             : /home/maxpain/.pm2
2017-08-17 11:04:32: PM2 PID file         : /home/maxpain/.pm2/pm2.pid
2017-08-17 11:04:32: RPC socket file      : /home/maxpain/.pm2/rpc.sock
2017-08-17 11:04:32: BUS socket file      : /home/maxpain/.pm2/pub.sock
2017-08-17 11:04:32: Application log path : /home/maxpain/.pm2/logs
2017-08-17 11:04:32: Process dump file    : /home/maxpain/.pm2/dump.pm2
2017-08-17 11:04:32: Concurrent actions   : 2
2017-08-17 11:04:32: SIGTERM timeout      : 1600
2017-08-17 11:04:32: ===============================================================================
[PM2] PM2 Successfully daemonized
```

**Comment by vmarchaud** [comment]
PM2 is acting as a load balancer but is limited by the hardware you have (it isnt designed to handle these attacks).
If you want to handle DDoS attack i advise you to checkout professional service like CloudFlare that have much more power to handle this problem correctly.

**Comment by Maxpain177** [comment]
@vmarchaud, We already using CloudFlare (and nginx as proxy before pm2).

**Comment by Maxpain177** [comment]
pm2 not starting automatically after this error. pls, fix it.

**Comment by vmarchaud** [comment]
From your PM2 logs, it seems that the daemon it successfully restarted after its crash, do you have a file in `~/.pm2/dump.pm2` ?

**Comment by acuntex** [comment]
I got the same error today at 5:55 in the morning.
Apparently it has nothing to do with DDoS because in my setup there is no web process, just some simple jobs running.
