### ISSUE TITLE
cannot install latest version

### ISSUE THREAD

**Issue by willin** [Unitech/pm2#3120]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?

cannot install latest version

## How could we reproduce this issue?

```bash
> yarn add pm2
------
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
warning There appears to be trouble with your network connection. Retrying...
⡀ jsonify@~0.0.0
```

```
jsonify@~0.0.0
```

package cannot install

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
Arguments:
  /usr/local/bin/node /usr/local/bin/yarn global add pm2

PATH:
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

Yarn version:
  0.27.5

Node version:
  8.4.0

Platform:
  linux x64

npm manifest:
  No manifest

yarn manifest:
  No manifest

Lockfile:
  No lockfile

Trace:
  Error: https://tgz.pm2.io/gkt-1.0.0.tgz: ETIMEDOUT
      at Timeout._onTimeout (/usr/local/lib/node_modules/yarn/node_modules/request/request.js:852:19)
      at ontimeout (timers.js:469:11)
      at tryOnTimeout (timers.js:304:5)
      at Timer.listOnTimeout (timers.js:264:5)
```

**Comment by vmarchaud** [comment]
See https://github.com/Unitech/pm2/issues/3106
