### ISSUE TITLE
ProcessContainerFork not found win10 + ubuntu

### ISSUE THREAD

**Issue by JohnRSim** [Unitech/pm2#3130]
Getting the following error when running
```
pm2 start debug.js
```
A simple webserver (total.js)

```
module.js:471
0|debug    |     throw err;
0|debug    |     ^
0|debug    |
0|debug    | Error: Cannot find module 'C:\work\simoleon\www\ProcessContainerFork.js'
0|debug    |     at Function.Module._resolveFilename (module.js:469:15)
0|debug    |     at Function.Module._load (module.js:417:25)
0|debug    |     at Module.runMain (module.js:604:10)
0|debug    |     at run (bootstrap_node.js:389:7)
0|debug    |     at startup (bootstrap_node.js:149:9)
0|debug    |     at bootstrap_node.js:504:3
```
ProcessContainerFork.js is not generated within that folder - I can replicate the issue on windows 10 locally and on ubuntu server

## How could we reproduce this issue?

I did the following - 
npm install -g pm2
npm install -g total.js
copy basic totaljs site/scripts across
pm2 start debug.js

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
```
```

===============================================================================
--- PM2 REPORT (Sat Sep 02 2017 23:01:50 GMT+0100 (GMT Summer Time)) ----------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.6.1
node version         : 6.11.2
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\johns\AppData\Roaming\nvm\v6.11.2\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 13min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.6.1
node version         : 6.11.2
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Program Files\nodejs\node_modules\pm2\bin\pm2,report
argv0                : C:\Program Files\nodejs\\node.exe
user                 : undefined
C:\Users\johns\AppData\Roaming\nvm\v6.11.2\node_modules\pm2\lib\API\Extra.js:70
        fmt.field('uid', process.geteuid());
                                 ^

TypeError: process.geteuid is not a function
    at C:\Users\johns\AppData\Roaming\nvm\v6.11.2\node_modules\pm2\lib\API\Extra.js:70:34
    at C:\Users\johns\AppData\Roaming\nvm\v6.11.2\node_modules\pm2\node_modules\pm2-axon-rpc\lib\client.js:45:10
    at Parser.<anonymous> (C:\Users\johns\AppData\Roaming\nvm\v6.11.2\node_modules\pm2\node_modules\pm2-axon\lib\sockets\req.js:67:8)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._write (C:\Users\johns\AppData\Roaming\nvm\v6.11.2\node_modules\pm2\node_modules\amp\lib\stream.js:91:16)
    at doWrite (_stream_writable.js:331:12)
    at writeOrBuffer (_stream_writable.js:317:5)
    at Parser.Writable.write (_stream_writable.js:243:11)
    at Socket.ondata (_stream_readable.js:555:20)
````

**Comment by vmarchaud** [comment]
Can you give us a simple script to reproduce the problem ? Also are you using the ubuntu subsystem on Windows ?

**Comment by JohnRSim** [comment]
No ubuntu is running on google.
Windows 10 is local

[www.zip](https://github.com/Unitech/pm2/files/1305943/www.zip)
This should work - run debug.js
