### ISSUE TITLE
There's an error in pm2.log

### ISSUE THREAD

**Issue by RaniSharim** [Unitech/pm2#3134]
2017-09-04 01:59:01: [PM2] Resurrecting PM2
/xxx/.nvm/versions/node/v8.4.0/lib/node_modules/pm2/node_modules/async/dist/async.js:903
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /xxx/.nvm/versions/node/v8.4.0/lib/node_modules/pm2/node_modules/async/dist/async.js:903:32
    at WriteStream.<anonymous> (/xxx/.nvm/versions/node/v8.4.0/lib/node_modules/pm2/lib/Utility.js:162:13)
    at emitOne (events.js:115:13)
    at WriteStream.emit (events.js:210:7)
    at onwriteError (_stream_writable.js:406:12)
    at onwrite (_stream_writable.js:428:5)
    at fs.js:2130:14
    at FSReqWrap.wrapper [as oncomplete] (fs.js:691:5)

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/commit/f5ee34c308418302569de10743486b50f980eb51

**Comment by Unitech** [comment]
Fixed on recently published pm2 (2.7.0):

```bash
$ npm install pm2@latest -g
$ pm2 update
```

Let me know if there is any issue,
