### ISSUE TITLE
pm2 v2.6.1 breaks when v2.4 is fine

### ISSUE THREAD

**Issue by terencechow** [Unitech/pm2#3151]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?
I removed my yarn.lock file and updated pm2 from 2.4 to 2.6.1. I use pm2 only locally (no global). However once updated my server didn't start. I have no idea why that would be the case. I've included logs from pm2 v2.4 and v2.6.1

As you can see in the logs for pm2 v2.4, at the very end, the app logs out `Server is now running at http://localhost:5000.` 

This does not happen in pm2.6. What's going on?

## Supporting information

Logs from pm2 v2.4
```
> DEBUG=* node_modules/pm2/bin/pm2 start pm2.json --only api-gateway-development --no-daemon

  pm2:paths pm2 home resolved to /Users/terence/.pm2 /Users/terence +0ms
  pm2:conf Using 2 parallelism (CONCURRENT_ACTIONS) +6ms
  pm2:client Using RPC file /Users/terence/.pm2/rpc.sock +112ms
  pm2:client Using PUB file /Users/terence/.pm2/pub.sock +0ms
  pm2:interface:daemon Getting interaction info +1ms
  pm2:interface:daemon [PING INTERACTOR] Trying to connect to Interactor daemon +0ms
  axon:sock connect attempt null:/Users/terence/.pm2/interactor.sock +0ms
pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
  pm2:client Using RPC file /Users/terence/.pm2/rpc.sock +5ms
  pm2:client Using PUB file /Users/terence/.pm2/pub.sock +0ms
  pm2:interface:daemon Getting interaction info +0ms
  pm2:interface:daemon [PING INTERACTOR] Trying to connect to Interactor daemon +1ms
  axon:sock connect attempt null:/Users/terence/.pm2/interactor.sock +4ms
  pm2:client [PING PM2] Trying to connect to server +0ms
  axon:sock connect attempt null:/Users/terence/.pm2/rpc.sock +0ms
  axon:sock error ENOENT +4ms
  axon:sock ignored ENOENT +0ms
  axon:sock error ENOENT +0ms
  axon:sock ignored ENOENT +0ms
  axon:sock error ECONNREFUSED +1ms
  axon:sock ignored ECONNREFUSED +0ms
  axon:sock attempting reconnect +102ms
  axon:sock closing +1ms
  axon:sock closing 0 connections +0ms
  pm2:client Daemon not launched +108ms
  axon:sock connect attempt null:/Users/terence/.pm2/rpc.sock +0ms
  axon:sock attempting reconnect +0ms
  axon:sock closing +0ms
  axon:sock closing 0 connections +0ms
  pm2:interface:daemon Interactor Daemon not launched +0ms
  axon:sock connect attempt null:/Users/terence/.pm2/interactor.sock +1ms
  axon:sock attempting reconnect +0ms
  axon:sock closing +0ms
  axon:sock closing 0 connections +0ms
  pm2:interface:daemon Interactor Daemon not launched +1ms
  axon:sock connect attempt null:/Users/terence/.pm2/interactor.sock +0ms
2017-09-12 12:17:46: Launching in no daemon mode
  axon:sock bind null:/Users/terence/.pm2/pub.sock +78ms
  axon:sock bind null:/Users/terence/.pm2/rpc.sock +1ms
  axon:sock Got error while trying to bind +2ms Error: listen EADDRINUSE /Users/terence/.pm2/pub.sock
    at Object.exports._errnoException (util.js:1023:11)
    at exports._exceptionWithHostPort (util.js:1046:20)
    at Server._listen2 (net.js:1248:19)
    at listen (net.js:1297:10)
    at Server.listen (net.js:1381:7)
    at PubSocket.Socket.bind (/Users/terence/workspace/api-gateway/node_modules/pm2-axon/lib/sockets/sock.js:412:15)
    at module.exports.Daemon.innerStart (/Users/terence/workspace/api-gateway/node_modules/pm2/lib/Daemon.js:99:30)
    at /Users/terence/workspace/api-gateway/node_modules/pm2/lib/Client.js:76:14
    at /Users/terence/workspace/api-gateway/node_modules/pm2/lib/Client.js:285:14
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
  axon:sock Got error while trying to bind +0ms Error: listen EADDRINUSE /Users/terence/.pm2/rpc.sock
    at Object.exports._errnoException (util.js:1023:11)
    at exports._exceptionWithHostPort (util.js:1046:20)
    at Server._listen2 (net.js:1248:19)
    at listen (net.js:1297:10)
    at Server.listen (net.js:1381:7)
    at RepSocket.Socket.bind (/Users/terence/workspace/api-gateway/node_modules/pm2-axon/lib/sockets/sock.js:412:15)
    at module.exports.Daemon.innerStart (/Users/terence/workspace/api-gateway/node_modules/pm2/lib/Daemon.js:113:30)
    at /Users/terence/workspace/api-gateway/node_modules/pm2/lib/Client.js:76:14
    at /Users/terence/workspace/api-gateway/node_modules/pm2/lib/Client.js:285:14
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
  axon:sock error ECONNREFUSED +1ms
  axon:sock ignored ECONNREFUSED +0ms
  axon:sock error ENOENT +0ms
  axon:sock ignored ENOENT +0ms
  axon:sock error ENOENT +0ms
  axon:sock ignored ENOENT +0ms
  axon:sock Got sub-error +1ms { Error: connect ECONNREFUSED /Users/terence/.pm2/pub.sock
    at Object.exports._errnoException (util.js:1023:11)
    at exports._exceptionWithHostPort (util.js:1046:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/Users/terence/.pm2/pub.sock' }
  axon:sock Got sub-error +2ms { Error: connect ECONNREFUSED /Users/terence/.pm2/rpc.sock
    at Object.exports._errnoException (util.js:1023:11)
    at exports._exceptionWithHostPort (util.js:1046:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/Users/terence/.pm2/rpc.sock' }
  pm2:interface:daemon Interaction file does not exists +86ms
  pm2:client Launching RPC client on socket file /Users/terence/.pm2/rpc.sock +0ms
  axon:sock connect attempt null:/Users/terence/.pm2/rpc.sock +1ms
  axon:sock accept /Users/terence/.pm2/rpc.sock +1ms
  axon:sock add socket 0 +0ms
  axon:sock connect +1ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  pm2:client RPC Connected to Daemon +2ms
  pm2:client Calling daemon method pm2:getVersion on rpc socket:/Users/terence/.pm2/rpc.sock +10ms
  pm2:cli Resolved filepath /Users/terence/workspace/api-gateway/pm2.json +3ms
  pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/Users/terence/.pm2/rpc.sock +10ms
2017-09-12 12:17:46: [PM2][WARN] Applications api-gateway-development not running, starting...
  pm2:client Calling daemon method pm2:prepare on rpc socket:/Users/terence/.pm2/rpc.sock +8ms
  pm2:watch Initial watch  [ 'server', 'tests', 'config' ] +10ms
  pm2:watch Watching server,tests,config +1ms
  pm2:watch Watch opts { ignored: /[\/\\]\.|node_modules/,
  persistent: true,
  ignoreInitial: true,
  cwd: '/Users/terence/workspace/api-gateway',
  usePolling: true } +0ms
2017-09-12 12:17:46: [Watch] Start watching 0
2017-09-12 12:17:46: Starting execution sequence in -fork mode- for app name:api-gateway-development id:0
  pm2:fork_mode stds: {"out":"/dev/null","err":"/dev/null"} +3ms
2017-09-12 12:17:46: App name:api-gateway-development id:0 online
  pm2:god Error vizion::analyze() for given folder: /Users/terence/workspace/api-gateway/server/ +22ms
2017-09-12 12:17:46: [PM2] App [api-gateway-development] launched (1 instances)
  pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/Users/terence/.pm2/rpc.sock +7ms
2017-09-12 12:17:46: ┌─────────────────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
│ App name                │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ watching │
├─────────────────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ api-gateway-development │ 0  │ fork │ 92517 │ online │ 0       │ 0s     │ 0%  │ 14.0 MB   │ enabled  │
└─────────────────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
2017-09-12 12:17:46:  Use `pm2 show <id|name>` to get more details about an app
2017-09-12 12:17:46: [--no-daemon] Continue to stream logs
2017-09-12 12:17:46: [--no-daemon] Exit on target PM2 exit pid=92516
  pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/Users/terence/.pm2/rpc.sock +26ms
2017-09-12 12:17:46: [STREAMING] Now streaming realtime logs for [all] processes
  axon:sock connect attempt null:/Users/terence/.pm2/pub.sock +125ms
  axon:sock accept /Users/terence/.pm2/pub.sock +0ms
  axon:sock add socket 0 +0ms
  axon:sock connect +1ms
  axon:sock add socket 0 +0ms
  axon:sub subscribe to "log:*" +0ms
12:17:47 0|api-gate | Tue, 12 Sep 2017 10:17:47 GMT app:config Found overrides, applying to default configuration
12:17:47 0|api-gate | Tue, 12 Sep 2017 10:17:47 GMT app:config Config built for env local
12:17:47 0|api-gate | Sep 12 12:17:47 api-gateway[92517] INFO:  Server is now running at http://localhost:5000.
```

Logs from pm2 v2.6.1
```
> DEBUG=* node_modules/pm2/bin/pm2 start pm2.json --only api-gateway-development --no-daemon

  pm2:paths pm2 home resolved to /Users/terence/.pm2 /Users/terence +0ms
  pm2:conf Using 2 parallelism (CONCURRENT_ACTIONS) +6ms
  pm2:client Using RPC file /Users/terence/.pm2/rpc.sock +171ms
  pm2:client Using PUB file /Users/terence/.pm2/pub.sock +0ms
  pm2:interface:daemon Getting interaction info +0ms
  pm2:interface:daemon [PING INTERACTOR] Trying to connect to Interactor daemon +1ms
  axon:sock connect attempt null:/Users/terence/.pm2/interactor.sock +0ms
pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
  pm2:client Using RPC file /Users/terence/.pm2/rpc.sock +4ms
  pm2:client Using PUB file /Users/terence/.pm2/pub.sock +0ms
  pm2:interface:daemon Getting interaction info +0ms
  pm2:interface:daemon [PING INTERACTOR] Trying to connect to Interactor daemon +0ms
  axon:sock connect attempt null:/Users/terence/.pm2/interactor.sock +4ms
  pm2:client [PING PM2] Trying to connect to server +1ms
  axon:sock connect attempt null:/Users/terence/.pm2/rpc.sock +0ms
  axon:sock error ENOENT +4ms
  axon:sock ignored ENOENT +0ms
  axon:sock error ENOENT +1ms
  axon:sock ignored ENOENT +0ms
  axon:sock error ECONNREFUSED +0ms
  axon:sock ignored ECONNREFUSED +0ms
  axon:sock attempting reconnect +106ms
  axon:sock closing +0ms
  axon:sock closing 0 connections +0ms
  pm2:client Daemon not launched +111ms
  axon:sock connect attempt null:/Users/terence/.pm2/rpc.sock +1ms
  axon:sock attempting reconnect +0ms
  axon:sock closing +0ms
  axon:sock closing 0 connections +0ms
  pm2:interface:daemon Interactor Daemon not launched +1ms
  axon:sock connect attempt null:/Users/terence/.pm2/interactor.sock +0ms
  axon:sock attempting reconnect +0ms
  axon:sock closing +0ms
  axon:sock closing 0 connections +0ms
  pm2:interface:daemon Interactor Daemon not launched +0ms
  axon:sock connect attempt null:/Users/terence/.pm2/interactor.sock +0ms
2017-09-12 12:19:59: Launching in no daemon mode
  axon:sock bind null:/Users/terence/.pm2/pub.sock +123ms
  axon:sock bind null:/Users/terence/.pm2/rpc.sock +1ms
  axon:sock Got error while trying to bind +2ms Error: listen EADDRINUSE /Users/terence/.pm2/pub.sock
    at Object.exports._errnoException (util.js:1023:11)
    at exports._exceptionWithHostPort (util.js:1046:20)
    at Server._listen2 (net.js:1248:19)
    at listen (net.js:1297:10)
    at Server.listen (net.js:1381:7)
    at PubSocket.Socket.bind (/Users/terence/workspace/api-gateway/node_modules/pm2-axon/lib/sockets/sock.js:412:15)
    at module.exports.Daemon.innerStart (/Users/terence/workspace/api-gateway/node_modules/pm2/lib/Daemon.js:99:30)
    at /Users/terence/workspace/api-gateway/node_modules/pm2/lib/Client.js:77:14
    at /Users/terence/workspace/api-gateway/node_modules/pm2/lib/Client.js:293:14
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
  axon:sock Got error while trying to bind +0ms Error: listen EADDRINUSE /Users/terence/.pm2/rpc.sock
    at Object.exports._errnoException (util.js:1023:11)
    at exports._exceptionWithHostPort (util.js:1046:20)
    at Server._listen2 (net.js:1248:19)
    at listen (net.js:1297:10)
    at Server.listen (net.js:1381:7)
    at RepSocket.Socket.bind (/Users/terence/workspace/api-gateway/node_modules/pm2-axon/lib/sockets/sock.js:412:15)
    at module.exports.Daemon.innerStart (/Users/terence/workspace/api-gateway/node_modules/pm2/lib/Daemon.js:113:30)
    at /Users/terence/workspace/api-gateway/node_modules/pm2/lib/Client.js:77:14
    at /Users/terence/workspace/api-gateway/node_modules/pm2/lib/Client.js:293:14
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
  axon:sock error ECONNREFUSED +0ms
  axon:sock ignored ECONNREFUSED +1ms
  axon:sock error ENOENT +0ms
  axon:sock ignored ENOENT +0ms
  axon:sock error ENOENT +0ms
  axon:sock ignored ENOENT +1ms
  axon:sock Got sub-error +0ms { Error: connect ECONNREFUSED /Users/terence/.pm2/pub.sock
    at Object.exports._errnoException (util.js:1023:11)
    at exports._exceptionWithHostPort (util.js:1046:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/Users/terence/.pm2/pub.sock' }
  axon:sock Got sub-error +2ms { Error: connect ECONNREFUSED /Users/terence/.pm2/rpc.sock
    at Object.exports._errnoException (util.js:1023:11)
    at exports._exceptionWithHostPort (util.js:1046:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/Users/terence/.pm2/rpc.sock' }
  pm2:interface:daemon Interaction file does not exists +131ms
  pm2:client Launching RPC client on socket file /Users/terence/.pm2/rpc.sock +0ms
  axon:sock connect attempt null:/Users/terence/.pm2/rpc.sock +1ms
  axon:sock accept /Users/terence/.pm2/rpc.sock +1ms
  axon:sock add socket 0 +0ms
  axon:sock connect +1ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  pm2:client RPC Connected to Daemon +2ms
  pm2:client Calling daemon method pm2:getVersion on rpc socket:/Users/terence/.pm2/rpc.sock +10ms
  pm2:cli Resolved filepath /Users/terence/workspace/api-gateway/pm2.json +3ms
  pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/Users/terence/.pm2/rpc.sock +12ms
2017-09-12 12:19:59: [PM2][WARN] Applications api-gateway-development not running, starting...
  pm2:client Calling daemon method pm2:prepare on rpc socket:/Users/terence/.pm2/rpc.sock +7ms
  pm2:watch Initial watch  [ 'server', 'tests', 'config' ] +9ms
  pm2:watch Watching server,tests,config +1ms
  pm2:watch Watch opts { ignored: /[\/\\]\.|node_modules/,
  persistent: true,
  ignoreInitial: true,
  cwd: '/Users/terence/workspace/api-gateway',
  usePolling: true } +0ms
2017-09-12 12:19:59: [Watch] Start watching api-gateway-development
2017-09-12 12:19:59: Starting execution sequence in -fork mode- for app name:api-gateway-development id:0
  pm2:fork_mode stds: {"out":"/dev/null","err":"/dev/null"} +3ms
2017-09-12 12:19:59: App name:api-gateway-development id:0 online
  pm2:god Error vizion::analyze() for given folder: /Users/terence/workspace/api-gateway/server/ +30ms
2017-09-12 12:19:59: [PM2] App [api-gateway-development] launched (1 instances)
  pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/Users/terence/.pm2/rpc.sock +7ms
2017-09-12 12:19:59: ┌─────────────────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬─────────┬──────────┐
│ App name                │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user    │ watching │
├─────────────────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼─────────┼──────────┤
│ api-gateway-development │ 0  │ fork │ 92827 │ online │ 0       │ 0s     │ 8%  │ 16.7 MB   │ terence │ enabled  │
└─────────────────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴─────────┴──────────┘
2017-09-12 12:19:59:  Use `pm2 show <id|name>` to get more details about an app
2017-09-12 12:19:59: [--no-daemon] Continue to stream logs
2017-09-12 12:19:59: [--no-daemon] Exit on target PM2 exit pid=92826
  pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/Users/terence/.pm2/rpc.sock +25ms
  axon:sock connect attempt null:/Users/terence/.pm2/pub.sock +126ms
  axon:sock accept /Users/terence/.pm2/pub.sock +0ms
  axon:sock add socket 0 +0ms
  axon:sock connect +1ms
  axon:sock add socket 0 +0ms
  axon:sub subscribe to "log:*" +1ms
```
Please run the following command (available on PM2 >= 2.6)

Command run on pm2 v >= 2.6
```
[PM2] Spawning PM2 daemon with pm2_home=/Users/terence/.pm2
[PM2] PM2 Successfully daemonized
===============================================================================
--- PM2 REPORT (Tue Sep 12 2017 12:21:01 GMT+0200 (CEST)) ---------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.6.1
node version         : 7.5.0
node path            : /Users/terence/workspace/api-gateway/./node_modules/pm2/bin/pm2
argv                 : /Users/terence/.nvm/versions/node/v7.5.0/bin/node,/Users/terence/workspace/api-gateway/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : terence
uid                  : 501
gid                  : 20
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.6.1
node version         : 7.5.0
node path            : /Users/terence/workspace/api-gateway/./node_modules/pm2/bin/pm2
argv                 : /Users/terence/.nvm/versions/node/v7.5.0/bin/node,/Users/terence/workspace/api-gateway/node_modules/pm2/bin/pm2,report
argv0                : node
user                 : terence
uid                  : 501
gid                  : 20
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : darwin
type                 : Darwin
cpus                 : Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
cpus nb              : 8
freemem              : 256192512
totalmem             : 17179869184
home                 : /Users/terence
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
```

**Comment by vmarchaud** [comment]
You might have two daemon running on your system that fight each other over the socket used to expose the RPC server, run `pkill PM2` and then retry ?

**Comment by brendanmckenzie** [comment]
When node was installed by snaps on Ubuntu I experienced this issue, installing node with apt resolved it.

**Comment by mur-me** [comment]
@brendanmckenzie I had the same problem, thanks for the hint
