### ISSUE TITLE
PM2 not supporting -i <number>

### ISSUE THREAD

**Issue by tirthaguha** [Unitech/pm2#3171]
## What's going wrong?
PM2 not supporting -i <number> on WIN7.

## How could we reproduce this issue?

C:\DIR\>pm2 -v
2.7.1

C:\DIR\>node -v
v5.9.1

C:\DIR\>npm -v
3.7.3

C:\DIR\>pm2 start server.js -i 2
[PM2] Applying action restartProcessId on app [server](ids: 0)
[PM2] [server](0) V
[PM2] Process successfully started
┌──────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬──────────┬─────────┬──────────┐
│ App name │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem      │ user    │ watching │
├──────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼──────────┼─────────┼──────────┤
│ server   │ 0  │ fork │ 10640 │ online │ 1       │ 0s     │ 0%  │ 6.4 MB   │ ssssss  │ disabled │
└──────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴──────────┴─────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app

 
### RESULT: 
 
Creates 4 instances, since i have a quadcore system. 

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
C:\DIR\>pm2 report
===============================================================================
--- PM2 REPORT (Mon Sep 25 2017 14:01:17 GMT+0530 (India Standard Time)) ------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.7.1
node version         : 5.9.1
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\ssssss\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : undefined
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 224min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.7.1
node version         : 5.9.1
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\ssssss\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : undefined
user                 : undefined
C:\Users\ssssss\AppData\Roaming\npm\node_modules\pm2\lib\API\Extra.js:70
        fmt.field('uid', process.geteuid());
                                 ^

TypeError: process.geteuid is not a function
    at C:\Users\ssssss\AppData\Roaming\npm\node_modules\pm2\lib\API\Extra.js:70:34
    at C:\Users\ssssss\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon-rpc\lib\client.js:45:10
    at Parser.<anonymous> (C:\Users\ssssss\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon\lib\sockets\req.js:67:8)
    at emitOne (events.js:90:13)
    at Parser.emit (events.js:182:7)
    at Parser._write (C:\Users\ssssss\AppData\Roaming\npm\node_modules\pm2\node_modules\amp\lib\stream.js:91:16)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at Parser.Writable.write (_stream_writable.js:215:11)
    at Socket.ondata (_stream_readable.js:536:20)

C:\DIR\>

```

**Comment by vmarchaud** [comment]
Try with a LTS nodejs version, node 5 isn't maintained ?
