### ISSUE TITLE
PM2 start fails with look_for_profiler with nvm using node 0.10.44

### ISSUE THREAD

**Issue by lowi** [Unitech/pm2#3173]
## What's going wrong?
I have this stack trace when trying to start my nodejs app:
```
0|test     | TypeError: Cannot read property 'R_OK' of undefined
0|test     |     at look_for_profiler (/home/apps/.nvm/v0.10.44/lib/node_modules/pm2/node_modules/pmx/lib/probes/profiling.js:108:53)
0|test     |     at Object.Profiling.detectV8Profiler (/home/apps/.nvm/v0.10.44/lib/node_modules/pm2/node_modules/pmx/lib/probes/profiling.js:119:5)
0|test     |     at Object.Profiling.v8Profiling (/home/apps/.nvm/v0.10.44/lib/node_modules/pm2/node_modules/pmx/lib/probes/profiling.js:123:13)
0|test     |     at Object.PMX.init (/home/apps/.nvm/v0.10.44/lib/node_modules/pm2/node_modules/pmx/lib/pmx.js:78:15)
0|test     |     at Object.<anonymous> (/home/apps/.nvm/v0.10.44/lib/node_modules/pm2/lib/ProcessContainerFork.js:8:18)
0|test     |     at Module._compile (module.js:456:26)
0|test     |     at Object.Module._extensions..js (module.js:474:10)
0|test     |     at Module.load (module.js:356:32)
0|test     |     at Function.Module._load (module.js:312:12)
0|test     |     at Function.Module.runMain (module.js:497:10)
```
The app works when I run it directly with node.

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
===============================================================================
--- PM2 REPORT (Mon Sep 25 2017 15:38:08 GMT+0200 (CEST)) ---------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.7.1
node version         : 0.10.44
node path            : /home/apps/.nvm/v0.10.44/bin/pm2
argv                 : node,/home/apps/.nvm/v0.10.44/lib/node_modules/pm2/lib/Daemon.js
argv0                : undefined
user                 : apps
uid                  : N/A
gid                  : N/A
uptime               : 4014min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.7.1
node version         : 0.10.44
node path            : /home/apps/.nvm/v0.10.44/bin/pm2
argv                 : node,/home/apps/.nvm/v0.10.44/bin/pm2,report
argv0                : undefined
user                 : apps

/home/apps/.nvm/v0.10.44/lib/node_modules/pm2/lib/API/Extra.js:70
        fmt.field('uid', process.geteuid());
                                 ^
TypeError: Object #<process> has no method 'geteuid'
    at /home/apps/.nvm/v0.10.44/lib/node_modules/pm2/lib/API/Extra.js:70:34
    at /home/apps/.nvm/v0.10.44/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/home/apps/.nvm/v0.10.44/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (events.js:95:17)
    at Parser._write (/home/apps/.nvm/v0.10.44/lib/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Parser.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
```

**Comment by Unitech** [comment]
pmx has been fixed for 0.10 but we will not pursue more fix to make pm2 compatible with node 0.10
https://github.com/keymetrics/pmx/issues/99
