### ISSUE TITLE
Error caught by domain

### ISSUE THREAD

**Issue by extensionsapp** [Unitech/pm2#3183]
## What's going wrong?
All applications stopped.

## Supporting information
```
2017-10-01 15:03:49: [PM2][WORKER] Process 1 restarted because it exceeds --max-memory-restart value (current_memory=84131840 max_memory_limit=79691776 [octets])
2017-10-01 15:03:49: Process 1 in a stopped status, starting it
2017-10-01 15:03:49: Stopping app:demo.org id:1
2017-10-01 15:03:49: [PM2][WORKER] Error caught by domain:
    at _errnoException (util.js:1019:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:494:9)
    at /usr/lib/node_modules/pm2/lib/TreeKill.js:33:14
    at buildProcessTree (/usr/lib/node_modules/pm2/lib/TreeKill.js:79:12)
    at module.exports (/usr/lib/node_modules/pm2/lib/TreeKill.js:32:5)
    at Object.God.killProcess (/usr/lib/node_modules/pm2/lib/God/Methods.js:223:7)
    at Object.God.stopProcessId (/usr/lib/node_modules/pm2/lib/God/ActionMethods.js:287:9)
    at Object.God.restartProcessId (/usr/lib/node_modules/pm2/lib/God/ActionMethods.js:384:11)
    at Object.God.softReloadProcessId (/usr/lib/node_modules/pm2/lib/God/Reload.js:201:18)
2017-10-01 15:04:01: ===============================================================================
2017-10-01 15:04:01: --- New PM2 Daemon started ----------------------------------------------------
2017-10-01 15:04:01: Time                 : Sun Oct 01 2017 15:04:01 GMT+0300 (MSK)
2017-10-01 15:04:01: PM2 version          : 2.7.1
2017-10-01 15:04:01: Node.js version      : 8.6.0
2017-10-01 15:04:01: Current arch         : x64
2017-10-01 15:04:01: PM2 home             : /root/.pm2
2017-10-01 15:04:01: PM2 PID file         : /root/.pm2/pm2.pid
2017-10-01 15:04:01: RPC socket file      : /root/.pm2/rpc.sock
2017-10-01 15:04:01: BUS socket file      : /root/.pm2/pub.sock
2017-10-01 15:04:01: Application log path : /root/.pm2/logs
2017-10-01 15:04:01: Process dump file    : /root/.pm2/dump.pm2
2017-10-01 15:04:01: Concurrent actions   : 2
2017-10-01 15:04:01: SIGTERM timeout      : 1600
2017-10-01 15:04:01: ===============================================================================
2017-10-01 15:04:02: Starting execution sequence in -fork mode- for app name:pm2-logrotate id:0
2017-10-01 15:04:02: App name:pm2-logrotate id:0 online
2017-10-01 15:04:02: 0
2017-10-01 15:04:02: Stopping app:pm2-logrotate id:0
2017-10-01 15:04:02: App [pm2-logrotate] with id [0] and pid [11974], exited with code [0] via signal [SIGINT]
2017-10-01 15:04:02: [HandleExit] PM2 is being killed, stopping restart procedure...
2017-10-01 15:04:02: pid=11974 msg=process killed
2017-10-01 15:04:02: ===============================================================================
2017-10-01 15:04:02: --- Stopping PM2 --------------------------------------------------------------
2017-10-01 15:04:02: Time                 : Sun Oct 01 2017 15:04:02 GMT+0300 (MSK)
2017-10-01 15:04:02: ===============================================================================
2017-10-01 15:04:02: RPC closed
2017-10-01 15:04:02: PUB closed
2017-10-01 15:04:02: PM2 successfully stopped
2017-10-01 15:27:41: ===============================================================================
2017-10-01 15:27:41: --- New PM2 Daemon started ----------------------------------------------------
2017-10-01 15:27:41: Time                 : Sun Oct 01 2017 15:27:41 GMT+0300 (MSK)
2017-10-01 15:27:41: PM2 version          : 2.7.1
2017-10-01 15:27:41: Node.js version      : 8.6.0
2017-10-01 15:27:41: Current arch         : x64
2017-10-01 15:27:41: PM2 home             : /root/.pm2
2017-10-01 15:27:41: PM2 PID file         : /root/.pm2/pm2.pid
2017-10-01 15:27:41: RPC socket file      : /root/.pm2/rpc.sock
2017-10-01 15:27:41: BUS socket file      : /root/.pm2/pub.sock
2017-10-01 15:27:41: Application log path : /root/.pm2/logs
2017-10-01 15:27:41: Process dump file    : /root/.pm2/dump.pm2
2017-10-01 15:27:41: Concurrent actions   : 2
2017-10-01 15:27:41: SIGTERM timeout      : 1600
2017-10-01 15:27:41: ===============================================================================
2017-10-01 15:27:41: Starting execution sequence in -fork mode- for app name:pm2-logrotate id:0
2017-10-01 15:27:41: App name:pm2-logrotate id:0 online
```

**Comment by vmarchaud** [comment]
Seems like you can't spawn `ps`, is it available in the system path ?
