### ISSUE TITLE
Unhandled error when initializing client for unknown user

### ISSUE THREAD

**Issue by yasuharu519** [Unitech/pm2#3184]
## What's going wrong?

This was discovered while trying to run applications with ldap authenticated environment.

If the pm2 tried to run with ldap authenticated user, pm2 crashed with unhandled error. The error related to (https://github.com/Unleash/unleash-client-node/issues/35), that crash occurred if the user doesn't have entry in /etc/passwd file.  Here is a stack trace from our app:

```
[~]$ pm2 status
[PM2] Spawning PM2 daemon with pm2_home=/home/deploy/.pm2
[PM2] PM2 Successfully daemonized
/usr/local/lib/node_modules/pm2/lib/API/CliUx.js:224
    current_user = os.userInfo().username;
                      ^

Error: ENOENT: no such file or directory, uv_os_get_passwd
    at Object.UX.dispAsTable (/usr/local/lib/node_modules/pm2/lib/API/CliUx.js:224:23)
    at /usr/local/lib/node_modules/pm2/lib/API.js:1536:10
    at /usr/local/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._write (/usr/local/lib/node_modules/pm2/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at Parser.Writable.write (_stream_writable.js:247:11)
```

## How could we reproduce this issue?

- Login with ldap authenticated user (no entry in /etc/passwd)
- Run `pm2 status`

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
```

```
[~]$ pm2 report
===============================================================================
--- PM2 REPORT (Mon Oct 02 2017 14:45:48 GMT+0900 (JST)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.7.1
node version         : 7.2.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : deploy
uid                  : 5000
gid                  : 5000
uptime               : 2min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.7.1
node version         : 7.2.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : deploy
uid                  : 5000
gid                  : 5000
===============================================================================
--- System info --------------------------------------------
arch                 : ia32
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
cpus nb              : 4
freemem              : 2854100992
totalmem             : 16388935680
home                 : /home/deploy
===============================================================================
--- PM2 list -----------------------------------------------
/usr/local/lib/node_modules/pm2/lib/API/CliUx.js:224
    current_user = os.userInfo().username;
                      ^

Error: ENOENT: no such file or directory, uv_os_get_passwd
    at Object.UX.dispAsTable (/usr/local/lib/node_modules/pm2/lib/API/CliUx.js:224:23)
    at /usr/local/lib/node_modules/pm2/lib/API/Extra.js:92:14
    at /usr/local/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._write (/usr/local/lib/node_modules/pm2/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at Parser.Writable.write (_stream_writable.js:247:11)
```

**Comment by yasuharu519** [comment]
Maybe fix with this kind of diff?

```diff
diff --git a/lib/API/CliUx.js b/lib/API/CliUx.js
index f9a0a89..3881200 100644
--- a/lib/API/CliUx.js
+++ b/lib/API/CliUx.js
@@ -221,7 +221,12 @@ UX.dispAsTable = function(list, interact_infos) {
   var current_user = '';

   if (os.userInfo)
-    current_user = os.userInfo().username;
+    try {
+      current_user = os.userInfo().username;
+    } catch (e) {
+      // For the case of unhandled error for uv_os_get_passwd
+      current_user = '';
+    }
   else
     current_user = process.env.USER || process.env.LNAME || process.env.USERNAME || process.env.SUDO_USER || process.env.C9_USER || process.env.LOGNAME;
     ;
```

**Comment by vmarchaud** [comment]
Could you make a PR so we can merge it asap ? thanks

**Comment by yasuharu519** [comment]
@vmarchaud 

Hi, thanks for checking. Actually, I made PR (https://github.com/Unitech/pm2/pull/3185), but I could not assign License Agreement because of my organization. Sorry.

Could you make PR that includes diff above?

**Comment by vmarchaud** [comment]
@yasuharu519 No problem, i will push it myself.
