### ISSUE TITLE
pm2 global error caught

### ISSUE THREAD

**Issue by kolykhalov** [Unitech/pm2#3188]
## What's going wrong?

pm2 constantly kills workers. Reboot helps for couple of hours sometimes, usually 20-30 minutes. Log shows some strange error that it can not find itself in a very strange place /bin/pm2 where it shouldn't be actually as it stays in node-modules or in global folder.

## How could we reproduce this issue?
no idea

## Supporting information
OS: Windows Server 2012

Please run the following command (available on PM2 >= 2.6)

```
--- PM2 global error caught ---------------------------------------------------
2017-10-02 17:18:34: Time                 : Mon Oct 02 2017 17:18:34 GMT+0400 (Russian Standard Time)
2017-10-02 17:18:34: This socket is closed
2017-10-02 17:18:34: Error: This socket is closed
    at Socket._writeGeneric (net.js:719:18)
    at Socket._write (net.js:779:8)
    at doWrite (_stream_writable.js:387:12)
    at clearBuffer (_stream_writable.js:513:7)
    at onwrite (_stream_writable.js:439:7)
    at WriteWrap.afterWrite [as oncomplete] (net.js:872:12)
2017-10-02 17:18:34: ===============================================================================
2017-10-02 17:18:34: [PM2] Resurrecting PM2
module.js:473
      throw err;
      ^

Error: Cannot find module 'C:\inetpub\project\bin\pm2'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
2017-10-02 17:18:34: PM2 successfully forked
2017-10-02 17:18:56: 
```

any help very appreciated. Thanks :)

**Comment by vmarchaud** [comment]
Please give us the versions of PM2/Node you are using

**Comment by kolykhalov** [comment]
node 8.6.0

pm2 2.7.1

**Comment by Unitech** [comment]
fixed while ago
