### ISSUE TITLE
`sudo pm2 startup -u ubuntu` fails for lack of permissions

### ISSUE THREAD

**Issue by ubershmekel** [Unitech/pm2#3197]
## What's going wrong?
I try to install pm2 under a user and fail.

```
sudo npm install -g pm2
sudo pm2 startup -u ubuntu
[...]
    amazon-ebs: >>> Executing systemctl start pm2-ubuntu
    amazon-ebs: Job for pm2-ubuntu.service failed because the control process exited with error code. See "systemctl status pm2-ubuntu.service" and "journalctl -xe" for details.

```

## How could we reproduce this issue?
Create a new ubuntu instance on AWS and run the above commands

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
fs.js:653
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/home/ubuntu/.pm2/pm2.log'
    at Object.fs.openSync (fs.js:653:18)
    at module.exports.Client.launchDaemon (/usr/lib/node_modules/pm2/lib/Client.js:207:14)
    at /usr/lib/node_modules/pm2/lib/Client.js:102:10
    at /usr/lib/node_modules/pm2/lib/Client.js:294:14
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

## systemctl status

```
$ systemctl status -n 100 pm2-ubuntu.service
Oct 06 17:17:55 ip-172-31-21-102 systemd[1]: Starting PM2 process manager...
Oct 06 17:17:56 ip-172-31-21-102 pm2[8844]: fs.js:653
Oct 06 17:17:56 ip-172-31-21-102 pm2[8844]:   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
Oct 06 17:17:56 ip-172-31-21-102 pm2[8844]:                  ^
Oct 06 17:17:56 ip-172-31-21-102 pm2[8844]: Error: EACCES: permission denied, open '/home/ubuntu/.pm2/pm2.log'
Oct 06 17:17:56 ip-172-31-21-102 pm2[8844]:     at Object.fs.openSync (fs.js:653:18)
Oct 06 17:17:56 ip-172-31-21-102 pm2[8844]:     at module.exports.Client.launchDaemon (/usr/lib/node_modules/pm2/lib/Client.js:207:14)
Oct 06 17:17:56 ip-172-31-21-102 pm2[8844]:     at /usr/lib/node_modules/pm2/lib/Client.js:102:10
Oct 06 17:17:56 ip-172-31-21-102 pm2[8844]:     at /usr/lib/node_modules/pm2/lib/Client.js:294:14
Oct 06 17:17:56 ip-172-31-21-102 pm2[8844]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
Oct 06 17:17:56 ip-172-31-21-102 pm2[8844]:     at process._tickCallback (internal/process/next_tick.js:180:9)
Oct 06 17:17:56 ip-172-31-21-102 systemd[1]: pm2-ubuntu.service: Control process exited, code=exited status=1
Oct 06 17:17:56 ip-172-31-21-102 systemd[1]: Failed to start PM2 process manager.
Oct 06 17:17:56 ip-172-31-21-102 systemd[1]: pm2-ubuntu.service: Unit entered failed state.
Oct 06 17:17:56 ip-172-31-21-102 systemd[1]: pm2-ubuntu.service: Failed with result 'exit-code'.
```

Might be related to https://github.com/Unitech/pm2/issues/1459

This is my current workaround

```
sudo pm2 startup
sudo chown ubuntu:ubuntu -R ~/.pm2
sudo pm2 startup -u ubuntu
sudo pm2 unstartup
sudo chown ubuntu:ubuntu -R ~/.pm2
```

**Comment by Unitech** [comment]
```
ubuntu$ npm install -g pm2
ubuntu$ pm2 startup
# COPY PASTE THE LINE SHOWN
ubuntu$ sudo pm2 startup XX XX XX
```

**Comment by ubershmekel** [comment]
@Unitech I want to script this installation on a machine a human does not interact with. Copy pasting isn't an option.
