### ISSUE TITLE
`pm2 install` scoped npm packages

### ISSUE THREAD

**Issue by mattbrunetti** [Unitech/pm2#3208]
## What's going wrong?

I want to use the `pm2 install <module>` command with a [scoped package on npm](https://docs.npmjs.com/getting-started/scoped-packages), but when I try I get an error:

```
C:\Users\mbrunetti>pm2 install @manitoulin-transport/dummy-private-package
[PM2][Module] Installing module @manitoulin-transport/dummy-private-package
[PM2][Module] Calling [YARN] to install @manitoulin-transport/dummy-private-package ...
yarn add v1.0.2
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ @manitoulin-transport/dummy-private-package@1.1.0
warning No license field
Done in 0.67s.
[PM2][Module] Module downloaded
ENOENT: no such file or directory, open 'C:\Users\mbrunetti\.pm2\node_modules\dummy-private-package\package.json'
module.js:491
    throw err;
    ^

Error: Cannot find module 'C:\Users\mbrunetti\.pm2\node_modules\dummy-private-package\package.json'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at startModule (C:\Users\mbrunetti\AppData\Roaming\npm\node_modules\pm2\lib\API\Modules\Modularizer.js:33:22)
    at C:\Users\mbrunetti\AppData\Roaming\npm\node_modules\pm2\lib\API\Modules\Modularizer.js:183:9
    at C:\Users\mbrunetti\AppData\Roaming\npm\node_modules\pm2\lib\Configuration.js:64:14
    at FSReqWrap.oncomplete (fs.js:135:15)
```

PM2 is looking for the package in `~/.pm2/node_modules/dummy-private-package/`, when it should be looking for the package in `~/.pm2/node_modules/@manitoulin-transport/dummy-private-package/`, where the package was actually installed.

[private packages on npm](https://docs.npmjs.com/private-modules/intro) are always scoped packages, so it's important for us to be able to `pm2 install` scoped packages.

## How could we reproduce this issue?

Run `pm2 install @manitoulin-transport/dummy-private-package`.

Here is [the package on npm](https://www.npmjs.com/package/@manitoulin-transport/dummy-private-package) and [the repository on github](https://github.com/ManitoulinTransport/dummy-private-package). It's name is not quite right, since I've made it public; a more accurate name would be dummy-scoped-package.

## Supporting information

<details>
<summary>$ pm2 report</summary>
<pre>
===============================================================================
--- PM2 REPORT (Wed Oct 11 2017 13:41:38 GMT-0400 (Eastern Daylight Time)) ----
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.7.1
node version         : 8.4.0
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\mbrunetti\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 9980min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.7.1
node version         : 8.4.0
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\mbrunetti\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : node
user                 : undefined
C:\Users\mbrunetti\AppData\Roaming\npm\node_modules\pm2\lib\API\Extra.js:70
        fmt.field('uid', process.geteuid());
                                 ^

TypeError: process.geteuid is not a function
    at C:\Users\mbrunetti\AppData\Roaming\npm\node_modules\pm2\lib\API\Extra.js:70:34
    at C:\Users\mbrunetti\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon-rpc\lib\client.js:45:10
    at Parser.<anonymous> (C:\Users\mbrunetti\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon\lib\sockets\req.js:67:8)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
    at Parser._write (C:\Users\mbrunetti\AppData\Roaming\npm\node_modules\pm2\node_modules\amp\lib\stream.js:91:16)
    at doWrite (_stream_writable.js:385:12)
    at writeOrBuffer (_stream_writable.js:371:5)
    at Parser.Writable.write (_stream_writable.js:288:11)
    at Socket.ondata (_stream_readable.js:642:20)
</pre>
</details>

**Comment by mattbrunetti** [comment]
I tried upgrading yarn to v1.2.0 (latest) but I got the same results.

**Comment by mattbrunetti** [comment]
I totally misunderstood what the `pm2 install <module>` is for, and it's not what I need, so I'm not concerned about this issue anymore... 

But for future reference, this command could support scoped/private npm packages if [getCanonicModuleName](https://github.com/Unitech/pm2/blob/9d980e017f1b3d31ba6d02f93a852c1a6e5e4cb3/lib/Utility.js#L181-L232) was changed to return `@foo/bar` given input `@foo/bar`
