### ISSUE TITLE
Can't run a python script with docs at beginning of file in cluster mode with multiple istances.

### ISSUE THREAD

**Issue by kiorq** [Unitech/pm2#3222]
## What's going wrong?
Can't cluster a python script with docs at beginning of file, like using docopt.

## How could we reproduce this issue?
Create a python script with docs at beginning of file, and try to run it in cluster mode with more than one instances
## Supporting information
Here is the error from logs
```
2|middlema | /Users/kirkdouglas/Code/e2etests/middleman/middleman_runner.py:1
2|middlema | (function (exports, require, module, __filename, __dirname) { '''
2|middlema |                                                                 ^
2|middlema |
2|middlema | SyntaxError: Invalid or unexpected token
2|middlema |     at createScript (vm.js:74:10)
2|middlema |     at Object.runInThisContext (vm.js:116:10)
2|middlema |     at Module._compile (module.js:533:28)
2|middlema |     at Object.Module._extensions..js (module.js:580:10)
2|middlema |     at Module.load (module.js:503:32)
2|middlema |     at tryModuleLoad (module.js:466:12)
2|middlema |     at Function.Module._load (module.js:458:3)
2|middlema |     at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:328:23
2|middlema |     at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:421:16
2|middlema |     at next (/usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:5302:29)
```

It doesn't seem to like the quotes at the beginning of script which I need for the docopt package to get arguments in my python script.

Report:
```
===============================================================================
--- PM2 REPORT (Thu Oct 19 2017 17:32:54 GMT-0500 (EST)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.7.2
node version         : 8.0.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : kirkdouglas
uid                  : 503
gid                  : 20
uptime               : 4min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.7.2
node version         : 8.0.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : kirkdouglas
uid                  : 503
gid                  : 20
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : darwin
type                 : Darwin
cpus                 : Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
cpus nb              : 4
freemem              : 1408000000
totalmem             : 17179869184
home                 : /Users/kirkdouglas
===============================================================================
--- PM2 list -----------------------------------------------
┌───────────┬────┬─────────┬───────┬─────────┬─────────┬────────┬─────┬───────────┬─────────────┬──────────┐
│ App name  │ id │ mode    │ pid   │ status  │ restart │ uptime │ cpu │ mem       │ user        │ watching │
├───────────┼────┼─────────┼───────┼─────────┼─────────┼────────┼─────┼───────────┼─────────────┼──────────┤
│ middleman │ 0  │ cluster │ 0     │ stopped │ 0       │ 0      │ 0%  │ 0 B       │ kirkdouglas │ disabled │
│ middleman │ 2  │ cluster │ 0     │ stopped │ 0       │ 0      │ 0%  │ 0 B       │ kirkdouglas │ disabled │
│ webapp    │ 1  │ fork    │ 75939 │ online  │ 0       │ 4m     │ 0%  │ 57.8 MB   │ kirkdouglas │ enabled  │
└───────────┴────┴─────────┴───────┴─────────┴─────────┴────────┴─────┴───────────┴─────────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/Users/kirkdouglas/.pm2/pm2.log last 20 lines:
PM2        | 2017-10-19 17:28:49: Application log path : /Users/kirkdouglas/.pm2/logs
PM2        | 2017-10-19 17:28:49: Process dump file    : /Users/kirkdouglas/.pm2/dump.pm2
PM2        | 2017-10-19 17:28:49: Concurrent actions   : 2
PM2        | 2017-10-19 17:28:49: SIGTERM timeout      : 1600
PM2        | 2017-10-19 17:28:49: ===============================================================================
PM2        | 2017-10-19 17:28:49: Starting execution sequence in -cluster mode- for app name:middleman id:0
PM2        | 2017-10-19 17:28:49: [Watch] Start watching webapp
PM2        | 2017-10-19 17:28:49: Starting execution sequence in -fork mode- for app name:webapp id:1
PM2        | 2017-10-19 17:28:49: App name:webapp id:1 online
PM2        | 2017-10-19 17:28:50: App name:middleman id:0 online
PM2        | 2017-10-19 17:28:50: Starting execution sequence in -cluster mode- for app name:middleman id:2
PM2        | 2017-10-19 17:28:50: (node:75937) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
PM2        | 2017-10-19 17:28:50: App name:middleman id:2 online
PM2        | 2017-10-19 17:28:50: (node:75937) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
PM2        | 2017-10-19 17:28:50: App name:middleman id:0 disconnected
PM2        | 2017-10-19 17:28:50: App [middleman] with id [0] and pid [75938], exited with code [0] via signal [SIGINT]
PM2        | 2017-10-19 17:28:50: Proc is not defined anymore or is being killed
PM2        | 2017-10-19 17:28:50: App name:middleman id:2 disconnected
PM2        | 2017-10-19 17:28:50: App [middleman] with id [2] and pid [75940], exited with code [0] via signal [SIGINT]
PM2        | 2017-10-19 17:28:50: Proc is not defined anymore or is being killed

Please copy/paste the above report in your issue on https://github.com/Unitech/pm2/issues
```

It works fine when I fork it and scale it up to like 3 instances via terminal commands, I want to be able to do that in a config

Thank you guys.

**Comment by kiorq** [comment]
My apologies should have done more digging. I changed the "exec_mode" to fork and it worked just fine.

**Comment by kiorq** [comment]
Just realized this defeats the purpose of load balancing, reopening.

**Comment by vmarchaud** [comment]
The cluster mode is only available with nodejs, so its an expected behavior
