### ISSUE TITLE
PM2 global error caught 

### ISSUE THREAD

**Issue by docaohuynh** [Unitech/pm2#3229]
I am using Pm2 version 2.7.1, Node v6.11.4, Centos 7
and I have a crash

```
2017-10-24 13:46:30: --- PM2 global error caught ---------------------------------------------------
2017-10-24 13:46:30: Time                 : Tue Oct 24 2017 13:46:30 GMT+0700 (+07)
2017-10-24 13:46:30: Cannot read property 'on' of undefined
2017-10-24 13:46:30: TypeError: Cannot read property 'on' of undefined
    at /data/software/nodejs/node-v6.11.4-linux-x64/lib/node_modules/pm2/lib/God/ForkMode.js:109:18
    at /data/software/nodejs/node-v6.11.4-linux-x64/lib/node_modules/pm2/node_modules/async/dist/async.js:421:16
    at next (/data/software/nodejs/node-v6.11.4-linux-x64/lib/node_modules/pm2/node_modules/async/dist/async.js:5302:29)
    at /data/software/nodejs/node-v6.11.4-linux-x64/lib/node_modules/pm2/node_modules/async/dist/async.js:906:16
    at WriteStream.<anonymous> (/data/software/nodejs/node-v6.11.4-linux-x64/lib/node_modules/pm2/lib/Utility.js:171:13)
    at emitOne (events.js:96:13)
    at WriteStream.emit (events.js:188:7)
    at WriteStream.<anonymous> (fs.js:2128:10)
    at FSReqWrap.oncomplete (fs.js:123:15)
2017-10-24 13:46:30: ===============================================================================
2017-10-24 13:46:30: [PM2] Resurrecting PM2
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn node EAGAIN
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at Immediate._tickDomainCallback (internal/process/next_tick.js:128:9)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
2017-10-24 13:46:44: ===============================================================================
```
any help. Thanks :)

**Comment by Unitech** [comment]
Could you run `pm2 report`
