### ISSUE TITLE
Error logged once at startup around configuration although startup works fine

### ISSUE THREAD

**Issue by shaunwarman** [Unitech/pm2#3231]
## What's going wrong?
Using `pm2-docker` and an error is logged on startup due to configuration. Configuration looks fine. Maybe something simple like `wait_ready` vs `wait-ready`? Startup works fine, but the below message occurs once or twice at initial startup.

## Supporting information
Pm2 version: 2.4.0

#### Configuration
```
{
  "apps": [{
    "name": "app",
    "script": "index.js",
    "instances": "max",
    "exec_mode": "cluster",
    "error_file": "/dev/null",
    "out_file": "/dev/null",
    "merge_logs": false,
    "log_date_format": "YYYY-MM-DD HH:mm Z",
    "listen_timeout": 3000,
    "wait_ready": true,
    "env": {
      "CLUSTER_INSTANCE": "max",
      "DEPLOY_ENV": "STAGE",
      "NODE_ENV": "staging",
    }
  }]
}
```

#### Error logs
```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.Configuration.getAllSync (/usr/local/lib/node_modules/pm2x/lib/Configuration.js:271:17)
    at Object.Modularizer.getAdditionalConf (/usr/local/lib/node_modules/pm2x/lib/API/Modules/Modularizer.js:246:35)
    at /usr/local/lib/node_modules/pm2x/lib/API.js:1018:40
    at /usr/local/lib/node_modules/pm2x/node_modules/async/lib/async.js:181:20
    at replenish (/usr/local/lib/node_modules/pm2x/node_modules/async/lib/async.js:319:21)
    at /usr/local/lib/node_modules/pm2x/node_modules/async/lib/async.js:330:15
    at Object.async.forEachLimit.async.eachLimit (/usr/local/lib/node_modules/pm2x/node_modules/async/lib/async.js:220:35)
    at startApps (/usr/local/lib/node_modules/pm2x/lib/API.js:988:11)
    at /usr/local/lib/node_modules/pm2x/lib/API.js:970:14
```

`module_conf.json` is empty.

**Comment by vmarchaud** [comment]
You should remove it if empty, i'm guessing that it fails to parse JSON since there is no bracket. Or you can just put `{}` in it
