### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by zvictor** [Unitech/pm2#324]
I am running pm2 0.7.8 in a centos 6.5 x64 machine and for any pm2 command I run in the terminal I see this error:

``` haskell
$ pm2 list

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

**Comment by pgmsuper** [comment]
个
