### ISSUE TITLE
PM2 

### ISSUE THREAD

**Issue by Sailor20** [Unitech/pm2#3259]
```
2017-11-06 10:28:30: --- PM2 global error caught ---------------------------------------------------
PM2        | 2017-11-06 10:28:30: Time                 : Mon Nov 06 2017 10:28:30 GMT+0800 (CST)
PM2        | 2017-11-06 10:28:30: Callback was already called.
PM2        | 2017-11-06 10:28:30: Error: Callback was already called.
PM2        |     at /home/dlhr/.nvm/versions/node/v6.11.1/lib/node_modules/pm2/node_modules/async/dist/async.js:903:32
PM2        |     at WriteStream.<anonymous> (/home/dlhr/.nvm/versions/node/v6.11.1/lib/node_modules/pm2/lib/Utility.js:162:13)
PM2        |     at emitOne (events.js:96:13)
PM2        |     at WriteStream.emit (events.js:188:7)
PM2        |     at onwriteError (_stream_writable.js:343:10)
PM2        |     at onwrite (_stream_writable.js:361:5)
PM2        |     at WritableState.onwrite (_stream_writable.js:90:5)
PM2        |     at fs.js:2148:14
PM2        |     at FSReqWrap.wrapper [as oncomplete] (fs.js:748:5)
PM2        | 2017-11-06 10:28:30: ===============================================================================
PM2        | 2017-11-06 10:28:30: [PM2] Resurrecting PM2
PM2        | /home/dlhr/.nvm/versions/node/v6.11.1/lib/node_modules/pm2/node_modules/async/dist/async.js:903
PM2        |         if (fn === null) throw new Error("Callback was already called.");
PM2        |                          ^
PM2        | 
PM2        | Error: Callback was already called.
PM2        |     at /home/dlhr/.nvm/versions/node/v6.11.1/lib/node_modules/pm2/node_modules/async/dist/async.js:903:32
PM2        |     at WriteStream.<anonymous> (/home/dlhr/.nvm/versions/node/v6.11.1/lib/node_modules/pm2/lib/Utility.js:162:13)
PM2        |     at emitOne (events.js:96:13)
PM2        |     at WriteStream.emit (events.js:188:7)
PM2        |     at onwriteError (_stream_writable.js:343:10)
PM2        |     at onwrite (_stream_writable.js:361:5)
PM2        |     at WritableState.onwrite (_stream_writable.js:90:5)
PM2        |     at fs.js:2148:14
PM2        |     at FSReqWrap.wrapper [as oncomplete] (fs.js:748:5)
PM2        | [PM2] Spawning PM2 daemon with pm2_home=/home/dlhr/.pm2
PM2        | 2017-11-06 11:48:42: Starting execution sequence in -fork mode- for app name:api-server id:0
PM2        | 2017-11-06 11:48:42: Starting execution sequence in -fork mode- for app name:cron-server id:1
PM2        | 2017-11-06 11:48:42: App name:api-server id:0 online
PM2        | 2017-11-06 11:48:42: App name:cron-server id:1 online
```

the error occurred in my server, what should i do?

**Comment by Unitech** [comment]
Which PM2 version are you running?
Could you run `pm2 report`
