### ISSUE TITLE
Using pgrep from brew proctools on OS X Sierra causes crashes due to large numbers of pgrep processes

### ISSUE THREAD

**Issue by inversion** [Unitech/pm2#3262]
## What's going wrong?

If you have `/usr/local/bin` before `/usr/bin` in your `PATH`, and a non-standard pgrep installed in `/usr/local/bin`, TreeKill fails to work and spawns hundreds of pgrep processes which typically make the system unusable. This is presumably because the `-P` parameter might be handled differently in the OSX and brew versions of `pgrep`.

The console is filled with:

```
PM2        | { Error: spawn pgrep EAGAIN
PM2        |     at _errnoException (util.js:1024:11)
PM2        |     at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
PM2        |     at onErrorNT (internal/child_process.js:374:16)
PM2        |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
PM2        |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
PM2        |   code: 'EAGAIN',
PM2        |   errno: 'EAGAIN',
PM2        |   syscall: 'spawn pgrep',
PM2        |   path: 'pgrep',
PM2        |   spawnargs: [ '-P', 31316 ] }
```

## How could we reproduce this issue?

`brew install proctools`
`export PATH=/usr/local/bin:$PATH`
`pm2 start`
Make a change to a watched file.

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
===============================================================================
--- PM2 REPORT (Tue Nov 07 2017 16:49:28 GMT+0000 (GMT)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.7.2
node version         : 8.8.1
node path            : /usr/bin/nice
argv                 : /usr/local/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : andrew
uid                  : 501
gid                  : 20
uptime               : 15min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.7.2
node version         : 8.8.1
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : andrew
uid                  : 501
gid                  : 20
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : darwin
type                 : Darwin
cpus                 : Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
cpus nb              : 8
freemem              : 4424851456
totalmem             : 17179869184
home                 : /Users/andrew
===============================================================================
```

**Comment by sonnenhaft** [comment]
Also helps to uninstall "pkill" and proctools form brew, because mac from 10.8 has its own pkill (just for whoever is having same issue)
