### ISSUE TITLE
pm 2.7.2 Cannot read property 'filename' of undefined 

### ISSUE THREAD

**Issue by SteveCruise** [Unitech/pm2#3265]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?

```
0|app      | TypeError: Cannot read property 'filename' of undefined
0|app      |     at findPackageJson (/usr/local/lib/node_modules/pm2/node_modules/_pmx@1.5.4@pmx/lib/configuration.js:24:57)
0|app      |     at Object.Options.init (/usr/local/lib/node_modules/pm2/node_modules/_pmx@1.5.4@pmx/lib/configuration.js:43:26)
0|app      |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/_pmx@1.5.4@pmx/lib/pmx.js:31:31)
0|app      |     at Module._compile (module.js:641:30)
0|app      |     at Object.Module._extensions..js (module.js:652:10)
0|app      |     at Module.load (module.js:560:32)
0|app      |     at tryModuleLoad (module.js:503:12)
0|app      |     at Function.Module._load (module.js:495:3)
0|app      |     at Module.require (module.js:585:17)
0|app      |     at require (internal/module.js:11:18)
PM2        | App [app] with id [0] and pid [20564], exited with code [1] via signal [SIGINT]
```

**Comment by neyasov** [comment]
+1

**Comment by vmarchaud** [comment]
Are you trying to use `.mjs` file ?

**Comment by neyasov** [comment]
@vmarchaud, i use dynamic-import in .js/.mjs with @std/esm

**Comment by neyasov** [comment]
@vmarchaud, the problem resolved after renaming to .mjs

**Comment by vmarchaud** [comment]
see https://github.com/Unitech/pm2/pull/3248
