### ISSUE TITLE
FreeBSD startup not supported

### ISSUE THREAD

**Issue by 720720** [Unitech/pm2#3287]
FreeBSD 11.1 x64
PM2 2.7.2

When generating a startup script as root I get the following errors:

pm2 startup

```
[PM2][ERROR] Init system not found
/usr/local/lib/node_modules/pm2/lib/API/Startup.js:183
      throw new Error('Init system not found');
      ^

Error: Init system not found
    at module.exports.CLI.startup (/usr/local/lib/node_modules/pm2/lib/API/Startup.js:183:13)
    at Command.<anonymous> (/usr/local/lib/node_modules/pm2/bin/pm2:621:9)
    at Command.listener (/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:125:13)
    at Command.emit (events.js:213:7)
    at Command.parseArgs (/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:635:12)
    at Command.parse (/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:457:21)
    at Timeout._onTimeout (/usr/local/lib/node_modules/pm2/bin/pm2:184:15)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
```

pm2 startup freebsd

`[PM2][ERROR] Init system not found`

pm2 unstartup freebsd

```
[PM2][ERROR] Init system not found
/usr/local/lib/node_modules/pm2/lib/API/Startup.js:144
    shelljs.exec(commands.join('&& '), function(code, stdout, stderr) {
                          ^

TypeError: Cannot read property 'join' of undefined
    at module.exports.CLI.uninstallStartup (/usr/local/lib/node_modules/pm2/lib/API/Startup.js:144:27)
    at Command.<anonymous> (/usr/local/lib/node_modules/pm2/bin/pm2:612:9)
    at Command.listener (/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:125:13)
    at Command.emit (events.js:213:7)
    at Command.parseArgs (/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:635:12)
    at Command.parse (/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:457:21)
    at Timeout._onTimeout (/usr/local/lib/node_modules/pm2/bin/pm2:184:15)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
```

**Comment by vmarchaud** [comment]
FreeBSD init system is not supported, feel free to add support to it

**Comment by 720720** [comment]
https://github.com/Unitech/pm2

Startup script generation

PM2 can generate and configure a startup script to keep PM2 and your processes alive at every server restart.

Supports init systems like: systemd (Ubuntu 16, CentOS, Arch), upstart (Ubuntu 14/12), launchd (MacOSx, Darwin), **rc.d (FreeBSD)**.


http://pm2.keymetrics.io/docs/usage/startup/

Init systems supported

systemd: Ubuntu >= 16, CentOS >= 7, Arch, Debian >= 7
upstart: Ubuntu <= 14
launchd: Darwin, MacOSx
openrc: Gentoo Linux, Arch Linux
**rcd: FreeBSD**
systemv: Centos 6, Amazon Linux

**Comment by FlorianBerthold** [comment]
I can replicate the identical issue on:
- FreeBSD 11.0-RELEASE-p9 x64
- pm2 2.7.2

I expected that FreeBSD is official supported, see...

https://github.com/Unitech/pm2/blob/596b29c8409246a8b5b36be9ff3904a8b5c26285/lib/API/Startup.js#L256-L264

**Comment by Unitech** [comment]
sysrc + rcctl supported https://github.com/Unitech/pm2/blob/master/lib/API/Startup.js#L37
