### ISSUE TITLE
pm2 launches rogoue duplicate process

### ISSUE THREAD

**Issue by ArsalanDotMe** [Unitech/pm2#3291]
## What's going wrong?
pm2 launches duplicate ...ProcessContainerFork.js process which does not appear in the pm2 process list but keeps outputting its output to pm2 logs command. So running `pm2 stop all` stops the main process but the duplicate process keeps running in the background. I think it happens during restarts. Maybe instead of killing old process and starting new one, the kill command fails and a new process is started without killing old one (not sure, this is just my theory). I don't know how to reproduce this since this happens rarely but consistently. Let me know what data I could collect to help resolve this issue.

## How could we reproduce this issue?
Don't know yet. Happens rarely and under load.

## Supporting information
Operating System: Windows Server 2016

```
===============================================================================
--- PM2 REPORT (Sat Nov 18 2017 13:24:09 GMT+0100 (W. Europe Standard Time)) --
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.7.2
node version         : 6.12.0
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\lib\
Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 223min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.7.2
node version         : 6.12.0
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\bin\
pm2,report
argv0                : node
user                 : undefined
C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\lib\API\Extra.js:70
        fmt.field('uid', process.geteuid());
                                 ^

TypeError: process.geteuid is not a function
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\lib\API\Extra.js:70:34
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon-rpc\lib\client.js:45:10
    at Parser.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon\lib\sockets
\req.js:67:8)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._write (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\amp\lib\stream.js:91:16)
    at doWrite (_stream_writable.js:333:12)
    at writeOrBuffer (_stream_writable.js:319:5)
    at Parser.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (_stream_readable.js:555:20)
```

**Comment by vmarchaud** [comment]
Could you share a simple example that reproduce the problem please ? Thanks

**Comment by ArsalanDotMe** [comment]
I can't reproduce it on simple scripts but it happens pretty often in our production app which is fairly complex. Is there some kind of logs I can collect that can help identify the problem?

**Comment by vmarchaud** [comment]
You could check `~/.pm2/pm2.log` for errors i guess

**Comment by anselanza** [comment]
Happens to me consistently, with the following setup:

- Windows host
- Binary exe rather than a NodeJS script (exec_interpreter: "none")
- Set a low max_memory_restart limit

If the application is terminated manually (just closing it), then PM2 restarts the process just fine. But if it is restarted because of hitting the specified memory limit, a rogue instance is spawned (that PM2 apparently doesn't know about) and then subsequent attempts to restart the app fail.

Sample PM2 log:

```
2017-11-22 13:33:13: ===============================================================================
2017-11-22 13:33:13: --- New PM2 Daemon started ----------------------------------------------------
2017-11-22 13:33:13: Time                 : Wed Nov 22 2017 13:33:13 GMT+0100 (W. Europe Standard Time)
2017-11-22 13:33:13: PM2 version          : 2.7.2
2017-11-22 13:33:13: Node.js version      : 8.9.1
2017-11-22 13:33:13: Current arch         : x64
2017-11-22 13:33:13: PM2 home             : C:\Users\User\.pm2
2017-11-22 13:33:13: PM2 PID file         : C:\Users\User\.pm2\pm2.pid
2017-11-22 13:33:13: RPC socket file      : \\.\pipe\rpc.sock
2017-11-22 13:33:13: BUS socket file      : \\.\pipe\pub.sock
2017-11-22 13:33:13: Application log path : C:\Users\User\.pm2\logs
2017-11-22 13:33:13: Process dump file    : C:\Users\User\.pm2\dump.pm2
2017-11-22 13:33:13: Concurrent actions   : 2
2017-11-22 13:33:13: SIGTERM timeout      : 1600
2017-11-22 13:33:13: ===============================================================================
2017-11-22 13:33:13: Starting execution sequence in -fork mode- for app name:pm2-datadog id:0
2017-11-22 13:33:13: App name:pm2-datadog id:0 online
2017-11-22 13:33:13: Starting execution sequence in -fork mode- for app name:snapshotapp id:1
2017-11-22 13:33:13: App name:snapshotapp id:1 online
2017-11-22 13:33:13: Starting execution sequence in -fork mode- for app name:node-server id:2
2017-11-22 13:33:13: App name:node-server id:2 online
2017-11-22 13:33:13: Starting execution sequence in -fork mode- for app name:max-audio id:3
2017-11-22 13:33:13: App name:max-audio id:3 online
2017-11-22 13:33:13: Starting execution sequence in -fork mode- for app name:sentinel-bridge id:4
2017-11-22 13:33:13: App name:sentinel-bridge id:4 online
2017-11-22 13:34:44: [PM2][WORKER] Process 1 restarted because it exceeds --max-memory-restart value (current_memory=466
8026880 max_memory_limit=4294967296 [octets])
2017-11-22 13:34:44: Process 1 in a stopped status, starting it
2017-11-22 13:34:44: Stopping app:snapshotapp id:1
2017-11-22 13:34:44: pid=6740 msg=process killed
2017-11-22 13:34:44: Starting execution sequence in -fork mode- for app name:snapshotapp id:1
2017-11-22 13:34:44: App name:snapshotapp id:1 online
2017-11-22 13:34:45: App [snapshotapp] with id [1] and pid [0], exited with code [1] via signal [SIGINT]
2017-11-22 13:34:46: Starting execution sequence in -fork mode- for app name:snapshotapp id:1
2017-11-22 13:34:46: App name:snapshotapp id:1 online
2017-11-22 13:34:47: App [snapshotapp] with id [1] and pid [5448], exited with code [3221226505] via signal [SIGINT]
2017-11-22 13:34:48: Starting execution sequence in -fork mode- for app name:snapshotapp id:1
2017-11-22 13:34:48: App name:snapshotapp id:1 online
2017-11-22 13:34:49: App [snapshotapp] with id [1] and pid [7984], exited with code [3221226505] via signal [SIGINT]
2017-11-22 13:34:50: Starting execution sequence in -fork mode- for app name:snapshotapp id:1
2017-11-22 13:34:50: App name:snapshotapp id:1 online
2017-11-22 13:34:51: App [snapshotapp] with id [1] and pid [6552], exited with code [3221226505] via signal [SIGINT]
2017-11-22 13:34:52: Starting execution sequence in -fork mode- for app name:snapshotapp id:1
2017-11-22 13:34:52: App name:snapshotapp id:1 online
2017-11-22 13:34:53: App [snapshotapp] with id [1] and pid [8972], exited with code [3221226505] via signal [SIGINT]
2017-11-22 13:34:54: Starting execution sequence in -fork mode- for app name:snapshotapp id:1
2017-11-22 13:34:54: App name:snapshotapp id:1 online
2017-11-22 13:34:55: App [snapshotapp] with id [1] and pid [8672], exited with code [3221226505] via signal [SIGINT]
2017-11-22 13:34:56: Starting execution sequence in -fork mode- for app name:snapshotapp id:1
2017-11-22 13:34:56: App name:snapshotapp id:1 online
2017-11-22 13:34:57: App [snapshotapp] with id [1] and pid [1600], exited with code [3221226505] via signal [SIGINT]
2017-11-22 13:34:58: Starting execution sequence in -fork mode- for app name:snapshotapp id:1
2017-11-22 13:34:58: App name:snapshotapp id:1 online
2017-11-22 13:35:00: App [snapshotapp] with id [1] and pid [4796], exited with code [3221226505] via signal [SIGINT]
2017-11-22 13:35:01: Starting execution sequence in -fork mode- for app name:snapshotapp id:1
2017-11-22 13:35:01: App name:snapshotapp id:1 online
2017-11-22 13:35:02: App [snapshotapp] with id [1] and pid [224], exited with code [3221226505] via signal [SIGINT]
2017-11-22 13:35:03: Starting execution sequence in -fork mode- for app name:snapshotapp id:1
2017-11-22 13:35:03: App name:snapshotapp id:1 online
2017-11-22 13:35:03: App [snapshotapp] with id [1] and pid [820], exited with code [3221225786] via signal [SIGINT]
2017-11-22 13:35:04: Starting execution sequence in -fork mode- for app name:snapshotapp id:1
2017-11-22 13:35:04: App name:snapshotapp id:1 online
2017-11-22 13:35:05: App [snapshotapp] with id [1] and pid [10160], exited with code [3221226505] via signal [SIGINT]
2017-11-22 13:35:06: Starting execution sequence in -fork mode- for app name:snapshotapp id:1
2017-11-22 13:35:06: App name:snapshotapp id:1 online
2017-11-22 13:35:07: App [snapshotapp] with id [1] and pid [10000], exited with code [3221226505] via signal [SIGINT]
2017-11-22 13:35:07: [HandleExit] PM2 is being killed, stopping restart procedure...
2017-11-22 13:35:07: 0
2017-11-22 13:35:07: Stopping app:pm2-datadog id:0
2017-11-22 13:35:07: App [pm2-datadog] with id [0] and pid [10764], exited with code [1] via signal [SIGINT]
```

**Comment by ArsalanDotMe** [comment]
Here's a piece of log where doing `pm2 restart all` on a machine with just one script running produced 2 duplicate processes and the following logs:

```
2017-11-24 14:06:10: Stopping app:main id:0
2017-11-24 14:06:11: pid=303264 msg=process killed
2017-11-24 14:06:11: Starting execution sequence in -fork mode- for app name:main id:0
2017-11-24 14:06:11: App name:main id:0 online
2017-11-24 14:06:11: App [main] with id [0] and pid [0], exited with code [1] via signal [SIGINT]
2017-11-24 14:06:11: Starting execution sequence in -fork mode- for app name:main id:0
2017-11-24 14:06:11: App name:main id:0 online
```
Notice the line `App [main] with id [0] and pid [0], exited with code [1] via signal [SIGINT]`. There can be no process with pid [0] so pm2 somehow detects wrong sigint and starts a new process.

**Comment by Unitech** [comment]
Have you caught the SIGINT or SIGTERM signal in your application?

**Comment by ArsalanDotMe** [comment]
Yes, I have. Could that be causing this issue?

**Comment by E3V3A** [comment]
FWIW:  

This may be totally irrelevant, but... Native Windows CLI sucks at stopping forked processes. In addition the PID's reported in environments, such as Cygwin often cannot be used to stop a process, simply because that is not the true PID. You need to stop the WINPID. This is accomplished by installing *sysinternals*, `pskill64.exe` command, and running it with: `pskill64.exe -t <WINPID>`.

**Comment by akirablaid** [comment]
I get duped processes constantly.

**Comment by joelhickok** [comment]
This happens to me all the time.  It seems like it happens when I run `pm2 restart`.  Then if I update the codebase and restart, the app does not update because it's still running the original rogue process.  Only way to fix and get an update on the app is to restart machine.

**Comment by cburatto** [comment]
Happening in my Windows Server 2016. The process doesn't even appear on the PM2 `list` or `monit`, but still executes.

Using pm2 5.1.3

**Comment by NathanD19** [comment]
I am also running Windows Server 2016 and I am always getting duplicate processes.

**Comment by rafaelrferreira** [comment]
I am running Windows 10 and Ubuntu and still getting duplicate processes in 2022. =(

**Comment by ko3ak81** [comment]
Getting the same on Ubuntu 18 after restart, not always but very often, latest version

**Comment by ejames17** [comment]
Yup same issue on windows server 2022

**Comment by shaobaili3** [comment]
The same issue on Linux please fix

**Comment by tholeb** [comment]
Same issue on Ubuntu 22.04, Raspberry Pi 4 8Gb.

**Comment by cichy28** [comment]
Same issue. Windows server 2022

**Comment by laocoi** [comment]
The same issue, restart the computer is the only way to solve the problem
