### ISSUE TITLE
SyntaxError: Unexpected token ) when issuing `pm2 stop -` 

### ISSUE THREAD

**Issue by ktravelet** [Unitech/pm2#3307]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?
I fat fingered a command and pm2 emitted a strange error.  However, PM2 managed to not shut down so this wouldn't be considered a huge problem.   

## How could we reproduce this issue?
```
$ pm2 stop -

evalmachine.<anonymous>:2
)
^

SyntaxError: Unexpected token )
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Object.Common.parseConfig (/usr/local/lib/node_modules/pm2/lib/Common.js:277:17)
    at module.exports.API.actionFromJson (/usr/local/lib/node_modules/pm2/lib/API.js:1124:22)
    at ReadStream.<anonymous> (/usr/local/lib/node_modules/pm2/lib/API.js:557:12)
    at emitOne (events.js:115:13)
    at ReadStream.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:249:13)
    at ReadStream.Readable.push (_stream_readable.js:211:10)
```

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
===============================================================================
--- PM2 REPORT (Wed Nov 22 2017 15:42:41 GMT-0800 (PST)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.7.1
node version         : 8.6.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/Cellar/node/8.6.0/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : i827087
uid                  : 501
gid                  : 20
uptime               : 3166min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.7.1
node version         : 8.6.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/Cellar/node/8.6.0/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : i827087
uid                  : 501
gid                  : 20
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : darwin
type                 : Darwin
cpus                 : Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
cpus nb              : 8
freemem              : 4083933184
totalmem             : 17179869184
home                 : /Users/i827087
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬─────────┬──────────┐
│ App name │ id │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user    │ watching │
├──────────┼────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼─────────┼──────────┤
│ Hanamon  │ 0  │ fork │ 0   │ stopped │ 21      │ 0      │ 0%  │ 0 B    │ i827087 │ disabled │
└──────────┴────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴─────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/Users/i827087/.pm2/pm2.log last 20 lines:
PM2        | 2017-11-22 12:47:50: App name:Hanamon id:0 online
PM2        | 2017-11-22 15:17:59: Stopping app:Hanamon id:0
PM2        | 2017-11-22 15:17:59: App [Hanamon] with id [0] and pid [35040], exited with code [0] via signal [SIGINT]
PM2        | 2017-11-22 15:17:59: pid=35040 msg=process killed
PM2        | 2017-11-22 15:17:59: Starting execution sequence in -fork mode- for app name:Hanamon id:0
PM2        | 2017-11-22 15:17:59: App name:Hanamon id:0 online
PM2        | 2017-11-22 15:18:40: Stopping app:Hanamon id:0
PM2        | 2017-11-22 15:18:40: App [Hanamon] with id [0] and pid [45386], exited with code [0] via signal [SIGINT]
PM2        | 2017-11-22 15:18:40: pid=45386 msg=process killed
PM2        | 2017-11-22 15:18:40: Starting execution sequence in -fork mode- for app name:Hanamon id:0
PM2        | 2017-11-22 15:18:40: App name:Hanamon id:0 online
PM2        | 2017-11-22 15:19:42: Stopping app:Hanamon id:0
PM2        | 2017-11-22 15:19:42: App [Hanamon] with id [0] and pid [45454], exited with code [0] via signal [SIGINT]
PM2        | 2017-11-22 15:19:43: pid=45454 msg=process killed
PM2        | 2017-11-22 15:19:43: Starting execution sequence in -fork mode- for app name:Hanamon id:0
PM2        | 2017-11-22 15:19:43: App name:Hanamon id:0 online
PM2        | 2017-11-22 15:40:36: 0
PM2        | 2017-11-22 15:40:36: Stopping app:Hanamon id:0
PM2        | 2017-11-22 15:40:36: App [Hanamon] with id [0] and pid [45563], exited with code [0] via signal [SIGINT]
PM2        | 2017-11-22 15:40:36: pid=45563 msg=process killed

Please copy/paste the above report in your issue on https://github.com/Unitech/pm2/issues
```

**Comment by vmarchaud** [comment]
When you use `-`, commander expect arguments in a pipe, so it's normal that it fail in this case
