### ISSUE TITLE
pm2 not start anymore

### ISSUE THREAD

**Issue by samumeur** [Unitech/pm2#3392]
Hello, 

I've installed pm2, I tested once, and it worked.

Then, I restarted my raspberry, and when I tryied to launch back pm2 with my app, but... it didn't work:

pi@raspberrypi:~/Raspy $ pm2 start Main.js
/usr/lib/node_modules/pm2/node_modules/ansi-styles/index.js:1
(function (exports, require, module, __filename, __dirname) { 9efa0aac4a4591c6a7                                                                                                                                                             304129bfa5ce3a5
                                                              ^^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/node_modules/chalk/index.js                                                                                                                                                             :3:18)

I already tryied to uninstall/install pm2 but nothing changed.

My app is working alone.

Thanks in advance!

**Comment by vmarchaud** [comment]
Please re-open an issue with the template filed (specially `pm2 report`)
