### ISSUE TITLE
Error: listen EACCES IP:80 with ExpressJS and PM2

### ISSUE THREAD

**Issue by pirmax** [Unitech/pm2#3411]
I want host my ExpressJS (AdonisJS) application on PM2.

But, 80 port is not authorize less than 1024.

I want add HOST URL and PORT.

```
Error: listen EACCES IP:80
at Object._errnoException (util.js:1024:11)
at _exceptionWithHostPort (util.js:1046:20)
at Server.setupListenHandle [as _listen2] (net.js:1334:19)
at listenInCluster (net.js:1392:12)
at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
```

I want use 80 port because I want my application is accessible from URL without port...

**Comment by Unitech** [comment]
Use authbind

http://pm2.keymetrics.io/docs/usage/specifics/#listening-on-port-80-w-o-root
