### ISSUE TITLE
Can´t see reason behind ECONNREFUSED error

### ISSUE THREAD

**Issue by CodingJonas** [Unitech/pm2#3488]
## What's going wrong?
pm2 doesn't manage to connect

## How could we reproduce this issue?
I try to run the this script: https://github.com/cubedro/eth-net-intelligence-api

## Supporting information
This is the error log I get:

```
2018-02-22 18:48 +01:00: [wsc] =✘= Socket error: { Error: connect ECONNREFUSED 127.0.0.1:3000
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3000,
  type: 'error',
  target: 
   WebSocket {
     domain: null,
     _events: { error: [Function: onerror] },
     _eventsCount: 1,
     _maxListeners: undefined,
     _socket: null,
     _ultron: null,
     _closeReceived: false,
     bytesReceived: 0,
     readyState: 3,
     supports: { binary: true },
     extensions: null,
     _binaryType: 'arraybuffer',
     _isServer: false,
     url: 'ws://localhost:3000/api/?_primuscb=M6-eNQn',
     protocolVersion: 13,
     _closeTimer: null,
     _closeCode: 1006 } }
```
This is the output of `pm2 report`:
```
===============================================================================
--- PM2 REPORT (Thu Feb 22 2018 18:59:48 GMT+0100 (CET)) ----------------------
===============================================================================
--- Daemon --------------------------------------------------------------------
pm2d version         : 2.10.1
node version         : 9.5.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/Cellar/node/9.5.0/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : jonas
uid                  : 502
gid                  : 20
uptime               : 0min
===============================================================================
--- CLI -----------------------------------------------------------------------
local pm2            : 2.10.1
node version         : 9.5.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/Cellar/node/9.5.0/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : jonas
uid                  : 502
gid                  : 20
===============================================================================
--- System info ---------------------------------------------------------------
arch                 : x64
platform             : darwin
type                 : Darwin
cpus                 : Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
cpus nb              : 4
freemem              : 38416384
totalmem             : 4294967296
home                 : /Users/jonas
===============================================================================
--- PM2 list ------------------------------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
===============================================================================
--- Daemon logs ---------------------------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

I couldn`t find a solution for this problem so far. So any advice would be awesome!

**Comment by CodingJonas** [comment]
My mistake. I was thinking `pm2` will open the port it needs to transmit data through. So I haven't open one yet. Opening one `pm2` could connect to. Should have read the documentation better.
