### ISSUE TITLE
Can't start .bat file

### ISSUE THREAD

**Issue by luizwbr** [Unitech/pm2#3498]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?

When I try to start a .bat file, I got this error:

```
Importação de produto > D:\apps\Pentaho_8.0.0\data-integration\Kitchen.bat:1 
Importação de produto > (function (exports, require, module, __filename, __dirname) { @echo off
Importação de produto > SyntaxError: Invalid or unexpected token
Importação de produto >     at createScript (vm.js:80:10)
Importação de produto >     at Object.runInThisContext (vm.js:139:10)
Importação de produto >     at Module._compile (module.js:599:28)
Importação de produto >     at Object.Module._extensions..js (module.js:646:10)
Importação de produto >     at Module.load (module.js:554:32)
Importação de produto >     at tryModuleLoad (module.js:497:12)
Importação de produto >     at Function.Module._load (module.js:489:3)
Importação de produto >     at Object.<anonymous> (C:\Users\luiz.weber\AppData\Roaming\npm\node_modules\pm2\lib\
ProcessContainerFork.js:83:21)
Importação de produto >     at Module._compile (module.js:635:30)
Importação de produto >     at Object.Module._extensions..js (module.js:646:10)
```

## How could we reproduce this issue?
```
pm2 start anyfile.bat
```` 

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
===============================================================================
--- PM2 REPORT (Mon Feb 26 2018 15:18:12 GMT-0300 (E. South America Standard Time))
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.1
node version         : 8.9.1
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\luiz.weber\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 5644min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.1
node version         : 8.9.1
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\luiz.weber\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : node
user                 : luiz.weber
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
cpus nb              : 4
freemem              : 1395499008
totalmem             : 8471072768
home                 : C:\Users\luiz.weber
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬────────────┬──────────┐
│ App name │ id │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user       │ watching │
├──────────┼────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼────────────┼──────────┤
│ Kitchen  │ 0  │ fork │ 0   │ errored │ 15      │ 0      │ 0%  │ 0 B    │ luiz.weber │ disabled │
└──────────┴────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴────────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬────────────┬──────────┐
│ App name │ id │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user       │ watching │
├──────────┼────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼────────────┼──────────┤
│ Kitchen  │ 0  │ fork │ 0   │ errored │ 15      │ 0      │ 0%  │ 0 B    │ luiz.weber │ disabled │
└──────────┴────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴────────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

**Comment by luizwbr** [comment]
After all this time, I searched again for the same term and ended up in this thread.
The problem was the interpreter mode. To start .bat files, you must manually set the interpreter to none.

`pm2 start some.bat --interpreter none`

**Comment by cyqsimon** [comment]
Thanks, worked like a charm. I recently started using pm2 on my W10 machine and ran straight into this issue.

**Comment by thomasmost** [comment]
@luizwbr I know it's years later but how do I set this in the ecosystem file? setting "interpreter": "none" doesn't seem to work

**Comment by thomasmost** [comment]
Also passing it at the command line doesn't even seem to work

**Comment by Kevin-Velasquez-ACSG** [comment]
Any luck on this? 

--Interpreter   did nothing for me and pm2 is being useless with n8n as its a .cmd script, insteaad of JS

![image](https://github.com/Unitech/pm2/assets/98429152/2012e4c8-1eec-4d27-bdcf-ce4ccc902a47)

**Comment by DanielPrecise** [comment]
> Any luck on this?
> 
> --Interpreter did nothing for me and pm2 is being useless with n8n as its a .cmd script, insteaad of JS
> 
> ![image](https://github.com/Unitech/pm2/assets/98429152/2012e4c8-1eec-4d27-bdcf-ce4ccc902a47)

Use nodeJS wrapper like this:
```
const { exec } = require("child_process");
const path = require("path");

const batPath = path.join(__dirname, "<YOUR_BATCH_FILE.bat>");

const subprocess = exec(`"${batPath}"`, { windowsHide: true });

subprocess.stdout.pipe(process.stdout);
subprocess.stderr.pipe(process.stderr);

```

Than use this wrapper in pm2, That works for me.
