### ISSUE TITLE
pm2 is trying to load from an old file location

### ISSUE THREAD

**Issue by lukepighetti** [Unitech/pm2#3564]
I had a binary named **pigeond** that was initialized by

```
pm2 start ~/pigeon/src/pigeond
pm2 startup
```

PM2 managed this beautifully until

```
rm -r ~/pigeon/
pm2 delete pigeond
```

```
pm2 start ~/pigeon-new/binaries/linux/pigeond
pm2 startup
reboot
pm2 status    # pigeond – errored
pm2 log
```

```
PM2        | [2018-03-24 01:41:03] PM2 log: SIGTERM timeout      : 1600
PM2        | [2018-03-24 01:41:03] PM2 log: ===============================================================================
PM2        | [2018-03-24 01:41:03] PM2 log: Starting execution sequence in -fork mode- for app name:pigeond id:0
PM2        | [2018-03-24 01:41:03] PM2 log: App name:pigeond id:0 online
PM2        | [2018-03-24 01:41:03] PM2 error: Error: spawn /root/Pigeoncoin/src/pigeond ENOENT
PM2        |     at exports._errnoException (util.js:870:11)
PM2        |     at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
PM2        |     at onErrorNT (internal/child_process.js:344:16)
PM2        |     at nextTickCallbackWith2Args (node.js:441:9)
PM2        |     at process._tickDomainCallback (node.js:396:17)
PM2        | [2018-03-24 01:42:48] PM2 log: Stopping app:pigeond id:0
PM2        | [2018-03-24 01:42:48] PM2 error: app=pigeond id=0 does not have a pid
PM2        | [2018-03-24 01:42:55] PM2 log: Starting execution sequence in -fork mode- for app name:pigeond id:0
PM2        | [2018-03-24 01:42:55] PM2 log: App name:pigeond id:0 online
```

It appears that PM2 is trying to run this binary from the old location. Any suggestions on how to solve this?

**Comment by lukepighetti** [comment]
got it.

```
pm2 start ~/pigeon-new/binaries/linux/pigeond
pm2 startup
```

I forgot: 

```
pm2 save
```

Feel free to close
