### ISSUE TITLE
No logs - No errors --  What is wrong?

### ISSUE THREAD

**Issue by aguyinmontreal** [Unitech/pm2#3566]
When I try to run the following JSON:

  {
"apps" : [{
    "name"        : "monstache3",
    "script"      : "~/productionFolder/backend_and_frontend_Final/monstache/linux-amd64/monstache",
    "cwd"         : "~/productionFolder/backend_and_frontend_Final/monstache/linux-amd64/",
    "autorestart" : false,
    "args"        : "-f ~/productionFolder/backend_and_frontend_Final/monstache/config.toml",
    "error_file"      : "~/logs/err-2.log",
    "out_file"        : "~/logs/out-2.log",

  }]
}

Monstache is the excutable file available here https://github.com/rwynn/monstache/releases

**My error files and log files are completely empty!**

In `~/.pm2/pm2.log `  I see:

[2018-03-25 19:52:14] PM2 log: Starting execution sequence in -fork mode- for app name:monstache3 id:1
[2018-03-25 19:52:14] PM2 error: Error: EACCES: permission denied, open '/home/emilio/.pm2/pids/monstache3-1.pid'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at /usr/lib/node_modules/pm2/lib/God/ForkMode.js:240:12
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at next (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:958:16
    at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:172:13)
    at emitOne (events.js:116:13)
    at WriteStream.emit (events.js:211:7)
    at fs.open (fs.js:2162:10)
[2018-03-25 19:52:14] PM2 log: App name:monstache3 id:1 online
[2018-03-25 19:52:14] PM2 error: Error: spawn /home/emilio/productionFolder/backend_and_frontend_Final/monstache/linux-amd64/monstache ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by wallet77** [comment]
Hi @aguyinmontreal 

It seems the app doesn't even start, this is why you don't have logs.
Could you check permissions on file /home/emilio/.pm2/pids/monstache3-1.pid ?
There is a strange EACCES error, maybe you don't run pm2 with good user.

**Comment by aguyinmontreal** [comment]
@wallet77 Thank you! I will check the permissions today.

Two extra pieces of info:

1.Running pm2 with sudo doesn't help this issue
2.Running a node .js script works perfectly fine with or without sudo

**Comment by aguyinmontreal** [comment]
First error (EACCESS) error was fixed with `sudo chown <username>:<username> /home/<username>/.pm2/pids/monstache3-1.pid`
The issue was that I was trying to run the script as <username> but the socket was owned by root. The socket file needs the same owner as the script.

For the second error (the ENOENT), **no resolution in sight**.  The file exist and all permissions were given. It looks the same as this issue: https://github.com/dawson-org/dawson-cli/issues/209

**Comment by aguyinmontreal** [comment]
Ok I finally found the fix.

The fix for the second error (the ENOENT) is a little complicated.

I first found the fix to create a new user (see https://github.com/Unitech/pm2/issues/756#issuecomment-58369110 ), this fix worked while the files stayed with the old user, however as soon as I recreated the git repository in the current user's directory, the issue came back.

The fix is in 3 steps:
1.The paths specified in the JSON file cannot start with `~/` .  `/home/<username>/` needs to be used instead.
2.All single **directory** and **file** in **each of the paths** used by the JSON file must be owned by **root** In `home/<username>/a/b/c/d/binary`, `a`,`b`,`c`, `d` and `binary` must be owned by the **root** instead of **<username>**.
3.The "script" file (if executable) must have execution privilege. (In `home/<username>/a/b/c/d/binary`, `binary` must have execution privilege.)

If this is not sufficient (it was sufficient for my new user, but not for my old user):
4.Every single action must be **sudoed** from the start of file creation (delete the files and start over and  `sudo` everything):  `sudo git clone` instead of `git clone`, `sudo git init` instead of `git init`, `sudo git pull` instead of `git pull`, `sudo pm2 start` instead of `pm2 start`, `sudo pm2 kill` instead of `pm2 kill`, etc.

**Comment by wallet77** [comment]
Can we close this issue ?

**Comment by aguyinmontreal** [comment]
@wallet77   Yes, you can. However, there is definitely a bug in pm2 with permissions.
