### ISSUE TITLE
cron_restart doesn't work with non-js code

### ISSUE THREAD

**Issue by DmitryRomanenko** [Unitech/pm2#3616]
## What's going wrong?
When `exec_interpreter` is not `node`, cron_restart doesn't work (except first run on startup).  
It looks like it tries to execute script as JS code.

Logs:
```
/home/dmitry/.pm2/logs/worker-error-0.log last 15 lines:
0|worker   | /home/dmitry/test/time.php:1
0|worker   | (function (exports, require, module, __filename, __dirname) { <?php
0|worker   |                                                               ^
0|worker   | 
0|worker   | SyntaxError: Unexpected token <
0|worker   |     at createScript (vm.js:80:10)
0|worker   |     at Object.runInThisContext (vm.js:139:10)
0|worker   |     at Module._compile (module.js:616:28)
0|worker   |     at Object.Module._extensions..js (module.js:663:10)
0|worker   |     at Module.load (module.js:565:32)
0|worker   |     at tryModuleLoad (module.js:505:12)
0|worker   |     at Function.Module._load (module.js:497:3)
0|worker   |     at /usr/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
0|worker   |     at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
0|worker   |     at next (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
```
I have tried it in both `fork` and `cluster` modes.

## How could we reproduce this issue?
pm2.json
```json
{
    "apps" : [
        {
            "name": "worker",
            "cwd": "/home/dmitry/test",
            "script": "./time.php",
            "cron_restart": "*/2 * * * *",
            "autorestart": false,
            "exec_interpreter": "php",
            "vizion": false
        }
    ]
}
```

time.php:
```php
<?php
file_put_contents('time.log', date('c') . "\n", FILE_APPEND);
sleep(1);
```

## Supporting information
```
$ pm2 report
===============================================================================
--- PM2 REPORT (Wed Apr 18 2018 10:35:32 GMT+0300 (EEST)) ---------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.2
node version         : 8.11.1
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : dmitry
uid                  : 1001
gid                  : 1001
uptime               : 1101min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.2
node version         : 8.11.1
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : dmitry
uid                  : 1001
gid                  : 1001
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
cpus nb              : 8
freemem              : 464355328
totalmem             : 16685420544
home                 : /home/dmitry
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬────────┬──────────┐
│ App name │ id │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user   │ watching │
├──────────┼────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼────────┼──────────┤
│ worker   │ 0  │ fork │ 0   │ stopped │ 0       │ 0      │ 0%  │ 0 B    │ dmitry │ disabled │
└──────────┴────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬────────┬──────────┐
│ App name │ id │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user   │ watching │
├──────────┼────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼────────┼──────────┤
│ worker   │ 0  │ fork │ 0   │ stopped │ 0       │ 0      │ 0%  │ 0 B    │ dmitry │ disabled │
└──────────┴────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

**Comment by SurenAt93** [comment]
+ The same problem. 
When config file looks like this one:

```
{
  "apps" : [
    ...
    {
      "name": "Microservice №04",
      "script": "microservice_04.js",
      "cron_restart": "*/5 * * * * *"
    }
  ]
}
```

Everything works fine. (Fine - means, script is run every 5 seconds)

In case of this one:

{
  "apps" : [
    ...
   {
      "name": "Microservice №04",
      "script": "microservice_04.sh", // This bash file contains a single line -> node microservice_04.js
      "exec_interpreter": "bash",
      "cron_restart": "*/5 * * * * *"
    }
  ]
}
```

Works just one time.

**Comment by ChaosTong** [comment]
try to use pm2@3.2.2 version , use 3.2.4 i got this problem same
