### ISSUE TITLE
"Error: spawn pgrep ENOENT" when stopping running app

### ISSUE THREAD

**Issue by douira** [Unitech/pm2#3622]
## What's going wrong?
PM2 displays this log message:
```
Stopping app:mongod id:0
{ Error: spawn pgrep ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:178:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn pgrep',
  path: 'pgrep',
  spawnargs: [ '-P', 1144 ] }
```
which looks like an error. The pid in the last line changes to match the pid of the process being stopped. What is happening here? Is this normal? Is there something I chould/can do to fix it?  
`pgrep` is a command on my system and returns usage info for example when called.
## How could we reproduce this issue?
This seems to happeny any time pm2 stops an app if it is already running (in reload, restart and stop). This seems to apply to both the app `mongod` and the node express app `webserver`. 
```
===============================================================================
--- PM2 REPORT (Fri Apr 20 2018 20:13:08 GMT+0200 (CEST)) ---------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.2
node version         : 9.11.1
node path            : /Users/douira/.nvm/versions/node/v9.11.1/lib/node_modules/pm2/bin/pm2
argv                 : /Users/douira/.nvm/versions/node/v9.11.1/bin/node,/Users/douira/.nvm/versions/node/v9.11.1/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : douira
uid                  : 501
gid                  : 20
uptime               : 178min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.2
node version         : 9.11.1
node path            : /Users/douira/.nvm/versions/node/v9.11.1/bin/pm2
argv                 : /Users/douira/.nvm/versions/node/v9.11.1/bin/node,/Users/douira/.nvm/versions/node/v9.11.1/bin/pm2,report
argv0                : node
user                 : douira
uid                  : 501
gid                  : 20
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : darwin
type                 : Darwin
cpus                 : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
cpus nb              : 8
freemem              : 6631690240
totalmem             : 17179869184
home                 : /Users/douira
===============================================================================
--- PM2 list -----------------------------------------------
┌───────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬────────┬─────────────┬──────────┐
│ App name  │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem    │ user        │ watching │
├───────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼────────┼─────────────┼──────────┤
│ mongod    │ 0  │ fork │ 1144 │ online │ 0       │ 2h     │ 0%  │ 0 B    │ douira      │ disabled │
│ webserver │ 1  │ fork │ 7727 │ online │ 7       │ 2m     │ 0%  │ 0 B    │ douira      │ disabled │
└───────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴────────┴─────────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/Users/douira/.pm2/pm2.log last 20 lines:
PM2        | [2018-04-20 19:53:56] PM2 log: pid=4961 msg=process killed
PM2        | [2018-04-20 19:53:56] PM2 log: Starting execution sequence in -fork mode- for app name:webserver id:1
PM2        | [2018-04-20 19:53:57] PM2 log: App name:webserver id:1 online
PM2        | [2018-04-20 19:56:10] PM2 log: App [webserver] with id [1] and pid [5086], exited with code [1] via signal [SIGINT]
PM2        | [2018-04-20 19:56:10] PM2 log: Starting execution sequence in -fork mode- for app name:webserver id:1
PM2        | [2018-04-20 19:56:11] PM2 log: App name:webserver id:1 online
PM2        | [2018-04-20 19:58:59] PM2 log: Process 1 in a stopped status, starting it
PM2        | [2018-04-20 19:58:59] PM2 log: Stopping app:webserver id:1
PM2        | [2018-04-20 19:58:59] PM2 error: Error: spawn pgrep ENOENT
PM2        | [2018-04-20 19:58:59] PM2 log: App [webserver] with id [1] and pid [5441], exited with code [0] via signal [SIGINT]
PM2        | [2018-04-20 19:59:00] PM2 log: pid=5441 msg=process killed
PM2        | [2018-04-20 19:59:00] PM2 log: Starting execution sequence in -fork mode- for app name:webserver id:1
PM2        | [2018-04-20 19:59:00] PM2 log: App name:webserver id:1 online
PM2        | [2018-04-20 20:10:34] PM2 log: Process 1 in a stopped status, starting it
PM2        | [2018-04-20 20:10:34] PM2 log: Stopping app:webserver id:1
PM2        | [2018-04-20 20:10:34] PM2 error: Error: spawn pgrep ENOENT
PM2        | [2018-04-20 20:10:34] PM2 log: App [webserver] with id [1] and pid [5925], exited with code [0] via signal [SIGINT]
PM2        | [2018-04-20 20:10:34] PM2 log: pid=5925 msg=process killed
PM2        | [2018-04-20 20:10:34] PM2 log: Starting execution sequence in -fork mode- for app name:webserver id:1
PM2        | [2018-04-20 20:10:35] PM2 log: App name:webserver id:1 online

```

**Comment by douira** [comment]
Not stale, just old
