### ISSUE TITLE
PM2  did not restart process after ENOMEM error

### ISSUE THREAD

**Issue by BrianHVB** [Unitech/pm2#3623]
## What's going wrong?
Yesterday, my very stable Node.js application shutdown due to an ENOMEM error. The machine was under a very light load when this occurred. PM2 did not restart the process or attempt to restart the process. I had to manually restart the process when I noticed it was down.

PM2 Version: 2.10.1

## How could we reproduce this issue?

I have tried to reproduce the issue, but have not been able to trigger an out of memory error.

## Supporting information

Log Files:

```
[2018-04-10 07:12:17] PM2 log: Starting execution sequence in -fork mode- for app name:market_watch_server id:2
[2018-04-10 07:12:17] PM2 log: App name:market_watch_server id:2 online
[2018-04-20 22:59:30] PM2 log: App [marketDataHarvester] with id [0] and pid [1797], exited with code [0] via signal [SIGKILL]
[2018-04-20 22:59:30] PM2 log: Starting execution sequence in -fork mode- for app name:marketDataHarvester id:0
[2018-04-20 22:59:30] PM2 error: Trace: { Error: spawn ENOMEM
    at _errnoException (util.js:1003:13)
    at ChildProcess.spawn (internal/child_process.js:330:11)
    at exports.spawn (child_process.js:499:9)
    at /usr/lib/node_modules/pm2/lib/God/ForkMode.js:100:20
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at next (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:958:16
    at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:172:13)
    at WriteStream.emit (events.js:127:13)
    at WriteStream.emit (domain.js:439:23) errno: 'ENOMEM', code: 'ENOMEM', syscall: 'spawn' }
    at Object.God.logAndGenerateError (/usr/lib/node_modules/pm2/lib/God/Methods.js:36:15)
    at /usr/lib/node_modules/pm2/lib/God/ForkMode.js:108:13
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at next (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:958:16
    at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:172:13)
    at WriteStream.emit (events.js:127:13)
    at WriteStream.emit (domain.js:439:23)
    at fs.open (fs.js:2229:10)
    at FSReqWrap.oncomplete (fs.js:153:20)
[2018-04-21 06:08:03] PM2 error: Process with pid 1797 already exists
[2018-04-21 06:10:51] PM2 error: Process with pid 1797 already exists
[2018-04-21 06:11:58] PM2 log: Stopping app:market_watch_server id:2
[2018-04-21 06:11:58] PM2 log: ===============================================================================
[2018-04-21 06:11:58] PM2 log: --- PM2 global error caught ---------------------------------------------------
[2018-04-21 06:11:58] PM2 log: Time                 : Sat Apr 21 2018 06:11:58 GMT+0000 (UTC)
[2018-04-21 06:11:58] PM2 error: spawn ENOMEM
[2018-04-21 06:11:58] PM2 error: Error: spawn ENOMEM
    at _errnoException (util.js:1003:13)
    at ChildProcess.spawn (internal/child_process.js:330:11)
    at exports.spawn (child_process.js:499:9)
    at /usr/lib/node_modules/pm2/lib/TreeKill.js:33:14
    at buildProcessTree (/usr/lib/node_modules/pm2/lib/TreeKill.js:79:12)
    at module.exports (/usr/lib/node_modules/pm2/lib/TreeKill.js:32:5)
    at Object.God.killProcess (/usr/lib/node_modules/pm2/lib/God/Methods.js:223:7)
    at Object.God.stopProcessId (/usr/lib/node_modules/pm2/lib/God/ActionMethods.js:287:9)
    at God.deleteProcessId (/usr/lib/node_modules/pm2/lib/God/ActionMethods.js:339:9)
    at Server.onmessage (/usr/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:105:6)
[2018-04-21 06:11:58] PM2 log: ===============================================================================
[2018-04-21 06:11:58] PM2 error: [PM2] Resurrecting PM2
[2018-04-21 06:13:37] PM2 log: Stopping app:market_watch_server id:2
[2018-04-21 06:13:37] PM2 log: App [market_watch_server] with id [2] and pid [7860], exited with code [0] via signal [SIGINT]
[2018-04-21 06:13:37] PM2 log: pid=7860 msg=process killed
[2018-04-21 06:13:37] PM2 log: PM2 successfully stopped
[2018-04-21 06:13:53] PM2 log: ===============================================================================
[2018-04-21 06:13:53] PM2 log: --- New PM2 Daemon started ----------------------------------------------------
[2018-04-21 06:13:53] PM2 log: Time                 : Sat Apr 21 2018 06:13:53 GMT+0000 (UTC)
[2018-04-21 06:13:53] PM2 log: PM2 version          : 2.10.1
[2018-04-21 06:13:53] PM2 log: Node.js version      : 9.6.1
[2018-04-21 06:13:53] PM2 log: Current arch         : x64
[2018-04-21 06:13:53] PM2 log: PM2 home             : /home/admin/.pm2
[2018-04-21 06:13:53] PM2 log: PM2 PID file         : /home/admin/.pm2/pm2.pid
[2018-04-21 06:13:53] PM2 log: RPC socket file      : /home/admin/.pm2/rpc.sock
[2018-04-21 06:13:53] PM2 log: BUS socket file      : /home/admin/.pm2/pub.sock
[2018-04-21 06:13:53] PM2 log: Application log path : /home/admin/.pm2/logs
[2018-04-21 06:13:53] PM2 log: Process dump file    : /home/admin/.pm2/dump.pm2
[2018-04-21 06:13:53] PM2 log: Concurrent actions   : 2
[2018-04-21 06:13:53] PM2 log: SIGTERM timeout      : 1600
[2018-04-21 06:13:53] PM2 log: ===============================================================================

```

Please run the following command (available on PM2 >= 2.6)

```
--- PM2 REPORT (Sat Apr 21 2018 06:31:27 GMT+0000 (UTC)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.1
node version         : 9.6.1
node path            : undefined
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : admin
uid                  : 1000
gid                  : 27
uptime               : 17min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.1
node version         : 9.6.1
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : admin
uid                  : 1000
gid                  : 27
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
cpus nb              : 1
freemem              : 1188208640
totalmem             : 2097389568
home                 : /home/admin
===============================================================================
--- PM2 list -----------------------------------------------
┌─────────────────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬───────────┬───────┬──────────┐
│ App name            │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ user  │ watching │
├─────────────────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼───────┼──────────┤
│ marketDataHarvester │ 0  │ fork │ 1799 │ online │ 0       │ 17m    │ 0%  │ 43.1 MB   │ admin │ disabled │
│ market_watch_server │ 1  │ fork │ 1804 │ online │ 0       │ 17m    │ 0%  │ 38.0 MB   │ admin │ disabled │
└─────────────────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴───────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌─────────────────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬───────────┬───────┬──────────┐
│ App name            │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ user  │ watching │
├─────────────────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼───────┼──────────┤
│ marketDataHarvester │ 0  │ fork │ 1799 │ online │ 0       │ 17m    │ 0%  │ 43.1 MB   │ admin │ disabled │
│ market_watch_server │ 1  │ fork │ 1804 │ online │ 0       │ 17m    │ 0%  │ 38.0 MB   │ admin │ disabled │
└─────────────────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴───────┴──────────┘

```

**Comment by blairvanderhoof** [comment]
This happened to me last night. Does anyone know how to at least get this to recover on its own? It didn't restart the process. I had to reboot so the upstart process kicked in.
