### ISSUE TITLE
Cluster mode not working on Windows

### ISSUE THREAD

**Issue by DavidPMacNeil** [Unitech/pm2#3627]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?

PM2 Cluster mode does not work

## How could we reproduce this issue?

Launch an application using PM2 with clustered mode enabled on Windows (10).

## Supporting information

```
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\src\project\node_modules\pm2\lib\ProcessContainer.js:17:20)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
[2018-04-25 11:23:56] PM2 log: App name:APPid:0 disconnected
[2018-04-25 11:23:56] PM2 log: App [APP] with id [0] and pid [19248], exited with code [1] via signal [SIGINT]
[2018-04-25 11:23:56] PM2 log: Script C:\src\projects\dist\server\server\app.js had too many unstable restarts (16). Stopped. "errored"
[2018-04-25 11:23:56] PM2 log: App name:APP id:1 online
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\src\project\node_modules\pm2\lib\ProcessContainer.js:17:20)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
[2018-04-25 11:23:56] PM2 log: App name:APPid:1 disconnected
[2018-04-25 11:23:56] PM2 log: App [APP] with id [1] and pid [18544], exited with code [1] via signal [SIGINT]
[2018-04-25 11:23:56] PM2 log: Script C:\src\project\dist\server\server\app.js had too many unstable restarts (16). Stopped. "errored"

```

Report Info:

```
===============================================================================
--- PM2 REPORT (Wed Apr 25 2018 11:31:31 GMT-0300 (Atlantic Daylight Time)) ---
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.2
node version         : 8.9.1
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\src\project\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 19min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.2
node version         : 8.9.1
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\dmacneil\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : node
user                 : dmacneil
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
cpus nb              : 8
freemem              : 8223498240
totalmem             : 17039532032
home                 : C:\Users\dmacneil
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬─────────┬─────┬─────────┬─────────┬────────┬─────┬────────┬─────────┬──────────┐
│ App name │ id │ mode    │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user    │ watching │
├──────────┼────┼─────────┼─────┼─────────┼─────────┼────────┼─────┼────────┼─────────┼──────────┤
│ APP      │ 0  │ cluster │ 0   │ errored │ 15      │ 0      │ 0%  │ 0 B    │ dmacneil  │ disabled │
│ APP      │ 1  │ cluster │ 0   │ errored │ 15      │ 0      │ 0%  │ 0 B    │ dmacneil  │ disabled │
└──────────┴────┴─────────┴─────┴─────────┴─────────┴────────┴─────┴────────┴─────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬─────────┬─────┬─────────┬─────────┬────────┬─────┬────────┬─────────┬──────────┐
│ App name │ id │ mode    │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user    │ watching │
├──────────┼────┼─────────┼─────┼─────────┼─────────┼────────┼─────┼────────┼─────────┼──────────┤
│ APP      │ 0  │ cluster │ 0   │ errored │ 15      │ 0      │ 0%  │ 0 B    │ dmacneil  │ disabled │
│ APP      │ 1  │ cluster │ 0   │ errored │ 15      │ 0      │ 0%  │ 0 B    │ dmacneil  │ disabled │
└──────────┴────┴─────────┴─────┴─────────┴─────────┴────────┴─────┴────────┴─────────┴──────────┘
```

**Comment by codingbeans** [comment]
For those who have the same problem with pm2 API and are looking for workaround:
Replace

```javascript
import pm2 from 'pm2';
pm2.start({ script: app.js, instance: 4 });
```

with

```javascript
import { exec } from 'child_process';
exec('pm2 start -i 4 app.js');
```
