### ISSUE TITLE
Big memory usage even after closing all the processes

### ISSUE THREAD

**Issue by mihai1voicescu** [Unitech/pm2#3630]
## What's going wrong?
PM2 went up to 2.5 GB of memory. Even after stopping all the processes the memory usage did not go down.
Note that the real memory usage is much greater than the one registered in the snapshots.
`ps -aux` output:
```
node      2974  0.5 22.6 2509348 1423356 ?     Ssl  Apr13 102:29 PM2 v2.10.2: God Daemon (/var/lib/node/.pm2)
```
`top` output:
```
2974 node      20   0 2509348 1.365g   7644 S   0.0 22.7 102:31.92 PM2 v2.10.2: Go
```
SNAPSHOTS:
[PM2-SNAPSHOT.zip](https://github.com/Unitech/pm2/files/1950606/PM2-SNAPSHOT.zip)

## Supporting information

Note that App names have been obscured for privacy reasons and the debugger was attached after the memory usage to take the snapshots.

```
===============================================================================
--- PM2 REPORT (Thu Apr 26 2018 09:40:38 GMT+0000 (UTC)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.2
node version         : 8.11.1
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : node
uid                  : 5020
gid                  : 5020
uptime               : 18690min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.2
node version         : 8.11.1
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : node
uid                  : 5020
gid                  : 5020
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
cpus nb              : 12
freemem              : 0
totalmem             : 6442450944
home                 : /var/lib/node
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────────────┬────┬──────┬───────┬─────────┬─────────┬────────┬─────┬────────┬──────┬──────────┐
│ App name         │ id │ mode │ pid   │ status  │ restart │ uptime │ cpu │ mem    │ user │ watching │
├──────────────────┼────┼──────┼───────┼─────────┼─────────┼────────┼─────┼────────┼──────┼──────────┤
│ XXX │ 10 │ fork │ 0     │ stopped │ 1293    │ 0      │ 0%  │ 0 B    │ node │ disabled │
│ XXX │ 0  │ fork │ 0     │ stopped │ 6       │ 0      │ 0%  │ 0 B    │ node │ disabled │
│ XXX │ 14 │ fork │ 0     │ stopped │ 1293    │ 0      │ 0%  │ 0 B    │ node │ disabled │
│ XXX │ 5  │ fork │ 0     │ stopped │ 5       │ 0      │ 0%  │ 0 B    │ node │ disabled │
│ XXX │ 6  │ fork │ 0     │ stopped │ 5       │ 0      │ 0%  │ 0 B    │ node │ disabled │
│ XXX │ 2  │ fork │ 0     │ stopped │ 6       │ 0      │ 0%  │ 0 B    │ node │ disabled │
│ XXX │ 8  │ fork │ 29957 │ stopped │ 48      │ 0      │ 0%  │ 0 B    │ node │ disabled │
│ XXX │ 9  │ fork │ 29963 │ stopped │ 48      │ 0      │ 0%  │ 0 B    │ node │ disabled │
│ XXX │ 18 │ fork │ 0     │ stopped │ 7       │ 0      │ 0%  │ 0 B    │ node │ disabled │
│ XXX │ 3  │ fork │ 0     │ stopped │ 6       │ 0      │ 0%  │ 0 B    │ node │ disabled │
│ XXX │ 7  │ fork │ 0     │ stopped │ 6       │ 0      │ 0%  │ 0 B    │ node │ disabled │
│ XXX │ 12 │ fork │ 0     │ stopped │ 1293    │ 0      │ 0%  │ 0 B    │ node │ disabled │
│ XXX │ 15 │ fork │ 0     │ stopped │ 1293    │ 0      │ 0%  │ 0 B    │ node │ disabled │
│ XXX │ 13 │ fork │ 0     │ stopped │ 6       │ 0      │ 0%  │ 0 B    │ node │ disabled │
│ XXX │ 17 │ fork │ 30027 │ stopped │ 48      │ 0      │ 0%  │ 0 B    │ node │ disabled │
│ XXX │ 16 │ fork │ 30021 │ stopped │ 48      │ 0      │ 0%  │ 0 B    │ node │ disabled │
│ XXX │ 4  │ fork │ 0     │ stopped │ 1296    │ 0      │ 0%  │ 0 B    │ node │ disabled │
│ XXX │ 1  │ fork │ 0     │ stopped │ 6       │ 0      │ 0%  │ 0 B    │ node │ disabled │
│ XXX │ 11 │ fork │ 0     │ stopped │ 1293    │ 0      │ 0%  │ 0 B    │ node │ disabled │
└──────────────────┴────┴──────┴───────┴─────────┴─────────┴────────┴─────┴────────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/var/lib/node/.pm2/pm2.log last 20 lines:
PM2        | [2018-04-22 10:21:10] PM2 log: App [presence_0] with id [15] and pid [14991], exited with code [1] via signal [SIGINT]
PM2        | [2018-04-22 10:21:10] PM2 log: App [ung_0] with id [11] and pid [15001], exited with code [1] via signal [SIGINT]
PM2        | [2018-04-22 10:21:11] PM2 log: Starting execution sequence in -fork mode- for app name:sshareservice_0 id:4
PM2        | [2018-04-22 10:21:11] PM2 log: App name:sshareservice_0 id:4 online
PM2        | [2018-04-22 10:21:11] PM2 log: Starting execution sequence in -fork mode- for app name:hammer_0 id:8
PM2        | [2018-04-22 10:21:11] PM2 error: Error: Unknown system error -122: Unknown system error -122, write
PM2        |     at Object.fs.writeSync (fs.js:735:20)
PM2        |     at Object.fs.writeFileSync (fs.js:1309:24)
PM2        |     at /usr/lib/node_modules/pm2/lib/God/ForkMode.js:240:12
PM2        |     at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
PM2        |     at next (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
PM2        |     at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:958:16
PM2        |     at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:172:13)
PM2        |     at emitOne (events.js:116:13)
PM2        |     at WriteStream.emit (events.js:211:7)
PM2        |     at fs.open (fs.js:2162:10)
PM2        | [2018-04-22 10:21:11] PM2 log: App name:hammer_0 id:8 online
PM2        | [2018-04-22 10:21:11] PM2 log: Starting exeDebugger listening on ws://127.0.0.1:9229/7f58503c-698d-44b1-8057-e1f0b3cc70ab
PM2        | For help see https://nodejs.org/en/docs/inspector
PM2        | Debugger attached.
```

**Comment by eran10** [comment]
+1

**Comment by ermazi** [comment]
+1
