### ISSUE TITLE
pm2 not resurrecting after reboot - Linux Mint, pm2 2.10.3

### ISSUE THREAD

**Issue by jcollum** [Unitech/pm2#3635]
## What's going wrong?

After executing the startup script, saving a process (shell script) and restarting the process that I saved is not running but the God daemon is.  

The process that is running is in `/usr/local/`; is that the problem? All users have read and execute rights to the directory the process is in. 

## How could we reproduce this issue?
See supporting info below. 

## Supporting information

```
$ cat /etc/lsb-release 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.2
DISTRIB_CODENAME=sonya
DISTRIB_DESCRIPTION="Linux Mint 18.2 Sonya"

~ @ Mint-Miner (justin) 
$ pm2 --version
2.10.3

~ @ Mint-Miner (justin) 
$ node --version
v8.9.0

~ @ Mint-Miner (justin) 
$ npm --version
5.5.1

$ pm2 startup 
[PM2] Init System found: systemd
[PM2] To setup the Startup Script, copy/paste the following command:
sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u justin --hp /home/justin

~ @ Mint-Miner (justin) 
$ sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u justin --hp /home/justin
[PM2] Init System found: systemd
Platform systemd
Template
[Unit]
Description=PM2 process manager
Documentation=https://pm2.keymetrics.io/
After=network.target

[Service]
Type=forking
User=justin
LimitNOFILE=infinity
…

~ @ Mint-Miner (justin) 
$  pm2 ls
┌──────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬──────────┬───────────┬──────────┐
│ App name │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem      │ user      │ watching │
├──────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼──────────┼───────────┼──────────┤
│ eth      │ 0  │ fork │ 1883 │ online │ 0       │ 77s    │ 0%  │ 2.9 MB   │ undefined │ disabled │
└──────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴──────────┴───────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app

~ @ Mint-Miner (justin) 
$ pm2 save
[PM2] Saving current process list...
[PM2] Successfully saved in /opt/.pm2/dump.pm2

$ sudo reboot 

$ ssh justin@192.168.x.x

$ sudo ps aux | grep pm2
[sudo] password for justin: 
justin    1733  0.2  0.5 918448 42904 ?        Ssl  12:36   0:00 PM2 v2.10.3: God Daemon (/opt/.pm2)
justin    1748  0.0  0.0  14228  1028 pts/0    S+   12:38   0:00 grep pm2

$ pm2 report
[PM2] Spawning PM2 daemon with pm2_home=/opt/.pm2
[PM2] PM2 Successfully daemonized
===============================================================================
--- PM2 REPORT (Sat Apr 28 2018 12:36:12 GMT-0700 (PDT)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.3
node version         : 8.9.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : justin
uid                  : 1000
gid                  : 1000
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.3
node version         : 8.9.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : justin
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz
cpus nb              : 2
freemem              : 7716679680
totalmem             : 8370266112
home                 : /home/justin
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app

$ sudo pm2 ls
[PM2] Spawning PM2 daemon with pm2_home=/home/justin/.pm2
[PM2] PM2 Successfully daemonized
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app


```

**Comment by jcollum** [comment]
This is after starting up the process. Process has been up for 5 days. 

<details> 
[{"instance_var":"NODE_APP_INSTANCE","exec_mode":"fork_mode","watch":false,"treekill":true,"autorestart":true,"automation":true,"pmx":true,"vizion":true,"name":"eth","node_args":[],"pm_exec_path":"/home/justin/mining/eth.sh","env":{"PM2_USAGE":"CLI","_":"/usr/bin/pm2","XDG_RUNTIME_DIR":"/run/user/1000","ANDROID_NDK_HOME":"/usr/local/opt/android-ndk","SSH_CONNECTION":"192.168.1.8 57947 192.168.1.6 22","LOGNAME":"justin","HOME":"/home/justin","SHLVL":"1","PS1":"\\n\\w @ \\h (\\u) \\n$ ","NODE_ENV":"development","LANG":"en_US.UTF-8","EDITOR":"/usr/bin/nano","PWD":"/home/justin","BLOCKSIZE":"1k","PATH":"/usr/local/git/bin:/sw/bin:/usr/local/bin:/usr/local:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/bin","MAIL":"/var/mail/justin","PM2_HOME":"/opt/.pm2","MAVEN_HOME":"/usr/local/opt/maven","USER":"justin","ANT_HOME":"/usr/local/opt/ant","SSH_TTY":"/dev/pts/0","GRADLE_HOME":"/usr/local/opt/gradle","SSH_CLIENT":"192.168.1.8 57947 22","XDG_SESSION_COOKIE":"6a4e92f40a6e4d7e8a650c6c44d79ab2-1524943402.514850-684517716","SHELL":"/bin/bash","TERM":"xterm-256color","ANDROID_HOME":"/Users/jcollum/Library/Android/sdk","XDG_SESSION_ID":"1","eth":{}},"pm_cwd":"/home/justin","exec_interpreter":"bash","pm_out_log_path":"/opt/.pm2/logs/eth-out-0.log","pm_err_log_path":"/opt/.pm2/logs/eth-error-0.log","pm_pid_path":"/opt/.pm2/pids/eth-0.pid","km_link":false,"vizion_running":false,"NODE_APP_INSTANCE":0,"PM2_USAGE":"CLI","_":"/usr/bin/pm2","XDG_RUNTIME_DIR":"/run/user/1000","ANDROID_NDK_HOME":"/usr/local/opt/android-ndk","SSH_CONNECTION":"192.168.1.8 57947 192.168.1.6 22","LOGNAME":"justin","HOME":"/home/justin","SHLVL":"1","PS1":"\\n\\w @ \\h (\\u) \\n$ ","NODE_ENV":"development","LANG":"en_US.UTF-8","EDITOR":"/usr/bin/nano","PWD":"/home/justin","BLOCKSIZE":"1k","PATH":"/usr/local/git/bin:/sw/bin:/usr/local/bin:/usr/local:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/bin","MAIL":"/var/mail/justin","PM2_HOME":"/opt/.pm2","MAVEN_HOME":"/usr/local/opt/maven","USER":"justin","ANT_HOME":"/usr/local/opt/ant","SSH_TTY":"/dev/pts/0","GRADLE_HOME":"/usr/local/opt/gradle","SSH_CLIENT":"192.168.1.8 57947 22","XDG_SESSION_COOKIE":"6a4e92f40a6e4d7e8a650c6c44d79ab2-1524943402.514850-684517716","SHELL":"/bin/bash","TERM":"xterm-256color","ANDROID_HOME":"/Users/jcollum/Library/Android/sdk","XDG_SESSION_ID":"1","status":"online","pm_uptime":1524943565142,"axm_actions":[],"axm_monitor":{},"axm_options":{},"axm_dynamic":{},"created_at":1524943474368,"restart_time":0,"unstable_restarts":0,"versioning":null}]

</details>

**Comment by colebowl** [comment]
@jcollum - Can you search the `~/.pm2/pm2/log` for "PM2 error: Cancelling versioning data parsing" and see if it lines up with the times the process does not restart? 

I ask as I've been pulling my hair out all week trying to figure out why the same thing has been happening one one of our applications. I just happen to be running the same Node and pm2 versions as you. 

TIA

**Comment by jcollum** [comment]
@colebowl 

```
~ @ Mint 
$ cat ~/.pm2/pm2.log| grep "versioning data" 

~ @ Mint 
$
```

No hits.

**Comment by jcollum** [comment]
@wallet77  here you go: 

```
[{"instance_var":"NODE_APP_INSTANCE","exec_mode":"fork_mode","watch":false,"treekill":true,"autorestart":true,"automation":true,"pmx":true,"vizion":true,"name":"eth","node_args":[],"pm_exec_path":"/home/justin/mining/eth.sh","env":{"PM2_USAGE":"CLI","_":"/usr/bin/pm2","XDG_RUNTIME_DIR":"/run/user/1000","ANDROID_NDK_HOME":"/usr/local/opt/android-ndk","SSH_CONNECTION":"192.168.1.8 57947 192.168.1.6 22","LOGNAME":"justin","HOME":"/home/justin","SHLVL":"1","PS1":"\\n\\w @ \\h (\\u) \\n$ ","NODE_ENV":"development","LANG":"en_US.UTF-8","EDITOR":"/usr/bin/nano","PWD":"/home/justin","BLOCKSIZE":"1k","PATH":"/usr/local/git/bin:/sw/bin:/usr/local/bin:/usr/local:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/bin","MAIL":"/var/mail/justin","PM2_HOME":"/opt/.pm2","MAVEN_HOME":"/usr/local/opt/maven","USER":"justin","ANT_HOME":"/usr/local/opt/ant","SSH_TTY":"/dev/pts/0","GRADLE_HOME":"/usr/local/opt/gradle","SSH_CLIENT":"192.168.1.8 57947 22","XDG_SESSION_COOKIE":"6a4e92f40a6e4d7e8a650c6c44d79ab2-1524943402.514850-684517716","SHELL":"/bin/bash","TERM":"xterm-256color","ANDROID_HOME":"/Users/jcollum/Library/Android/sdk","XDG_SESSION_ID":"1","eth":{}},"pm_cwd":"/home/justin","exec_interpreter":"bash","pm_out_log_path":"/opt/.pm2/logs/eth-out-0.log","pm_err_log_path":"/opt/.pm2/logs/eth-error-0.log","pm_pid_path":"/opt/.pm2/pids/eth-0.pid","km_link":false,"vizion_running":false,"NODE_APP_INSTANCE":0,"PM2_USAGE":"CLI","_":"/usr/bin/pm2","XDG_RUNTIME_DIR":"/run/user/1000","ANDROID_NDK_HOME":"/usr/local/opt/android-ndk","SSH_CONNECTION":"192.168.1.8 57947 192.168.1.6 22","LOGNAME":"justin","HOME":"/home/justin","SHLVL":"1","PS1":"\\n\\w @ \\h (\\u) \\n$ ","NODE_ENV":"development","LANG":"en_US.UTF-8","EDITOR":"/usr/bin/nano","PWD":"/home/justin","BLOCKSIZE":"1k","PATH":"/usr/local/git/bin:/sw/bin:/usr/local/bin:/usr/local:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/bin","MAIL":"/var/mail/justin","PM2_HOME":"/opt/.pm2","MAVEN_HOME":"/usr/local/opt/maven","USER":"justin","ANT_HOME":"/usr/local/opt/ant","SSH_TTY":"/dev/pts/0","GRADLE_HOME":"/usr/local/opt/gradle","SSH_CLIENT":"192.168.1.8 57947 22","XDG_SESSION_COOKIE":"6a4e92f40a6e4d7e8a650c6c44d79ab2-1524943402.514850-684517716","SHELL":"/bin/bash","TERM":"xterm-256color","ANDROID_HOME":"/Users/jcollum/Library/Android/sdk","XDG_SESSION_ID":"1","status":"online","pm_uptime":1524943565142,"axm_actions":[],"axm_monitor":{},"axm_options":{},"axm_dynamic":{},"created_at":1524943474368,"restart_time":0,"unstable_restarts":0,"versioning":null}]

```

**Comment by wallet77** [comment]
@jcollum 

I'm not sure, but there is no "username" property in this dump file. And we have many issues concerning this.
Maybe it can help if you add it manually or if you generate a new dump file.

**Comment by jcollum** [comment]
I just checked on a different Mint machine I have (the other one isn't available right now) and this was the result: 

```
media@mediaCube ~ $ env | grep USER
USER=media
media@mediaCube ~ $ env | grep USERNAME

```

Is it possible that Mint doesn't set USERNAME?

**Comment by Unitech** [comment]
On machine reboot, can you do a `pm2 ls` instead of `sudo pm2 ls` because running under sudo will create a different pm2 instance

USER is not [issue](https://github.com/Unitech/pm2/blob/development/lib/Common.js#L698)

Can you also run `sudo systemctl status pm2-justin` and give us the output

**Comment by jcollum** [comment]
Finally coming back to this. 

After reboot: 

```$ pm2 ls
[PM2] Spawning PM2 daemon with pm2_home=/opt/.pm2
[PM2] PM2 Successfully daemonized
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```


```
$ sudo systemctl status pm2-justin
[sudo] password for justin: 
● pm2-justin.service - PM2 process manager
   Loaded: loaded (/etc/systemd/system/pm2-justin.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2018-10-20 15:24:50 PDT; 13min ago
     Docs: https://pm2.keymetrics.io/
  Process: 1051 ExecStart=/usr/lib/node_modules/pm2/bin/pm2 resurrect (code=exited, status=1/FAILURE)

Oct 20 15:24:50 Mint-Miner pm2[1051]:     at Object.fs.openSync (fs.js:646:18)
Oct 20 15:24:50 Mint-Miner pm2[1051]:     at module.exports.Client.launchDaemon (/usr/lib/node_modules/pm2/lib/Client.js:219:14)
Oct 20 15:24:50 Mint-Miner pm2[1051]:     at /usr/lib/node_modules/pm2/lib/Client.js:103:10
Oct 20 15:24:50 Mint-Miner pm2[1051]:     at /usr/lib/node_modules/pm2/lib/Client.js:307:14
Oct 20 15:24:50 Mint-Miner pm2[1051]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
Oct 20 15:24:50 Mint-Miner pm2[1051]:     at process._tickCallback (internal/process/next_tick.js:180:9)
Oct 20 15:24:50 Mint-Miner systemd[1]: pm2-justin.service: Control process exited, code=exited status=1
Oct 20 15:24:50 Mint-Miner systemd[1]: Failed to start PM2 process manager.
Oct 20 15:24:50 Mint-Miner systemd[1]: pm2-justin.service: Unit entered failed state.
Oct 20 15:24:50 Mint-Miner systemd[1]: pm2-justin.service: Failed with result 'exit-code'.
```

**Comment by jcollum** [comment]
I have upgraded to the current version: 

```
~ @ Mint-Miner (justin) 
$ sudo env PATH=$PATH:/home/justin/.nvm/versions/node/v8.2.1/bin /home/justin/.nvm/versions/node/v8.2.1/lib/node_modules/pm2/bin/pm2 startup systemd -u justin --hp /home/justin
[sudo] password for justin: 
[PM2] Init System found: systemd
Platform systemd
Template
[Unit]
Description=PM2 process manager
Documentation=https://pm2.keymetrics.io/
After=network.target

[Service]
Type=forking
User=justin
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
Environment=PATH=/home/justin/.nvm/versions/node/v8.2.1/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
Environment=PM2_HOME=/home/justin/.pm2
PIDFile=/home/justin/.pm2/pm2.pid

ExecStart=/home/justin/.nvm/versions/node/v8.2.1/lib/node_modules/pm2/bin/pm2 resurrect
ExecReload=/home/justin/.nvm/versions/node/v8.2.1/lib/node_modules/pm2/bin/pm2 reload all
ExecStop=/home/justin/.nvm/versions/node/v8.2.1/lib/node_modules/pm2/bin/pm2 kill

[Install]
WantedBy=multi-user.target

Target path
/etc/systemd/system/pm2-justin.service
Command list
[ 'systemctl enable pm2-justin' ]
[PM2] Writing init configuration in /etc/systemd/system/pm2-justin.service
[PM2] Making script booting at startup...
[PM2] [-] Executing: systemctl enable pm2-justin...
[PM2] [v] Command successfully executed.
+---------------------------------------+
[PM2] Freeze a process list on reboot via:
$ pm2 save

[PM2] Remove init script via:
$ pm2 unstartup systemd

~ @ Mint-Miner (justin) 
$ pm2 save 
[PM2] Saving current process list...
[PM2] Successfully saved in /opt/.pm2/dump.pm2

~ @ Mint-Miner (justin) 
$ pm2 ls 
┌──────────┬────┬─────────┬──────┬──────┬────────┬─────────┬────────┬─────┬──────────┬────────┬──────────┐
│ App name │ id │ version │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem      │ user   │ watching │
├──────────┼────┼─────────┼──────┼──────┼────────┼─────────┼────────┼─────┼──────────┼────────┼──────────┤
│ eth      │ 0  │ N/A     │ fork │ 2073 │ online │ 0       │ 5s     │ 0%  │ 3.0 MB   │ justin │ disabled │
└──────────┴────┴─────────┴──────┴──────┴────────┴─────────┴────────┴─────┴──────────┴────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app

~ @ Mint-Miner (justin) 
$ pm2 --version 
3.2.2


```

When I reboot and log back in this is what happens: 

```
Welcome to Linux Mint 18.2 Sonya (GNU/Linux 4.8.0-53-generic x86_64)

 * Documentation:  https://www.linuxmint.com
Last login: Sun Oct 21 14:30:55 2018 from 192.168.1.8

~ @ Mint-Miner (justin) 
$ pm2 ls
[PM2] Spawning PM2 daemon with pm2_home=/opt/.pm2
[PM2] PM2 Successfully daemonized
```

So it's not working still.
