### ISSUE TITLE
Hide/disable unhandledRejection logging

### ISSUE THREAD

**Issue by sidelux** [Unitech/pm2#3644]
## What's going wrong?

I handle unhandledRejection manually, print it on console is an annoying duplicate i think.
Example:
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: ETELEGRAM: 429 Too Many Requests: retry after 67
    at request.then.resp (/home/fenix/lootBot/node_modules/node-telegram-bot-api/src/telegram.js:280:15)
    at tryCatcher (/home/fenix/lootBot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/fenix/lootBot/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/fenix/lootBot/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/fenix/lootBot/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/fenix/lootBot/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/fenix/lootBot/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/fenix/lootBot/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/fenix/lootBot/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

## How could we reproduce this issue?

I imagine it happens with all type of unhandledRejection.

There is a way to disable this type of messages?
Thanks!

**Comment by wallet77** [comment]
Hi @sidelux 

Indeed, pmx catch all unhandledRejection and print this kind of message.
Maybe we can add an option to disable this catch.

**Comment by sidelux** [comment]
@wallet77, it could be very useful ;)

**Comment by wallet77** [comment]
I think we can achieve this in version 3.0.0 with the new apm and after https://github.com/Unitech/pm2/issues/3692 is done.

**Comment by wallet77** [comment]
Done : https://github.com/keymetrics/pm2-io-apm/issues/127

**Comment by cloudrac3r** [comment]
Could you briefly explain how I could set the option to disable these unhandledRejection logs, please?

**Comment by wallet77** [comment]
Yes sorry, you can try :

```
pmx.init({
  catchExceptions: false
})
```

With latest pm2 (development branch) in ecosystem file :
{
  "io": {
    "conf": {
      "catchExceptions": false
    }
  }
}

**Comment by mkubenka** [comment]
Confirming - setting `io.conf.catchExceptions` does not disable PMX exception handler.

As temporary workaround I have disabled `pmx` and `automation` in ecosystem file.

**Comment by bradennapier** [comment]
Super.Annoying.

**Comment by bradennapier** [comment]
workarounds dont wokr in cluster mode - pretty annoying....
