### ISSUE TITLE
PM2 cannot start up with ./node_modules/.bin/pm2 start server -i max --attach

### ISSUE THREAD

**Issue by ardenkahza** [Unitech/pm2#3658]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?
I use yarn install this project,
And run it on docker,
It occurred an error,
The message is under the following,

How should I do?
I am a newbie with node.

```
/usr/src/app/node_modules/.bin/pm2:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

## How could we reproduce this issue?
```
{
  "name": "publisher",
  "version": "1.0.13-hotfix.3",
  "description": "",
  "private": true,
  "scripts": {
    "dev": "npm run clean-cache && node server",
    "clean-cache": "rimraf -rf ./node_modules/.cache",
    "build": "next build",
    "start": "NODE_ENV=production node ./node_modules/.bin/pm2 start server -i max --attach"
  },
  "dependencies": {
    "axios": "^0.16.2",
    "babel-plugin-inline-dotenv": "^1.1.1",
    "babel-plugin-transform-inline-environment-variables": "^0.2.0",
    "babel-polyfill": "^6.26.0",
    "body-parser": "^1.17.2",
    "classnames": "^2.2.5",
    "compression": "^1.7.1",
    "dotenv": "^4.0.0",
    "express": "4.16.2",
    "helmet": "3.9.0",
    "http-status": "^1.0.1",
    "lodash": "^4.17.4",
    "lru-cache": "^4.1.1",
    "next": "4.2.3",
    "next-routes": "1.2.0",
    "pm2": "2.9.3",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-helmet": "^5.2.0",
    "react-jss": "^8.2.1",
    "request": "^2.83.0",
    "request-promise-native": "^1.0.5",
    "sitemap": "^1.13.0"
  },
  "devDependencies": {
    "babel-plugin-inline-react-svg": "^0.5.2",
    "rimraf": "^2.6.2"
  }
}
```
## Supporting information
node v8.11.1
pm2 2.9.3
yarn 1.6.0
os win7 64bits ver.

Please run the following command (available on PM2 >= 2.6)
NODE_ENV=production node ./node_modules/.bin/pm2 start server -i max --attach
```
$ pm2 report
```

**Comment by BishopCodes** [comment]
Try running pm2 init and then change your start to the following

./node_modules/.bin/pm2-runtime start ecosystem.config.js --env production

**Comment by radarsu** [comment]
I have quite similar error when doing `pm2 start my-process` that should launch `ng serve`.
```
  - name:          my-process
    cwd:            ../..
    script:         ./node_modules/.bin/ng
    args:           serve
    env:
      DEBUG_COLORS: 1
```
Error:
```
(...)\node_modules\.bin\ng:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
               ^^^^^^^
SyntaxError: missing ) after argument list
```
