### ISSUE TITLE
PM2 not started after crash - hard coded /bin/pm2 Windows

### ISSUE THREAD

**Issue by mgryniak** [Unitech/pm2#3668]
## What's going wrong?

Sometimes PM2 crash.  Based on the Windows logs looks like it can be related to antivirus software actions. 

Auto restart PM2 is not possible because execution path is hard coded to  `/bin/pm2`  

## How could we reproduce this issue?

Unfortunately not possible reproduce. Information based on the logs.

### Environment

```
OS: Windows Server 2016
Node: v8.9.4  
pm2: 2.9.3
```

### Log
```
2018-05-13 15:32:57: ===============================================================================
2018-05-13 15:32:58: --- PM2 global error caught ---------------------------------------------------
2018-05-13 15:32:58: Time                 : Sun May 13 2018 15:32:58 GMT+0000 (Coordinated Universal Time)
2018-05-13 15:32:58: spawn EPERM
2018-05-13 15:32:59: Error: spawn EPERM
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Object.win (C:\Program Files\MyApp\PM2\node_modules\pidusage\lib\stats.js:128:16)
    at Object.<anonymous> (C:\Program Files\MyApp\PM2\node_modules\pidusage\index.js:13:28)
    at Object.exports.stat (C:\Program Files\MyApp\PM2\node_modules\pidusage\index.js:37:20)
    at computeMonitor (C:\Program Files\MyApp\PM2\node_modules\pm2\lib\God\ActionMethods.js:59:18)
    at C:\Program Files\MyApp\PM2\node_modules\pm2\node_modules\async\dist\async.js:3096:16
    at replenish (C:\Program Files\MyApp\PM2\node_modules\pm2\node_modules\async\dist\async.js:998:17)
    at iterateeCallback (C:\Program Files\MyApp\PM2\node_modules\pm2\node_modules\async\dist\async.js:983:17)
2018-05-13 15:32:59: ===============================================================================
2018-05-13 15:32:59: [PM2] Resurrecting PM2
module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\Windows\system32\bin\pm2'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
2018-05-13 15:33:00: PM2 successfully forked
```
## My analyze

First topic for me is why pm2 after fatal error try to find pm2 execution file in directory `'C:\Windows\system32\bin\pm2'`

pm2 is installed in directory `C:\Program Files\MyApp\PM2\node_modules\.bin` and this path is added to system path. I can execute from command line pm2

PM2_HOME is set in my situation on the `C:\Program Files\MyApp\PM2`.

I did the small analyze of the pm2 files and in file:
[Daemon.js](https://github.com/Unitech/pm2/blob/0d009364d58b3f3cfe2c6fa40606c441ba73d5e9/lib/Daemon.js#L47) you can find section: 

`	var path = cst.IS_WINDOWS ? process.cwd() + '/bin/pm2' : process.env['_'];`

Why for the Windows, path is hard coded to `process.cwd() + '/bin/pm2'`?
In my situation correct value will be:

`var path = cst.IS_WINDOWS ? cst.PM2_HOME + 'node_modules\.bin\pm2' : process.env['_'];`

I think best way is add variable like cst.PM2_BIN because then user can set this path manually related to the system environment configuration.

`var path = cst.IS_WINDOWS ? cst.PM2_BIN + '/pm2' : process.env['_'];`

Thank you for your help.

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/issues/3793
