### ISSUE TITLE
PM2 cluster mode errored but it is working fine in fork mode

### ISSUE THREAD

**Issue by katturajam** [Unitech/pm2#3680]
`$ pm2 start server.js --name=ma-api-service -i 0 --node-args=  --max-old-space-size=256`

```
$ pm2 report
===============================================================================
--- PM2 REPORT (Wed May 23 2018 09:16:32 GMT+0000 (UTC)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.4
node version         : 8.9.4
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : xxxxx
uid                  : 501
gid                  : 501
uptime               : 1567min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.4
node version         : 8.9.4
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : xxxxx
uid                  : 501
gid                  : 501
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
cpus nb              : 2
freemem              : 1905864704
totalmem             : 8064356352
home                 : /home/xxxxx
===============================================================================
--- PM2 list -----------------------------------------------
┌─────────────────────┬────┬─────────┬─────┬─────────┬─────────┬────────┬─────┬────────┬───────────┬──────────┐
│ App name            │ id │ mode    │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user      │ watching │
├─────────────────────┼────┼─────────┼─────┼─────────┼─────────┼────────┼─────┼────────┼───────────┼──────────┤
│ ma-api-service-v2.0 │ 8  │ cluster │ 0   │ errored │ 45      │ 0      │ 0%  │ 0 B    │ xxxxx │ disabled │
│ ma-api-service-v2.0 │ 9  │ cluster │ 0   │ errored │ 45      │ 0      │ 0%  │ 0 B    │ xxxxx │ disabled │
└─────────────────────┴────┴─────────┴─────┴─────────┴─────────┴────────┴─────┴────────┴───────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌─────────────────────┬────┬─────────┬─────┬─────────┬─────────┬────────┬─────┬────────┬───────────┬──────────┐
│ App name            │ id │ mode    │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user      │ watching │
├─────────────────────┼────┼─────────┼─────┼─────────┼─────────┼────────┼─────┼────────┼───────────┼──────────┤
│ ma-api-service-v2.0 │ 8  │ cluster │ 0   │ errored │ 45      │ 0      │ 0%  │ 0 B    │ xxxxx │ disabled │
│ ma-api-service-v2.0 │ 9  │ cluster │ 0   │ errored │ 45      │ 0      │ 0%  │ 0 B    │ xxxxx │ disabled │
└─────────────────────┴────┴─────────┴─────┴─────────┴─────────┴────────┴─────┴────────┴───────────┴──────────┘
```

```
/home/xxxxx/.pm2/pm2.log last 15 lines:
PM2        |
PM2        | Error: ENOENT: no such file or directory, uv_cwd
PM2        |     at Object.resolve (path.js:1177:25)
PM2        |     at Function.Module._resolveLookupPaths (module.js:418:17)
PM2        |     at Function.Module._resolveFilename (module.js:532:20)
PM2        |     at Function.Module._load (module.js:468:25)
PM2        |     at Module.require (module.js:587:17)
PM2        |     at require (internal/module.js:11:18)
PM2        |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:13:15)
PM2        |     at Module._compile (module.js:643:30)
PM2        |     at Object.Module._extensions..js (module.js:654:10)
PM2        |     at Module.load (module.js:556:32)
PM2        | [2018-05-23 09:16:22] PM2 log: App name:ma-api-service-v2.0 id:9 disconnected
PM2        | [2018-05-23 09:16:22] PM2 log: App [ma-api-service-v2.0] with id [9] and pid [13669], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-23 09:16:22] PM2 log: Script /var/opt/TTT/apps/xxxxx/src/SISMA/server/ma-api-service/v2.0/server.js had too many unstable restarts (16). Stopped. "errored"
```

**Comment by katturajam** [comment]
#2057
