### ISSUE TITLE
PM2 SyntaxError when our server is restarted: Unexpected token (

### ISSUE THREAD

**Issue by emipc** [Unitech/pm2#3696]
## What's going wrong?
Every time our server running pm2 in cluster mode is restarted, we are getting this error in a loop:

```
SyntaxError: Unexpected token (
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
at next (/usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:958:16
at WriteStream.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Utility.js:172:13)
```

We had to run `pm2 update` to fix it (it's the second time we have to do that).

## How could we reproduce this issue?

No sure, we just get this error when our server is restarted.

## Supporting information

```
$ pm2 report
```
```
===============================================================================
--- PM2 REPORT (Tue Jun 05 2018 08:10:03 GMT+0000 (UTC)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.1
node version         : 8.0.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : abcde
uid                  : 500
gid                  : 500
uptime               : 1021min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.1
node version         : 8.0.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : abcde
uid                  : 500
gid                  : 500
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2420 0 @ 1.90GHz
cpus nb              : 4
freemem              : 527515648
totalmem             : 6442450944
home                 : /var/www/vhosts/abcde.com
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────┬───────────┬─────────────┬──────────┐
│ App name         │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user        │ watching │
├──────────────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────┼───────────┼─────────────┼──────────┤
│ api              │ 2  │ cluster │ 25998 │ online │ 0       │ 17h    │ 0%  │ 52.2 MB   │ abcde 	  │ enabled  │
│ api              │ 3  │ cluster │ 25999 │ online │ 0       │ 17h    │ 0%  │ 53.2 MB   │ abcde	  │ enabled  │
│ abcde-pagaments  │ 1  │ fork    │ 25992 │ online │ 0       │ 17h    │ 0%  │ 41.9 MB   │ abcde 	  │ enabled  │
│ abcde-secretaria │ 0  │ fork    │ 25986 │ online │ 0       │ 17h    │ 0%  │ 38.7 MB   │ abcde 	  │ enabled  │
└──────────────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────┴───────────┴─────────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/var/www/vhosts/abcde.com/.pm2/pm2.log last 20 lines:
PM2        | [2018-06-04 15:08:07] PM2 log: BUS socket file      : /var/www/vhosts/abcde.com/.pm2/pub.sock
PM2        | [2018-06-04 15:08:07] PM2 log: Application log path : /var/www/vhosts/abcde.com/.pm2/logs
PM2        | [2018-06-04 15:08:07] PM2 log: Process dump file    : /var/www/vhosts/abcde.com/.pm2/dump.pm2
PM2        | [2018-06-04 15:08:07] PM2 log: Concurrent actions   : 2
PM2        | [2018-06-04 15:08:07] PM2 log: SIGTERM timeout      : 1600
PM2        | [2018-06-04 15:08:07] PM2 log: ===============================================================================
PM2        | [2018-06-04 15:08:07] PM2 log: [Watch] Start watching abcde-secretaria
PM2        | [2018-06-04 15:08:07] PM2 log: Starting execution sequence in -fork mode- for app name:abcde-secretaria id:0
PM2        | [2018-06-04 15:08:07] PM2 log: [Watch] Start watching abcde-pagaments
PM2        | [2018-06-04 15:08:07] PM2 log: Starting execution sequence in -fork mode- for app name:abcde-pagaments id:1
PM2        | [2018-06-04 15:08:08] PM2 log: App name:abcde-secretaria id:0 online
PM2        | [2018-06-04 15:08:08] PM2 log: App name:abcde-pagaments id:1 online
PM2        | [2018-06-04 15:08:08] PM2 log: [Watch] Start watching api
PM2        | [2018-06-04 15:08:08] PM2 log: Starting execution sequence in -cluster mode- for app name:api id:2
PM2        | [2018-06-04 15:08:08] PM2 log: [Watch] Start watching api
PM2        | [2018-06-04 15:08:08] PM2 log: Starting execution sequence in -cluster mode- for app name:api id:3
PM2        | [2018-06-04 15:08:08] PM2 log: App name:api id:2 online
PM2        | [2018-06-04 15:08:08] PM2 error: (node:25976) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
PM2        | [2018-06-04 15:08:08] PM2 log: App name:api id:3 online
PM2        | [2018-06-04 15:08:08] PM2 error: (node:25976) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
```

**Comment by AlexVyi** [comment]
Thanks for that.Never would have thought of updating pm2.I waisted one hour. :)) Had the same issue today with pm2 v 3.2.2 on Ubuntu 18.04 LTS node v 10.13.

**Comment by AlexVyi** [comment]
One more detail.For me the unexpected token was <

**Comment by Shubhankardubey** [comment]
for me the unexpected token is :

**Comment by anthlasserre** [comment]
Another one found a solution?
