### ISSUE TITLE
spawn ENOENT error after reboot

### ISSUE THREAD

**Issue by digitalnature** [Unitech/pm2#3715]
After restart, PM2 lists the process with a "errored" status, and process logs are empty.

This is the error message from the pm2.log file:

````
 PM2 error: Error: spawn /var/www/test-server/main ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

````

I'm running this inside a virtual machine, the OS is Ubuntu Server 14.
I think this happens because the process file is located within a Windows folder that is mounted in the virtual OS after PM2 starts (`/var/www/`).

I tried starting it with the delay command  ` pm2 start main --restart-delay 5000`
but the same error appears. Could it be that delay is not honored after restart?

PM2 report:

```
===============================================================================
--- PM2 REPORT (Fri Jun 15 2018 12:00:57 GMT+0300 (EEST)) ---------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.4
node version         : 10.2.1
node path            : /usr/local/lib/node_modules/pm2/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
uptime               : 1min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.4
node version         : 10.2.1
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz
cpus nb              : 1
freemem              : 3773952000
totalmem             : 4144721920
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌──────┬──────┬─────────┬───┬─────┬────────┐
│ Name │ mode │ status  │ ↺ │ cpu │ memory │
├──────┼──────┼─────────┼───┼─────┼────────┤
│ main │ fork │ errored │ 0 │ 0%  │ 0 B    │
└──────┴──────┴─────────┴───┴─────┴────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────┬──────┬─────────┬───┬─────┬────────┐
│ Name │ mode │ status  │ ↺ │ cpu │ memory │
├──────┼──────┼─────────┼───┼─────┼────────┤
│ main │ fork │ errored │ 0 │ 0%  │ 0 B    │
└──────┴──────┴─────────┴───┴─────┴────────┘

```

**Comment by digitalnature** [comment]
No.
Is your app located in a shared folder that is mounted on boot?

**Comment by alexandrule** [comment]
@digitalnature I spent about 3 hours to figure out where is the problem. In my case, I have dependency with ImageMagick in the application.
I just installed this dependency and the issue was solved.
In my opinion, try to check all your dependencies and maybe you will solve this issue.
Good luck!
