### ISSUE TITLE
Would moment Deprecation error cause a restart?

### ISSUE THREAD

**Issue by SteveyPugs** [Unitech/pm2#3727]
## What's going wrong? 

PM2 restarted, we don't know why

## How could we reproduce this issue?

I see this in the error log. Would this cause it?

```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 11/25/2016, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (repo\node_modules\moment\moment.js:320:94)
    at configFromString (repo\node_modules\moment\moment.js:2178:11)
    at configFromInput (repo\node_modules\moment\moment.js:2547:9)
    at prepareConfig (repo\node_modules\moment\moment.js:2530:9)
    at createFromConfig (repo\node_modules\moment\moment.js:2497:40)
    at createLocalOrUTC (repo\node_modules\moment\moment.js:2584:12)
    at createLocal (repo\node_modules\moment\moment.js:2588:12)
    at hooks (repo\node_modules\moment\moment.js:16:25)
    at repo\tasks\email-reports.js:704:23
    at arrayEach (repo\node_modules\lodash\index.js:1289:13)
    at Function.<anonymous> (repo\node_modules\lodash\index.js:3345:13)
    at null.<anonymous> (repo\tasks\email-reports.js:703:15)
    at tryCatcher (repo\node_modules\sequelize\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (repo\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (repo\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (repo\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (repo\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (repo\node_modules\sequelize\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (repo\node_modules\sequelize\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (repo\node_modules\sequelize\node_modules\bluebird\js\release\async.js:17:14)

```

**Comment by wallet77** [comment]
Hi @SteveyPugs 

If you have an error (and this is the case here) in your code : yes it will restart your application !

**Comment by SteveyPugs** [comment]
Its a warning though not an error. http://momentjs.com/guides/#/warnings/js-date/

**Comment by wallet77** [comment]
If you have a stack trace maybe it throws an exception, catched by pm2 and so it restarts your application.
