### ISSUE TITLE
Unable to start process

### ISSUE THREAD

**Issue by mpdeglau** [Unitech/pm2#3763]
## What's going wrong?
I'm trying to use PM2 to launch node-red, which is installed globally.  I can successfully start node-red directly, but when I try using PM2, the daemon process starts.  But it hangs after Done is printed in the shell.
## Supporting information
2018-07-04T11:31:08.811Z] PM2 log: ===============================================================================
[2018-07-04T11:31:11.745Z] PM2 log: --- New PM2 Daemon started ----------------------------------------------------
[2018-07-04T11:31:11.746Z] PM2 log: Time                 : Wed Jul 04 2018 11:31:11 GMT-0900 (Pacific Standard Time)
[2018-07-04T11:31:11.746Z] PM2 log: PM2 version          : 3.0.0
[2018-07-04T11:31:11.746Z] PM2 log: Node.js version      : 10.5.0
[2018-07-04T11:31:11.746Z] PM2 log: Current arch         : x64
[2018-07-04T11:31:11.746Z] PM2 log: PM2 home             : /root/.pm2
[2018-07-04T11:31:11.747Z] PM2 log: PM2 PID file         : /root/.pm2/pm2.pid
[2018-07-04T11:31:11.747Z] PM2 log: RPC socket file      : /root/.pm2/rpc.sock
[2018-07-04T11:31:11.747Z] PM2 log: BUS socket file      : /root/.pm2/pub.sock
[2018-07-04T11:31:11.747Z] PM2 log: Application log path : /root/.pm2/logs
[2018-07-04T11:31:11.747Z] PM2 log: Process dump file    : /root/.pm2/dump.pm2
[2018-07-04T11:31:11.747Z] PM2 log: Concurrent actions   : 2
[2018-07-04T11:31:11.748Z] PM2 log: SIGTERM timeout      : 1600
[2018-07-04T11:31:11.748Z] PM2 log: ===============================================================================
[2018-07-04T11:31:12.608Z] PM2 log: Starting execution sequence in -fork mode- for app name:node-red id:0
[2018-07-04T11:31:12.614Z] PM2 log: App name:node-red id:0 online
[2018-07-04T11:31:12.649Z] PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
[2018-07-04T11:31:12.652Z] PM2 error: Error caught while calling pidusage
[2018-07-04T11:31:12.653Z] PM2 error: Error: No maching pid found
[2018-07-04T11:31:12.654Z] PM2 log: ===============================================================================
[2018-07-04T11:31:12.654Z] PM2 log: --- PM2 global error caught ---------------------------------------------------
[2018-07-04T11:31:12.654Z] PM2 log: Time                 : Wed Jul 04 2018 11:31:12 GMT-0900 (Pacific Standard Time)
[2018-07-04T11:31:12.659Z] PM2 error: Cannot read property '16804' of undefined
[2018-07-04T11:31:12.659Z] PM2 error: TypeError: Cannot read property '16804' of undefined
    at /usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:79:30
    at Array.map (<anonymous>)
    at retPidUsage (/usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:68:29)
    at /usr/local/lib/node_modules/pm2/node_modules/pidusage/lib/stats.js:75:14
    at each (/usr/local/lib/node_modules/pm2/node_modules/pidusage/lib/helpers/parallel.js:24:15)
    at /usr/local/lib/node_modules/pm2/node_modules/pidusage/lib/helpers/parallel.js:32:9
    at /usr/local/lib/node_modules/pm2/node_modules/pidusage/lib/procfile.js:60:14
    at FSReqWrap.oncomplete (fs.js:145:20)
[2018-07-04T11:31:12.659Z] PM2 log: ===============================================================================
[2018-07-04T11:31:12.659Z] PM2 error: [PM2] Resurrecting PM2
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '/root/.pm2/undefined'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
[2018-07-04T11:31:12.737Z] PM2 log: PM2 successfully forked

```
$ pm2 report
```
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
===============================================================================
--- PM2 REPORT (Wed Jul 04 2018 11:33:35 GMT-0900 (Pacific Standard Time)) ----
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.0.0
node version         : 10.5.0
node path            : undefined
argv                 : /usr/local/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : mike
uid                  : 0
gid                  : 0
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.0.0
node version         : 10.5.0
node path            : undefined
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : mike
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : freebsd
type                 : FreeBSD
cpus                 : Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz
cpus nb              : 4
freemem              : 306044928
totalmem             : 16921944064
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app

**Comment by Unitech** [comment]
Thanks for reporting this issue, appreciated.
Issue has been posted on the related project.

It seems that pidusage (cpu/mem monitoring) has some issue with freebsd

**Comment by Unitech** [comment]
Issue fixed, just reinstall pm2 it should update the pidusage module.

```bash
$ npm install pm2 -g
$ pm2 update
```
