### ISSUE TITLE
Error caught by domain: and Error: spawn ENOMEM 

### ISSUE THREAD

**Issue by rishabhdixit** [Unitech/pm2#3782]
## What's going wrong?
Everything was running smooth for so long but suddenly today all pm2 processes/jobs were stopped (pm2 ls was showing empty list). Processes didn't restart [we have 4 GB of RAM available on our server]
Can someone help letting us know whats the root cause and how can we prevent this issue from happening in future again.
Thanks

## Supporting information
Following are the pm2.log file errors: 

2018-07-06 22:15:20: [PM2][WORKER] Error caught by domain:
Error: spawn ENOMEM
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Object.exports.execFile (child_process.js:212:15)
    at exports.exec (child_process.js:142:18)
    at getUrl (/usr/lib/node_modules/pm2/node_modules/vizion/lib/git.js:18:5)
    at fn (/usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:746:34)
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:1213:16
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:166:37
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:706:43
2018-07-06 22:15:50: [PM2][WORKER] Error caught by domain:
Error: spawn ENOMEM
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Object.exports.execFile (child_process.js:212:15)
    at exports.exec (child_process.js:142:18)
    at getUrl (/usr/lib/node_modules/pm2/node_modules/vizion/lib/git.js:18:5)
    at fn (/usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:746:34)
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:1213:16
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:166:37
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:706:43
2018-07-06 22:16:15: App [FallbackTransactions] with id [215] and pid [20344], exited with code [0] via signal [SIGABRT]
2018-07-06 22:16:15: Starting execution sequence in -fork mode- for app name:FallbackTransactions id:215
2018-07-06 22:16:15: App name:FallbackTransactions id:215 online
2018-07-06 22:16:20: [PM2][WORKER] Error caught by domain:
Error: spawn ENOMEM
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Object.exports.execFile (child_process.js:212:15)
    at exports.exec (child_process.js:142:18)
    at getUrl (/usr/lib/node_modules/pm2/node_modules/vizion/lib/git.js:18:5)
    at fn (/usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:746:34)
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:1213:16
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:166:37
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:706:43
2018-07-07 22:15:21: [PM2][WORKER] Error caught by domain:
Error: spawn ENOMEM
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Object.exports.execFile (child_process.js:212:15)
    at exports.exec (child_process.js:142:18)
    at getUrl (/usr/lib/node_modules/pm2/node_modules/vizion/lib/git.js:18:5)
    at fn (/usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:746:34)
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:1213:16
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:166:37
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:706:43
2018-07-07 22:15:25: App [MEMBERSON] with id [217] and pid [16315], exited with code [0] via signal [SIGABRT]
2018-07-07 22:15:25: Starting execution sequence in -fork mode- for app name:MEMBERSON id:217
2018-07-07 22:15:25: Trace: { Error: spawn ENOMEM
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at /usr/lib/node_modules/pm2/lib/God/ForkMode.js:94:20
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at next (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:958:16
    at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:172:13)
    at emitOne (events.js:116:13)
    at WriteStream.emit (events.js:211:7) code: 'ENOMEM', errno: 'ENOMEM', syscall: 'spawn' }
    at Object.God.logAndGenerateError (/usr/lib/node_modules/pm2/lib/God/Methods.js:36:15)
    at /usr/lib/node_modules/pm2/lib/God/ForkMode.js:102:13
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at next (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:958:16
    at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:172:13)
    at emitOne (events.js:116:13)
    at WriteStream.emit (events.js:211:7)
    at fs.open (fs.js:2153:10)
    at FSReqWrap.oncomplete (fs.js:135:15)
2018-07-08 22:15:23: [PM2][WORKER] Error caught by domain:
Error: spawn ENOMEM
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Object.exports.execFile (child_process.js:212:15)
    at exports.exec (child_process.js:142:18)
    at getPrevNext (/usr/lib/node_modules/pm2/node_modules/vizion/lib/git.js:93:5)
    at fn (/usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:746:34)
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:1213:16
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:166:37
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:706:43
2018-07-09 02:25:47: Stopping app:ROBSPRICEPROMO id:216
2018-07-09 02:25:47: Process with pid 16315 already exists
2018-07-09 02:25:47: Stopping app:UpdateDailyPrices id:218
2018-07-09 02:25:47: App [ROBSPRICEPROMO] with id [216] and pid [16308], exited with code [0] via signal [SIGINT]
2018-07-09 02:25:47: App [UpdateDailyPrices] with id [218] and pid [16362], exited with code [0] via signal [SIGINT]
2018-07-09 02:25:47: pid=16308 msg=process killed
2018-07-09 02:25:47: Starting execution sequence in -fork mode- for app name:ROBSPRICEPROMO id:216
2018-07-09 02:25:47: App name:ROBSPRICEPROMO id:216 online
2018-07-09 02:25:47: Stopping app:UpdateDailyPromotions id:219
2018-07-09 02:25:47: pid=16362 msg=process killed
2018-07-09 02:25:47: Starting execution sequence in -fork mode- for app name:UpdateDailyPrices id:218
2018-07-09 02:25:47: App name:UpdateDailyPrices id:218 online
2018-07-09 02:25:47: Stopping app:UpdateDailyInventory id:220
2018-07-09 02:25:47: pid=16375 msg=failed to kill - retrying in 100ms
2018-07-09 02:25:47: App [UpdateDailyPromotions] with id [219] and pid [16375], exited with code [0] via signal [SIGINT]
2018-07-09 02:25:47: pid=16405 msg=failed to kill - retrying in 100ms
2018-07-09 02:25:47: pid=16375 msg=process killed
2018-07-09 02:25:47: Starting execution sequence in -fork mode- for app name:UpdateDailyPromotions id:219
2018-07-09 02:25:47: App [UpdateDailyInventory] with id [220] and pid [16405], exited with code [0] via signal [SIGINT]
2018-07-09 02:25:47: App name:UpdateDailyPromotions id:219 online
2018-07-09 02:25:47: pid=16405 msg=process killed
2018-07-09 02:25:47: Starting execution sequence in -fork mode- for app name:UpdateDailyInventory id:220
2018-07-09 02:25:47: App name:UpdateDailyInventory id:220 online
2018-07-09 22:15:23: [PM2][WORKER] Error caught by domain:
Error: spawn ENOMEM
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Object.exports.execFile (child_process.js:212:15)
    at exports.exec (child_process.js:142:18)
    at getUrl (/usr/lib/node_modules/pm2/node_modules/vizion/lib/git.js:18:5)
    at fn (/usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:746:34)
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:1213:16
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:166:37
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:706:43
2018-07-10 22:15:24: [PM2][WORKER] Error caught by domain:
Error: spawn ENOMEM
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Object.exports.execFile (child_process.js:212:15)
    at exports.exec (child_process.js:142:18)
    at getUrl (/usr/lib/node_modules/pm2/node_modules/vizion/lib/git.js:18:5)
    at fn (/usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:746:34)
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:1213:16
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:166:37
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:706:43
2018-07-10 22:15:26: App [NinjavanService] with id [179] and pid [15077], exited with code [0] via signal [SIGABRT]
2018-07-10 22:15:26: Starting execution sequence in -fork mode- for app name:NinjavanService id:179
2018-07-10 22:15:26: App name:NinjavanService id:179 online
2018-07-10 22:15:26: ===============================================================================
2018-07-10 22:15:26: --- PM2 global error caught ---------------------------------------------------
2018-07-10 22:15:26: Time                 : Tue Jul 10 2018 22:15:26 GMT+0000 (UTC)
2018-07-10 22:15:26: spawn ENOMEM
2018-07-10 22:15:26: Error: spawn ENOMEM
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Object.exports.execFile (child_process.js:212:15)
    at exports.exec (child_process.js:142:18)
    at getUrl (/usr/lib/node_modules/pm2/node_modules/vizion/lib/git.js:18:5)
    at fn (/usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:746:34)
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:1213:16
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:166:37
    at /usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:706:43
2018-07-10 22:15:26: ===============================================================================
2018-07-10 22:15:26: [PM2] Resurrecting PM2
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:502:9)
    at Domain.<anonymous> (/usr/lib/node_modules/pm2/lib/Daemon.js:47:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Domain.emit (events.js:211:7)
    at Domain._errorHandler (domain.js:118:23)
    at process._fatalException (bootstrap_node.js:371:33)

**Comment by wallet77** [comment]
It seems your apps received a signal SIGABRT, like if the system could no longer make them run.

You also have "Error: spawn ENOMEM" which means your system is out of memory and it can't restart your apps.

It can happen if you don't have enough swap. You can check on linux with `free -m`.

**Comment by rishabhdixit** [comment]
Hi @wallet77 yes i checked on our linux server with command `free -m ` and there was no free space.
I allocated 1 GB free space now, would that be enough ?
And is this the solution for both the above errors (ENOMEM and caught by domain) ?

**Comment by wallet77** [comment]
I can't say if 1GB is enough, it depends of your application but it's a good start.
Yes I think it will solve both issues, the ENOEM is clearly and out of memory when pm2 try to restart app. The error is caught by domain but the root cause is out of memory.

**Comment by Unitech** [comment]
@rishabhdixit could you try this low memory version of pm2:

```
$ npm install Unitech/pm2#vizion -g
$ pm2 update
```

And tell us the result)

**Comment by lockwiser** [comment]
> And tell us the result)
```
# npm install Unitech/pm2#vizion -g
npm ERR! code 1
npm ERR! Command failed: git checkout vizion
npm ERR! error: pathspec 'vizion' did not match any file(s) known to git
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-16T15_23_02_770Z-debug.log
```

```
# tail -n50 /root/.npm/_logs/2020-03-16T15_23_02_770Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'Unitech/pm2#vizion',
1 verbose cli   '-g'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.15.0
4 verbose npm-session 2f0c5a3d7df38ba5
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for github:Unitech/pm2#vizion Command failed: git checkout vizion
7 silly fetchPackageMetaData error: pathspec 'vizion' did not match any file(s) known to git
8 timing stage:rollbackFailedOptional Completed in 2ms
9 timing stage:runTopLevelLifecycles Completed in 4021ms
10 verbose stack Error: Command failed: git checkout vizion
10 verbose stack error: pathspec 'vizion' did not match any file(s) known to git
10 verbose stack
10 verbose stack     at ChildProcess.exithandler (child_process.js:295:12)
10 verbose stack     at ChildProcess.emit (events.js:223:5)
10 verbose stack     at maybeClose (internal/child_process.js:1021:16)
10 verbose stack     at Socket.<anonymous> (internal/child_process.js:430:11)
10 verbose stack     at Socket.emit (events.js:223:5)
10 verbose stack     at Pipe.<anonymous> (net.js:664:12)
11 verbose cwd /home/hello.world
12 verbose Linux 4.19.0-6-amd64
13 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "Unitech/pm2#vizion" "-g"
14 verbose node v12.15.0
15 verbose npm  v6.13.4
16 error code 1
17 error Command failed: git checkout vizion
17 error error: pathspec 'vizion' did not match any file(s) known to git
18 verbose exit [ 1, true ]
```

@Unitech
