### ISSUE TITLE
why does not PM2  Resurrecting?

### ISSUE THREAD

**Issue by moto-a** [Unitech/pm2#3793]
## What's going wrong?
Node Application was not restarted.
It seems to pm2 failed to resurrect.

## How could we reproduce this issue?
Almost every time.

## Supporting information
pm2 -vesion
v2.9.1

```
$ pm2 report
```

2018-07-13 09:40:15: PM2 successfully forked
2018-07-13 09:40:19: ===============================================================================
2018-07-13 09:40:19: --- New PM2 Daemon started ----------------------------------------------------
2018-07-13 09:40:19: Time                 : Fri Jul 13 2018 09:40:19
2018-07-13 09:40:19: PM2 version          : 2.9.1
2018-07-13 09:40:19: Node.js version      : 8.9.3
2018-07-13 09:40:19: Current arch         : x64
2018-07-13 09:40:19: PM2 home             : C:\Users\Administrator\.pm2
2018-07-13 09:40:19: PM2 PID file         : C:\Users\Administrator\.pm2\pm2.pid
2018-07-13 09:40:19: RPC socket file      : \\.\pipe\rpc.sock
2018-07-13 09:40:19: BUS socket file      : \\.\pipe\pub.sock
2018-07-13 09:40:19: Application log path : C:\Users\Administrator\.pm2\logs
2018-07-13 09:40:19: Process dump file    : C:\Users\Administrator\.pm2\dump.pm2
2018-07-13 09:40:19: Concurrent actions   : 2
2018-07-13 09:40:19: SIGTERM timeout      : 1600
2018-07-13 09:40:19: ===============================================================================
2018-07-13 09:40:19: Starting execution sequence in -fork mode- for app name:pm2-logrotate id:0
2018-07-13 09:40:19: App name:pm2-logrotate id:0 online
2018-07-13 09:41:48: Starting execution sequence in -fork mode- for app name:XXXXXXXXXX id:1
2018-07-13 09:41:48: App name:XXXXXXXXXX id:1 online
2018-07-13 09:59:39: ===============================================================================
2018-07-13 09:59:39: --- PM2 global error caught ---------------------------------------------------
2018-07-13 09:59:39: Time                 : Fri Jul 13 2018 09:59:39
2018-07-13 09:59:39: This socket is closed
2018-07-13 09:59:39: Error: This socket is closed
    at Socket._writeGeneric (net.js:726:18)
    at Socket._write (net.js:786:8)
    at doWrite (_stream_writable.js:387:12)
    at clearBuffer (_stream_writable.js:514:7)
    at onwrite (_stream_writable.js:439:7)
    at WriteWrap.afterWrite [as oncomplete] (net.js:879:12)
2018-07-13 09:59:39: ===============================================================================
2018-07-13 09:59:39: [PM2] Resurrecting PM2
module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\Windows\system32\bin\pm2'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by Unitech** [comment]
1/ Run `pm2 report` and paste the output here
2/ Can you upgrade to pm2 v3 (`npm install pm2 -g; pm2 update`)

**Comment by moto-a** [comment]
pm2 report 


===============================================================================
--- PM2 REPORT 
===============================================================================
--- Daemon --------------------------------------------------------------------
pm2d version         : 2.9.1
node version         : 8.9.3
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 4762min
===============================================================================
--- CLI -----------------------------------------------------------------------
local pm2            : 2.9.1
node version         : 8.9.3
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : node
user                 : undefined


I will try pm2 upgrade.

**Comment by moto-a** [comment]
Continuation from last time. (pm2 report)

C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\lib\API\Extra.js:70
        fmt.field('uid', process.geteuid());
                                 ^

TypeError: process.geteuid is not a function
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\lib\API\Extra.js:70:34
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon-rpc\lib\client.js:45:10
    at Parser.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon\lib\sockets\req.js:67:8)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser._write (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\amp\lib\stream.js:91:16)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Parser.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)

**Comment by Unitech** [comment]
the geteuid was skipped if not present, I reinforced the check on windows.
What is your windows version?

**Comment by moto-a** [comment]
Thank you for your reply.
Windows version is "Windows Server 2016 Standard".

**Comment by Unitech** [comment]
Thanks.
Is pm2 not in `C:\Windows\system32\bin\pm2`?
Could you type `where pm2`?

**Comment by moto-a** [comment]
>where pm2
C:\Users\Administrator\AppData\Roaming\npm\pm2
C:\Users\Administrator\AppData\Roaming\npm\pm2.cmd

**Comment by Unitech** [comment]
Thank you
@f-hj @vmarchaud do you have an idea on how to get the current binary path? Right now on windows we do that: `var path = cst.IS_WINDOWS ? process.cwd() + '/bin/pm2' : process.env['_'];`

**Comment by wallet77** [comment]
We should use __dirname no ?

For example if you use pm2 in your home directory.
Then results from pm2 binary : 

```
console.log(process.cwd())
C:\Users\Administrator\
console.log(__dirname)
C:\Users\Administrator\AppData\Roaming\npm\pm2
```

So something like that should do the trick : 
var path = cst.IS_WINDOWS ? __dirname + '/../bin/pm2' : process.env['_'];

**Comment by wallet77** [comment]
Hi @moto-a 

I've just try multiple times on Windows 10, pm2 3.0.2
pm2 start/restart/resurrect works fine.

Do you try with latest pm2 ?

**Comment by moto-a** [comment]
Thank you.
Production environment can not be updated now. 
However, the latest version seems to be no problem in the development environment.

**Comment by wallet77** [comment]
Hi @moto-a 

I will wait for your feedback on production environment, if it works I will close the issue.
