### ISSUE TITLE
After upgrading to latest pm2 typescript interpreter stops working 

### ISSUE THREAD

**Issue by dustin-lennon** [Unitech/pm2#3812]
## What's going wrong?
After updating to latest version of pm2, typescript interpreter stops working

## How could we reproduce this issue?
pm2 install typescript returns as errored

## Supporting information
![putty_2018-07-20_17-18-27](https://user-images.githubusercontent.com/92093/43025752-f7de4e9c-8c40-11e8-8fbf-29016f83e6cd.png)

![putty_2018-07-20_17-19-23](https://user-images.githubusercontent.com/92093/43025785-11261d1c-8c41-11e8-9c2b-52a38f36f74d.png)

`/root/.pm2/logs/ts-node-error.log`
```
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.register (/root/.pm2/modules/ts-node/node_modules/ts-node/src/index.ts:205:25)
    at Object.<anonymous> (/root/.pm2/modules/ts-node/node_modules/ts-node/src/bin.ts:100:17)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
```

**Comment by dustin-lennon** [comment]
I cannot even get Typescript to work via the latest development version

**Comment by Unitech** [comment]
Can't reproduce the bug

https://asciinema.org/a/BaHVZ0hNH8S2tCpernlwNHjlZ

From new PM2, I installed typescript then started a typescript app and it worked as expected.
Could you run:

```
$ pm2 uninstall all
$ pm2 install typescript
$ pm2 start app.ts
```

**Comment by dustin-lennon** [comment]
I did some finagling and managed to get it working. I don't recall what exactly I did though. I did not take note.

**Comment by Unitech** [comment]
ok feel free to re open the issue if this issue persist.

**Comment by papakai** [comment]
I also run in a similar issue that subdependencies where not available like arrify, dist, yn and make-error.
after following the above by using
```bash
$ pm2 uninstall all
$ pm2 install typescript
$ pm2 start app.ts
```
Everything is back working. Ty for that hint.

I am using moment (momentjs) in one app and expect these dependencies to come from there.

**Comment by mayankvadia** [comment]
getting same issue in windows 10
