### ISSUE TITLE
exec_interpreter fails when pointed to older node version

### ISSUE THREAD

**Issue by fptoth** [Unitech/pm2#3833]
## What's going wrong?
I'm using current node and current pm2 to run a very old node app on an old node version. Example startup JSON for a test app that demonstrates this:

```
{
  "apps" : [{
    "name"        : "hello",
    "cwd"         : "/home/appuser/test-app/",
    "out_file"    : "out.log",
    "error_file"  : "error.log",
    "pid_file"    : "app.pid",
    "script"      : "hello.js",
    "merge_logs"  : true,
    "args"        : "",
    "watch"       : false,
    "node_args"   : "",
    "instances"   : "1",
    "exec_mode"   : "fork",
    "exec_interpreter"  : "/home/appuser/.nvm/versions/node/v0.12.18/bin/node",
    "env": {
        "NODE_ENV": "production"
    }
  }]
}
```
The above fails to start and appears to trying to load pm2 with the old version of node:
```
/home/appuser/node_modules/pm2/lib/ProcessUtils.js:6
      const pmx = require('@pm2/io');
      ^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/appuser/node_modules/pm2/lib/ProcessContainerFork.js:7:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

The culprit is this test in God/ForkMode.js:

```javascript
if (interpreter === 'node' || RegExp('node$').test(interpreter)) {
  args.push(path.resolve(path.dirname(module.filename), '..', 'ProcessContainerFork.js'));
}
else
  args.push(pm2_env.pm_exec_path);
```
Note that the regex matches my old version ('node$') where it wouldn't for example, with 'perl' or 'python'. It then fiddles the arguments to call ProcessContainerFork.js which then tries to ... (I'm not really sure exactly what ProcessContainerFork.js is doing).

If I comment out the test, everything works fine.

Thanks,
Fred

## Supporting information

```
===============================================================================
--- PM2 REPORT (Fri Jul 27 2018 13:21:18 GMT-0400 (EDT)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.0.3
node version         : 8.11.3
node path            : not found
argv                 : /home/appuser/.nvm/versions/node/v8.11.3/bin/node,/home/appuser/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : appuser
uid                  : 1001
gid                  : 1001
uptime               : 72108min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.0.3
node version         : 8.11.3
node path            : /home/appuser/node_modules/pm2/bin/pm2
argv                 : /home/appuser/.nvm/versions/node/v8.11.3/bin/node,/home/appuser/node_modules/pm2/bin/pm2,report
argv0                : node
user                 : appuser
uid                  : 1001
gid                  : 1001
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
cpus nb              : 4
freemem              : 7012462592
totalmem             : 7832682496
home                 : /home/appuser
===============================================================================
```

**Comment by wallet77** [comment]
HI @fptoth 

Which interpreter do you use ?

**Comment by fptoth** [comment]
Hi,

As shown in the startup JSON above, I'm using node 0.12.18.

Thanks,
Fred

**Comment by wallet77** [comment]
In pm2 3.0.0 we dop node 0.12 support.
You should use node 4+ or downgrade pm2 to 2.x.

Error clearly indicates that const keyword is not allow which is basically the case in node 0.12.

**Comment by fptoth** [comment]
Help me understand. If my app was "perl hello.pl", presumably pm2 would not be concerned about which version of perl I have installed on my system. It would just run the command I give it.

Why is an old node app treated differently? Why should pm2 try to load itself into the old node version? There's nothing in my test app that does anything with pm2, yet I get the above error.

Thanks,
Fred

**Comment by wallet77** [comment]
It's only because const keyword is inside ProcessContainerFork.js file.
This file is used as wrapper for your script. So every line of codes inside it is also interpreted with the interpreter you specified, in your case 0.12 which doesn't allow const keyword.
