### ISSUE TITLE
App won't start. ReferenceError: gl_retry is not defined

### ISSUE THREAD

**Issue by Zaph-x** [Unitech/pm2#3844]
## What's going wrong?
pm2 fails to start app.
Throws a `ReferenceError` saying gl_retry is not defined.

## How could we reproduce this issue?
This issue happened from one day to the other. I only tried to start my app using pm2. (`pm2 start app.js`)

## Supporting information
Trying to run my app, using `pm2 start app.js` gives the following error
```
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\name\.pm2
spawn node ENOENT
spawn node ENOENT
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\name\.pm2
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\name\.pm2
spawn node ENOENT
spawn node ENOENT
spawn node ENOENT
spawn node ENOENT
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\name\.pm2
spawn node ENOENT
spawn node ENOENT
C:\Users\name\AppData\Roaming\npm\node_modules\pm2\lib\API.js:1509
        if (gl_retry == 0) {
        ^

ReferenceError: gl_retry is not defined
    at doList (C:\Users\name\AppData\Roaming\npm\node_modules\pm2\lib\API.js:1509:9)
    at C:\Users\name\AppData\Roaming\npm\node_modules\pm2\lib\Client.js:521:18
    at C:\Users\name\AppData\Roaming\npm\node_modules\pm2\lib\Client.js:106:21
    at ChildProcess.onError (C:\Users\name\AppData\Roaming\npm\node_modules\pm2\lib\Client.js:259:17)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

```
$ pm2 report
```
Running `pm2 report` gives the following messages 
```
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\name\.pm2
spawn node ENOENT
spawn node ENOENT
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\name\.pm2
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\name\.pm2
spawn node ENOENT
spawn node ENOENT
[PM2][ERROR] You need to update your Daemon, please type `$ pm2 update`
spawn node ENOENT
spawn node ENOENT
```
If I then run `pm2 update` I get this error 
```
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\name\.pm2
spawn node ENOENT
spawn node ENOENT
Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\name\.pm2
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\name\.pm2
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\name\.pm2
spawn node ENOENT
spawn node ENOENT
[PM2] Saving current process list...
spawn node ENOENT
spawn node ENOENT
spawn node ENOENT
spawn node ENOENT
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\name\.pm2
spawn node ENOENT
spawn node ENOENT
Error retrieving process list: spawn node ENOENT
[PM2] [-] Stopping Modules
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\name\.pm2
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\name\.pm2
spawn node ENOENT
spawn node ENOENT
Error retrieving process list: spawn node ENOENT
[PM2] [v] Modules Stopped
[PM2] [-] Stopping all Applications
spawn node ENOENT
spawn node ENOENT
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\name\.pm2
spawn node ENOENT
spawn node ENOENT
Error retrieving process list: spawn node ENOENT
spawn node ENOENT
[PM2] [v] All Applications Stopped
[PM2] [-] Stopping Agent
[PM2] [v] Agent Stopped
[PM2] [-] Stopping PM2 Daemon
C:\Users\name\AppData\Roaming\npm\node_modules\pm2\lib\Client.js:623
  this.client.call('stopWatch', method, env, function() {
              ^

TypeError: Cannot read property 'call' of undefined
    at module.exports.stopWatch (C:\Users\name\AppData\Roaming\npm\node_modules\pm2\lib\Client.js:623:15)
    at module.exports.executeRemote (C:\Users\name\AppData\Roaming\npm\node_modules\pm2\lib\Client.js:510:10)
    at module.exports.killDaemon (C:\Users\name\AppData\Roaming\npm\node_modules\pm2\lib\Client.js:582:8)
    at C:\Users\name\AppData\Roaming\npm\node_modules\pm2\lib\API.js:613:23
    at C:\Users\name\AppData\Roaming\npm\node_modules\pm2\lib\API\pm2-plus\link.js:135:21
    at ping (C:\Users\name\AppData\Roaming\npm\node_modules\pm2\node_modules\@pm2\agent\src\InteractorClient.js:83:37)    at ReqSocket.client.sock.once._ (C:\Users\name\AppData\Roaming\npm\node_modules\pm2\node_modules\@pm2\agent\src\InteractorClient.js:44:14)
    at Object.onceWrapper (events.js:273:13)
    at ReqSocket.emit (events.js:182:13)
    at Timeout._onTimeout (C:\Users\name\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon\lib\sockets\sock.js:279:12)
```

**Comment by wallet77** [comment]
Hi @Zaph-x 

Indeed we have a problem with gl_entry variable.
But it seems you got the error because of another issue in your app/environment/machine.
You have a lot of `spawn node ENOENT` logs.

I will fix variable access but it will not fix ENOENT errors !

**Comment by Zaph-x** [comment]
Any idea as to what I can do for now?

**Comment by wallet77** [comment]
Is there any logs you can share with us ?
If you can share /home/{user}/.pm2/pm2.log

What happens if you run your app without pm2 ? Do you have some outputs ?

**Comment by Zaph-x** [comment]
I managed to resolve the problem by copying my entire .pm2 directory from another computer.
