### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by ceo** [Unitech/pm2#3925]
## What's going wrong?

`pm2 logs server` not showing logs... showing an error instead

```

/usr/lib/node_modules/pm2/lib/API/Log.js:38
    fd.on('data', function(data) { chunk += data.toString(); });
                                                 ^

RangeError: Invalid string length
    at ReadStream.<anonymous> (/usr/lib/node_modules/pm2/lib/API/Log.js:38:50)
    at ReadStream.emit (events.js:182:13)
    at addChunk (_stream_readable.js:277:12)
    at readableAddChunk (_stream_readable.js:262:11)
    at ReadStream.Readable.push (_stream_readable.js:217:10)
    at fs.read (fs.js:2134:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:583:17)
astra5087:/var/bin#

```

## How could we reproduce this issue?

I had a program running for a few days.  then this happened

## Supporting information

```
astra5087:~# pm2 report
===============================================================================
--- PM2 REPORT (Mon Sep 24 2018 22:02:46 GMT+0200 (CEST)) ---------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.3
node version         : 10.1.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
uptime               : 125426min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.3
node version         : 10.1.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
cpus nb              : 8
freemem              : 15817895936
totalmem             : 67429306368
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌────────────┬────┬──────┬──────┬─────────┬─────────┬────────┬─────┬────────────┬──────┬──────────┐
│ App name   │ id │ mode │ pid  │ status  │ restart │ uptime │ cpu │ mem        │ user │ watching │
├────────────┼────┼──────┼──────┼─────────┼─────────┼────────┼─────┼────────────┼──────┼──────────┤
│ controller │ 2  │ fork │ 0    │ stopped │ 1       │ 0      │ 0%  │ 0 B        │ root │ disabled │
│ phoneman   │ 1  │ fork │ 6621 │ online  │ 2       │ 9m     │ 1%  │ 155.6 MB   │ root │ disabled │
│ server     │ 0  │ fork │ 6743 │ online  │ 3       │ 4m     │ 3%  │ 339.0 MB   │ root │ disabled │
└────────────┴────┴──────┴──────┴─────────┴─────────┴────────┴─────┴────────────┴──────┴──────────┘
===============================================================================
```

**Comment by wallet77** [comment]
hi @ceo 

Strange ! It seems you have a string which exceed MAX_STRING_LENGTH in your logs.
We should add a try catch for this specific case.

**Comment by akinyele** [comment]
I'm having the same issue. What was the resolution for this?

**Comment by ajaysourcedigital** [comment]
same issue... any solution ?

**Comment by markosinho** [comment]
I encountered this problem today, resolved it with updating node to version 12.18.3 and pm2 to version 4.4.1

**Comment by jesobreira** [comment]
Facing the same issue. `pm2 monit` works properly tho.
