### ISSUE TITLE
Puppeteer served by pm2 doesn't work.

### ISSUE THREAD

**Issue by itsTeknas** [Unitech/pm2#3933]
## What's going wrong?

Puppeteer crashes when running on app served by pm2.

```
API >     { TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
API >     at Promise.then (/home/ubuntu/node_modules/puppeteer/lib/NavigatorWatcher.js:94:21)
API >     at <anonymous> name: 'TimeoutError' }
```

Puppeteer is a wrapper around google headless chrome, when you try to spin up a puppeteer instance inside of an app running pm2, not only does puppeteer fail but also the cpu usage spikes and the entire server becomes unresponsive. 

I tried running the same code on nodemon and forever and that works fine with only ~40mb of ram usage and the request completes within 5 seconds.

## How could we reproduce this issue?

Run any puppeteer instance inside of an app served by pm2

```

.then(url => {
    return puppeteer.launch({
      defaultViewport: {
        width: 1920,
        height: 1080,
        isMobile: false
      },
      printBackground: true
    }).then(browser => {
      return browser.newPage().then(page => {
        return page.goto(url).then(resp => {
          return page.screenshot({
            type: "jpeg"
          })
        }).then(buffer => {
          browser.close();
          return buffer;
        })
      })
    })
```

## Supporting information

```
===============================================================================
--- PM2 REPORT (Sun Sep 30 2018 05:41:19 GMT+0000 (UTC)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.4
node version         : 8.11.3
node path            : /home/ubuntu/.nvm/versions/node/v8.11.3/bin/pm2
argv                 : /home/ubuntu/.nvm/versions/node/v8.11.3/bin/node,/home/ubuntu/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : ubuntu
uid                  : 1000
gid                  : 1000
uptime               : 945min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.4
node version         : 8.11.3
node path            : /home/ubuntu/.nvm/versions/node/v8.11.3/bin/pm2
argv                 : /home/ubuntu/.nvm/versions/node/v8.11.3/bin/node,/home/ubuntu/.nvm/versions/node/v8.11.3/bin/pm2,report
argv0                : node
user                 : ubuntu
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
cpus nb              : 1
freemem              : 8552448
totalmem             : 503242752
home                 : /home/ubuntu
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────┬────────────┬────────┬──────────┐
│ App name │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu │ mem        │ user   │ watching │
├──────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────┼────────────┼────────┼──────────┤
│ API      │ 0  │ cluster │ 20796 │ online │ 1       │ 15h    │ 0%  │ 112.5 MB   │ ubuntu │ disabled │
│ QUEUE    │ 1  │ fork    │ 20797 │ online │ 1       │ 15h    │ 0%  │ 51.4 MB    │ ubuntu │ disabled │
└──────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────┴────────────┴────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────┬────────────┬────────┬──────────┐
│ App name │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu │ mem        │ user   │ watching │
├──────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────┼────────────┼────────┼──────────┤
│ API      │ 0  │ cluster │ 20796 │ online │ 1       │ 15h    │ 0%  │ 112.5 MB   │ ubuntu │ disabled │
│ QUEUE    │ 1  │ fork    │ 20797 │ online │ 1       │ 15h    │ 0%  │ 51.4 MB    │ ubuntu │ disabled │
└──────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────┴────────────┴────────┴──────────┘
```

**Comment by itsTeknas** [comment]
This does seem to work fine on my development environment running on mac.
Report from local env,

```
===============================================================================
--- PM2 REPORT (Sun Sep 30 2018 11:34:19 GMT+0530 (IST)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.4
node version         : 8.11.2
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : Sanket
uid                  : 501
gid                  : 20
uptime               : 6min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.4
node version         : 8.11.2
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : Sanket
uid                  : 501
gid                  : 20
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : darwin
type                 : Darwin
cpus                 : Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz
cpus nb              : 8
freemem              : 519847936
totalmem             : 8589934592
home                 : /Users/Sanket
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬─────────┬──────┬────────┬─────────┬────────┬─────┬───────────┬────────┬──────────┐
│ App name │ id │ mode    │ pid  │ status │ restart │ uptime │ cpu │ mem       │ user   │ watching │
├──────────┼────┼─────────┼──────┼────────┼─────────┼────────┼─────┼───────────┼────────┼──────────┤
│ API      │ 0  │ cluster │ 1813 │ online │ 3       │ 4m     │ 0%  │ 97.7 MB   │ Sanket │ enabled  │
│ QUEUE    │ 1  │ fork    │ 1814 │ online │ 3       │ 4m     │ 0%  │ 54.0 MB   │ Sanket │ enabled  │
└──────────┴────┴─────────┴──────┴────────┴─────────┴────────┴─────┴───────────┴────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/Users/Sanket/.pm2/pm2.log last 20 lines:
PM2        | [2018-09-30 11:29:20] PM2 log: Starting execution sequence in -cluster mode- for app name:API id:0
PM2        | [2018-09-30 11:29:20] PM2 log: pid=1610 msg=process killed
PM2        | [2018-09-30 11:29:20] PM2 log: Starting execution sequence in -fork mode- for app name:QUEUE id:1
PM2        | [2018-09-30 11:29:20] PM2 log: App name:QUEUE id:1 online
PM2        | [2018-09-30 11:29:20] PM2 log: App name:API id:0 online
PM2        | [2018-09-30 11:29:20] PM2 error: (node:1377) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
PM2        | [2018-09-30 11:29:45] PM2 error: Change detected on path routes/stylist-api.js for app API - restarting
PM2        | [2018-09-30 11:29:45] PM2 log: Stopping app:API id:0
PM2        | [2018-09-30 11:29:45] PM2 error: Change detected on path routes/stylist-api.js for app QUEUE - restarting
PM2        | [2018-09-30 11:29:45] PM2 log: Stopping app:QUEUE id:1
PM2        | [2018-09-30 11:29:45] PM2 log: App name:API id:0 disconnected
PM2        | [2018-09-30 11:29:45] PM2 log: App [API] with id [0] and pid [1658], exited with code [0] via signal [SIGINT]
PM2        | [2018-09-30 11:29:45] PM2 log: App [QUEUE] with id [1] and pid [1659], exited with code [0] via signal [SIGINT]
PM2        | [2018-09-30 11:29:45] PM2 log: pid=1658 msg=process killed
PM2        | [2018-09-30 11:29:45] PM2 log: Starting execution sequence in -cluster mode- for app name:API id:0
PM2        | [2018-09-30 11:29:45] PM2 log: pid=1659 msg=process killed
PM2        | [2018-09-30 11:29:45] PM2 log: Starting execution sequence in -fork mode- for app name:QUEUE id:1
PM2        | [2018-09-30 11:29:45] PM2 log: App name:QUEUE id:1 online
PM2        | [2018-09-30 11:29:45] PM2 log: App name:API id:0 online
PM2        | [2018-09-30 11:29:45] PM2 error: (node:1377) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.

```

**Comment by emcodest** [comment]
Solved mine by using https://www.npmjs.com/package/forever

**Comment by antongorodezkiy** [comment]
Had the same issue today

Node: v8.10.0
NPM: 6.8.0
puppeteer@1.13.0
pm2@3.4.0

```
2019-07-10 10:26 +00:00: { TimeoutError: Navigation Timeout Exceeded: 90000ms exceeded
2019-07-10 10:26 +00:00:     at Promise.then (~/data-server/crawler/node_modules/puppeteer/lib/LifecycleWatcher.js:143:21)
2019-07-10 10:26 +00:00:     at propagateAslWrapper (~/data-server/crawler/node_modules/async-listener/index.js:504:23)
2019-07-10 10:26 +00:00:     at ~/data-server/crawler/node_modules/async-listener/index.js:541:70
2019-07-10 10:26 +00:00:     at <anonymous>
2019-07-10 10:26 +00:00:   -- ASYNC --
2019-07-10 10:26 +00:00:     at Frame.<anonymous> (~/data-server/crawler/node_modules/puppeteer/lib/helper.js:108:27)
2019-07-10 10:26 +00:00:     at Page.waitForNavigation (~/data-server/crawler/node_modules/puppeteer/lib/Page.js:676:49)
2019-07-10 10:26 +00:00:     at Page.<anonymous> (~/data-server/crawler/node_modules/puppeteer/lib/helper.js:109:23)
2019-07-10 10:26 +00:00:     at Worker.waitForNavigation (~/data-server/crawler/src/Providers/Worker.js:81:21)
2019-07-10 10:26 +00:00:     at tryCatch (~/data-server/crawler/node_modules/regenerator-runtime/runtime.js:62:40)
2019-07-10 10:26 +00:00:     at Generator.invoke [as _invoke] (~/data-server/crawler/node_modules/regenerator-runtime/runtime.js:288:22)
2019-07-10 10:26 +00:00:     at Generator.prototype.(anonymous function) [as next] (~/data-server/crawler/node_modules/regenerator-runtime/runtime.js:114:21)
2019-07-10 10:26 +00:00:     at asyncGeneratorStep (~/data-server/crawler/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
2019-07-10 10:26 +00:00:     at _next (~/data-server/crawler/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
2019-07-10 10:26 +00:00:     at propagateAslWrapper (~/data-server/crawler/node_modules/async-listener/index.js:504:23)
2019-07-10 10:26 +00:00:     at ~/data-server/crawler/node_modules/async-listener/index.js:541:70
2019-07-10 10:26 +00:00:     at <anonymous>
2019-07-10 10:26 +00:00:     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
2019-07-10 10:26 +00:00:     at process.fallback (~/data-server/crawler/node_modules/async-listener/index.js:565:15) name: 'TimeoutError' }
```

**Comment by StrsMasl** [comment]
> 
> 
> Bumping the server specs to t2.medium solved it.
> Sorry for the bug report, i had no idea what is happening at the time.

this his been a while, could you further explain how you solved this issue?
