### ISSUE TITLE
Error caught while calling pidusage

### ISSUE THREAD

**Issue by baitun** [Unitech/pm2#3942]
## What's going wrong?

A window constantly opens, immediately closes and the following error in the log:

```
PM2      | Error caught while calling pidusage
PM2      | Error: ERROR:
PM2      | Description = Exception occurred.
PM2      |     at ChildProcess.<anonymous> (C:\www\node\node_modules\pm2\node_modules\pidusage\lib\bin.js:41:19)
PM2      |     at emitTwo (events.js:126:13)
PM2      |     at ChildProcess.emit (events.js:214:7)
PM2      |     at maybeClose (internal/child_process.js:915:16)
PM2      |     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

## How could we reproduce this issue?

`pm2 start --env production` on Windows server.

## Supporting information

```
===============================================================================
--- PM2 REPORT (Fri Oct 05 2018 10:46:52 GMT+0300 (Russia TZ 2 Standard Time))
===============================================================================
--- Daemon --------------------------------------------------------------------
pm2d version         : 3.1.3
node version         : 8.12.0
node path            : C:/www/node/node
argv                 : C:\Program Files\nodejs\node.exe,C:\www\node\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 12min
===============================================================================
--- CLI -----------------------------------------------------------------------
local pm2            : 3.1.3
node version         : 8.10.0
node path            : C:/www/node/node
argv                 : C:\www\node\node.exe,C:\www\node\node_modules\pm2\bin\pm2,report
argv0                : C:\www\node\node.exe
user                 : yury.savin
===============================================================================
--- System info ---------------------------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz
cpus nb              : 12
freemem              : 14813372416
totalmem             : 34356629504
home                 : C:\Users\yury.savin
===============================================================================
--- PM2 list ------------------------------------------------------------------
┌──────────┬────┬──────┬────────┬────────┬─────────┬────────┬─────┬────────┬────────────┬──────────┐
│ App name │ id │ mode │ pid    │ status │ restart │ uptime │ cpu │ mem    │ user       │ watching │
├──────────┼────┼──────┼────────┼────────┼─────────┼────────┼─────┼────────┼────────────┼──────────┤
│ api      │ 0  │ fork │ 101900 │ online │ 0       │ 2m     │ 0%  │ 0 B    │ yury.savin │ disabled │
└──────────┴────┴──────┴────────┴────────┴─────────┴────────┴─────┴────────┴────────────┴──────────┘
===============================================================================
--- Daemon logs ---------------------------------------------------------------
C:\users\yury.savin\.pm2\pm2.log last 20 lines:
PM2        | [2018-10-05T10:46:09.847Z] PM2 error: Error caught while calling pidusage
PM2        | [2018-10-05T10:46:09.847Z] PM2 error: Error: ERROR:
PM2        | Description = Exception occurred.
PM2        |
PM2        | [2018-10-05T10:46:16.628Z] PM2 error: Error caught while calling pidusage
PM2        | [2018-10-05T10:46:16.628Z] PM2 error: Error: ERROR:
PM2        | Description = Exception occurred.
PM2        |
PM2        | [2018-10-05T10:46:17.003Z] PM2 error: Error caught while calling pidusage
PM2        | [2018-10-05T10:46:17.003Z] PM2 error: Error: ERROR:
PM2        | Description = Exception occurred.
PM2        |
PM2        | [2018-10-05T10:46:39.909Z] PM2 error: Error caught while calling pidusage
PM2        | [2018-10-05T10:46:39.909Z] PM2 error: Error: ERROR:
PM2        | Description = Exception occurred.
PM2        |
PM2        | [2018-10-05T10:46:53.316Z] PM2 error: Error caught while calling pidusage
PM2        | [2018-10-05T10:46:53.316Z] PM2 error: Error: ERROR:
PM2        | Description = Exception occurred.
PM2        |
```

**Comment by soyuka** [comment]
Hi,

can you try to manually execute :

```
wmic PROCESS where ProcessId=YOUR_PID get CreationDate,KernelModeTime,ParentProcessId,ProcessId,UserModeTime,WorkingSetSize
```

by replacing `YOUR_PID` with an existing process id?

**Comment by baitun** [comment]
@soyuka 
it returns
```
ERROR:
Description = Exception occurred.
```

**Comment by soyuka** [comment]
This is your issue then, you should contact the support of your WINDOWS_NT provider or find out more details about this exception so that we can help you more.

**Comment by Unitech** [comment]
```
ERROR:
Description = Exception occurred.
```

That's all the details about that exception? My god pretty dumb output from that windows command
