### ISSUE TITLE
PM2 crashes after running for a while

### ISSUE THREAD

**Issue by ravithb** [Unitech/pm2#3954]
## What's going wrong?
PM2 crashes after running a node app for a while with the following trace

## Supporting information
```

[2018-10-11T11:02:18.764Z] PM2 log: Starting execution sequence in -fork mode- for app name:sbos-test-async-mailer-daemon id:1
[2018-10-11T11:02:18.769Z] PM2 log: App name:sbos-test-async-mailer-daemon id:1 online
[2018-10-11T13:25:50.609Z] PM2 log: App [sbos-test-async-mailer-daemon] with id [1] and pid [20755], exited with code [0] via signal [SIGINT]
[2018-10-11T13:25:50.724Z] PM2 log: App [sbos-async-mailer-daemon] with id [0] and pid [20712], exited with code [0] via signal [SIGINT]
[2018-10-11T13:25:50.727Z] PM2 log: Starting execution sequence in -fork mode- for app name:sbos-test-async-mailer-daemon id:1
[2018-10-11T13:25:50.730Z] PM2 log: ===============================================================================
[2018-10-11T13:25:50.731Z] PM2 log: --- PM2 global error caught ---------------------------------------------------
[2018-10-11T13:25:50.731Z] PM2 log: Time                 : Thu Oct 11 2018 13:25:50 GMT+1030 (ACDT)
[2018-10-11T13:25:50.731Z] PM2 error: Cannot read property 'on' of undefined
[2018-10-11T13:25:50.732Z] PM2 error: TypeError: Cannot read property 'on' of undefined
    at /usr/lib/node_modules/pm2/lib/God/ForkMode.js:115:19
    at /usr/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16
    at next (/usr/lib/node_modules/pm2/node_modules/async/waterfall.js:21:29)
    at /usr/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
    at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:171:13)
    at emitOne (events.js:116:13)
    at WriteStream.emit (events.js:211:7)
    at fs.open (fs.js:2170:10)
    at FSReqWrap.oncomplete (fs.js:135:15)
[2018-10-11T13:25:50.733Z] PM2 log: ===============================================================================
[2018-10-11T13:25:50.733Z] PM2 error: [PM2] Resurrecting PM2
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn node EAGAIN
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at Immediate._tickDomainCallback [as _onImmediate] (internal/process/next_tick.js:219:9)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

```
$ pm2 report
===============================================================================
--- PM2 REPORT (Thu Oct 11 2018 23:59:15 GMT+1030 (ACDT)) ---------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.1.3
node version         : 8.12.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : sbosonli
uid                  : 1001
gid                  : 1001
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.1.3
node version         : 8.12.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : sbosonli
uid                  : 1001
gid                  : 1001
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : QEMU Virtual CPU version (cpu64-rhel6)
cpus nb              : 8
freemem              : 413757440
totalmem             : 6086197248
home                 : /home/sbosonli
===============================================================================
--- PM2 list -----------------------------------------------
┌──────┬────┬──────┬────────┬───┬─────┬────────┐
│ Name │ id │ mode │ status │ ↺ │ cpu │ memory │
└──────┴────┴──────┴────────┴───┴─────┴────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────┬────┬──────┬────────┬───┬─────┬────────┐
│ Name │ id │ mode │ status │ ↺ │ cpu │ memory │
└──────┴────┴──────┴────────┴───┴─────┴────────┘
 Use `pm2 show <id|name>` to get more details about an app


```

**Comment by Unitech** [comment]
pm2@3.2.5 published

```
$ npm install pm2@latest -g
$ pm2 update
```
