### ISSUE TITLE
PM2 is trying to use old/removed linux brew files

### ISSUE THREAD

**Issue by leshacat** [Unitech/pm2#3961]
**To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- Step-by-step reproduction instructions (by running `brew` commands)**

1) Installed brew to try it
2) Didn't like it
3) Uninstalled brew
4) Installed NVM & NodeJS v8.1.4
5) Updated NPM & node-gyp to @latest
6) Installed PM2
7) Now cannot use NodeJS installed with nvm/npm/pm2 with errors showing ".linuxbrew"
8) echo $PATH still shows linux brew remains even after uninstall, disconnect, reconnect
9) Nothing exists in ~/.bashrc related to linux brew

- What you expected to happen
Brew to be uninstalled completely and gone from my system

**When I run "node init.js" everything runs perfectly fine (minus the fact I am half done setting up the pool software):**
> kthx@mn0:~/BOOTNOMP$ node init.js
> [2018-10-12T11:39:04.291Z] [debug] [system] [init.js] : POSIX Connection Limit (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
> [2018-10-12T11:39:05.330Z] [debug] [system] [SwitchingSetup[:1]] : Loading last proxy state from redis
> [2018-10-12T11:39:05.347Z] [debug] [system] [init.js] : Master
> [2018-10-12T11:39:05.362Z] [debug] [mogwaicoin] [ShareProcessor [:0]] : Share processing setup with redis (127.0.0.1:6379)
> [2018-10-12T11:39:05.364Z] [error] [mogwaicoin] [Pool [:1]] : Could not start pool, error with init batch RPC call: {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:19000"}
> [2018-10-12T11:39:05.718Z] [debug] [system] [SwitchingSetup[:2]] : Loading last proxy state from redis
> [2018-10-12T11:39:05.746Z] [debug] [mogwaicoin] [ShareProcessor [:1]] : Share processing setup with redis (127.0.0.1:6379)
> [2018-10-12T11:39:05.759Z] [error] [mogwaicoin] [Pool [:2]] : Could not start pool, error with init batch RPC call: {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:19000"}
> [2018-10-12T11:39:05.847Z] [debug] [system] [SwitchingSetup[:3]] : Loading last proxy state from redis
> [2018-10-12T11:39:05.866Z] [debug] [mogwaicoin] [ShareProcessor [:2]] : Share processing setup with redis (127.0.0.1:6379)
> [2018-10-12T11:39:05.867Z] [error] [mogwaicoin] [Pool [:3]] : Could not start pool, error with init batch RPC call: {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:19000"}
> [2018-10-12T11:39:06.204Z] [debug] [system] [SwitchingSetup[:4]] : Loading last proxy state from redis
> [2018-10-12T11:39:06.220Z] [debug] [mogwaicoin] [ShareProcessor [:3]] : Share processing setup with redis (127.0.0.1:6379)
> [2018-10-12T11:39:06.222Z] [error] [mogwaicoin] [Pool [:4]] : Could not start pool, error with init batch RPC call: {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:19000"}
> [2018-10-12T11:39:06.320Z] [info] [system] [CLI] : CLI listening on 0.0.0.0:17000

**But when I run "pm2 start init.js --watch --name pool" I get this error from PM2:**
> 0|pool     | Error: Cannot find module '/home/linuxbrew/.linuxbrew/lib/node_modules/pm2/lib/ProcessContainerFork.js'
> 0|pool     |     at Function.Module._resolveFilename (module.js:336:15)
> 0|pool     |     at Function.Module._load (module.js:278:25)
> 0|pool     |     at Function.Module.runMain (module.js:501:10)
> 0|pool     |     at startup (node.js:129:16)
> 0|pool     |     at node.js:814:3
> 0|pool     | module.js:338
> 0|pool     |     throw err;
> 0|pool     |           ^
> 0|pool     | Error: Cannot find module '/home/linuxbrew/.linuxbrew/lib/node_modules/pm2/lib/ProcessContainerFork.js'
> 0|pool     |     at Function.Module._resolveFilename (module.js:336:15)
> 0|pool     |     at Function.Module._load (module.js:278:25)
> 0|pool     |     at Function.Module.runMain (module.js:501:10)
> 0|pool     |     at startup (node.js:129:16)
> 0|pool     |     at node.js:814:3

**Now this error is thrown by PM2, however I am not posting in PM2 issue repo because this error involves remains of a linux brew installation.**

If someone can help please, I have tried also:
**rm -rf ~/.npm**
**rm -rf ~/.nvm**
**rm -rf ~/.pm2**
**rm -rf node_modules**
rebuilding all NPM packages incl. PM2

**I know there is a node_modules folder somewhere in the root system, I will try and find it and delete PM2 from it**

## Supporting information

```
kthx@easyxpool:~$ pm2 report
===============================================================================
--- PM2 REPORT (Fri Oct 12 2018 14:52:32 GMT-0400 (EDT)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.2.0
node version         : 8.1.4
node path            : /home/kthx/.nvm/v8.1.4/bin/pm2
argv                 : /home/kthx/.nvm/v8.1.4/bin/node,/home/kthx/.nvm/v8.1.4/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : kthx
uid                  : 1000
gid                  : 1000
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.2.0
node version         : 8.1.4
node path            : /home/kthx/.nvm/v8.1.4/bin/pm2
argv                 : /home/kthx/.nvm/v8.1.4/bin/node,/home/kthx/.nvm/v8.1.4/bin/pm2,report
argv0                : node
user                 : kthx
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz
cpus nb              : 4
freemem              : 108838912
totalmem             : 2684354560
home                 : /home/kthx
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬─────────┬─────────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name │ id │ version │ mode    │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├──────────┼────┼─────────┼─────────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ pool     │ 0  │ 1.0.7   │ cluster │ 31092 │ online │ 0       │ 6s     │ 0%  │ 47.3 MB   │ kthx │ disabled │
│ pool     │ 1  │ 1.0.7   │ cluster │ 31093 │ online │ 0       │ 6s     │ 0%  │ 47.3 MB   │ kthx │ disabled │
│ pool     │ 2  │ 1.0.7   │ cluster │ 31104 │ online │ 0       │ 6s     │ 0%  │ 47.4 MB   │ kthx │ disabled │
│ pool     │ 3  │ 1.0.7   │ cluster │ 31109 │ online │ 0       │ 6s     │ 0%  │ 47.3 MB   │ kthx │ disabled │
└──────────┴────┴─────────┴─────────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
⇆  PM2+ activated | Web: https://app.pm2.io/#/r/n56qlqeio9alkze | Server: easyxpool.tk-4447 | Conn: Axon
┌──────────┬────┬─────────┬─────────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name │ id │ version │ mode    │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├──────────┼────┼─────────┼─────────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ pool     │ 0  │ 1.0.7   │ cluster │ 31092 │ online │ 0       │ 6s     │ 0%  │ 47.3 MB   │ kthx │ disabled │
│ pool     │ 1  │ 1.0.7   │ cluster │ 31093 │ online │ 0       │ 6s     │ 0%  │ 47.3 MB   │ kthx │ disabled │
│ pool     │ 2  │ 1.0.7   │ cluster │ 31104 │ online │ 0       │ 6s     │ 0%  │ 47.4 MB   │ kthx │ disabled │
│ pool     │ 3  │ 1.0.7   │ cluster │ 31109 │ online │ 0       │ 6s     │ 0%  │ 47.3 MB   │ kthx │ disabled │
└──────────┴────┴─────────┴─────────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
kthx@easyxpool:~$ 
```

Related to problem here: https://github.com/Homebrew/brew/issues/5094

Thanks

**Comment by leshacat** [comment]
Unable to further this issue as I have reinstalled.

Thansk
