### ISSUE TITLE
interactor:daemon Got an a error on ping root { Error: socket hang up...

### ISSUE THREAD

**Issue by xyboox** [Unitech/pm2#3974]
## What's going wrong?
Agent started to error after about 12 hours of functioning and it lasted for about 4 hours, and in that period, all our pm2 managed apps were down.

## How could we reproduce this issue?
I really don't know

## Supporting information

$ pm2 report
from agent.log:

`interactor:daemon Got an a error on ping root { Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1148:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
  code: 'ECONNRESET',
  path: null,
  host: 'root.keymetrics.io',
  port: 443,
  localAddress: undefined }`

repeated at interval of about 2 minutes ( more or less) .

**Comment by Unitech** [comment]
@vmarchaud
