### ISSUE TITLE
 cb is not a function

### ISSUE THREAD

**Issue by Koldunz** [Unitech/pm2#3998]
Hi. Such an error began to appear. Tell me where to look. Is it possible that this problem is not in the pm2?

pm2 version 3.2.2
node version 8.11.3

```
TypeError: cb is not a function
at afterWrite (_stream_writable.js:464:3)
at onwrite (_stream_writable.js:455:7)
at Socket._writeGeneric (net.js:773:5)
at Socket._writev (net.js:778:8)
at doWrite (_stream_writable.js:395:12)
at clearBuffer (_stream_writable.js:501:5)
at Socket.Writable.uncork (_stream_writable.js:313:7)
at ClientRequest._flushOutput (_http_outgoing.js:844:10)
at ClientRequest._flush (_http_outgoing.js:819:16)
at ClientRequest._deferToConnect (_http_client.js:277:47)
at callSocketMethod (_http_client.js:685:7)
at ClientRequest.onSocket (_http_client.js:690:7)
at Object.onceWrapper (events.js:315:30)
at emitOne (events.js:121:20)
at ClientRequest.emit (events.js:211:7)
at tickOnSocket (_http_client.js:652:7)
at onSocketNT (_http_client.js:668:5)
at args.(anonymous function) (/root/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by Unitech** [comment]
This is dark matter magic. Kidding. I need more information on how to reproduce this issue
