### ISSUE TITLE
Error: Cannot find module '../constants.js'

### ISSUE THREAD

**Issue by fustic** [Unitech/pm2#4001]
## PM2 can not start the app on Elasticbeanstalk
node version: 8.9.3
pm2 version: 3.2.2
EB node command is `npm start`, where `start` defined as `pm2 start ecosystem.config.js --env production`
The app itself works on EB without pm2, i.e. starting as just `node server.js`

```
-------------------------------------
/var/log/nodejs/nodejs.log
-------------------------------------
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@18.26.1 start: `pm2 start ecosystem.config.js --env production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at app@18.26.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/.npm/_logs/2018-11-02T17_27_00_132Z-debug.log

> app@18.26.1 start /var/app/current
> pm2 start ecosystem.config.js --env production

module.js:538
    throw err;
    ^

Error: Cannot find module '../constants.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/app/current/node_modules/.bin/pm2:11:20)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)

    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@18.26.1 start: `pm2 start ecosystem.config.js --env production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@18.26.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/.npm/_logs/2018-11-02T17_27_00_448Z-debug.log

> app@18.26.1 start /var/app/current
> pm2 start ecosystem.config.js --env production

module.js:538
    throw err;
    ^
```

**Comment by extensionsapp** [comment]
`npm install --loglevel=silent --parseable --no-optional --no-shrinkwrap --no-package-lock pm2@latest`
`pm2 update`

```
binding.lstat(baseLong);
              ^

Error: ENOENT: no such file or directory, lstat '/usr/lib/node_modules/pm2/node_modules/@pm2/js-api/node_modules/ws/lib/Constants.js'
    at Object.realpathSync (fs.js:1657:15)
    at toRealPath (module.js:164:13)
    at tryFile (module.js:160:22)
    at tryExtensions (module.js:172:22)
    at Function.Module._findPath (module.js:225:20)
    at Function.Module._resolveFilename (module.js:546:25)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (/usr/lib/node_modules/pm2/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/node_modules/@pm2/js-api/node_modules/ws/lib/WebSocket.js:19:19)
```

**Comment by iamchristopher** [comment]
Did you ever figure this out, @fustic?

**Comment by fustic** [comment]
@iamchristopher no, unfortunately. To be honest I didn't really look into this. pm2 works just fine in docker set up

**Comment by iamchristopher** [comment]
@fustic Thanks anyway! :)
