### ISSUE TITLE
Updated to Node 11- shimmer error

### ISSUE THREAD

**Issue by Denaton** [Unitech/pm2#4003]
## What's going wrong?
Error on server start.

## How could we reproduce this issue?
Start the server

## Supporting information
Its started to happen after i updated the NodeJs to version 11.
Seen other have removed their support for shimmer in their modules.
Its does not break the code but its annoying.

> TypeError: Cannot redefine property: pseudoRandomBytes
    at Function.defineProperty (<anonymous>)
    at defineProperty (/usr/local/lib/node_modules/pm2/node_modules/shimmer/index.js:14:10)
    at wrap (/usr/local/lib/node_modules/pm2/node_modules/shimmer/index.js:56:3)
    at /usr/local/lib/node_modules/pm2/node_modules/shimmer/index.js:76:7
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/pm2/node_modules/shimmer/index.js:75:11
    at Array.forEach (<anonymous>)
    at massWrap (/usr/local/lib/node_modules/pm2/node_modules/shimmer/index.js:74:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/async-listener/index.js:332:3)
    at Module._compile (internal/modules/cjs/loader.js:707:30)

**Comment by vmarchaud** [comment]
I believe the issue come from the `async-listener` module that should have been fixed with this commit : https://github.com/othiym23/async-listener/commit/e0c269a39c16892c2402b06f398201956b905033
Could you try with a clean pm2 install ?

**Comment by Denaton** [comment]
Seems like i have the latest version of async-listener, and pm2 is up to date.

`npm view async-listener version`

> 0.6.10

**Comment by Unitech** [comment]
I've added node@11 to travis, let see what it says: https://github.com/Unitech/pm2/commit/45d3b6b7a34cf47105bde6b6db9358f33d6d230c https://travis-ci.org/Unitech/pm2/builds/453861831
