### ISSUE TITLE
Error: Cannot find module ProcessContainerFork.js

### ISSUE THREAD

**Issue by fishcharlie** [Unitech/pm2#4016]
## What's going wrong?

When building on CircleCI some of my builds are failing randomly. Some are passing and some are passing.

I ran a build that failed using SSH on CircleCI to try to track down the issue. When attempting to run `npx pm2 restart all` while watching the logs using `npx pm2 logs` it produces the following output over and over:

```
PM2      | App [server:0] exited with code [1] via signal [SIGINT]
PM2      | App [server:0] starting in -fork mode-
PM2      | App [server:0] online
0|server | internal/modules/cjs/loader.js:583
0|server |     throw err;
0|server |     ^
0|server | Error: Cannot find module '/home/circleci/.npm/_npx/7597/lib/node_modules/pm2/lib/ProcessContainerFork.js'
0|server |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
0|server |     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
0|server |     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
0|server |     at startup (internal/bootstrap/node.js:266:19)
0|server |     at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
PM2      | App [server:0] exited with code [1] via signal [SIGINT]
PM2      | Script /home/circleci/repo/node_modules/OtherSystem/server.js had too many unstable restarts (16). Stopped. "errored"
```

It looks like it's having trouble finding a certain module. I'm not sure if this is a PM2 problem or NPX problem or what. But thought I'd ask here to see if anyone has any ideas on how to fix.

## How could we reproduce this issue?

Unknown

## Supporting information

```
circleci@default-c3462f62-acf4-4069-bf2c-880b79af12a6:~/repo$ npx pm2 report
npx: installed 261 in 5.946s
===============================================================================
--- PM2 REPORT (Fri Nov 09 2018 19:32:47 GMT+0000 (Coordinated Universal Time)) 
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.2.2
node version         : 10.9.0
node path            : /opt/circleci/.nvm/versions/node/v10.9.0/bin/npm
argv                 : /opt/circleci/.nvm/versions/node/v10.9.0/bin/node,/home/circleci/.npm/_npx/7597/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : circleci
uid                  : 1001
gid                  : 1002
uptime               : 6min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.2.2
node version         : 10.9.0
node path            : /opt/circleci/.nvm/versions/node/v10.9.0/bin/npx
argv                 : /opt/circleci/.nvm/versions/node/v10.9.0/bin/node,/home/circleci/.npm/_npx/9116/bin/pm2,report
argv0                : node
user                 : circleci
uid                  : 1001
gid                  : 1002
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU @ 2.30GHz
cpus nb              : 2
freemem              : 5622091776
totalmem             : 7843196928
home                 : /home/circleci
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬─────────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬──────────┬──────────┐
│ App name │ id │ version │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user     │ watching │
├──────────┼────┼─────────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼──────────┼──────────┤
│ server   │ 0  │ 1.0.0   │ fork │ 0   │ errored │ 30      │ 0      │ 0%  │ 0 B    │ circleci │ disabled │
└──────────┴────┴─────────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬─────────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬──────────┬──────────┐
│ App name │ id │ version │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user     │ watching │
├──────────┼────┼─────────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼──────────┼──────────┤
│ server   │ 0  │ 1.0.0   │ fork │ 0   │ errored │ 30      │ 0      │ 0%  │ 0 B    │ circleci │ disabled │
└──────────┴────┴─────────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴──────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

**Comment by vedantroy** [comment]
I am also having this issue.
