### ISSUE TITLE
zlib: unexpected end of file

### ISSUE THREAD

**Issue by andrunix** [Unitech/pm2#4020]
## What's going wrong?
Unable to install pm2 on RedHat 7.

My configuration is a bit difficult. I am behind a corporate firewall and web proxy. Further, we have an npm proxy as well. For most npm installs, my current configuration with the firewall and proxies is fine. But installing pm2 I get the following error:

```
$ npm install pm2 -g
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gkt@https://tgz.pm2.io/gkt-1.0.0.tgz (node_modules/pm2/node_modules/gkt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 407 authenticationrequired: gkt@https://tgz.pm2.io/gkt-1.0.0.tgz

npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file
```
I've tried using --no-optional but that doesn't seem to work either. Same error here. 

With --verbose, I get a little more detail but still don't see what the problem might be:

```
npm verb stack ZlibError: zlib: unexpected end of file
npm verb stack     at Zlib.(anonymous function).onerror (/opt/ping/apps/node-v10.13.0-linux-x64/lib/node_modules/npm/node_modules/minizlib/index.js:131:21)
npm verb stack     at Unzip.write (/opt/ping/apps/node-v10.13.0-linux-x64/lib/node_modules/npm/node_modules/minizlib/index.js:255:31)
npm verb stack     at Unzip.flush (/opt/ping/apps/node-v10.13.0-linux-x64/lib/node_modules/npm/node_modules/minizlib/index.js:222:10)
npm verb stack     at Unzip.end (/opt/ping/apps/node-v10.13.0-linux-x64/lib/node_modules/npm/node_modules/minizlib/index.js:229:10)
npm verb stack     at Object.end (/opt/ping/apps/node-v10.13.0-linux-x64/lib/node_modules/npm/node_modules/tar/lib/parse.js:415:21)
npm verb stack     at PassThrough.onend (_stream_readable.js:628:10)
npm verb stack     at Object.onceWrapper (events.js:273:13)
npm verb stack     at PassThrough.emit (events.js:187:15)
npm verb stack     at endReadableNT (_stream_readable.js:1094:12)
npm verb stack     at process._tickCallback (internal/process/next_tick.js:63:19)
npm verb cwd /home/bcbst/a16106p2
npm verb Linux 3.10.0-957.el7.x86_64
npm verb argv "/opt/ping/apps/node-v10.13.0-linux-x64/bin/node" "/opt/ping/apps/node-v10.13.0-linux-x64/bin/npm" "i" "pm2" "-g" "--verbose"
npm verb node v10.13.0
npm verb npm  v6.4.1
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file
npm verb exit [ -5, true ]

```

## Supporting information

Node version: 10.13.0

NPM version: 6.4.1

Red Hat Enterprise Linux Server release 7.6 (Maipo)

**Comment by Unitech** [comment]
this has been fixed since we updated ssl certificates

**Comment by andrunix** [comment]
That fixed it! You’re awesome.
