### ISSUE TITLE
Not able to take snapshot

### ISSUE THREAD

**Issue by sunnysharma12** [Unitech/pm2#4023]
## What's going wrong?

While trying to take snapshot of memory, it throws an error.

## How could we reproduce this issue?

Run `pm2 snapshot`

```
root@54be7daa1c7f:/app# pm2 snapshot
Error: Heap snapshot is not available (node 10+)
    at snapshotPM2 (/usr/local/lib/node_modules/pm2/lib/Daemon.js:168:17)
    at Server.onmessage (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:104:6)
    at emitTwo (events.js:106:13)
    at RepSocket.emit (events.js:191:7)
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/rep.js:51:15)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._write (/usr/local/lib/node_modules/pm2/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:333:12)
    at writeOrBuffer (_stream_writable.js:319:5)
root@54be7daa1c7f:/app# 
```

## Supporting information

```
$ pm2 report
===============================================================================
--- PM2 REPORT (Wed Nov 14 2018 19:14:44 GMT+0530 (IST)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.2.2
node version         : 6.14.4
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
uptime               : 186min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.2.2
node version         : 6.14.4
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
cpus nb              : 4
freemem              : 281255936
totalmem             : 16820678656
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬─────────┬─────────┬──────┬────────┬─────────┬────────┬──────┬────────────┬──────┬──────────┐
│ App name │ id │ version │ mode    │ pid  │ status │ restart │ uptime │ cpu  │ mem        │ user │ watching │
├──────────┼────┼─────────┼─────────┼──────┼────────┼─────────┼────────┼──────┼────────────┼──────┼──────────┤
│ web      │ 0  │ 2.0.0   │ cluster │ 2585 │ online │ 12      │ 9m     │ 9.5% │ 489.8 MB   │ root │ disabled │
└──────────┴────┴─────────┴─────────┴──────┴────────┴─────────┴────────┴──────┴────────────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬─────────┬─────────┬──────┬────────┬─────────┬────────┬─────┬────────────┬──────┬──────────┐
│ App name │ id │ version │ mode    │ pid  │ status │ restart │ uptime │ cpu │ mem        │ user │ watching │
├──────────┼────┼─────────┼─────────┼──────┼────────┼─────────┼────────┼─────┼────────────┼──────┼──────────┤
│ web      │ 0  │ 2.0.0   │ cluster │ 2585 │ online │ 12      │ 9m     │ 0%  │ 489.8 MB   │ root │ disabled │
└──────────┴────┴─────────┴─────────┴──────┴────────┴─────────┴────────┴─────┴────────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

**Comment by vmarchaud** [comment]
`Error: Heap snapshot is not available (node 10+)`
```node version         : 6.14.4```
Also those features are only for debug, so you should be using them
