### ISSUE TITLE
pm2 startup crash instead of warning

### ISSUE THREAD

**Issue by OmgImAlexis** [Unitech/pm2#4042]
## What's going wrong?
Running `pm2 startup` causes error and then crash of pm2.

## How could we reproduce this issue?
Run `pm2 startup` on the `Unraid` OS.

## Supporting information
```
[PM2][ERROR] Init system not found
/usr/lib/node_modules/pm2/lib/API/Startup.js:201
      throw new Error('Init system not found');
      ^

Error: Init system not found
    at API.CLI.startup (/usr/lib/node_modules/pm2/lib/API/Startup.js:201:13)
    at Command.<anonymous> (/usr/lib/node_modules/pm2/bin/pm2:752:9)
    at Command.listener (/usr/lib/node_modules/pm2/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/usr/lib/node_modules/pm2/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/lib/node_modules/pm2/node_modules/commander/index.js:474:21)
    at Timeout._onTimeout (/usr/lib/node_modules/pm2/bin/pm2:220:15)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
```

```
===============================================================================
--- PM2 REPORT (Fri Nov 23 2018 17:44:11 GMT-0800 (Pacific Standard Time)) ----
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.2.2
node version         : 10.13.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
uptime               : 4min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.2.2
node version         : 10.13.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
cpus nb              : 24
freemem              : 65622220800
totalmem             : 67611373568
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬─────────┬──────┬───────┬────────┬─────────┬────────┬─────┬────────────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem        │ user │ watching │
├──────────┼────┼─────────┼──────┼───────┼────────┼─────────┼────────┼─────┼────────────┼──────┼──────────┤
│ API      │ 0  │ 0.0.0   │ fork │ 18956 │ online │ 0       │ 4m     │ 0%  │ 165.6 MB   │ root │ enabled  │
└──────────┴────┴─────────┴──────┴───────┴────────┴─────────┴────────┴─────┴────────────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬─────────┬──────┬───────┬────────┬─────────┬────────┬─────┬────────────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem        │ user │ watching │
├──────────┼────┼─────────┼──────┼───────┼────────┼─────────┼────────┼─────┼────────────┼──────┼──────────┤
│ API      │ 0  │ 0.0.0   │ fork │ 18956 │ online │ 0       │ 4m     │ 0%  │ 165.6 MB   │ root │ enabled  │
└──────────┴────┴─────────┴──────┴───────┴────────┴─────────┴────────┴─────┴────────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

## Extra
I was hoping this would just show a warning instead of the error being thrown.

**Comment by Unitech** [comment]
What kind of init system does `Unraid OS` use?

**Comment by OmgImAlexis** [comment]
It's based on slackware so [this one](http://www.slackware.com/config/init.php) I would assume. I can ask at work(I work for Unraid) though.

**Comment by OmgImAlexis** [comment]
Bad bot
