### ISSUE TITLE
output (stdout and stderr) lost in clustermode

### ISSUE THREAD

**Issue by andrewsensus** [Unitech/pm2#4075]
## What's going wrong?
output (stdout and stderr via console.log, console.error, and output of uncaught exceptions to stderr) is lost when node app running in cluster mode terminates.

## How could we reproduce this issue?

1. npm install pm2@latest -g (this was originally seen on Linux on pm2 2.10.4; it was reproduced on Windows on 2.10.4, then reproduced and the example script simplified on Windows on pm2 3.2.3)
2. node 'C:\Program Files\nodejs\node_modules\pm2\bin\pm2' start .\log-and-throw.js -i 2 --merge-logs --log-date-format='YYYY-MM-DD HH:mm:ss' --output out.log --error err.log --name log-and-throw '--' arg-to-app

## expected results

expected contents of out.log (time prepended to lines; repeated according to how many times the processes attempt to start)
1. "argv.length 3"
2. "stdout before"

expected contents of err.log (time prepended to lines; repeated according to how many times the processes attempt to start)
1. "stderr before"
2. stack trace showing no such file or directory

## actual results

actual contents of out.log (time prepended to lines; repeated according to how many times the processes attempt to start)
1. "argv.length 3"
2. MISSING: "stdout before"

actual contents of err.log (time prepended to lines; repeated according to how many times the processes attempt to start)
1. "stderr before"
2. MISSING: stack trace showing no such file or directory

Note that running under fork mode (by removing the -i entirely under 2.10.4; by passing -i 1 under 3.2.3) results in the expected output in the log files.

## Supporting information

```
$ pm2 report
```

username replaced with first.last, preserving whatever case it appeared in:
```
pm2 report
===============================================================================
--- PM2 REPORT (Fri Dec 14 2018 17:07:01 GMT-0700 (Mountain Standard Time)) ---
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.2.3
node version         : 8.11.4
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\first.last\AppData\Roaming\nvm\v8.11.4\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 6min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.2.3
node version         : 8.11.4
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Program Files\nodejs\node_modules\pm2\bin\pm2,report
argv0                : C:\Program Files\nodejs\\node.exe
user                 : First.Last
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
cpus nb              : 8
freemem              : 16592232448
totalmem             : 33936121856
home                 : C:\Users\first.last
===============================================================================
--- PM2 list -----------------------------------------------
┌───────────────┬────┬─────────┬─────────┬─────┬─────────┬─────────┬────────┬─────┬────────┬─────────────┬──────────┐
│ App name      │ id │ version │ mode    │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user        │ watching │
├───────────────┼────┼─────────┼─────────┼─────┼─────────┼─────────┼────────┼─────┼────────┼─────────────┼──────────┤
│ log-and-throw │ 0  │ 0.0.1   │ cluster │ 0   │ errored │ 15      │ 0      │ 0%  │ 0 B    │ First.Last │ disabled │
│ log-and-throw │ 1  │ 0.0.1   │ cluster │ 0   │ errored │ 15      │ 0      │ 0%  │ 0 B    │ First.Last │ disabled │
└───────────────┴────┴─────────┴─────────┴─────┴─────────┴─────────┴────────┴─────┴────────┴─────────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌───────────────┬────┬─────────┬─────────┬─────┬─────────┬─────────┬────────┬─────┬────────┬─────────────┬──────────┐
│ App name      │ id │ version │ mode    │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user        │ watching │
├───────────────┼────┼─────────┼─────────┼─────┼─────────┼─────────┼────────┼─────┼────────┼─────────────┼──────────┤
│ log-and-throw │ 0  │ 0.0.1   │ cluster │ 0   │ errored │ 15      │ 0      │ 0%  │ 0 B    │ First.Last │ disabled │
│ log-and-throw │ 1  │ 0.0.1   │ cluster │ 0   │ errored │ 15      │ 0      │ 0%  │ 0 B    │ First.Last │ disabled │
└───────────────┴────┴─────────┴─────────┴─────┴─────────┴─────────┴────────┴─────┴────────┴─────────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

## first ~50 of pm2.log, replacing username again

```
2018-12-14T17:00:56: PM2 log: ===============================================================================
2018-12-14T17:00:56: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
2018-12-14T17:00:56: PM2 log: Time                 : Fri Dec 14 2018 17:00:56 GMT-0700 (Mountain Standard Time)
2018-12-14T17:00:56: PM2 log: PM2 version          : 3.2.3
2018-12-14T17:00:56: PM2 log: Node.js version      : 8.11.4
2018-12-14T17:00:56: PM2 log: Current arch         : x64
2018-12-14T17:00:56: PM2 log: PM2 home             : C:\Users\first.last\.pm2
2018-12-14T17:00:56: PM2 log: PM2 PID file         : C:\Users\first.last\.pm2\pm2.pid
2018-12-14T17:00:56: PM2 log: RPC socket file      : \\.\pipe\rpc.sock
2018-12-14T17:00:56: PM2 log: BUS socket file      : \\.\pipe\pub.sock
2018-12-14T17:00:56: PM2 log: Application log path : C:\Users\first.last\.pm2\logs
2018-12-14T17:00:56: PM2 log: Process dump file    : C:\Users\first.last\.pm2\dump.pm2
2018-12-14T17:00:56: PM2 log: Concurrent actions   : 2
2018-12-14T17:00:56: PM2 log: SIGTERM timeout      : 1600
2018-12-14T17:00:56: PM2 log: ===============================================================================
2018-12-14T17:00:56: PM2 log: App [log-and-throw:0] starting in -cluster mode-
2018-12-14T17:00:57: PM2 log: App [log-and-throw:0] online
2018-12-14T17:00:57: PM2 log: App [log-and-throw:1] starting in -cluster mode-
2018-12-14T17:00:57: PM2 error: (node:8608) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
2018-12-14T17:00:57: PM2 log: App name:log-and-throw id:0 disconnected
2018-12-14T17:00:57: PM2 log: App [log-and-throw:0] exited with code [0] via signal [SIGINT]
2018-12-14T17:00:57: PM2 log: App [log-and-throw:0] starting in -cluster mode-
2018-12-14T17:00:57: PM2 log: App [log-and-throw:1] online
2018-12-14T17:00:57: PM2 error: (node:8608) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
2018-12-14T17:00:58: PM2 log: App name:log-and-throw id:1 disconnected
2018-12-14T17:00:58: PM2 log: App [log-and-throw:0] online
2018-12-14T17:00:58: PM2 log: App [log-and-throw:1] exited with code [0] via signal [SIGINT]
2018-12-14T17:00:58: PM2 log: App [log-and-throw:1] starting in -cluster mode-
2018-12-14T17:00:58: PM2 error: Error caught while calling pidusage
2018-12-14T17:00:58: PM2 error: Error: No maching pid found
2018-12-14T17:00:58: PM2 log: App name:log-and-throw id:0 disconnected
2018-12-14T17:00:58: PM2 log: App [log-and-throw:0] exited with code [0] via signal [SIGINT]
2018-12-14T17:00:58: PM2 log: App [log-and-throw:0] starting in -cluster mode-
2018-12-14T17:00:58: PM2 log: App [log-and-throw:1] online
2018-12-14T17:00:58: PM2 log: App [log-and-throw:0] online
2018-12-14T17:00:58: PM2 log: App name:log-and-throw id:1 disconnected
2018-12-14T17:00:58: PM2 log: App [log-and-throw:1] exited with code [0] via signal [SIGINT]
2018-12-14T17:00:58: PM2 log: App [log-and-throw:1] starting in -cluster mode-
2018-12-14T17:00:59: PM2 log: App name:log-and-throw id:0 disconnected
2018-12-14T17:00:59: PM2 log: App [log-and-throw:0] exited with code [0] via signal [SIGINT]
2018-12-14T17:00:59: PM2 log: App [log-and-throw:0] starting in -cluster mode-
2018-12-14T17:00:59: PM2 log: App [log-and-throw:1] online
2018-12-14T17:00:59: PM2 log: App [log-and-throw:0] online
2018-12-14T17:00:59: PM2 log: App name:log-and-throw id:1 disconnected
2018-12-14T17:00:59: PM2 log: App [log-and-throw:1] exited with code [0] via signal [SIGINT]
2018-12-14T17:00:59: PM2 log: App [log-and-throw:1] starting in -cluster mode-
2018-12-14T17:00:59: PM2 log: App name:log-and-throw id:0 disconnected
2018-12-14T17:00:59: PM2 log: App [log-and-throw:0] exited with code [0] via signal [SIGINT]
2018-12-14T17:00:59: PM2 log: App [log-and-throw:0] starting in -cluster mode-
2018-12-14T17:00:59: PM2 log: App [log-and-throw:1] online
```

## lines from pm2.log when running in fork mode (problem is only seen in cluster mode)

```
2018-12-14T17:32:37: PM2 log: App [log-and-throw:0] starting in -fork mode-
2018-12-14T17:32:37: PM2 log: App [log-and-throw:0] online
2018-12-14T17:32:37: PM2 log: App [log-and-throw:0] exited with code [1] via signal [SIGINT]
2018-12-14T17:32:37: PM2 log: App [log-and-throw:0] starting in -fork mode-
2018-12-14T17:32:37: PM2 log: App [log-and-throw:0] online
2018-12-14T17:32:37: PM2 error: Error caught while calling pidusage
2018-12-14T17:32:37: PM2 error: Error: No maching pid found
2018-12-14T17:32:37: PM2 log: App [log-and-throw:0] exited with code [1] via signal [SIGINT]
2018-12-14T17:32:37: PM2 log: App [log-and-throw:0] starting in -fork mode-
2018-12-14T17:32:37: PM2 log: App [log-and-throw:0] online
2018-12-14T17:32:38: PM2 log: App [log-and-throw:0] exited with code [1] via signal [SIGINT]
2018-12-14T17:32:38: PM2 log: App [log-and-throw:0] starting in -fork mode-
2018-12-14T17:32:38: PM2 log: App [log-and-throw:0] online
2018-12-14T17:32:38: PM2 log: App [log-and-throw:0] exited with code [1] via signal [SIGINT]
2018-12-14T17:32:38: PM2 log: App [log-and-throw:0] starting in -fork mode-
2018-12-14T17:32:38: PM2 log: App [log-and-throw:0] online
2018-12-14T17:32:38: PM2 error: Error caught while calling pidusage
2018-12-14T17:32:38: PM2 error: Error: No maching pid found
2018-12-14T17:32:38: PM2 log: App [log-and-throw:0] exited with code [1] via signal [SIGINT]
2018-12-14T17:32:38: PM2 log: App [log-and-throw:0] starting in -fork mode-
```
## contents of log-and-throw.js

```
'use stict';
const fs = require('fs');
console.log('argv.length', process.argv.length);
console.log('stdout before');
console.error('stderr before');
const junk = fs.readFileSync('no/such/file', 'utf8');
console.log('stdout not reached');
console.error('stderr not reached');
```

**Comment by andrewsensus** [comment]
If I make this change to pm2/lib/God/ClusterMode.js
```diff
      /*********************************
       * If you edit this function
       * Do the same in ForkMode.js !
       *********************************/
      if (msg.data && msg.type) {
+ console.log(`got msg type ${msg.type} at ${Utility.getDate()} for pid ${clu.pm2_env.pm_id} with name ${clu.pm2_env.name} rev ${(clu.pm2_env.versioning && clu.pm2_env.versioning.revision) ? clu.pm2_env.versioning.revision : null} with data ${msg.data}`);
        return God.bus.emit(msg.type ? msg.type : 'process:msg', {
          at      : Utility.getDate(),
          data    : msg.data,
```

followed by ```pm2 kill; pm2 reset all; pm2 update```, then pm2.log looks like this (with username replaced again)
```
2018-12-14T17:44:47: PM2 log: App [log-and-throw:1] exited with code [0] via signal [SIGINT]
2018-12-14T17:44:47: PM2 log: App [log-and-throw:1] starting in -cluster mode-
2018-12-14T17:44:47: PM2 log: got msg type axm:option:configuration at 1544834687899 for pid 0 with name log-and-throw rev null with data [object Object]
2018-12-14T17:44:47: PM2 log: got msg type axm:option:configuration at 1544834687905 for pid 0 with name log-and-throw rev null with data [object Object]
2018-12-14T17:44:47: PM2 log: got msg type log:out at 1544834687916 for pid 0 with name log-and-throw rev null with data 2018-12-14 17:44:47: argv.length 3

2018-12-14T17:44:47: PM2 log: got msg type log:out at 1544834687917 for pid 0 with name log-and-throw rev null with data 2018-12-14 17:44:47: stdout before

2018-12-14T17:44:47: PM2 log: got msg type log:err at 1544834687917 for pid 0 with name log-and-throw rev null with data 2018-12-14 17:44:47: stderr before

2018-12-14T17:44:47: PM2 log: got msg type log:err at 1544834687918 for pid 0 with name log-and-throw rev null with data 
Error: ENOENT: no such file or directory, open 'C:\Working\no\such\file'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (C:\Working\log-and-throw.js:6:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at C:\Users\first.last\AppData\Roaming\nvm\v8.11.4\node_modules\pm2\lib\ProcessContainer.js:295:23
    at C:\Users\first.last\AppData\Roaming\nvm\v8.11.4\node_modules\pm2\node_modules\async\internal\once.js:12:16

2018-12-14T17:44:47: PM2 log: got msg type process:exception at 1544834687918 for pid 0 with name log-and-throw rev null with data [object Object]
2018-12-14T17:44:47: PM2 log: App name:log-and-throw id:0 disconnected
2018-12-14T17:44:47: PM2 log: App [log-and-throw:0] exited with code [0] via signal [SIGINT]
2018-12-14T17:44:47: PM2 log: Script C:\Working\log-and-throw.js had too many unstable restarts (16). Stopped. "errored"
2018-12-14T17:44:47: PM2 log: App [log-and-throw:1] online
2018-12-14T17:44:48: PM2 log: got msg type axm:option:configuration at 1544834688180 for pid 1 with name log-and-throw rev null with data [object Object]
2018-12-14T17:44:48: PM2 log: got msg type axm:option:configuration at 1544834688186 for pid 1 with name log-and-throw rev null with data [object Object]
2018-12-14T17:44:48: PM2 log: got msg type log:out at 1544834688197 for pid 1 with name log-and-throw rev null with data 2018-12-14 17:44:48: argv.length 3

2018-12-14T17:44:48: PM2 log: got msg type log:out at 1544834688198 for pid 1 with name log-and-throw rev null with data 2018-12-14 17:44:48: stdout before

2018-12-14T17:44:48: PM2 log: got msg type log:err at 1544834688198 for pid 1 with name log-and-throw rev null with data 2018-12-14 17:44:48: stderr before

2018-12-14T17:44:48: PM2 log: got msg type log:err at 1544834688199 for pid 1 with name log-and-throw rev null with data 
Error: ENOENT: no such file or directory, open 'C:\Working\no\such\file'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (C:\Working\log-and-throw.js:6:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at C:\Users\first.last\AppData\Roaming\nvm\v8.11.4\node_modules\pm2\lib\ProcessContainer.js:295:23
    at C:\Users\first.last\AppData\Roaming\nvm\v8.11.4\node_modules\pm2\node_modules\async\internal\once.js:12:16

2018-12-14T17:44:48: PM2 log: got msg type process:exception at 1544834688199 for pid 1 with name log-and-throw rev null with data [object Object]
2018-12-14T17:44:48: PM2 log: App name:log-and-throw id:1 disconnected
2018-12-14T17:44:48: PM2 log: App [log-and-throw:1] exited with code [0] via signal [SIGINT]
2018-12-14T17:44:48: PM2 log: Script C:\Working\log-and-throw.js had too many unstable restarts (16). Stopped. "errored"
```

I think what's happening is that pm2 is successfully emitting to ```God.bus.emit```, but it doesn't do anything because the actual writing to err.log and out.log follows a different path (possibly in a different process?). Possibly the relevant path is ```process.stdout.write```, ```process.stderr.write```, and ```getUncaughtExceptionListener``` in ```pm2/lib/ProcessContainer.js```, but it isn't clear that output is making it there or whether it should.

**Comment by andrewsensus** [comment]
I tried running with environment variables ```DEBUG``` set to ```pm2:*``` and ```PM2_DEBUG``` set to ```true``` as suggested here: https://github.com/Unitech/pm2/blob/master/.github/CONTRIBUTING.md, but I didn't notice any differences.

**Comment by andrewsensus** [comment]
@Unitech To be clear, this was originally seen on Linux, but I developed the simplified reproducible on Windows. Here's corresponding output on Linux.

## pm2 start

```
[ahart@web01 ~]$ pm2 start ./log-and-throw.js -i 2 --merge-logs --log-date-format='YYYY-MM-DD HH:mm:ss' --output out.log --error err.log --name log-and-throw -- arg-to-app
[PM2] Starting /home/ahart/log-and-throw.js in cluster_mode (2 instances)
[PM2] Done.
┌───────────────┬────┬─────────┬──────┬───────────┬─────────┬────────┬─────┬───────────┬───────┬──────────┐
│ App name      │ id │ mode    │ pid  │ status    │ restart │ uptime │ cpu │ mem       │ user  │ watching │
├───────────────┼────┼─────────┼──────┼───────────┼─────────┼────────┼─────┼───────────┼───────┼──────────┤
│ log-and-throw │ 0  │ cluster │ 5153 │ launching │ 1       │ 0      │ 0%  │ 0 B       │ ahart │ disabled │
│ log-and-throw │ 1  │ cluster │ 5143 │ online    │ 0       │ 0s     │ 22% │ 19.4 MB   │ ahart │ disabled │
└───────────────┴────┴─────────┴──────┴───────────┴─────────┴────────┴─────┴───────────┴───────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

## pm2 report

```
[ahart@web01 ~]$ pm2 report
===============================================================================
--- PM2 REPORT (Mon Dec 17 2018 20:08:45 GMT+0000 (GMT)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.4
node version         : 8.11.4
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : ahart
uid                  : 30456
gid                  : 1000
uptime               : 161min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.4
node version         : 8.11.4
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : ahart
uid                  : 30456
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz
cpus nb              : 4
freemem              : 2686488576
totalmem             : 8201424896
home                 : /home/ahart
===============================================================================
--- PM2 list -----------------------------------------------
┌───────────────┬────┬─────────┬─────┬─────────┬─────────┬────────┬─────┬────────┬───────┬──────────┐
│ App name      │ id │ mode    │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user  │ watching │
├───────────────┼────┼─────────┼─────┼─────────┼─────────┼────────┼─────┼────────┼───────┼──────────┤
│ log-and-throw │ 0  │ cluster │ 0   │ errored │ 15      │ 0      │ 0%  │ 0 B    │ ahart │ disabled │
│ log-and-throw │ 1  │ cluster │ 0   │ errored │ 15      │ 0      │ 0%  │ 0 B    │ ahart │ disabled │
└───────────────┴────┴─────────┴─────┴─────────┴─────────┴────────┴─────┴────────┴───────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/home/ahart/.pm2/pm2.log last 20 lines:
PM2        | [2018-12-17 17:29:01] PM2 log: App name:log-and-throw id:1 online
PM2        | [2018-12-17 17:29:01] PM2 log: App name:log-and-throw id:0 online
PM2        | [2018-12-17 17:29:01] PM2 log: App name:log-and-throw id:1 disconnected
PM2        | [2018-12-17 17:29:01] PM2 log: App [log-and-throw] with id [1] and pid [5415], exited with code [0] via signal [SIGINT]
PM2        | [2018-12-17 17:29:01] PM2 log: Starting execution sequence in -cluster mode- for app name:log-and-throw id:1
PM2        | [2018-12-17 17:29:01] PM2 log: App name:log-and-throw id:0 disconnected
PM2        | [2018-12-17 17:29:01] PM2 log: App [log-and-throw] with id [0] and pid [5421], exited with code [0] via signal [SIGINT]
PM2        | [2018-12-17 17:29:01] PM2 log: Starting execution sequence in -cluster mode- for app name:log-and-throw id:0
PM2        | [2018-12-17 17:29:01] PM2 log: App name:log-and-throw id:1 online
PM2        | [2018-12-17 17:29:01] PM2 log: App name:log-and-throw id:0 online
PM2        | [2018-12-17 17:29:01] PM2 log: App name:log-and-throw id:1 disconnected
PM2        | [2018-12-17 17:29:01] PM2 log: App [log-and-throw] with id [1] and pid [5435], exited with code [0] via signal [SIGINT]
PM2        | [2018-12-17 17:29:01] PM2 log: Starting execution sequence in -cluster mode- for app name:log-and-throw id:1
PM2        | [2018-12-17 17:29:01] PM2 log: App name:log-and-throw id:0 disconnected
PM2        | [2018-12-17 17:29:01] PM2 log: App [log-and-throw] with id [0] and pid [5441], exited with code [0] via signal [SIGINT]
PM2        | [2018-12-17 17:29:01] PM2 log: Script /home/ahart/log-and-throw.js had too many unstable restarts (16). Stopped. "errored"
PM2        | [2018-12-17 17:29:01] PM2 log: App name:log-and-throw id:1 online
PM2        | [2018-12-17 17:29:01] PM2 log: App name:log-and-throw id:1 disconnected
PM2        | [2018-12-17 17:29:01] PM2 log: App [log-and-throw] with id [1] and pid [5455], exited with code [0] via signal [SIGINT]
PM2        | [2018-12-17 17:29:01] PM2 log: Script /home/ahart/log-and-throw.js had too many unstable restarts (16). Stopped. "errored"

Please copy/paste the above report in your issue on https://github.com/Unitech/pm2/issues
```

## out.log

notice the lack of "stdout before":
```
[ahart@web01 ~]$ cat out.log 
2018-12-17 17:28:57: argv.length 3
2018-12-17 17:28:57: argv.length 3
2018-12-17 17:28:57: argv.length 3
2018-12-17 17:28:58: argv.length 3
2018-12-17 17:28:58: argv.length 3
2018-12-17 17:28:58: argv.length 3
2018-12-17 17:28:58: argv.length 3
2018-12-17 17:28:58: argv.length 3
2018-12-17 17:28:58: argv.length 3
2018-12-17 17:28:59: argv.length 3
2018-12-17 17:28:59: argv.length 3
2018-12-17 17:28:59: argv.length 3
2018-12-17 17:28:59: argv.length 3
2018-12-17 17:28:59: argv.length 3
2018-12-17 17:28:59: argv.length 3
2018-12-17 17:28:59: argv.length 3
2018-12-17 17:28:59: argv.length 3
2018-12-17 17:29:00: argv.length 3
2018-12-17 17:29:00: argv.length 3
2018-12-17 17:29:00: argv.length 3
2018-12-17 17:29:00: argv.length 3
2018-12-17 17:29:00: argv.length 3
2018-12-17 17:29:00: argv.length 3
2018-12-17 17:29:00: argv.length 3
2018-12-17 17:29:00: argv.length 3
2018-12-17 17:29:01: argv.length 3
2018-12-17 17:29:01: argv.length 3
2018-12-17 17:29:01: argv.length 3
2018-12-17 17:29:01: argv.length 3
2018-12-17 17:29:01: argv.length 3
2018-12-17 17:29:01: argv.length 3
2018-12-17 17:29:01: argv.length 3
```

## err.log

notice lack of stack trace:
```
[ahart@web01 ~]$ cat err.log 
2018-12-17 17:28:57: stderr before
2018-12-17 17:28:57: stderr before
2018-12-17 17:28:57: stderr before
2018-12-17 17:28:58: stderr before
2018-12-17 17:28:58: stderr before
2018-12-17 17:28:58: stderr before
2018-12-17 17:28:58: stderr before
2018-12-17 17:28:58: stderr before
2018-12-17 17:28:58: stderr before
2018-12-17 17:28:59: stderr before
2018-12-17 17:28:59: stderr before
2018-12-17 17:28:59: stderr before
2018-12-17 17:28:59: stderr before
2018-12-17 17:28:59: stderr before
2018-12-17 17:28:59: stderr before
2018-12-17 17:28:59: stderr before
2018-12-17 17:28:59: stderr before
2018-12-17 17:29:00: stderr before
2018-12-17 17:29:00: stderr before
2018-12-17 17:29:00: stderr before
2018-12-17 17:29:00: stderr before
2018-12-17 17:29:00: stderr before
2018-12-17 17:29:00: stderr before
2018-12-17 17:29:00: stderr before
2018-12-17 17:29:00: stderr before
2018-12-17 17:29:01: stderr before
2018-12-17 17:29:01: stderr before
2018-12-17 17:29:01: stderr before
2018-12-17 17:29:01: stderr before
2018-12-17 17:29:01: stderr before
2018-12-17 17:29:01: stderr before
2018-12-17 17:29:01: stderr before
```

**Comment by pc-jedi** [comment]
I have the same issue

**Comment by andrewsensus** [comment]
Any volunteers to dig further?

**Comment by andrewsensus** [comment]
bump

**Comment by andrewsensus** [comment]
bump

**Comment by zyf0330** [comment]
I have seen that commit 004b7846c9a00cdc88855ef29ce02ab4dced0379 commented code which makes sure log directories existing.
As for root cause I don't find. I use docker and pm2-runtime to run node app, and if I exec `pm2 ls` to start pm2 process firstly before `pm2-runtime start app.yml`, this error won't occur.
