### ISSUE TITLE
dgram is not working with PM2

### ISSUE THREAD

**Issue by andrew-medvedev** [Unitech/pm2#4087]
I'm into problem with using dgram with pm2 as cluster.

Make a simple script

```
var datagram = require('dgram');
var udpServer = datagram.createSocket('udp4');
udpServer.bind(13377);
```

Run it as cluster (exec_mode=cluster, instances=2) and you will get an error:

```
Error: write ENOTSUP
PM2          |     at ChildProcess.target._send (internal/child_process.js:742:20)
PM2          |     at ChildProcess.target.send (internal/child_process.js:626:19)
PM2          |     at sendHelper (internal/cluster/utils.js:24:15)
PM2          |     at send (internal/cluster/master.js:356:10)
PM2          |     at handle.add (internal/cluster/master.js:328:5)
PM2          |     at SharedHandle.add (internal/cluster/shared_handle.js:29:3)
PM2          |     at queryServer (internal/cluster/master.js:317:10)
PM2          |     at Worker.onmessage (internal/cluster/master.js:252:5)
PM2          |     at ChildProcess.onInternalMessage (internal/cluster/utils.js:45:8)
PM2          |     at ChildProcess.emit (events.js:187:15)
```

`node -v` = v10.14.2

`pm2 report`

```
===============================================================================
--- PM2 REPORT (Wed Dec 26 2018 12:56:10 GMT+0500 (GMT+05:00)) ----------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.2.4
node version         : 10.14.2
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\ihatemicrosoft1\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 11min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.2.4
node version         : 10.14.2
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\ihatemicrosoft1\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : node
user                 : ihatemicrosoft1
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
cpus nb              : 8
freemem              : 906055680
totalmem             : 4139626496
home                 : C:\Users\ihatemicrosoft1
===============================================================================
--- PM2 list -----------------------------------------------
┌─────────────┬────┬─────────┬─────────┬─────┬─────────┬─────────┬────────┬─────┬────────┬─────────────────┬──────────┐
│ App name    │ id │ version │ mode    │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user            │ watching │
├─────────────┼────┼─────────┼─────────┼─────┼─────────┼─────────┼────────┼─────┼────────┼─────────────────┼──────────┤
│ pm2-is-nice │ 0  │ 2.6.28  │ cluster │ 0   │ errored │ 0       │ 0      │ 0%  │ 0 B    │ ihatemicrosoft1 │ disabled │
│ pm2-is-nice │ 1  │ 2.6.28  │ cluster │ 0   │ errored │ 0       │ 0      │ 0%  │ 0 B    │ ihatemicrosoft1 │ disabled │
└─────────────┴────┴─────────┴─────────┴─────┴─────────┴─────────┴────────┴─────┴────────┴─────────────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌─────────────┬────┬─────────┬─────────┬─────┬─────────┬─────────┬────────┬─────┬────────┬─────────────────┬──────────┐
│ App name    │ id │ version │ mode    │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user            │ watching │
├─────────────┼────┼─────────┼─────────┼─────┼─────────┼─────────┼────────┼─────┼────────┼─────────────────┼──────────┤
│ pm2-is-nice │ 0  │ 2.6.28  │ cluster │ 0   │ errored │ 0       │ 0      │ 0%  │ 0 B    │ ihatemicrosoft1 │ disabled │
│ pm2-is-nice │ 1  │ 2.6.28  │ cluster │ 0   │ errored │ 0       │ 0      │ 0%  │ 0 B    │ ihatemicrosoft1 │ disabled │
└─────────────┴────┴─────────┴─────────┴─────┴─────────┴─────────┴────────┴─────┴────────┴─────────────────┴──────────┘
```

**Comment by andrew-medvedev** [comment]
Am I right that udp sharing is not supported on Win at all?

**Comment by Unitech** [comment]
Yes confirmed, it works as expected on linux, not on windows

**Comment by hfranco346** [comment]
i have the same problem in cluster udp server in node with dgram package!
