### ISSUE TITLE
defaultInterpreter is not defined in Common.js

### ISSUE THREAD

**Issue by ccamensuli** [Unitech/pm2#4106]
## What's going wrong?

defaultInterpreter  is not defined Common.js:416 

```
 Wed Jan 09 2019 13:19:14 ERROR nodefony : [ ReferenceError: defaultInterpreter is not defined
      at Object.Common.sink.resolveInterpreter (/Users/cci/repository/nodefony-core/src/nodefony/node_modules/pm2/lib/Common.js:416:66)
      at Object.Common.prepareAppConf (/Users/cci/repository/nodefony-core/src/nodefony/node_modules/pm2/lib/Common.js:206:15)
      at Object.Common.resolveAppAttributes (/Users/cci/repository/nodefony-core/src/nodefony/node_modules/pm2/lib/Common.js:610:20)
      at /Users/cci/repository/nodefony-core/src/nodefony/node_modules/pm2/lib/API.js:1064:35
      at /Users/cci/repository/nodefony-core/src/nodefony/node_modules/async/internal/withoutIndex.js:9:16
      at replenish (/Users/cci/repository/nodefony-core/src/nodefony/node_modules/async/internal/eachOfLimit.js:66:17)
      at /Users/cci/repository/nodefony-core/src/nodefony/node_modules/async/internal/eachOfLimit.js:71:9
      at eachLimit (/Users/cci/repository/nodefony-core/src/nodefony/node_modules/async/eachLimit.js:43:36)
      at startApps (/Users/cci/repository/nodefony-core/src/nodefony/node_modules/pm2/lib/API.js:1048:7)
      at /Users/cci/repository/nodefony-core/src/nodefony/node_modules/pm2/lib/API.js:1029:16
      at /Users/cci/repository/nodefony-core/src/nodefony/node_modules/async/internal/once.js:12:16
      at replenish (/Users/cci/repository/nodefony-core/src/nodefony/node_modules/async/internal/eachOfLimit.js:61:25)
      at /Users/cci/repository/nodefony-core/src/nodefony/node_modules/async/internal/eachOfLimit.js:71:9
      at eachLimit (/Users/cci/repository/nodefony-core/src/nodefony/node_modules/async/eachLimit.js:43:36)
      at /Users/cci/repository/nodefony-core/src/nodefony/node_modules/pm2/lib/API.js:982:7
      at /Users/cci/repository/nodefony-core/src/nodefony/node_modules/pm2-axon-rpc/lib/client.js:45:10 ]
```
## Supporting information

```
$ pm2 report
--- PM2 report ----------------------------------------------------------------
Date                 : Wed Jan 09 2019 13:19:20 GMT+0100 (GMT+01:00)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.2.5
node version         : 10.15.0
node path            : /Users/cci/.nvm/versions/node/v10.15.0/bin/nodefony
argv                 : /Users/cci/.nvm/versions/node/v10.15.0/bin/node,/Users/cci/repository/nodefony-core/src/nodefony/node_modules/pm2/lib/Daemon.js
argv0                : /Users/cci/.nvm/versions/node/v10.15.0/bin/node
user                 : cci
uid                  : 501
gid                  : 20
uptime               : 45min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.2.5
node version         : 10.15.0
node path            : ./src/nodefony/node_modules/.bin/pm2
argv                 : /Users/cci/.nvm/versions/node/v10.15.0/bin/node,/Users/cci/repository/nodefony-core/src/nodefony/node_modules/.bin/pm2,report
argv0                : node
user                 : cci
uid                  : 501
gid                  : 20
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : darwin
type                 : Darwin
cpus                 : Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
cpus nb              : 8
freemem              : 167268352
totalmem             : 17179869184
home                 : /Users/cci
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬─────────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴─────────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/Users/cci/.pm2/pm2.log last 20 lines:
PM2        | 2019-01-09T12:33:45: PM2 log: pid=87081 msg=process killed
PM2        | 2019-01-09T12:33:45: PM2 log: App name:nodefony-starter id:7 disconnected
PM2        | 2019-01-09T12:33:45: PM2 log: App [nodefony-starter:7] exited with code [0] via signal [SIGINT]
PM2        | 2019-01-09T12:33:45: PM2 log: pid=87086 msg=process killed
PM2        | 2019-01-09T12:33:45: PM2 log: PM2 successfully stopped
PM2        | 2019-01-09T12:33:52: PM2 log: ===============================================================================
PM2        | 2019-01-09T12:33:52: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2019-01-09T12:33:52: PM2 log: Time                 : Wed Jan 09 2019 12:33:52 GMT+0100 (GMT+01:00)
PM2        | 2019-01-09T12:33:52: PM2 log: PM2 version          : 3.2.5
PM2        | 2019-01-09T12:33:52: PM2 log: Node.js version      : 10.15.0
PM2        | 2019-01-09T12:33:52: PM2 log: Current arch         : x64
PM2        | 2019-01-09T12:33:52: PM2 log: PM2 home             : /Users/cci/.pm2
PM2        | 2019-01-09T12:33:52: PM2 log: PM2 PID file         : /Users/cci/.pm2/pm2.pid
PM2        | 2019-01-09T12:33:52: PM2 log: RPC socket file      : /Users/cci/.pm2/rpc.sock
PM2        | 2019-01-09T12:33:52: PM2 log: BUS socket file      : /Users/cci/.pm2/pub.sock
PM2        | 2019-01-09T12:33:52: PM2 log: Application log path : /Users/cci/.pm2/logs
PM2        | 2019-01-09T12:33:52: PM2 log: Process dump file    : /Users/cci/.pm2/dump.pm2
PM2        | 2019-01-09T12:33:52: PM2 log: Concurrent actions   : 2
PM2        | 2019-01-09T12:33:52: PM2 log: SIGTERM timeout      : 1600
PM2        | 2019-01-09T12:33:52: PM2 log: ===============================================================================

```

**Comment by mbotmcc** [comment]
same issue here

**Comment by JounQin** [comment]
Then another error occurs: `Cannot read property 'indexOf' of undefined`...

**Comment by Unitech** [comment]
which node.js version are you using?

**Comment by JounQin** [comment]
@Unitech `node -v v11.3.0`

**Comment by Unitech** [comment]
could you share your ecosystem file please or the way you start your script

**Comment by JounQin** [comment]
`pm2 start --wait-ready npm -- start`

**Comment by Unitech** [comment]
I've reverted the fix tentative to support node managed by Ubuntu snap for now. It has been published to keep the previous behavior. Sorry for the unexpected

**Comment by ccamensuli** [comment]
For me in Common.js  :

process.execPath = /Users/cci/.nvm/versions/node/v10.15.0/bin/node 
app.pm_exec_path = /Users/cci/.nvm/versions/node/v10.15.0/bin/nodefony 
betterInterpreter = undefined

```
 Wed Jan 09 2019 16:45:56 ERROR nodefony : [ TypeError: Cannot read property 'indexOf' of undefined
      at Object.Common.sink.resolveInterpreter (/Users/cci/repository/nodefony-core/src/nodefony/node_modules/pm2/lib/Common.js:420:28)
      at Object.Common.prepareAppConf (/Users/cci/repository/nodefony-core/src/nodefony/node_modules/pm2/lib/Common.js:206:15)
      at Object.Common.resolveAppAttributes (/Users/cci/repository/nodefony-core/src/nodefony/node_modules/pm2/lib/Common.js:610:20)
      at /Users/cci/repository/nodefony-core/src/nodefony/node_modules/pm2/lib/API.js:1064:35
      at /Users/cci/repository/nodefony-core/src/nodefony/node_modules/async/internal/withoutIndex.js:9:16
      at replenish (/Users/cci/repository/nodefony-core/src/nodefony/node_modules/async/internal/eachOfLimit.js:66:17)
      at /Users/cci/repository/nodefony-core/src/nodefony/node_modules/async/internal/eachOfLimit.js:71:9
      at eachLimit (/Users/cci/repository/nodefony-core/src/nodefony/node_modules/async/eachLimit.js:43:36)
      at startApps (/Users/cci/repository/nodefony-core/src/nodefony/node_modules/pm2/lib/API.js:1048:7)
      at /Users/cci/repository/nodefony-core/src/nodefony/node_modules/pm2/lib/API.js:1029:16
      at /Users/cci/repository/nodefony-core/src/nodefony/node_modules/async/internal/once.js:12:16
      at replenish (/Users/cci/repository/nodefony-core/src/nodefony/node_modules/async/internal/eachOfLimit.js:61:25)
      at /Users/cci/repository/nodefony-core/src/nodefony/node_modules/async/internal/eachOfLimit.js:71:9
      at eachLimit (/Users/cci/repository/nodefony-core/src/nodefony/node_modules/async/eachLimit.js:43:36)
      at /Users/cci/repository/nodefony-core/src/nodefony/node_modules/pm2/lib/API.js:982:7
      at /Users/cci/repository/nodefony-core/src/nodefony/node_modules/pm2-axon-rpc/lib/client.js:45:10 ]
````

**Comment by mbotmcc** [comment]
can this be re-opened as it's still broken

**Comment by mbotmcc** [comment]
@dlevel yup that's what we did, just finished updating all our projects
