### ISSUE TITLE
process still running after `pm2 stop all`

### ISSUE THREAD

**Issue by joshhopkins** [Unitech/pm2#4136]
## What's going wrong?

From what I can tell from the docs, `pm2 stop` should "kill the process but keep it in the process list"

## How could we reproduce this issue?

1. `pm2 start`
2. `pm2 stop all`
3. `pm2 ls` – shows processes in list with status = stopped
4. Node processes continue to run in the background

Is this expected behaviour?

## Supporting information

Created after running `pm2 kill`

```
--- PM2 report ----------------------------------------------------------------
Date                 : Wed Jan 23 2019 19:13:15 GMT+0100 (Central European Standard Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.2.9
node version         : 11.7.0
node path            : /Users/joshhopkins/.nvm/versions/node/v11.7.0/bin/pm2
argv                 : /Users/joshhopkins/.nvm/versions/node/v11.7.0/bin/node,/Users/joshhopkins/.nvm/versions/node/v11.7.0/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : joshhopkins
uid                  : 501
gid                  : 20
uptime               : 119min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.2.9
node version         : 11.7.0
node path            : /Users/joshhopkins/.nvm/versions/node/v11.7.0/bin/pm2
argv                 : /Users/joshhopkins/.nvm/versions/node/v11.7.0/bin/node,/Users/joshhopkins/.nvm/versions/node/v11.7.0/bin/pm2,report
argv0                : node
user                 : joshhopkins
uid                  : 501
gid                  : 20
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : darwin
type                 : Darwin
cpus                 : Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
cpus nb              : 8
freemem              : 19292160
totalmem             : 17179869184
home                 : /Users/joshhopkins
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬─────────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴─────────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/Users/joshhopkins/.pm2/pm2.log last 20 lines:
PM2        |     at Object.God.softReloadProcessId (/Users/joshhopkins/.nvm/versions/node/v11.7.0/lib/node_modules/pm2/lib/God/Reload.js:185:17)
PM2        |     at CronJob.onTick (/Users/joshhopkins/.nvm/versions/node/v11.7.0/lib/node_modules/pm2/lib/Worker.js:40:13)
PM2        |     at CronJob.fireOnTick (/Users/joshhopkins/.nvm/versions/node/v11.7.0/lib/node_modules/pm2/node_modules/cron/lib/cron.js:546:23)
PM2        |     at Timeout.callbackWrapper [as _onTimeout] (/Users/joshhopkins/.nvm/versions/node/v11.7.0/lib/node_modules/pm2/node_modules/cron/lib/cron.js:613:10)
PM2        |     at listOnTimeout (timers.js:324:15)
PM2        |     at processTimers (timers.js:268:5)
PM2        | 2019-01-23T19:12:00: PM2 error: Error: PM ID unknown
PM2        |     at Object.God.softReloadProcessId (/Users/joshhopkins/.nvm/versions/node/v11.7.0/lib/node_modules/pm2/lib/God/Reload.js:185:17)
PM2        |     at CronJob.onTick (/Users/joshhopkins/.nvm/versions/node/v11.7.0/lib/node_modules/pm2/lib/Worker.js:40:13)
PM2        |     at CronJob.fireOnTick (/Users/joshhopkins/.nvm/versions/node/v11.7.0/lib/node_modules/pm2/node_modules/cron/lib/cron.js:546:23)
PM2        |     at Timeout.callbackWrapper [as _onTimeout] (/Users/joshhopkins/.nvm/versions/node/v11.7.0/lib/node_modules/pm2/node_modules/cron/lib/cron.js:613:10)
PM2        |     at listOnTimeout (timers.js:324:15)
PM2        |     at processTimers (timers.js:268:5)
PM2        | 2019-01-23T19:13:00: PM2 error: Error: PM ID unknown
PM2        |     at Object.God.softReloadProcessId (/Users/joshhopkins/.nvm/versions/node/v11.7.0/lib/node_modules/pm2/lib/God/Reload.js:185:17)
PM2        |     at CronJob.onTick (/Users/joshhopkins/.nvm/versions/node/v11.7.0/lib/node_modules/pm2/lib/Worker.js:40:13)
PM2        |     at CronJob.fireOnTick (/Users/joshhopkins/.nvm/versions/node/v11.7.0/lib/node_modules/pm2/node_modules/cron/lib/cron.js:546:23)
PM2        |     at Timeout.callbackWrapper [as _onTimeout] (/Users/joshhopkins/.nvm/versions/node/v11.7.0/lib/node_modules/pm2/node_modules/cron/lib/cron.js:613:10)
PM2        |     at listOnTimeout (timers.js:324:15)
PM2        |     at processTimers (timers.js:268:5)
```

**Comment by MaffooBristol** [comment]
I had this issue too running with `--cron`

After stopping and deleting a process that was started with the cron flag, it apparently kept trying to restart the process but it didn't exist anymore. So perhaps related?

**Comment by joshhopkins** [comment]
Sounds like it @MaffooBristol. In my case there was also a forked process running with `cron_restart`.

**Comment by BarryThrill** [comment]
I am also having this issue. With python scripts.

**Comment by Gennttii** [comment]
I am having same problem, but with deleted processes, I can see actions of previous processes which are not available in new ones.. Hope this will be fixed soon!

**Comment by creativiii** [comment]
Yeah same here. I need to restart my whole machine to stop processes.

**Comment by Unitech** [comment]
x https://github.com/Unitech/pm2/issues/4485

**Comment by nikita-fuchs** [comment]
I am having the same issue right now, even after `pm2 kill` nodejs processes are being restarted. `pm2 list` shows an empty list already, but even after restart pm2 fires up those nodejs scripts again.

**Comment by KerimCisneros** [comment]
I had the same issue. What worked for me was uninstalling PM2, and even after that, I had to stop the Node services.

- Windows Server 2019 standard.
- Node version 20.11.1
