### ISSUE TITLE
On reboot -> PM2 error: Trace: { Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by ClearlyDazed** [Unitech/pm2#4139]
Hello, I'm looking for any clues on how to fix this.
  
On reboot of my single board computer (Odroid XU4) running Ubuntu 18.04, PM2 reports that it can not find the directory that holds the error and output logs which are on a USB drive connected to the Odroid, mounted to the media directory. The PM2 log (this is located on the ram disk of the Odroid) reports:

2019-01-25T13:31:09: PM2 log: App [camera:0] starting in -fork mode-
2019-01-25T13:31:09: PM2 log: App [cron:1] starting in -fork mode-
2019-01-25T13:31:09: PM2 error: Trace: { Error: ENOENT: no such file or directory, open '/media/odroid/Odroid_HD/Data/pm2_logs/camera-out.log'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/media/odroid/Odroid_HD/Data/pm2_logs/camera-out.log' }
    at Object.God.logAndGenerateError (/root/.nvm/versions/node/v9.9.0/lib/node_modules/pm2/lib/God/Methods.js:34:15)
    at /root/.nvm/versions/node/v9.9.0/lib/node_modules/pm2/lib/God/ForkMode.js:86:13
    at /root/.nvm/versions/node/v9.9.0/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16
    at WriteStream.next (/root/.nvm/versions/node/v9.9.0/lib/node_modules/pm2/node_modules/async/waterfall.js:21:29)
    at WriteStream.<anonymous> (/root/.nvm/versions/node/v9.9.0/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16)
    at Object.onceWrapper (events.js:272:13)
    at WriteStream.emit (events.js:180:13)
    at WriteStream.emit (domain.js:421:20)
    at fs.open (fs.js:2231:12)
    at FSReqWrap.oncomplete (fs.js:153:20)

I have tried various ways to remedy this, from changing the ecosystem file with exp_backoff_restart, restart_delay; changing the pm2-root.service to wait for the mounting of the USB drive; creating a symlink under the home directory to the drive directory, all to no avail. 

After reboot I can manually resurrect PM2 processes. It seems that PM2 does not wait for the system to completely load before running.

PM2 is set up with startup systemd and is saved to the dump file. 

The ecosystem file is:
module.exports = 
{ 
  apps : 
  [
    {
    name   : "camera",
    script : "/home/Shinobi/camera.js",
	error_file : "/media/odroid/Odroid_HD/Data/pm2_logs/camera-err.log",
    out_file : "/media/odroid/Odroid_HD/Data/pm2_logs/camera-out.log"
	}
   ,{
	name   : "cron",
    script : "/home/Shinobi/cron.js",
	error_file : "/media/odroid/Odroid_HD/Data/pm2_logs/cron-err.log",
    out_file : "/media/odroid/Odroid_HD/Data/pm2_logs/cron-out.log"
	}
  ]
}

The pm2-root.service file is:
[Unit]
Description=PM2 process manager
Documentation=https://pm2.keymetrics.io/
After=network.target

[Service]
Type=forking
User=root
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
Environment=PATH=/root/.nvm/versions/node/v9.9.0/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
Environment=PM2_HOME=/root/.pm2
PIDFile=/root/.pm2/pm2.pid

ExecStart=/root/.nvm/versions/node/v9.9.0/lib/node_modules/pm2/bin/pm2 resurrect
ExecReload=/root/.nvm/versions/node/v9.9.0/lib/node_modules/pm2/bin/pm2 reload all
ExecStop=/root/.nvm/versions/node/v9.9.0/lib/node_modules/pm2/bin/pm2 kill

[Install]
WantedBy=multi-user.target

The output from PM2 report is:
--- PM2 report ----------------------------------------------------------------
Date                 : Fri Jan 25 2019 15:19:42 GMT-0600 (CST)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.2.9
node version         : 9.9.0
node path            : /root/.nvm/versions/node/v9.9.0/bin/pm2
argv                 : /root/.nvm/versions/node/v9.9.0/bin/node,/root/.nvm/versions/node/v9.9.0/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
uptime               : 104min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.2.9
node version         : 9.9.0
node path            : /root/.nvm/versions/node/v9.9.0/bin/pm2
argv                 : /root/.nvm/versions/node/v9.9.0/bin/node,/root/.nvm/versions/node/v9.9.0/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : arm
platform             : linux
type                 : Linux
cpus                 : ARMv7 Processor rev 3 (v7l)
cpus nb              : 8
freemem              : 1228922880
totalmem             : 2091458560
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬─────────┬──────┬──────┬────────┬─────────┬────────┬──────┬────────────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid  │ status │ restart │ uptime │ cpu  │ mem        │ user │ watching │
├──────────┼────┼─────────┼──────┼──────┼────────┼─────────┼────────┼──────┼────────────┼──────┼──────────┤
│ camera   │ 0  │ 1.0.38  │ fork │ 2418 │ online │ 0       │ 104m   │ 4.3% │ 124.6 MB   │ root │ disabled │
│ cron     │ 1  │ 1.0.38  │ fork │ 2424 │ online │ 0       │ 104m   │ 0%   │ 54.9 MB    │ root │ disabled │
└──────────┴────┴─────────┴──────┴──────┴────────┴─────────┴────────┴──────┴────────────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/root/.pm2/pm2.log last 20 lines:
PM2        | 2019-01-25T13:34:48: PM2 log: PM2 successfully stopped
PM2        | 2019-01-25T13:35:09: PM2 log: ===============================================================================
PM2        | 2019-01-25T13:35:09: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2019-01-25T13:35:09: PM2 log: Time                 : Fri Jan 25 2019 13:35:09 GMT-0600 (CST)
PM2        | 2019-01-25T13:35:09: PM2 log: PM2 version          : 3.2.9
PM2        | 2019-01-25T13:35:09: PM2 log: Node.js version      : 9.9.0
PM2        | 2019-01-25T13:35:09: PM2 log: Current arch         : arm
PM2        | 2019-01-25T13:35:09: PM2 log: PM2 home             : /root/.pm2
PM2        | 2019-01-25T13:35:09: PM2 log: PM2 PID file         : /root/.pm2/pm2.pid
PM2        | 2019-01-25T13:35:09: PM2 log: RPC socket file      : /root/.pm2/rpc.sock
PM2        | 2019-01-25T13:35:09: PM2 log: BUS socket file      : /root/.pm2/pub.sock
PM2        | 2019-01-25T13:35:09: PM2 log: Application log path : /root/.pm2/logs
PM2        | 2019-01-25T13:35:09: PM2 log: Process dump file    : /root/.pm2/dump.pm2
PM2        | 2019-01-25T13:35:09: PM2 log: Concurrent actions   : 2
PM2        | 2019-01-25T13:35:09: PM2 log: SIGTERM timeout      : 1600
PM2        | 2019-01-25T13:35:09: PM2 log: ===============================================================================
PM2        | 2019-01-25T13:35:09: PM2 log: App [camera:0] starting in -fork mode-
PM2        | 2019-01-25T13:35:09: PM2 log: App [cron:1] starting in -fork mode-
PM2        | 2019-01-25T13:35:09: PM2 log: App [camera:0] online
PM2        | 2019-01-25T13:35:09: PM2 log: App [cron:1] online

Thanks

**Comment by ClearlyDazed** [comment]
I resolved this issue by following this link: https://askubuntu.com/questions/164926/how-to-make-partitions-mount-at-startup , which basically reconfigures the drive to mount at startup.
