### ISSUE TITLE
Latest PM2 version not working with latest enmap database

### ISSUE THREAD

**Issue by tomo92s** [Unitech/pm2#4201]
I have this error when i write **pm2 start app.js**

PM2 version: 3.4.0
Enmap version: 4.8.1

```
name: 'EnmapError',
  message:
   'Wrong value type provided for options.defer:  Provided "WrappedPromise", expecting "Promise", in enmap "settings".' }
{ EnmapError: Wrong value type provided for options.defer:  Provided "WrappedPromise", expecting "Promise", in enmap "settings".
    at Map.[_defineSetting] (/home/pi/senubot/node_modules/enmap/src/index.js:1061:13)
    at new Enmap (/home/pi/senubot/node_modules/enmap/src/index.js:131:27)
    at Object.<anonymous> (/home/pi/senubot/bot.js:18:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:172:43)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:27:21)
```

**Comment by vmarchaud** [comment]
Hey,

It should be fixed with a pm2 re-installation:
```
npm install pm2 -g
pm2 update
```
