### ISSUE TITLE
Hide error stack on unhandledRejection

### ISSUE THREAD

**Issue by sidelux** [Unitech/pm2#4227]
## What's going wrong?

On unhandledRejection pm2 prints the full stack trace on every error.
There is a way to hide and print only programmatically? (if needed)

## How could we reproduce this issue?

Probably causing a simple unhandledRejection error during pm2 execution.

## Supporting information
```
--- PM2 report ----------------------------------------------------------------
Date                 : Mon Apr 01 2019 15:31:33 GMT+0200 (GMT+02:00)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.4.1
node version         : 10.8.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
uptime               : 241min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.4.1
node version         : 10.8.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
cpus nb              : 8
freemem              : 6301704192
totalmem             : 33751605248
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌─────────────┬────┬─────────┬──────┬───────┬────────┬─────────┬────────┬──────┬────────────┬──────┬──────────┐
│ App name    │ id │ version │ mode │ pid   │ status │ restart │ uptime │ cpu  │ mem        │ user │ watching │
├─────────────┼────┼─────────┼──────┼───────┼────────┼─────────┼────────┼──────┼────────────┼──────┼──────────┤
│ compactor   │ 5  │ 1.0.0   │ fork │ 20059 │ online │ 0       │ 4h     │ 0.1% │ 45.1 MB    │ root │ disabled │
│ lootBot     │ 3  │ 1.0.0   │ fork │ 23107 │ online │ 16      │ 53m    │ 4.9% │ 116.3 MB   │ root │ disabled │
│ lootBotApi  │ 0  │ 1.0.0   │ fork │ 20030 │ online │ 0       │ 4h     │ 0.2% │ 46.8 MB    │ root │ disabled │
│ lootBotPlus │ 4  │ 1.0.0   │ fork │ 2033  │ online │ 1       │ 93m    │ 0.6% │ 78.3 MB    │ root │ disabled │
│ r6stats     │ 2  │ 1.0.0   │ fork │ 20042 │ online │ 0       │ 4h     │ 0.1% │ 57.0 MB    │ root │ disabled │
│ userStats   │ 1  │ 1.0.0   │ fork │ 20035 │ online │ 0       │ 4h     │ 0.1% │ 48.1 MB    │ root │ disabled │
└─────────────┴────┴─────────┴──────┴───────┴────────┴─────────┴────────┴──────┴────────────┴──────┴──────────┘
Module
┌───────────────┬────┬─────────┬───────┬────────┬─────────┬──────┬───────────┬──────┐
│ Module        │ id │ version │ pid   │ status │ restart │ cpu  │ memory    │ user │
├───────────────┼────┼─────────┼───────┼────────┼─────────┼──────┼───────────┼──────┤
│ pm2-logrotate │ 6  │ 2.6.0   │ 20080 │ online │ 0       │ 0.1% │ 42.9 MB   │ root │
└───────────────┴────┴─────────┴───────┴────────┴─────────┴──────┴───────────┴──────┘
===============================================================================
--- Daemon logs --------------------------------------------
/root/.pm2/pm2.log last 20 lines:
PM2        | 2019-04-01T14:10:16: PM2 log: App [lootBot:3] starting in -fork mode-
PM2        | 2019-04-01T14:10:16: PM2 log: App [lootBot:3] online
PM2        | 2019-04-01T14:15:04: PM2 log: Stopping app:lootBot id:3
PM2        | 2019-04-01T14:15:04: PM2 log: App [lootBot:3] exited with code [0] via signal [SIGINT]
PM2        | 2019-04-01T14:15:04: PM2 log: pid=26156 msg=process killed
PM2        | 2019-04-01T14:15:04: PM2 log: App [lootBot:3] starting in -fork mode-
PM2        | 2019-04-01T14:15:04: PM2 log: App [lootBot:3] online
PM2        | 2019-04-01T14:36:01: PM2 log: Stopping app:lootBot id:3
PM2        | 2019-04-01T14:36:01: PM2 log: App [lootBot:3] exited with code [0] via signal [SIGINT]
PM2        | 2019-04-01T14:36:02: PM2 log: pid=4367 msg=process killed
PM2        | 2019-04-01T14:36:02: PM2 log: App [lootBot:3] starting in -fork mode-
PM2        | 2019-04-01T14:36:02: PM2 log: App [lootBot:3] online
PM2        | 2019-04-01T14:36:39: PM2 log: Stopping app:lootBot id:3
PM2        | 2019-04-01T14:36:39: PM2 log: App [lootBot:3] exited with code [0] via signal [SIGINT]
PM2        | 2019-04-01T14:36:39: PM2 log: pid=19769 msg=process killed
PM2        | 2019-04-01T14:36:39: PM2 log: App [lootBot:3] starting in -fork mode-
PM2        | 2019-04-01T14:36:39: PM2 log: App [lootBot:3] online
PM2        | 2019-04-01T14:38:16: PM2 log: App [lootBot:3] exited with code [1] via signal [SIGINT]
PM2        | 2019-04-01T14:38:16: PM2 log: App [lootBot:3] starting in -fork mode-
PM2        | 2019-04-01T14:38:16: PM2 log: App [lootBot:3] online

```

And an unhandledRejection log:

```
{ Error: ETELEGRAM: 403 Forbidden: bot was blocked by the user
    at request.then.resp (/home/fenix/lootBot/node_modules/node-telegram-bot-api/src/telegram.js:280:15)
    at tryCatcher (/home/fenix/lootBot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/fenix/lootBot/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/fenix/lootBot/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/fenix/lootBot/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/fenix/lootBot/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/fenix/lootBot/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/fenix/lootBot/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/fenix/lootBot/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
  code: 'ETELEGRAM',
  response:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        emitClose: true,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: true,
        decoder: null,
        encoding: null },
     readable: false,
     _events:
      { end: [Array],
        close: [Array],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'api.telegram.org',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 7,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'api.telegram.org',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: null,
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: -1,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'api.telegram.org',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 7,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'api.telegram.org',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: null,
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: -1,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
      { server: 'nginx/1.12.2',
        date: 'Mon, 01 Apr 2019 13:10:23 GMT',
        'content-type': 'application/json',
        'content-length': '84',
        connection: 'keep-alive',
        'access-control-allow-origin': '*',
        'access-control-expose-headers': 'Content-Length,Content-Type,Date,Server,Connection',
        'strict-transport-security': 'max-age=31536000; includeSubDomains; preload' },
     rawHeaders:
      [ 'Server',
        'nginx/1.12.2',
        'Date',
        'Mon, 01 Apr 2019 13:10:23 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '84',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Content-Length,Content-Type,Date,Server,Connection',
        'Strict-Transport-Security',
        'max-age=31536000; includeSubDomains; preload' ],
     trailers: {},
     rawTrailers: [],
     aborted: false,
     upgrade: false,
     url: '',
     method: null,
     statusCode: 403,
     statusMessage: 'Forbidden',
     client:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'api.telegram.org',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 7,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'api.telegram.org',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: null,
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: -1,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     _consuming: false,
     _dumped: false,
     req:
      ClientRequest {
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header:
         'POST /botXXX/sendMessage HTTP/1.1\r\nhost: api.telegram.org\r\ncontent-type: application/x-www-form-urlencoded\r\ncontent-length: 2372\r\nConnection: keep-alive\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path:
         '/botXXX/sendMessage',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     request:
      Request {
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        method: 'POST',
        simple: false,
        resolveWithFullResponse: true,
        forever: true,
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Querystring],
        _auth: [Auth],
        _oauth: [OAuth],
        _multipart: [Multipart],
        _redirect: [Redirect],
        _tunnel: [Tunnel],
        _rp_resolve: [Function],
        _rp_reject: [Function],
        _rp_promise: [Promise],
        _rp_callbackOrig: undefined,
        callback: [Function],
        _rp_options: [Object],
        headers: [Object],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: [Object],
        dests: [],
        __isRequestRequest: true,
        _callback: [Function: RP$callback],
        uri: [Url],
        proxy: null,
        tunnel: true,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: 443,
        host: 'api.telegram.org',
        body:
         'parse_mode=HTML&chat_id=670383774&text=%F0%9F%93%9C%20Report%20battaglia%20del%20turno%20%3Ci%3E31%3C%2Fi%3E%20contro%20%3Cb%3EDrago%20Multiforme%3C%2Fb%3E%20%28Boss%29%3A%0A%0A%F0%9F%92%A2%20Incrementi%20attivati%3A%0A%3E%20Piattaforma%20di%20Lancio%20%28%2B%3Cb%3E0%2C5%3C%2Fb%3E%25%20riduzione%20probabilit%C3%A0%20colpo%20critico%20dei%20nemici%29%0A%3E%20Nido%20del%20Drago%20%28%2B%3Cb%3E1%3C%2Fb%3E%25%20probabilit%C3%A0%20colpo%29%0A%0A%E2%98%84%20La%20Piattaforma%20di%20Lancio%20%C3%A8%20stata%20disattivata%21%0A%0A%E2%9A%A1%EF%B8%8F%20La%20Torre%20dello%20Stregone%20non%20%C3%A8%20stata%20costruita%2C%20nessun%20danno%20al%20nemico%21%0A%0A%F0%9F%A5%81%20Il%20Campo%20Militare%20fornisce%20%3Cb%3E9%2C18%3C%2Fb%3E%25%20bonus%20al%20danno%20delle%20artiglierie%21%0A%0A%F0%9F%97%A1%20L%27Artiglieria%20Leggera%20non%20ha%20nessuno%20al%20suo%20interno%2C%20nessun%20danno%20al%20nemico%21%0A%0A%F0%9F%90%BA%20Il%20nemico%20attacca%2C%20le%20mura%20non%20attutiscono%20danni%20%28resistenza%20terminata%29%3A%0A%3E%20F3DE93%20subisce%20%3Cb%3E8.329%3C%2Fb%3E%20danni%20%28%F0%9F%A5%8B%29%0A%3E%20Arenter%20subisce%20%3Cb%3E9.275%3C%2Fb%3E%20danni%20%28%F0%9F%A5%8B%29%0A%3E%20Diaspro%20subisce%20%3Cb%3E7.952%3C%2Fb%3E%20danni%0A%3E%20LediMun%20subisce%20%3Cb%3E8.088%3C%2Fb%3E%20danni%0A%0A%E2%9A%94%20L%27Artiglieria%20Pesante%20colpisce%20infliggendo%20in%20totale%20%3Cb%3E413.069%3C%2Fb%3E%20danni%3A%20%0A%3E%20F3DE93%20infligge%20%3Cb%3E289.757%3C%2Fb%3E%20danni%20%28critico%29%0A%3E%20Arenter%20infligge%20%3Cb%3E123.312%3C%2Fb%3E%20danni%0A%0A%F0%9F%90%B2%20I%20draghi%20del%20nido%20si%20alzano%20in%20volo%20e%20attaccano%20il%20nemico%20infliggendo%20complessivamente%20%3Cb%3E2.815.244%3C%2Fb%3E%20danni%20%F0%9F%94%BA%0A%0A%F0%9F%94%8B%20La%20Fabbrica%20di%20Energia%20consente%20di%20recuperare%20il%20%3Cb%3E11%25%3C%2Fb%3E%20di%20hp%20a%20tutti%0A%0A%E2%9C%A8%20I%20compagni%20recuperano%20salute%3A%0A%3E%20Nessuno%20necessita%20di%20cure%0A%0A%F0%9F%92%89%20Compagni%20in%20infermeria%3A%0A%3E%20Wolcarlos%0A%3E%20Akito1985%0A%3E%20LaSop%0A%3E%20Oscurity95%0A%3E%20Stargazer092%0A%3E%20Beruthyel%0A%3E%20Garrosh_malogrido%0A%0AIl%20nemico%20ha%20subito%20in%20totale%20%3Cb%3E3.228.313%3C%2Fb%3E%20danni%0ASalute%3A%20%E2%96%A0%E2%96%A0%E2%96%A0%E2%96%A0%E2%96%A0%E2%96%A0%E2%96%A1%E2%96%A1%E2%96%A1%E2%96%A1%2017.981.819%2F32.174.213%0A%0A',
        path:
         '/botXXX/sendMessage',
        httpModule: [Object],
        agentClass: [Function],
        agentOptions: [Object],
        agent: [Agent],
        _started: true,
        href:
         'https://api.telegram.org/XXX/sendMessage',
        req: [ClientRequest],
        ntick: true,
        response: [Circular],
        originalHost: 'api.telegram.org',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     body:
      { ok: false,
        error_code: 403,
        description: 'Forbidden: bot was blocked by the user' } } }
```

Thanks!

**Comment by sidelux** [comment]
For now i fixed with `--no-pmx`...
Tell me if there are other better options.
