### ISSUE TITLE
Pm2 suddently crashes

### ISSUE THREAD

**Issue by ricolk** [Unitech/pm2#4237]
Hi to Everyone, 

Today pm2 crashed and I cannot understand why. 

pm2.log shows:

```
2019-04-06T21:40:26: PM2 log: ===============================================================================
2019-04-06T21:40:26: PM2 log: --- PM2 global error caught ---------------------------------------------------
2019-04-06T21:40:26: PM2 log: Time                 : Sat Apr 06 2019 21:40:26 GMT+0200 (GMT+02:00)
2019-04-06T21:40:26: PM2 error: write EBADF
2019-04-06T21:40:26: PM2 error: Error: write EBADF
    at WriteWrap.afterWrite [as oncomplete] (net.js:779:14)
2019-04-06T21:40:26: PM2 log: ===============================================================================
2019-04-06T21:40:26: PM2 error: [PM2] Resurrecting PM2
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/undefined'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

Just two application are managed by pm2. I cannot understand which one caused the crash.

**Comment by Unitech** [comment]
Epic crash, cannot find module undefined! Never seen that in my life!

Can you run pm2 report and paste output here. If that does not work please report os, node version.

Anyway it looks like a system error

**Comment by ricolk** [comment]
Hi, 

The system restart, no info about the crash.

```
--- PM2 report ----------------------------------------------------------------
Date                 : Sat Apr 06 2019 22:31:21 GMT+0200 (GMT+02:00)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.4.0
node version         : 10.15.3
node path            : not found
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : pi
uid                  : 1000
gid                  : 1000
uptime               : 26min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.4.0
node version         : 10.15.3
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : pi
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : arm
platform             : linux
type                 : Linux
cpus                 : ARMv7 Processor rev 4 (v7l)
cpus nb              : 4
freemem              : 200802304
totalmem             : 917676032
home                 : /home/pi
===============================================================================
--- PM2 list -----------------------------------------------
┌─────────────┬────┬─────────┬──────┬─────┬────────┬─────────┬────────┬─────┬──────────┬──────┬──────────┐
│ App name    │ id │ version │ mode │ pid │ status │ restart │ uptime │ cpu │ mem      │ user │ watching │
├─────────────┼────┼─────────┼──────┼─────┼────────┼─────────┼────────┼─────┼──────────┼──────┼──────────┤
│ NAS_feed_bk │ 0  │ N/A     │ fork │ 923 │ online │ 0       │ 26m    │ 0%  │ 2.5 MB   │ pi   │ disabled │
│ Link_alive  │ 1  │ N/A     │ fork │ 930 │ online │ 0       │ 26m    │ 0%  │ 2.5 MB   │ pi   │ disabled │
└─────────────┴────┴─────────┴──────┴─────┴────────┴─────────┴────────┴─────┴──────────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/home/pi/.pm2/pm2.log last 20 lines:
PM2        | 2019-04-06T22:04:07: PM2 log: PM2 successfully stopped
PM2        | 2019-04-06T22:04:30: PM2 log: ===============================================================================
PM2        | 2019-04-06T22:04:30: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2019-04-06T22:04:30: PM2 log: Time                 : Sat Apr 06 2019 22:04:30 GMT+0200 (GMT+02:00)
PM2        | 2019-04-06T22:04:30: PM2 log: PM2 version          : 3.4.0
PM2        | 2019-04-06T22:04:30: PM2 log: Node.js version      : 10.15.3
PM2        | 2019-04-06T22:04:30: PM2 log: Current arch         : arm
PM2        | 2019-04-06T22:04:30: PM2 log: PM2 home             : /home/pi/.pm2
PM2        | 2019-04-06T22:04:30: PM2 log: PM2 PID file         : /home/pi/.pm2/pm2.pid
PM2        | 2019-04-06T22:04:30: PM2 log: RPC socket file      : /home/pi/.pm2/rpc.sock
PM2        | 2019-04-06T22:04:30: PM2 log: BUS socket file      : /home/pi/.pm2/pub.sock
PM2        | 2019-04-06T22:04:30: PM2 log: Application log path : /home/pi/.pm2/logs
PM2        | 2019-04-06T22:04:30: PM2 log: Process dump file    : /home/pi/.pm2/dump.pm2
PM2        | 2019-04-06T22:04:30: PM2 log: Concurrent actions   : 2
PM2        | 2019-04-06T22:04:30: PM2 log: SIGTERM timeout      : 1600
PM2        | 2019-04-06T22:04:30: PM2 log: ===============================================================================
PM2        | 2019-04-06T22:04:30: PM2 log: App [NAS_feed_bk:0] starting in -fork mode-
PM2        | 2019-04-06T22:04:30: PM2 log: App [Link_alive:1] starting in -fork mode-
PM2        | 2019-04-06T22:04:30: PM2 log: App [NAS_feed_bk:0] online
PM2        | 2019-04-06T22:04:30: PM2 log: App [Link_alive:1] online
```

Working on a Raspberry Pi with  Raspbian GNU/Linux 9 (stretch) and Node v10.15.3

Thanks in advance.

**Comment by martianmartian** [comment]
so socket.io needs some worker, it's in the doc, socket.io and pm2

**Comment by pawanrai852** [comment]
Same Problem, Angular app inside PM2 Got Crashed But not Find Any Logs of the Crash and unable to track Reason Behind the Crash

**Comment by martianmartian** [comment]
yeah just stop using this pm2 nonesense

**Comment by hdlion** [comment]
Use pm2 version 4. I had same problem with version 5.
