### ISSUE TITLE
pm2 fatally crashes on ENOMEM when stopping process

### ISSUE THREAD

**Issue by askmike** [Unitech/pm2#4240]
PM2 was managing multiple processes, I tried stopping one and it crashed. My activity:

<img width="827" alt="Screenshot 2019-04-09 at 13 45 51" src="https://user-images.githubusercontent.com/969743/55776217-902ad600-5ace-11e9-9c44-9866a87efd4d.png">

logs:

    2019-04-09T00:27:24: PM2 log: App [binance_all:8] online
    2019-04-09T05:45:15: PM2 log: Stopping app:updateAum id:9
    internal/child_process.js:372
        throw errnoException(err, 'spawn');
        ^

    Error: spawn ENOMEM
        at ChildProcess.spawn (internal/child_process.js:372:11)
        at spawn (child_process.js:559:9)
        at /root/.nvm/versions/node/v11.11.0/lib/node_modules/pm2/lib/TreeKill.js:33:14
        at buildProcessTree (/root/.nvm/versions/node/v11.11.0/lib/node_modules/pm2/lib/TreeKill.js:79:12)
        at module.exports (/root/.nvm/versions/node/v11.11.0/lib/node_modules/pm2/lib/TreeKill.js:32:5)
        at Object.God.killProcess (/root/.nvm/versions/node/v11.11.0/lib/node_modules/pm2/lib/God/Methods.js:221:7)
        at God.stopProcessId (/root/.nvm/versions/node/v11.11.0/lib/node_modules/pm2/lib/God/ActionMethods.js:339:9)
        at Server.onmessage (/root/.nvm/versions/node/v11.11.0/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:104:6)
        at RepSocket.emit (events.js:197:13)
        at RepSocket.EventEmitter.emit (domain.js:446:20)
    2019-04-09T05:45:37: PM2 log: ===============================================================================
    2019-04-09T05:45:37: PM2 log: --- New PM2 Daemon started ----------------------------------------------------

I understand pm2 can't magically make more memory appear, but what differed from my expectations:

- no error was shown
- why is pm2 trying to spawn anything when I want to kill a process?
- full crash of pm2

Pretty sure there are good explanations for all of them though :)

**Comment by Unitech** [comment]
Could you run `pm2 report`? If PM2 crash it is respawned again (as you can see at the bottom of the pm2 logs `2019-04-09T05:45:37: PM2 log: --- New PM2 Daemon started ----------------------------------------------------`)

Also PM2 3.5.0 has a new systemd script that auto respawn PM2 if it crashed and if the domain mechanism did not succeed.

**Comment by askmike** [comment]
"pm2 report" only seems to spit out last lines of the Pm2 log. Which don't
include the error anymore since pm2 seemed to restart after typing "pm2
ls". I only posted the log section containing the error. After that the
logs indicate pm2 restarted.

**Comment by askmike** [comment]
To follow up on your request, here is the full output of `pm2 report`:

```
--- PM2 report ----------------------------------------------------------------
Date                 : Tue Apr 09 2019 10:46:31 GMT+0000 (Coordinated Universal Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.3.1
node version         : 11.11.0
node path            : /root/.nvm/versions/node/v11.11.0/bin/pm2
argv                 : /root/.nvm/versions/node/v11.11.0/bin/node,/root/.nvm/versions/node/v11.11.0/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
uptime               : 300min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.3.1
node version         : 11.11.0
node path            : /root/.nvm/versions/node/v11.11.0/bin/pm2
argv                 : /root/.nvm/versions/node/v11.11.0/bin/node,/root/.nvm/versions/node/v11.11.0/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2630L 0 @ 2.00GHz
cpus nb              : 1
freemem              : 107335680
totalmem             : 1033375744
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌─────────────┬────┬─────────┬──────┬───────┬────────┬─────────┬────────┬──────┬───────────┬──────┬──────────┐
│ App name    │ id │ version │ mode │ pid   │ status │ restart │ uptime │ cpu  │ mem       │ user │ watching │
├─────────────┼────┼─────────┼──────┼───────┼────────┼─────────┼────────┼──────┼───────────┼──────┼──────────┤
│ akira-lb    │ 4  │ N/A     │ fork │ 20942 │ online │ 0       │ 4h     │ 0.2% │ 76.2 MB   │ root │ disabled │
│ binance_all │ 0  │ N/A     │ fork │ 14858 │ online │ 0       │ 4h     │ 1.2% │ 86.6 MB   │ root │ disabled │
│ bitmex_all  │ 1  │ N/A     │ fork │ 14889 │ online │ 0       │ 4h     │ 0.4% │ 79.6 MB   │ root │ disabled │
│ cf:perp     │ 2  │ N/A     │ fork │ 14908 │ online │ 0       │ 4h     │ 0.2% │ 81.4 MB   │ root │ disabled │
│ okex:perp   │ 3  │ N/A     │ fork │ 14927 │ online │ 0       │ 4h     │ 0.2% │ 79.0 MB   │ root │ disabled │
└─────────────┴────┴─────────┴──────┴───────┴────────┴─────────┴────────┴──────┴───────────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/root/.pm2/pm2.log last 20 lines:
PM2        | 2019-04-09T05:45:37: PM2 log: Current arch         : x64
PM2        | 2019-04-09T05:45:37: PM2 log: PM2 home             : /root/.pm2
PM2        | 2019-04-09T05:45:37: PM2 log: PM2 PID file         : /root/.pm2/pm2.pid
PM2        | 2019-04-09T05:45:37: PM2 log: RPC socket file      : /root/.pm2/rpc.sock
PM2        | 2019-04-09T05:45:37: PM2 log: BUS socket file      : /root/.pm2/pub.sock
PM2        | 2019-04-09T05:45:37: PM2 log: Application log path : /root/.pm2/logs
PM2        | 2019-04-09T05:45:37: PM2 log: Process dump file    : /root/.pm2/dump.pm2
PM2        | 2019-04-09T05:45:37: PM2 log: Concurrent actions   : 2
PM2        | 2019-04-09T05:45:37: PM2 log: SIGTERM timeout      : 1600
PM2        | 2019-04-09T05:45:37: PM2 log: ===============================================================================
PM2        | 2019-04-09T06:01:12: PM2 log: App [binance_all:0] starting in -fork mode-
PM2        | 2019-04-09T06:01:12: PM2 log: App [binance_all:0] online
PM2        | 2019-04-09T06:06:26: PM2 log: App [bitmex_all:1] starting in -fork mode-
PM2        | 2019-04-09T06:06:26: PM2 log: App [bitmex_all:1] online
PM2        | 2019-04-09T06:06:33: PM2 log: App [cf:perp:2] starting in -fork mode-
PM2        | 2019-04-09T06:06:33: PM2 log: App [cf:perp:2] online
PM2        | 2019-04-09T06:06:36: PM2 log: App [okex:perp:3] starting in -fork mode-
PM2        | 2019-04-09T06:06:36: PM2 log: App [okex:perp:3] online
PM2        | 2019-04-09T06:37:46: PM2 log: App [akira-lb:4] starting in -fork mode-
PM2        | 2019-04-09T06:37:46: PM2 log: App [akira-lb:4] online

```

**Comment by Unitech** [comment]
update to latest pm2 and refresh of startup script will fix the issue:
```
npm install pm2@latest -g
pm2 update
pm2 unstartup
pm2 startup
```
