### ISSUE TITLE
bash and sh not available in $PATH 

### ISSUE THREAD

**Issue by snsarma** [Unitech/pm2#4277]
Hi folks

I get an error with the below details when I do a pm2 start ecosystem.config.js .
Please let me know how can this be resolved ? Thanks

C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\lib\Common.js:669
        throw new Error('bash and sh not available in $PATH')
        ^

Error: bash and sh not available in $PATH
    at Object.Common.verifyConfs (C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\lib\Common.js:669:15)
    at API._startJson (C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\lib\API.js:926:27)
    at API.start (C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\lib\API.js:334:12)
    at C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\bin\pm2:291:13
    at C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\node_modules\async\internal\withoutIndex.js:9:16
    at replenish (C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\node_modules\async\internal\eachOfLimit.js:66:17)
    at C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\node_modules\async\internal\eachOfLimit.js:71:9
    at eachLimit (C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\node_modules\async\forEachLimit.js:43:36)
    at Command.<anonymous> (C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\bin\pm2:290:7)
    at Command.listener (C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:315:8)

## Supporting information

```
$ pm2 report
```

**Comment by snsarma** [comment]
$ pm2 report

```
--- PM2 report ----------------------------------------------------------------
Date                 : Mon May 13 2019 10:24:56 GMT-0400 (Eastern Daylight Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.5.0
node version         : 10.11.0
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 3922min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.5.0
node version         : 10.11.0
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : node
user                 : ssarma
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
cpus nb              : 4
freemem              : 388190208
totalmem             : 3967594496
home                 : C:\Users\SSarma
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬─────────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴─────────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
C:\etc\pm2\pm2.log last 20 lines:
PM2        | 2019-05-10T17:01:05: PM2 log: App [server:0] online
PM2        | 2019-05-10T17:02:45: PM2 log: Stopping app:server id:0
PM2        | 2019-05-10T17:02:46: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
PM2        | 2019-05-10T17:02:46: PM2 log: pid=27388 msg=process killed
PM2        | 2019-05-10T17:02:46: PM2 log: PM2 successfully stopped
PM2        | 2019-05-10T17:02:54: PM2 log: ===============================================================================
PM2        | 2019-05-10T17:02:54: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2019-05-10T17:02:54: PM2 log: Time                 : Fri May 10 2019 17:02:54 GMT-0400 (Eastern Daylight Time)
PM2        | 2019-05-10T17:02:54: PM2 log: PM2 version          : 3.5.0
PM2        | 2019-05-10T17:02:54: PM2 log: Node.js version      : 10.11.0
PM2        | 2019-05-10T17:02:54: PM2 log: Current arch         : x64
PM2        | 2019-05-10T17:02:54: PM2 log: PM2 home             : C:\etc\pm2
PM2        | 2019-05-10T17:02:54: PM2 log: PM2 PID file         : C:\etc\pm2\pm2.pid
PM2        | 2019-05-10T17:02:54: PM2 log: RPC socket file      : \\.\pipe\rpc.sock
PM2        | 2019-05-10T17:02:54: PM2 log: BUS socket file      : \\.\pipe\pub.sock
PM2        | 2019-05-10T17:02:54: PM2 log: Application log path : C:\etc\pm2\logs
PM2        | 2019-05-10T17:02:54: PM2 log: Process dump file    : C:\etc\pm2\dump.pm2
PM2        | 2019-05-10T17:02:54: PM2 log: Concurrent actions   : 2
PM2        | 2019-05-10T17:02:54: PM2 log: SIGTERM timeout      : 1600
PM2        | 2019-05-10T17:02:54: PM2 log: ===============================================================================

```


Please copy/paste the above report in your issue on https://github.com/Unitech/pm2/issues
