### ISSUE TITLE
Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by shawn-tangsc** [Unitech/pm2#4284]
## What's going wrong?
There will be a certain probability after a period of execute pm2 start xxx
and it will crash ,can not reload ,how to fix it?

7|node-server  | Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
7|node-server  |     at doWrite (_stream_writable.js:406:19)
7|node-server  |     at writeOrBuffer (_stream_writable.js:394:5)
7|node-server  |     at WriteStream.Writable.write (_stream_writable.js:294:11)
7|node-server  |     at SyncWriteStream.write (/home/ops/nodejs/lib/node_modules/pm2/lib/ProcessContainer.js:204:48)
7|node-server  |     at write (console.js:164:12)
7|node-server  |     at Console.warn (console.js:211:3)
7|node-server  |     at WriteStream.<anonymous> (/home/ops/nodejs/lib/node_modules/pm2/lib/Utility.js:183:23)
7|node-server  |     at WriteStream.emit (events.js:189:13)
7|node-server  |     at onwriteError (_stream_writable.js:425:12)
7|node-server  |     at onwrite (_stream_writable.js:456:5)
7|node-server  |     at doWrite (_stream_writable.js:406:11)
7|node-server  |     at writeOrBuffer (_stream_writable.js:394:5)
7|node-server  |     at WriteStream.Writable.write (_stream_writable.js:294:11)
7|node-server  |     at SyncWriteStream.write (/home/ops/nodejs/lib/node_modules/pm2/lib/ProcessContainer.js:204:48)
7|node-server  |     at write (console.js:164:12)
7|node-server  |     at Console.warn (console.js:211:3)

## Supporting information

```
>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 3.4.0
Local PM2 version: 3.5.0




```
--- PM2 report ----------------------------------------------------------------
Date                 : Thu May 16 2019 10:56:21 GMT+0800 (GMT+08:00)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.4.0
node version         : 10.15.3
node path            : /usr/local/bin/pm2
argv                 : /home/ops/nodejs/bin/node,/home/ops/nodejs/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : ops
uid                  : 1000
gid                  : 1000
uptime               : 12702min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.5.0
node version         : 10.15.3
node path            : /usr/local/bin/pm2
argv                 : /home/ops/nodejs/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : ops
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E7-4820 v3 @ 1.90GHz
cpus nb              : 8
freemem              : 282931200
totalmem             : 16649105408
home                 : /home/ops
===============================================================================
--- PM2 list -----------------------------------------------
┌─────────────┬────┬─────────┬─────────┬───────┬────────┬─────────┬────────┬──────┬───────────┬──────┬──────────┐
│ App name    │ id │ version │ mode    │ pid   │ status │ restart │ uptime │ cpu  │ mem       │ user │ watching │
├─────────────┼────┼─────────┼─────────┼───────┼────────┼─────────┼────────┼──────┼───────────┼──────┼──────────┤
│ node-server │ 0  │ 1.0.0   │ cluster │ 51219 │ online │ 1       │ 39m    │ 0.6% │ 49.8 MB   │ ops  │ disabled │
│ node-server │ 1  │ 1.0.0   │ cluster │ 51234 │ online │ 1       │ 39m    │ 0.4% │ 51.8 MB   │ ops  │ disabled │
│ node-server │ 2  │ 1.0.0   │ cluster │ 51275 │ online │ 1       │ 39m    │ 0.5% │ 50.3 MB   │ ops  │ disabled │
│ node-server │ 3  │ 1.0.0   │ cluster │ 51312 │ online │ 1       │ 39m    │ 0.5% │ 49.2 MB   │ ops  │ disabled │
│ node-server │ 4  │ 1.0.0   │ cluster │ 51319 │ online │ 1       │ 39m    │ 0.5% │ 51.3 MB   │ ops  │ disabled │
│ node-server │ 5  │ 1.0.0   │ cluster │ 51355 │ online │ 1       │ 39m    │ 0.5% │ 59.9 MB   │ ops  │ disabled │
│ node-server │ 6  │ 1.0.0   │ cluster │ 51363 │ online │ 1       │ 39m    │ 0.5% │ 49.3 MB   │ ops  │ disabled │
│ node-server │ 7  │ 1.0.0   │ cluster │ 51394 │ online │ 1       │ 39m    │ 0.5% │ 50.2 MB   │ ops  │ disabled │
└─────────────┴────┴─────────┴─────────┴───────┴────────┴─────────┴────────┴──────┴───────────┴──────┴──────────┘
===============================================================================
```

**Comment by ayizhi** [comment]
connect before start delete and list may be helpful , it is helpful to me

**Comment by Nesher123** [comment]
Hey,
I encounter the same problem actually...
Any solution?
@ayizhi Can you explain, please? I didn't understand what you suggested.

**Comment by ayizhi** [comment]
@Nesher123  run pm2.start or pm2.list(describe) in pm2.connect callback

**Comment by shivam8800** [comment]
@ayizhi  still I couldn't solve this problem
already done with it which you suggested but nothing help me
can you please help me ?

**Comment by ayizhi** [comment]
> @ayizhi still I couldn't solve this problem
> already done with it which you suggested but nothing help me
> can you please help me ?

Would you  post your code?
we need connect the daemon every time we use pm2.start or pm2.list, and we should disconnect after that by official guide. But because of the async process,  there will be one situation that after second connect the first disconnect happened, which leads to the second connect fail.
i dont know if this explanation is clear?

**Comment by shivam8800** [comment]
Sorry I couldn't understand it
let me tell you what are things I have done in order to solve this
I am running my server with pm2 `npm run  NODE_ENV=production pm2 start index.js --name 'api-server'`
when I run the server with pm2 It shows `7|node-server | Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed` error
But when I simply run the server with `screen npm start` It's working fine.
I think the problem is with pm2 but I already reinstall pm2?

**Comment by jawaaad** [comment]
I encountered the same issue, still not being able to figure out what actually is going wrong

**Comment by sadaphalrahul** [comment]
Hi I am getting following error while running my node server..Can anyone plz help me on this..I am stuck with this error and can't find any solution


 Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
 at doWrite (_stream_writable.js:427:19)
 at writeOrBuffer (_stream_writable.js:415:5)
 at WriteStream.Writable.write (_stream_writable.js:305:11)
at SyncWriteStream.write (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainer.js:205:48)
 at Object.Console.<computed> (internal/console/constructor.js:237:12)
at Object.warn (internal/console/constructor.js:287:26)
at WriteStream.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\lib\Utility.js:183:23)
at WriteStream.emit (events.js:210:5)
at WriteStream.EventEmitter.emit (domain.js:475:20)
at errorOrDestroy (internal/streams/destroy.js:108:12)
at onwriteError (_stream_writable.js:446:5)
at onwrite (_stream_writable.js:473:5)
at doWrite (_stream_writable.js:427:11)
at writeOrBuffer (_stream_writable.js:415:5)
at WriteStream.Writable.write (_stream_writable.js:305:11)
at SyncWriteStream.write (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainer.js:205:48)
at Object.Console.<computed> (internal/console/constructor.js:237:12)
at Object.warn (internal/console/constructor.js:287:26)
at WriteStream.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\lib\Utility.js:183:23)
at WriteStream.emit (events.js:210:5)
at WriteStream.EventEmitter.emit (domain.js:475:20)
at errorOrDestroy (internal/streams/destroy.js:108:12) {
code: 'ERR_STREAM_DESTROYED'
}

**Comment by andrei-tofan** [comment]
This issue happens because you don't have enough disk space left on the server. Run `pm2 flush` to empty the logs.

**Comment by sadaphalrahul** [comment]
> This issue happens because you don't have enough disk space left on the server. Run `pm2 flush` to empty the logs.

thanks for your solution

**Comment by tranhuuhiep508** [comment]
> pm2 flush

I have the same problem, I also run 'pm2 flush' but It's not ok

**Comment by gebrits** [comment]
Encoutering same problem. 

Also why on earth is this issue closed? 
Being 'stale', as in no recent activity, doesn't imply this issue is fixed.

**Comment by ashutosh1127** [comment]
My was getting this error because .pm1/logs/project-out.log was very big file.which was taken to much spcae.

**Comment by xiaohubei** [comment]
> This issue happens because you don't have enough disk space left on the server. Run `pm2 flush` to empty the logs.

thanks for your solution

**Comment by cipiripper** [comment]
> This issue happens because you don't have enough disk space left on the server. Run `pm2 flush` to empty the logs.

I can confirm that this is not true for all cases. I just had it happen on a machine in production with over 70% of free disk space.

Fix for me was to restart the process, if you look into `pm2 logs` output, you will see that PM2 error being spammed right after a process has logged something:

```
18|task-ru | 2021-07-21 22:30:49 - info : <project-status-update-worker.js 7> Project is saved with status defined
PM2        | Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
PM2        |     at doWrite (_stream_writable.js:411:19)
PM2        |     at writeOrBuffer (_stream_writable.js:399:5)
PM2        |     at WriteStream.Writable.write (_stream_writable.js:299:11)
PM2        |     at Socket.forkOutData (/usr/local/lib/node_modules/pm2/lib/God/ForkMode.js:189:48)
PM2        |     at Socket.emit (events.js:198:13)
PM2        |     at Socket.EventEmitter.emit (domain.js:466:23)
PM2        |     at addChunk (_stream_readable.js:288:12)
PM2        |     at readableAddChunk (_stream_readable.js:269:11)
PM2        |     at Socket.Readable.push (_stream_readable.js:224:10)
PM2        |     at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

```

So in my case, buggy process is process 18. And after restarting it I had no problems with this error.

Odd thing is that this happened on the second machine as well, but with two different processes... somewhat at the same time. So I suspect this is something to do with KeyMetrics integration. :thinking:

**Comment by ArmanDolati** [comment]
hi friends,
I found this way to solve this problem :
    options: {
        encrypt:false
      }
full :
const msSqlConfig={
    server:SQL_SERVER_NAME,
    port:SQL_PORT,
    user:`${SQL_USER_NAME}`,
    password:`${SQL_PASSWORD}`,
    database:SQL_DB_NAME,
    options: {
        encrypt:false
      }
}

**Comment by bencat-sixense** [comment]
> > This issue happens because you don't have enough disk space left on the server. Run `pm2 flush` to empty the logs.
> 
> I can confirm that this is not true for all cases. I just had it happen on a machine in production with over 70% of free disk space.
> 
> Fix for me was to restart the process, if you look into `pm2 logs` output, you will see that PM2 error being spammed right after a process has logged something:
> 
> ```
> 18|task-ru | 2021-07-21 22:30:49 - info : <project-status-update-worker.js 7> Project is saved with status defined
> PM2        | Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
> PM2        |     at doWrite (_stream_writable.js:411:19)
> PM2        |     at writeOrBuffer (_stream_writable.js:399:5)
> PM2        |     at WriteStream.Writable.write (_stream_writable.js:299:11)
> PM2        |     at Socket.forkOutData (/usr/local/lib/node_modules/pm2/lib/God/ForkMode.js:189:48)
> PM2        |     at Socket.emit (events.js:198:13)
> PM2        |     at Socket.EventEmitter.emit (domain.js:466:23)
> PM2        |     at addChunk (_stream_readable.js:288:12)
> PM2        |     at readableAddChunk (_stream_readable.js:269:11)
> PM2        |     at Socket.Readable.push (_stream_readable.js:224:10)
> PM2        |     at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> ```
> 
> So in my case, buggy process is process 18. And after restarting it I had no problems with this error.
> 
> Odd thing is that this happened on the second machine as well, but with two different processes... somewhat at the same time. So I suspect this is something to do with KeyMetrics integration. 🤔

Thanks, that was it for me ;)
