### ISSUE TITLE
start process with EOF error

### ISSUE THREAD

**Issue by ayizhi** [Unitech/pm2#4286]
the problem was triggered by Daemon.js line 34 only in windows with pm2 3.5.0 Programmatic APIs
`Daemon.prototype.start = function() {
  var that = this;
  var d = domain.create();
  d.once('error', function(err) {
    fmt.sep();
    fmt.title('PM2 global error caught');
    fmt.field('Time', new Date());
    console.error(err.message);
    console.error(err.stack);
    fmt.sep();
    console.error('[PM2] Resurrecting PM2');
    var path = cst.IS_WINDOWS ? process.cwd() + '/bin/pm2' : process.env['_'];
    var fork_new_pm2 = require('child_process').spawn('node', [path, 'update'], {
      detached: true,
      stdio: 'inherit'
    });
    fork_new_pm2.on('close', function() {
      console.log('PM2 successfully forked');
      process.exit(0);
    })
  });
  d.run(function() {
    that.innerStart();
  });
}`

After a long time running ， pm2 start makes an error killing the daemon process and making a new one；this leads we lost the control of the old daemon and processes managered by the old daemon；

the pm2 log is

> ===============================================================================
2019-05-17T16:01:36: PM2 log: --- PM2 global error caught ---------------------------------------------------
2019-05-17T16:01:36: PM2 log: Time                 : Fri May 17 2019 16:01:36 GMT+0800 (中国标准时间)
2019-05-17T16:01:36: PM2 error: write EOF
2019-05-17T16:01:36: PM2 error: Error: write EOF
    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)
2019-05-17T16:01:36: PM2 log: ===============================================================================
2019-05-17T16:01:36: PM2 error: [PM2] Resurrecting PM2
module.js:549
    throw err;
    ^
Error: Cannot find module 'C:\Program Files (x86)\Kungfu.Trader\bin\pm2'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
2019-05-17T16:01:37: PM2 log: PM2 successfully forked

 it may be out of windows memory management， how can i do with that @Unitech

**Comment by drb-germany** [comment]
Same problem here: I start a saved session with pm2 resurrect. After a few hours or days I run pm2 list, which will then cause the above error "PM2 global error caught". Afterwards, the pm2 demon is started again and pm2 list will show me no processes running (even though all jobs which are NOT node.js projects are still running). Need to reboot the system to empty everything and run pm2 resurrect again.

**Comment by ayizhi** [comment]
> Same problem here: I start a saved session with pm2 resurrect. After a few hours or days I run pm2 list, which will then cause the above error "PM2 global error caught". Afterwards, the pm2 demon is started again and pm2 list will show me no processes running (even though all jobs which are NOT node.js projects are still running). Need to reboot the system to empty everything and run pm2 resurrect again.

I make it by using no daemon mode and take  some product logic change to suit this no daemon mode

**Comment by spmiller** [comment]
We use pm2-windows-service and have noticed the underlying EOF error too. pm2-windows-service runs PM2 in no-daemon mode, so it's not exactly the same situation, but it still causes a crash in PM2. It's quite hard to reproduce; after our set of processes has been running a while I can sometimes reproduce it by running `pm2 status` or similar, but other times I can run a script that tries this for hours with no effect.

The only error message we have is this:
```
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: write EOF
    at WriteWrap.afterWrite [as oncomplete] (net.js:779:14)
Emitted 'error' event at:
    at Socket.<anonymous> (C:\Program Files (x86)\snipped\node_modules\pm2-axon\lib\sockets\sock.js:202:49)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:604:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:781:10)
```

> I make it by using no daemon mode and take some product logic change to suit this no daemon mode

@ayizhi, what was the "product logic change" you did? Do you have any hints as to what might have been causing the socket to be closed? Right now we are working under the assumption that it's a message we're sending that is causing this issue, but this is only an assumption.

**Comment by taieb-tk** [comment]
This error still occure: PM2 error: Error: write EOF, any ideas?
