### ISSUE TITLE
[DEP0112] DeprecationWarning: Socket.prototype._handle is deprecated

### ISSUE THREAD

**Issue by alexcastillo** [Unitech/pm2#4313]
Hi,

Great project, thank you.

## What's going wrong?

I'm getting a deprecation warning on node 12.2.0:

```
10:32:42 0|api      | (node:46081) [DEP0112] DeprecationWarning: Socket.prototype._handle is deprecated
10:32:42 0|api      | Warning DeprecationWarning: Socket.prototype._handle is deprecated
10:32:42 0|api      |     at Object.extractSocket (/Users/alexcastillo/.npm/cache/_npx/45921/lib/node_modules/pm2/node_modules/event-loop-inspector/utils.js:24:23)
10:32:42 0|api      |     at /Users/alexcastillo/.npm/cache/_npx/45921/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:39:17
10:32:42 0|api      |     at Array.forEach (<anonymous>)
10:32:42 0|api      |     at Object.dump (/Users/alexcastillo/.npm/cache/_npx/45921/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:22:42)
10:32:42 0|api      |     at Timeout._onTimeout (/Users/alexcastillo/.npm/cache/_npx/45921/lib/node_modules/pm2/node_modules/@pm2/io/build/main/transports/IPCTransport.js:34:50)
10:32:42 0|api      |     at listOnTimeout (internal/timers.js:531:17)
10:32:42 0|api      |     at processTimers (internal/timers.js:475:7) {
10:32:42 0|api      |   name: 'DeprecationWarning',
10:32:42 0|api      |   code: 'DEP0112'
10:32:42 0|api      | }
```
## Supporting information

```
--- PM2 report ----------------------------------------------------------------
Date                 : Sun Jun 09 2019 10:39:25 GMT-0400 (Eastern Daylight Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.5.1
node version         : 12.2.0
node path            : /Users/alexcastillo/.npm-global/bin/npx
argv                 : /usr/local/bin/node,/Users/alexcastillo/.npm/cache/_npx/45921/bin/pm2,start,ecosystem.config.js,--no-daemon
argv0                : node
user                 : alexcastillo
uid                  : 501
gid                  : 20
uptime               : 11min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.5.1
node version         : 12.2.0
node path            : /Users/alexcastillo/.npm-global/bin/npx
argv                 : /usr/local/bin/node,/Users/alexcastillo/.npm/cache/_npx/46145/bin/pm2,report
argv0                : node
user                 : alexcastillo
uid                  : 501
gid                  : 20
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : darwin
type                 : Darwin
cpus                 : Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
cpus nb              : 4
freemem              : 1781071872
totalmem             : 17179869184
home                 : /Users/alexcastillo
===============================================================================

**Comment by alexcastillo** [comment]
I believe I found another module causing this issue. https://github.com/brightcove/hot-shots/issues/111

**Comment by jeromevalentin** [comment]
I have also the problem without using brightcove! 

```
(node:15802) [DEP0112] DeprecationWarning: Socket.prototype._handle is deprecated
at Object.extractSocket (/home/jvalentin/project/node_modules/event-loop-inspector/utils.js:24:23)
at /home/jvalentin/project/node_modules/event-loop-inspector/index.js:39:17
at Array.forEach (<anonymous>)
at Object.dump (/home/jvalentin/project/node_modules/event-loop-inspector/index.js:22:42)
at Timeout.autoExitHandle.setInterval [as _onTimeout] (/home/jvalentin/project/node_modules/@pm2/io/src/transports/IPCTransport.ts:43:44)
at listOnTimeout (internal/timers.js:535:17)
at processTimers (internal/timers.js:479:7)
```
Node: 11.15.0
```
├─┬ @pm2/io@4.2.5
│ ├─┬ @pm2/agent-node@1.1.10
├─┬ pm2@3.5.1
│ ├─┬ @pm2/agent@0.5.26
│ │ ├── pm2-axon@3.3.0 deduped
│ │ ├── pm2-axon-rpc@0.5.1 deduped
│ ├── @pm2/io@4.2.5 deduped
│ ├─┬ @pm2/js-api@0.5.60
│ ├─┬ pm2-axon@3.3.0
│ ├─┬ pm2-axon-rpc@0.5.1
│ ├─┬ pm2-deploy@0.4.0
│ ├─┬ pm2-multimeter@0.1.2
```
