### ISSUE TITLE
Error: ID, DATA or TOPIC field is missing when using pm2-intercom module.

### ISSUE THREAD

**Issue by mib008** [Unitech/pm2#4378]
```
Error: ID, DATA or TOPIC field is missing
       at Object.God.logAndGenerateError (//node-v10.16.0-linux-x64/lib/node_modules/pm2/lib/God/Methods.js:39:12)
       at God.sendDataToProcessId (//node-v10.16.0-linux-x64/lib/node_modules/pm2/lib/God/ActionMethods.js:709:21)
       at Server.onmessage (//node-v10.16.0-linux-x64/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:104:6)
       at RepSocket.emit (events.js:198:13)
       at RepSocket.EventEmitter.emit (domain.js:448:20)
       at Parser.<anonymous> (//node-v10.16.0-linux-x64/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/rep.js:51:15)
       at Parser.emit (events.js:198:13)
       at Parser.EventEmitter.emit (domain.js:466:23)
       at Parser._write (//node-v10.16.0-linux-x64/lib/node_modules/pm2/node_modules/amp/lib/stream.js:91:16)
       at doWrite (_stream_writable.js:415:12)

```
I debugged pm2/lib/God/ActionMethods.js:709, got the issue args 'packet' is
{ data:'', type:'log:err', ... }
no property named 'topic'.

and found the commit:
https://github.com/Unitech/pm2/commit/b9256cea26547bb3d5a6d10a7959b0674112923d

I searched code 'log:err' in working directory, found it in
node_modules/pm2/lib/ProcessContainer.js:195
node_modules/pm2/lib/ProcessContainer.js:267
...I am not sure, should the message use 'topic' property instead of 'type' that send by ProcessContainer?

My pm2 version is v3.5.1, and node version is v10.16.0

**Comment by EthianWong** [comment]
+1
