### ISSUE TITLE
PM2 API child processes shared logging with parent process?

### ISSUE THREAD

**Issue by kevzettler** [Unitech/pm2#4384]
## What's going wrong?
I am trying to use the [PM2 API](http://pm2.keymetrics.io/docs/usage/pm2-api/) to manually manage child processes. I would like the child processes to write to the same log file that the parent process does. The parent process writes to the default `/var/log/nodejs/nodejs.log` file.

I have tried configuring the child processes to use the `output` and `error` options for this path.

When I set the `output` and `error` options to `/var/log/nodejs/nodejs.log` The child process does not seem to start. Additionally it does not seem to trigger a failure and hit the try catch block. 

## How could we reproduce this issue?

```
    import pm2 from 'pm2-promise';
    try {
      workerConfig = {
        name: 'monitor-worker-0',
        script: './dist/worker.js', // Script to be run
        output: '/var/log/nodejs/nodejs.log',
        error: '/var/log/nodejs/nodejs.log',
      };

      log.info('Starting worker', workerConfig);
      workers = await pm2.start(workerConfig);
    } catch (ex) {
      log.error('Failed to start child worker!');
      log.error(ex);
    }
```

## Supporting information

```
--- PM2 report ----------------------------------------------------------------
Date                 : Tue Aug 06 2019 23:39:15 GMT+0000 (Coordinated Universal Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.5.1
node version         : 10.16.0
node path            : /opt/elasticbeanstalk/node-install/node-v10.16.0-linux-x64/bin/node
argv                 : /opt/elasticbeanstalk/node-install/node-v10.16.0-linux-x64/bin/node,/var/app/current/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : nodejs
uid                  : 496
gid                  : 494
uptime               : 103min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.5.1
node version         : 10.16.0
node path            : not found
argv                 : /opt/elasticbeanstalk/node-install/node-v10.16.0-linux-x64/bin/node,/var/app/current/node_modules/.bin/pm2,report
argv0                : /opt/elasticbeanstalk/node-install/node-v10.16.0-linux-x64/bin/node
user                 : nodejs
uid                  : 496
gid                  : 494
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
cpus nb              : 2
freemem              : 2961891328
totalmem             : 4137099264
home                 : /tmp
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────────────┬────┬─────────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬────────┬──────────┐
│ App name         │ id │ version │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user   │ watching │
├──────────────────┼────┼─────────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼────────┼──────────┤
│ monitor-worker-0 │ 0  │ 0.0.1   │ fork │ 12866 │ online │ 0       │ 103m   │ 1%  │ 89.1 MB   │ nodejs │ disabled │
└──────────────────┴────┴─────────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/tmp/.pm2/pm2.log last 20 lines:
PM2        |     at WriteStream.EventEmitter.emit (domain.js:448:20)
PM2        |     at lazyFs.open (internal/fs/streams.js:277:12)
PM2        |     at FSReqWrap.args [as oncomplete] (fs.js:140:20)
PM2        | 2019-08-06T21:56:12: PM2 log: ===============================================================================
PM2        | 2019-08-06T21:56:13: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2019-08-06T21:56:13: PM2 log: Time                 : Tue Aug 06 2019 21:56:13 GMT+0000 (Coordinated Universal Time)
PM2        | 2019-08-06T21:56:13: PM2 log: PM2 version          : 3.5.1
PM2        | 2019-08-06T21:56:13: PM2 log: Node.js version      : 10.16.0
PM2        | 2019-08-06T21:56:13: PM2 log: Current arch         : x64
PM2        | 2019-08-06T21:56:13: PM2 log: PM2 home             : /tmp/.pm2
PM2        | 2019-08-06T21:56:13: PM2 log: PM2 PID file         : /tmp/.pm2/pm2.pid
PM2        | 2019-08-06T21:56:13: PM2 log: RPC socket file      : /tmp/.pm2/rpc.sock
PM2        | 2019-08-06T21:56:13: PM2 log: BUS socket file      : /tmp/.pm2/pub.sock
PM2        | 2019-08-06T21:56:13: PM2 log: Application log path : /tmp/.pm2/logs
PM2        | 2019-08-06T21:56:13: PM2 log: Process dump file    : /tmp/.pm2/dump.pm2
PM2        | 2019-08-06T21:56:13: PM2 log: Concurrent actions   : 2
PM2        | 2019-08-06T21:56:13: PM2 log: SIGTERM timeout      : 1600
PM2        | 2019-08-06T21:56:13: PM2 log: ===============================================================================
PM2        | 2019-08-06T21:56:13: PM2 log: App [monitor-worker-0:0] starting in -fork mode-
PM2        | 2019-08-06T21:56:13: PM2 log: App [monitor-worker-0:0] online

```

Please copy/paste the above report in your issue on https://github.com/Unitech/pm2/issue
```

**Comment by kevzettler** [comment]
looks like this is stemming from a permissions issue 

```
2019-08-07T00:30:30: PM2 log: App [monitor-worker-0:0] starting in -fork mode-
2019-08-07T00:30:30: PM2 error: Trace: { [Error: EACCES: permission denied, open '/var/log/nodejs/nodejs.log']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/var/log/nodejs/nodejs.log' }
    at Object.God.logAndGenerateError (/var/app/current/node_modules/pm2/lib/God/Methods.js:34:15)
    at /var/app/current/node_modules/pm2/lib/God/ForkMode.js:86:13
    at /var/app/current/node_modules/async/internal/once.js:12:16
    at WriteStream.next (/var/app/current/node_modules/async/waterfall.js:21:29)
    at WriteStream.<anonymous> (/var/app/current/node_modules/async/internal/onlyOnce.js:12:16)
    at Object.onceWrapper (events.js:286:20)
    at WriteStream.emit (events.js:198:13)
    at WriteStream.EventEmitter.emit (domain.js:448:20)
    at lazyFs.open (internal/fs/streams.js:277:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```

Is this setup going to be possible?
