### ISSUE TITLE
stackparser error in 3.51.

### ISSUE THREAD

**Issue by KiPSOFT** [Unitech/pm2#4403]
## What's going wrong?
PM2 restart repeatly.

## How could we reproduce this issue?
Run again.

## Supporting information
{ E_AMI_SOCKED_CLOSE: Lost connection to server.
at Socket.<anonymous> (/var/api/node_modules/asterisk.io/lib/ami.js:277:30)
at Socket.emit (events.js:198:13)
at Socket.EventEmitter.emit (domain.js:448:20)
at TCP._handle.close (net.js:606:12)
message: 'Lost connection to server.',
name: 'E_AMI_SOCKED_CLOSE' }
/usr/lib/node_modules/pm2/node_modules/@pm2/io/build/main/utils/stackParser.js:81
const context = this.cache.get(userFrame.file_name);
                                                                       ^
TypeError: Cannot read property 'file_name' of null
at StackTraceParser.parse (/usr/lib/node_modules/pm2/node_modules/@pm2/io/build/main/utils/stackParser.js:81:50)
 at StackTraceParser.retrieveContext (/usr/lib/node_modules/pm2/node_modules/@pm2/io/build/main/utils/stackParser.js:121:21)
at NotifyFeature.onUncaughtException (/usr/lib/node_modules/pm2/node_modules/@pm2/io/build/main/features/notify.js:112:45)
at process.emit (events.js:203:15)
at process.EventEmitter.emit (domain.js:448:20)
at process._fatalException (internal/bootstrap/node.js:496:27)
PM2                       | App [api_release_auto_start:0] exited with code [7] via signal [SIGINT]
PM2                       | App [api_release_auto_start:0] starting in -fork mode-

```
$ pm2 report
```

**Comment by Unitech** [comment]
x-posted https://github.com/keymetrics/pm2-io-apm/issues/261
