### ISSUE TITLE
Following DotEnv best-practices...question about ecosystem file

### ISSUE THREAD

**Issue by armenr** [Unitech/pm2#4409]
I'm running into an issue.

I want to run the equivalent of this command, via PM2:

`NODE_PATH=/usr/lib/node_modules NODE_ENV=production node --require 'dotenv/config' index.js`

DotEnv is installed globally. All my APIs are compiled into single files via @zeit/ncc, so the only dependencies required on my hosts are node itself, pm2, and dotEnv installed globally. 

What's the correct way of setting up my ecosystem yml file? 

### Current File:

```
apps:
################################################
## Proxy
################################################
  - name          : MY-PROXY
    script        : /opt/myProj/builds/my-proxy/index.js
    interpreter   : node
    args          :
      - NODE_PATH=/usr/lib/node_modules
      - NODE_ENV=production
      - --require 'dotenv/config'
    watch         : false
```

### Behavior:

It appears to run the script, but clearly isn't picking up the `--require` line, as none of my environment variables are loading.

**Comment by armenr** [comment]
I also tried the following:

```
apps:
################################################
## Proxy
################################################
  - name          : MY-PROXY
    cwd           : /opt/myProj/builds/my-proxy
    script        : index.js
    interpreter   : node
    env           :
      NODE_PATH: /usr/lib/node_modules
      NODE_ENV: production
    node_args     : dotenv/config
    watch         : false
```

Yields:
```
0|MY-PROXY  | Error: Cannot find module '/opt/myProj/builds/my-proxy/dotenv/config'
0|MY-PROXY  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
0|MY-PROXY  |     at Function.Module._load (internal/modules/cjs/loader.js:677:27)
0|MY-PROXY  |     at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
0|MY-PROXY  |     at internal/main/run_main_module.js:17:11 {
0|MY-PROXY  |   code: 'MODULE_NOT_FOUND',
0|MY-PROXY  |   requireStack: []
0|MY-PROXY  | }
```

...which would mean it's not picking up NODE_PATH correctly

**Comment by armenr** [comment]
Thanks for all the help, everyone! Closing, since we've decided to ditch PM2.
