### ISSUE TITLE
Contact support, specified bucket doesnt exist

### ISSUE THREAD

**Issue by Puyodead1** [Unitech/pm2#4419]
## What's going wrong?
I tried to login from cli but it kept giving me a js error:
```
(node:5603) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'offer_type' of undefined
    at /usr/lib/node_modules/pm2/lib/API/pm2-plus/PM2IO.js:306:49
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/pm2/lib/API/pm2-plus/PM2IO.js:305:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:5603) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5603) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
so i tried deleting my current buckets but its saying they dont exist and to contact support
## How could we reproduce this issue?
I'm not real sure whats going on
## Supporting information

```
PM2        | 2019-09-12T21:29:38: PM2 log: RPC socket file      : /root/.pm2/rpc.sock
PM2        | 2019-09-12T21:29:38: PM2 log: BUS socket file      : /root/.pm2/pub.sock
PM2        | 2019-09-12T21:29:38: PM2 log: Application log path : /root/.pm2/logs
PM2        | 2019-09-12T21:29:38: PM2 log: Process dump file    : /root/.pm2/dump.pm2
PM2        | 2019-09-12T21:29:38: PM2 log: Concurrent actions   : 2
PM2        | 2019-09-12T21:29:38: PM2 log: SIGTERM timeout      : 1600
PM2        | 2019-09-12T21:29:38: PM2 log: ===============================================================================
PM2        | 2019-09-12T21:29:38: PM2 log: App [pm2-discord:0] starting in -fork mode-
PM2        | 2019-09-12T21:29:38: PM2 log: App [pm2-discord:0] online
PM2        | 2019-09-12T21:33:43: PM2 log: App [app2:1] starting in -fork mode-
PM2        | 2019-09-12T21:33:43: PM2 log: App [app2:1] online
PM2        | 2019-09-12T21:33:50: PM2 log: App [user:2] starting in -fork mode-
PM2        | 2019-09-12T21:33:50: PM2 log: App [user:2] online
PM2        | 2019-09-12T21:34:06: PM2 log: App [server:3] starting in -fork mode-
PM2        | 2019-09-12T21:34:06: PM2 log: App [server:3] online
PM2        | 2019-09-13T00:12:44: PM2 log: Stopping app:pm2-discord id:0
PM2        | 2019-09-13T00:12:45: PM2 log: App [pm2-discord:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-09-13T00:12:45: PM2 log: pid=2494 msg=process killed
PM2        | 2019-09-13T00:14:05: PM2 log: App [pm2-discord:0] starting in -fork mode-
PM2        | 2019-09-13T00:14:05: PM2 log: App [pm2-discord:0] online
```

**Comment by dan-online** [comment]
I am also experiencing the same issue
