### ISSUE TITLE
Cannot run npm commands with pm2 on Windows 10

### ISSUE THREAD

**Issue by Vontus** [Unitech/pm2#4429]
## What's going wrong?
It's not possible to run npm commands with pm2 on Windows 10.
## How could we reproduce this issue?
Run `pm2 start npm -- start` on Windows.
## Supporting information
This is the same as #2808, but that issue is closed and the problem is not solved.

Process logs:
```
0|npm      | C:\PROGRAM FILES\NODEJS\NPM.CMD:1
0|npm      | :: Created by npm, please don't edit manually.
0|npm      | ^
0|npm      |
0|npm      | SyntaxError: Unexpected token :
0|npm      |     at Module._compile (internal/modules/cjs/loader.js:721:23)
0|npm      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
0|npm      |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|npm      |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
0|npm      |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
0|npm      |     at Object.<anonymous> (C:\Users\Alberto\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:27:21)
0|npm      |     at Module._compile (internal/modules/cjs/loader.js:776:30)
0|npm      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
0|npm      |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|npm      |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

```
$ pm2 report
```
```
--- PM2 report ----------------------------------------------------------------
Date                 : Tue Sep 24 2019 10:09:09 GMT+0200 (GMT+02:00)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.5.1
node version         : 10.16.0
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\Alberto\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 14min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.5.1
node version         : 10.16.0
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\Alberto\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : node
user                 : Alberto
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
cpus nb              : 8
freemem              : 6990700544
totalmem             : 17027870720
home                 : C:\Users\Alberto
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬─────────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬─────────┬──────────┐
│ App name │ id │ version │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user    │ watching │
├──────────┼────┼─────────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼─────────┼──────────┤
│ npm      │ 0  │ N/A     │ fork │ 0   │ errored │ 15      │ 0      │ 0%  │ 0 B    │ Alberto │ disabled │
└──────────┴────┴─────────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴─────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
C:\Users\Alberto\.pm2\pm2.log last 20 lines:
PM2        | 2019-09-24T09:54:45: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
PM2        | 2019-09-24T09:54:45: PM2 log: App [npm:0] starting in -fork mode-
PM2        | 2019-09-24T09:54:45: PM2 log: App [npm:0] online
PM2        | 2019-09-24T09:54:45: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
PM2        | 2019-09-24T09:54:45: PM2 log: App [npm:0] starting in -fork mode-
PM2        | 2019-09-24T09:54:45: PM2 log: App [npm:0] online
PM2        | 2019-09-24T09:54:46: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
PM2        | 2019-09-24T09:54:46: PM2 log: App [npm:0] starting in -fork mode-
PM2        | 2019-09-24T09:54:46: PM2 log: App [npm:0] online
PM2        | 2019-09-24T09:54:46: PM2 error: Error caught while calling pidusage
PM2        | 2019-09-24T09:54:46: PM2 error: Error: No hay instancias disponibles.
PM2        |
PM2        | 2019-09-24T09:54:46: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
PM2        | 2019-09-24T09:54:46: PM2 log: App [npm:0] starting in -fork mode-
PM2        | 2019-09-24T09:54:46: PM2 log: App [npm:0] online
PM2        | 2019-09-24T09:54:46: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
PM2        | 2019-09-24T09:54:46: PM2 log: App [npm:0] starting in -fork mode-
PM2        | 2019-09-24T09:54:46: PM2 log: App [npm:0] online
PM2        | 2019-09-24T09:54:46: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
PM2        | 2019-09-24T09:54:46: PM2 log: Script C:\PROGRAM FILES\NODEJS\NPM.CMD had too many unstable restarts (16). Stopped. "errored"

```

**Comment by heavenkiller2018** [comment]
I have the same problem, how to fix it ?is there anyone can help?

**Comment by grubxy** [comment]
same problem.
