### ISSUE TITLE
v11.13 build errors

### ISSUE THREAD

**Issue by EvanCarroll** [Unitech/pm2#444]
```
make: Entering directory `/usr/local/lib/node_modules/pm2/node_modules/usage/build'
  CXX(target) Release/obj.target/sysinfo/src/binding.o
../src/binding.cpp: In function ‘void RegisterModule(v8::Handle<v8::Object>)’:
../src/binding.cpp:8:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     target->Set(String::NewSymbol("HERTZ"), Number::New(sysconf(_SC_CLK_TCK)));
                 ^
../src/binding.cpp:8:77: error: no matching function for call to ‘v8::Number::New(long int)’
     target->Set(String::NewSymbol("HERTZ"), Number::New(sysconf(_SC_CLK_TCK)));
                                                                             ^
../src/binding.cpp:8:77: note: candidate is:
In file included from /usr/local/lib/node_modules/pm2/node_modules/usage/.node-gyp/0.11.13/src/node.h:61:0,
                 from ../src/binding.h:1,
                 from ../src/binding.cpp:1:
/usr/local/lib/node_modules/pm2/node_modules/usage/.node-gyp/0.11.13/deps/v8/include/v8.h:2061:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/usr/local/lib/node_modules/pm2/node_modules/usage/.node-gyp/0.11.13/deps/v8/include/v8.h:2061:24: note:   candidate expects 2 arguments, 1 provided
../src/binding.cpp:9:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     target->Set(String::NewSymbol("PAGE_SIZE"), Number::New(sysconf(_SC_PAGESIZE)));
                 ^
../src/binding.cpp:9:82: error: no matching function for call to ‘v8::Number::New(long int)’
     target->Set(String::NewSymbol("PAGE_SIZE"), Number::New(sysconf(_SC_PAGESIZE)));
                                                                                  ^
../src/binding.cpp:9:82: note: candidate is:
In file included from /usr/local/lib/node_modules/pm2/node_modules/usage/.node-gyp/0.11.13/src/node.h:61:0,
                 from ../src/binding.h:1,
                 from ../src/binding.cpp:1:
/usr/local/lib/node_modules/pm2/node_modules/usage/.node-gyp/0.11.13/deps/v8/include/v8.h:2061:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/usr/local/lib/node_modules/pm2/node_modules/usage/.node-gyp/0.11.13/deps/v8/include/v8.h:2061:24: note:   candidate expects 2 arguments, 1 provided
../src/binding.cpp:17:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     target->Set(String::NewSymbol("OS"), String::New(OS));
                 ^
../src/binding.cpp:17:42: error: ‘New’ is not a member of ‘v8::String’
     target->Set(String::NewSymbol("OS"), String::New(OS));
                                          ^
make: *** [Release/obj.target/sysinfo/src/binding.o] Error 1
make: Leaving directory `/usr/local/lib/node_modules/pm2/node_modules/usage/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/pm2/node_modules/usage
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm http GET https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/mkdirp
npm ERR! usage@0.3.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the usage@0.3.9 install script.
npm ERR! This is most likely a problem with the usage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls usage
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "pm2"
npm ERR! cwd /home/ubuntu/node
npm ERR! node -v v0.11.13
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubuntu/node/npm-debug.log
npm ERR! not ok code 0
```

**Comment by EvanCarroll** [comment]
I'm still getting this very error.
