### ISSUE TITLE
sysinfos network issue

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#4458]
```
PM2        | 2019-10-15T13:49:53: PM2 log: systeminfos collection process offline with code 1
PM2        | /data/nvm/.nvm/versions/node/v10.3.0/lib/node_modules/pm2/node_modules/systeminformation/lib/network.js:807
PM2        |                 let proc = line[6].split('/');
PM2        |                                    ^
PM2        | 
PM2        | TypeError: Cannot read property 'split' of undefined
PM2        |     at /data/nvm/.nvm/versions/node/v10.3.0/lib/node_modules/pm2/node_modules/systeminformation/lib/network.js:807:36
PM2        |     at Array.forEach (<anonymous>)
PM2        |     at /data/nvm/.nvm/versions/node/v10.3.0/lib/node_modules/pm2/node_modules/systeminformation/lib/network.js:786:19
PM2        |     at ChildProcess.exithandler (child_process.js:282:7)
PM2        |     at ChildProcess.emit (events.js:182:13)
PM2        |     at maybeClose (internal/child_process.js:961:16)
PM2        |     at Socket.stream.socket.on (internal/child_process.js:380:11)
PM2        |     at Socket.emit (events.js:182:13)
PM2        |     at Pipe._handle.close [as _onclose] (net.js:596:12)
PM2        | 2019-10-15T13:49:53: PM2 log: systeminfos collection process offline with code 1
```

**Comment by Unitech** [comment]
fixed with systeminformation on last v
