### ISSUE TITLE
Chron jobs persist after pm2 delete myscript

### ISSUE THREAD

**Issue by CyborgDroid** [Unitech/pm2#4485]
Chron jobs persist after deleting the pm2 job. If I add a different job with no chron or with a different chron and the same pm2 ID gets assigned to it, it will restart with the original chron.

To remove the chron jobs I had to restart pm2 itself with `pm2 kill` and `pm2 start`

chron_test.py
```python
from datetime import datetime

now = datetime.now()
dt_string = now.strftime("%d/%m/%Y %H:%M:%S")
print("Chron executed at:", dt_string)
```

```
pm2 start chron_test.py --cron "*/1 * * * *" --interpreter /home/myuser/miniconda3/envs/myenv/bin/python --no-autorestart
```

If there is no script in id 0, it will keep trying to execute the chron schedule as well:
```
$ pm2 delete 0
[PM2] Applying action deleteProcessId on app [0](ids: 0)
[PM2] [0](0) ✓
┌────┬─────────────────────────┬─────────┬─────────┬──────────┬────────┬──────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name                    │ version │ mode    │ pid      │ uptime │ ↺    │ status   │ cpu      │ mem      │ user     │ watching │
└────┴─────────────────────────┴─────────┴─────────┴──────────┴────────┴──────┴──────────┴──────────┴──────────┴──────────┴──────────┘
```

```
PM2        | 2019-10-31T14:08:00: PM2 error: Error: pm_id 0 not available in 0
PM2        |     at Object.God.softReloadProcessId (/usr/local/lib/node_modules/pm2/lib/God/Reload.js:194:17)
PM2        |     at CronJob.onTick (/usr/local/lib/node_modules/pm2/lib/Worker.js:40:13)
PM2        |     at CronJob.fireOnTick (/usr/local/lib/node_modules/pm2/node_modules/cron/lib/cron.js:562:23)
PM2        |     at Timeout.callbackWrapper [as _onTimeout] (/usr/local/lib/node_modules/pm2/node_modules/cron/lib/cron.js:629:10)
PM2        |     at ontimeout (timers.js:482:11)
PM2        |     at tryOnTimeout (timers.js:317:5)
PM2        |     at Timer.listOnTimeout (timers.js:277:5)
PM2        | 2019-10-31T14:09:00: PM2 error: Error: pm_id 0 not available in 0
PM2        |     at Object.God.softReloadProcessId (/usr/local/lib/node_modules/pm2/lib/God/Reload.js:194:17)
PM2        |     at CronJob.onTick (/usr/local/lib/node_modules/pm2/lib/Worker.js:40:13)
PM2        |     at CronJob.fireOnTick (/usr/local/lib/node_modules/pm2/node_modules/cron/lib/cron.js:562:23)
PM2        |     at Timeout.callbackWrapper [as _onTimeout] (/usr/local/lib/node_modules/pm2/node_modules/cron/lib/cron.js:629:10)
PM2        |     at ontimeout (timers.js:482:11)
PM2        |     at tryOnTimeout (timers.js:317:5)
PM2        |     at Timer.listOnTimeout (timers.js:277:5)
PM2        | 2019-10-31T14:10:00: PM2 error: Error: pm_id 0 not available in 0
PM2        |     at Object.God.softReloadProcessId (/usr/local/lib/node_modules/pm2/lib/God/Reload.js:194:17)
PM2        |     at CronJob.onTick (/usr/local/lib/node_modules/pm2/lib/Worker.js:40:13)
PM2        |     at CronJob.fireOnTick (/usr/local/lib/node_modules/pm2/node_modules/cron/lib/cron.js:562:23)
PM2        |     at Timeout.callbackWrapper [as _onTimeout] (/usr/local/lib/node_modules/pm2/node_modules/cron/lib/cron.js:629:10)
PM2        |     at ontimeout (timers.js:482:11)
PM2        |     at tryOnTimeout (timers.js:317:5)
PM2        |     at Timer.listOnTimeout (timers.js:277:5)``
```

**Comment by Unitech** [comment]
This fix has been incorporated to the latest PM2 release.
To update:

```bash
npm install pm2@latest -g
pm2 update
````

**Comment by nikita-fuchs** [comment]
This is happening for me right now, even without anything cron-related (at least not that I"ve knowingly put it in place).

**Comment by ginixsan** [comment]
> This is happening for me right now, even without anything cron-related (at least not that I"ve knowingly put it in place).

For me too. No cron. Process doesn't stop
