### ISSUE TITLE
pm2 DeprecationWarning on OutgoingMessage.prototype._headers 

### ISSUE THREAD

**Issue by olehcambel** [Unitech/pm2#4488]
## What's going wrong?

I upgraded NodeJS version from 10.16.2 to 12.13 and pm2 to latest one.
So now, each time I restart my app, after certain amount of time I get warning
```
process.on('warning', error => {
    logger.error('Warning detected\n%o', error);
});
```

```
	Warning detected
DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
    at Object.extractSocket (/home/node/.nvm/versions/node/v12.13.0/lib/node_modules/pm2/node_modules/event-loop-inspector/utils.js:33:44)
    at /home/node/.nvm/versions/node/v12.13.0/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:39:17
    at Array.forEach (<anonymous>)
    at Object.dump (/home/node/.nvm/versions/node/v12.13.0/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:22:42)
    at Timeout._onTimeout (/home/node/.nvm/versions/node/v12.13.0/lib/node_modules/pm2/node_modules/@pm2/io/build/main/transports/IPCTransport.js:34:50)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  [stack]: 'DeprecationWarning: OutgoingMessage.prototype._headers is deprecated\n' +
    '    at Object.extractSocket (/home/node/.nvm/versions/node/v12.13.0/lib/node_modules/pm2/node_modules/event-loop-inspector/utils.js:33:44)\n' +
    '    at /home/node/.nvm/versions/node/v12.13.0/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:39:17\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at Object.dump (/home/node/.nvm/versions/node/v12.13.0/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:22:42)\n' +
    '    at Timeout._onTimeout (/home/node/.nvm/versions/node/v12.13.0/lib/node_modules/pm2/node_modules/@pm2/io/build/main/transports/IPCTransport.js:34:50)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)',
  [message]: 'OutgoingMessage.prototype._headers is deprecated',
  name: 'DeprecationWarning',
  code: 'DEP0066'
}
```

## How could we reproduce this issue?

- run node.js app with `pm2 start src/index.js --name $npm_package_name && pm2 log $npm_package_name`
- add this process
 ```
process.on('warning', error => {
    logger.error('Warning detected\n%o', error);
});
```
- after certain amount of time (it could be 5 minutes of 5 hours) - I get this warning

## Supporting information

```
--- PM2 report ----------------------------------------------------------------
Date                 : Fri Nov 01 2019 12:23:35 GMT+0200 (Eastern European Standard Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.1.2
node version         : 12.13.0
node path            : /home/node/.nvm/versions/node/v12.13.0/bin/pm2
argv                 : /home/node/.nvm/versions/node/v12.13.0/bin/node,/home/node/.nvm/versions/node/v12.13.0/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : node
uid                  : 1001
gid                  : 1001
uptime               : 13872min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.1.2
node version         : 12.13.0
node path            : /home/node/.nvm/versions/node/v12.13.0/bin/pm2
argv                 : /home/node/.nvm/versions/node/v12.13.0/bin/node,/home/node/.nvm/versions/node/v12.13.0/bin/pm2,report
argv0                : node
user                 : node
uid                  : 1001
gid                  : 1001
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
cpus nb              : 2
freemem              : 483889152
totalmem             : 4148072448
home                 : /home/node
===============================================================================
--- PM2 list -----------------------------------------------
┌────┬────────────────────┬──────────┬──────┬──────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status   │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼──────────┼──────────┼──────────┤
│ 0  │ employee           │ fork     │ 10   │ online   │ 0.5%     │ 73.0mb   │
└────┴────────────────────┴──────────┴──────┴──────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/home/node/.pm2/pm2.log last 20 lines:
PM2        | 2019-11-01T10:11:05: PM2 log: Stopping app:employee id:0
PM2        | 2019-11-01T10:11:05: PM2 log: App [employee:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-11-01T10:11:05: PM2 log: pid=5416 msg=process killed
PM2        | 2019-11-01T10:11:25: PM2 log: App [employee:0] starting in -fork mode-
PM2        | 2019-11-01T10:11:25: PM2 log: App [employee:0] online
PM2        | 2019-11-01T10:12:16: PM2 log: Stopping app:employee id:0
PM2        | 2019-11-01T10:12:16: PM2 log: App [employee:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-11-01T10:12:16: PM2 log: pid=7906 msg=process killed
PM2        | 2019-11-01T10:12:38: PM2 log: App [employee:0] starting in -fork mode-
PM2        | 2019-11-01T10:12:38: PM2 log: App [employee:0] online
PM2        | 2019-11-01T12:07:42: PM2 log: Stopping app:employee id:0
PM2        | 2019-11-01T12:07:42: PM2 log: App [employee:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-11-01T12:07:42: PM2 log: pid=8030 msg=process killed
PM2        | 2019-11-01T12:07:42: PM2 log: App [employee:0] starting in -fork mode-
PM2        | 2019-11-01T12:07:42: PM2 log: App [employee:0] online
PM2        | 2019-11-01T12:09:54: PM2 log: Stopping app:employee id:0
PM2        | 2019-11-01T12:09:54: PM2 log: App [employee:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-11-01T12:09:54: PM2 log: pid=10337 msg=process killed
PM2        | 2019-11-01T12:09:54: PM2 log: App [employee:0] starting in -fork mode-
PM2        | 2019-11-01T12:09:54: PM2 log: App [employee:0] online

```

**Comment by koooge** [comment]
https://github.com/keymetrics/event-loop-inspector/pull/9

**Comment by Unitech** [comment]
Solved, just run PM2 install/update:

```
npm install pm2@latest -g
pm2 update
```

https://github.com/keymetrics/pm2-io-apm/commit/4578a447c71a16e1350814b65c1088f450dbd3e8
