### ISSUE TITLE
package as single binary

### ISSUE THREAD

**Issue by pynixwang** [Unitech/pm2#4505]
## What's going wrong?

I use pm2 for a non node environment, and do not want to install node and npm, then I try to package this into a single binary with `pkg` tool, but fail.

some info:
```
pkg /usr/local/lib/node_modules/pm2/bin/pm2 -t node8-linux-x64
> pkg@4.4.0
> Warning Cannot resolve 'confPath'
  /usr/local/lib/node_modules/pm2/lib/Common.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'path.resolve(filename)'
  /usr/local/lib/node_modules/pm2/lib/Common.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'package_file'
  /usr/local/lib/node_modules/pm2/lib/API/Modules/NPM.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'opts.cmd || opts.package'
  /usr/local/lib/node_modules/pm2/lib/API/Modules/NPM.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'path.join(module_path, 'package.json')'
  /usr/local/lib/node_modules/pm2/lib/API/Modules/TAR.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
```

```
./pm2
pkg/prelude/bootstrap.js:1185
      throw error;
      ^

ReferenceError: source is not defined
    at Object.<anonymous> (/snapshot/pm2/constants.js:1:63)
    at Module.install.Module._compile (/snapshot/pm2/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:662:10)
    at Module.load (module.js:564:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:595:17)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/snapshot/pm2/bin/pm2:0:0)
```

**Comment by Unitech** [comment]
Hey,
Try this: https://getpm2.com/

**Comment by pynixwang** [comment]
@Unitech  this link should be added to README.

**Comment by Unitech** [comment]
It's still in beta, did it worked as you expected?

**Comment by pynixwang** [comment]
@Unitech  yes

**Comment by utsavkapoor** [comment]
@pynixwang @Unitech - Can someone provide me the instructions for this. The website mentioned is not available anymore
