### ISSUE TITLE
Misleading error message when running pm2 from deleted working directory

### ISSUE THREAD

**Issue by inaitana** [Unitech/pm2#4508]
## What's going wrong?

When running just about any pm2 command from a shell where the working directory has been deleted, "_Error: ENOENT: no such file or directory, uv_cwd_" gets thrown.

This has been misleading in my case, where during a deploy I was trying to pm2 restart a job with a _cwd_ configured setting, so the error looked like linked to it, not to my current shell state.
Maybe the exception can be catched and a fitting error message can be used.

## How could we reproduce this issue?

```
root@ubuntu:/home/user# mkdir foobar
root@ubuntu:/home/user# cd foobar
root@ubuntu:/home/user/foobar# rm -r ../foobar
root@ubuntu:/home/user/foobar# pm2 status

path.js:1077
        path = process.cwd();
                       ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1077:24)
    at Function.Module._resolveLookupPaths (internal/modules/cjs/loader.js:534:17)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:629:20)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/bin/pm2:11:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

## Supporting information

pm2 version 3.4.0 on Ubuntu 16.04.5 running Linux 4.4.0-133-generic

"pm2 report" actually throws the same error :D

**Comment by Naterra** [comment]
+1

**Comment by Fernando-Utzig** [comment]
+1 :(
