### ISSUE TITLE
PM2 does not work anymore on NodeJS V6

### ISSUE THREAD

**Issue by cfabio** [Unitech/pm2#4511]
##  What's going wrong?
PM2 doesn't seem to work anymore on NodeJS v6, I think it has to do with the library Chokidar having dropped support to NodeJS versions older than 8; see [pull request](https://github.com/paulmillr/chokidar/pull/798).  
When I run `pm2 start something.js` the only output I get is `[PM2] Spawning PM2 daemon with pm2_home=/home/root/.pm2`.  
`pm2.log` file contains the following error message:  
```
async remove(item) {
        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/Watcher.js:6:16)
```

## How could we reproduce this issue?
Try to use PM2 with NodeJS v6

## Supporting information
```
# pm2 report
[PM2] Spawning PM2 daemon with pm2_home=/home/root/.pm2
```

Am I missing something? Any idea on how I can make PM2 work with this old version of NodeJS?

**Comment by Unitech** [comment]
PM2 v4 does not support Node.js versions bellow 8.x
https://travis-ci.org/Unitech/pm2

**Comment by mahesh19868** [comment]
Hi Unitech,

I am using node version 8.12.0 and I am also getting the same error. Please find the error details below:-



/usr/src/app/node_modules/pm2/node_modules/chokidar/index.js:151
  async remove(item) {
        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/node_modules/pm2/lib/Watcher.js:6:16)

**Comment by alinech20** [comment]
Hey guys,

After we updated to the latest pm2 version, we also got this error and after a bit of reading I saw this node compatibility issue. The thing is that we recently updated to Node 13.10.1 and we still encounter this issue. It writes around 40-50MB of logs each day to that file, this being the only error. Any help, please? Error below:

/usr/lib/node_modules/pm2/node_modules/chokidar/index.js:151
	async remove(item) {
	      ^^^^^^

SyntaxError: Unexpected identifier
	at createScript (vm.js:56:10)
	at Object.runInThisContext (vm.js:97:10)
	at Module._compile (module.js:549:28)
	at Object.Module._extensions..js (module.js:586:10)
	at Module.load (module.js:494:32)
	at tryModuleLoad (module.js:453:12)
	at Function.Module._load (module.js:445:3)
	at Module.require (module.js:504:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/Watcher.js:6:16)

**Comment by noetix** [comment]
If you want to run PM2 on Node v6 you'll have to use version 3.

`npm install pm2@^3`

**Comment by amarjitCloud** [comment]
I had below error:

    /root/.nvm/versions/node/v8.0.0/lib/node_modules/pm2/node_modules/chalk/source/index.js:103
        ...styles,
        ^^^ SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/.nvm/versions/node/v8.0.0/lib/node_modules/pm2/constants.js:10:14)

pm2 supported version 4.1.2 has some issue with Node version 8, We must upgrade node version to at least 12 to work it properly. I did the same and it worked for me.

**Note:** Node. js versions are mostly backward compatible, meaning that code you wrote for Node 8 will work on Node 10 or 12. Thus, if you only have plain old JavaScript you should face no difficulties upgrading
