### ISSUE TITLE
Error when delete a cron job then restart it.

### ISSUE THREAD

**Issue by imcsd** [Unitech/pm2#4532]
I start a process by `ecosystem.config.js` file and I set  cron_restart.

The `ecosystem.config.js` like this:
```js
module.exports = {
  apps : [{
    name: 'App',
    script: 'app.js',
    instances: 1,
    autorestart: false,
    watch: false,
    cron_restart: '0,30 9-16 * * 1-5',
    log_date_format: 'YYYY-MM-DD HH:mm:ss'
  }]
};
```

I run `pm2 start ecosystem.config.js` and then I stop all PM2 process, and I run `pm2 start ecosystem.config.js`  again, the App just run once, didn't restart by cron_restart setting.

When I read ` /root/.pm2/pm2.log`, I see some error like this:
```
2019-11-29T10:00:00: PM2 error: Error: pm_id _old_0 not available in _old_0
    at Object.God.softReloadProcessId (/usr/lib/node_modules/pm2/lib/God/Reload.js:194:17)
    at CronJob.onTick (/usr/lib/node_modules/pm2/lib/Worker.js:36:13)
    at CronJob.fireOnTick (/usr/lib/node_modules/pm2/node_modules/cron/lib/cron.js:562:23)
    at Timeout.callbackWrapper [as _onTimeout] (/usr/lib/node_modules/pm2/node_modules/cron/lib/cron.js:629:10)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by Unitech** [comment]
Which PM2 version are you running? (copy paste output of `pm2 report`)

**Comment by Cstome** [comment]
```
--- PM2 report ----------------------------------------------------------------
Date                 : Tue Dec 03 2019 10:42:59 GMT+0800 (China Standard Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.2.0
node version         : 12.13.1
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
uptime               : 5696min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.2.0
node version         : 12.13.1
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) Gold 6161 CPU @ 2.20GHz
cpus nb              : 1
freemem              : 86130688
totalmem             : 2091356160
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌─────┬─────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name    │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼─────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 1   │ 51Job   │ default     │ 1.0.4   │ cluster │ 29026    │ 12h    │ 1    │ online    │ 0%       │ 71.7mb   │ root     │ disabled │
│ 0   │ TTFund  │ default     │ 1.0.4   │ cluster │ 30327    │ 3D     │ 1    │ online    │ 0%       │ 62.5mb   │ root     │ disabled │
└─────┴─────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/root/.pm2/pm2.log last 20 lines:
PM2        |     at Object.God.softReloadProcessId (/usr/lib/node_modules/pm2/lib/God/Reload.js:194:17)
PM2        |     at CronJob.onTick (/usr/lib/node_modules/pm2/lib/Worker.js:36:13)
PM2        |     at CronJob.fireOnTick (/usr/lib/node_modules/pm2/node_modules/cron/lib/cron.js:562:23)
PM2        |     at Timeout.callbackWrapper [as _onTimeout] (/usr/lib/node_modules/pm2/node_modules/cron/lib/cron.js:629:10)
PM2        |     at listOnTimeout (internal/timers.js:531:17)
PM2        |     at processTimers (internal/timers.js:475:7)
PM2        | 2019-12-03T10:00:00: PM2 error: Error: pm_id _old_0 not available in _old_0
PM2        |     at Object.God.softReloadProcessId (/usr/lib/node_modules/pm2/lib/God/Reload.js:194:17)
PM2        |     at CronJob.onTick (/usr/lib/node_modules/pm2/lib/Worker.js:36:13)
PM2        |     at CronJob.fireOnTick (/usr/lib/node_modules/pm2/node_modules/cron/lib/cron.js:562:23)
PM2        |     at Timeout.callbackWrapper [as _onTimeout] (/usr/lib/node_modules/pm2/node_modules/cron/lib/cron.js:629:10)
PM2        |     at listOnTimeout (internal/timers.js:531:17)
PM2        |     at processTimers (internal/timers.js:475:7)
PM2        | 2019-12-03T10:30:00: PM2 error: Error: pm_id _old_0 not available in _old_0
PM2        |     at Object.God.softReloadProcessId (/usr/lib/node_modules/pm2/lib/God/Reload.js:194:17)
PM2        |     at CronJob.onTick (/usr/lib/node_modules/pm2/lib/Worker.js:36:13)
PM2        |     at CronJob.fireOnTick (/usr/lib/node_modules/pm2/node_modules/cron/lib/cron.js:562:23)
PM2        |     at Timeout.callbackWrapper [as _onTimeout] (/usr/lib/node_modules/pm2/node_modules/cron/lib/cron.js:629:10)
PM2        |     at listOnTimeout (internal/timers.js:531:17)
PM2        |     at processTimers (internal/timers.js:475:7)

```

**Comment by AlexZeDim** [comment]
I guess cron-restart still haven't been fixed and it's still actual issue:

```
PM2        | 2020-02-29T19:52:10: PM2 log: Stopping app:getToken id:0
PM2        | 2020-02-29T19:52:10: PM2 log: App name:getToken id:0 disconnected
PM2        | 2020-02-29T19:52:10: PM2 log: App [getToken:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-02-29T19:52:10: PM2 log: pid=24052 msg=process killed
PM2        | 2020-02-29T19:52:14: PM2 log: [PM2] Deregistering a cron job on: 0
PM2        | 2020-02-29T20:00:24: PM2 log: [PM2][WORKER] Registering a cron job on: 0
PM2        | 2020-02-29T20:00:24: PM2 log: App [getToken:0] starting in -cluster mode-
PM2        | 2020-02-29T20:00:24: PM2 log: App [getToken:0] online
```
According to this logs, the problem here just because active process (in this case it's called: `getToken`) is killed by pm2 via `process.exit(1)` which is an error code.

**Comment by goodwillsandy** [comment]
This issue is still active. I am using version 4.4.0 & i am still facing this issue. 
Just For information, **This happens when ```exec_mode: cluster```** & get resolved when ```exec_mode: fork```.
