### ISSUE TITLE
No restart with watch, 0% cpu and ram

### ISSUE THREAD

**Issue by Romans96** [Unitech/pm2#4541]
## What's going wrong?
Hello! I'm using PM2 from several months, and i haven't any kind of problem. Now, since 1 month all the processes, in the `pm2 list`, said 0% of CPU usage, and 0B of RAM usage.
I tried to clean all the .pm2 files from all the machine, uninstall it and kill all processes, then reinstalled it. But it continue to work in this way, no restart on file modify (or some crashes), and 0 usage of cpu/ram in the pm2 list. But when i start the processes they does not go off:

### $ pm2 list

```

│ id | version │ mode   │ pid   │ uptime │ ↺    │ status   │ cpu      │ mem      │ user     │ watching │

│ 2 │ 1.0.0   │ cluster │ 29983    │ 2D     │ 3    │ online   │ 0%      │ 0b       │ dev… │ enabled  │
│ 0 | 1.2.0   │ cluster │ 1242       │ 17D   │ 3    │ online   │ 0%       │ 0b       │ dev… │ enabled  │
│ 1 │ 1.0.0   │ cluster │ 29935    │ 2D     │ 4    │ online   │ 0%       │ 0b       │ dev… │ enabled  │
│ 5 │ 1.0.0   │ cluster │ 4638      │ 17D   │ 25  │ online   │ 0%      │ 0b       │ dev… │ enabled  │
│ 3 │ 1.0.0   │ cluster │ 15817    │ 2D     │ 1    │ online   │ 0%       │ 0b       │ dev… │ enabled  │
│ 4 │ 2.1.0   │ cluster │ 1478      │ 17D   │ 0    │ online   │ 0%       │ 0b       │ dev… │ enabled  │

```

### $ pm2 report

I made the `pm2 report` command and i had this error:

```
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
/usr/lib/node_modules/pm2/lib/API/Extra.js:110
      fmt.field('cpus', os.cpus()[0].model);
                                 ^

TypeError: Cannot read property '0' of undefined
    at /usr/lib/node_modules/pm2/lib/API/Extra.js:110:34
    at /usr/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (events.js:198:13)
    at Parser._write (/usr/lib/node_modules/pm2/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Parser.Writable.write (_stream_writable.js:299:11)
    at Socket.ondata (_stream_readable.js:708:20)
    at Socket.emit (events.js:198:13)
```

Thank you :)

**Comment by Unitech** [comment]
Wut, your machine seems to have some deep issues. 
What is your node.js version? Linux distribution? pm2 version?
