### ISSUE TITLE
Starting processes on windows - spawn UNKNOWN 

### ISSUE THREAD

**Issue by andyepx** [Unitech/pm2#4552]
## What's going wrong?

I am trying to run a very simple node http server on Windows 10 using PM2. As I run the start command I get the following:
```
[PM2] Spawning PM2 daemon with pm2_home=C:\Developer\pm2_home
[PM2] PM2 Successfully daemonized
[PM2] Starting C:\Developer\apps\script\https-server.js in fork_mode (1 instance)
[PM2] Done.
```
Not sure what the issue is, but the terminal hangs at `Done` and the process doesn't start. I can only install and run `pm2` from my local `node_modules` directory, and not install it as a global dependency.

In the logs file, I can see this after running the start command:

```
PM2        | 2019-12-17T15:21:33: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2019-12-17T15:21:33: PM2 log: Time                 : Tue Dec 17 2019 15:21:33 GMT+1000 (Australian Eastern Standard Time)
PM2        | 2019-12-17T15:21:33: PM2 log: PM2 version          : 4.2.1
PM2        | 2019-12-17T15:21:33: PM2 log: Node.js version      : 11.11.0
PM2        | 2019-12-17T15:21:33: PM2 log: Current arch         : x64
PM2        | 2019-12-17T15:21:33: PM2 log: PM2 home             : C:\Developer\pm2_home
PM2        | 2019-12-17T15:21:33: PM2 log: PM2 PID file         : C:\Developer\pm2_home\pm2.pid
PM2        | 2019-12-17T15:21:33: PM2 log: RPC socket file      : \\.\pipe\rpc.sock
PM2        | 2019-12-17T15:21:33: PM2 log: BUS socket file      : \\.\pipe\pub.sock
PM2        | 2019-12-17T15:21:33: PM2 log: Application log path : C:\Developer\pm2_home\logs
PM2        | 2019-12-17T15:21:33: PM2 log: Worker Interval      : 30000
PM2        | 2019-12-17T15:21:33: PM2 log: Process dump file    : C:\Developer\pm2_home\dump.pm2
PM2        | 2019-12-17T15:21:33: PM2 log: Concurrent actions   : 2
PM2        | 2019-12-17T15:21:33: PM2 log: SIGTERM timeout      : 1600
PM2        | 2019-12-17T15:21:33: PM2 log: ===============================================================================

PM2      | App [container:0] starting in -fork mode-
PM2      | App [container:0] online
PM2      | ===============================================================================
PM2      | --- PM2 global error caught ---------------------------------------------------
PM2      | Time                 : Tue Dec 17 2019 15:22:40 GMT+1000 (Australian Eastern Standard Time)
PM2      | spawn UNKNOWN
PM2      | Error: spawn UNKNOWN
PM2      |     at ChildProcess.spawn (internal/child_process.js:372:11)
PM2      |     at spawn (child_process.js:559:9)
PM2      |     at run (C:\Developer\apps\script\node_modules\pidusage\lib\bin.js:18:12)
PM2      |     at wmic (C:\Developer\apps\script\node_modules\pidusage\lib\wmic.js:48:3)
PM2      |     at get (C:\Developer\apps\script\node_modules\pidusage\lib\stats.js:73:3)
PM2      |     at pidusage (C:\Developer\apps\script\node_modules\pidusage\index.js:25:5)
PM2      |     at getMonitorData (C:\Developer\apps\script\node_modules\pm2\lib\God\ActionMethods.js:60:5)
PM2      |     at Server.onmessage (C:\Developer\apps\script\node_modules\pm2-axon-rpc\lib\server.js:104:6)
PM2      |     at RepSocket.emit (events.js:197:13)
PM2      |     at RepSocket.EventEmitter.emit (domain.js:446:20)
PM2      | ===============================================================================
PM2      | [PM2] Resurrecting PM2
PM2      | PM2 successfully forked
```

I couldn't find any solutions around, what could this be related to? Thank you!

## Supporting information

```
--- PM2 report ----------------------------------------------------------------
Date                 : Tue Dec 17 2019 15:29:22 GMT+1000 (Australian Eastern Standard Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.2.1
node version         : 11.11.0
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Developer\apps\script\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.2.1
node version         : 11.11.0
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Developer\apps\script\node_modules\pm2\bin\pm2,report
argv0                : node
user                 : eeeaaa
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
cpus nb              : 4
freemem              : 9629196288
totalmem             : 17006432256
home                 : C:\Users\eeeaaa
===============================================================================
--- PM2 list -----------------------------------------------
┌─────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
└─────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
C:\Developer\pm2_home\pm2.log last 20 lines:
PM2        |     at Function.Module._load (internal/modules/cjs/loader.js:575:25)
PM2        |     at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
PM2        |     at internal/main/run_main_module.js:21:11
PM2        | 2019-12-17T15:28:05: PM2 log: PM2 successfully forked
PM2        | 2019-12-17T15:29:22: PM2 log: ===============================================================================
PM2        | 2019-12-17T15:29:22: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2019-12-17T15:29:22: PM2 log: Time                 : Tue Dec 17 2019 15:29:22 GMT+1000 (Australian Eastern Standard Time)
PM2        | 2019-12-17T15:29:22: PM2 log: PM2 version          : 4.2.1
PM2        | 2019-12-17T15:29:22: PM2 log: Node.js version      : 11.11.0
PM2        | 2019-12-17T15:29:22: PM2 log: Current arch         : x64
PM2        | 2019-12-17T15:29:22: PM2 log: PM2 home             : C:\Developer\pm2_home
PM2        | 2019-12-17T15:29:22: PM2 log: PM2 PID file         : C:\Developer\pm2_home\pm2.pid
PM2        | 2019-12-17T15:29:22: PM2 log: RPC socket file      : \\.\pipe\rpc.sock
PM2        | 2019-12-17T15:29:22: PM2 log: BUS socket file      : \\.\pipe\pub.sock
PM2        | 2019-12-17T15:29:22: PM2 log: Application log path : C:\Developer\pm2_home\logs
PM2        | 2019-12-17T15:29:22: PM2 log: Worker Interval      : 30000
PM2        | 2019-12-17T15:29:22: PM2 log: Process dump file    : C:\Developer\pm2_home\dump.pm2
PM2        | 2019-12-17T15:29:22: PM2 log: Concurrent actions   : 2
PM2        | 2019-12-17T15:29:22: PM2 log: SIGTERM timeout      : 1600
PM2        | 2019-12-17T15:29:22: PM2 log: ===============================================================================

```

**Comment by Unitech** [comment]
Not related to PM2, looks like an issue with Node.js install https://github.com/microsoft/vscode/issues/74197
