### ISSUE TITLE
[nodemon][npm script] Cluster mode nodejs processes logs does not display

### ISSUE THREAD

**Issue by aprilmintacpineda** [Unitech/pm2#4566]
## What's going wrong?

Logs of cluster workers doesn't show.

## How could we reproduce this issue?

1. Run a nodejs process, that does console log, in cluster mode (`pm2 start npm -i --name sweet-cluster -- run dev`).
2. Do `pm2 monit`.
3. Admire the worker processes of the cluster (displayed on the processes box).
4. Be sad that the log box of all the cluster workers are empty.

## Supporting information

In this context, pm2 is running `npm run dev` which is running `cross-env NODE_ENV=dev nodemon --ignore schema.json --ignore dist --exec npx babel-node -- src/server.js`.

With `pm2 logs [worker-process-id] --lines 100`, I can see the initial logs of npm itself:

```
[TAILING] Tailing last 100 lines for [2] process (change the value with --lines option)
/Users/aprilmintacpineda/.pm2/logs/portal-be-cluster-error.log last 100 lines:
/Users/aprilmintacpineda/.pm2/logs/portal-be-cluster-out.log last 100 lines:
2|portal-b |
2|portal-b | > my-app@1.0.1 dev /Users/aprilmintacpineda/work/my-app/server
2|portal-b | > cross-env NODE_ENV=dev nodemon --ignore schema.json --ignore dist --exec npx babel-node -- src/server.js
2|portal-b |
2|portal-b |
2|portal-b | > my-app@1.0.1 dev /Users/aprilmintacpineda/work/my-app/server
2|portal-b | > cross-env NODE_ENV=dev nodemon --ignore schema.json --ignore dist --exec npx babel-node -- src/server.js
2|portal-b |
2|portal-b |
2|portal-b | > my-app@1.0.1 dev /Users/aprilmintacpineda/work/my-app/server
2|portal-b | > cross-env NODE_ENV=dev nodemon --ignore schema.json --ignore dist --exec npx babel-node -- src/server.js
2|portal-b |
2|portal-b |
2|portal-b | > my-app@1.0.1 dev /Users/aprilmintacpineda/work/my-app/server
2|portal-b | > cross-env NODE_ENV=dev nodemon --ignore schema.json --ignore dist --exec npx babel-node -- src/server.js
2|portal-b |
```

```
--- PM2 report ----------------------------------------------------------------
Date                 : Fri Jan 03 2020 14:35:13 GMT+0800 (Philippine Standard Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.2.1
node version         : 13.5.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/Cellar/node/13.5.0/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : aprilmintacpineda
uid                  : 501
gid                  : 20
uptime               : 296min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.2.1
node version         : 13.5.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/Cellar/node/13.5.0/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : aprilmintacpineda
uid                  : 501
gid                  : 20
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : darwin
type                 : Darwin
cpus                 : Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz
cpus nb              : 4
freemem              : 3397160960
totalmem             : 17179869184
home                 : /Users/aprilmintacpineda
===============================================================================
--- PM2 list -----------------------------------------------
┌─────┬──────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name                 │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2   │ portal-be-cluster    │ default     │ N/A     │ cluster │ 4475     │ 4h     │ 0    │ online    │ 0%       │ 38.5mb   │ apr… │ disabled │
│ 3   │ portal-be-cluster    │ default     │ N/A     │ cluster │ 4476     │ 4h     │ 0    │ online    │ 0%       │ 37.8mb   │ apr… │ disabled │
│ 4   │ portal-be-cluster    │ default     │ N/A     │ cluster │ 4477     │ 4h     │ 0    │ online    │ 0%       │ 37.3mb   │ apr… │ disabled │
│ 5   │ portal-be-cluster    │ default     │ N/A     │ cluster │ 4478     │ 4h     │ 0    │ online    │ 0%       │ 37.5mb   │ apr… │ disabled │
│ 0   │ portal-fe            │ default     │ N/A     │ fork    │ 15555    │ 42m    │ 2    │ online    │ 0%       │ 34.2mb   │ apr… │ disabled │
└─────┴──────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/Users/aprilmintacpineda/.pm2/pm2.log last 20 lines:
PM2        |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
PM2        |     at Object.<anonymous> (/Users/aprilmintacpineda/my-app/server/node_modules/@babel/node/lib/_babel-node.js:238:23)
PM2        |     at Module._compile (internal/modules/cjs/loader.js:1139:30)
PM2        |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
PM2        |     at Module.load (internal/modules/cjs/loader.js:988:32)
PM2        |     at Function.Module._load (internal/modules/cjs/loader.js:896:14)
PM2        |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
PM2        |     at internal/main/run_main_module.js:17:47
PM2        | Emitted 'error' event on WebSocketServer instance at:
PM2        |     at Server.emit (events.js:305:20)
PM2        |     at emitErrorNT (net.js:1335:8)
PM2        |     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
PM2        |   code: 'EADDRINUSE',
PM2        |   errno: -48,
PM2        |   syscall: 'listen',
PM2        |   address: '::',
PM2        |   port: 7071
PM2        | }
PM2        | [nodemon] app crashed - waiting for file changes before starting...
PM2        | [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by felixmosh** [comment]
I have the same issue :\ seems that it worked in previous major version (v3)
