### ISSUE TITLE
TypeError: debug_1.default is not a function

### ISSUE THREAD

**Issue by jlubeck** [Unitech/pm2#4610]
I'm getting this error inside the log files after pm2 has been started:

```
TypeError: debug_1.default is not a function
    at Object.<anonymous> (/usr/lib/node_modules/@pm2/io/build/main/src/configuration.js:4:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/@pm2/io/build/main/src/features/notify.js:6:25)
    at Module._compile (module.js:570:32)
/usr/lib/node_modules/@pm2/io/build/main/src/configuration.js:4
const debug = debug_1.default('axm:configuration');
```
And my errors logs are getting flooded with it. What is causing this?  I checked and de debug module is there in the node_modules folder

**Comment by jlubeck** [comment]
Was using an old version of the debug module.
