### ISSUE TITLE
/usr/lib/node_modules/pm2/lib/binaries/CLI.js:997

### ISSUE THREAD

**Issue by besthigh** [Unitech/pm2#4620]
## What's going wrong?
Centos7(RedHat 4.8.5) 

Can't start pm2 any command just see that..

## How could we reproduce this issue?

/usr/lib/node_modules/pm2/lib/binaries/CLI.js:997
  .action(() => {
           ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/bin/pm2:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

## Supporting information

```
$ pm2 report
```

**Comment by fancy-crab** [comment]
I'm having the same exact issue. This happened after a reboot of the system. My environment is raspbian buster.

**Comment by besthigh** [comment]
> I'm having the same exact issue. This happened after a reboot of the system. My environment is raspbian buster.

I've done the same thing, and I've solved this. It was not clear how it happened, but I removed it all, re-installed everything from npm, and set up environment variables.
