### ISSUE TITLE
Error "Unexpected reserved word" with node v0.12 as interpreter

### ISSUE THREAD

**Issue by CherryDT** [Unitech/pm2#4625]
## What's going wrong?

I have configured an app with a custom `interpreter` which is node v0.12. Starting this app fails with the following error:

    1|zhcs-ssl | 2020-03-05 15:46:39: /home/ubuntu/.npm- global/lib/node_modules/pm2/lib/ProcessContainerFork.js:29
    1|zhcs-ssl | 2020-03-05 15:46:39:     import(process.env.pm_exec_path);
    1|zhcs-ssl | 2020-03-05 15:46:39:     ^^^^^^
    1|zhcs-ssl | 2020-03-05 15:46:39: SyntaxError: Unexpected reserved word
    1|zhcs-ssl | 2020-03-05 15:46:39:     at exports.runInThisContext (vm.js:73:16)
    1|zhcs-ssl | 2020-03-05 15:46:39:     at Module._compile (module.js:443:25)
    1|zhcs-ssl | 2020-03-05 15:46:39:     at Object.Module._extensions..js (module.js:478:10)
    1|zhcs-ssl | 2020-03-05 15:46:39:     at Module.load (module.js:355:32)
    1|zhcs-ssl | 2020-03-05 15:46:39:     at Function.Module._load (module.js:310:12)
    1|zhcs-ssl | 2020-03-05 15:46:39:     at Function.Module.runMain (module.js:501:10)
    1|zhcs-ssl | 2020-03-05 15:46:39:     at startup (node.js:129:16)
    1|zhcs-ssl | 2020-03-05 15:46:39:     at node.js:814:3

Note that it works when I create a copy of node v0.12 and call it `node2` instead of `node`. I think this behavior is very unexpected.

My app is configured like this:

```json
                {
                        "name": "zhcs-sslproxy",
                        "interpreter": "/home/ubuntu/app/zhcs-sslproxy/node-v0.12.18-linux-x64/bin/node",
                        "script": "index.js",
                        "args": "",
                        "cwd": "/home/ubuntu/app/zhcs-sslproxy",
                        "env": {
                                "PORT": 3000
                        },
                        "log_file": "/home/ubuntu/.pm2/logs/zhcs-sslproxy_combined.log",
                        "log_date_format": "YYYY-MM-DD HH:mm:ss"
                }
```

## How could we reproduce this issue?

Set interpreter of an app to node v0.12.

## Supporting information

```
--- PM2 report ----------------------------------------------------------------
Date                 : Thu Mar 05 2020 15:54:44 GMT+0000 (Coordinated Universal Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.2.3
node version         : 12.16.1
node path            : not found
argv                 : /usr/local/bin/node,/home/ubuntu/.npm-global/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : ubuntu
uid                  : 1000
gid                  : 1000
uptime               : 8min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.2.3
node version         : 12.16.1
node path            : /home/ubuntu/.npm-global/bin/pm2
argv                 : /usr/local/bin/node,/home/ubuntu/.npm-global/bin/pm2,report
argv0                : node
user                 : ubuntu
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : AMD EPYC 7571
cpus nb              : 2
freemem              : 116588544
totalmem             : 2057093120
home                 : /home/ubuntu
===============================================================================
--- PM2 list -----------------------------------------------
┌─────┬───────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name                  │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼───────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2   │ warehouse-es-proxy    │ default     │ 1.0.8-… │ fork    │ 29335    │ 8m     │ 0    │ online    │ 0.2%     │ 46.7mb   │ ubuntu   │ disabled │
│ 1   │ zhcs-sslproxy         │ default     │ 1.3.0   │ fork    │ 0        │ 0      │ 15   │ errored   │ 0%       │ 0b       │ ubuntu   │ disabled │
└─────┴───────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
Module
┌────┬───────────────────────────────────────┬────────────────────┬───────┬──────────┬──────┬──────────┬──────────┬──────────┐
│ id │ module                                │ version            │ pid   │ status   │ ↺    │ cpu      │ mem      │ user     │
├────┼───────────────────────────────────────┼────────────────────┼───────┼──────────┼──────┼──────────┼──────────┼──────────┤
│ 0  │ pm2-logrotate                         │ 2.7.0              │ 29322 │ online   │ 0    │ 0%       │ 42.8mb   │ ubuntu   │
└────┴───────────────────────────────────────┴────────────────────┴───────┴──────────┴──────┴──────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/home/ubuntu/.pm2/pm2.log last 20 lines:
PM2        | 2020-03-05T15:46:38: PM2 log: App [zhcs-sslproxy:1] exited with code [1] via signal [SIGINT]
PM2        | 2020-03-05T15:46:38: PM2 log: App [zhcs-sslproxy:1] starting in -fork mode-
PM2        | 2020-03-05T15:46:38: PM2 log: App [zhcs-sslproxy:1] online
PM2        | 2020-03-05T15:46:38: PM2 log: App [zhcs-sslproxy:1] exited with code [1] via signal [SIGINT]
PM2        | 2020-03-05T15:46:38: PM2 log: App [zhcs-sslproxy:1] starting in -fork mode-
PM2        | 2020-03-05T15:46:38: PM2 log: App [zhcs-sslproxy:1] online
PM2        | 2020-03-05T15:46:38: PM2 log: App [zhcs-sslproxy:1] exited with code [1] via signal [SIGINT]
PM2        | 2020-03-05T15:46:38: PM2 log: App [zhcs-sslproxy:1] starting in -fork mode-
PM2        | 2020-03-05T15:46:38: PM2 log: App [zhcs-sslproxy:1] online
PM2        | 2020-03-05T15:46:38: PM2 log: App [zhcs-sslproxy:1] exited with code [1] via signal [SIGINT]
PM2        | 2020-03-05T15:46:38: PM2 log: App [zhcs-sslproxy:1] starting in -fork mode-
PM2        | 2020-03-05T15:46:38: PM2 log: App [zhcs-sslproxy:1] online
PM2        | 2020-03-05T15:46:39: PM2 log: App [zhcs-sslproxy:1] exited with code [1] via signal [SIGINT]
PM2        | 2020-03-05T15:46:39: PM2 log: App [zhcs-sslproxy:1] starting in -fork mode-
PM2        | 2020-03-05T15:46:39: PM2 log: App [zhcs-sslproxy:1] online
PM2        | 2020-03-05T15:46:39: PM2 log: App [zhcs-sslproxy:1] exited with code [1] via signal [SIGINT]
PM2        | 2020-03-05T15:46:39: PM2 log: App [zhcs-sslproxy:1] starting in -fork mode-
PM2        | 2020-03-05T15:46:39: PM2 log: App [zhcs-sslproxy:1] online
PM2        | 2020-03-05T15:46:39: PM2 log: App [zhcs-sslproxy:1] exited with code [1] via signal [SIGINT]
PM2        | 2020-03-05T15:46:39: PM2 log: Script /home/ubuntu/app/zhcs-sslproxy/index.js had too many unstable restarts (16). Stopped. "errored"
```

**Comment by Xaekai** [comment]
Just so there is no confusion, you are still trying to using the absolutely ancient Node v0.12.8 that is the three _[hundred sixth item](https://nodejs.org/en/download/releases/)_ in this list from the v0.12 series which was first released in **2015** and was **five** LTS release cycles ago, and last _code changing_ commit was _[1208](https://github.com/nodejs/node/commits/v0.12)_ days ago?

Anyway, 
```js
// Require the real application
if (process.env.pm_exec_path) {
  if (ProcessUtils.isESModule(process.env.pm_exec_path) === true) {
    import(process.env.pm_exec_path);
  }
  else
    require('module')._load(process.env.pm_exec_path, null, true);
}
else
  throw new Error('Could not _load() the script');
```

Which we can trace back to [here](https://github.com/Unitech/pm2/blob/master/lib/God/ForkMode.js#L57) I think. Perhaps an option should be provided so users could explicitly state their app is old as shit with some `"legacy: %anythingTruthy%"` flag.

However, the fact that the interpreter executable filename is being RegEx'd as a detection mechanism _is_ bad form.

**Comment by CherryDT** [comment]
Yes. :)

Long story.

It's necessary to proxy ssl requests to an equally old server that all regular software nowadays refuses to talk to. node 0.12 comes with an old enough version of openssl that it still works.

**Comment by Xaekai** [comment]
I actually have dealt with that exact problem before, I ended up building a statically-linked custom module (built with ancient openssl) to act as an endpoint agent for that one legacy system.

If the client wants to spend the billable hours  ¯\_(ツ)_/¯

**Comment by Xaekai** [comment]
It's not stale Mr. Bot. Regex against the executable file name as the sole diagnostic determination what interpreter the user as invoked is still poor form.

**Comment by CherryDT** [comment]
@Xaekai seems it was closed anyway :(

**Comment by HimanshuAgrahari07** [comment]
I want to run the node version 4.9.1, I do get the same error. What was the fix / workaround for this?
