### ISSUE TITLE
this.autodump is not a function

### ISSUE THREAD

**Issue by vanchu001** [Unitech/pm2#4694]
pm2 v4.4.0

use
```shell
echo '[{"name":"mobile_bff/alpha2"}]' | pm2 stop -
```
throw a error
```shell
/ssd-extand/soft/node-version/node-v14.1.0-linux-x64/lib/node_modules/pm2/lib/API.js:588
          this.autodump(() => {
               ^

TypeError: this.autodump is not a function
    at /ssd-extand/soft/node-version/node-v14.1.0-linux-x64/lib/node_modules/pm2/lib/API.js:588:16
    at /ssd-extand/soft/node-version/node-v14.1.0-linux-x64/lib/node_modules/pm2/lib/API.js:1310:22
    at wrapper (/ssd-extand/soft/node-version/node-v14.1.0-linux-x64/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16)
    at iterateeCallback (/ssd-extand/soft/node-version/node-v14.1.0-linux-x64/lib/node_modules/pm2/node_modules/async/internal/eachOfLimit.js:63:24)
    at /ssd-extand/soft/node-version/node-v14.1.0-linux-x64/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
    at /ssd-extand/soft/node-version/node-v14.1.0-linux-x64/lib/node_modules/pm2/lib/API.js:1306:18
    at wrapper (/ssd-extand/soft/node-version/node-v14.1.0-linux-x64/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16)
    at iterateeCallback (/ssd-extand/soft/node-version/node-v14.1.0-linux-x64/lib/node_modules/pm2/node_modules/async/internal/eachOfLimit.js:63:24)
    at /ssd-extand/soft/node-version/node-v14.1.0-linux-x64/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
    at /ssd-extand/soft/node-version/node-v14.1.0-linux-x64/lib/node_modules/pm2/lib/API.js:1303:20
[PM2] [mobile_bff/alpha2](0) ✓
```

**Comment by Unitech** [comment]
thanks for reporting, will be in next release
