### ISSUE TITLE
Execute (non-interpreted) binaries

### ISSUE THREAD

**Issue by ravi** [Unitech/pm2#471]
PM2 is fully capable of executing binaries as it does interpreted scripts, but cannot do so today because of the forcing of an interpreter in ForkMode.js. Of course any binary can be wrapped in a shell script, but is that level of obfuscation of any value? I'd like to submit a pull request to make the relevant change to ForkMode.js to add a check for `exec_interpreter === 'none``, if there is interest. Thank you.

**Comment by vmarchaud** [comment]
`--interpreterArgs` option should work ;)

**Comment by mtrabelsi** [comment]
Thanks @vmarchaud! 

I've tried this : 

`pm2 start  "myApp -d param.json" --interpreterArgs  --interpreter none -x -- --server`

 And I got an error  :

> error: unknown option `--interpreterArgs'

Then I've seen the [doc ](http://pm2.keymetrics.io/docs/usage/pm2-api/) but can't see any sample using this option in action.

**Comment by Haythamamin** [comment]
I have the same issue ! when I dont specify `"exec_interpreter": "none",` app start in fork - mode, but with `"exec_interpreter": "none",` included in .json file app start in cluster - mode but I get the following error:
```
SyntaxError: Invalid or unexpected token
04:58:23 5|app  |     at new Script (vm.js:79:7)
04:58:23 5|app  |     at createScript (vm.js:251:10)
04:58:23 5|app  |     at Object.runInThisContext (vm.js:303:10)
04:58:23 5|app  |     at Module._compile (internal/modules/cjs/loader.js:657:28)
04:58:23 5|app  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
04:58:23 5|app  |     at Module.load (internal/modules/cjs/loader.js:599:32)
04:58:23 5|app  |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
04:58:23 5|app  |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
04:58:23 5|app  |     at Function._load (/usr/local/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:172:43)
04:58:23 5|app  |     at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:295:23
04:58:23 6|app  | /bin/bash:1
04:58:23 6|app  | (function (exports, require, module, __filename, __dirname) { ELF
04:58:23 6|app  |                                                               ^
04:58:23 6|app  | SyntaxError: Invalid or unexpected token
04:58:23 6|app  |     at new Script (vm.js:79:7)
04:58:23 6|app  |     at createScript (vm.js:251:10)
04:58:23 6|app  |     at Object.runInThisContext (vm.js:303:10)
04:58:23 6|app  |     at Module._compile (internal/modules/cjs/loader.js:657:28)
04:58:23 6|app  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
04:58:23 6|app  |     at Module.load (internal/modules/cjs/loader.js:599:32)
04:58:23 6|app  |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
04:58:23 6|app  |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
04:58:23 6|app  |     at Function._load (/usr/local/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:172:43)
04:58:23 6|app  |     at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:295:23
```
