### ISSUE TITLE
SyntaxError: Invalid or unexpected token in /bin/bash

### ISSUE THREAD

**Issue by vcheeze** [Unitech/pm2#4722]
## What's going wrong?
I am trying to run pm2 on an AWS EC2 instance, and I encounter this error when I do a `pm2 start`:
```
SyntaxError: Invalid or unexpected token
     at wrapSafe (internal/modules/cjs/loader.js:1063:16)
     at Module._compile (internal/modules/cjs/loader.js:1111:27)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
     at Module.load (internal/modules/cjs/loader.js:996:32)
     at Function.Module._load (internal/modules/cjs/loader.js:896:14)
     at /usr/lib/node_modules/pm2/lib/ProcessContainer.js:303:25
     at wrapper (/usr/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16)
     at next (/usr/lib/node_modules/pm2/node_modules/async/waterfall.js:96:20)
     at /usr/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
     at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:186:13)
 /bin/bash:1
 ELF
```
Any help would be appreciated.
## How could we reproduce this issue?
I built my app with Sapper.js. My ecosystem.config.js is quite simple:
```
module.exports = {
  apps: [{
    name: 'my-app'
    script: 'node __sapper__/build',
    exec_mode: 'cluster',
    instances: 1,
    watch: true,
    env: {
      NODE_ENV: 'development',
    },
    env_production: {
      NODE_ENV: 'production',
    },
  }]
}
```
Running a [Sapper app](https://github.com/sveltejs/sapper) with pm2 should reproduce the issue.
## Supporting information

```
$ pm2 report
```
```
--- PM2 report ----------------------------------------------------------------
Date                 : Sun May 24 2020 20:16:14 GMT+0000 (Coordinated Universal Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.4.0
node version         : 13.11.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : ubuntu
uid                  : 1000
gid                  : 1000
uptime               : 12min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.4.0
node version         : 13.11.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : ubuntu
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
cpus nb              : 2
freemem              : 461455360
totalmem             : 1004003328
home                 : /home/ubuntu
===============================================================================
--- PM2 list -----------------------------------------------
┌─────┬────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name           │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ my-app    │ default     │ N/A     │ cluster │ 0        │ 0      │ 15   │ errored   │ 0%       │ 0b       │ ubuntu   │ enabled  │
└─────┴────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/home/ubuntu/.pm2/pm2.log last 20 lines:
PM2        | 2020-05-24T20:03:25: PM2 log: App [my-app:0] online
PM2        | 2020-05-24T20:03:25: PM2 log: App name:my-app id:0 disconnected
PM2        | 2020-05-24T20:03:25: PM2 log: App [my-app:0] exited with code [0] via signal [SIGINT]
PM2        | 2020-05-24T20:03:25: PM2 log: App [my-app:0] starting in -cluster mode-
PM2        | 2020-05-24T20:03:25: PM2 log: App [my-app:0] online
PM2        | 2020-05-24T20:03:25: PM2 log: App name:my-app id:0 disconnected
PM2        | 2020-05-24T20:03:25: PM2 log: App [my-app:0] exited with code [0] via signal [SIGINT]
PM2        | 2020-05-24T20:03:25: PM2 log: App [my-app:0] starting in -cluster mode-
PM2        | 2020-05-24T20:03:25: PM2 log: App [my-app:0] online
PM2        | 2020-05-24T20:03:26: PM2 log: App name:my-app id:0 disconnected
PM2        | 2020-05-24T20:03:26: PM2 log: App [my-app:0] exited with code [0] via signal [SIGINT]
PM2        | 2020-05-24T20:03:26: PM2 log: App [my-app:0] starting in -cluster mode-
PM2        | 2020-05-24T20:03:26: PM2 log: App [my-app:0] online
PM2        | 2020-05-24T20:03:26: PM2 log: App name:my-app id:0 disconnected
PM2        | 2020-05-24T20:03:26: PM2 log: App [my-app:0] exited with code [0] via signal [SIGINT]
PM2        | 2020-05-24T20:03:26: PM2 log: App [my-app:0] starting in -cluster mode-
PM2        | 2020-05-24T20:03:26: PM2 log: App [my-app:0] online
PM2        | 2020-05-24T20:03:26: PM2 log: App name:my-app id:0 disconnected
PM2        | 2020-05-24T20:03:26: PM2 log: App [my-app:0] exited with code [0] via signal [SIGINT]
PM2        | 2020-05-24T20:03:26: PM2 log: Script /bin/bash had too many unstable restarts (16). Stopped. "errored"

```

**Comment by ntngoc96** [comment]
Did you fix it, bro ??

**Comment by ntngoc96** [comment]
I got the same error, anyone please help :((

**Comment by KevinylZhao** [comment]
I got the same error, anyone please help :((

**Comment by samanar** [comment]
any updated ??

**Comment by fenos** [comment]
same here

**Comment by KevinylZhao** [comment]
any updates ??

**Comment by Unitech** [comment]
Drop "node" in the line `script: 'node __sapper__/build'`

Script should be only the path to the script that must be started

**Comment by m1m6** [comment]
same here

**Comment by cchalfan1** [comment]
@Unitech answer worked for me.

> Drop "node" in the line `script: 'node __sapper__/build'`
> 
> Script should be only the path to the script that must be started

**Comment by johanazhu** [comment]
name: 'my-app'  no  ‘,’

**Comment by johanazhu** [comment]
same here

**Comment by waelio** [comment]
> Drop "node" in the line `script: 'node __sapper__/build'`
> 
> Script should be only the path to the script that must be started
where? in `package.json`??

**Comment by jithinsk** [comment]
It seems in cluster mode we have to give the path to the script that should be started.
eg: `script: "dist/index.js"`

If not using cluster mode then the following will work alright.
`script: "node dist/index.js"`

I had compile tasks inside the script.
eg: `npm run dev:compile && npm run start`
This is working alright in normal mode, but throws error in cluster mode.

**Comment by pavankumar-meesho** [comment]
+1 running fine on normal mode but not on cluster mode

**Comment by HugoLMTY** [comment]
same problem here with `"script": "npm start",`
