### ISSUE TITLE
Cannot find module Strapi

### ISSUE THREAD

**Issue by juliensl** [Unitech/pm2#4750]
Hi everybody, 

## What's going wrong?
I'm trying to run an application with pm2, but I can't.
I have this message in my logs : 
```
Error: Cannot find module '/home/lfg/new_strapi/strapi-gatsby-stable'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
at Function.Module._load (internal/modules/cjs/loader.js:840:27)
at Object.<anonymous> (/home/lfg/.nvm/versions/node/v12.16.3/lib/node_modules/pm2/lib/ProcessContainerFork.js:32:23)
at Module._compile (internal/modules/cjs/loader.js:1133:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
at Module.load (internal/modules/cjs/loader.js:977:32)
at Function.Module._load (internal/modules/cjs/loader.js:877:14)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
at internal/main/run_main_module.js:18:47 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}
```

What I don't understand, is that I did `npm install`, `npm run build` and when I launch `npm run develop` or `npm run start`, my strapi server is launched and worked.

## How could we reproduce this issue?
I don't know... Try to launch a clean strapi project ? 

## Supporting information

```
--- PM2 report ----------------------------------------------------------------
Date                 : Thu Jun 18 2020 10:16:38 GMT+0000 (Coordinated Universal Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.4.0
node version         : 12.16.3
node path            : /home/lfg/.nvm/versions/node/v12.16.3/bin/pm2
argv                 : /home/lfg/.nvm/versions/node/v12.16.3/bin/node,/home/lfg/.nvm/versions/node/v12.16.3/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : lfg
uid                  : 1000
gid                  : 1000
uptime               : 9min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.4.0
node version         : 12.16.3
node path            : /home/lfg/.nvm/versions/node/v12.16.3/bin/pm2
argv                 : /home/lfg/.nvm/versions/node/v12.16.3/bin/node,/home/lfg/.nvm/versions/node/v12.16.3/bin/pm2,report
argv0                : node
user                 : lfg
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
cpus nb              : 1
freemem              : 865374208
totalmem             : 1998045184
home                 : /home/lfg
===============================================================================
--- PM2 list -----------------------------------------------
┌─────┬─────────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name                    │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼─────────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ strapi-gatsby-stable    │ default     │ 0.1.0   │ fork    │ 0        │ 0      │ 15   │ errored   │ 0%       │ 0b       │ lfg      │ disabled │
└─────┴─────────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[PM2][WARN] Current process list running is not in sync with saved list. Type 'pm2 save' to synchronize or enable autosync via 'pm2 set pm2:autodump true'
===============================================================================
--- Daemon logs --------------------------------------------
/home/lfg/.pm2/pm2.log last 20 lines:
PM2        | 2020-06-18T10:06:57: PM2 log: App [strapi-gatsby-stable:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-06-18T10:06:57: PM2 log: App [strapi-gatsby-stable:0] starting in -fork mode-
PM2        | 2020-06-18T10:06:57: PM2 log: App [strapi-gatsby-stable:0] online
PM2        | 2020-06-18T10:06:57: PM2 log: App [strapi-gatsby-stable:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-06-18T10:06:57: PM2 log: App [strapi-gatsby-stable:0] starting in -fork mode-
PM2        | 2020-06-18T10:06:57: PM2 log: App [strapi-gatsby-stable:0] online
PM2        | 2020-06-18T10:06:57: PM2 log: App [strapi-gatsby-stable:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-06-18T10:06:57: PM2 log: App [strapi-gatsby-stable:0] starting in -fork mode-
PM2        | 2020-06-18T10:06:57: PM2 log: App [strapi-gatsby-stable:0] online
PM2        | 2020-06-18T10:06:57: PM2 log: App [strapi-gatsby-stable:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-06-18T10:06:57: PM2 log: App [strapi-gatsby-stable:0] starting in -fork mode-
PM2        | 2020-06-18T10:06:57: PM2 log: App [strapi-gatsby-stable:0] online
PM2        | 2020-06-18T10:06:57: PM2 log: App [strapi-gatsby-stable:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-06-18T10:06:57: PM2 log: App [strapi-gatsby-stable:0] starting in -fork mode-
PM2        | 2020-06-18T10:06:57: PM2 log: App [strapi-gatsby-stable:0] online
PM2        | 2020-06-18T10:06:58: PM2 log: App [strapi-gatsby-stable:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-06-18T10:06:58: PM2 log: App [strapi-gatsby-stable:0] starting in -fork mode-
PM2        | 2020-06-18T10:06:58: PM2 log: App [strapi-gatsby-stable:0] online
PM2        | 2020-06-18T10:06:58: PM2 log: App [strapi-gatsby-stable:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-06-18T10:06:58: PM2 log: Script /home/lfg/new_strapi/strapi-gatsby-stable had too many unstable restarts (16). Stopped. "errored"
```

Thank you !

**Comment by juliensl** [comment]
My bad, it was easy, I just have to launch pm2 in the project folder...
I was launching it like this : `pm2 my_folder1/my_folder2/project/`

Thank you and have a good day !
