### ISSUE TITLE
PM2 global error caught: handle.setSimultaneousAccepts is not a function

### ISSUE THREAD

**Issue by ElijahKaftanov** [Unitech/pm2#4807]
Error caused by [https://github.com/mikaelbr/node-notifier](https://github.com/mikaelbr/node-notifier) using [Windows SnoreToast](https://github.com/KDE/snoretoast). At the same time, nodemon is doing fine
```
PM2      | ===============================================================================
PM2      | --- PM2 global error caught ---------------------------------------------------
PM2      | Time                 : Mon Aug 10 2020 18:46:59 GMT+0300 (Eastern European Summer Time)
PM2      | handle.setSimultaneousAccepts is not a function
PM2      |     at ChildProcess.target._send (internal/child_process.js:791:16)
PM2      |     at ChildProcess.target.send (internal/child_process.js:706:19)
PM2      |     at sendHelper (internal/cluster/utils.js:26:15)
PM2      |     at send (internal/cluster/master.js:348:10)
PM2      |     at internal/cluster/master.js:314:5
PM2      |     at SharedHandle.add (internal/cluster/shared_handle.js:30:3)
PM2      |     at queryServer (internal/cluster/master.js:308:10)
PM2      |     at Worker.onmessage (internal/cluster/master.js:248:5)
PM2      |     at ChildProcess.onInternalMessage (internal/cluster/utils.js:47:8)
PM2      |     at ChildProcess.emit (events.js:327:22)
PM2      | ===============================================================================
PM2      | [PM2] Resurrecting PM2
PM2      | Stopping app:serral-dev id:0
PM2      | App name:serral-dev id:0 disconnected
PM2      | App [serral-dev:0] exited with code [1] via signal [SIGINT]
PM2      | pid=17272 msg=process killed
```

```
--- PM2 report ----------------------------------------------------------------
Date                 : Mon Aug 10 2020 18:47:26 GMT+0300 (Eastern European Summer Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.4.0
node version         : 14.2.0
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\elijah\AppData\Local\Yarn\Data\global\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.4.0
node version         : 14.2.0
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\elijah\AppData\Local\Yarn\Data\global\node_modules\pm2\bin\pm2,report
argv0                : node
user                 : elijah
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
cpus nb              : 8
freemem              : 763191296
totalmem             : 17025642496
home                 : C:\Users\elijah
===============================================================================
--- PM2 list -----------------------------------------------
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 1  │ serral             │ cluster  │ 0    │ stopped   │ 0%       │ 0b       │
│ 0  │ serral-dev         │ cluster  │ 0    │ online    │ 4.5%     │ 140.0mb  │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
C:\Users\elijah\.pm2\pm2.log last 20 lines:
PM2        | 2020-08-10T18:47:00: PM2 log: pid=17272 msg=process killed
PM2        | 2020-08-10T18:47:00: PM2 log: PM2 successfully stopped
PM2        | 2020-08-10T18:47:01: PM2 log: ===============================================================================
PM2        | 2020-08-10T18:47:01: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2020-08-10T18:47:01: PM2 log: Time                 : Mon Aug 10 2020 18:47:01 GMT+0300 (Eastern European Summer Time)
PM2        | 2020-08-10T18:47:01: PM2 log: PM2 version          : 4.4.0
PM2        | 2020-08-10T18:47:01: PM2 log: Node.js version      : 14.2.0
PM2        | 2020-08-10T18:47:01: PM2 log: Current arch         : x64
PM2        | 2020-08-10T18:47:01: PM2 log: PM2 home             : C:\Users\elijah\.pm2
PM2        | 2020-08-10T18:47:01: PM2 log: PM2 PID file         : C:\Users\elijah\.pm2\pm2.pid
PM2        | 2020-08-10T18:47:01: PM2 log: RPC socket file      : \\.\pipe\rpc.sock
PM2        | 2020-08-10T18:47:01: PM2 log: BUS socket file      : \\.\pipe\pub.sock
PM2        | 2020-08-10T18:47:01: PM2 log: Application log path : C:\Users\elijah\.pm2\logs
PM2        | 2020-08-10T18:47:01: PM2 log: Worker Interval      : 30000
PM2        | 2020-08-10T18:47:01: PM2 log: Process dump file    : C:\Users\elijah\.pm2\dump.pm2
PM2        | 2020-08-10T18:47:01: PM2 log: Concurrent actions   : 2
PM2        | 2020-08-10T18:47:01: PM2 log: SIGTERM timeout      : 1600
PM2        | 2020-08-10T18:47:01: PM2 log: ===============================================================================
PM2        | 2020-08-10T18:47:01: PM2 log: App [serral-dev:0] starting in -cluster mode-
PM2        | 2020-08-10T18:47:01: PM2 log: App [serral-dev:0] online

```

**Comment by ElijahKaftanov** [comment]
Resolved by switching to fork exec_mode
