### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by tousif1504** [Unitech/pm2#4815]
```
--- PM2 report ----------------------------------------------------------------
Date                 : Mon Aug 17 2020 06:42:45 GMT+0000 (Coordinated Universal Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.4.0
node version         : 10.22.0
node path            : /usr/local/bin/pm2
argv                 : /usr/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : ansible
uid                  : 1001
gid                  : 1001
uptime               : 1min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.4.0
node version         : 10.22.0
node path            : /usr/local/bin/pm2
argv                 : /usr/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : ansible
uid                  : 1001
gid                  : 1001
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
cpus nb              : 1
freemem              : 455618560
totalmem             : 1026158592
home                 : /home/ansible
===============================================================================
--- PM2 list -----------------------------------------------
┌─────┬───────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name          │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼───────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ mai_web_v2    │ default     │ 0.1.0   │ fork    │ N/A      │ 0      │ 2    │ stopped   │ 0%       │ 0b       │ ansible  │ disabled │
└─────┴───────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/home/ansible/.pm2/pm2.log last 20 lines:
PM2        |     at WriteStream.EventEmitter.emit (domain.js:448:20)
PM2        |     at lazyFs.open (internal/fs/streams.js:277:12)
PM2        |     at FSReqWrap.args [as oncomplete] (fs.js:140:20)
PM2        | 2020-08-17T06:41:21: PM2 log: PM2 successfully stopped
PM2        | 2020-08-17T06:41:21: PM2 log: ===============================================================================
PM2        | 2020-08-17T06:41:21: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2020-08-17T06:41:21: PM2 log: Time                 : Mon Aug 17 2020 06:41:21 GMT+0000 (Coordinated Universal Time)
PM2        | 2020-08-17T06:41:21: PM2 log: PM2 version          : 4.4.0
PM2        | 2020-08-17T06:41:21: PM2 log: Node.js version      : 10.22.0
PM2        | 2020-08-17T06:41:21: PM2 log: Current arch         : x64
PM2        | 2020-08-17T06:41:21: PM2 log: PM2 home             : /home/ansible/.pm2
PM2        | 2020-08-17T06:41:21: PM2 log: PM2 PID file         : /home/ansible/.pm2/pm2.pid
PM2        | 2020-08-17T06:41:21: PM2 log: RPC socket file      : /home/ansible/.pm2/rpc.sock
PM2        | 2020-08-17T06:41:21: PM2 log: BUS socket file      : /home/ansible/.pm2/pub.sock
PM2        | 2020-08-17T06:41:21: PM2 log: Application log path : /home/ansible/.pm2/logs
PM2        | 2020-08-17T06:41:21: PM2 log: Worker Interval      : 30000
PM2        | 2020-08-17T06:41:21: PM2 log: Process dump file    : /home/ansible/.pm2/dump.pm2
PM2        | 2020-08-17T06:41:21: PM2 log: Concurrent actions   : 2
PM2        | 2020-08-17T06:41:21: PM2 log: SIGTERM timeout      : 1600
PM2        | 2020-08-17T06:41:21: PM2 log: ===============================================================================

```

**Comment by tousif1504** [comment]
unable to start pm2
