### ISSUE TITLE
[pm2-runtime]: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by butonly** [Unitech/pm2#4829]
## What's going wrong?

https://github.com/Unitech/pm2/blob/14871cd04ff721f0d23eff4e80def16aa2cf3e72/lib/Utility.js#L183

Here will cause recursive call and throw ` RangeError: Maximum call stack size exceeded` exception when `stds[io]` stream trigger `error` event

```
RangeError: Maximum call stack size exceeded
    at String (<anonymous>)
    at formatWithOptions (util.js:99:23)
    at format (util.js:72:10)
    at getMessage (internal/errors.js:238:22)
    at new NodeError (internal/errors.js:159:13)
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at WriteStream.Writable.write (_stream_writable.js:299:11)
    at WriteStream.write (/usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:208:48)
    at write (console.js:164:12)
    at Console.warn (console.js:211:3)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Utility.js:183:23)
    at WriteStream.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
    at doWrite (_stream_writable.js:411:11)
    at writeOrBuffer (_stream_writable.js:399:5)
    at WriteStream.Writable.write (_stream_writable.js:299:11)
    at WriteStream.write (/usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:208:48)
    at write (console.js:164:12)
    at Console.warn (console.js:211:3)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Utility.js:183:23)
    at WriteStream.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
    at doWrite (_stream_writable.js:411:11)
```

## How could we reproduce this issue?

I can't reproduce

process config example:

```yml
apps:
  - name: app
    script: app.js
    exec_mode: cluster
    instances: '8'
    combine_logs: true
```

## Supporting information

```
$ pm2 report
```

```
--- PM2 report ----------------------------------------------------------------
Date                 : Thu Aug 27 2020 20:32:47 GMT+0800 (China Standard Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.4.0
node version         : 10.22.0
node path            : not found
argv                 : /usr/local/nvm/versions/node/v10.22.0/bin/node,/usr/local/nvm/versions/node/v10.22.0/bin/pm2-runtime,pm2.yml
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
uptime               : 1117min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.4.0
node version         : 10.22.0
node path            : /usr/local/nvm/versions/node/v10.22.0/bin/pm2
argv                 : /usr/local/nvm/versions/node/v10.22.0/bin/node,/usr/local/nvm/versions/node/v10.22.0/bin/pm2,report
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : AMD EPYC 7K62 48-Core Processor
cpus nb              : 90
freemem              : 146304532480
totalmem             : 201958469632
home                 : /root
===============================================================================
```

**Comment by bifot** [comment]
same on 5.1.1
