### ISSUE TITLE
Nothing's working with an error

### ISSUE THREAD

**Issue by itwithlyam** [Unitech/pm2#4851]
## What's going wrong?
Nothing's working with pm2

## How could we reproduce this issue?
Basically do something with PM2

## Supporting information
Error:
connect EPERM //./pipe/rpc.sock
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\44754\.pm2
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: connect EPERM //./pipe/rpc.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
Emitted 'error' event on ReqSocket instance at:
    at Socket.<anonymous> (C:\Users\44754\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon\lib\sockets\sock.js:201:49)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'EPERM',
  code: 'EPERM',
  syscall: 'connect',
  address: '//./pipe/rpc.sock'
}

```
$ pm2 report
```
^^^^ pm2 report just gives the same error

**Comment by ZeroJsus** [comment]
same error

**Comment by LittleTurtleJ** [comment]
Same error except 'errno' is 'errno: -4048'
