### ISSUE TITLE
EACCES, permission denied

### ISSUE THREAD

**Issue by binarykitchen** [Unitech/pm2#487]
Each time I try to start an app, I get this. No idea what I should adjust in the user permissions.

I am running pm2 with the right user `nodejs` who owns the home directory.

```
fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES, permission denied '/home/nodejs/.pm2/pids/www.signora.co.nz.pid10.pid'
  at Object.fs.openSync (fs.js:427:18)
  at Object.fs.writeFileSync (fs.js:966:15)
  at ProcessContainer (/opt/node-0.10.28/lib/node_modules/pm2/lib/ProcessContainer.js:30:6)
  at Object.<anonymous> (/opt/node-0.10.28/lib/node_modules/pm2/lib/ProcessContainer.js:44:3)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
```

**Comment by davalapar** [comment]
Using WinSCP I SFTP logged-in as root, right click the file and changed it s Group & User to my user, then set Permmissions to 777.

**Comment by DevAtCN** [comment]
For me `pm2 kill` then `pm2 start SERVER.JS` worked for me.

**Comment by mylastore** [comment]
I  have the similar problem still pm2 version 4.5.6 on production but I am running as ecosystem.json and this is the code on that file 

```bash
  {
    "apps": [
      {
        "name": "appname",
        "script": "PORT=3002 node build",
        "instances": 1,
        "exec_mode": "fork"
      }
    ]
  }
```

rror: EACCES: permission denied, mkdir '/root/.pm2/logs'
    at Object.mkdirSync (fs.js:1009:3)
    at mkdirpNativeSync (/usr/lib/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/usr/lib/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/usr/lib/node_modules/pm2/lib/Client.js:133:25)
    at new module.exports (/usr/lib/node_modules/pm2/lib/Client.js:38:8)
    at new API (/usr/lib/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
Error: EACCES: permission denied, mkdir '/root/.pm2/pids'

**Comment by rifton007** [comment]
Same problem, someone has solution ?

**Comment by mylastore** [comment]
I am STILL HAVING THIS ISSUE on a new ubuntu Debian 11 installation

Error: EACCES: permission denied, mkdir '/root/.pm2/logs'
Error: EACCES: permission denied, mkdir '/root/.pm2/pids'
Error: EACCES: permission denied, open '/root/.pm2/module_conf.json
Error: EACCES: permission denied, mkdir '/root/.pm2/modules'

**Comment by starlocke** [comment]
I'm doing this within a docker container. While the primary init is running as _root_, the child process is running as the user _node_.

```
/usr/src/app # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 {docker-entrypoi} /bin/sh /usr/src/app/docker-entrypoint.dev.sh
    7 root      0:00 npm run start:dev
   18 node      0:00 node /usr/src/app/node_modules/.bin/cross-env NODE_PATH=. nodemon cluster.js
   25 node      0:00 node /usr/src/app/node_modules/.bin/nodemon cluster.js
   56 root      0:00 ash
   68 root      0:00 ps aux
```

To fix this, I configured the environment variable `PM2_HOME` to something appropriate for my application, based on [this comment](https://github.com/Unitech/pm2/issues/1321#issuecomment-136488300).

**Comment by mathias22osterhagen22** [comment]
Does someone know how this error impacts PM2?

**Comment by vetan2** [comment]
> I am STILL HAVING THIS ISSUE on a new ubuntu Debian 11 installation
> 
> Error: EACCES: permission denied, mkdir '/root/.pm2/logs' Error: EACCES: permission denied, mkdir '/root/.pm2/pids' Error: EACCES: permission denied, open '/root/.pm2/module_conf.json Error: EACCES: permission denied, mkdir '/root/.pm2/modules'

If you use `sudo` prefix, try taking it out

**Comment by xiaofenging** [comment]
On windows10  ,pm2 read shared file error ,at first, According to the big guy's description,i resolve the permission error ,meanwhile On certain machines ,new error was  found ,i try to fs.stat ,get the error desc is like 
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'stat',
who can tell me how to resolve it or the problem is about what,thanks
