### ISSUE TITLE
PM2 Cannot run node 4.8.4 as interpreter?

### ISSUE THREAD

**Issue by shinebayar-g** [Unitech/pm2#4877]
## What's going wrong?

I'm trying to run old meteor js application which runs on nodejs 4.8.4

Here if I try to run pm2 on nodejs 10.x (same with 12.x)

```
# pm2-runtime ecosystem.json 
2020-10-10T21:53:47: PM2 log: Launching in no daemon mode
2020-10-10T21:53:47: PM2 log: App [my-app:0] starting in -fork mode-
2020-10-10T21:53:47: PM2 log: App [my-app:0] online
/home/node/.nvm/versions/node/v10.22.1/lib/node_modules/pm2/lib/ProcessContainerFork.js:30
    import(url.pathToFileURL(process.env.pm_exec_path));
    ^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
2020-10-10T21:53:47: PM2 log: App [my-app:0] exited with code [1] via signal [SIGINT]
```

Here if I try to run pm2 on nodejs 8.x

```
# pm2-runtime ecosystem.json 
2020-10-10T22:02:41: PM2 log: Launching in no daemon mode
2020-10-10T22:02:42: PM2 log: App [my-app:0] starting in -fork mode-
2020-10-10T22:02:42: PM2 log: App [my-app:0] online
/home/node/.nvm/versions/node/v8.17.0/lib/node_modules/pm2/node_modules/@pm2/io/node_modules/debug/src/node.js:132
	let val = process.env[key];
	^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/node/.nvm/versions/node/v8.17.0/lib/node_modules/pm2/node_modules/@pm2/io/node_modules/debug/src/index.js:9:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
2020-10-10T22:02:42: PM2 log: App [my-app:0] exited with code [1] via signal [SIGINT]
```

## How could we reproduce this issue?

Install pm2 latest version 4.5.0 on node js 10.22, try to run nodejs 4.8.4 as interpreter.

## Supporting information

```
--- PM2 report ----------------------------------------------------------------
Date                 : Sat Oct 10 2020 21:58:06 GMT+0000 (Coordinated Universal Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.5.0
node version         : 10.22.1
node path            : /home/node/.nvm/versions/node/v10.22.1/bin/pm2
argv                 : /home/node/.nvm/versions/node/v10.22.1/bin/node,/home/node/.nvm/versions/node/v10.22.1/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : node
uid                  : 1000
gid                  : 1000
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.5.0
node version         : 10.22.1
node path            : /home/node/.nvm/versions/node/v10.22.1/bin/pm2
argv                 : /home/node/.nvm/versions/node/v10.22.1/bin/node,/home/node/.nvm/versions/node/v10.22.1/bin/pm2,report
argv0                : node
user                 : node
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : AMD A8-3500M APU with Radeon(tm) HD Graphics
cpus nb              : 4
freemem              : 956104704
totalmem             : 7814324224
home                 : /home/node
===============================================================================
--- PM2 list -----------------------------------------------
┌─────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
└─────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/home/node/.pm2/pm2.log last 20 lines:
PM2        | 2020-10-10T21:54:44: PM2 log: Concurrent actions   : 2
PM2        | 2020-10-10T21:54:44: PM2 log: SIGTERM timeout      : 1600
PM2        | 2020-10-10T21:54:44: PM2 log: ===============================================================================
PM2        | 2020-10-10T21:54:50: PM2 log: PM2 successfully stopped
PM2        | 2020-10-10T21:58:06: PM2 log: ===============================================================================
PM2        | 2020-10-10T21:58:06: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2020-10-10T21:58:06: PM2 log: Time                 : Sat Oct 10 2020 21:58:06 GMT+0000 (Coordinated Universal Time)
PM2        | 2020-10-10T21:58:06: PM2 log: PM2 version          : 4.5.0
PM2        | 2020-10-10T21:58:06: PM2 log: Node.js version      : 10.22.1
PM2        | 2020-10-10T21:58:06: PM2 log: Current arch         : x64
PM2        | 2020-10-10T21:58:06: PM2 log: PM2 home             : /home/node/.pm2
PM2        | 2020-10-10T21:58:06: PM2 log: PM2 PID file         : /home/node/.pm2/pm2.pid
PM2        | 2020-10-10T21:58:06: PM2 log: RPC socket file      : /home/node/.pm2/rpc.sock
PM2        | 2020-10-10T21:58:06: PM2 log: BUS socket file      : /home/node/.pm2/pub.sock
PM2        | 2020-10-10T21:58:06: PM2 log: Application log path : /home/node/.pm2/logs
PM2        | 2020-10-10T21:58:06: PM2 log: Worker Interval      : 30000
PM2        | 2020-10-10T21:58:06: PM2 log: Process dump file    : /home/node/.pm2/dump.pm2
PM2        | 2020-10-10T21:58:06: PM2 log: Concurrent actions   : 2
PM2        | 2020-10-10T21:58:06: PM2 log: SIGTERM timeout      : 1600
PM2        | 2020-10-10T21:58:06: PM2 log: ===============================================================================
```

I've actually tried to run pm2 with multiple nodejs versions such as 8.x LTS, 10.x LTS, 12.x LTS. I have also tried `rm -rf ~/.pm2` before every attempt.

**Comment by soyuka** [comment]
import is now an experimental feature in node I suggest to update the code see https://github.com/Unitech/pm2/issues/1034#issuecomment-729863438
