### ISSUE TITLE
Port Already in Use in Cluster Mode

### ISSUE THREAD

**Issue by rrandall91** [Unitech/pm2#4975]
## What's going wrong?

One of our Node.js microservices are being intermittently killed during our application's peak use times. We currently have 10+ services being managed by PM2 and all of them are returning an error that the assigned ports are already in use, despite being available prior to starting the PM2 daemon.  Although all of the services are throwing the error, only one of the services is being killed. I have even recreated our production environment on a fresh instance and am still encountering the problem.

It appears that the service runs fine when there is lower amounts of traffic to the application.

## How could we reproduce this issue?

We have multiple services (approx. 15) running in cluster mode on a 16GB AWS instance with 2 cores.

### Sample config

```javascript
module.exports = {
  apps: [
    {
      name: "accounting",
      cwd: "./services/AccountingService",
      exec_mode: "cluster",
      instances: "max",
      script: "npm",
      args: "start",
      env_production: {
        ...defaultEnv,
        DB_NAME: "accounting",
        PORT: 9000
      },
    },

    {
      name: "agreement",
      cwd: "./services/AgreementService",
      exec_mode: "cluster",
      instances: "max",
      script: "npm",
      args: "start",    
      env_production: {
        ...defaultEnv,
        PORT: 8011
      },
    },
```

## Supporting information

```
--- PM2 report ----------------------------------------------------------------
Date                 : Thu Jan 28 2021 01:50:50 GMT+0000 (Coordinated Universal Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.5.1
node version         : 14.15.4
node path            : /home/ubuntu/.nvm/versions/node/v14.15.4/bin/pm2
argv                 : /home/ubuntu/.nvm/versions/node/v14.15.4/bin/node,/home/ubuntu/.nvm/versions/node/v14.15.4/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : ubuntu
uid                  : 1000
gid                  : 1000
uptime               : 1min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.5.1
node version         : 14.15.4
node path            : /home/ubuntu/.nvm/versions/node/v14.15.4/bin/pm2
argv                 : /home/ubuntu/.nvm/versions/node/v14.15.4/bin/node,/home/ubuntu/.nvm/versions/node/v14.15.4/bin/pm2,report
argv0                : node
user                 : ubuntu
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
cpus nb              : 2
freemem              : 14411083776
totalmem             : 16482066432
home                 : /home/ubuntu
===============================================================================
--- PM2 list -----------------------------------------------
┌─────┬───────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name              │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼───────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ accounting        │ default     │ 0.37.2  │ cluster │ 1475     │ 37s    │ 0    │ online    │ 0.6%     │ 46.4mb   │ ubuntu   │ disabled │
│ 2   │ accounting        │ default     │ 0.37.2  │ cluster │ 1489     │ 37s    │ 0    │ online    │ 0%       │ 55.4mb   │ ubuntu   │ disabled │
│ 1   │ agreement         │ default     │ 0.37.2  │ cluster │ 1481     │ 37s    │ 0    │ online    │ 0%       │ 55.2mb   │ ubuntu   │ disabled │
│ 3   │ agreement         │ default     │ 0.37.2  │ cluster │ 1491     │ 37s    │ 0    │ online    │ 0.3%     │ 54.9mb   │ ubuntu   │ disabled │
│ 4   │ asset             │ default     │ 0.37.2  │ cluster │ 1503     │ 37s    │ 0    │ online    │ 0%       │ 54.7mb   │ ubuntu   │ disabled │
│ 6   │ asset             │ default     │ 0.37.2  │ cluster │ 1517     │ 37s    │ 0    │ online    │ 0%       │ 56.0mb   │ ubuntu   │ disabled │
│ 5   │ authentication    │ default     │ 0.37.2  │ cluster │ 1509     │ 37s    │ 0    │ online    │ 0.3%     │ 54.8mb   │ ubuntu   │ disabled │
│ 7   │ authentication    │ default     │ 0.37.2  │ cluster │ 1523     │ 37s    │ 0    │ online    │ 0%       │ 55.7mb   │ ubuntu   │ disabled │
│ 8   │ calendar          │ default     │ 0.37.2  │ cluster │ 1543     │ 36s    │ 0    │ online    │ 0%       │ 54.6mb   │ ubuntu   │ disabled │
│ 10  │ calendar          │ default     │ 0.37.2  │ cluster │ 1561     │ 36s    │ 0    │ online    │ 0%       │ 54.7mb   │ ubuntu   │ disabled │
│ 13  │ client            │ default     │ 0.37.2  │ cluster │ 1585     │ 36s    │ 0    │ online    │ 0%       │ 54.3mb   │ ubuntu   │ disabled │
│ 15  │ client            │ default     │ 0.37.2  │ cluster │ 1607     │ 36s    │ 0    │ online    │ 0%       │ 55.0mb   │ ubuntu   │ disabled │
│ 9   │ clientActivity    │ default     │ 0.37.2  │ cluster │ 1549     │ 36s    │ 0    │ online    │ 0.3%     │ 55.9mb   │ ubuntu   │ disabled │
│ 11  │ clientActivity    │ default     │ 0.37.2  │ cluster │ 1568     │ 36s    │ 0    │ online    │ 0%       │ 56.4mb   │ ubuntu   │ disabled │
│ 12  │ clientSales       │ default     │ 0.37.2  │ cluster │ 1583     │ 36s    │ 0    │ online    │ 0%       │ 54.9mb   │ ubuntu   │ disabled │
│ 14  │ clientSales       │ default     │ 0.37.2  │ cluster │ 1605     │ 36s    │ 0    │ online    │ 0%       │ 54.9mb   │ ubuntu   │ disabled │
│ 16  │ credential        │ default     │ 0.37.2  │ cluster │ 1627     │ 35s    │ 0    │ online    │ 0.3%     │ 54.6mb   │ ubuntu   │ disabled │
│ 18  │ credential        │ default     │ 0.37.2  │ cluster │ 1649     │ 35s    │ 0    │ online    │ 0%       │ 56.0mb   │ ubuntu   │ disabled │
│ 17  │ dataMapping       │ default     │ 0.37.2  │ cluster │ 1628     │ 35s    │ 0    │ online    │ 0%       │ 54.8mb   │ ubuntu   │ disabled │
│ 19  │ dataMapping       │ default     │ 0.37.2  │ cluster │ 1651     │ 35s    │ 0    │ online    │ 0%       │ 55.3mb   │ ubuntu   │ disabled │
│ 20  │ etl               │ default     │ 0.37.2  │ cluster │ 1671     │ 34s    │ 0    │ online    │ 0%       │ 54.7mb   │ ubuntu   │ disabled │
│ 21  │ gateway           │ default     │ 0.37.2  │ cluster │ 1677     │ 34s    │ 0    │ online    │ 0%       │ 56.0mb   │ ubuntu   │ disabled │
│ 23  │ gateway           │ default     │ 0.37.2  │ cluster │ 1699     │ 34s    │ 0    │ online    │ 0%       │ 55.6mb   │ ubuntu   │ disabled │
│ 22  │ notification      │ default     │ 0.37.2  │ cluster │ 1693     │ 34s    │ 0    │ online    │ 0%       │ 55.0mb   │ ubuntu   │ disabled │
│ 24  │ notification      │ default     │ 0.37.2  │ cluster │ 1742     │ 33s    │ 0    │ online    │ 0.6%     │ 54.9mb   │ ubuntu   │ disabled │
│ 25  │ reporting         │ default     │ 0.37.2  │ cluster │ 1754     │ 33s    │ 0    │ online    │ 0.3%     │ 54.9mb   │ ubuntu   │ disabled │
│ 27  │ reporting         │ default     │ 0.37.2  │ cluster │ 1787     │ 33s    │ 0    │ online    │ 0.3%     │ 55.0mb   │ ubuntu   │ disabled │
│ 26  │ workflow          │ default     │ 0.37.2  │ cluster │ 1768     │ 33s    │ 0    │ online    │ 0%       │ 54.8mb   │ ubuntu   │ disabled │
│ 28  │ workflow          │ default     │ 0.37.2  │ cluster │ 1810     │ 32s    │ 0    │ online    │ 0.3%     │ 56.6mb   │ ubuntu   │ disabled │
└─────┴───────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/home/ubuntu/.pm2/pm2.log last 20 lines:
PM2        |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
PM2        |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
PM2        |     at Module.load (internal/modules/cjs/loader.js:928:32)
PM2        |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
PM2        |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
PM2        |     at internal/main/run_main_module.js:17:47
PM2        | Configuring Winston Error Logger...
PM2        | Configuring Winston Error Logger...
PM2        | Listening on port: 8009
PM2        | Error: listen EADDRINUSE: address already in use :::8009
PM2        |     at Server.setupListenHandle [as _listen2] (net.js:1318:16)
PM2        |     at listenInCluster (net.js:1366:12)
PM2        |     at Server.listen (net.js:1452:7)
PM2        |     at Object.<anonymous> (/app/services/ReportingService/index.js:69:8)
PM2        |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
PM2        |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
PM2        |     at Module.load (internal/modules/cjs/loader.js:928:32)
PM2        |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
PM2        |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
PM2        |     at internal/main/run_main_module.js:17:47

```

**Comment by rrandall91** [comment]
After looking more into this, it appears that the error is not being triggered when the services are forked rather than use cluster mode.

**Comment by Unitech** [comment]
You can't cluster application via npm start. To make cluster work, in the script attribute of your ecosystem.config.js, directly put the path of your javascript app.

**Comment by rrandall91** [comment]
@Unitech is there a reason that it would have worked before with no problem? The configuration hasn't changed in months yet we've only started receiving these errors this week.

**Comment by neighlyd-alo** [comment]
@Unitech  - where do the documents explain that npm start can't run in cluster mode? I am getting lots of conflicting information about this online.
