### ISSUE TITLE
[PM2][ERROR] Process failed to launch spawn ENOTDIR

### ISSUE THREAD

**Issue by DurandSacha** [Unitech/pm2#4996]
Hello, I trying to deploy a express application with node. and pm2 blocks the launch of the instance with an error message when `pm2 start`

I have a running instance, I would like to launch a second one ! 

Here is the log : 

$ pm2 report
```
--- PM2 report ----------------------------------------------------------------
Date                 : Mon Feb 22 2021 15:37:57 GMT+0000 (Coordinated Universal Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.5.4
node version         : 10.23.3
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : git
uid                  : 1002
gid                  : 1002
uptime               : 4360min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.5.4
node version         : 10.23.3
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : git
uid                  : 1002
gid                  : 1002
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz
cpus nb              : 2
freemem              : 5178929152
totalmem             : 7137898496
home                 : /home/git
===============================================================================
--- PM2 list -----------------------------------------------
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 1  │ application_name            │ fork     │ 32   │ online    │ 0.3%     │ 49.3mb   │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/home/git/.pm2/pm2.log last 20 lines:
PM2        |     at ChildProcess.spawn (internal/child_process.js:366:11)
PM2        |     at spawn (child_process.js:551:9)
PM2        |     at /usr/lib/node_modules/pm2/lib/God/ForkMode.js:118:20
PM2        |     at wrapper (/usr/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16)
PM2        |     at next (/usr/lib/node_modules/pm2/node_modules/async/waterfall.js:96:20)
PM2        |     at /usr/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
PM2        |     at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:186:13)
PM2        |     at WriteStream.emit (events.js:198:13)
PM2        |     at WriteStream.EventEmitter.emit (domain.js:466:23)
PM2        |     at lazyFs.open (internal/fs/streams.js:282:10) errno: 'ENOTDIR', code: 'ENOTDIR', syscall: 'spawn' }
PM2        |     at Object.God.logAndGenerateError (/usr/lib/node_modules/pm2/lib/God/Methods.js:34:15)
PM2        |     at /usr/lib/node_modules/pm2/lib/God/ForkMode.js:120:13
PM2        |     at wrapper (/usr/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16)
PM2        |     at next (/usr/lib/node_modules/pm2/node_modules/async/waterfall.js:96:20)
PM2        |     at /usr/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
PM2        |     at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:186:13)
PM2        |     at WriteStream.emit (events.js:198:13)
PM2        |     at WriteStream.EventEmitter.emit (domain.js:466:23)
PM2        |     at lazyFs.open (internal/fs/streams.js:282:10)
PM2        |     at FSReqWrap.args [as oncomplete] (fs.js:140:20)

```

thanks for your help

**Comment by DurandSacha** [comment]
I solved my issue, ecosystem.config.js file was wrong : 

Here is the correct file 

`module.exports = {
  apps : [{
    name: "nameApp",
    script: "index.js",
    args: "start",
    autorestart: true,
    env: {
      //NODE_ENV: 'development'
    },
    env_production: {
      NODE_ENV: 'production',
      //API_URL: 'YOUR ENV URL',
      PORT:3000
    }
  }]
};
`
