### ISSUE TITLE
Error whhen installing pm2-logrotate : UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by linaia** [Unitech/pm2#5022]
## What's going wrong?
When trying to install pm2-logrotate : 
```
pm2 install pm2-logrotate                                    [14:55:37]
[PM2][Module] Installing NPM pm2-logrotate module
[PM2][Module] Calling [NPM] to install pm2-logrotate ...
(node:22202) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:411:3)
    at spawn (child_process.js:545:16)
    at /home/pm2/.config/yarn/global/node_modules/pm2/lib/API/Modules/NPM.js:208:74
(node:22202) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22202) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
## How could we reproduce this issue?

I don't know, first time I have this error. Is nodeJS version correct (10.21.0) ?
On other system I have pm2-logrotate installed but with 

```
local pm2            : 4.4.0
node version         : 12.16.3
```

Here I has this same message with 4.4.0, I have updated pm2 at 4.5.5, but same
## Supporting information
```
--- PM2 report ----------------------------------------------------------------
Date                 : Wed Mar 17 2021 16:11:20 GMT+0100 (Central European Standard Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.5.5
node version         : 10.21.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/home/pm2/.config/yarn/global/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : aaaa
uid                  : 1001
gid                  : 1001
uptime               : 8min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.5.5
node version         : 10.21.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : aaaa
uid                  : 1001
gid                  : 1001
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz
cpus nb              : 8
freemem              : 21157580800
totalmem             : 33466507264
home                 : /home/aaaa
===============================================================================
--- PM2 list -----------------------------------------------
┌─────┬───────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name          │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼───────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ xxxx-api      │ default     │ 0.0.1   │ fork    │ 13701    │ 8m     │ 0    │ online    │ 0.3%     │ 106.6mb  │ aaaa   │ disabled │
└─────┴───────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/home/pm2/pm2.log last 20 lines:
PM2        | 2021-03-17T16:02:31: PM2 log: pid=11852 msg=process killed
PM2        | 2021-03-17T16:02:31: PM2 log: PM2 successfully stopped
PM2        | 2021-03-17T16:02:32: PM2 log: ===============================================================================
PM2        | 2021-03-17T16:02:32: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2021-03-17T16:02:32: PM2 log: Time                 : Wed Mar 17 2021 16:02:32 GMT+0100 (Central European Standard Time)
PM2        | 2021-03-17T16:02:32: PM2 log: PM2 version          : 4.5.5
PM2        | 2021-03-17T16:02:32: PM2 log: Node.js version      : 10.21.0
PM2        | 2021-03-17T16:02:32: PM2 log: Current arch         : x64
PM2        | 2021-03-17T16:02:32: PM2 log: PM2 home             : /home/pm2
PM2        | 2021-03-17T16:02:32: PM2 log: PM2 PID file         : /home/pm2/pm2.pid
PM2        | 2021-03-17T16:02:32: PM2 log: RPC socket file      : /home/pm2/rpc.sock
PM2        | 2021-03-17T16:02:32: PM2 log: BUS socket file      : /home/pm2/pub.sock
PM2        | 2021-03-17T16:02:32: PM2 log: Application log path : /home/pm2/logs
PM2        | 2021-03-17T16:02:32: PM2 log: Worker Interval      : 30000
PM2        | 2021-03-17T16:02:32: PM2 log: Process dump file    : /home/pm2/dump.pm2
PM2        | 2021-03-17T16:02:32: PM2 log: Concurrent actions   : 2
PM2        | 2021-03-17T16:02:32: PM2 log: SIGTERM timeout      : 1600
PM2        | 2021-03-17T16:02:32: PM2 log: ===============================================================================
PM2        | 2021-03-17T16:02:32: PM2 log: App [xxxx-api:0] starting in -fork mode-
PM2        | 2021-03-17T16:02:32: PM2 log: App [xxxx-api:0] online

```

**Comment by mraduldubey** [comment]
Same issue with pm2 version 5.1.0 and node version 12.14.1. Any updates on this ?

**Comment by mraduldubey** [comment]
This worked for me. 
 It needs to find the path of the directory where the node binary resides. 


`echo "Adding nodejs/node*/bin dir to PATH:"`

`NODE_BIN_PATH="$(dirname "${NODE_PATH}")"`

`echo $NODE_BIN_PATH`

`PATH=$NODE_BIN_PATH $PM2_PATH install pm2-logrotate`

**Comment by cherryshoe** [comment]
I got this error when npm wasn't installed on a Centos7 server:  "TypeError [ERR_INVALID_ARG_TYPE]: The \"file\" argument must be of type string. Received null", which wasn't the true problem.  The true problem was exposed here - "Calling [NPM] to install pm2-logrotate@2.7.0".  Verifying the npm version failed since npm wasn't found.

I noticed this problem with a NodeSource Node Installer method with v16.15.0.  The NodeSource installer didn't install npm as it should have (https://rpm.nodesource.com/setup_16.x).

Switching to the Node.js installer worked: Steps taken from https://github.com/nodejs/help/wiki/Installation#how-to-install-nodejs-via-binary-archive-on-linux

```
   $ mkdir -p /usr/local/lib/nodejs
   $ wget https://nodejs.org/download/release/v16.15.0/node-v16.15.0-linux-x64.tar.xz
   $ tar -xJvf node-v16.15.0-linux-x64.tar.xz -C /usr/local/lib/nodejs 
```
   Chose to use symbolic link to /usr/bin since this path is already in my PATH environment variable:
```
   $ ln -s /usr/local/lib/nodejs/node-v16.15.0-linux-x64/bin/node /usr/bin/node
   $ ln -s /usr/local/lib/nodejs/node-v16.15.0-linux-x64/bin/npm /usr/bin/npm
   $ ln -s /usr/local/lib/nodejs/node-v16.15.0-linux-x64/bin/npx /usr/bin/npx
```
Verified install with:
```
$ node -v
$ npm version
$ npx -v
```
