### ISSUE TITLE
including a space while using the `--name` option causes issues

### ISSUE THREAD

**Issue by edwardsmarkf** [Unitech/pm2#5032]
when i tried putting a space in the `--name` such as:

`   --name  'Homework Assignment'`

caused the following issue:

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at Object.<anonymous> (/home/comptonpeslonline.com/public_html/comptonPractice/homeworkAssignment/feathersServer/src/app.js:33:22)

removing the space fixed it.

node -v ; npm -v  ;  pm2 -v ;
v10.24.0
7.7.5
4.5.5

**Comment by smoliakov** [comment]
Same problem. Any ideas?
