### ISSUE TITLE
Error: write EPIPE error with yarn berry, pm2^4.5.6 and node^16 on Apple Silicon

### ISSUE THREAD

**Issue by tomchentw** [Unitech/pm2#5064]
## What's going wrong?

```
pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
2021-05-05T16:39:51: PM2 log: Launching in no daemon mode
2021-05-05T16:39:51: PM2 log: [PM2][WARN] Applications yarn-next-start not running, starting...
2021-05-05T16:39:51: PM2 log: App [yarn-next-start:0] starting in -cluster mode-
2021-05-05T16:39:51: PM2 log: App [yarn-next-start:0] online
2021-05-05T16:39:51: PM2 log: App [yarn-next-start:1] starting in -cluster mode-
/a-project-repo/.pnp.js:24833
  return Object.defineProperties(new Error(message), {
                                 ^

Error: git-node-fs tried to access js-git, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: js-git (via "js-git/mixins/fs-db")
Required by: git-node-fs@npm:1.0.0 (via /a-project-repo/.yarn/cache/git-node-fs-npm-1.0.0-e77903bcaf-0aa64fcaca.zip/node_modules/git-node-fs/mixins/)

Require stack:
- /a-project-repo/.yarn/cache/git-node-fs-npm-1.0.0-e77903bcaf-0aa64fcaca.zip/node_modules/git-node-fs/mixins/fs-db.js
- /a-project-repo/.yarn/cache/vizion-npm-2.2.1-4efea0d7b8-ffc78f5d14.zip/node_modules/vizion/lib/git/js-git-service.js
- /a-project-repo/.yarn/cache/vizion-npm-2.2.1-4efea0d7b8-ffc78f5d14.zip/node_modules/vizion/lib/git/git.js
- /a-project-repo/.yarn/cache/vizion-npm-2.2.1-4efea0d7b8-ffc78f5d14.zip/node_modules/vizion/lib/vizion.js
- /a-project-repo/.yarn/cache/vizion-npm-2.2.1-4efea0d7b8-ffc78f5d14.zip/node_modules/vizion/index.js
- /a-project-repo/.yarn/unplugged/pm2-npm-4.5.6-f784cf43d0/node_modules/pm2/lib/God.js
- /a-project-repo/.yarn/unplugged/pm2-npm-4.5.6-f784cf43d0/node_modules/pm2/lib/Daemon.js
- /a-project-repo/.yarn/unplugged/pm2-npm-4.5.6-f784cf43d0/node_modules/pm2/lib/Client.js
- /a-project-repo/.yarn/unplugged/pm2-npm-4.5.6-f784cf43d0/node_modules/pm2/lib/API.js
- /a-project-repo/.yarn/unplugged/pm2-npm-4.5.6-f784cf43d0/node_modules/pm2/lib/binaries/CLI.js
- /a-project-repo/.yarn/unplugged/pm2-npm-4.5.6-f784cf43d0/node_modules/pm2/bin/pm2
    at internalTools_makeError (/a-project-repo/.pnp.js:24833:34)
    at resolveToUnqualified (/a-project-repo/.pnp.js:25798:23)
    at resolveRequest (/a-project-repo/.pnp.js:25890:29)
    at Object.resolveRequest (/a-project-repo/.pnp.js:25968:26)
    at Function.external_module_.Module._resolveFilename (/a-project-repo/.pnp.js:25066:34)
    at Function.external_module_.Module._load (/a-project-repo/.pnp.js:24931:48)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/a-project-repo/.yarn/cache/git-node-fs-npm-1.0.0-e77903bcaf-0aa64fcaca.zip/node_modules/git-node-fs/mixins/fs-db.js:1:12)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
➜  platform git:(develop) ✗ node:events:342
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (node:internal/child_process:849:20)
    at process.target.send (node:internal/child_process:722:19)
    at IPCTransport.send (/a-project-repo/.yarn/cache/@pm2-io-npm-5.0.0-3c2a626e24-e05ba9099b.zip/node_modules/@pm2/io/build/main/transports/IPCTransport.js:83:21)
    at IPCTransport.setOptions (/a-project-repo/.yarn/cache/@pm2-io-npm-5.0.0-3c2a626e24-e05ba9099b.zip/node_modules/@pm2/io/build/main/transports/IPCTransport.js:73:21)
    at Function.configureModule (/a-project-repo/.yarn/cache/@pm2-io-npm-5.0.0-3c2a626e24-e05ba9099b.zip/node_modules/@pm2/io/build/main/configuration.js:13:62)
    at NotifyFeature.init (/a-project-repo/.yarn/cache/@pm2-io-npm-5.0.0-3c2a626e24-e05ba9099b.zip/node_modules/@pm2/io/build/main/features/notify.js:33:33)
    at FeatureManager.init (/a-project-repo/.yarn/cache/@pm2-io-npm-5.0.0-3c2a626e24-e05ba9099b.zip/node_modules/@pm2/io/build/main/featureManager.js:81:21)
    at PMX.init (/a-project-repo/.yarn/cache/@pm2-io-npm-5.0.0-3c2a626e24-e05ba9099b.zip/node_modules/@pm2/io/build/main/pmx.js:90:29)
    at Object.<anonymous> (/a-project-repo/.yarn/cache/@pm2-io-npm-5.0.0-3c2a626e24-e05ba9099b.zip/node_modules/@pm2/io/build/main/index.js:5:65)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (node:internal/cluster/worker:30:12)
    at process.emit (node:events:365:28)
    at node:internal/child_process:853:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
node:events:342
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (node:internal/child_process:849:20)
    at process.target.send (node:internal/child_process:722:19)
    at sendHelper (node:internal/cluster/utils:27:15)
    at send (node:internal/cluster/child:216:10)
    at EventEmitter.cluster._setupWorker (node:internal/cluster/child:51:3)
    at initializeClusterIPC (node:internal/bootstrap/pre_execution:352:13)
    at prepareMainThreadExecution (node:internal/bootstrap/pre_execution:66:3)
    at node:internal/main/run_main_module:7:1
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (node:internal/cluster/worker:30:12)
    at process.emit (node:events:365:28)
    at node:internal/child_process:853:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

## How could we reproduce this issue?

1. Install yarn berry, pm2^4.5.6 and node^16 
2. Install `pm2` locally in your project: `yarn add pm2`
3. Start pm2 in cluster mode

## Workaround

This issue came from the yarn berry strict dependency requirement. To workaround this, you will have to edit the `.yarnrc.yml` file and add:

```
packageExtensions:
  git-node-fs@1.0.0:
    dependencies:
      js-git: ^0.7.8
```

And run `yarn` after saving the edits. After that, yarn will get the correct dependency of `git-node-fs`.

## Supporting information

```
$ pm2 report
```

**Comment by tomchentw** [comment]
## Workaround

This issue came from the yarn berry strict dependency requirement. To workaround this, you will have to edit the .yarnrc.yml file and add:

```
packageExtensions:
  git-node-fs@1.0.0:
    dependencies:
      js-git: ^0.7.8
```

And run yarn after saving the edits. After that, yarn will get the correct dependency of git-node-fs.

**Comment by filipesarturi** [comment]
> ## Workaround
> This issue came from the yarn berry strict dependency requirement. To workaround this, you will have to edit the .yarnrc.yml file and add:
> 
> ```
> packageExtensions:
>   git-node-fs@1.0.0:
>     dependencies:
>       js-git: ^0.7.8
> ```
> 
> And run yarn after saving the edits. After that, yarn will get the correct dependency of git-node-fs.

worked with me
