### ISSUE TITLE
Getting error every few seconds in the logs (on FreeBSD)

### ISSUE THREAD

**Issue by IrosTheBeggar** [Unitech/pm2#5090]
## What's going wrong?

I installed pm2 and started an app. When I run `pm2 logs` I see the following error pop up every 20 seconds

```
0|pm2-sysm | Error while retrieving graphics informations
0|pm2-sysm | TypeError: Cannot read property 'controllers' of null
0|pm2-sysm |     at /usr/local/lib/node_modules/pm2/node_modules/pm2-sysmonit/src/SystemInfos.js:347:24
0|pm2-sysm |     at runMicrotasks (<anonymous>)
0|pm2-sysm |     at processTicksAndRejections (node:internal/process/task_queues:94:5)
0|pm2-sysm | Error while retrieving graphics informations
0|pm2-sysm | TypeError: Cannot read property 'controllers' of null
0|pm2-sysm |     at /usr/local/lib/node_modules/pm2/node_modules/pm2-sysmonit/src/SystemInfos.js:347:24
0|pm2-sysm |     at runMicrotasks (<anonymous>)
0|pm2-sysm |     at processTicksAndRejections (node:internal/process/task_queues:94:5)
0|pm2-sysm | Error while retrieving graphics informations
0|pm2-sysm | TypeError: Cannot read property 'controllers' of null
0|pm2-sysm |     at /usr/local/lib/node_modules/pm2/node_modules/pm2-sysmonit/src/SystemInfos.js:347:24
0|pm2-sysm |     at runMicrotasks (<anonymous>)
0|pm2-sysm |     at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

## How could we reproduce this issue?

Install pm2 on freeBSD 12.2 and look at the logs

Node Version:  v15.14.0

## Supporting information

```
--- PM2 report ----------------------------------------------------------------
Date                 : Tue Jun 08 2021 02:04:43 GMT+0000 (Coordinated Universal Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 5.0.0
node version         : 15.14.0
node path            : not found
argv                 : /usr/local/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
uptime               : 15min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 5.0.0
node version         : 15.14.0
node path            : not found
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : freebsd
type                 : FreeBSD
cpus                 : DO-Premium-AMD
cpus nb              : 1
freemem              : 167649280
totalmem             : 1034502144
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌─────┬─────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name            │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼─────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 1   │ mstream         │ default     │ 5.1.9   │ fork    │ 91752    │ 15m    │ 0    │ online    │ 25%      │ 59.1mb   │ root     │ disabled │
└─────┴─────────────────┴─────────────┴───��─────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
host metrics | cpu: 18.1% | mem free: 66.0% | vtnet0: ⇓ 0mb/s ⇑ 0mb/s | vtnet1: ⇓ 0mb/s ⇑ 0mb/s | disk: ⇓ 0mb/s ⇑ 0mb/s |
===============================================================================
--- Daemon logs --------------------------------------------
/root/.pm2/pm2.log last 20 lines:
PM2        | 2021-06-08T01:48:59: PM2 log: ===============================================================================
PM2        | 2021-06-08T01:48:59: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2021-06-08T01:48:59: PM2 log: Time                 : Tue Jun 08 2021 01:48:59 GMT+0000 (Coordinated Universal Time)
PM2        | 2021-06-08T01:48:59: PM2 log: PM2 version          : 5.0.0
PM2        | 2021-06-08T01:48:59: PM2 log: Node.js version      : 15.14.0
PM2        | 2021-06-08T01:48:59: PM2 log: Current arch         : x64
PM2        | 2021-06-08T01:48:59: PM2 log: PM2 home             : /root/.pm2
PM2        | 2021-06-08T01:48:59: PM2 log: PM2 PID file         : /root/.pm2/pm2.pid
PM2        | 2021-06-08T01:48:59: PM2 log: RPC socket file      : /root/.pm2/rpc.sock
PM2        | 2021-06-08T01:48:59: PM2 log: BUS socket file      : /root/.pm2/pub.sock
PM2        | 2021-06-08T01:48:59: PM2 log: Application log path : /root/.pm2/logs
PM2        | 2021-06-08T01:48:59: PM2 log: Worker Interval      : 30000
PM2        | 2021-06-08T01:48:59: PM2 log: Process dump file    : /root/.pm2/dump.pm2
PM2        | 2021-06-08T01:48:59: PM2 log: Concurrent actions   : 2
PM2        | 2021-06-08T01:48:59: PM2 log: SIGTERM timeout      : 1600
PM2        | 2021-06-08T01:48:59: PM2 log: ===============================================================================
PM2        | 2021-06-08T01:48:59: PM2 log: App [pm2-sysmonit:0] starting in -fork mode-
PM2        | 2021-06-08T01:48:59: PM2 log: App [mstream:1] starting in -fork mode-
PM2        | 2021-06-08T01:48:59: PM2 log: App [pm2-sysmonit:0] online
PM2        | 2021-06-08T01:48:59: PM2 log: App [mstream:1] online

```

**Comment by IrosTheBeggar** [comment]
PM2 appears to be taking up more resource usage than usual on the machine this is happening on.  I think it might be related to this bug

**Comment by Unitech** [comment]
Working on it

in the meantime you can do:

pm2 set pm2:sysmonit false
pm2 update

**Comment by Unitech** [comment]
Reinstall pm2, the submodule is fixed

```
npm install pm2@latest -g
pm2 update
```

Re open the issue if you still see the issue
Thanks

**Comment by IrosTheBeggar** [comment]
Everything looks good after the update. Thanks
