### ISSUE TITLE
Getting error every few seconds in the logs (on windows)

### ISSUE THREAD

**Issue by YuanGYao** [Unitech/pm2#5095]
## What's going wrong?
I installed pm2 and started an app. And I see the following error pop up every few seconds.
And it seems that every time the error occurred, the CMD window popup and then disappear.
```
Error while getting network statistics TypeError: Cannot read property 'rx' of null
    at C:\ProgramData\nvm\v14.17.0\node_modules\pm2\node_modules\pm2-sysmonit\src\SystemInfos.js:453:33
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Could not retrieve fds
TypeError: Cannot read property 'allocated' of null
    at C:\ProgramData\nvm\v14.17.0\node_modules\pm2\node_modules\pm2-sysmonit\src\SystemInfos.js:480:45
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error when retrieving process list TypeError: Cannot read property 'includes' of undefined
    at C:\ProgramData\nvm\v14.17.0\node_modules\pm2\node_modules\pm2-sysmonit\src\SystemInfos.js:331:32
    at Array.filter (<anonymous>)
    at C:\ProgramData\nvm\v14.17.0\node_modules\pm2\node_modules\pm2-sysmonit\src\SystemInfos.js:331:12
```
## How could we reproduce this issue?
Install pm2 on windows and start an app. And then check the pm2-sysmonit-error.log

## Supporting information
pm2 version: 5.0.2

I have tried it in different environment.
Windows 10 20H2 + node 14.17.0
Windows Server 2012R2 + node 14.17.0 / 13.14.0 / 13.11.0 / 11.15.0 / 10.24.1
Windows Server 2008R2 + node 13.11.0

**Comment by Unitech** [comment]
fixed on 5.0.3
thanks for reporting
