### ISSUE TITLE
"pm2 l" command throwing error (v5.0.3)

### ISSUE THREAD

**Issue by dsine-de** [Unitech/pm2#5096]
## What's going wrong?

When trying to run `pm2 l` or `pm2 list`, I get the following error:

```
/usr/lib/node_modules/pm2/lib/API/UX/pm2-ls.js:432
    sys_summary_line += `⇓ ${UxHelpers.colorizedMetric(sys_metrics[`net:rx_5:${iface}`].value, 10, 20, 'mb/s')} `
                                                                                        ^

TypeError: Cannot read property 'value' of undefined
    at /usr/lib/node_modules/pm2/lib/API/UX/pm2-ls.js:432:89
    at Array.forEach (<anonymous>)
    at miniMonitBar (/usr/lib/node_modules/pm2/lib/API/UX/pm2-ls.js:430:14)
    at Object.module.exports [as list] (/usr/lib/node_modules/pm2/lib/API/UX/pm2-ls.js:473:5)
    at doList (/usr/lib/node_modules/pm2/lib/API.js:1761:12)
    at /usr/lib/node_modules/pm2/lib/API.js:1731:7
    at /usr/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (node:events:365:28)
    at Parser._write (/usr/lib/node_modules/pm2/node_modules/amp/lib/stream.js:91:16)
```

## How could we reproduce this issue?
- Ubuntu 18.04.5
- pm2 v5.0.3
- Node v16.2.0

## Supporting information
```
--- PM2 report ----------------------------------------------------------------
Date                 : Tue Jun 08 2021 15:21:09 GMT+0200 (Central European Summer Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 5.0.3
node version         : 16.2.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : <redacted>
uid                  : 1000
gid                  : 1000
uptime               : 3min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 5.0.3
node version         : 16.2.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : <redacted>
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) Gold 5215 CPU @ 2.50GHz
cpus nb              : 2
freemem              : 3473924096
totalmem             : 4294967296
home                 : /home/<redacted>
===============================================================================
--- PM2 list -----------------------------------------------
┌─────┬──────────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name                     │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 1   │ <redacted>    │ default     │ N/A     │ fork    │ 8943     │ 3m     │ 0    │ online    │ 0.2%     │ 89.1mb   │ <redacted>    │ disabled │
└─────┴──────────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
```

**Comment by Unitech** [comment]
Fixed via pm2@5.0.4
Feel free to reopen the issue if you have any other issue
