### ISSUE TITLE
Memory limit reload + pm2.reload caused zombie process

### ISSUE THREAD

**Issue by antonybudianto** [Unitech/pm2#5104]
## What's going wrong?

Zombie process due to memory limit reload race condition with pm2.reload.
So, if deployment happen (read: `pm2 reload`, or `kill -1 pid`) during child having killed due to memory limit at the same time, zombie process happened.

## How could we reproduce this issue?

Please clone https://github.com/antonybudianto/hello-pm2/tree/reloadzombie

```
cd src
node lite-pm2 hello

# Grab the main PID
ps aux | grep lite-pm2

# Verify child count, should be 4, expected for now
ps aux | grep boot.js | grep -v grep

# Wait until child memory reload happen, and run
kill -1 <PID>
```

You'll get :

```
2021-06-14T13:41:52: PM2 log: pid=30572 msg=process killed
2021-06-14T13:41:52: PM2 error: [axm:option:configuration] Unknown id _old_3
2021-06-14T13:41:52: PM2 error: [axm:option:configuration] Unknown id _old_3
2021-06-14T13:41:52: PM2 error: AXM ACTION Unknown id _old_3
2021-06-14T13:41:52: PM2 error: AXM ACTION Unknown id _old_3
2021-06-14T13:41:52: PM2 error: AXM ACTION Unknown id _old_3
2021-06-14T13:41:52: PM2 error: AXM ACTION Unknown id _old_3
2021-06-14T13:41:52: PM2 error: AXM ACTION Unknown id _old_3
2021-06-14T13:41:52: PM2 error: [axm:option:configuration] Unknown id _old_3
2021-06-14T13:41:52: PM2 error: [axm:option:configuration] Unknown id _old_3
2021-06-14T13:41:52: PM2 log: -reload- New worker listening
2021-06-14T13:41:52: PM2 error: _old_3 : id unknown
2021-06-14T13:41:52: PM2 error: Trace: Error: _old_3 : id unknown
    at Object.God.logAndGenerateError (/hello-pm2/node_modules/pm2/lib/God/Methods.js:39:12)
    at Object.God.stopProcessId (/hello-pm2/node_modules/pm2/lib/God/ActionMethods.js:306:21)
    at Object.God.deleteProcessId (/hello-pm2/node_modules/pm2/lib/God/ActionMethods.js:383:9)
    at Worker.onListen (/hello-pm2/node_modules/pm2/lib/God/Reload.js:132:16)
```

try check child count again:
```
ps aux | grep boot.js | grep -v grep
```

it became 5, expected 4. (the 5 never becomes 4 again). sometimes it's 6 if child is still memory-limit reloading..
Expected:
If no memory-limit reload (child: 4)
if memory-limit reload (child: 5)
Current:
If no memory-limit reload (child: 5)
if memory-limit reload (child: 6)

Let me know if I missed something, Thanks for your support.

P.S. : Same issue with pm2@5 too. The repro repo used v4.4.0

## Current workaround

I put bus listener to listen on child sigint, based on that, delay the pm2.reload process by some seconds.

## Supporting information

```
$ pm2 report
```

**Comment by Ionys320** [comment]
Hello, any news regarding zombie process?

**Comment by Unitech** [comment]
**v7.0.0** has been released with significant Bun runtime improvements (`ProcessContainerBun.js`, `ProcessContainerForkBun.js`, BPM injection in Bun cluster mode) and a TreeKill rewrite that addresses several process-lifecycle race conditions.

Could you retest on 7.0.0 and confirm whether this issue still reproduces?

```bash
# With npm
npm install pm2@latest -g

# Or with bun
bun install pm2@latest -g

# Then reload the daemon and restore your process list
pm2 update
```

Full release notes: https://github.com/Unitech/pm2/releases/tag/v7.0.0

**Comment by Unitech** [comment]
Thanks for the report.
This has been fixed on pm2@7.0.4

```bash
$ npm install pm2@7.0.4 -g
$ pm2 update
```
