### ISSUE TITLE
pm2 status "ERRORED"

### ISSUE THREAD

**Issue by Neo0165CA** [Unitech/pm2#5125]
--- Daemon logs --------------------------------------------
/home/ubuntu/.pm2/pm2.log last 20 lines:
PM2        |     at WriteStream.EventEmitter.emit (node:domain:548:15)
PM2        |     at node:internal/fs/streams:61:16
PM2        |     at FSReqCallback.oncomplete (node:fs:171:23)
PM2        | 2021-07-19T08:57:43: PM2 log: App [server:0] online
PM2        | 2021-07-19T08:57:43: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-07-19T08:57:43: PM2 log: App [server:0] starting in -fork mode-
PM2        | 2021-07-19T08:57:43: PM2 error: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (7247)
PM2        |     at Object.writeFileSync (node:fs:1464:5)
PM2        |     at /usr/local/lib/node_modules/pm2/lib/God/ForkMode.js:264:12
PM2        |     at wrapper (/usr/local/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16)
PM2        |     at next (/usr/local/lib/node_modules/pm2/node_modules/async/waterfall.js:96:20)
PM2        |     at /usr/local/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
PM2        |     at WriteStream.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Utility.js:186:13)
PM2        |     at WriteStream.emit (node:events:327:20)
PM2        |     at WriteStream.EventEmitter.emit (node:domain:548:15)
PM2        |     at node:internal/fs/streams:61:16
PM2        |     at FSReqCallback.oncomplete (node:fs:171:23)
PM2        | 2021-07-19T08:57:43: PM2 log: App [server:0] online
PM2        | 2021-07-19T08:57:44: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-07-19T08:57:44: PM2 log: Script /home/ubuntu/project/server.js had too many unstable restarts (16). Stopped. "errored"

**Comment by prabhatpp** [comment]
hi i got this  error
