### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by rockycastaneda** [Unitech/pm2#5136]
## What's going wrong?

export default class Tools {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/rox/Projects/CrimeTimeApi/models/Case.js:4:15)

## How could we reproduce this issue?

I have a class named Tools declared as 

export default class Tools {
.
.
.
}	

## Supporting information

I can run the app alone without the -i max option but if i use the -i max option, it gives me the above stated error.

```
$ pm2 report
```

**Comment by rockycastaneda** [comment]
```
--- PM2 report ----------------------------------------------------------------
Date                 : Thu Jul 29 2021 19:01:37 GMT-0700 (Pacific Daylight Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 5.1.0
node version         : 16.4.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/Cellar/node/16.4.0/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : rox
uid                  : 501
gid                  : 20
uptime               : 119min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 5.1.0
node version         : 16.4.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/Cellar/node/16.4.0/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : rox
uid                  : 501
gid                  : 20
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : darwin
type                 : Darwin
cpus                 : Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
cpus nb              : 4
freemem              : 633044992
totalmem             : 17179869184
home                 : /Users/rox
===============================================================================
--- PM2 list -----------------------------------------------
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 0  │ server             │ cluster  │ 403  │ online    │ 0%       │ 64.3mb   │
│ 1  │ server             │ cluster  │ 405  │ online    │ 0%       │ 42.9mb   │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
[PM2][WARN] Current process list is not synchronized with saved list. Type 'pm2 save' to synchronize.
===============================================================================
--- Daemon logs --------------------------------------------
/Users/rox/.pm2/pm2.log last 20 lines:
PM2        | 2021-07-29T19:01:32: PM2 log: App name:server id:1 disconnected
PM2        | 2021-07-29T19:01:32: PM2 log: App [server:1] exited with code [0] via signal [SIGINT]
PM2        | 2021-07-29T19:01:32: PM2 log: App [server:1] starting in -cluster mode-
PM2        | 2021-07-29T19:01:32: PM2 log: App [server:1] online
PM2        | 2021-07-29T19:01:33: PM2 log: App name:server id:0 disconnected
PM2        | 2021-07-29T19:01:33: PM2 log: App [server:0] exited with code [0] via signal [SIGINT]
PM2        | 2021-07-29T19:01:33: PM2 log: App [server:0] starting in -cluster mode-
PM2        | 2021-07-29T19:01:33: PM2 log: App [server:0] online
PM2        | 2021-07-29T19:01:34: PM2 log: App name:server id:1 disconnected
PM2        | 2021-07-29T19:01:34: PM2 log: App [server:1] exited with code [0] via signal [SIGINT]
PM2        | 2021-07-29T19:01:34: PM2 log: App [server:1] starting in -cluster mode-
PM2        | 2021-07-29T19:01:35: PM2 log: App [server:1] online
PM2        | 2021-07-29T19:01:35: PM2 log: App name:server id:0 disconnected
PM2        | 2021-07-29T19:01:35: PM2 log: App [server:0] exited with code [0] via signal [SIGINT]
PM2        | 2021-07-29T19:01:35: PM2 log: App [server:0] starting in -cluster mode-
PM2        | 2021-07-29T19:01:35: PM2 log: App [server:0] online
PM2        | 2021-07-29T19:01:36: PM2 log: App name:server id:1 disconnected
PM2        | 2021-07-29T19:01:36: PM2 log: App [server:1] exited with code [0] via signal [SIGINT]
PM2        | 2021-07-29T19:01:36: PM2 log: App [server:1] starting in -cluster mode-
PM2        | 2021-07-29T19:01:36: PM2 log: App [server:1] online

```
