### ISSUE TITLE
TypeError: type.slice is not a function

### ISSUE THREAD

**Issue by marcosspn** [Unitech/pm2#5257]
## What's going wrong?

This error is happening:

```
PM2          | ===============================================================================
PM2          | --- PM2 global error caught ---------------------------------------------------
PM2          | Time                 : Tue Dec 21 2021 13:45:52 GMT+0000 (Coordinated Universal Time)
PM2          | type.slice is not a function
PM2          | TypeError: type.slice is not a function
PM2          |     at EventEmitter.emit (/usr/lib/node_modules/pm2/node_modules/eventemitter2/lib/eventemitter2.js:343:77)
PM2          |     at Worker.cluMessage (/usr/lib/node_modules/pm2/lib/God/ClusterMode.js:65:24)
PM2          |     at Worker.emit (events.js:412:35)
PM2          |     at Worker.emit (domain.js:537:15)
PM2          |     at ChildProcess.<anonymous> (internal/cluster/worker.js:33:12)
PM2          |     at ChildProcess.emit (events.js:400:28)
PM2          |     at ChildProcess.emit (domain.js:537:15)
PM2          |     at emit (internal/child_process.js:912:12)
PM2          |     at processTicksAndRejections (internal/process/task_queues.js:83:21)
PM2          | ===============================================================================
PM2          | [PM2] Resurrecting PM2
```

## How could we reproduce this issue?

Everytime I run the app in cluster mode the error happens and PM2 keeps restarting with the same error happening again.

## Supporting information

```
--- PM2 report ----------------------------------------------------------------
Date                 : Tue Dec 21 2021 14:16:29 GMT+0000 (Coordinated Universal Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 5.1.2
node version         : 14.18.2
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : marcos
uid                  : 1001
gid                  : 1002
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 5.1.2
node version         : 14.18.2
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : marcos
uid                  : 1001
gid                  : 1002
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU @ 2.20GHz
cpus nb              : 2
freemem              : 6384754688
totalmem             : 8340885504
home                 : /home/marcos
===============================================================================
--- PM2 list -----------------------------------------------
┌─────┬──────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name         │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2   │ connector    │ default     │ 1.7.0   │ cluster │ 605142   │ 1s     │ 0    │ online    │ 18.2%    │ 50.7mb   │ marcos   │ enabled  │
│ 1   │ processor    │ default     │ 1.7.0   │ cluster │ 605134   │ 1s     │ 0    │ online    │ 22.7%    │ 50.8mb   │ marcos   │ enabled  │
│ 0   │ scheduler    │ default     │ 1.7.0   │ cluster │ 605128   │ 1s     │ 0    │ online    │ 31.8%    │ 55.2mb   │ marcos   │ enabled  │
└─────┴──────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/home/marcos/.pm2/pm2.log last 20 lines:
PM2        | 2021-12-21T14:16:28: PM2 log: Current arch         : x64
PM2        | 2021-12-21T14:16:28: PM2 log: PM2 home             : /home/marcos/.pm2
PM2        | 2021-12-21T14:16:28: PM2 log: PM2 PID file         : /home/marcos/.pm2/pm2.pid
PM2        | 2021-12-21T14:16:28: PM2 log: RPC socket file      : /home/marcos/.pm2/rpc.sock
PM2        | 2021-12-21T14:16:28: PM2 log: BUS socket file      : /home/marcos/.pm2/pub.sock
PM2        | 2021-12-21T14:16:28: PM2 log: Application log path : /home/marcos/.pm2/logs
PM2        | 2021-12-21T14:16:28: PM2 log: Worker Interval      : 30000
PM2        | 2021-12-21T14:16:28: PM2 log: Process dump file    : /home/marcos/.pm2/dump.pm2
PM2        | 2021-12-21T14:16:28: PM2 log: Concurrent actions   : 2
PM2        | 2021-12-21T14:16:28: PM2 log: SIGTERM timeout      : 1600
PM2        | 2021-12-21T14:16:28: PM2 log: ===============================================================================
PM2        | 2021-12-21T14:16:28: PM2 log: [Watch] Start watching scheduler
PM2        | 2021-12-21T14:16:28: PM2 log: App [scheduler:0] starting in -cluster mode-
PM2        | 2021-12-21T14:16:28: PM2 log: [Watch] Start watching processor
PM2        | 2021-12-21T14:16:28: PM2 log: App [processor:1] starting in -cluster mode-
PM2        | 2021-12-21T14:16:28: PM2 log: App [scheduler:0] online
PM2        | 2021-12-21T14:16:28: PM2 log: [Watch] Start watching connector
PM2        | 2021-12-21T14:16:28: PM2 log: App [connector:2] starting in -cluster mode-
PM2        | 2021-12-21T14:16:28: PM2 log: App [processor:1] online
PM2        | 2021-12-21T14:16:29: PM2 log: App [connector:2] online

```

**Comment by fabcam** [comment]
We are having the same issue. Where you able to solve it @marcosspn ?? Thanks!
