### ISSUE TITLE
failed to install pm2-intercom

### ISSUE THREAD

**Issue by imseon** [Unitech/pm2#5306]
## What's going wrong?
failed to install pm2-intercom

## How could we reproduce this issue?
just run pm2 install pm2-intercom.

will get these output:

```
[PM2][Module] Installing NPM pm2-intercom module
[PM2][Module] Calling [NPM] to install pm2-intercom ...
npm ERR! code 1
npm ERR! Command failed: git checkout development
npm ERR! error: pathspec 'development' did not match any file(s) known to git
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-17T12_40_03_545Z-debug.log
[PM2][ERROR] Installation failed via NPM, module has been restored to prev version
```

## Supporting information

```
--- PM2 report ----------------------------------------------------------------
Date                 : Thu Feb 17 2022 20:40:50 GMT+0800 (China Standard Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 5.1.2
node version         : 14.19.0
node path            : not found
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
uptime               : 225min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 5.1.2
node version         : 14.19.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel Core Processor (Broadwell, IBRS)
cpus nb              : 8
freemem              : 14126854144
totalmem             : 16820056064
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 1  │ ippt-conv          │ cluster  │ 0    │ online    │ 0%       │ 132.9mb  │
│ 2  │ ippt-conv          │ cluster  │ 0    │ online    │ 0.8%     │ 117.5mb  │
│ 3  │ ippt-conv          │ cluster  │ 0    │ online    │ 0%       │ 225.0mb  │
│ 4  │ ippt-conv          │ cluster  │ 0    │ online    │ 0.8%     │ 247.6mb  │
│ 5  │ ippt-conv          │ cluster  │ 0    │ online    │ 0%       │ 227.6mb  │
│ 6  │ ippt-conv          │ cluster  │ 0    │ online    │ 0%       │ 122.0mb  │
│ 7  │ ippt-conv          │ cluster  │ 0    │ online    │ 0.8%     │ 114.6mb  │
│ 8  │ ippt-conv          │ cluster  │ 0    │ online    │ 0.8%     │ 165.4mb  │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/root/.pm2/pm2.log last 20 lines:
PM2        | 2022-02-17T16:54:56: PM2 log: SIGTERM timeout      : 1600
PM2        | 2022-02-17T16:54:56: PM2 log: ===============================================================================
PM2        | 2022-02-17T16:54:56: PM2 log: App [ippt-conv:1] starting in -cluster mode-
PM2        | 2022-02-17T16:54:56: PM2 log: App [ippt-conv:1] online
PM2        | 2022-02-17T16:54:56: PM2 log: App [ippt-conv:2] starting in -cluster mode-
PM2        | 2022-02-17T16:54:56: PM2 log: App [ippt-conv:2] online
PM2        | 2022-02-17T16:54:56: PM2 log: App [ippt-conv:3] starting in -cluster mode-
PM2        | 2022-02-17T16:54:56: PM2 log: App [ippt-conv:3] online
PM2        | 2022-02-17T16:54:56: PM2 log: App [ippt-conv:4] starting in -cluster mode-
PM2        | 2022-02-17T16:54:56: PM2 log: App [ippt-conv:4] online
PM2        | 2022-02-17T16:54:56: PM2 log: App [ippt-conv:5] starting in -cluster mode-
PM2        | 2022-02-17T16:54:56: PM2 log: App [ippt-conv:5] online
PM2        | 2022-02-17T16:54:56: PM2 log: App [ippt-conv:6] starting in -cluster mode-
PM2        | 2022-02-17T16:54:56: PM2 log: App [ippt-conv:6] online
PM2        | 2022-02-17T16:54:56: PM2 log: App [ippt-conv:7] starting in -cluster mode-
PM2        | 2022-02-17T16:54:56: PM2 log: App [ippt-conv:7] online
PM2        | 2022-02-17T16:54:56: PM2 log: App [ippt-conv:8] starting in -cluster mode-
PM2        | 2022-02-17T16:54:56: PM2 log: App [ippt-conv:8] online

```

**Comment by Takezawa** [comment]
I am in the same situation.
It seems to be caused by trying to fetch the development branch, but I don't know how to fix it.

```
26 silly fetchPackageMetaData error for pm2@github:unitech/pm2#development Command failed: git checkout development
26 silly fetchPackageMetaData error: pathspec 'development' did not match any file(s) known to git
27 timing stage:rollbackFailedOptional Completed in 0ms
28 timing stage:runTopLevelLifecycles Completed in 15125ms
29 silly saveTree pm2-intercom
29 silly saveTree └─┬ pm2-intercom@1.0.0
29 silly saveTree   ├── async@3.2.3
29 silly saveTree   ├── pmx@1.6.7
29 silly saveTree   └── semver@7.3.5
30 verbose stack Error: Command failed: git checkout development
30 verbose stack error: pathspec 'development' did not match any file(s) known to git
30 verbose stack
30 verbose stack     at ChildProcess.exithandler (child_process.js:308:12)
30 verbose stack     at ChildProcess.emit (events.js:314:20)
30 verbose stack     at maybeClose (internal/child_process.js:1022:16)
30 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

**Comment by cococe** [comment]
me to, the same error.
fetchPackageMetaData error for pm2@github:unitech/pm2#development Command failed: /usr/bin/git checkout development

**Comment by imseon** [comment]
@cococe you are right, I published another package to npm, changed the dependence to unitech/pm2#master, and solved the problem.

**Comment by always-awake** [comment]
@alvaropacokink

try [pm2-intercom-search](https://www.npmjs.com/package/pm2-intercom-search) or [pm2-intercom-eeo](https://www.npmjs.com/package/pm2-intercom-eeo)

**Comment by alvaropacokink** [comment]
@always-awake I don't think so. This is an issue with `[pm2-intercom](https://registry.npmjs.org/pm2-intercom)`. But, the pm2 guys just deleted the development branch, changing the gitflow and causing this error.
Anybody has some workaround or fix?

**Comment by imseon** [comment]
@alvaropacokink As always-awake said, you can use [pm2-intercom-eeo](https://www.npmjs.com/package/pm2-intercom-eeo) instead. That's the package I published. Made no changes but changing the branch from development to master.

**Comment by Unitech** [comment]
I recreated the development branch, sorry for the unexpected

**Comment by always-awake** [comment]
@Unitech
I wonder why `pm2-intercom` package  is looking at the development branch, not the master.

**Comment by robincsamuel** [comment]
@Unitech It's taking very long to install `pm2-intercom`. I tried [pm2-graceful-intercom](https://github.com/Claude-Ray/pm2-graceful-intercom) and it works fine.
