### ISSUE TITLE
Express server crashes unexpected with pm2

### ISSUE THREAD

**Issue by martianmartian** [Unitech/pm2#5323]
## What's going wrong?

/opt/homebrew/lib/node_modules/@socket.io/pm2/node_modules/@socket.io/sticky/index.js:55
        return leastActiveWorker.id;
                                 ^

TypeError: Cannot read properties of undefined (reading 'id')
    at computeWorkerId (/opt/homebrew/lib/node_modules/@socket.io/pm2/node_modules/@socket.io/sticky/index.js:55:34)
    at Socket.<anonymous> (/opt/homebrew/lib/node_modules/@socket.io/pm2/node_modules/@socket.io/sticky/index.js:63:24)
    at Object.onceWrapper (node:events:510:26)
    at Socket.emit (node:events:402:35)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)

this happens so frequently with my express server

## How could we reproduce this issue?
"express": "^4.16.2",
pm2 is latest
## Supporting information

```
$ pm2 report
```

**Comment by martianmartian** [comment]
it seems timeout param makes a difference... and had nothing todo with express.js, but rather interfered by webpack's hot reload feature, which also depend on sockets.

var connectionOptions = {
    // "reconnectionAttempts": "Infinity",
    // "timeout": 10000,
    // withCredentials: true, // with cookies
    // "transports": ["websocket"]
};

const socket = io(namespace, connectionOptions);

i commented out the "timeout" and it started working fine.
