### ISSUE TITLE
pm2 (v5.2.0) throws exception after kill...

### ISSUE THREAD

**Issue by 524c** [Unitech/pm2#5371]
## What's going wrong?
pm2 throws exception after list or start command if it is right after a kill

## How could we reproduce this issue?
First flow:
Start a project if not exist any: `pm2 start pm2.json --env development`
Kill all projects: `pm2 kill`
Start any project again `pm2 start pm2.json --env development`

Second flow:
Kill all projects: `pm2 kill`
Run `pm2 list`

```
05:39:48 xx@rpi4-1 code ±|master ✗|→ pm2 list
[PM2] Spawning PM2 daemon with pm2_home=/xx/.pm2
[PM2] PM2 Successfully daemonized
[PM2][Module] Starting NPM module @types/node
[PM2][WARN] Applications  not running, starting...
[PM2][ERROR] Error: No script path - aborting
[
  Error: No script path - aborting
      at Object.Common.resolveAppAttributes (/xx/.local/share/pnpm/global/5/.pnpm/pm2@5.2.0/node_modules/pm2/lib/Common.js:647:11)
      at /xx/.local/share/pnpm/global/5/.pnpm/pm2@5.2.0/node_modules/pm2/lib/API.js:1129:35
      at /xx/.local/share/pnpm/global/5/.pnpm/pm2@5.2.0/node_modules/pm2/node_modules/async/internal/withoutIndex.js:8:40
      at replenish (/xx/.local/share/pnpm/global/5/.pnpm/pm2@5.2.0/node_modules/pm2/node_modules/async/internal/eachOfLimit.js:81:17)
      at /xx/.local/share/pnpm/global/5/.pnpm/pm2@5.2.0/node_modules/pm2/node_modules/async/internal/eachOfLimit.js:86:9
      at eachLimit (/xx/.local/share/pnpm/global/5/.pnpm/pm2@5.2.0/node_modules/pm2/node_modules/async/eachLimit.js:47:43)
      at awaitable (/xx/.local/share/pnpm/global/5/.pnpm/pm2@5.2.0/node_modules/pm2/node_modules/async/internal/awaitify.js:13:28)
      at startApps (/xx/.local/share/pnpm/global/5/.pnpm/pm2@5.2.0/node_modules/pm2/lib/API.js:1113:7)
      at /xx/.local/share/pnpm/global/5/.pnpm/pm2@5.2.0/node_modules/pm2/lib/API.js:1094:16
      at wrapper (/xx/.local/share/pnpm/global/5/.pnpm/pm2@5.2.0/node_modules/pm2/node_modules/async/internal/once.js:12:16)
```

**Comment by trevorparscal** [comment]
I'm also seeing this issue with the latest version (5.2.0) today, has there been any resolution to it?

**Comment by 524c** [comment]
> I'm also seeing this issue with the latest version (5.2.0) today, has there been any resolution to it?

no :)
