### ISSUE TITLE
PM2 error: Trace: Error: spawn E2BIG

### ISSUE THREAD

**Issue by Shravanannavajjala-gep** [Unitech/pm2#5377]
We are facing this issue while deploying our application with node version of 16.14.0. Below are the error details
2022-06-15T07:44:38: PM2 log: Launching in no daemon mode
2022-06-15T07:44:39: PM2 log: App [index:0] starting in -cluster mode-
2022-06-15T07:44:40: PM2 error: Trace: Error: spawn E2BIG
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:700:9)
    at fork (node:child_process:166:10)
    at createWorkerProcess (node:internal/cluster/primary:144:10)
    at EventEmitter.cluster.fork (node:internal/cluster/primary:179:25)
    at Object.nodeApp (/node_modules/pm2/lib/God/ClusterMode.js:48:21)
    at Object.executeApp (/node_modules/pm2/lib/God.js:232:9)
    at inject (/node_modules/pm2/lib/God.js:146:18)
    at Object.injectVariables (/node_modules/pm2/lib/God.js:573:10)
    at /node_modules/pm2/lib/God.js:144:9 {
  errno: -7,
  code: 'E2BIG',
  syscall: 'spawn'
}
    at Object.God.logAndGenerateError (/node_modules/pm2/lib/God/Methods.js:34:15)
    at Object.nodeApp (/node_modules/pm2/lib/God/ClusterMode.js:50:11)
    at Object.executeApp (/node_modules/pm2/lib/God.js:232:9)
    at inject (/node_modules/pm2/lib/God.js:146:18)
    at Object.injectVariables (/node_modules/pm2/lib/God.js:573:10)
    at /node_modules/pm2/lib/God.js:144:9
    at /node_modules/async/internal/map.js:22:9
    at replenish (/node_modules/async/internal/eachOfLimit.js:81:17)
    at /node_modules/async/internal/eachOfLimit.js:86:9
    at _asyncMap (/node_modules/async/internal/map.js:20:12)
2022-06-15T07:44:40: PM2 error: spawn E2BIG

**Comment by alexander-bozung** [comment]
Any news on this one?

**Comment by OnlyPiglet** [comment]
> Any news on this one?

yes, if you deploy app by k8s, k8s will inject all service info by env, so you can disable this feature by set pod.spec field

enableServiceLinks: false

**Comment by OnlyPiglet** [comment]
> We are facing this issue while deploying our application with node version of 16.14.0. Below are the error details
> 2022-06-15T07:44:38: PM2 log: Launching in no daemon mode
> 2022-06-15T07:44:39: PM2 log: App [index:0] starting in -cluster mode-
> 2022-06-15T07:44:40: PM2 error: Trace: Error: spawn E2BIG
> at ChildProcess.spawn (node:internal/child_process:413:11)
> at spawn (node:child_process:700:9)
> at fork (node:child_process:166:10)
> at createWorkerProcess (node:internal/cluster/primary:144:10)
> at EventEmitter.cluster.fork (node:internal/cluster/primary:179:25)
> at Object.nodeApp (/node_modules/pm2/lib/God/ClusterMode.js:48:21)
> at Object.executeApp (/node_modules/pm2/lib/God.js:232:9)
> at inject (/node_modules/pm2/lib/God.js:146:18)
> at Object.injectVariables (/node_modules/pm2/lib/God.js:573:10)
> at /node_modules/pm2/lib/God.js:144:9 {
> errno: -7,
> code: 'E2BIG',
> syscall: 'spawn'
> }
> at Object.God.logAndGenerateError (/node_modules/pm2/lib/God/Methods.js:34:15)
> at Object.nodeApp (/node_modules/pm2/lib/God/ClusterMode.js:50:11)
> at Object.executeApp (/node_modules/pm2/lib/God.js:232:9)
> at inject (/node_modules/pm2/lib/God.js:146:18)
> at Object.injectVariables (/node_modules/pm2/lib/God.js:573:10)
> at /node_modules/pm2/lib/God.js:144:9
> at /node_modules/async/internal/map.js:22:9
> at replenish (/node_modules/async/internal/eachOfLimit.js:81:17)
> at /node_modules/async/internal/eachOfLimit.js:86:9
> at _asyncMap (/node_modules/async/internal/map.js:20:12)
> 2022-06-15T07:44:40: PM2 error: spawn E2BIG

yes, if you deploy app by k8s, k8s will inject all service info by env, so you can disable this feature by set pod.spec field

enableServiceLinks: false

**Comment by OnlyPiglet** [comment]
> We are facing this issue while deploying our application with node version of 16.14.0. Below are the error details
> 2022-06-15T07:44:38: PM2 log: Launching in no daemon mode
> 2022-06-15T07:44:39: PM2 log: App [index:0] starting in -cluster mode-
> 2022-06-15T07:44:40: PM2 error: Trace: Error: spawn E2BIG
> at ChildProcess.spawn (node:internal/child_process:413:11)
> at spawn (node:child_process:700:9)
> at fork (node:child_process:166:10)
> at createWorkerProcess (node:internal/cluster/primary:144:10)
> at EventEmitter.cluster.fork (node:internal/cluster/primary:179:25)
> at Object.nodeApp (/node_modules/pm2/lib/God/ClusterMode.js:48:21)
> at Object.executeApp (/node_modules/pm2/lib/God.js:232:9)
> at inject (/node_modules/pm2/lib/God.js:146:18)
> at Object.injectVariables (/node_modules/pm2/lib/God.js:573:10)
> at /node_modules/pm2/lib/God.js:144:9 {
> errno: -7,
> code: 'E2BIG',
> syscall: 'spawn'
> }
> at Object.God.logAndGenerateError (/node_modules/pm2/lib/God/Methods.js:34:15)
> at Object.nodeApp (/node_modules/pm2/lib/God/ClusterMode.js:50:11)
> at Object.executeApp (/node_modules/pm2/lib/God.js:232:9)
> at inject (/node_modules/pm2/lib/God.js:146:18)
> at Object.injectVariables (/node_modules/pm2/lib/God.js:573:10)
> at /node_modules/pm2/lib/God.js:144:9
> at /node_modules/async/internal/map.js:22:9
> at replenish (/node_modules/async/internal/eachOfLimit.js:81:17)
> at /node_modules/async/internal/eachOfLimit.js:86:9
> at _asyncMap (/node_modules/async/internal/map.js:20:12)
> 2022-06-15T07:44:40: PM2 error: spawn E2BIG

this is because pm2 will fork failed in cluster mode when too many env variable

**Comment by 5idu** [comment]
you can use `filter_env` to resolve the problem!
```json
{
    "name": "mytest",
    "script": "./bin/www",
    "instances": "1",
    "autorestart": true,
    "time": true,
    "filter_env": [
        "PREFIX_"
    ]
}
```
