### ISSUE TITLE
15 restarts, no logs

### ISSUE THREAD

**Issue by dandv** [Unitech/pm2#546]
My script is in an `errored` status and none of the log files shown by `pm2 desc` contain anything (they don't exist). How can I debug what caused [the 15 restarts in a row](github.com/Unitech/pm2/pull/251#issue-25486932)?

``` text
02:16:28 [0s] stockbase:~/stockbase$ pm2 desc 4
Describing process with pid 4 - name stockbase-frontend-prod
┌───────────────────┬────────────────────────────────────────────────────────────────────┐
│ status            │ errored                                                            │
│ name              │ stockbase-frontend-prod                                            │
│ id                │ 4                                                                  │
│ path              │ /home/stockbase/stockbase-prod/frontend/stockbase-frontend-prod.js │
│ exec cwd          │ /home/stockbase/stockbase-prod                                     │
│ error log path    │ /home/stockbase/stockbase-prod/stockbase-frontend-prod.err         │
│ out log path      │ /home/stockbase/stockbase-prod/stockbase-frontend-prod-4.log       │
│ pid path          │ /home/stockbase/.pm2/pids/stockbase-frontend-prod.pid              │
│ mode              │ cluster_mode                                                       │
│ watch & reload    │ ✘                                                                  │
│ interpreter       │ node                                                               │
│ restarts          │ 15                                                                 │
│ unstable restarts │ 0                                                                  │
│ uptime            │ 0                                                                  │
│ created at        │ 1970-01-01T00:00:00.000Z                                           │
└───────────────────┴────────────────────────────────────────────────────────────────────┘
02:16:45 [0s] stockbase:~/stockbase$ cat /home/stockbase/stockbase-prod/stockbase-frontend-prod-4.log
cat: /home/stockbase/stockbase-prod/stockbase-frontend-prod-4.log: No such file or directory
02:17:03 [0s] stockbase:~/stockbase$ cat /home/stockbase/stockbase-prod/stockbase-frontend-prod.err
cat: /home/stockbase/stockbase-prod/stockbase-frontend-prod.err: No such file or directory
```

Also, `~/pm2/logs` is empty.

**Comment by jkulak** [comment]
In my case the problem was trivial. I looked at `$ tailf ~/.pm2/pm2.log` to see:

```
vagrant@lol-slack-bot-local:~/.pm2$ tailf ~/.pm2/pm2.log
2016-10-19 14:42:53: Starting execution sequence in -fork mode- for app name:lol-slack-bot-TEST id:0
2016-10-19 14:42:53: App name:lol-slack-bot-TEST id:0 online
2016-10-19 14:42:54: App [lol-slack-bot-TEST] with id [0] and pid [14834], exited with code [0] via signal [SIGINT]
2016-10-19 14:42:54: Starting execution sequence in -fork mode- for app name:lol-slack-bot-TEST id:0
2016-10-19 14:42:54: App name:lol-slack-bot-TEST id:0 online
2016-10-19 14:42:55: App [lol-slack-bot-TEST] with id [0] and pid [14860], exited with code [0] via signal [SIGINT]
2016-10-19 14:42:55: Starting execution sequence in -fork mode- for app name:lol-slack-bot-TEST id:0
2016-10-19 14:42:55: App name:lol-slack-bot-TEST id:0 online
2016-10-19 14:42:56: App [lol-slack-bot-TEST] with id [0] and pid [14886], exited with code [0] via signal [SIGINT]
2016-10-19 14:42:56: Script /mnt/host/mount_dir/test.js had too many unstable restarts (16). Stopped. "errored"
```

The part `exited with code [0] via signal [SIGINT]` mans that execution of my script has finished and therefore it needs to be restarted.

I did not have any server/while loops inside my script - so it run from top to bottom and was exiting as soon as it run the last line of code. As expected... This was causing the 15 restarts.

**Comment by ktrzeciaknubisa** [comment]
I started to have same problems with pm2 2.3.0, when trying to run cluster app with `-i 2` option. The app logs didn't show anything, because the problem probably was related to pm2 itself:

```bash
$ pm2 logs --lines 200
[TAILING] Tailing last 200 lines for [all] processes (change the value with --lines option)
/home/ubuntu/.pm2/pm2.log last 200 lines:
...
PM2        | path.js:1144
PM2        |           cwd = process.cwd();
PM2        |                         ^
PM2        | 
PM2        | Error: ENOENT: no such file or directory, uv_cwd
PM2        |     at Error (native)
PM2        |     at Object.resolve (path.js:1144:25)
PM2        |     at Function.Module._resolveLookupPaths (module.js:361:17)
PM2        |     at Function.Module._resolveFilename (module.js:431:31)
PM2        |     at Function.Module._load (module.js:388:25)
PM2        |     at Module.require (module.js:468:17)
PM2        |     at require (internal/module.js:20:19)
PM2        |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:12:15)
PM2        |     at Module._compile (module.js:541:32)
PM2        |     at Object.Module._extensions..js (module.js:550:10)
PM2        | 2017-02-20 14:16:08: App name:app id:0 disconnected
PM2        | 2017-02-20 14:16:08: App [app] with id [0] and pid [28520], exited with code [1] via signal [SIGINT]
PM2        | 2017-02-20 14:16:08: Script /.../app.js had too many unstable restarts (16). Stopped. "errored"
PM2        | 2017-02-20 14:16:08: App name:app id:1 disconnected
PM2        | 2017-02-20 14:16:08: App [app] with id [1] and pid [28538], exited with code [1] via signal [SIGINT]
PM2        | 2017-02-20 14:16:08: Script /.../app.js had too many unstable restarts (16). Stopped. "errored"
```

Running it in non-cluster mode worked. Also worked in cluster mode, but with `--no-daemon`.

However after I upgraded pm2 to 2.4.0 it started to work for me.
