### ISSUE TITLE
how to install pm2 on node js 8 ?

### ISSUE THREAD

**Issue by dnsdev9** [Unitech/pm2#5476]
===============================================================================
--- Daemon logs --------------------------------------------
/root/.pm2/pm2.log last 20 lines:
PM2        |     at God.deleteProcessId (/root/.nvm/versions/node/v8.17.0/lib/node_modules/pm2/lib/God/ActionMethods.js:366:9)
PM2        |     at Server.onmessage (/root/.nvm/versions/node/v8.17.0/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:104:6)
PM2        |     at emitTwo (events.js:126:13)
PM2        |     at RepSocket.emit (events.js:214:7)
PM2        |     at Parser.<anonymous> (/root/.nvm/versions/node/v8.17.0/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/rep.js:51:15)
PM2        |     at emitOne (events.js:116:13)
PM2        |     at Parser.emit (events.js:211:7)
PM2        |     at Parser._write (/root/.nvm/versions/node/v8.17.0/lib/node_modules/pm2/node_modules/amp/lib/stream.js:91:16)
PM2        |     at Object.God.logAndGenerateError (/root/.nvm/versions/node/v8.17.0/lib/node_modules/pm2/lib/God/Methods.js:34:15)
PM2        |     at /root/.nvm/versions/node/v8.17.0/lib/node_modules/pm2/lib/God/ActionMethods.js:367:30
PM2        |     at Object.God.stopProcessId (/root/.nvm/versions/node/v8.17.0/lib/node_modules/pm2/lib/God/ActionMethods.js:289:14)
PM2        |     at God.deleteProcessId (/root/.nvm/versions/node/v8.17.0/lib/node_modules/pm2/lib/God/ActionMethods.js:366:9)
PM2        |     at Server.onmessage (/root/.nvm/versions/node/v8.17.0/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:104:6)
PM2        |     at emitTwo (events.js:126:13)
PM2        |     at RepSocket.emit (events.js:214:7)
PM2        |     at Parser.<anonymous> (/root/.nvm/versions/node/v8.17.0/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/rep.js:51:15)
PM2        |     at emitOne (events.js:116:13)
PM2        |     at Parser.emit (events.js:211:7)
PM2        | 2022-10-27T14:03:28: PM2 log: [PM2] This PM2 is not UP TO DATE
PM2        | 2022-10-27T14:03:28: PM2 log: [PM2] Upgrade to version 5.2.2

**Comment by johandalabacka** [comment]
Node 8:s eol was at December 31, 2019 so you could try to run a version of pm2 before this date

**Comment by dnsdev9** [comment]
can share link how to download old version pm2 ?

**Comment by johandalabacka** [comment]
You just do as before but instead of `yarn add pm2` or `npm install pm2` you need to specify a version for the package like pm2@4.0.1 see here for old versions of pm2 https://www.npmjs.com/package/pm2

**Comment by itsvinayak** [comment]
hi @dnsdev9, did the solution work?

**Comment by masterbater** [comment]
Node 10 is supported in the latest version so try upgrading node 8 to node 10

**Comment by markosole** [comment]
I've found that pm2@2.6.0 works fine with node 8.16.0. 

```
npm install pm2@2.6.0 -g
pm2 install pm2-logrotate
```

Logrotate is optional. If you had logrotate before and downgraded pm2 to lower version then you'll have to reinstall pm2-logrotate.
