### ISSUE TITLE
Deploy nextjs app from local to vps -> no logs in pm2 log

### ISSUE THREAD

**Issue by silviu-cpu** [Unitech/pm2#5563]
## What's going wrong?

```
--- PM2 report ----------------------------------------------------------------
Date                 : Thu Mar 02 2023 00:34:46 GMT+0200 (Eastern European Standard Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 5.2.2
node version         : 14.15.0
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\barbu\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 122min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 5.2.2
node version         : 14.15.0
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\barbu\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : C:\Program Files\nodejs\node.exe
user                 : barbu
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
cpus nb              : 12
freemem              : 9432842240
totalmem             : 17108914176
home                 : C:\Users\barbu
===============================================================================
--- PM2 list -----------------------------------------------
┌─────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐│ id  │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │└─────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘===============================================================================
--- Daemon logs --------------------------------------------
C:\Users\barbu\.pm2\pm2.log last 20 lines:
PM2        | 2023-02-27T00:14:34: PM2 log: Concurrent actions   : 2
PM2        | 2023-02-27T00:14:34: PM2 log: SIGTERM timeout      : 1600
PM2        | 2023-02-27T00:14:34: PM2 log: ===============================================================================
PM2        | 2023-03-01T22:32:24: PM2 log: ===============================================================================
PM2        | 2023-03-01T22:32:24: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2023-03-01T22:32:24: PM2 log: Time                 : Wed Mar 01 2023 22:32:24 GMT+0200 (Eastern European Standard Time)
PM2        | 2023-03-01T22:32:24: PM2 log: PM2 version          : 5.2.2
PM2        | 2023-03-01T22:32:24: PM2 log: Current arch         : x64
PM2        | 2023-03-01T22:32:24: PM2 log: PM2 home             : C:\Users\barbu\.pm2
PM2        | 2023-03-01T22:32:24: PM2 log: PM2 PID file         : C:\Users\barbu\.pm2\pm2.pid
PM2        | 2023-03-01T22:32:24: PM2 log: RPC socket file      : \\.\pipe\rpc.sock
PM2        | 2023-03-01T22:32:24: PM2 log: BUS socket file      : \\.\pipe\pub.sock
PM2        | 2023-03-01T22:32:24: PM2 log: Application log path : C:\Users\barbu\.pm2\logs
PM2        | 2023-03-01T22:32:24: PM2 log: Worker Interval      : 30000
PM2        | 2023-03-01T22:32:24: PM2 log: Process dump file    : C:\Users\barbu\.pm2\dump.pm2
PM2        | 2023-03-01T22:32:24: PM2 log: SIGTERM timeout      : 1600
PM2        | 2023-03-01T22:32:24: PM2 log: ===============================================================================
PM2        | 2023-03-02T00:09:45: PM2 log: Reloading logs...

``
## How could we reproduce this issue?

I want to deploy a nextJS app, from my local, to a VPS server. 
When i run pm2 deploy production setup 
--> Deploying to production environment
--> on host 89.44.137.23
Deploy failed
spawn sh ENOENT

-------------------
Also my ecosystem.config.js is :
module.exports = {
    apps: [{
        script: 'npm start'
    }],

    deploy : {
        production : {
            key: 'key.pem',
            user : 'root',
            host : ..........',
            ref : 'origin/main',
            repo :'........',
            path : '/home/root',
            'pre-deploy-local': '',
            'post-deploy' : 'source ~/.nvm/nvm.sh && npm install && npm run build && pm2 reload ecosystem.config.js --env production',
            'pre-setup': '',
            'ssh-options': 'ForwardAgent=yes'
        }
    }
}      

## Supporting information

<!--
Please run the following command (available on PM2 >= 2.6)
-->
```
$ pm2 report
```

**Comment by silviu-cpu** [comment]
Also, i have installed pm2.io module, and i found this in logs: 

    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 255,
  signal: null,
  cmd: 'who | grep -v localhost | wc -l'
}
Failed to retrieve process count Error: Command failed: top -bn1 | awk 'NR > 7 && $8 ~ /R|S|D|T/ { print $12 }'
'top' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 255,
  signal: null,
  cmd: "top -bn1 | awk 'NR > 7 && $8 ~ /R|S|D|T/ { print $12 }'"
}
Failed to retrieve zombie process count Error: Command failed: top -bn1 | awk 'NR > 7 && $8 ~ /Z/ { print $12 }'
'top' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 255,
  signal: null,
  cmd: "top -bn1 | awk 'NR > 7 && $8 ~ /Z/ { print $12 }'"
}

**Comment by silviu-cpu** [comment]
It worked from git bash.

**Comment by VesperQuartz** [comment]
How did you solve this?
