### ISSUE TITLE
:: Created by npm, please don't edit manually.

### ISSUE THREAD

**Issue by it4sa** [Unitech/pm2#5571]
## What's going wrong?
I'm following this [details](https://docs.strapi.io/dev-docs/deployment/process-manager) especially the `Start and configure PM2 with a config.js file` part but getting this error, anyone ran into this before?

```
C:\Users\<user>\AppData\Roaming\nvm\v16.15.0\NPM.CMD:1
:: Created by npm, please don't edit manually.
^

SyntaxError: Unexpected token ':'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Object.<anonymous> (C:\Users\<user>\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:33:23)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

## How could we reproduce this issue?
Please follow this [link](https://docs.strapi.io/dev-docs/deployment/process-manager) to reproduce the error. 

Followed this [post](https://github.com/Unitech/pm2/issues/2808) and also posted below but not reply as yet.

## Supporting information
All the information is supplied below.

```
--- PM2 report ----------------------------------------------------------------
Date                 : Thu Mar 16 2023 23:39:51 GMT+0200 (South Africa Standard Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 5.2.2
node version         : 16.15.0
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\<user>\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 96min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 5.2.2
node version         : 16.15.0
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\<user>\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : C:\Program Files\nodejs\node.exe
user                 : <user>
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
cpus nb              : 4
freemem              : 12363161600
totalmem             : 17178693632
home                 : C:\Users\<user>
===============================================================================
--- PM2 list -----------------------------------------------
┌─────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼───────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ server    │ default     │ 0.1.0   │ fork    │ 268824   │ 89m    │ 0    │ online    │ 0%       │ 136.8mb  │ mon… │ disabled │
└─────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
C:\ProgramData\pm2\home\pm2.log last 20 lines:
PM2        |     at God.deleteProcessId (C:\Users\<user>\AppData\Roaming\npm\node_modules\pm2\lib\God\ActionMethods.js:366:9)
PM2        |     at Server.onmessage (C:\Users\<user>\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon-rpc\lib\server.js:104:6)
PM2        |     at RepSocket.emit (node:events:527:28)
PM2        |     at RepSocket.emit (node:domain:475:12)
PM2        |     at Parser.<anonymous> (C:\Users\<user>\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon\lib\sockets\rep.js:51:15)
PM2        |     at Parser.emit (node:events:527:28)
PM2        |     at Parser.emit (node:domain:537:15)
PM2        |     at Parser._write (C:\Users\<user>\AppData\Roaming\npm\node_modules\pm2\node_modules\amp\lib\stream.js:91:16)
PM2        |     at Object.God.logAndGenerateError (C:\Users\<user>\AppData\Roaming\npm\node_modules\pm2\lib\God\Methods.js:34:15)
PM2        |     at C:\Users\<user>\AppData\Roaming\npm\node_modules\pm2\lib\God\ActionMethods.js:367:30
PM2        |     at Object.God.stopProcessId (C:\Users\<user>\AppData\Roaming\npm\node_modules\pm2\lib\God\ActionMethods.js:289:14)
PM2        |     at God.deleteProcessId (C:\Users\<user>\AppData\Roaming\npm\node_modules\pm2\lib\God\ActionMethods.js:366:9)
PM2        |     at Server.onmessage (C:\Users\<user>\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon-rpc\lib\server.js:104:6)
PM2        |     at RepSocket.emit (node:events:527:28)
PM2        |     at RepSocket.emit (node:domain:475:12)
PM2        |     at Parser.<anonymous> (C:\Users\<user>\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon\lib\sockets\rep.js:51:15)
PM2        |     at Parser.emit (node:events:527:28)
PM2        |     at Parser.emit (node:domain:537:15)
PM2        | 2023-03-16T23:30:16: PM2 log: Stopping app:app id:3
PM2        | 2023-03-16T23:30:16: PM2 error: app=app id=3 does not have a pid

```

**Comment by it4sa** [comment]
@Unitech may I ask you for some details on this issue. Thanks!

**Comment by it4sa** [comment]
@keymetrics can you please help on this? Thanks.

**Comment by it4sa** [comment]
@nitinmukesh did you ever resolve your issue in #2808? I ran into the same issue and struggling to get it resolved. Thanks.

**Comment by it4sa** [comment]
Thanks @laminebakelli for your [comment](https://github.com/Unitech/pm2/issues/2808#issuecomment-1510414999) on this issue.

I will follow your suggestions but still not working, got this error now :
![pm2_new_error](https://user-images.githubusercontent.com/51520529/236697205-c9aa0706-b1a6-4018-8df2-9a65a2853c74.png)

May I ask what is the config in your `ecosystem.config.js` file?

**Comment by mistryaksh** [comment]
Did anyone resolve this issue, faced same issue with node project

**Comment by hassaan-AK** [comment]
I am also having the same issue, I was trying to run a simple express app

command:
`pm2 start npm --name "backend" -- run dev`

Error:
```
PM2        | 2024-01-31T12:32:54: PM2 log: Script C:\PROGRAM FILES\NODEJS\NPM.CMD had too many unstable restarts (16). Stopped. "errored"

C:\Users\SCS\.pm2\logs\backend-app-out.log last 15 lines:
C:\Users\SCS\.pm2\logs\backend-app-error.log last 15 lines:
0|backend- | C:\PROGRAM FILES\NODEJS\NPM.CMD:1
0|backend- | :: Created by npm, please don't edit manually.
0|backend- | ^
0|backend- |
0|backend- | SyntaxError: Unexpected token ':'
0|backend- |     at internalCompileFunction (node:internal/vm:77:18)
0|backend- |     at wrapSafe (node:internal/modules/cjs/loader:1288:20)
0|backend- |     at Module._compile (node:internal/modules/cjs/loader:1340:27)
0|backend- |     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
0|backend- |     at Module.load (node:internal/modules/cjs/loader:1207:32)
0|backend- |     at Module._load (node:internal/modules/cjs/loader:1023:12)
0|backend- |     at Object.<anonymous> (C:\Users\SCS\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:33:23)
0|backend- |     at Module._compile (node:internal/modules/cjs/loader:1376:14)
0|backend- |     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
0|backend- |     at Module.load (node:internal/modules/cjs/loader:1207:32)
```

**Comment by hassaan-AK** [comment]
I got it working but it opens up a terminal try it like this 
instead of `npm` use its path.
`pm2 start "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" --name "MultilingualSystem" -- run dev`

**Comment by doppelgunner** [comment]
```
\nvm\v20.15.0\NPM.CMD:1
:: Created by npm, please don't edit manually.
```

**Comment by alcy** [comment]
Same problem when using pm2 with vite (npm run dev). Only the above solution with the full path to npm-cli.js worked, but feels less than ideal.

**Comment by aryomuzakki** [comment]
i'm using nvs, in windows 10 with git bash, and having the same problem.

```sh
C:\Users\matak\AppData\Local\nvs\node\20.10.0\x64\NPM.CMD:1
0|myApp    | :: Created by npm, please don't edit manually.
0|myApp    | ^
0|myApp    | 
0|myApp    | SyntaxError: Unexpected token ':'
0|myApp    |     at internalCompileFunction (node:internal/vm:77:18)
0|myApp    |     at wrapSafe (node:internal/modules/cjs/loader:1288:20)
0|myApp    |     at Module._compile (node:internal/modules/cjs/loader:1340:27)
0|myApp    |     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
0|myApp    |     at Module.load (node:internal/modules/cjs/loader:1207:32)
0|myApp    |     at Module._load (node:internal/modules/cjs/loader:1023:12)
0|myApp    |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
0|myApp    |     at node:internal/main/run_main_module:28:49
0|myApp    | 
0|myApp    | Node.js v20.10.0
```

only this temporary solution by @hassaan-AK  that works

> I got it working but it opens up a terminal try it like this instead of `npm` use its path. `pm2 start "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" --name "MultilingualSystem" -- run dev`

i was first accidently used bun, and it doesnt work, then remove package and reinstall with npm, i wonder if this relevant

**Comment by mdhilwan** [comment]
@aryomuzakki This is how I resolved this:

install node and npm locally into your project so that it's in your package.json

**package.json**
```json
{
   "devDependencies": {
       "node": "^20.19.0",
       "npm": "^10.8.2"
   }
}
```

you should see `node` and `npm` executables / binaries in your `node_modules/.bin` folder.

Update start.config.js with the path to your npm:

start.config.js
```javascript
const path = require("path");
const npmPath = path.resolve(require.resolve("npm"))

module.exports = {
    apps: [
        {
            name: "storybook",
            script: npmPath,
            args: "run start",
        },
    ],
};
```

Works now in mac and windows

**Comment by doppelgunner** [comment]
Cause of error:
- nvm or nvs (pm2 has a problem with version manager/switcher)
```
C:\Users\User\AppData\Roaming\nvm\v22.14.0\NPM.CMD:1
:: Created by npm, please don't edit manually.
```

Here's a workaround:
- build the file first
- don't use npm on ecosystem.config.js 

Here's my package.json script:
```
  "scripts": {
    "build": "tsc -p tsconfig.json",
    "prod": "npm run build && pm2 start"
  },
```

Here's my ecosystem.config.js
```
/* eslint-disable */
module.exports = {
  apps: [
    {
        name: "delete-worker",
        script: "build/src/main.js",
        restart_delay: 100,
        cwd: __dirname,
        env: {
          NODE_ENV: "production"
        }
      }
    ]
};
```
