### ISSUE TITLE
pm2 monit crashes

### ISSUE THREAD

**Issue by cameralis** [Unitech/pm2#5577]
## What's going wrong?
I run pm2 monit while a process is running. When specific text is outputted into the log, monit crashes.

## How could we reproduce this issue?
I honestly have no idea

## Supporting information
```
TypeError: Cannot read properties of null (reading 'slice')
    at /usr/lib/node_modules/pm2/node_modules/blessed/lib/program.js:2543:35
    at Array.forEach (<anonymous>)
    at Program._attr (/usr/lib/node_modules/pm2/node_modules/blessed/lib/program.js:2542:11)
    at Box.Element._parseTags (/usr/lib/node_modules/pm2/node_modules/blessed/lib/widgets/element.js:498:26)
    at Box.Element.parseContent (/usr/lib/node_modules/pm2/node_modules/blessed/lib/widgets/element.js:393:22)
    at Box.<anonymous> (/usr/lib/node_modules/pm2/node_modules/blessed/lib/widgets/element.js:184:10)
    at Box.EventEmitter._emit (/usr/lib/node_modules/pm2/node_modules/blessed/lib/events.js:94:20)
    at Box.EventEmitter.emit (/usr/lib/node_modules/pm2/node_modules/blessed/lib/events.js:117:12)
    at emit (/usr/lib/node_modules/pm2/node_modules/blessed/lib/widgets/node.js:109:15)
    at List.Node.insert (/usr/lib/node_modules/pm2/node_modules/blessed/lib/widgets/node.js:111:5)
   ```

pm2 v5.2.2
node v16.19.1

**Comment by 55nknown** [comment]
Could this be an issue with blessed?

**Comment by jamie0xgitc0decat** [comment]
Same here

**Comment by adrianhelvikspond** [comment]
Same here.

```
❯ pm2 monit

TypeError: Cannot read properties of null (reading 'slice')
    at /Users/adrian.helvik/.volta/tools/image/packages/pm2/lib/node_modules/blessed/lib/program.js:2543:35
    at Array.forEach (<anonymous>)
    at Program._attr (/Users/adrian.helvik/.volta/tools/image/packages/pm2/lib/node_modules/blessed/lib/program.js:2542:11)
    at Element._parseTags (/Users/adrian.helvik/.volta/tools/image/packages/pm2/lib/node_modules/blessed/lib/widgets/element.js:479:26)
    at Element.parseContent (/Users/adrian.helvik/.volta/tools/image/packages/pm2/lib/node_modules/blessed/lib/widgets/element.js:393:22)
    at Box.<anonymous> (/Users/adrian.helvik/.volta/tools/image/packages/pm2/lib/node_modules/blessed/lib/widgets/element.js:184:10)
    at EventEmitter._emit (/Users/adrian.helvik/.volta/tools/image/packages/pm2/lib/node_modules/blessed/lib/events.js:94:20)
    at EventEmitter.emit (/Users/adrian.helvik/.volta/tools/image/packages/pm2/lib/node_modules/blessed/lib/events.js:117:12)
    at emit (/Users/adrian.helvik/.volta/tools/image/packages/pm2/lib/node_modules/blessed/lib/widgets/node.js:109:15)
    at Node.insert (/Users/adrian.helvik/.volta/tools/image/packages/pm2/lib/node_modules/blessed/lib/widgets/node.js:111:5)
```

**Comment by adrianhelvikspond** [comment]
<img width="648" alt="Skjermbilde 2024-03-20 kl  16 56 41" src="https://github.com/Unitech/pm2/assets/117183540/1f1790b7-4b2e-4939-b6b2-41971c3b08d1">

**Comment by adrianhelvikspond** [comment]
Probably an issue with blessed though. I'll see if I can determine what is causing this.

**Comment by adrianhelvik** [comment]
I submitted a PR to blessed to resolve this issue.

https://github.com/chjj/blessed/pull/439

**Comment by Unitech** [comment]
I forked blessed and merged your PR

Could you try it and confirm it has fixed your issue:

```
npm install Unitech/pm2#development -g
pm2 update
```

**Comment by deksden** [comment]
> I forked blessed and merged your PR
> 
> Could you try it and confirm it has fixed your issue:
> 
> ```
> npm install Unitech/pm2#development -g
> pm2 update
> ```

Tried 2 times to reproduce bug with new version - all is ok! Before every 'pm2 restart all' crashes 'pm2 monit'.

So, iI'll keep monitoring and return when i'll have more info

**Comment by Unitech** [comment]
Fixed on PM2 6.0.12:

```
npm install pm2@6.0.12 -g
pm2 update
```
