### ISSUE TITLE
The "options.uid" property must be int32. Received type string ('1000')

### ISSUE THREAD

**Issue by Mapsred** [Unitech/pm2#5656]
## What's going wrong?

```
[PM2] Starting /usr/bin/bash in fork_mode (1 instance)
[PM2][ERROR] Error while launching application TypeError [ERR_INVALID_ARG_TYPE]: The "options.uid" property must be int32. Received type string ('1000')
at new NodeError (node:internal/errors:387:5)
at normalizeSpawnArguments (node:child_process:563:11)
at spawn (node:child_process:726:13)
at /home/fmathieu/Projects/PROJECT/node_modules/pm2/lib/God/ForkMode.js:113:20
at wrapper (/home/fmathieu/Projects/PROJECT/node_modules/async/internal/once.js:12:16)
at next (/home/fmathieu/Projects/PROJECT/node_modules/async/waterfall.js:96:20)
at /home/fmathieu/Projects/PROJECT/node_modules/async/internal/onlyOnce.js:12:16
at WriteStream.<anonymous> (/home/fmathieu/Projects/PROJECT/node_modules/pm2/lib/Utility.js:186:13)
    at WriteStream.emit (node:events:513:28)
    at WriteStream.emit (node:domain:552:15)

```

## How could we reproduce this issue?

```
pm2 start "ls -la"
```

Or any start command

## Supporting information

```
$ pm2 report
```
```
--- PM2 report ----------------------------------------------------------------
Date                 : Thu Aug 17 2023 17:42:20 GMT+0200 (Central European Summer Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 5.3.0
node version         : 16.20.1
node path            : /home/fmathieu/.nvm/versions/node/v16.20.1/bin/npx
argv                 : /home/fmathieu/.nvm/versions/node/v16.20.1/bin/node,/home/fmathieu/Projects/PROJECT/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : fmathieu
uid                  : 1000
gid                  : 1000
uptime               : 57min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 5.3.0
node version         : 16.20.1
node path            : /home/fmathieu/.nvm/versions/node/v16.20.1/bin/npx
argv                 : /home/fmathieu/.nvm/versions/node/v16.20.1/bin/node,/home/fmathieu/Projects/PROJECT/node_modules/.bin/pm2,report
argv0                : node
user                 : fmathieu
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : 13th Gen Intel(R) Core(TM) i7-13700H
cpus nb              : 20
freemem              : 6804668416
totalmem             : 16414769152
home                 : /home/fmathieu
===============================================================================
--- PM2 list -----------------------------------------------
┌────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
└────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
```

**Comment by Mapsred** [comment]
Closed since it was due to already having gid/uid variables in my env
