### ISSUE TITLE
Try catch blocks cause the pm2 app to crash when an exception is caught.

### ISSUE THREAD

**Issue by thavus** [Unitech/pm2#5781]
## What's going wrong?
Try catch blocks cause the pm2 app to crash when an exception is caught when the exception is caused by a folder lookup, where the directory does not exist.

## How could we reproduce this issue?
Use readFileSync from the fs module. This is a synchronous lookup of a file. In my case, I'm using it to look for the certs on the server. If it can't find the certs, then it assumes that the code is running on localhost and starts up the http server for local development.

This actually use to work on Friday, two days ago, and it has been working for over a year.. I did not upgrade any packages. I've started up my PC today to do some development on my app and today, the try catch is complaining that it can't find that folder and is crashing instead of being caught by the try catch.

## Error Log
```
 --- PM2 global error caught ---------------------------------------------------
PM2         | Time                 : Mon Mar 11 2024 14:14:30 GMT-0400 (Eastern Daylight Time)
PM2         | The argument 'path' must be a string or Uint8Array without null bytes. Received 'C:\\Users\\Sean\\Documents\\Ream\\.git\\\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0...
PM2         | TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received 'C:\\Users\\Sean\\Documents\\Ream\\.git\\\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0...
PM2         |     at Object.readFile (node:fs:393:10)
PM2         |     at Object.readFile (C:\Users\Sean\AppData\Roaming\npm\node_modules\pm2\node_modules\git-node-fs\lib\node-fs.js:18:10)
PM2         |     at Object.readRef (C:\Users\Sean\AppData\Roaming\npm\node_modules\pm2\node_modules\js-git\mixins\fs-db.js:62:8)
PM2         |     at resolveRef (C:\Users\Sean\AppData\Roaming\npm\node_modules\pm2\node_modules\js-git\mixins\walkers.js:104:8)
PM2         |     at onShallow (C:\Users\Sean\AppData\Roaming\npm\node_modules\pm2\node_modules\js-git\mixins\walkers.js:18:5)
PM2         |     at C:\Users\Sean\AppData\Roaming\npm\node_modules\pm2\node_modules\js-git\mixins\fs-db.js:89:7
PM2         |     at C:\Users\Sean\AppData\Roaming\npm\node_modules\pm2\node_modules\git-node-fs\lib\node-fs.js:23:12
PM2         |     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
PM2         |     at FSReqCallback.callbackTrampoline (node:internal/async_hooks:130:17)

Error: ENOENT: no such file or directory, open '/var/ssl/website_name_replaced_for_bug_report.com/combined'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at Object.<anonymous> (C:\Users\Sean\Documents\Ream\Service\user\user-app.ts:61:28)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Object.<anonymous> (C:\Users\user_name\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:33:23)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '/var/ssl/website_name_replaced_for_bug_report.com/combined'
}
```

## Supporting information
```
--- Daemon logs --------------------------------------------
C:\Users\Sean\.pm2\pm2.log last 20 lines:
PM2        | 2024-03-11T14:14:38: PM2 log: Stopping app:user-app id:0
PM2        | 2024-03-11T14:14:38: PM2 log: App [user-app:0] exited with code [1] via signal [SIGINT]
PM2        | 2024-03-11T14:14:38: PM2 log: pid=27028 msg=process killed
PM2        | 2024-03-11T14:14:38: PM2 log: PM2 successfully stopped
PM2        | 2024-03-11T14:14:39: PM2 log: ===============================================================================
PM2        | 2024-03-11T14:14:39: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2024-03-11T14:14:39: PM2 log: Time                 : Mon Mar 11 2024 14:14:39 GMT-0400 (Eastern Daylight Time)
PM2        | 2024-03-11T14:14:39: PM2 log: PM2 version          : 5.3.0
PM2        | 2024-03-11T14:14:39: PM2 log: Node.js version      : 16.14.2
PM2        | 2024-03-11T14:14:39: PM2 log: Current arch         : x64
PM2        | 2024-03-11T14:14:39: PM2 log: PM2 home             : C:\Users\Sean\.pm2
PM2        | 2024-03-11T14:14:39: PM2 log: PM2 PID file         : C:\Users\Sean\.pm2\pm2.pid
PM2        | 2024-03-11T14:14:39: PM2 log: RPC socket file      : \\.\pipe\rpc.sock
PM2        | 2024-03-11T14:14:39: PM2 log: BUS socket file      : \\.\pipe\pub.sock
PM2        | 2024-03-11T14:14:39: PM2 log: Application log path : C:\Users\Sean\.pm2\logs
PM2        | 2024-03-11T14:14:39: PM2 log: Worker Interval      : 30000
PM2        | 2024-03-11T14:14:39: PM2 log: Process dump file    : C:\Users\Sean\.pm2\dump.pm2
PM2        | 2024-03-11T14:14:39: PM2 log: Concurrent actions   : 2
PM2        | 2024-03-11T14:14:39: PM2 log: SIGTERM timeout      : 1600
PM2        | 2024-03-11T14:14:39: PM2 log: ===============================================================================
```

**Comment by thavus** [comment]
I think this is more so a problem with the fs package. While it does say the function is synchronous, it seems that the error would indicate that it is not synchronous which would mean the code is erroring outside the context of the try catch block.

**Comment by thavus** [comment]
I tested with an asynchronous lookup on the file which returns a promise. I included a catch on the promise. However even with a catch on the promise AND a try catch block pm2 seems to want to aggressively stop the app from running. Not sure what's going on, but perhaps it's not the fs module.

**Comment by thavus** [comment]
So it's not the FS module at all. I removed that completely and the error persists.

**Comment by thavus** [comment]
I removed my usage of FS and I am still seeing an error.
```
 ===============================================================================
PM2         | --- PM2 global error caught ---------------------------------------------------
PM2         | Time                 : Mon Mar 11 2024 17:07:40 GMT-0400 (Eastern Daylight Time)
PM2         | The argument 'path' must be a string or Uint8Array without null bytes. Received 'C:\\Users\\Sean\\Documents\\Ream\\.git\\\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0...
PM2         | TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received 'C:\\Users\\Sean\\Documents\\Ream\\.git\\\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0...
PM2         |     at Object.readFile (node:fs:393:10)
PM2         |     at Object.readFile (C:\Users\Sean\AppData\Roaming\npm\node_modules\pm2\node_modules\git-node-fs\lib\node-fs.js:18:10)
PM2         |     at Object.readRef (C:\Users\Sean\AppData\Roaming\npm\node_modules\pm2\node_modules\js-git\mixins\fs-db.js:62:8)
PM2         |     at resolveRef (C:\Users\Sean\AppData\Roaming\npm\node_modules\pm2\node_modules\js-git\mixins\walkers.js:104:8)
PM2         |     at onShallow (C:\Users\Sean\AppData\Roaming\npm\node_modules\pm2\node_modules\js-git\mixins\walkers.js:18:5)
PM2         |     at C:\Users\Sean\AppData\Roaming\npm\node_modules\pm2\node_modules\js-git\mixins\fs-db.js:89:7
PM2         |     at C:\Users\Sean\AppData\Roaming\npm\node_modules\pm2\node_modules\git-node-fs\lib\node-fs.js:23:12
PM2         |     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
PM2         |     at FSReqCallback.callbackTrampoline (node:internal/async_hooks:130:17)
PM2         | ===============================================================================
```

**Comment by thavus** [comment]
GOD DAMN I ALREADY REPORTED THIS ISSUE A FEW MONTHS AGO
https://github.com/Unitech/pm2/issues/5696
