### ISSUE TITLE
Pm2 restart error

### ISSUE THREAD

**Issue by puneethgl** [Unitech/pm2#5851]
PM2        |     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:19)
PM2        |     at onErrorNT (internal/child_process.js:472:16)
PM2        |     at processTicksAndRejections (internal/process/task_queues.js:82:21)
PM2        | 2024-07-02T12:42:27: PM2 log: App [ajax-be-002:1] online
PM2        | 2024-07-02T12:42:27: PM2 error: Error: spawn node ENOENT
PM2        |     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:19)
PM2        |     at onErrorNT (internal/child_process.js:472:16)
PM2        |     at processTicksAndRejections (internal/process/task_queues.js:82:21)
PM2        | 2024-07-02T12:42:27: PM2 log: App [ajax-be-003:2] starting in -fork mode-
PM2        | 2024-07-02T12:42:27: PM2 log: Stopping app:ajax-mongo-watch id:3
PM2        | 2024-07-02T12:42:27: PM2 log: App [ajax-be-003:2] online
PM2        | 2024-07-02T12:42:27: PM2 error: Error: spawn node ENOENT
PM2        |     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:19)
PM2        |     at onErrorNT (internal/child_process.js:472:16)
PM2        |     at processTicksAndRejections (internal/process/task_queues.js:82:21)
PM2        | 2024-07-02T12:42:27: PM2 log: App [ajax-mongo-watch:3] exited with code [0] via signal [SIGINT]
PM2        | 2024-07-02T12:42:27: PM2 log: pid=2712578 msg=process killed
PM2        | 2024-07-02T12:42:27: PM2 log: App [ajax-mongo-watch:3] starting in -fork mode-
PM2        | 2024-07-02T12:42:27: PM2 log: App [ajax-mongo-watch:3] online

**Comment by eugene0928** [comment]
can u give more details?
