### ISSUE TITLE
that is undefined within list function in API.js

### ISSUE THREAD

**Issue by Khanon** [Unitech/pm2#5928]
## What's going wrong?
`that` is *undefined* within API.js `list` method

## How could we reproduce this issue?
pm2 version: `5.4.2`

ecosystem.config.json:
```
{
	"apps": [
		{
			"name": "system-manager-service",
			"script": "./dist/services/system-manager-service/main.js",
			"exec_mode": "cluster",
			"instances": "5",
			"watch": true,
			"env": {
			},
			"env_local": {
				"NODE_ENV": "local"
			},
			"env_dev": {
				"NODE_ENV": "dev"
			},
			"env_test": {
				"NODE_ENV": "test"
			},
			"env_www": {
				"NODE_ENV": "www"
			}
		}
	]
}
```

I'm calling `list` method just like this:
```
import {
  list,
  ProcessDescription,
  sendDataToProcessId
} from 'pm2'

...
return new Promise((resolve, reject) => {
  list((error: any, descriptions: ProcessDescription[]) => {
  }
})
...
```

Error:
```
17:23:27 4|system-manager-service  | TypeError: Cannot read properties of undefined (reading 'Client')
17:23:27 4|system-manager-service  |     at list (C:\Projects\system-manager-service\node_modules\pm2\lib\API.js:600:10)
17:23:27 4|system-manager-service  |     at C:\Projects\system-manager-service\dist\services\system-manager-service\main.js:415:32
17:23:27 4|system-manager-service  |     at new Promise (<anonymous>)
17:23:27 4|system-manager-service  |     at PM2.initialize (C:\Projects\system-manager-service\dist\services\system-manager-service\main.js:404:16)
17:23:27 4|system-manager-service  |     at SM.initialize (C:\Projects\system-manager-service\dist\services\system-manager-service\main.js:45:25)
17:23:27 4|system-manager-service  |     at C:\Projects\system-manager-service\dist\services\system-manager-service\main.js:1365:37
17:23:27 4|system-manager-service  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

API.js failing code block (line 600):
```
/**
   * Get list of all processes managed
   *
   * @param {Function} cb Callback
   */
  list (opts, cb) {
    var that = this;

    if (typeof(opts) == 'function') {
      cb = opts;
      opts = null;
    }

    // that is undefined
    that.Client.executeRemote('getMonitorData', {}, function(err, list) {
      if (err) {
        Common.printError(err);
        return cb ? cb(Common.retErr(err)) : that.exitCli(conf.ERROR_EXIT);
      }

```

tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2020", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@a-safe/system-manager-package": ["packages/system-manager-package/src/index.ts"]
    }
  },
  "exclude": ["node_modules", "tmp"]
}

```

**Comment by Khanon** [comment]
This issue is happening if `list` method is being called too fast after the service start. PM2 seems to need a short time after the service start to be ready for this method.
