### ISSUE TITLE
Duplicate Procceses 

### ISSUE THREAD

**Issue by D3ltaa** [Unitech/pm2#5938]
When I try to restart the process using pm2 restart or pm2 reload, it ends up creating duplicate processes. Even if I stop them, they continue running somewhere, and I have to restart the entire server.

Anyone has an idea on that?

**Comment by VikashChoudahry** [comment]
Hi @D3ltaa, Could you please share some more details? I have tried reproducing at my end, it seems to be working fine for me.

**Steps that I followed to reproduce:**
1. Created a simple node.js app.
2. Installed pm2 globally.
3. Start the node.js app using `pm2`.
4. Restarted the process using both `pm2 restart <pid>` or `pm2 reload <pid>`

**Outcome**: Using `pm2 list`, I could see only processing running.

Used versions:
node.js: 16.15.1
pm2: 5.4.3

Thanks!

**Comment by Rohan487** [comment]
#### **Description**  
I'm experiencing a major issue with PM2 where old Node.js processes **aren't being properly terminated before restarting**. This is causing memory leaks and excessive resource usage.  

#### **System Info**  
- **VPS Memory Usage (After Multiple Restarts)**  
  ```
               total        used        free      shared  buff/cache   available
  Mem:           7.6Gi       6.9Gi       182Mi       1.0Mi       560Mi       436Mi
  Swap:             0B          0B          0B
  ```
- **Environment**  
  - PM2 Dashboard used for restarts  
  - Multiple zombie `node` processes found after restart  
  - Old processes **not terminated properly**, leading to extreme memory usage  

#### **Steps to Reproduce**  
1. Start a Node.js process with PM2 (`pm2 start index.js --name myApp`).  
2. Restart it using PM2 Dashboard.  
3. Check running processes (`ps aux | grep node`).  
4. Observe that old `node` processes **are still running**.  

#### **Expected Behavior**  
PM2 should **cleanly restart** the app, terminating old processes before spawning new ones.  

#### **Actual Behavior**  
Every restart **spawns a new process but doesn't kill the old one**, leading to high memory usage and potential system crashes.  

#### **Impact**  
- High **memory consumption**  
- VPS becoming **unresponsive** due to process accumulation  
- Need to **manually kill old processes** (`kill -9 <PID>` every time)

**Comment by D3ltaa** [comment]
> Hi [@D3ltaa](https://github.com/D3ltaa), Could you please share some more details? I have tried reproducing at my end, it seems to be working fine for me.
> 
> **Steps that I followed to reproduce:**
> 
> 1. Created a simple node.js app.
> 2. Installed pm2 globally.
> 3. Start the node.js app using `pm2`.
> 4. Restarted the process using both `pm2 restart <pid>` or `pm2 reload <pid>`
> 
> **Outcome**: Using `pm2 list`, I could see only processing running.
> 
> Used versions: node.js: 16.15.1 pm2: 5.4.3
> 
> Thanks!

Im using latest node.js and pm2 versions. The steps im doing is “pm2 restart <pid>” but in list it dispaing one of each app but it running 2 times in the bg

**Comment by VikashChoudahry** [comment]
> > Hi [@D3ltaa](https://github.com/D3ltaa), Could you please share some more details? I have tried reproducing at my end, it seems to be working fine for me.
> > **Steps that I followed to reproduce:**
> > 
> > 1. Created a simple node.js app.
> > 2. Installed pm2 globally.
> > 3. Start the node.js app using `pm2`.
> > 4. Restarted the process using both `pm2 restart <pid>` or `pm2 reload <pid>`
> > 
> > **Outcome**: Using `pm2 list`, I could see only processing running.
> > Used versions: node.js: 16.15.1 pm2: 5.4.3
> > Thanks!
> 
> Im using latest node.js and pm2 versions. The steps im doing is “pm2 restart ” but in list it dispaing one of each app but it running 2 times in the bg

I see. Let me try re-producing that again.

**Comment by msi-martinsen** [comment]
Any update on this?

**Comment by Unitech** [comment]
**v7.0.0** has been released with significant changes that may have addressed this issue: TreeKill rewrite, Bun runtime support (`ProcessContainerBun.js`, `ProcessContainerForkBun.js`), `[object Object]` env var leak fix, Windows path migration to `os.homedir()`, internalized supply chain (axon/bpm/io-agent/fclone), and several CVE fixes.

Could you retest on 7.0.0 and confirm whether this issue still reproduces?

```bash
# With npm
npm install pm2@latest -g

# Or with bun
bun install pm2@latest -g

# Then reload the daemon and restore your process list
pm2 update
```

Full release notes: https://github.com/Unitech/pm2/releases/tag/v7.0.0

**Comment by drag0n-app** [comment]
> **v7.0.0** has been released with significant changes that may have addressed this issue: TreeKill rewrite, Bun runtime support (`ProcessContainerBun.js`, `ProcessContainerForkBun.js`), `[object Object]` env var leak fix, Windows path migration to `os.homedir()`, internalized supply chain (axon/bpm/io-agent/fclone), and several CVE fixes.
> 
> Could you retest on 7.0.0 and confirm whether this issue still reproduces?
> 
> # With npm
> npm install pm2@latest -g
> 
> # Or with bun
> bun install pm2@latest -g
> 
> # Then reload the daemon and restore your process list
> pm2 update
> Full release notes: https://github.com/Unitech/pm2/releases/tag/v7.0.0

node v26.2.0 + pm2 v7.0.1 test

index.js
```js
import { serve } from '@hono/node-server'
import { Hono } from 'hono'

const app = new Hono()
app.get('/', (c) => c.text('Hello Node.js!'))

serve({ fetch: app.fetch, port: 4321 })
console.log(`Listening at http://localhost:${4321}/`)
```

pm2.config.cjs
```js
module.exports = {
  apps: [
    {
      name: "test",
      script: "./index.js",
      time: true,
    }
  ]
}
```
```shell
npm install && pm2 start pm2.config.cjs
pm2 reload 0  && pm2 logs 0

[TAILING] Tailing last 15 lines for [0] process (change the value with --lines option)
/root/.pm2/logs/test-out.log last 15 lines:
0|test     | 2026-05-22T02:57:17: Listening at http://localhost:4321/
0|test     | 2026-05-22T02:57:17: Listening at http://localhost:4321/
0|test     | 2026-05-22T02:57:17: Listening at http://localhost:4321/
0|test     | 2026-05-22T02:57:17: Listening at http://localhost:4321/
0|test     | 2026-05-22T02:57:17: Listening at http://localhost:4321/
0|test     | 2026-05-22T02:57:18: Listening at http://localhost:4321/
0|test     | 2026-05-22T02:57:18: Listening at http://localhost:4321/
0|test     | 2026-05-22T02:57:18: Listening at http://localhost:4321/
0|test     | 2026-05-22T02:57:18: Listening at http://localhost:4321/
0|test     | 2026-05-22T02:57:18: Listening at http://localhost:4321/
0|test     | 2026-05-22T02:57:18: Listening at http://localhost:4321/
0|test     | 2026-05-22T02:57:18: Listening at http://localhost:4321/
0|test     | 2026-05-22T02:57:18: Listening at http://localhost:4321/
0|test     | 2026-05-22T02:57:18: Listening at http://localhost:4321/
0|test     | 2026-05-22T02:57:18: Listening at http://localhost:4321/

/root/.pm2/logs/test-error.log last 15 lines:
0|test     | 2026-05-22T02:57:18: Error: listen EADDRINUSE: address already in use :::4321
0|test     | 2026-05-22T02:57:18:     at Server.setupListenHandle [as _listen2] (node:net:2008:16)
0|test     | 2026-05-22T02:57:18:     at listenInCluster (node:net:2065:12)
0|test     | 2026-05-22T02:57:18:     at Server.listen (node:net:2170:7)
0|test     | 2026-05-22T02:57:18:     at serve (file:///app/node_modules/@hono/node-server/dist/index.mjs:1031:9)
0|test     | 2026-05-22T02:57:18:     at file:///app/index.js:7:1
0|test     | 2026-05-22T02:57:18:     at ModuleJob.run (node:internal/modules/esm/module_job:439:25)
0|test     | 2026-05-22T02:57:18:     at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
0|test     | 2026-05-22T02:57:18:     at async node:internal/modules/esm/loader:666:26 {
0|test     | 2026-05-22T02:57:18:   code: 'EADDRINUSE',
0|test     | 2026-05-22T02:57:18:   errno: -98,
0|test     | 2026-05-22T02:57:18:   syscall: 'listen',
0|test     | 2026-05-22T02:57:18:   address: '::',
0|test     | 2026-05-22T02:57:18:   port: 4321
0|test     | 2026-05-22T02:57:18: }
```

**Comment by Unitech** [comment]
Thanks for the report.
This has been fixed on pm2@7.0.4

```bash
$ npm install pm2@7.0.4 -g
$ pm2 update
```
