### ISSUE TITLE
pm2 startup gentoo breaks

### ISSUE THREAD

**Issue by clintonskakun** [Unitech/PM2#770]
I ran pm2 startup gentoo on my server ssh and got this:

```
a htdocs # pm2 startup gentoo
[PM2] Generating system init script in /etc/init.d/pm2-init.sh
[PM2] Making script booting at startup...

fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/var/lock/subsys/pm2-init.sh'
    at Object.fs.openSync (fs.js:427:18)
    at Object.CLI.startup (/usr/lib64/node_modules/pm2/lib/CLI.js:477:21)
    at Command.<anonymous> (/usr/lib64/node_modules/pm2/bin/pm2:377:9)
    at Command.listener (/usr/lib64/node_modules/pm2/node_modules/commander/index.js:249:8)
    at Command.EventEmitter.emit (events.js:98:17)
    at Command.parseArgs (/usr/lib64/node_modules/pm2/node_modules/commander/index.js:480:12)
    at Command.parse (/usr/lib64/node_modules/pm2/node_modules/commander/index.js:372:21)
    at /usr/lib64/node_modules/pm2/bin/pm2:135:17
    at /usr/lib64/node_modules/pm2/lib/CLI.js:245:20
    at /usr/lib64/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
```

**Comment by Tjatse** [comment]
fixed? if not, feel free to open this or fire a new one.

**Comment by clintonskakun** [comment]
The current init script doesn't work for rc in gentoo on my VM. I wrote up this script that works on my setup after reboot:

```
#!/sbin/runscript

NAME=pm2
PM2=/usr/lib64/node_modules/pm2/bin/pm2
pidfile=/root/.pm2/pm2.pid
export PATH=/usr/bin:$PATH
export PM2_HOME="/root/.pm2"

depend() {
  need net
  need localmount
  after bootmisc
}

start() {
  ebegin "Starting pm2"

  start-stop-daemon --start --pidfile ${pidfile} --user root:root --exec ${PM2} -- resurrect
}

stop() {
  ebegin "Stopping pm2"

  $PM2 dump
  $PM2 delete all
  $PM2 kill
}
```

Just save that as /etc/init.d/pm2 with a chmod +x and tweak user/group/locations based on your setup.

Hit reboot

On reboot check to make sure your scripts have been started: `pm2 list`

**Comment by despotix** [comment]
Thanks clintonskakun. It worked for my gentoo.
