### ISSUE TITLE
Fails in strict mode

### ISSUE THREAD

**Issue by NekR** [Unitech/pm2#786]
```
stolyar@stolyar-desktop:~$ export PM2_NODE_OPTIONS='--harmony --use-strict'
stolyar@stolyar-desktop:~$ pm2 start .
/usr/local/lib/node_modules/pm2/bin/pm2:318
    if (secret && !public) {
                   ^^^^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:124:16)
    at node.js:842:3
```

**Comment by SoaringTiger** [comment]
use io.js will solve it.
pm2 start koa.js --name spa --interpreter iojs
