### ISSUE TITLE
wkhtmltopdf not working under pm2

### ISSUE THREAD

**Issue by solshark** [Unitech/pm2#884]
Hi,
I've tried to run meteor-based project with pm2. Project uses wkhtmltopdf. If project started by meteor or node directly, pdf generation works fine.
But if project started by pm2 pdf generation doesn't work.
Logs:

```
[teliapdf-4 (err)] emit (events.js:92:17)
[teliapdf-4 (err)]     at emitReadable_ (_stream_readable.js:426:10)
[teliapdf-4 (err)]     at emitReadable (_stream_readable.js:422:5)
[teliapdf-4 (err)]     at readableAddChunk (_stream_readable.js:165:9)
[teliapdf-4 (err)]     at Socket.Readable.push (_stream_readable.js:127:10)
[teliapdf-4 (err)]     at Pipe.onread (net.js:528:21)
[teliapdf-4 (err)] events.js:72
[teliapdf-4 (err)]         throw er; // Unhandled 'error' event
[teliapdf-4 (err)]               ^
[teliapdf-4 (err)] Error: QMetaObject::invokeMethod: No such method WebCore::SocketStreamHandlePrivate::socketSentData()
[teliapdf-4 (err)]     at Socket.<anonymous> (/datastorage/www/node.js/pdftelia/programs/server/npm/classcraft:meteor-wkhtmltopdf/node_modules/wkhtmltopdf/index.js:79:17)
[teliapdf-4 (err)]     at Socket.g (events.js:180:16)
[teliapdf-4 (err)]     at Socket.emit (events.js:95:17)
[teliapdf-4 (err)]     at Socket.<anonymous> (_stream_readable.js:764:14)
[teliapdf-4 (err)]     at Socket.emit (events.js:92:17)
[teliapdf-4 (err)]     at emitReadable_ (_stream_readable.js:426:10)
[teliapdf-4 (err)]     at emitReadable (_stream_readable.js:422:5)
[teliapdf-4 (err)]     at readableAddChunk (_stream_readable.js:165:9)
[teliapdf-4 (err)]     at Socket.Readable.push (_stream_readable.js:127:10)
[teliapdf-4 (err)]     at Pipe.onread (net.js:528:21)
```

**Comment by FromStoneage** [comment]
@solshark are you able to link to the specific issues with wkhtmltopdf ? I'm experiencing a similar issue, in which wkhtmltopdf are constantly timed out.
