### ISSUE TITLE
Wrong drive when reading .pm2 on Windows

### ISSUE THREAD

**Issue by KoltesDigital** [Unitech/pm2#908]
I'm on **Windows 8.1** with **PM2 0.12.3**, my `Users` directory is on `C:`, and I keep my projects on `D:`. On a console, when the working directory is on `D:`, PM2 searches for `D:\Users` instead of `C:\Users`.

```
D:\Projects\foobar> pm2 monit

fs.js:653
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: ENOENT, no such file or directory 'D:\Users\username\.pm2'
    at Object.fs.mkdirSync (fs.js:653:18)
    at Object.CLI.pm2Init (C:\Users\username\AppData\Roaming\npm\node_modules\pm2\lib\CLI.js:34:8)
    at Object.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\pm2\bin\pm2:19:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

In the meantime, a workaround is

```
mklink /J D:\Users C:\Users
```

**Comment by akotranza** [comment]
This shouldn't be closed. It's obnoxious to require "c:\pm2 start e:\absolute\path\to\something\far\away.js" or janky symbolic link workarounds.
