### ISSUE TITLE
PM2 will be killed when get error Error: channel closed

### ISSUE THREAD

**Issue by gse7en2012** [Unitech/PM2#947]
I got the error twice today when using pm2 in production server(ubuntu 14.04). the log shows:

    2015-01-19 09:59:50: App name:weicai-api id:22 online
    2015-01-19 09:59:50: App name:weicai-api id:17 online
    2015-01-19 09:59:50: App name:weicai-api id:19 online
    2015-01-19 09:59:50: App name:weicai-api id:20 online
    2015-01-19 09:59:50: Error: channel closed
        at ChildProcess.target.send (child_process.js:413:26)
        at sendHelper (cluster.js:597:8)
        at RoundRobinHandle.handoff (cluster.js:178:3)
        at RoundRobinHandle.distribute (cluster.js:164:20)
    2015-01-19 10:00:03: [PM2][WORKER] Started with refreshing interval: 30000
    2015-01-19 10:00:03: [[[[ PM2/God daemon launched ]]]]
    2015-01-19 10:00:03: BUS system [READY] on port /root/.pm2/pub.sock
    2015-01-19 10:00:03: RPC interface [READY] on port /root/.pm2/rpc.sock
    2015-01-19 10:00:38: PM2 is being killed via kill method
    2015-01-19 10:00:38: RPC socket closed
    2015-01-19 10:00:38: PUB socket closed
    2015-01-19 10:00:39: [PM2][WORKER] Started with refreshing interval: 30000
    2015-01-19 10:00:39: [[[[ PM2/God daemon launched ]]]]
    2015-01-19 10:00:39: BUS system [READY] on port /root/.pm2/pub.sock
    2015-01-19 10:00:39: RPC interface [READY] on port /root/.pm2/rpc.sock

and 

    2015-01-19 14:33:46: App name:weicai-api id:10 online
    2015-01-19 14:33:46: App name:weicai-api id:0 online
    2015-01-19 14:33:46: App name:weicai-api id:20 online
    2015-01-19 14:33:46: App name:weicai-api id:6 online
    2015-01-19 14:33:46: Error: channel closed
        at ChildProcess.target.send (child_process.js:413:26)
        at sendHelper (cluster.js:597:8)
        at RoundRobinHandle.handoff (cluster.js:178:3)
        at RoundRobinHandle.distribute (cluster.js:164:20)
    2015-01-19 14:35:59: [PM2][WORKER] Started with refreshing interval: 30000
    2015-01-19 14:35:59: [[[[ PM2/God daemon launched ]]]]
    2015-01-19 14:35:59: BUS system [READY] on port /root/.pm2/pub.sock
    2015-01-19 14:35:59: RPC interface [READY] on port /root/.pm2/rpc.sock
    
I find out that before this error happened,4 pm2 instance restarted at the same time(I have 24 instance in cluster mode for app.js).Is that one of the reason?  
My Node version is v0.11.12, pm2 version is v0.12.3.  After this error, all pm2 instance were be killed. and i have to run the pm2 deamon myself.  
May you  provide some helps or solutions ? thank you.

**Comment by Tjatse** [comment]
#912 
There're too many bugs with Cluster Module, although it has been rewrote many times.

**Comment by gse7en2012** [comment]
thanks

**Comment by vijaybarnwal** [comment]
Hi,

I also got this issue so many times on production with cluster mode on 0.12.4. 

I am so worry why after some times pm2.log shows error as channel closed and kill my application.

Please help.

Thanks,
Vijay
