### ISSUE TITLE
"Cannot find module" error is not logged in cluster mode

### ISSUE THREAD

**Issue by Jokero** [Unitech/PM2#951]
OS: Ubuntu 14.04.1 LTS
node: 0.11.14
pm2: 0.12.3

I have one line in app.js:
```javascript
var logger = require('logger'); // does not exist
```
Start process in fork mode:
```javascript
pm2 start app.js
```

There is error description in logs:
```
Error: Cannot find module 'logger'
at Function.Module._resolveFilename (module.js:336:15)
at Function.Module._load (module.js:278:25)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object. (/home/ubuntu/dev/app.js:1:63)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:501:10)
```

Now try to start in cluster mode:
```javascript
pm2 start app.js -i 0
```

And all logs:
```
########### Starting streaming logs for [all] process
PM2: 2015-01-19 14:45:49: App name:app id:10 exited
PM2: 2015-01-19 14:45:49: Starting execution sequence in -cluster mode- for app name:app id:10
PM2: 2015-01-19 14:45:49: App name:app id:9 online
PM2: 2015-01-19 14:45:49: App name:app id:10 online
PM2: 2015-01-19 14:45:49: App name:app id:9 exited
PM2: 2015-01-19 14:45:49: Starting execution sequence in -cluster mode- for app name:app id:9
PM2: 2015-01-19 14:45:49: App name:app id:10 exited
PM2: 2015-01-19 14:45:49: Starting execution sequence in -cluster mode- for app name:app id:10
PM2: 2015-01-19 14:45:49: App name:app id:9 online
PM2: 2015-01-19 14:45:49: App name:app id:10 online
PM2: 2015-01-19 14:45:49: App name:app id:9 exited
PM2: 2015-01-19 14:45:49: Starting execution sequence in -cluster mode- for app name:app id:9
PM2: 2015-01-19 14:45:49: App name:app id:10 exited
PM2: 2015-01-19 14:45:49: Starting execution sequence in -cluster mode- for app name:app id:10
PM2: 2015-01-19 14:45:49: App name:app id:9 online
PM2: 2015-01-19 14:45:49: App name:app id:10 online
PM2: 2015-01-19 14:45:49: App name:app id:9 exited
PM2: 2015-01-19 14:45:49: Script /home/ubuntu/dev/app.js had too many unstable restarts (15). Stopped. "errored"
PM2: 2015-01-19 14:45:49: App name:app id:10 exited
PM2: 2015-01-19 14:45:49: Script /home/ubuntu/dev/app.js had too many unstable restarts (15). Stopped. "errored"
```

Nothing about error...

In real app I use NODE_PATH and can't understand why application does not start. NODE_PATH is not used by app and module is not loaded though it exists. Very strange

**Comment by Jokero** [comment]
I tried to use NODE_PATH with node cluster module and it works. But if I use "pm2 start app.js -i 0" app does not run

**Comment by soyuka** [comment]
Are you trying to request a global module?
Le ven. 23 janv. 2015 à 15:19, Dmitry Kirilyuk <notifications@github.com> a
écrit :

**Comment by DmitryGeometria** [comment]
Cluster? I used built-in module

**Comment by soyuka** [comment]
My bad, misread the logs.


Le ven. 23 janv. 2015 à 17:11, DmitryGeometria <notifications@github.com> a
écrit :

**Comment by Unitech** [comment]
I confirm the bug.
It happens because stds[].write is not defined (one added a console.error on the catch statement).
https://github.com/Unitech/PM2/blob/master/lib/ProcessContainer.js#L159

@Tjatse would you mind to have a fast check on this code section?

Thanks
