### ISSUE TITLE
Every command I run results in Error: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by duro** [Unitech/PM2#954]
I have tired installing locally and using `npm run` as well as globally, and even running `pm2 list` results in this error.

```
path.js:313
        throw new TypeError('Arguments to path.resolve must be strings');
              ^
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/constants.js:16:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Satan.js:16:15)
    at Module._compile (module.js:456:26)
```

I am running node version `v0.10.35` and npm `2.1.18`

At a loss for why this might be occurring. Any thoughts on how I could debug.

**Comment by duro** [comment]
Looks like my problem was that my HOME env var was not set (as I was running this inside a pretty lean Docker container).

That being said, perhaps a more meaningful Error message could be output for this case.
