### ISSUE TITLE
PM2 crashes or does not start on Ubuntu

### ISSUE THREAD

**Issue by perminder-klair** [Unitech/PM2#975]
Hello,

I have 2 processes running on my Ubuntu, I did pm2 save / pm2 dump
Also added startup script.

But randomly pm2 shuts down and does not start my processes.

When I did `tail -n 150 ~/.pm2/pm2.log`

It gives following result:

```
2015-01-28 15:37:07: [PM2][WORKER] Started with refreshing interval: 30000                                             
2015-01-28 15:37:07: [[[[ PM2/God daemon launched ]]]]                                                                 
2015-01-28 15:37:07: BUS system [READY] on port /root/.pm2/pub.sock                                                    
2015-01-28 15:37:07: RPC interface [READY] on port /root/.pm2/rpc.sock                                                 
2015-01-28 15:37:13: Starting execution sequence in -fork mode- for app name:DigitalAholic id:0                        
2015-01-28 15:37:13: App name:DigitalAholic id:0 online                                                                
2015-01-28 23:40:40: Error: spawn ENOMEM                                                                               
    at errnoException (child_process.js:1001:11)                                                                       
    at ChildProcess.spawn (child_process.js:948:11)                                                                    
    at exports.spawn (child_process.js:736:9)                                                                          
    at Object.exports.execFile (child_process.js:618:15)                                                               
    at exports.exec (child_process.js:589:18)                                                                          
    at getUrl (/usr/lib/node_modules/pm2/node_modules/vizion/lib/git.js:15:5)                                          
    at fn (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:641:34)                                           
    at Object._onImmediate (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:557:34)                          
    at processImmediate [as _immediateCallback] (timers.js:345:15)                                                     
2015-01-29 05:42:07: [PM2][WORKER] Started with refreshing interval: 
```

**Comment by soyuka** [comment]
You're running out of memory.

**Comment by perminder-klair** [comment]
Thanks @soyuka how you find out I am out of memory?

**Comment by soyuka** [comment]
`2015-01-28 23:40:40: Error: spawn ENOMEM` && [http://lmgtfy.com/?q=ENOMEM+nodejs](Google ENOMEM+nodejs)

**Comment by perminder-klair** [comment]
thanks @soyuka just upgraded RAM on my machine. let's see. 

Many thanks again.

**Comment by yeiniel** [comment]
Yes but even if you run out of memory PM2 should restart the process. I have the same problem and i need that PM2 restart my process on this specific type of crash. Is there any way to achieve that?

**Comment by jshkurti** [comment]
@yeiniel are you using PM2 v0.12.15 ? If yes, can you show me some `~/.pm2/pm2.log` lines around the moment the crash occured ?

**Comment by yeiniel** [comment]
I'm using version 0.12.9

**Comment by jshkurti** [comment]
I highly suggest you to upgrade to the latest version.
Also, you can disable vizion (versioning metadata parser) feature when you start an app with the flag `--no-vizion` (which is causing the out of memory error in this situation)

**Comment by yeiniel** [comment]
OK, let me try. Thanks for the fast response. Great job you are doing. Thanks again.

**Comment by yeiniel** [comment]
The server crashed again. Here some lines around the crash

aiceweb-site-0 (out):      roles: [ 'agent' ],
aiceweb-site-0 (out):      telephone: null,
aiceweb-site-0 (out):      timeout: 60,
aiceweb-site-0 (out):      timeout_enabled: true,
aiceweb-site-0 (out):      title: null,
aiceweb-site-0 (out):      role: [ 'agent' ] } }
aiceweb-site-0 (out): 192.168.1.173 - - [21/May/2015:17:49:51 +0000] "POST /api/v1/ProcessManager/receiveFromCollector HTTP/1.1" 200 20 "-" "Mozilla/5.0"
PM2: child_process.js:1155
PM2:     throw errnoException(err, 'spawn');
PM2:           ^
PM2: Error: spawn ENOMEM
PM2:     at exports._errnoException (util.js:746:11)
PM2:     at ChildProcess.spawn (child_process.js:1155:11)
PM2:     at exports.spawn (child_process.js:988:9)
PM2:     at Object.exports.execFile (child_process.js:682:15)
PM2:     at exports.exec (child_process.js:642:18)
PM2:     at getRemote (/usr/lib/node_modules/pm2/node_modules/vizion/lib/git.js:62:5)
PM2:     at fn (/usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:641:34)
PM2:     at Immediate._onImmediate (/usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:557:34)
PM2:     at processImmediate [as _immediateCallback] (timers.js:358:17)
PM2: 2015-05-21 13:52:07: [PM2][WORKER] Started with refreshing interval: 30000
PM2: 2015-05-21 13:52:07: [[[[ PM2/God daemon launched ]]]]
PM2: 2015-05-21 13:52:07: BUS system [READY] on port /root/.pm2/pub.sock
PM2: 2015-05-21 13:52:07: RPC interface [READY] on port /root/.pm2/rpc.sock

**Comment by yeiniel** [comment]
I'm triying with the --no-vizion option to see what happen.

**Comment by franciskim** [comment]
Same issue here:

```
2015-05-21 14:59:01: App name:readee-get-social-shares id:2 online

child_process.js:935
    throw errnoException(process._errno, 'spawn');
          ^
Error: spawn ENOMEM
    at errnoException (child_process.js:988:11)
    at ChildProcess.spawn (child_process.js:935:11)
    at exports.spawn (child_process.js:723:9)
    at Object.exports.execFile (child_process.js:607:15)
    at exports.exec (child_process.js:578:18)
    at getUrl (/usr/local/lib/node_modules/pm2/node_modules/vizion/lib/git.js:17:5)
    at fn (/usr/local/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/usr/local/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
2015-05-22 01:34:58: [PM2][WORKER] Started with refreshing interval: 30000
2015-05-22 01:34:58: [[[[ PM2/God daemon launched ]]]]
```

Doesn't start until I manually restart it with resurrect. On Ubuntu 14.04.2 LTS on Amazon EC2. Is there a workaround, with the ping option?

**Comment by jshkurti** [comment]
How many RAM do you have on your machine ?

**Comment by jshkurti** [comment]
PM2 uses between 60MB (no applications launched) and ~130MB (a lot of apps running).
That is really not much of a memory footprint.

**Comment by franciskim** [comment]
I have 2GB of ram, I've created a shell script that uses pm2 ping as a workaround for now.

**Comment by jshkurti** [comment]
PM2 v0.12.16 is released. This bug shouldn't happen anymore. At least it won't crash PM2 if ENOMEM occurs.

https://github.com/Unitech/PM2/releases/tag/0.12.16

**Comment by pushpendragzb** [comment]
a
