### ISSUE TITLE
pm2 cannot restart process when you remove the log file!

### ISSUE THREAD

**Issue by zj8487** [Unitech/PM2#977]
**reproduce process.**

**step 1**: pm2 start your server

**step 2**: remove the logs for your server

**step 3**: pm2 stop XX && pm2 start XX

you will see the following error:
```
[PM2] [ERROR] script not found :*/logs/xxxxx
Error: script not found : */logs/xxxxx
    at resolvePaths (/usr/local/lib/node_modules/pm2/lib/CLI.js:1545:11)
    at /usr/local/lib/node_modules/pm2/lib/CLI.js:132:28
    at /usr/local/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (events.js:95:17)
    at Parser._write (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:282:12)
    at writeOrBuffer (_stream_writable.js:269:5)
    at Parser.Writable.write (_stream_writable.js:198:11)
    at Socket.ondata (_stream_readable.js:520:20)
```

**Comment by SeungHam** [comment]
u need it must use pm2 delete XXX&& pm2 start XXX 

on and after pm2 start cant not change config so delete process and restart process

**Comment by zj8487** [comment]
thanks a lot

**Comment by zj8487** [comment]
@SeungHam  i think we should review it again for one more scene.

1. we use log4js datefine type.
2.new day start, but the server has not log one record this day. so there is no log file for the new day.
3. pm2 stop XX && pm2 start XX

4.same thing happen again.

**Comment by SeungHam** [comment]
if you will generator a log file everday, you must use lograte.

pm2 haven't this fuction. 

you don't want cron or other process for a log file everday. 

just you separate a log when restart server. 

in this way pm2 delete XX && pm2 start XX.

so stored as the starting time based on a logfile.
