### ISSUE TITLE
TypeError: Object #<ChildProcess> has no method 'disconnect'

### ISSUE THREAD

**Issue by cayasso** [Unitech/PM2#990]
I am getting this error message running `$ pm2 flush`  while client is tailing logs.

```
usr/local/lib/node_modules/pm2/lib/Log.js:94
    tail.disconnect();
         ^
TypeError: Object #<ChildProcess> has no method 'disconnect'
    at Socket.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Log.js:94:10)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable (_stream_readable.js:406:5)
    at readableAddChunk (_stream_readable.js:168:9)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at Pipe.onread (net.js:528:21)
```

**Comment by Unitech** [comment]
Which Node.js version?

**Comment by cayasso** [comment]
@Unitech I am using:
Node v0.10.29
npm@1.4.14
pm2@0.12.4

**Comment by platbr** [comment]
Same issue here.
[root@localhost crawler]# node -v
v0.12.0
[root@localhost crawler]# pm2 -v
0.12.5
[root@localhost crawler]# npm -v
2.5.1

**Comment by jshkurti** [comment]
Fixed : https://github.com/Unitech/PM2/commit/4e579a76b80334147f581b3929d7b7629079d9d9

Thanks for the feedback :)

**Comment by cayasso** [comment]
Awesome!!!!
